### ISSUE TITLE
change "teen program eligible" to "transition aged youth"

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#100]
part of epic #59 

**What type of user is this for? [volunteer/supervisor/admin/all]** 
all

**Where does/should this occur?**
Everywhere `casa_case` details display

**Description**
"teen program eligible" should be changed to "transition aged youth" everywhere - from the *database* to anywhere it appears on the *front* *end*. 

**Screenshots**
<img width="1247" alt="teen_program_eligible" src="https://user-images.githubusercontent.com/62810851/79703263-81d5d500-825f-11ea-83c2-bcd053c9dd74.png">

**Comment by compwron** [comment]
When changing the database, remember to not lose data (this is good practice for when we're in prod)
