### ISSUE TITLE
Fix funky UI for case details on narrow screen

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1003]
Fix funky UI for case details on narrow screen
https://casa-qa.herokuapp.com/casa_cases/101
![Screen Shot 2020-10-07 at 6 29 54 PM](https://user-images.githubusercontent.com/578159/95404927-34135e80-08cb-11eb-8b91-e4aae4e7a62e.png)

**Comment by Mozart2234** [comment]
I'm working on this issue
