### ISSUE TITLE
Do not show contact type groups without visible contact types 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1004]
**What type of user is this for? volunteer/supervisor/admin/all**
All (any user who can create a case contact) volunteer/supervisor/admin

**Description**
Do not show contact type groups without visible contact types (this includes contact type groups which only have *hidden* contact types)

**Screenshots of current behavior, if any**
![Screen Shot 2020-10-07 at 6 44 28 PM](https://user-images.githubusercontent.com/578159/95405728-69b94700-08cd-11eb-8aa1-beb7960c30cc.png)

**Comment by compwron** [comment]
Robin will work on this

**Comment by compwron** [comment]
@ rtkimz is working on this

**Comment by big-meel** [comment]
Is this fixed? I would love to work on this

**Comment by compwron** [comment]
@big-meel This is not fixed yet, but it is assigned to @rtkimz so you should not work on it. 
https://github.com/rubyforgood/casa/issues/881 is available, you could work on that instead :) If you want to work on it, comment on it "I am working on this" :)
If you want help with getting the repo set up locally or advice etc feel free to ask here or in slack in the #casa channel in https://rubyforgood.herokuapp.com/

**Comment by big-meel** [comment]
@compwron Ok thanks. Going to take a look at it now

**Comment by compwron** [comment]
@rtkimz 
You can replicate this problem by adding a new case contact group without any contact types in it

1. Log in as admin and click “edit organization” to get to https://casa-qa.herokuapp.com/casa_orgs/7/edit
1. click “new group” and make a group
1. open up the “new case contact” page for any case and see the new empty group (when this issue is completed, the empty group will not be visible unless there are contact types in that group)
<img width="1321" alt="Screen Shot 2020-10-14 at 5 22 06 PM" src="https://user-images.githubusercontent.com/578159/96059163-10f42c00-0e42-11eb-82f2-8df4365cb699.png">
