### ISSUE TITLE
deactivated unactivated admin sees wrong message

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1008]
**What is the problem, and what should happen instead?**
When an admin who has never activated their account is deactivated, the message they see when they try to log in is 

**Screenshots of current behavior, if any**
![Screen Shot 2020-10-07 at 7 15 23 PM](https://user-images.githubusercontent.com/578159/95407293-7b045280-08d1-11eb-8713-8045105aa5d7.png)

**Comment by littleforest** [comment]
@compwron should they see a message that their account was deactivated, or just get an invalid email/password notice?

**Comment by compwron** [comment]
@littleforest They should see a account deactivated message similar to the text in https://github.com/rubyforgood/casa/blob/master/app/views/casa_admin_mailer/deactivation.html.erb
This will be set in https://github.com/rubyforgood/casa/blob/master/config/locales/devise_invitable.en.yml

**Comment by ChaelCodes** [comment]
I deactivated admin2 in the Rails console and I'm seeing this error message when trying to log in:
![image](https://user-images.githubusercontent.com/8124558/97112908-5aa00a80-16bd-11eb-99ba-faa718d74dca.png)

**Comment by littleforest** [comment]
The current banner text is for volunteers that have been deactivated. The correct banner should have text similar to the deactivated text for admins:

```
# config/locales/en.yml

admin_self_deactivated: "Your account is currently inactive. Please contact your CASA administrator for more details."
```

Though this message should be put in the [Devise invitable locale file](https://github.com/rubyforgood/casa/blob/master/config/locales/devise_invitable.en.yml).

**Comment by compwron** [comment]
@CovenantHuman When you have time, can you check if this is still an issue?

**Comment by CovenantHuman** [comment]
@compwron I just made and deactivated a new admin and I got the pending invitation message when I tried to log in as the unactivated deactivated admin. So, yes, it's still happening.

**Comment by compwron** [comment]
Closing as unreplicable
