### ISSUE TITLE
Make invalid formatting import error formatting nicer

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1012]
**What type of user is this for? volunteer/supervisor/admin/all**
admin, supervisor

**Description**

This should not have the `[]` pr the `"` but should still be all on one line. 

It should look like 
`Expected Header: display_name, email`
not
`Expected Header: ["display_name", "email"].`

**Screenshots of current behavior, if any**
![Screen Shot 2020-10-07 at 7 48 02 PM](https://user-images.githubusercontent.com/578159/95409285-231c1a80-08d6-11eb-9046-8f4be3b7b68f.png)

**Comment by Mozart2234** [comment]
I'm working on this issue.
