### ISSUE TITLE
Case contact report - starting from should be before ending at

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1014]
**What type of user is this for? volunteer/supervisor/admin/all**
casa admin

**Description**
Case contact report - starting from should be before ending at
This did download a report that contained many records. That seems odd. 

**Screenshots of current behavior, if any**
![Screen Shot 2020-10-07 at 7 56 51 PM](https://user-images.githubusercontent.com/578159/95409861-76db3380-08d7-11eb-842d-c7db5ac9470e.png)

**Comment by sarslanoglu** [comment]
@compwron I can work on this one!

**Comment by sarslanoglu** [comment]
@compwron I can work on this one!
