### ISSUE TITLE
Users can configure their communication preferences

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1016]
Part of epic #1017, dependent on #1785 

AS a **volunteer/supervisor/admin**,
I WANT to be able to customize my communication preferences,
SO THAT I receive notifications through the channels I wish to receive them.

Dev note: add a user_preferences lazy-initialize db table rows, or what works

### How it works now
There is currently no place for any user to configure communication preferences since the only channel for receiving notifications was email up until #1017. 

### How it should work
Users should have the option of selecting the channels through which they'd like to receive notifications (at least one channel must be selected). 
It should look something like this:
![Screen Shot 2021-02-25 at 6 16 44 PM (2)](https://user-images.githubusercontent.com/62810851/109246104-7ebc4700-7796-11eb-95e2-a193f9b94b11.png)

### Acceptance criteria
- [x] There is a new section called "Communication Preferences" under "Edit Profile"
- [x] There is instructional text in this section reading: _Tell us how you'd like to receive notifications._
- [x] There are two options with corresponding checkboxes in this section:
   - [x] Email me
   - [x] Text me
- [x] Beneath these options is a button "Save Preferences" that when clicked, will update communication preferences. 
- [x] If a user selects "Save Preferences" without selecting one option, a dialogue box appears, reading:
_One option must be selected._ with the button "okay". Clicking the button closes the dialogue box and returns the user to the same screen.

**Comment by seanmarcia** [comment]
Should there be a third option on how to receive communications? Something like,


Tell us how you'd like to receive communications:

- [ ]  E-mail me
- [ ]  Text me
- [ ]  Both E-mail and Text

**Comment by compwron** [comment]
We still want this :)

**Comment by compwron** [comment]
This is not in prod yet
