### ISSUE TITLE
In Case Contacts page, table cells should not contain header names

### ISSUE THREAD

**Issue by erik-trantt** [rubyforgood/casa#1020]
**What is the problem, and what should happen instead?**
As a Volunteer, when visiting "Case Contact", I'm seeing table header names showing up in table cells.

I think the headers should ***not be shown*** in table cells.

**Screenshots of current behavior, if any**
![image](https://user-images.githubusercontent.com/44339322/95412784-77c2a280-0975-11eb-97d4-e05b0f3e5d88.png)

**Comment by compwron** [comment]
Oh yikes that is weird. Yes that is a bug.

**Comment by keithrbennett** [comment]
![casa-wide-window-render-error](https://user-images.githubusercontent.com/28410/95667902-6080e200-0b3a-11eb-98be-0465884a9101.png)

Hi, when logging in as volunteer1@example.com with the sample data I am experiencing render errors when increasing the browser window width beyond a certain point (see image). Do you still see this after your change? (My image is from master without your change.) I can create another issue for this, but if your change fixes this, there's no need to.
