### ISSUE TITLE
Case Contacts page text is not vertically aligned correctly when the window is wide

### ISSUE THREAD

**Issue by keithrbennett** [rubyforgood/casa#1038]
**What is the problem, and what should happen instead?**

On the Case Contacts page, when the window is wide, the data is not vertically aligned with the column headings. It shifts to the right. To reproduce, log in to dev seeded application as volunteer1@example.com (you can use `bin/login 1` to do this), select "Case Contacts", and increase window width continuously until you see this effect.

**Screenshots of current behavior, if any**

![image](https://user-images.githubusercontent.com/28410/95685358-6d96e300-0bc5-11eb-9a39-5e3966ede192.png)

**Comment by carterrwood** [comment]
Hi! I'd like to look into this if someone could assign it to me :)
