### ISSUE TITLE
Publish test coverage data to codeclimate

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1040]
**Description**
Publish test coverage data to codeclimate
https://codeclimate.com/github/rubyforgood/casa/progress/coverage
https://docs.codeclimate.com/docs/configuring-test-coverage

**Screenshots of current behavior, if any**
![Screen Shot 2020-10-11 at 10 42 34 AM](https://user-images.githubusercontent.com/578159/95685735-8d6edc80-0bae-11eb-82ed-bc3200604280.png)

**Comment by cassianoblonski** [comment]
@compwron check my PR and read about the repo env var so we can test and review
