### ISSUE TITLE
Speed up test suite

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1042]
The tests take ~4 min on my laptop and ~6 min on travis. CASA is a small project and we can probably improve this. :) 
https://travis-ci.com/github/rubyforgood/casa/builds
<img width="1130" alt="Screen Shot 2020-10-11 at 11 07 23 AM" src="https://user-images.githubusercontent.com/578159/95686338-00c61d80-0bb2-11eb-95fe-f83ade1885a1.png">

Some resources which might provide inspiration:

https://medium.com/appaloosa-store-engineering/tips-to-improve-speed-of-your-test-suite-8418b485205c
https://rollout.io/blog/faster-rails-tests/
https://www.youtube.com/watch?v=q52n4p0wkIs
https://thoughtbot.com/blog/debugging-why-your-specs-have-slowed-down
https://relishapp.com/rspec/rspec-core/docs/configuration/profile-examples
https://github.com/test-prof/test-prof
https://github.com/discourse/discourse/pull/7414
https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/14370
https://github.com/test-prof/test-prof/issues/73
https://medium.com/appaloosa-store-engineering/
https://rollout.io/blog/rails-speed-up-tests/
https://goiabada.blog/improving-spec-speed-in-a-huge-old-rails-app-8f3ab05a33f9
https://kellysutton.com/2020/05/18/speeding-up-a-rails-continuous-integration-pipeline.html
https://jtway.co/speed-up-your-rails-test-suite-by-6-in-1-line-13fedb869ec4
https://chaione.com/blog/increase-performance-rspec-tests/
https://gist.github.com/kddeisz/66f2e7749535f30f868d36021056fd15
https://davidlaprade.github.io/speed-up-rails-tests
https://stackoverflow.com/questions/3663075/speeding-up-rspec-tests-in-a-large-rails-application
https://github.com/sporkrb/spork

**Comment by jimnanney** [comment]
I'm looking at the db_seed_spec  and I'm curious as to what value those tests are providing? I can speed the tests up by a few minutes by running the before blocks as before(:all) instead, but the tests don't specify much and really don't appear to show any value.

**Comment by littleforest** [comment]
@jimnanney we would like to have a test to run the seeds file to make sure it isn't broken when new developers try to get their environment being set up, and that it works correctly when we go to reseed staging. That being said, we definitely need to figure out a way to get rid of this staging seed test that creates 150+ records! Task #1089 has been created in order to combine the seeds files. Maybe the best thing to do is use some constants in #1089 that can then be stubbed (to a small value!) in the tests.

**Comment by jimnanney** [comment]
```
Top 10 slowest examples (158.94 seconds, 50.0% of total time):
  db:seed #staging seed file creates a CasaCase 
    28.96 seconds ./spec/lib/db_seed_spec.rb:28
  Seeds for environment: staging executes without raising an exception                                                                                                                       
    27.1 seconds ./spec/seeds/seeds_spec.rb:12
  db:seed #staging seed file creates a Supervisor                                                                                                                                            
    26.02 seconds ./spec/lib/db_seed_spec.rb:36
  db:seed #staging seed file creates a Volunteer
    24.91 seconds ./spec/lib/db_seed_spec.rb:32
  Seeds for environment: qa executes without raising an exception
    24.86 seconds ./spec/seeds/seeds_spec.rb:12
  Search history should clean after I navigate away from volunteers view is expected to eq ""
    7.46 seconds ./spec/system/search_history_clean_after_navigate_away_volunteer_table_spec.rb:7
  admin adds a new case when all fields are filled is successful
    5.4 seconds ./spec/system/admin_adds_new_case_spec.rb:17
  supervisor edits case edits case
    5.28 seconds ./spec/system/supervisor_edits_case_spec.rb:16
  admin adds a new case when non-mandatory fields are not filled is successful
    4.89 seconds ./spec/system/admin_adds_new_case_spec.rb:41
  volunteer edits case edits case
    4.07 seconds ./spec/system/volunteer_edits_case_spec.rb:24
```

**Comment by jimnanney** [comment]
Seeds not throwing an error seems to be something that should be caught at the build pipeline stage rather than the test suite stage.

**Comment by jimnanney** [comment]
I'm trying to combine the lib/db_seeds_spec tests and the seeds/seeds spec, maybe that will shave a bit of time off the tests.  It still feels more relevant to catch those in the build pipeline rather than the test suite. new people should always start with master branch, and if master passes ci, then it should also pass for new users.

**Comment by jimnanney** [comment]
I'll leave the db seeds stuff for that other ticket and try to speed up the rest.  The seeds tests account for 55% of the tests runtime, so that will be the biggest win.

**Comment by littleforest** [comment]
@jimnanney  the issue is that database fields get renamed, models get deleted etc., but the seed file doesn't get updated along with those changes. In this way the seed file would get flagged to get updated when the seed spec fails.

**Comment by jimnanney** [comment]
I understand the rational, I just meant that as part of the CI process have the db:seed task run, and if it fails, fail the CI. That catches it at CI time, and not test time. The tradeoff is huge wins in test runs, and not being able to catch seed problems until CI runs.

**Comment by compwron** [comment]
@jimnanney @littleforest I expect the seed test to speed up dramatically as part of @keithrbennett work on #1089 so I think it would be more valuable to focus on other tests for speed-up. 

I asked that we start testing seeds after they were broken and inconvenienced new contributors who were trying to get set up. 

Right now seed is not run on every new QA auto-deploy. I want to continue catching seed breakages in an automated test as part of protecting the new contributor experience. :)

**Comment by littleforest** [comment]
@jimnanney ah I see what you are saying with having it as part of the CI. I like that idea. @compwron thoughts?

**Comment by compwron** [comment]
Ah I see, having it as a separate build stage
Works for me! As long as a PR which breaks it has a red build, I'm happy.

**Comment by jimnanney** [comment]
Either way on the seeds as a build step, I'm working on some steps to speed up the rest of the test suite.  Looks like there are a fair bit of unnecessary DB hits in the suite. I added test-prof gem to the test group in the Gemfile to help me track them down. I've got some modest gains so far (seconds as opposed to minutes from the seeds tests) but still pretty big wins.

I'll be sending those up as a PR soon.  This issue being a sort of "ongoing" issue, there is no real "done" criteria.  I may create a separate issue for each "set" of speedups as I add them. This could allow for a more definitive "what is being done" and "why".

**Comment by jimnanney** [comment]
Trading seed problems not being caught until after a push is a win as long as the CI pipeline fails the build. The huge win is in individual test runs, because a fast test suite means a more often run test suite.

I like the analogy that says "a test suite that allows me to go get coffee while it runs, only gets run with I need coffee."

**Comment by compwron** [comment]
😅👍

**Comment by compwron** [comment]
@jimnanney How's it going? :)

**Comment by compwron** [comment]
@jimnanney I'm going to close this for now, feel free to reopen it if you want to get back to it :)
