### ISSUE TITLE
change system message for self-deactivated admins

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1043]
**What type of user is this for? [volunteer/supervisor/admin/all or All CASA Admin]**
admin

**Where does/should this occur?**
https://casa-qa.herokuapp.com/users/sign_in

**How does it work now?**
After self deactivating their own account, admins see a yellow highlighted system message reading: 
_Your account is currently inactive. Please contact your supervisor for more details._
![Screen Shot 2020-10-11 at 12 17 37 PM (2)](https://user-images.githubusercontent.com/62810851/95688073-59021d00-0bbc-11eb-92c7-e6a823c9dac8.png)

**How should it work instead?**
After self deactivating their own account, admins should see a yellow highlighted system message that reads: 
_Your account is currently inactive. Please contact your CASA administrator for more details._

**Comment by akp2603** [comment]
Hi @Zrrrpy, would love to this look into this issue. Can you please assign me this issue?

**Comment by Zrrrpy** [comment]
@akp2603 done! thank you 😄

**Comment by akp2603** [comment]
Hi @Zrrrpy raised the PR, tested it. can you get it merged?

**Comment by jmkoni** [comment]
@akp2603 we will review the pr. Just FYI, it does not need that label to count for hacktoberfest.

**Comment by jmkoni** [comment]
Also please don’t tag people here about a PR. We all look at PRs regularly.

**Comment by akp2603** [comment]
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

Apparently, they have changed some rules this time. PRs with the tag `hacktoberfest-accepted` will be the only ones that will be counted. 
Secondly, this is my first open source contribution. So just a little anxious. Sorry for that. @jmkoni

**Comment by Zrrrpy** [comment]
Congrats on your first open source contribution, @akp2603! 🎊 

We've added the `hacktoberfest` label to our repository to eliminate the extra step of contributors needing to add `hacktoberfest-accepted` to individual PRs (<a href="https://hacktoberfest.digitalocean.com/hacktoberfest-update">you can read more about Digital Ocean's updated rules for Hacktoberfest here</a>). 😃  We are super grateful for all of our Hacktoberfest contributors, and strive to make the experience as seamless as possible!
