### ISSUE TITLE
Add seeding for hearing types

### ISSUE THREAD

**Issue by haydenrou** [rubyforgood/casa#1048]
**What type of user is this for? volunteer/supervisor/admin/all**
Developer

**Description**
Add seeding for hearing types.

Per #1000 we have added an interface for hearing types per organization, however there was a conversation in #928 regarding seeding the data for this which was not added to the PR.

**Comment by akp2603** [comment]
Hey @Zrrrpy!! Need a little clarity on this. Can we connect on slack? (name: Aashish Passrija)

**Comment by compwron** [comment]
@akp2603 Did you get your question answered

**Comment by akp2603** [comment]
@compwron Nope.

**Comment by compwron** [comment]
@akp2603 What is your question?

**Comment by akp2603** [comment]
From what I observed was that Hearing types, are associated with a Casa orgs. How do I handle that?
Like, is this predefined that a particular hearing type will be associated with some particular casa org by default? If that is the case we might have to seed casa orgs too.

Or, is it the case that there are a certain hearing types, and a user can itself attach any hearing type with any casa org?

or, is it the case that whenever a new hearing type is created, it gets attached to all the existing casa_orgs and if a new casa_org is created, it gets attached to all the exisiting hearing types.


Cases 1 and 3 are pretty straightforward. and easy to implement.
But if it is the second case, then I think it might be better to break it into multiple issues. (It involves mutliple schema changes, might involve UI changes, multiple application level changes.)

Let me know :)

**Comment by compwron** [comment]
@akp2603 
Correct, a hearing type belongs to a casa org. There should never be any data leakage between casa orgs. So if hearing type A belongs to casa org 1, no one in casa org 2 should be able to see hearing type A.

Yes, it would be good to put hearing types in seed so that we can have realistic&useful data. 

Seed is never run in prod. In prod, all data will be real (created by users)

**Comment by compwron** [comment]
@akp2603 How is it going? Are you still working on this? If you don't have time please let us know so that someone else can work on it. :)

**Comment by compwron** [comment]
Very cool :)

**Comment by rpolley** [comment]
Going to take a stab at this.
