### ISSUE TITLE
Remove deprecated field case_contact.contact_types

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1050]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
Remove deprecated field case_contact.contact_types
All code is now using `case_contact.case_contact_contact_type` instead
Make sure to not break migrations or after_party tasks!

**Screenshots of current behavior, if any**

**Comment by RachelWyatt** [comment]
Hi! I can work on this one if you want to assign it to me.
