### ISSUE TITLE
Remove clock icon and display Last Contact Made column by default on Volunteers view for supervisor/admin

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1054]
<img width="521" alt="Screen Shot 2020-10-12 at 11 18 28 PM" src="https://user-images.githubusercontent.com/578159/95822721-4f260a00-0ce1-11eb-9262-5313dd6e15a9.png">

**Comment by Zrrrpy** [comment]
@compwron I agree that the clock icon needs more of an explanation, but would rather display that information off the bat then require the user take an additional action (even if it's just hover) to see that info (good chance many supervisors won't figure this out, especially for those viewing on mobile). 

Unless you have strong feelings against doing this, I'd rather remove the clock icon and instead, add a new column for "Last Contact Made" to the Volunteer View.

**Comment by compwron** [comment]
Tooltip requested/suggested by Sarah 25 Nov 2020

**Comment by ctreptow** [comment]
Will take this one.
