### ISSUE TITLE
Add Location to seed data

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1055]
<img width="207" alt="Screen Shot 2020-10-12 at 11 18 40 PM" src="https://user-images.githubusercontent.com/578159/95822766-62d17080-0ce1-11eb-9df9-266e24ef404d.png">

**Comment by Zrrrpy** [comment]
@compwron Location actually correlates to a CASA Org's `display_name`, which an admin can set. 

If we seed this, we'd be seeding it as a detail associated with a `casa_org`. (And I don't know that we have plans to seed a bunch of `casa_orgs` right now? We could, but it doesn't feel urgent...yet.)

I'm moving this over to `Not ready to build` until we decide.
