### ISSUE TITLE
Unify and parameterize dev, qa, staging seeds

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1058]
Unify and parameterize dev, qa, staging seeds

QA and staging should be basically identical and have lots of data- good for stress testing / realistic load times

developerment should have very little data- just enough to have one or two users and all they need for local testing

@littleforest was discussing this somewhere with someone but I don't see it on the board so I'm adding this issue 😅 feel free to edit / amend / replace :)

**Comment by littleforest** [comment]
@jmkoni created #1035 , so going to close this!
