### ISSUE TITLE
volunteers can generate court reports for non transition aged youth

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1064]
Part of epic #880 // relates to #922

AS a **volunteer**,
I can generate a court report that auto-fills with select details,
SO that I can fill out remaining details after downloading and submit it to my supervisor.

**Court Report for _non_ transition aged youth should look like this**
[Template for Court Report for youth under 14.pdf](https://github.com/rubyforgood/casa/files/5373258/Template.for.Court.Report.for.youth.under.14.pdf)

**Court Report Fields for _non_ `Transition_Aged_Youth`** _as they should appear_ (Italicized text is helper text the volunteer will need to manually delete before submitting. All information that should be automatically filled when the report is generated appears in [brackets].)
- Date Written: [`date` the report is generated]
- Hearing Date: [`court_report_date`]
- Respondent: 
- Case #: [`casa_case`] 
- DOB: [`birth_month_year_youth`]
- Persons Interviewed Regarding the Situation:
- Name // Title/Relationship // Contact Dates (should display as headers in a single row – underneath each header, the below details related to all `case_contacts` that occurred since the previous `court_report_date` show)
[one `contact_type` should display per row under "Title" column] 
[one `occurred_at` `date` should display per row under "Contact Dates" column]
- Situation: _Leave blank, your supervisor will fill this section out._
- Objective Information: _Summarize factual information gathered from your contacts. Just the Facts! Your fact-based opinions come later! Indicate sources and dates from school personnel, physicians, psychological reports, psychiatric repots, etc. (For example: This CASA spoke with Ms. Teacher on January 12, 2009. Ms. Teacher stated…)   After each sentence if someone asked “says who?” the answer should be “Jordy, Mom, DSS, school, foster parents, my eyes”.  The answer should not be “the CASA volunteer thinks so”._ 
- Placement: 
_Where is the child placed?_  
_How is the child adjusting to the placement?_  
_Are there any issues or concerns at this point in time at the placement?_  
_If so, what are they and who is doing what to address those issues or concerns?_
- Education/Vocation:
_Where is the child placed for education (public school, non-public school, GED, JobCorps, etc)?_  
_How is the child adjusting to the placement?_  
_Are there any concerns at this point in time?_  
_If so, what are they and who is doing what to address those concerns?_  
_Does this child have an IEP? if not, is there a need for one?_
_Is the child employed? If so, where? If not, are they looking for a job?_
_Does the child have any vocational/life skills?_
_Are they attending life skill classes?_
_Do they have any other life skills needs? (Driver's education, state ID, transportation assistance, clothing voucher, etc.)_
- Health/Mental Health:
_Is the child up to date with medical exams?_ 
_Are there any other medical concerns?_
_Is the child receiving therapy, medication monitoring, mentoring, other therapeutic services?_ 
_If so, with whom?_  
_What do the professionals (who are providing these services) say about the child's progress?_
- Family/Community Connections:
_Is this child seeing parents, siblings, other relatives?_  
_If so, who is the child visiting, and how often?_
_If there is no visitation, why is it not happening?_
- Permanency Plan: 
_What is the child's permanency plan? Give a summary of the actions taken to achieve it._
- Assessment: 
_This section should provide information that leads to your recommendations, but be based on the objective information included in the section above._  
_Describe how the child is doing. Include a statement about the CASA’s role in the child’s life. Describe the relationship the CASA and the child currently have._
_What are the current concerns for the child? Is there a need that is not being met?_  
_You are presenting your opinion about the case (using factual information). For example: Family therapy is currently not in place. It is important that this service begins because…_
_One paragraph should be dedicated to each concern. 
What is your recommendation on a service or a plan to meet this need?_ 
_Restate the permanency plan. 
Is this the most appropriate plan at this time?  Describe why or why not._ 
_If there is another plan that may be better, offer a recommendation for that plan and describe why and how to achieve this plan._ 
- Recommendations:
_Therefore, CASA respectfully recommends:_ 
_1.  Ben Price remains in the care and custody of the Department of Social Services/his mother/etc;_ 
_2.  Something else;_
_3.  Something else; and_
_4. CASA is continued._ 
- (( space for signature ))
- [`volunteer_display_name`]
- Court Appointed Special Advocate
- Appointed: [`case_assignment` `created_at` date]
- (( space for signature ))
- [`supervisor_volunteer` `display_name`]
- CASA Case Supervisor

**Acceptance criteria:**
- [ ] Volunteer can select which `casa_case` they are generating a court report for. 
- [ ] Their selection determines which court report type is generated (if `transition_aged_youth` is `TRUE` then court report for transition aged youth is generated, if `transition_aged_youth` is `FALSE` then court report for non-transition aged youth is generated)
- [ ] Their selection also determines which `casa_case` the auto filled data should be associated with.
- [ ] When volunteer clicks button "Generate Report", a court report is generated based off of the above requirements, and text: _Court report generating. Do not refresh or leave this page_ appears.
- [ ] When court report finishes generating, a button to "Download Court Report" appears.
- [ ] Clicking the button downloads the court report as a .docx

**Comment by coldiron** [comment]
Working on this.

**Comment by Zrrrpy** [comment]
Hey @coldiron, thanks for picking this up! How's it goin?

**Comment by compwron** [comment]
@coldiron Because we haven't heard from you lately, this issue will be returned to the TODO list. Feel free to pick it up again if you have time to work on it! :)

**Comment by Zrrrpy** [comment]
@pollygee this could be a good one for you!

**Comment by erik-trantt** [comment]
I'll take this one.

**Comment by compwron** [comment]
@erik-trantt How is it going? Our stakeholders are excited for this! :)

**Comment by erik-trantt** [comment]
@compwron Sorry for the delay. I got caught up in something, but gonna push it soon. Really excited as it's the last feature of the epic.

**Comment by compwron** [comment]
Very cool! :)
