### ISSUE TITLE
change My Cases table text when empty

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1067]
AS a **volunteer**,
IF I have no active case assignments,
I WANT to see the text: _No active cases_ in the "My Cases" table,
SO that I understand why it is otherwise empty. 

**How it works now**
Volunteers with no active case assignments see: "No data available in table" under "My Cases".

**How it should work instead**
Volunteers with no active case assignments should see: "No active cases" under "My Cases".

**Screenshots of current behavior**
<img width="1343" alt="no data available in table" src="https://user-images.githubusercontent.com/62810851/95913206-be8b1080-0d58-11eb-8352-c2d356f7a2ab.png">

**Comment by gskifstad** [comment]
I am working on this issue! 🥳

**Comment by FireLemons** [comment]
@gskifstad I was working on it too but didn't say anything. The `No data available in table` comes from this jQuery based library https://datatables.net/. And the api calls for that are in `app/javascript/src/dashboard.js`
