### ISSUE TITLE
Caterpillar automatically becomes butterfly when youth turns 14

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1070]
Part of epic #532

AS a **volunteer**,
WHEN my `casa_case` assignment turns 14,
I WANT the caterpillar next to their CINA number to turn into a butterfly,
SO THAT I have a visual reminder that they are now a `transition_aged_youth`.

### How it works now
Volunteers see a caterpillar and butterfly emoji next to their `casa_case` when they become a `transition_aged_youth`. Non transition aged youth have no special marker.

### Screenshot of current behavior
<img width="1440" alt="Screen Shot 2020-10-13 at 4 56 31 PM" src="https://user-images.githubusercontent.com/62810851/95927987-1c2d5600-0d75-11eb-86ab-4dcc36e95b8b.png">

### How it should work instead
A caterpillar should display to the left of a `casa_case` in the `case_contacts` table header, viewable by volunteers. When the `casa_case` turns 14 years of age, the caterpillar should _automatically_ sprout wings and from this point on, display as butterfly. (<a href="https://udw1g1.axshare.com/#id=v15n5y&p=volunteer_experience&g=1">Click on caterpillar to see it change in mockup.</a>)

### Screenshot of new behavior
![Screen Shot 2020-10-13 at 4 56 31 PM (3)](https://user-images.githubusercontent.com/62810851/95928030-3d8e4200-0d75-11eb-932f-3f041b038b96.png)

### Acceptance criteria
- [ ] A caterpillar or butterfly displays to the left of a `casa_case` in the volunteer view under `case_contacts`.
- [ ] If `casa_case` is under 14 years of age, a caterpillar displays.
- [ ] If `casa_case` is 14 years of age or older (i.e. `transition_aged_youth`), a butterfly displays. 
- [ ] Caterpillar automatically changes to a butterfly on the first day of a `casa_case`'s birth month the year they turn 14.

**Comment by Zrrrpy** [comment]
hey @duaimei! How's this goin?

**Comment by compwron** [comment]
Hey @duaimei I know we talked about this at office hours. How is it going?

On a technical note, the way I envision this working is a cronjob (like we have to kick off Monday emails) that checks youth birth month and updates the transition_aged_youth db field. 
>  Caterpillar automatically changes to a butterfly on the first day of a casa_case's birth month the year they turn 14.

**Comment by khiga8** [comment]
> On a technical note, the way I envision this working is a cronjob (like we have to kick off Monday emails) that checks youth birth month and updates the transition_aged_youth db field.
> 

Oooh! Looks like there was a task that was introduced [here][0], though I'm not sure how frequently it runs...

[0]: https://github.com/rubyforgood/casa/pull/920

**Comment by compwron** [comment]
This is the current state of our cronjobs in qa, staging, and prod. I guess we should make them match at some point. I wish we could make one cronjob that kicked off the others, so we don't have to add each one individually in each environment. 
![Screen Shot 2021-02-07 at 8 56 24 AM](https://user-images.githubusercontent.com/578159/107153449-866c9680-6922-11eb-86c4-5cfdc29dc4c9.png)
![Screen Shot 2021-02-07 at 8 56 20 AM](https://user-images.githubusercontent.com/578159/107153450-87052d00-6922-11eb-8daa-3034aff71693.png)
![Screen Shot 2021-02-07 at 8 56 15 AM](https://user-images.githubusercontent.com/578159/107153452-879dc380-6922-11eb-8ce2-f7f7c2da7c1d.png)

**Comment by compwron** [comment]
cronjobs now match in all 3 environments
