### ISSUE TITLE
Volunteers can filter case_contact view

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1071]
AS a **volunteer**, 
WHEN I am viewing `case_contacts`,
I WANT to be able to filter `case_contacts`,
SO THAT I can easily find the `case_contact` I need to reference.

 ### Volunteers should be able to filter by
- [ ] date ranges
- [ ] `contact_type_group`
- [ ] `case_contact_contact_type`
- [ ] `contact_made` (yes/no)
- [ ] `contact_medium`
- [ ] `want_driving_reimbursement` (yes/no)
- [ ] Volunteers can sort all of the above by ascending and descending order.

### Acceptance criteria
- [ ] A button labeled "Filtered by" displays in the new `case_contacts` table header viewable by volunteers (see #696)
- [ ] Clicking the button displays all "Filter by" options
- [ ] Volunteer can filter by any combination of conditions above
- [ ] It is easy for the volunteer to close the "Filter by" menu after making their selections

**Comment by Archish27** [comment]
@Zrrrpy I would like to work on this :)

**Comment by Archish27** [comment]
Do we want a filter in this page? 
![Uploading image.png…]()

**Comment by compwron** [comment]
@Archish27 Yes! Filtering here would be very useful

**Comment by compwron** [comment]
@Archish27 I am unassigning this because I don't think it's being worked on. Feel free to pick it back up if you have time! :)

**Comment by rhian-cs** [comment]
Hello, it's been a while. May I give this one a try?
