### ISSUE TITLE
Make "Manage Court Details" Active column match columns above it true vs Yes

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1073]
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**
Make "Manage Court Details" Active column match columns above it true vs Yes

**Screenshots of current behavior, if any**
<img width="441" alt="Screen Shot 2020-10-13 at 10 20 03 PM" src="https://user-images.githubusercontent.com/578159/95946954-785a9f00-0da2-11eb-8460-9817955f77d0.png">

**Comment by compwron** [comment]
This is a good bitesize issue for a new contributor.

**Comment by JadeDickinson** [comment]
I'm working on this one if that's ok?
