### ISSUE TITLE
case_contact rows should always align with table header

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1079]
AS any user (volunteer/admin/supervisor), 
WHEN I am viewing CASA Case Details,
I WANT to see rows display under their corresponding column headers,
SO THAT I have proper context for the information I am viewing. 

### How it's working now
As a page stretches and becomes wider, rows of `case_contacts` begin separating from their corresponding column headers. 
![Screen Shot 2020-10-14 at 12 50 00 PM (2)](https://user-images.githubusercontent.com/62810851/96039382-68cc6c00-0e1d-11eb-8935-a06b8cab92e4.png)

### How it should work instead
`case_contact` rows should always line up with their respective column headers. As a page's size changes, the design should remain stable.
_Mobile view of this page is very different and should not change._

### Acceptance Criteria
When a page's width increases,
`case_contact` rows remain in their respective columns.

**Comment by gskifstad** [comment]
Hi! can i do this one? 

Seems like this is related to a DataTables formatting gotcha with scroll-enabled tables:
https://datatables.net/manual/tech-notes/6
https://datatables.net/forums/discussion/42659/table-header-width-not-aligned-with-body-width
