### ISSUE TITLE
All-CASA Admin can see casa org overview key metrics

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1086]
**What type of user is this for?**
`AllCasaAdmin` (this is different from `CasaAdmin`!)

**Description**
AS an All CASA Admin, (the type of user that adds a new CASA org to the platform)
I WANT to see high level data summaries associated with each `casa_org`,
SO THAT I have insight into platform usage by each `casa_org`. 

Log in at https://casa-qa.herokuapp.com/all_casa_admins/sign_in as allcasaadmin@example.com / 123456 (see seed data for alternate logins)

**Acceptance Criteria**
- [ ] On a `casa_org` page, there is a new section called "Details"
- [ ] In this section, the following data associated with the corresponding `casa_org` is a viewable:
- [ ] Number of admins
- [ ] Number of supervisors
- [ ] Number of volunteers (active and inactive as separate numbers)
- [ ] Number of cases  (active and inactive as separate numbers)
- [ ] Number of case contacts

**Screenshots**
It should display on this page:
<img width="1319" alt="Screen Shot 2020-10-24 at 2 50 45 PM" src="https://user-images.githubusercontent.com/62810851/97094604-050b2580-160b-11eb-8655-0c41a5385325.png">

**Comment by steph-hickman9** [comment]
I can work on this!

**Comment by littleforest** [comment]
@steph-hickman9 this is marked as not ready to build, so please look for another ticket in the To Do column of the project.

**Comment by steph-hickman9** [comment]
Sorry didn't see the label!

**Comment by jmkoni** [comment]
@steph-hickman9 check out the issues here https://github.com/rubyforgood/casa/projects/1#column-8461147

**Comment by rpolley** [comment]
Going to work on this.

**Comment by Zrrrpy** [comment]
Thank you @rpolley!! 🙏🏼
