### ISSUE TITLE
Admin can upload casa_org logo

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1088]
AS an **admin**,
I WANT to be able to upload my `casa_org`'s logo,
SO THAT my `casa_org` instance is branded and familiar to staff and volunteers. 

### Acceptance Criteria
On the Edit CASA Organization page,
there is a button to choose and upload an image file.
One uploaded, this image file populates in the header for this `casa_org`.

**Comment by rebecarancan** [comment]
I can work on this!
