### ISSUE TITLE
casa_org without custom logo displays neutral CASA logo by default

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1090]
AS any user (volunteer/supervisor/admin),
IF my `casa_org` does not have a custom logo,
THEN I should see the neutral CASA logo (the one I see on the log in/out screen) in the site header. 

### Acceptance Criteria
The neutral CASA logo (below) displays by default in a `casa_org`'s header until an Admin customizes their `casa_org` instance and uploads a custom logo to the header.
![logo copy](https://user-images.githubusercontent.com/62810851/96069037-3c7f1280-0e52-11eb-8cc4-0127453085e9.png)

**Comment by RachelWyatt** [comment]
Hi, I can work on this one!
