### ISSUE TITLE
fix sign-in screen

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1102]
AS any user (volunteer/supervisor/admin/All CASA Admin), 
WHEN I visit https://casa-qa.herokuapp.com/users/sign_in,
I WANT it to look just like the logged out view <a href="https://casa-qa.herokuapp.com/"><I see here,</a>
SO THAT both views are uniform and familiar.

### Screenshot of how it works now
<img width="1361" alt="logged out view 2" src="https://user-images.githubusercontent.com/62810851/96171269-85c67500-0ed9-11eb-8e25-e5346bebeed0.png">

### Screenshot of how it should work instead
<img width="1355" alt="logged out view 1" src="https://user-images.githubusercontent.com/62810851/96171276-8828cf00-0ed9-11eb-9dc7-1a1c196cbc22.png">

 ### Acceptance Criteria
- [ ] eliminate white space underneath footer
- [ ] add space between "Forgot your password?" and footer
- [ ] add image featured <a href="https://casa-qa.herokuapp.com/">in logged out view</a> (see below)
![AM14480-1-800x533](https://user-images.githubusercontent.com/62810851/96171038-36804480-0ed9-11eb-9525-e153575c97e3.jpg)

**Comment by drborges** [comment]
@Zrrrpy I'll take on this issue over the weekend, thank you.

**Comment by seanmarcia** [comment]
My bad I submitted a PR for this. I didn't check to see if there was an issue with someone on it before submitting a PR.

**Comment by drborges** [comment]
No worries @seanmarcia, I'm glad you were able to get to this one sooner than me, thank you.

@Zrrrpy for reference the fixes were shipped in https://github.com/rubyforgood/casa/pull/1107
