### ISSUE TITLE
Remove route to "Generate Court Report" from sidebar for admins and supervisors

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1103]
AS a supervisor or admin,
I SHOULD NOT see "Generate Court Reports" in the left sidebar,
BECAUSE this is not a feature I need to use.

### How it works now
Supervisors and admins can both see "Generate Court Reports" in the left sidebar.
<img width="1362" alt="generate court reports" src="https://user-images.githubusercontent.com/62810851/96177810-4ac93f00-0ee3-11eb-85a1-6aa99a7b4fb1.png">

### How it should work instead
"Generate Court Reports" should not display as an option for supervisors and admins to access in the sidebar menu.

### Acceptance Criteria
"Generate Court Reports" does not display in sidebar menu for supervisors and admins.

**Comment by rebecarancan** [comment]
I can work on this

**Comment by Zrrrpy** [comment]
all yours, @rebecarancan! Thank you 😄
