### ISSUE TITLE
add bug report form to footer and sidebar for all users

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1104]
AS any user (volunteer/supervisor/admin/All CASA Admin), 
WHEN I am logged in OR logged out,
I WANT access to the bug report form,
SO THAT I can record any site issues I experience.

### How it works now
The bug report form is not currently accessible from anywhere on the site for any users.

### How it should work instead
All users should be able to access the bug report form, whether they are logged in or logged out.

### Acceptance Criteria
- [ ] The <a href="https://rubyforgood.typeform.com/to/iXY4BubB"> bug report form</a> is hyperlinked in the sidebar menu _for all users_. 
- [ ] The hyperlinked text reads: Report a site issue
- [ ] The hyperlinked text displays above the user's email in the sidebar menu.
- [ ] The hyperlinked text "Report a site issue" displays to the right of the Ruby For Good logo in the site footer that displays when a user is logged out, <a href=
"https://casa-r4g-staging.herokuapp.com/">here</a> and <a href="https://casa-qa.herokuapp.com/users/sign_in">here.</a>

**Comment by renugasaraswathy** [comment]
Hi @Zrrrpy, I would like to work on this issue. Could you assign it to me?

**Comment by renugasaraswathy** [comment]
@Zrrrpy @littleforest could you review the PR?
