### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ext' of undefined

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1115]
See discussion in slack- we have a console error that should be cleaned up. https://rubyforgood.slack.com/archives/CVB0QJGVD/p1602891352340000
```
app/javascript/src/dashboard.js:  $.fn.dataTable.ext.search.push(
jQuery.Deferred.exceptionHook @ jquery.js:3432
jquery.js:3438 Uncaught TypeError: Cannot read property 'ext' of undefined
    at HTMLDocument.<anonymous> (dashboard.js:3)
    at mightThrow (jquery.js:3235)
    at process (jquery.js:3277)
localhost/:1 
```
(it’s also in my browser’s console)

**Comment by luisgregson** [comment]
I am working on this issue

**Comment by Zrrrpy** [comment]
Thanks @luisgregson! Just assigned to you. 😃

**Comment by luisgregson** [comment]
@Zrrrpy thanks! I'm struggling to log into slack via the link in the issue description. I think i need a rubyforgood.com account? Do i need to register somewhere or is it possible for you to post the slack discussion in this issue? thanks

**Comment by luisgregson** [comment]
@Zrrrpy I've managed to get everything running locally and i'm logged into slack but i can't recreate this issue.

I'm logged in as a volunteer, viewing the `/casa_cases` page. i don't get any errors in the console, and when i pause execution in `dashboard.js` it shows that `$.fn.dataTable` is an object, whereas the error is reporting it as undefined.

![image](https://user-images.githubusercontent.com/8599818/97290274-3ae51f80-1840-11eb-90e7-654377cae28f.png)

Am i doing something wrong or has this issue already been fixed?

**Comment by compwron** [comment]
@luisgregson I don't think we fixed it on purpose but I no longer see it in QA or staging 😅
Thank you for looking into it! 
If you want to work on more casa work, here is our list of things that need doing! https://github.com/rubyforgood/casa/projects/1
https://casa-qa.herokuapp.com/
https://casa-r4g-staging.herokuapp.com/
