### ISSUE TITLE
Docker Scripts

### ISSUE THREAD

**Issue by jhsu802701** [rubyforgood/casa#1116]
I'd like to add scripts for executing Docker commands.  This would free people from having to repeatedly type in "docker-compose run --rm web".

Examples of Docker scripts are:
- https://github.com/openfoodfoundation/openfoodnetwork/tree/master/docker
- https://github.com/codebar/planner/tree/master/bin

**Comment by littleforest** [comment]
Sounds good. You can add a section to the end of the [doc/DOCKER.md](https://github.com/rubyforgood/casa/blob/master/doc/DOCKER.md) file describing how these scripts are optionally available to use.
