### ISSUE TITLE
[bug] casa admin downloading reports

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1117]
bug seen on prod, which was just deployed and is using the same code as in staging and qa
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1602904458457200
BugsnagAPP  8:14 PM
New unhandled error in production from casa in case_contact_reports#index (details)
Unhandled error
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type bigint: ""
LINE 1: ...17') AND (contact_types.contact_type_group_id in ('','1','2'...
                                                            ^
Location
app/models/case_contact_report.rb:24 - block in to_csv
New
8:15
Event in production from casa in case_contact_reports#index (details)
Unhandled error
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type bigint: ""
LINE 1: ...17') AND (contact_types.contact_type_group_id in ('','1','2'...
                                                            ^
Location
app/models/case_contact_report.rb:24 - block in to_csv

<img width="816" alt="Screen Shot 2020-10-16 at 8 15 12 PM" src="https://user-images.githubusercontent.com/578159/96327202-74ba5880-0fec-11eb-8623-0fcf0d050621.png">

**Comment by erik-trantt** [comment]
Mind if I take this one?

**Comment by erik-trantt** [comment]
Sample params of a report request: 
```
{
"start_date"=>"2020-05-19", 
"end_date"=>"2020-10-20", 
"supervisor_ids"=>["", "2"], 
"creator_ids"=>["", "1"], 
"contact_type_ids"=>["", "1", "2"], 
"contact_type_group_ids"=>["", "1", "2", "3", "4", "5", "6"], 
"want_driving_reimbursement"=>"true", 
"contact_made"=>"false", 
"has_transitioned"=>"", 
"commit"=>"Download Report"
}
```

Contact Type Group filter fails when selections include the prompt option `-Select Contact Type Groups-`. 
The generated SQL statement has the `WHERE` clause with empty string option, which causes the error.

```rb
# app/models/case_contact.rb

scope :contact_type_groups,  ->(contact_type_group_ids =  nil)  {
  joins(:contact_types).where("contact_types.contact_type_group_id in (?)", contact_type_group_ids)
    if contact_type_group_ids.present?
}

## That JOINS results to this SQL statement:
# SELECT case_contacts.* 
# FROM case_contacts 
# INNER JOIN case_contact_contact_types ON case_contact_contact_types.case_contact_id = case_contacts.id 
# INNER JOIN contact_types ON contact_types.id = case_contact_contact_types.contact_type_id 
# WHERE (contact_types.contact_type_group_id in ('','1','2','3','4','5','6'))
```

Solution is to replace the `JOINS` with:

```rb
# app/models/case_contact.rb
scope :contact_type_groups,  ->(contact_type_group_ids =  nil)  {
  joins(contact_types: :contact_type_group)
          .where(contact_type_groups: { id: contact_type_group_ids })
          .group(:id)
}
## That JOINS results to this SQL statement:
# SELECT case_contacts.* 
# FROM case_contacts 
# INNER JOIN case_contact_contact_types ON case_contact_contact_types.case_contact_id = case_contacts.id 
# INNER JOIN contact_types ON contact_types.id = case_contact_contact_types.contact_type_id 
# INNER JOIN contact_type_groups ON contact_type_groups.id = contact_types.contact_type_group_id 
# WHERE contact_type_groups.id IN (NULL, 1, 2, 3, 4, 5, 6) 
# GROUP BY case_contacts.id
```

The empty string is auto-handled by ActiveRecord Querying Interface, and converted to `NULL` value.

**Comment by erik-trantt** [comment]
I also identified a bunch of other bugs relating to scopes of CaseContact used in CaseContactReport filters. 

1. When 1 `case_contact` has many `contact_types` that belongs to the same `contact_type_group`, the report will have duplicate records of that `case_contact`.

Considering the purpose of this Case Contact Report is to list each case contact as a record, then the above behavior should be a bug.

![image](https://user-images.githubusercontent.com/44339322/96468739-28834880-1278-11eb-89b1-d99777582edb.png)
![image-20201019235733092](https://user-images.githubusercontent.com/44339322/96468917-5cf70480-1278-11eb-8824-4dd929d95adb.png)

I think the solution is to add a `.group(:id)` to the scope `CaseContact`.`contact_type_groups`.

-----

2. Want Driving Reimbersement, Contact Made, Transition Aged Youth filters **do not** work at all if selecting either Both / Yes / No. The params are of String type, then is used to a Boolean type. Example:

  ```rb
# app/models/case_contact.rb
  scope :contact_made, ->(contact_made = nil) {
    where(contact_made: contact_made) if contact_made == true || contact_made == false
  }
  scope :has_transitioned, ->(has_transitioned = nil) {
    joins(:casa_case).where(casa_cases: {transition_aged_youth: has_transitioned}) if has_transitioned == true || has_transitioned == false
  }
  scope :want_driving_reimbursement, ->(want_driving_reimbursement = nil) {
    where(want_driving_reimbursement: want_driving_reimbursement) if want_driving_reimbursement == true || want_driving_reimbursement == false
  }
```

The `where` blocks will never be includes.

I think we can rewrite them into:

`where(contact_made: contact_made == "true") if contact_made&.length&.positive?`

`contact_made&.length&.positive?` will result to *false* if `contact_made` is nil or empty.

-----

3. Contact Types filters **do not** work properly. If none is selected, it will accept all `contact_types`, which is expected. If one or more options are selected, the query is comparing `contact_types.name` against `contact_type.ids`.

```rb
# app/models/case_contact.rb
  scope :contact_type, ->(contact_type = nil) {
    if contact_type.present?
      joins(:contact_types)
        .where("contact_types.name in (?)", contact_type)
    end
  }
```

There are 2 ways to fix this:

1. Change to use `contact_types`.`id` for filtering. It is similar to the bug of this issue:
```rb
  scope :contact_type, ->(contact_type_ids = nil) {
    if contact_type.present?
      joins(:contact_types)
        .where(contact_types.id: contact_type_ids)
    end
  }
```

2. Change the generate values of options element of Contact Type to `name` from `id`:

![image](https://user-images.githubusercontent.com/44339322/96472459-35a23680-127c-11eb-93d1-1a01ed92ad3d.png)
![image](https://user-images.githubusercontent.com/44339322/96472492-43f05280-127c-11eb-948d-5cdf9a613261.png)

**Comment by compwron** [comment]
@erik-trantt Thanks for making these great finds 😱 😅 and such a good explanation of them! 💪💖
Any of these bugs that you don't fix in a PR for this issue, please open separate github issues for. https://github.com/rubyforgood/casa/issues/new/choose

**Comment by erik-trantt** [comment]
@compwron No worry. I found the report outcome is flaky, so went ahead and manually QA them. The tests are made for the model, but not for from view to model.

I'll work on getting the Case Group Type filter right, and open issues for the other 2.

**Comment by compwron** [comment]
@erik-trantt sounds good
I want to eradicate the flaky tests, as far as I am concerned each one of them is a bug :(

**Comment by erik-trantt** [comment]
Yeah, I agree, those tests could have been designed better.

**Comment by compwron** [comment]
this issue is completed but didn't auto-close, so I will close it :)
