### ISSUE TITLE
remove Case Contacts view from Supervisor and Admin dashboards

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1118]
**What type of user is this for? volunteer/supervisor/admin/all OR All CASA Admin**
admins and supervisors

**Description**
The Case Contacts view can be removed for both admins and supervisors. They can already see this data by clicking on a `casa_case`, or by generating a report. 

**Screenshots of current behavior, if any**
This is what the Case Contacts view looks like, except it goes on forever because there are many case contacts associated with each case. It is no longer needed.
<img width="1324" alt="Screen Shot 2020-10-24 at 3 23 33 PM" src="https://user-images.githubusercontent.com/62810851/97094794-050c2500-160d-11eb-8386-af6615fc7d3a.png">

**Comment by cassianoblonski** [comment]
@compwron if I'm not mistaken this is already done, right? can we close this issue or there is something to finish here?

**Comment by Zrrrpy** [comment]
this is done! closing out
