### ISSUE TITLE
Create deploy checklist

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1119]
**Description**
Let's not oops again plz

Create a DEPLOY_CHECKLIST.md in `docs/` and link to it from the readme "production" section
1. For any manual deploy (currently staging or prod)
1. Announce deploy in slack #casa "I am about to deploy [staging|prod]". If you have any problems (need to rerun a deploy, need to run code in rails console) post to a slack thread about it (do not include any identifying info about youths or any passwords or credentials of course)
1. Log into heroku console https://dashboard.heroku.com/teams/rubyforgood/apps 
1. Download a manual db backup (do this for staging also both for practice and in case there is data in there which we want to be able to retrieve) https://dashboard.heroku.com/apps/casa-production > click add-on "heroku postgres" > Durability > "Create Manual Backup" > Download
1. Log into heroku rails console for the environment you are about to deploy to, to make sure your credentials are set up in case you need to clean something up in a hurry `heroku run rails c --app casa-production` or `heroku run rails c --app casa-r4g-staging`
1. Locally, check out the version of the code that is going to be deployed (so if there is a bug you can look at the exact code that has the bug in order to diagnose it) `git checkout <hash from heroku UI>`
1. Click the deploy button https://dashboard.heroku.com/pipelines/ab5437b7-b7da-4204-bcfc-33bac4466347
1. Watch the log until it's done and watch for errors
1. Go to the environment which was just deployed and click around looking for problems. Always check as user type Volunteer first because they are the users we have the most of
1. Post in slack that the deploy is done

**Comment by steph-hickman9** [comment]
I got this!
