### ISSUE TITLE
undefined method `pre_match' for nil

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1125]
BugsnagAPP  1:25 PM
New unhandled error in staging from casa in bin/rails:10 (details)
Unhandled error
NoMethodError: undefined method `pre_match' for nil:NilClass
Location
bin/rails:10 - <main>
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1603052731461800

**Comment by littleforest** [comment]
Think this was a weird blip. Only other reference I can find online has to do with the irb console. Checked rails console for staging and worked fine. Closing for now.
