### ISSUE TITLE
Casa Admin can inactivate case from Edit Case page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1132]
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**
Casa Admin can inactivate case from Edit Case page
> I can't figure out how to inactivate a case. 
> [Let's] put an inactivate button in the "edit case" page

**Open Questions**
For an inactivated case,
- should volunteers be unassigned from it --- **yes, volunteers who are active on a case that goes inactive should immediately become unassigned, or available**
- should supervisors be allowed to inactivate a case --- **No**
- should admins be allowed to inactivate a case --- **yes, as admin I can do any/all updates quarterly with my stats.**
- should case contacts show up in a downloaded report for an inactivated case --- **yes, i think for our reports it doesn't matter if contacts were occurring on a case that subsequently closes**
- should an inactivated case show up in "cases which can be assigned to volunteers" --- **No**
- if a new case is imported which has the same case number as an inactivated case, should the importer see an error? And/or should the case be re-activated ---​**Yes**
- should cases ever be allowed to be reactivated --- **yes, we may get removed from a case and then referred to it later so reactivation sounds good in those rare circumstances**
- does the admin need to see a list of all deactivated cases, and if so where should it be --- **yes, i would think that it could be in the case list with a filter ability like we have in the volunteer page. Filter by: "active" or "inactive"**

**Screenshots of current behavior, if any**
![Screen Shot 2020-10-19 at 4 19 19 PM](https://user-images.githubusercontent.com/578159/96521778-dc5be800-1226-11eb-8cdd-58a9e550f50d.png)

**Comment by RachelWyatt** [comment]
I can look into this one
