### ISSUE TITLE
add notes column to case_contacts table in CASA Case Details

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1133]
**What type of user is this for? volunteer/supervisor/admin/all or All CASA Admin**
all

**Description**
All users should be able to view "notes" associated with a `case_contact` in the `case_contacts` table on the CASA Case Details page.

**Screenshots of current behavior, if any**
This is what it currently looks like, without the additional column. 
<img width="1437" alt="Screen Shot 2020-10-24 at 3 41 36 PM" src="https://user-images.githubusercontent.com/62810851/97095045-7cdb4f00-160f-11eb-85e8-e0f5bf348068.png">

**Acceptance Criteria**
- [ ] There is a new column titled "Notes" in the `case_contacts` table associated with each `casa_case` on the CASA Case Details page
- [ ] New column displays between "Created by" and "Actions" columns
- [ ] This column displays notes associated with that `case_contact`
- [ ] Only the first 100 characters of a note displays. 
- [ ] Notes containing more than 100 characters show an option to "Read More"
- [ ] Clicking "Read more" expands the note and displays the remaining characters. 
- [ ] User sees option to "Hide" expanded notes.
- [ ] Clicking "Hide" collapses additional characters and only shows the first 100 characters.

**Comment by khiga8** [comment]
Hello! I'd like to take this issue :-)
