### ISSUE TITLE
Supervisor/admin should be able to edit case contacts from the /case_contacts page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1134]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor/admin

**Description**
Supervisors should be able to edit case contacts from the /case_contacts page

**Screenshots of current behavior, if any**
![sb](https://user-images.githubusercontent.com/578159/96522402-2b564d00-1228-11eb-8c20-1dd54e045cd9.png)

**Comment by Zrrrpy** [comment]
no longer needed – see #1118
