### ISSUE TITLE
In Case Contact Report, Want Driving Reimbersement, Contact Made, Transition Aged Youth filters are not working

### ISSUE THREAD

**Issue by erik-trantt** [rubyforgood/casa#1137]
Sample params of a report request:

{
"start_date"=>"2020-05-19", 
"end_date"=>"2020-10-20", 
"supervisor_ids"=>["", "2"], 
"creator_ids"=>["", "1"], 
"contact_type_ids"=>["", "1", "2"], 
"contact_type_group_ids"=>["", "1", "2", "3", "4", "5", "6"], 
"want_driving_reimbursement"=>"true", 
"contact_made"=>"false", 
"has_transitioned"=>"", 
"commit"=>"Download Report"
}

Identified a bunch of other bugs relating to scopes of CaseContact used in CaseContactReport filters at:
 - /case_contact_reports

2. Want Driving Reimbersement, Contact Made, Transition Aged Youth filters **do not** work at all if selecting either Both / Yes / No. The params are of String type, then compare to a Boolean type. Example:

  ```rb
# app/models/case_contact.rb
  scope :contact_made, ->(contact_made = nil) {
    where(contact_made: contact_made) if contact_made == true || contact_made == false
  }
  scope :has_transitioned, ->(has_transitioned = nil) {
    joins(:casa_case).where(casa_cases: {transition_aged_youth: has_transitioned}) if has_transitioned == true || has_transitioned == false
  }
  scope :want_driving_reimbursement, ->(want_driving_reimbursement = nil) {
    where(want_driving_reimbursement: want_driving_reimbursement) if want_driving_reimbursement == true || want_driving_reimbursement == false
  }
```

The `where` blocks will never be includes.

I think we can rewrite them into:

```rb
where(contact_made: contact_made == "true") if contact_made&.length&.positive?

# `contact_made&.length&.positive?` will result to *false* 
# if `contact_made` is nil or empty.

```

OR, clean up the params in `case_contact_reports_controller` to pass in Boolean types TRUE / FALSE or nil if empty.

_Originally posted by @erik-trantt in https://github.com/rubyforgood/casa/issues/1117#issuecomment-712247123_

**Comment by cassianoblonski** [comment]
got this
