### ISSUE TITLE
Update font to match CASA styleguide font

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#114]
Part of epic: #38 

**What type of user is this for? volunteer/supervisor/admin/all**
all

**Where does/should this occur?**
Everywhere text displays on the frontend.

**Description**
Update font to match regular CASA font

We want to make this app look "CASA style" and welcoming for the 100+ volunteers who will start using it for the first time soon! See the attached font guide. :) [color.font.pdf](https://github.com/rubyforgood/casa/files/4498162/color.font.pdf)

> National CASA/GAL uses two main typefaces for all of its
> marketing materials. Brandon Grotesque is used for headlines
> and is the “face” of the brand. There are multiple weights
> of Brandon Grotesque available. Proxima Nova is used for
> subheads and body copy.
> Two more fonts are included for limited, special-use cases.
> For creative that must follow ADA guidelines, Serifa STD, a serif
> font, may be used in place of Proxima Nova for body copy.
> For web applications, Montserrat is available as a free web-safe
> font from Google.
> Brandon Grotesque is a new font and is available from National
> CASA/GAL in the following weights: regular, light, black and
> italic. Proxima Nova is a current CASA/GAL font.

<img width="1043" alt="Screen Shot 2020-04-18 at 6 33 12 PM" src="https://user-images.githubusercontent.com/578159/79677167-17f7f580-81a3-11ea-82aa-458e6d67d861.png">

Style references: 
https://drive.google.com/open?id=1s1vgxXFTYeslFXCh0SWFkgLsIC74sjy7

**Screenshots of current behavior, if any**

**Related issues, if any**

**Comment by colinsoleim** [comment]
The app now uses the Montserrat font as recommended in the style guide. However, the text CSS doesn't align with the style guide in all cases, and it could use some CSS touchups to more closely match the CASA style.

**Comment by compwron** [comment]
This seems done for now- the font is correct. We're getting a UI review from CASA soon, hopefully next week, and we'll make issues for what they want when that happens. :)
