### ISSUE TITLE
Add more safeguards to casa_case.clear_court_dates

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1141]
**Description**
Update `casa_case.clear_court_dates` which was added in https://github.com/rubyforgood/casa/pull/1140 to check whether a court date is in the past before clearing it 
Since this isn't called from the UI, we don't need to add a policyfile entry around this
We can see court cases which have had court dates cleared in paper trail

**Comment by big-meel** [comment]
@compwron I'll do this PR, a conditional will be fine correct?

**Comment by big-meel** [comment]
Hey @compwron may I work on this?

**Comment by big-meel** [comment]
@Zrrrpy is this still available

**Comment by Zrrrpy** [comment]
Yes it is, and it is all yours! Thanks for picking up, @big-meel 😄

**Comment by big-meel** [comment]
No problem

**Comment by littleforest** [comment]
Sorry, little fix still needed! https://github.com/rubyforgood/casa/pull/1235/files/9c0db4d77fca263d122524990f62caacbccb323e..5609cc49ff441042c6f9a39ad34e05e770e00c0a#r516410229

**Comment by compwron** [comment]
Whoops sorry about that
