### ISSUE TITLE
default date range for reports 6 months for supervisors

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1148]
AS a **supervisor**,
I WANT the default date range on the generate court reports page to be the past 6 months,
SO THAT I can quickly pull reports that provide historical context I regularly need. 

### How it works now
The default date range on court reports for supervisors is the past 30 days.
<img width="1368" alt="Screen Shot 2020-10-21 at 9 06 51 AM" src="https://user-images.githubusercontent.com/62810851/96747234-e3950a00-137c-11eb-9128-560fb0fe7d3d.png">

### How it should work instead
The default date range on court reports for supervisors should be the past 6 months.

**Comment by steph-hickman9** [comment]
I can take on this issue!
