### ISSUE TITLE
Make table borders prettier

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#115]
This is part of epic https://github.com/rubyforgood/casa/issues/38

**What type of user is this for? volunteer/supervisor/admin/all**
all, especially volunteers

**Description**
Make the table borders prettier (less bold, wider, with padding) for all volunteer-viewable tables
Try to make these styles apply to the whole app so we can have a unified look :)
We want to make this app look "CASA style" and welcoming for the 100+ volunteers who will start using it for the first time soon! See the attached font guide. :) [color.font.pdf](https://github.com/rubyforgood/casa/files/4498162/color.font.pdf)

> National CASA/GAL uses two main typefaces for all of its
> marketing materials. Brandon Grotesque is used for headlines
> and is the “face” of the brand. There are multiple weights
> of Brandon Grotesque available. Proxima Nova is used for
> subheads and body copy.
> Two more fonts are included for limited, special-use cases.
> For creative that must follow ADA guidelines, Serifa STD, a serif
> font, may be used in place of Proxima Nova for body copy.
> For web applications, Montserrat is available as a free web-safe
> font from Google.
> Brandon Grotesque is a new font and is available from National
> CASA/GAL in the following weights: regular, light, black and
> italic. Proxima Nova is a current CASA/GAL font.

**Screenshots of current behavior, if any**
<img width="822" alt="Screen Shot 2020-04-18 at 5 31 07 PM" src="https://user-images.githubusercontent.com/578159/79676381-956b3800-819a-11ea-9aa8-89956c1d848c.png">
<img width="1043" alt="Screen Shot 2020-04-18 at 6 33 12 PM" src="https://user-images.githubusercontent.com/578159/79677167-17f7f580-81a3-11ea-82aa-458e6d67d861.png">

**Related issues, if any**
https://github.com/rubyforgood/casa/issues/114 is also about style

**Comment by colinsoleim** [comment]
For this issue, all current table styles have been updated to use bootstrap or jquery datatable default styles. They still don't conform to CASA's style guide, but they at least give a unified look to the MVP.

**Comment by compwron** [comment]
I'm resolving this since it's done for now- we'll get more style guidance soon :)
