### ISSUE TITLE
judge_names only display on case details if admin has added judge_names to casa_org

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1153]
part of epic #880 // relates to #927 and #929

AS a supervisor or volunteer,
IF an admin has not added `judge_names` to our unique `casa_org` instance,
THEN I should not see `judge_name` in my case details. 

### Acceptance Criteria
IF there are no `judge_names` available within a `casa_org` instance,
THEN `judge_name` does not display as an available option to add to next `court_date` under case details.

**Comment by pedrosmmoreira** [comment]
Hello 👋 Happy to take this one on!

**Comment by pedrosmmoreira** [comment]
It seems like this is dependent on at least https://github.com/rubyforgood/casa/issues/929 being ready. I'll keep an eye out for that going in, then circle back to this!

**Comment by compwron** [comment]
@pedrosmmoreira #929 is merged! Do you still have time to work on this? Please let us know :)

**Comment by pedrosmmoreira** [comment]
Hey @compwron, yes I can still do this one. Thanks for the ping!

**Comment by AngeVeza** [comment]
Hey @pedrosmmoreira, thank you so much for all your work on this, it looks great. Could you also remove judge name from the casa case details page?

![Casa2](https://user-images.githubusercontent.com/73323436/98889184-12277180-245f-11eb-837b-eef6466ee27b.JPG)

**Comment by pedrosmmoreira** [comment]
Hey @AngeVeza, sure. I'll open a new PR for that.
