### ISSUE TITLE
Volunteer name should be link on admin/supervisor

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1154]
![Screen Shot 2020-10-21 at 6 24 04 PM](https://user-images.githubusercontent.com/578159/96807322-1a920c80-13cb-11eb-96a5-4e3236475c79.png)

**Comment by cassianoblonski** [comment]
can I do this?

**Comment by jmkoni** [comment]
@cassianoblonski sure! but i noticed that you also asked about another ticket. do you mind picking a single ticket at a time? Do you want this one or the other one?

**Comment by cassianoblonski** [comment]
@jmkoni I'm already finishing the other one ( #1137 )

**Comment by jmkoni** [comment]
I'm talking about #1161

**Comment by compwron** [comment]
@cassianoblonski @jmkoni this issue is already claimed by @NickSchimek (you can see in the "Assigned" section) please do not work on this issue. :) 
Happy to have you work on another issue though! As @jmkoni says, please do one at a time. :)
