### ISSUE TITLE
Supervisor would like to be able to see all case contact notes at once for a case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1155]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor

**Description**
Supervisor would like to be able to see all case contact notes at once for a case - not currently possible
This is on the mockups- a kind of expanding section for each case contact
Requested by Sarah (stakeholder) 21 Oct

**Screenshots of current behavior, if any**

**Comment by Zrrrpy** [comment]
covered by #1133
