### ISSUE TITLE
Event in production from casa in users/sessions#create

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1163]
This may not actually be prod? Is bugsnag showing wrong env?

BugsnagAPP  8:32 PM
Event in production from casa in users/sessions#create (details)
Unhandled error
ActiveModel::UnknownAttributeError: unknown attribute 'remember_me' for User.
Location
vendor/bundle/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/attribute_assignment.rb:52 - _assign_attribute

https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1603337573030200

if you have a <your name>@rubygorgood.org email then log in / reset password with that email 

Event | Release Stage | Severity
-- | -- | --

ActiveModel::UnknownAttributeErrorusers/sessions#createunknown attribute 'remember_me' for User.21 minutes agoOct 22nd, 03:32:53 UTCproductionunhandledstacktracebreadcrumbsappdevicerequestusersessionadd tab +ActiveModel::UnknownAttributeError · unknown attribute 'remember_me' for User.Rawvendor/bundle/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/attribute_assignment.rb:52_assign_attribute        if respond_to?(setter)          public_send(setter, v)        else          raise UnknownAttributeError.new(self, k)        end      end  end | ActiveModel::UnknownAttributeErrorusers/sessions#createunknown attribute 'remember_me' for User.21 minutes agoOct 22nd, 03:32:53 UTC | production | unhandled |   | if respond_to?(setter) |   | public_send(setter, v) |   | else |   | raise UnknownAttributeError.new(self, k) |   | end |   | end |   | end
ActiveModel::UnknownAttributeErrorusers/sessions#createunknown attribute 'remember_me' for User.21 minutes agoOct 22nd, 03:32:53 UTC | production | unhandled
  | if respond_to?(setter)
  | public_send(setter, v)
  | else
  | raise UnknownAttributeError.new(self, k)
  | end
  | end
  | end

![Screen Shot 2020-10-21 at 8 54 52 PM](https://user-images.githubusercontent.com/578159/96822811-cc3b3880-13df-11eb-8a94-74ba18aae509.png)

**Comment by littleforest** [comment]
Ref #1234
