### ISSUE TITLE
Search for user by current and previous names

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#117]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor/admin

**Description**
A supervisor or admin can filter a list of volunteers by name. This name search should take into account previous names of the user. For example, if Christine Jacobs changes her name to Christie Smith-Jacob, typing "Christine" or "Jacobs" into search should still bring her up. 

Be careful to not depend on the concepts of "first name" or "last name" - see some info about names below. 

Names can change when someone gets married or divorced, when they transition genders, when they take a "stage name", in order to separate their identity from unpleasant or overly-famous relatives, etc. Many software systems handle this poorly and many people are used to being annoyed and sad about how their names are handled by software. Let's not be an additional problem; we want our volunteers to not be annoyed at CASA because of us in any way. :)

1. If you haven't yet read https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ please do so before working on this issue. In fact, maybe re-read it anyway, it's healthy to remember :)
1. Any user is able to edit their own name at any time and to any length (maximum... ~300 characters for now is fine).
1. Some sample names to consider (not real current volunteer names): Hubert Blaine Wolfeschlegelsteinhausenbergerdor ff Sr, Carlos María Eduardo García de la Cal Fernández Leal Luna Delgado Galván Sanz, Svetlana Viktorevna Rakhmaninova
1. https://en.wikipedia.org/wiki/Spanish_naming_customs
1. http://yuba.stanford.edu/~molinero/html/surname.html
1.http://blog.tesol.org/7-naming-customs-from-around-the-world/
1. https://www.fbiic.gov/public/2008/nov/Naming_practice_guide_UK_2006.pdf
1. https://en.wikipedia.org/wiki/Name_change

**Screenshots of current behavior, if any**

**Related issues, if any**
This must be done after https://github.com/rubyforgood/casa/issues/116

**Comment by colinsoleim** [comment]
An update on this issue, the jquery datatables search feature works for current volunteer names. If we want to be able to search by previous names, we'll need change how we store the name field in the database.

**Comment by compwron** [comment]
I was hoping that because paper_trail records previous volunteer names we could use those existing db records as the basis of a new search. 

This issue is low priority imo, it is from a concern of one of the CASA staff that we haven't seen in manifest in the prod system yet. It thought it would be fun to build for someone so I wrote it down. :)

**Comment by colinsoleim** [comment]
Oh cool, I didn't realize paper_trail had that functionality. From the rails console, looks like something like `past_names = user.versions.map { |version| version&.reify&.display_name }` would work to pull past names.
