### ISSUE TITLE
remove route to Case Contacts from admin and supervisor sidebar menu

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1181]
relates to #1118

AS an **admin** or **supervisor**,
I no longer need access to the "Case Contacts" view,
because I can already view these details by clicking on a `casa_case`. 

**Screenshots of current behavior**
This is what the sidebar looks like now:
<img width="311" alt="Screen Shot 2020-10-24 at 3 23 33 PM" src="https://user-images.githubusercontent.com/62810851/97094862-df335000-160d-11eb-858b-20d91a7acd52.png">

**Acceptance Criteria**
Route to Case Contacts is removed from sidebar menu for supervisors and admins.

**Comment by steph-hickman9** [comment]
I got this!
