### ISSUE TITLE
deactivated casa_cases should not be available to assign to volunteers

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1184]
dependent on #1182

AS a **supervisor** or **admin**,
I WANT TO _only_ see active `casa_cases` available to assign to volunteers,
SO THAT I do not accidentally assign a volunteer to an inactive `casa_case`.

### How it works now
Currently, all `casa_cases` display as available to assign to volunteers in the dropdown menu under "Assign a New Case" on the Editing Volunteer Page (see screenshot below).
<img width="1375" alt="Screen Shot 2020-10-24 at 5 40 27 PM" src="https://user-images.githubusercontent.com/62810851/97096434-1a8b4a00-1621-11eb-969f-c9c4c92a92b3.png">

### How it should work
Only active `casa_cases` should display in the dropdown menu under "Assign a New Case" as available to assign to a volunteer.

**Comment by chaserx** [comment]
@Zrrrpy Hello. 👋 I've worked on a couple of other RfG projects off and on. I was looking thru the open issues, and while this one isn't very high priority. I think I can fix it pretty quickly, easily. If that's acceptable, please assign me and I'll work on a PR for this. 😃

**Comment by compwron** [comment]
@chaserx welcome! :)
