### ISSUE TITLE
add filter to Cases view

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1185]
AS a **supervisor** or **admin**,
I WANT TO filter `casa_cases` by a select criteria,
SO THAT I can easily view `casa_cases` that meet that criteria.

### How it works now
`casa_cases` display in numerical order, and are only sortable by ascending and descending order within each column.

### How it should work
`casa_cases` should be filterable by the following:
- active / inactive (see #1182) 
- assigned / not assigned to a volunteer
- assigned to more than one volunteer
- transition aged youth / not transition aged youth
- CINA vs TPR (this shows up in the case number: some start with `CINA` and some start with `TPR`)

### Screenshots
This is how filters work in Volunteer View:
<img width="1369" alt="Screen Shot 2020-10-24 at 6 25 28 PM" src="https://user-images.githubusercontent.com/62810851/97096826-5d9bec00-1626-11eb-90a3-bf451723d89b.png">

**Comment by metamoni** [comment]
I'll give it a shot :)

**Comment by isaacm** [comment]
@Zrrrpy  For the bullet point `- assigned / not assigned to a volunteer` does this `filter by name` of the assigned volunteer? or is this simply a boolean filter `yes|no` if the case is assigned or not?

**Comment by Zrrrpy** [comment]
The latter! Should be yes/no if the case is assigned or not. Thank you for picking this up, @isaacm
