### ISSUE TITLE
error when admin attempts to import inactive casa_case

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1190]
dependent on #1182

AS an **admin**,
WHEN I attempt to import an inactive `casa_case`,
I _do not_ want the `casa_case` to be re-imported, 
_instead_, I WANT to receive an informative error message,
SO THAT I understand why the inactive `casa_case` was not imported.

### How it works now
`casa_cases` currently only have one state, which is active, but #1182 is changing that – soon, `casa_cases` will have two states: active or inactive.

### How it should work
When an admin attempts to import an _inactive_ `casa_case` which is already in the system, the inactive `casa_case` should not be imported. Instead, a reason why that row of the import failed should be listed in the "Errors" column available for download after an import attempt.

That error should read something like:
_CASA case already exists, but is inactive. Reactivate the CASA case instead._

**Comment by steph-hickman9** [comment]
I have got this one!

**Comment by Zrrrpy** [comment]
all yours, @steph-hickman9!
