### ISSUE TITLE
Use pundit to deactivate a casa case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1193]
```
  def deactivate
    casa_case = CasaCase.find(params[:id])
    # TODO: authorize action with pundit
```
https://github.com/rubyforgood/casa/pull/1192/files#r511674102

**Comment by peaonunes** [comment]
Hey, I'm happy to give a try on that. I was looking at the code and the pundit policies, and `update_case_status?` seems to suit our needs, right?
https://github.com/rubyforgood/casa/blob/d94a0e73faf3469c28a9af0c34dd9e0209d3274e/app/policies/casa_case_policy.rb#L36-L40

**Comment by littleforest** [comment]
@peaonunes that looks correct!

**Comment by compwron** [comment]
@peaonunes How is it going? Are you still working on this? If not, please comment here so that we can assign it to someone else.

**Comment by peaonunes** [comment]
> @peaonunes How is it going? Are you still working on this? If not, please comment here so that we can assign it to someone else.

Hey, yeah I'm on it. I'm just having problems to get my setup working, hopefully I will be able to finish that this weekend. If I don't manage to get it done I'm happy to pass it on.

**Comment by compwron** [comment]
Very cool! Happy to help if you want :)
