### ISSUE TITLE
Friendlier warning box when Admin disables a CASA Case

### ISSUE THREAD

**Issue by RachelWyatt** [rubyforgood/casa#1197]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin (only admins have permission to deactivate a case)

**Description**
Right now, we're using a basic browser warning when an Admin clicks "Deactivate CASA Case". We want a prettier, more user-friendly dialogue box with customized button text. 

**Acceptance Criteria**
[] Clicking on "Deactivate CASA Case" triggers a dialogue reading: Deactivating a CASA Case will unassign any volunteers currently assigned to this case. Are you sure you'd like to continue? and two buttons: "Yes, deactivate" and "No, go back"
[] Clicking "Yes, deactivate" deactivates casa_case 
[] Clicking "No, go back" closes dialogue box.

**Screenshots of current behavior, if any**
Current warning:
<img width="542" alt="Screen Shot 2020-10-25 at 7 57 46 PM" src="https://user-images.githubusercontent.com/37967627/97175283-a7411f80-1769-11eb-9cc5-8cd7e6b21834.png">

**Comment by Math-O5** [comment]
Can  I be assigned to it? Or there's someone already work on int?

**Comment by jmkoni** [comment]
@Math-O5 no one is assigned yet, so it's all yours!
