### ISSUE TITLE
Unassign Volunteer Button falling off screen on Edit Casa_case page

### ISSUE THREAD

**Issue by AngeVeza** [rubyforgood/casa#1219]
As an admin/supervisor, 
when I resize my screen smaller, 
I want the unassign volunteer button to stay on the page,
so that I can click on it. 

How it's working now,
the unassign volunteer button is falling off the page,
when the screen is made smaller.

Screen shot of current behaviour:
<img width="464" alt="Casaedit" src="https://user-images.githubusercontent.com/73323436/97519046-28610800-195e-11eb-9a1c-018e1ee1f4e9.PNG">

How it should work,
the unassign volunteer button should move with the screen and it should be responsive to the screen as it changes.

**Comment by joaovitoras** [comment]
Hello, @AngeVeza can you assign this problem to me? I would like to work on it

**Comment by Zrrrpy** [comment]
all yours, @joaovitoras!
