### ISSUE TITLE
Update button styles on login screen

### ISSUE THREAD

**Issue by NickSchimek** [rubyforgood/casa#1223]
**Description**
The login button should attract the eye with a nice background color and have the forgot password button be less noticeable.

Current design:

<img width="608" alt="Screen Shot 2020-10-29 at 9 25 41 PM" src="https://user-images.githubusercontent.com/19519317/97645496-72e2a180-1a90-11eb-9c70-9c25ff1f1f74.png">

**Acceptance Criteria**

 - Swap the design on the two buttons

**Comment by gVirtu** [comment]
I'd like to help with this one if possible. :)

**Comment by NickSchimek** [comment]
> Shall this affect the all_casa_admins login page as well?

I assume so. I did not know there was more than one login page. Is this the case @Zrrrpy ?

**Comment by compwron** [comment]
@NickSchimek @gVirtu yes there are 2 login screens- 1 for regular users, 1 for AllCasaAdmin. We care the most about the one for regular users but happy to have both fixed :)
