### ISSUE TITLE
Supervisor/Admin search cases from Cases page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1232]
**What type of user is this for? volunteer/supervisor/admin/all**
Supervisor/Admin 

**Description**
an admin or supervisor should be able to search cases by case_number from the Cases page, similar to how one can search Volunteers from the Volunteers page- see screenshots

**Screenshots of current behavior, if any**
![volunteer page](https://user-images.githubusercontent.com/578159/97793224-5f295f00-1ba6-11eb-9481-dd3af681fd14.png)
![Cases page](https://user-images.githubusercontent.com/578159/97793226-605a8c00-1ba6-11eb-982d-2b1ecd465ecc.png)

**Comment by Zrrrpy** [comment]
this has been done and is in staging!
