### ISSUE TITLE
Remove unassigned volunteers from Volunteers table and Case Detail View

### ISSUE THREAD

**Issue by metamoni** [rubyforgood/casa#1233]
**What is the problem, and what should happen instead?**

Unassigned volunteers still appear in the Case table and Case Detail View. Only volunteers assigned to that case should show up here.

**Reproduction steps**

- While logged in as an Admin, go to Cases to view the cases table
- Click 'Edit' to open a case and assign a few volunteers to it
- On the same page, click 'Unassign Volunteer' to unassign one of them
- Navigate back to Cases table and notice that the case appears to be assigned to all volunteers, including any unassigned
- Click 'Details View' and notice that all volunteers appear here too
- Navigate back to the table, click the unassigned volunteer's name and see that the case is still assigned to them

**Note**: When clicking 'Unassign Cases' from a volunteer's profile page (you get here by clicking a volunteer's name from the table), the Cases table and Case Detail View pages update correctly.

**Screenshots of current behavior, if any**

<img width="1243" alt="Screenshot 2020-10-31 at 11 49 10" src="https://user-images.githubusercontent.com/22390758/97806305-ea602e80-1c52-11eb-9902-3bdccd6a0d04.png">

<img width="898" alt="Screenshot 2020-10-31 at 11 49 00" src="https://user-images.githubusercontent.com/22390758/97806304-e8966b00-1c52-11eb-93d4-8f1d4bbdbc2f.png">

**Comment by littleforest** [comment]
@metamoni thanks for working on this! Unfortunately, this solution doesn't quite work, and it is breaking the build.

This line:

```
assigned_volunteers(policy_scope(@casa_case)).each_with_index do |volunteer, index|
```

should actually look more like:

```
policy_scope(assigned_volunteers(@casa_case)).each_with_index do |volunteer, index|
```

where the policy scope is wrapping a set of volunteers. However, it expects an ActiveRecord relation, but the `assigned_volunteers` method is returning an array.

Do you have time to take another look at this? If so, let us know if you need any help.

Also, please add `RSpec` in front of the `describe` statement in the spec -- this was the initial failure in Travis, but it got overlooked for a linting error instead:

```
RSpec.describe CasaCaseHelper
```

Thanks!

**Comment by compwron** [comment]
Sorry that's my bad, i will take a look tonight

**Comment by metamoni** [comment]
Thanks for explaining that, @littleforest, I'll keep that in mind in the future. I haven't used pundit before, so had no idea. Thanks for the fix, @compwron!

**Comment by littleforest** [comment]
Thanks @compwron! Will create follow-up case to prettify the `assigned_volunteers` method.
