### ISSUE TITLE
prod error

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1234]
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1604229702129900
https://app.bugsnag.com/ruby-for-good/casa/errors/5f90f6ddf86dad00180b3d17?event_id=5f9e9a46006222299f260000&i=sk&m=oc
BugsnagAPP  3:21 AM
Event in production from casa in users/sessions#create (details)
Unhandled error
ActiveModel::UnknownAttributeError: unknown attribute 'remember_me' for User.
Location
vendor/bundle/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/attribute_assignment.rb:52 - _assign_attribute

**Comment by littleforest** [comment]
We don't have the `remember_me` in our code at all, and the 6 times this error has been encountered it has been from an IP address in Russia. So I don't think this is a legit error.
