### ISSUE TITLE
Add "after_action :verify_authorized" to force authorization everywhere

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1237]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
Add "after_action :verify_authorized" to force authorization everywhere
This is a safety measure
https://www.rubydoc.info/github/elabs/pundit/Pundit:verify_authorized
https://github.com/varvet/pundit#ensuring-policies-and-scopes-are-used

**Comment by littleforest** [comment]
Do you mean `before_action`?

**Comment by littleforest** [comment]
Oh never mind! I should have read the links first.

**Comment by scottolsen** [comment]
@compwron It looks like we are using `must_be_admin` in quite a few of the controllers. I'm thinking this should probably be removed and replaced with the Pundit authorization as part of this PR. Thoughts?

```ruby
# app/controllers/application_controller.rb:22
  def must_be_admin
    return if current_user&.casa_admin?

    flash[:notice] = t("default", scope: "pundit")
    redirect_to root_url
  end
```

**Comment by scottolsen** [comment]
I think this is pretty close to everything we want to do.
 
- [ ] Make all policies inherit from `ApplicationPolicy`
- [ ] Clean up duplication methods
- [ ] Verify all policies have matching spec for all actions
- [ ] Add `authorize` helper to all controller actions
- [ ] Add `after_action :verify_authorized` to `ApplicationController`
- [ ] Remove all `before_action :authenticate_user!` from controllers

**Comment by compwron** [comment]
> @compwron It looks like we are using `must_be_admin` in quite a few of the controllers. I'm thinking this should probably be removed and replaced with the Pundit authorization as part of this PR. Thoughts?
> 
> ```ruby
> # app/controllers/application_controller.rb:22
>   def must_be_admin
>     return if current_user&.casa_admin?
> 
>     flash[:notice] = t("default", scope: "pundit")
>     redirect_to root_url
>   end
> ```

Sounds like a good plan!
