### ISSUE TITLE
make per PR heroku review app

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1238]
make per PR heroku review app
We need permissions for this- ask Sean/Polly
<img width="532" alt="Screen Shot 2020-11-04 at 8 36 02 AM" src="https://user-images.githubusercontent.com/578159/98139458-165cf900-1e79-11eb-9fe2-9f7973451133.png">

**Comment by littleforest** [comment]
@seanmarcia or @pollygee are either of you able to authorize us to be able to create review apps?

**Comment by compwron** [comment]
I think this is dead in the water 😅
I personally am not feeling a pain that this would solve but I'm happy for it to happen. I don't have permissions for it tho.

**Comment by littleforest** [comment]
I would still really like to get this set up unless it is a financial issue! I often want to review the UI for PRs, and it would be so much faster to do it in a review app than pulling the code locally. Will ping in Slack about this.

**Comment by pollygee** [comment]
Sorry! I never saw this!  My github notifications are a bit prolific.  Is this something we still want to do?  Do we have an idea on the charges for this?

**Comment by littleforest** [comment]
@pollygee so I think we would just get charged the $7/mo rate, prorated to the number of minutes we are actually running the review apps. So if we only manually create the review apps when we would like to easily review a UI change, and if we are good about deleting them when we are finished, then I don't think we would rack up more than a few days a month of charges, which wouldn't be very much.

**Comment by seanmarcia** [comment]
This has been enabled!

**Comment by littleforest** [comment]
You rock! Thank you! Re-opening since there is a little configuration set up to be done still.

**Comment by littleforest** [comment]
Reopening since configuration isn't correct and builds aren't working.
