### ISSUE TITLE
Remove "new casa contact" on Admin's dashboard

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#124]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
Remove "new casa contact" on Admin's dashboard because Admin don't do that often and if they need to, they will go to the Case page and do it from there

**Screenshots of current behavior, if any**
<img width="823" alt="Screen Shot 2020-04-19 at 12 27 19 PM" src="https://user-images.githubusercontent.com/578159/79697727-25f85580-8239-11ea-9b78-5aac4408fc6c.png">

**Related issues, if any**

**Comment by compwron** [comment]
https://github.com/eclectic-coding is working on this https://rubyforgood.slack.com/archives/C04PM108S/p1587330437126500?thread_ts=1587327161.124100&cid=C04PM108S

**Comment by eclectic-coding** [comment]
Yes I will get started on this one.
