### ISSUE TITLE
Unassigning case from Volunteer page completely deletes case assignment

### ISSUE THREAD

**Issue by metamoni** [rubyforgood/casa#1241]
**What is the problem, and what should happen instead?**
On the Volunteer page, clicking the 'Unassign case' button deletes the assignment completely. This means that, instead of appearing as 'Deactivated', the case just disappears from the Volunteer's 'Assigned Cases' list. It would be better to keep a record of this assignment but display a status of 'Deactivated', along with an action of 'None'. This is already added to the code, but because it's linked to the volunteer's active status instead of the case assignment's active status, it doesn't work.

**Screenshots of current behavior, if any**

<img width="1305" alt="Screenshot 2020-11-04 at 19 44 32" src="https://user-images.githubusercontent.com/22390758/98160895-c745b100-1ed6-11eb-8cd4-efc0c62d57b7.png">

<img width="1289" alt="Screenshot 2020-11-04 at 19 45 52" src="https://user-images.githubusercontent.com/22390758/98160901-c9a80b00-1ed6-11eb-895a-ba7a68b33667.png">

**Comment by compwron** [comment]
I agree this is something that we want to change.

**Comment by metamoni** [comment]
I looked at it as part of another task, but haven't quite managed to get it to work. The file that needs looked at is the volunteers/edit view, lines 84-104. The conditions should be updated to `if assignment.is_active`, and the button should link to the `unassign_case_assignment` path. However, I wasn't sure how to update the action, which currently redirects to the casa_case. This is fine if you're using the 'Unassign Volunteer' button from the Case detail page, but when we're doing it from the Volunteer detail page we want is to stay there.

**Comment by compwron** [comment]
I think we fixed this - I couldn't replicate it.
