### ISSUE TITLE
Assign a New Volunteer dropdown contains already assigned volunteers

### ISSUE THREAD

**Issue by metamoni** [rubyforgood/casa#1242]
**What is the problem, and what should happen instead?**
On the Edit Cases page, volunteers still appear in the 'Assign a New Volunteer' dropdown list even after they've been assigned to a case (screenshot no. 1). The user can click their names and nothing happens, as they're already assigned. This is particularly confusing when the case only has a few volunteers - in this case the dropdown completely covers the names of currently assigned volunteers (screenshot no. 2).

**Reproduction steps:**
Go to Cases, pick a case and click Edit
If no volunteers are assigned, assign one using the dropdown at the bottom
Notice that the names of volunteers who have already been assigned appear in the dropdown list

**Screenshots of current behavior, if any**
<img width="1284" alt="Screenshot 2020-11-04 at 20 01 29" src="https://user-images.githubusercontent.com/22390758/98162607-83a07680-1ed9-11eb-8516-e1e33b035240.png">

<img width="452" alt="Screenshot 2020-11-04 at 20 07 34" src="https://user-images.githubusercontent.com/22390758/98162617-8602d080-1ed9-11eb-9e4b-3492dfc50ed7.png">

**Comment by cjilbert504** [comment]
So I think I have this sorted out but I don't know how to write the spec for it. I've tried a bunch of things and spent a while getting my google-fu on to no avail. I'm going to submit a PR for what I have for review and I would love to pair with someone to see about how to write this spec.
