### ISSUE TITLE
inactive volunteer calculation is not the same between pages

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1246]
AS a **supervisor or admin**,
I want to see at a glance which volunteers have _not_ made successful contact with their youth in 14 days or more,
so that I know to reach out to this volunteer (or their supervisor) and ensure they are fulfilling their responsibilities.

### How it's working now
The clock emoji next to the volunteer names indicates a volunteer has not made contact with their assigned youth in the past **30 days** or more.
![Screen Shot 2020-11-04 at 7 36 17 PM](https://user-images.githubusercontent.com/578159/98194794-0d017a00-1ed5-11eb-8a2e-24a5e2b63c2a.png)

### How it should work instead
The numbers here reflect supervisors assigned to volunteers who have not made successful contact with their currently assigned youth in the past **14 days or more**. This is the correct logic for this query. 
![Screen Shot 2020-11-04 at 7 36 26 PM](https://user-images.githubusercontent.com/578159/98194798-0f63d400-1ed5-11eb-8332-386323a0b327.png)

### Acceptance Criteria
Query should only include:
- [ ] active volunteers
- [ ] currently assigned to at least one active case
- [ ] who have not logged a `case_contact` where `contact_made = true` in at least 14 days.

### @compwron's notes

```
  def cases_where_contact_made_in_days(num_days = 30)
    casa_cases
      .joins(:case_contacts)
      .where(case_contacts: {contact_made: true})
      .where("case_contacts.occurred_at > ?", Date.current - num_days.days)
    # this should respect current vs past cases
  end
```

```
  def made_contact_with_all_cases_in_days?(num_days = 30) # should be 14!
    # this should do the same thing as no_contact_for_two_weeks but for a volunteer
    total_cases_count = casa_cases.count
    return true if total_cases_count.zero?
    current_contact_cases_count = cases_where_contact_made_in_days(num_days).count
    current_contact_cases_count == total_cases_count
  end
```

**Comment by librod89** [comment]
@compwron, for this ticket, the clock should be removed from the Volunteers page, and a new column should be added to show how many youth have not been contacted in the past 14 days. Is this correct?

**Comment by compwron** [comment]
@librod89 let's keep the clock but change the meaning of it. If it's easy, it would also be nice to make the clock have a tooltip/hovertext explaining what's up. We want the system to be self-explanatory as much as possible :)

**Comment by librod89** [comment]
Ok cool. I can work on this.

**Comment by librod89** [comment]
Actually the clock was removed in this PR https://github.com/rubyforgood/casa/pull/1482

@compwron is there anything else you want to do for this ticket?

**Comment by compwron** [comment]
All good then! :)
