### ISSUE TITLE
All CASA Admin can create new All CASA Admin

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1247]
AS an All CASA Admin,
I WANT the ability to create additional All CASA Admin accounts, 
SO THAT more than one All CASA Admin can log in. 
Note: Currently an `AllCasaAdmin` can only create a `CasaAdmin` not a `AllCasaAdmin` and we want to be able to do both. 

Log in at https://casa-qa.herokuapp.com/all_casa_admins/sign_in as allcasaadmin@example.com / 123456 (see seed data for alternate logins)

![Screen Shot 2020-12-11 at 6 42 09 PM](https://user-images.githubusercontent.com/578159/101970670-9b59d180-3be0-11eb-870a-4899a8f93673.png)

**Comment by librod89** [comment]
I'd like to work on this one.

**Comment by compwron** [comment]
All yours :)
