### ISSUE TITLE
email configuration for password reset

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#125]
Part of epics #3, #4, #105  

_We are still deciding on which email service to use, but the code for this can be started to the extent possible before that decision is made. We can test email locally._

**What type of user is this for? [volunteer/supervisor/admin/all**
all (volunteers most immediately)

**Where does/should this occur?**
login & user email

**Description**
When a user clicks [forgot your password](https://casa-r4g-staging.herokuapp.com/users/password/new) and submits "Send me reset password instructions," a reset password email should be triggered and sent by the system to the user email provided. That email should direct to a [future work, not in this issue] password reset page. 

References:
https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-edit-their-password

**Email Text**

Subject line: Create a password & set up your account

Hello [volunteer display name],

A CASA/Prince George’s County volunteer console account has been created for you. This console is for logging the time you spend and actions you take on your CASA case. You can log activity with your CASA youth, their family members, their foster family or placement, the DSS worker, your Case Supervisor and others associated with your CASA case (such as teachers and therapists).

Your console account is associated with this email. If this is not the correct email to use, please stop here and contact your Case Supervisor to change the email address. If you are ready to get started, please set your password. This is the first step to accessing your new volunteer account.

[button text = Set your password]

Please reach out to your Case Supervisor if you experience any difficulties or have questions.

- CASA/Prince George’s County

**Screenshots:**
Here is what a PG CASA email looks like:
![PG CASA](https://user-images.githubusercontent.com/62810851/80314748-27310180-87a8-11ea-9a8d-08a7d742f1bf.png)

And here are some examples of password reset emails.
![ActionID](https://user-images.githubusercontent.com/62810851/80290522-5e48d980-86fa-11ea-9f69-3f8e8d714ee7.jpg)
![opentable](https://user-images.githubusercontent.com/62810851/80290523-60ab3380-86fa-11ea-9ae1-473314488874.jpg)
![spotify](https://user-images.githubusercontent.com/62810851/80290525-6143ca00-86fa-11ea-9953-58a8622275de.jpg)

Relates to issues: #22, #23

**Comment by Zrrrpy** [comment]
copy updated with revisions from PG/CASA
