### ISSUE TITLE
Sort contact type groups in contact type edit

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1255]
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**
Sort contact type groups in contact type edit
https://casa-r4g-staging.herokuapp.com/contact_types/49/edit

**Screenshots of current behavior, if any**
![Screen Shot 2020-11-04 at 11 01 37 PM](https://user-images.githubusercontent.com/578159/98208219-c79f7580-1ef1-11eb-940b-ac4607a74e6a.png)

**Comment by compwron** [comment]
this is probably in app/views/contact_type_groups/_form.html.erb:24

**Comment by SMJ289** [comment]
@compwron just to clarify, is the intent to sort the _contact type groups_ alphabetically?

**Comment by compwron** [comment]
Yes

**Comment by compwron** [comment]
@SMJ289 are you still working on this? :)

**Comment by SMJ289** [comment]
@compwron sorry again! As per my comment on the other issue I opened up, I have figured out how to sort these but haven't found the work up the corresponding tests. Should I make a PR with the sorted contact types in leu of tests for now?

**Comment by compwron** [comment]
@SMJ289 no worries! yes please do. Don't worry about making it pretty, just make a PR and I will take it the rest of the way :)
