### ISSUE TITLE
Move js out of erb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1259]
move js out of app/views/case_contacts/_case_contact.html.erb and into a js file

```
<script type="text/javascript">

  function moreText (event) {
    event.preventDefault()
    const table_cell = event.target.closest('td')

    table_cell.querySelectorAll('.full-notes')[0].style.display = 'block'
    table_cell.querySelectorAll('.limited-notes')[0].style.display = 'none'
  }

  function lessText (event) {
    event.preventDefault()
    const table_cell = event.target.closest('td')

    table_cell.querySelectorAll('.full-notes')[0].style.display = 'none'
    table_cell.querySelectorAll('.limited-notes')[0].style.display = 'block'
  }
</script>

```

**Comment by kukyak2020** [comment]
hi team! I would like to work on this issue. Can you add to me this issue? @littleforest? thanks :)

**Comment by kukyak2020** [comment]
Thanks 😎

**Comment by ATMartin** [comment]
@kukyak2020 Are you still working on this ticket? I'd love to take it on if not.

**Comment by kukyak2020** [comment]
@ATMartin Hi, yes I am working on it. Can you give me a couple of days for it? thank you! 🙏🏿

**Comment by ATMartin** [comment]
@kukyak2020 Of course! It looks like a GitHub bot unassigned you - @compwron could we reassign so no one else grabs this ticket?

**Comment by Zrrrpy** [comment]
@kukyak2020 just reassigned. Thank you for your help with this! 🙏🏼
