### ISSUE TITLE
Location should not be clickable

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1266]
AS any user,
I WANT Location in my sidebar to be static,
SO THAT I am clear it is static data that does not lead anywhere and do not feel tempted to click on it.

### How it works now
Clicking on a CASA Org's Location in the sidebar menu brings a user to their default home view. 

### How it should work instead
Location should not be clickable, it should display in the sidebar menu as static data.

**Comment by gabrielbaldao** [comment]
Can I work in this case?

**Comment by compwron** [comment]
@gabrielbaldao yes! :)
