### ISSUE TITLE
Names should not be clickable under "Assigned to" for volunteers

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1269]
AS a **volunteer**,
I WANT to see my name (and the names of any other volunteers assigned to my `casa_case`), 
but I SHOULD NOT be able to click on them,
BECAUSE I do not have permission to edit that page. 

### How it works now
Volunteers can click on names under "Assigned to" in the "My Cases" view, but when they do, they get an error message: _Sorry, you are not authorized to perform this action._
![Screen Shot 2020-11-05 at 5 25 35 PM (2)](https://user-images.githubusercontent.com/62810851/98315042-1994d980-1f8c-11eb-8c2d-55fd70eee0d9.png)

### How it should work
Names under "Assigned to" in "My Cases" should _not_ be clickable for volunteers (but they _should_ remain clickable for admins and supervisors).

**Comment by AngeVeza** [comment]
Hey @metamoni, thank you so much for taking on this issue! 👏 
I just tested this in QA and was still able to click on the volunteer name under assigned to while logged in as volunteer. Any idea what's going on?

![Casa3](https://user-images.githubusercontent.com/73323436/98889541-c1644880-245f-11eb-8553-57a76ccc92da.JPG)

**Comment by littleforest** [comment]
@AngeVeza this hadn't been deployed to QA yet, but it should be there now if you want to take another look!
