### ISSUE TITLE
give buttons room to breathe on mobile

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1274]
AS any user,
I WANT there to be more space between buttons and buttons and buttons and other things,
SO THAT it is easier to click on the thing I want to click on – and not the thing next to, on top of, or under it.

### Environment
staging, mobile web, Firefox, Safari, and Chrome

### Where does/should this occur on the frontend?
Most places where there are buttons:
- "New Supervisor" button in Supervisors view for admins
- "Pick displayed columns" button in Cases view for admins/supervisors

### How it works now
There is no space between many buttons on mobile web. It's hard to tell where one button ends and another part of the UI begins.
![IMG_D0345D6F0DC0-1](https://user-images.githubusercontent.com/62810851/98320441-d04a8700-1f97-11eb-829d-3c93aae5be8e.jpeg)

### How it should work instead
There should be a clear space between buttons and other objects on mobile web, so it's obvious what the user is clicking on.

**Comment by bjthompson805** [comment]
I'll take this.

**Comment by bjthompson805** [comment]
@Zrrrpy, I'm not seeing the issue with the "Pick displayed columns" button in Cases view for admins/supervisors. Here's what I see (the buttons don't seem to run into each other like they do on some of the other pages).

![image](https://user-images.githubusercontent.com/40772561/103598518-0b960300-4ec0-11eb-889c-36da0c360c6d.png)

**Comment by mdr-uma** [comment]
Hi, Is this still available? If yes, I will take this :)

**Comment by littleforest** [comment]
@mdr-uma I think this might have gotten fixed with some previous work that was done, but please take a look to confirm.  If it is no longer an issue I think we have some other front-end tasks available.
