### ISSUE TITLE
log out button lost on mobile web for admins

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1275]
AS an **admin**,
I WANT to see the log out button in my left sidebar menu on mobile web,
SO THAT I can log out.

### Environments
staging, mobile web, Safari, Chrome, and Firefox

### Where does/should this occur on the front end?
In the left sidebar menu.

### How it works now
There are so many items in the sidebar menu for admins, that the logout button at the bottom is hidden. The sidebar menu is not easy to scroll through (sometimes impossible), so the user can not scroll down to reach the log out button, either.

### Screenshots and screengrabs of current behavior
![IMG_6D712CAB9BC7-1](https://user-images.githubusercontent.com/62810851/98320865-a3e33a80-1f98-11eb-8792-25878662569d.jpeg)
**Safari**
![Safari](https://user-images.githubusercontent.com/62810851/98322298-f40fcc00-1f9b-11eb-9e87-2ed33dbe5d4d.gif)
**Chrome**
![Chrome](https://user-images.githubusercontent.com/62810851/98322371-186ba880-1f9c-11eb-936e-fe32b96b5a22.gif)

### How it should work
Admins should be able to easily access the log out button on mobile web.

**Comment by khiga8** [comment]
I'm assigned to this other [issue](https://github.com/rubyforgood/casa/issues/1273) to fix the log out behavior on mobile, but I'm blocked by this issue! I'm going to unassign myself from the other one and assign myself to this one first!
