### ISSUE TITLE
[bug] PROD - ActiveModel::UnknownAttributeError: unknown attribute 'remember_me' for User.

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1278]
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1604732588177900
Event in production from casa in users/sessions#create (details)
Unhandled error
ActiveModel::UnknownAttributeError: unknown attribute 'remember_me' for User.
Location
vendor/bundle/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/attribute_assignment.rb:52 - _assign_attribute

**Comment by littleforest** [comment]
Ref #1234. Same IP address for this error instance. I'm assuming there is no one from Russia who we would expect to be logging in to the production server?
