### ISSUE TITLE
re-add simplecov -> codeclimate coverage reporting

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1304]
It was removed in https://github.com/rubyforgood/casa/pull/1288 and we want it back
See the readme badge for our codeclimate page - that is where we should see simplecov metrics reflected.

**Comment by cam-benfield** [comment]
@compwron , apologies for my multiple comments on multiple issues here. I'm looking for an issue and verifying that they're still issues by oldest to newest. This does appear to have been resolved, but I noticed that our code is throwing some duplication issues that it really shouldn't be.

Well, not unless we're going to start creating issues for minor duplication issues. (I.e. 4 lines of code that look really similar but do different things.) Think: creating a judge vs. creating a hearing. So I'm thinking the CodeClimate settings need to be adjusted, likely the mass, but that's a bit outside of my scope.
