### ISSUE TITLE
Remove "Other type text" from new case contact success page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#131]
part of epic #3

**What type of user is this for? [volunteer/supervisor/admin/all]**
volunteer

**Where does/should this occur?**
On the page a volunteer views after successfully creating a new `case_contact`.

**Description**
"Other type text" should not display here. Can be removed entirely.

**Screenshots**
<img width="1237" alt="volunteer_bug" src="https://user-images.githubusercontent.com/62810851/79701543-d6268800-8252-11ea-884c-593e843db965.png">

**Comment by colinsoleim** [comment]
Fixed in PR #151
