### ISSUE TITLE
Can't access CASA case page

### ISSUE THREAD

**Issue by AngeVeza** [rubyforgood/casa#1319]
As any user,
when I click on CINA-00-1151,
I want to be taken to that CASA case page,
so that I can view and edit CASA case details.

Environment,
QA chrome

How it works now:
when I click on CINA-00-1151 (`casa_case 454`), I see the following error message.
![Screen Shot 2020-11-11 at 6 12 49 PM (2)](https://user-images.githubusercontent.com/73323436/98887664-08e8d580-245c-11eb-994e-8fd651173457.png)

How it should work:
when I click on CINA-00-1151, I should be taken to the corresponding CASA case page.

**Comment by littleforest** [comment]
@Zrrrpy I fixed this issue directly on the QA site and made two follow up tasks related to what caused this issue:

#1322 
#1323

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro
