### ISSUE TITLE
Hearing_types only display on case details if admin has added hearing_types to casa_org

### ISSUE THREAD

**Issue by AngeVeza** [rubyforgood/casa#1320]
As any user, 
when my casa_org has no hearing_types,
I do not want to see hearing_types on case details page,
so that I am not confused by fields that irrelevant to my casa_org.

Environment:
QA

How it works now:
When I am logged in as any user,
I see hearing_types on the edit case details page.
<img width="961" alt="Casa1" src="https://user-images.githubusercontent.com/73323436/98888818-4d757080-245e-11eb-8c70-87149b030c85.PNG">

How it should work:
If my casa_org has no hearing_types,
then I should not see hearing_types on the edit casa case details page.

**Comment by Zrrrpy** [comment]
@AngeVeza turns out this does work, we were just testing in a `casa_org` instance that _does_ have `hearing_types`, so going to close out. :)
