### ISSUE TITLE
Supervisors should not be able to assign cases that belong to a different organization

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#1322]
**What is the problem, and what should happen instead?**

* Verify that supervisors can not view or assign cases that belong to a different organization
* Add specs if they don't exist

**Screenshots of current behavior, if any**

Places a supervisor can view or assign cases:

<img width="1344" alt="Screen Shot 2020-11-11 at 7 21 25 PM" src="https://user-images.githubusercontent.com/1938665/98891555-4c8b1180-2453-11eb-8d0b-15b7d4df6d3e.png">

<img width="1346" alt="Screen Shot 2020-11-11 at 7 22 34 PM" src="https://user-images.githubusercontent.com/1938665/98891559-50b72f00-2453-11eb-8797-25d7cafd411d.png">

**Comment by patrickarnett** [comment]
Can I grab this one?

**Comment by littleforest** [comment]
It's yours!

**Comment by patrickarnett** [comment]
@littleforest It should also be required that a `volunteer` and their `supervisor` belong the the same `casa_org`, right?

**Comment by littleforest** [comment]
@patrickarnett yes!

**Comment by patrickarnett** [comment]
@littleforest This scope returns any `user` (not just `volunteers`) within the `casa_org` who is not currently assigned a supervisor. So, e.g., a `supervisor` without a `supervisor` would be included. Is that a bug?
https://github.com/rubyforgood/casa/blob/c84b0e9261f83654d79ce1dd1f73dc392258729e/app/models/user.rb#L28-L35

Is this the right way to ask questions like this, or should I use the casa slack channel?

**Comment by patrickarnett** [comment]
It's only called on the `Volunteer` class, so I'll move it there.

**Comment by littleforest** [comment]
@patrickarnett sounds good to move it to the Volunteer class. Asking questions here is fine, or also slack channel is okay too!
