### ISSUE TITLE
Add validation to ensure that volunteers can't be assigned casa cases from a different organization

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#1323]
**Description**

On our QA site, we have at least one casa case that is assigned to a volunteer but belongs to a different organization than the volunteer.  This error may have occurred during seeding. Add a validation that ensures that volunteers are in the same organization as the casa case to which they are assigned.

**Comment by patrickarnett** [comment]
May I?

**Comment by littleforest** [comment]
Absolutely, thanks!
