### ISSUE TITLE
[bug] Downloading report with these settings throws exception

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1333]
**What is the problem, and what should happen instead?**
Example exception: https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1605317614092000

**Screenshots of current behavior, if any**
![Screen Shot 2020-11-13 at 5 33 18 PM (1)](https://user-images.githubusercontent.com/578159/99137311-d1eefd00-25de-11eb-8e0f-d9db882fa123.png)
![Screen Shot 2020-11-13 at 5 33 36 PM](https://user-images.githubusercontent.com/578159/99137313-d3b8c080-25de-11eb-88c3-981a678ae66a.png)

**Comment by rogesson** [comment]
Hello @compwron!

I will work on it :)

**Comment by littleforest** [comment]
Great, thanks @rogesson !
