### ISSUE TITLE
make seed data multi-CASA

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1338]
**Description**
Update seed to, on all but lowest data setting, create at least 2 CASAs **with different-looking data** so we can find cross-CASA bugs.

**Comment by cam-benfield** [comment]
@compwron , I'll take this one. I'm pretty sure it's solved, but I'll verify before marking as closed.

**Comment by cam-benfield** [comment]
Looks like it's solved, at least for the standard dev seed data.
![image](https://user-images.githubusercontent.com/33261934/119982849-5e667900-bf8d-11eb-8c92-47831f082a3f.png)
