### ISSUE TITLE
paginate db query results and use that pagination on the frontend

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1352]
**What type of user is this for? volunteer/supervisor/admin/all**
all, but improvements will be most visible for supervisor and admin

**Description**
paginate db query results and use that pagination on the frontend
The point of this is to make page load faster for supervisor & admin
This was prompted by https://ideaboardz.com/for/R4G%20CASA%20Nov%202020%20retro%2Ffuturespective/3512118

**Screenshots of current behavior, if any**

**Comment by patrickarnett** [comment]
Can I jump on this one?

**Comment by patrickarnett** [comment]
@compwron This spec is actually testing that the cell is blank when the joining `supervisor_volunteer` is inactive. Should the cell be blank when the `supervisor` itself is inactive, as well?
https://github.com/rubyforgood/casa/blob/b29b1427b1a6e92fbb74468ac744f84ba0a767f8/spec/system/admin_views_volunteers_page_spec.rb#L141-L151

**Comment by compwron** [comment]
Yes, if the volunteer's supervisor is inactive then this cell should be blank.
The cell should also be blank if the volunteer used to be, but is no longer associated to the supervisor i.e. what it's actually testing now)

**Comment by patrickarnett** [comment]
It's outside the scope of this issue, but should the deactivation of a `supervisor` or `volunteer` in turn deactivate any associated `supervisor_volunteers` and/or `case_assignments`?

**Comment by compwron** [comment]
Closing this because it is done in PR #1412
