### ISSUE TITLE
Automatically remove Help Wanted issue label for issues in-progress/qa/later-columns

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1362]
AS a maintainer of this project,
I WANT the `help wanted` label to automatically be removed from issues in the `in-progress` column or any columns following that one,
SO THAT I do not need to manually remove the `help wanted label` from these issues. 

### Proposed solutions & approach
This is probably a github actions thing

Maybe we could make a cronjob github action that runs every few hours and [finds all issues in project columns](https://docs.github.com/en/free-pro-team@latest/rest/reference/projects#list-project-cards) and then [remove label from issue](https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#remove-a-label-from-an-issue)

**Comment by bjthompson805** [comment]
I'll take this as well, since it's related to #1363.
