### ISSUE TITLE
Automate adding Help Wanted label to every issue in project board "TODO" column

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1363]
This would be a big win for contributor friendliness!

Tools that might be able to help us do this:
https://github.com/philschatz/project-bot
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-automation-for-project-boards
https://github.com/marketplace/actions/manage-issue-labels

**Comment by bjthompson805** [comment]
I'll take this.
