### ISSUE TITLE
Create a Dockerfile that only hosts the db - for local development

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1366]
This came from our retro board
If we do this, I would like to have some way of testing our docker files

> Could we get a docker setup just for the database?  In the docs the setup you either have to go full on with using only the docker (web+database) or go full local for development.
> In various projects I worked on the faster dev setup would involve running the app locally and using the docker for the database. I could not quite get that to work with current docker-compose setup.

@littleforest this is just an idea. What do you think?

**Comment by littleforest** [comment]
I haven't done this before but I will try it out!
