### ISSUE TITLE
Download just notes from a casa case as a word document

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1367]
**What type of user is this for? volunteer/supervisor/admin/all**
all (most important for volunteer)

**Description**
The purpose
On the Casa Case page, there should be a "download all notes" button (model this after the generate/download on Court Report page). This should download all the notes (also with date of note creation) for that casa case, with the case number at the top of the doc
The doc can be a txt file or word doc, but the stakeholders would prefer a word doc

Example url: 
https://casa-qa.herokuapp.com/casa_cases/1072
![Screen Shot 2020-11-18 at 8 45 16 PM](https://user-images.githubusercontent.com/578159/99622440-00a21480-29df-11eb-9147-a3f5720f89c7.png)

**Comment by GuillermoCoding** [comment]
Hello, picking this up! 😄

**Comment by littleforest** [comment]
Great, thank you!

**Comment by compwron** [comment]
@GuillermoCoding are you still working on this? :)

**Comment by GuillermoCoding** [comment]
Hi @compwron, I was just about to post a comment on this issue and unassign myself to see if anyone else wants to pick it up (: it's been busy this last couple of weeks for me, and don't think I will have some time to work on it for now. Hoping someone else can work on this! 😄

**Comment by compwron** [comment]
Very cool. No worries. :) We'll be here when you have time!! 💖
