### ISSUE TITLE
Exclude unassigned volunteers from “no contact in 14 days” Admin dashboard

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1370]
On the Admin's dashboard, volunteers who have been *unassigned* from the supervisor are showing up in the “no contact in 14 days” count. Exclude unassigned volunteers from the count. 

Example url: https://casa-qa.herokuapp.com/supervisors
![Screen Shot 2020-11-18 at 11 22 40 PM](https://user-images.githubusercontent.com/578159/99634301-191d2980-29f5-11eb-8901-a62107a32832.png)

**Comment by stufro** [comment]
I was going to offer to pick this up - however I'm unable to recreate the bug. I unassigned a volunteer who had no case contacts for 14 days and the number on the dashboard decreased. Let me know if I've misunderstood.

**Comment by littleforest** [comment]
@stufro thanks for taking a look! I wasn't able to reproduce either. @compwron is there a specific example you are seeing on the QA site that is a problem?

**Comment by Zrrrpy** [comment]
@compwron have you been able to verify the query includes unassigned volunteers? I tested this manually after Power folks worked on it and it was _not_ including unassigned volunteers at that time. 

Let's close this out if it's working as it should!

**Comment by pollygee** [comment]
@Zrrrpy looks like maybe this can be closed out?  Except it looks like you moved it from not ready to build into TODO so maybe you do want it worked on, were you able to reproduce?

**Comment by Zrrrpy** [comment]
I just moved it over to that column to make it easier to drag it up to a different spot in the to-do column. (Dragging issues up and down columns in GitHub is painful.)

I haven't been able to reproduce since our last fix related to this query, but I believe @compwron has. If not, we can close it out.

**Comment by compwron** [comment]
Closing as obsolete
