### ISSUE TITLE
Scope per casa org in CaseContactPolicy

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1371]
There should never be `.all` only `.where(casa_org: @user.casa_org)` in this code and code like it

Add tests to go with this change

```
 def resolve
      case @user
      when CasaAdmin # scope.in_casa_administered_by(@user)
        scope.all
      when Volunteer
        scope.where(casa_case: CasaCase.actively_assigned_to(@user), creator: @user)
      when Supervisor
        scope.all
      else
        raise "unrecognized user type #{@user.type}"
      end
```

**Comment by gabrielbaldao** [comment]
Can I work in this case?

**Comment by littleforest** [comment]
Absolutely!

**Comment by gabrielbaldao** [comment]
Will be `.where(casa_org: @user.casa_org)` for `CasaCasePolicy`, `CaseAssignmentPolicy`, `CaseContactPolicy` and `UserPolicy`? @compwron

**Comment by littleforest** [comment]
@gabrielbaldao yes that sounds right! And you can use `current_organization` which is defined [here](https://github.com/rubyforgood/casa/blob/main/app/controllers/concerns/organizational.rb#L11-L13) instead of `@user.casa_org`.
