### ISSUE TITLE
Add validation for court_report fields

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#1389]
**Description**
There are two related fields on the `casa_case` model, the `court_report_submitted_at` and `court_report_status` field. Add a validation to make sure that:

1. If `court_report_submitted_at` is not null, then `court_report_status` is something other than "not submitted"
2. If `court_report_submitted_at` is null, then `court_report_status` is "not submitted"

**Comment by Rockenfels** [comment]
I'm working on this issue
