### ISSUE TITLE
Sort Contact Types on Edit Organization Page

### ISSUE THREAD

**Issue by SMJ289** [rubyforgood/casa#1390]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
Add ability to sort *Contact Types* by Name, Group, or both to make it easier for the user to navigate the somewhat lengthy list.

**Screenshots of current behavior, if any**
![Screen Shot 2020-11-24 at 4 08 38 PM](https://user-images.githubusercontent.com/57697706/100156881-52c7b780-2e6f-11eb-8878-94e3b6cf9331.png)

**Comment by compwron** [comment]
I just checked and this still needs doing. I'm going to assign this to our new dev @kylemckenzie88
![casa-sort](https://user-images.githubusercontent.com/578159/107273862-7cbb5f80-6a04-11eb-941c-5eb2f053990c.png)

**Comment by kylemckenzie88** [comment]
Hello, I am new here and ready to help

**Comment by compwron** [comment]
@kylemckenzie88 How's it going in there? :)
