### ISSUE TITLE
Add Tests for Creating and Editing Contact Types

### ISSUE THREAD

**Issue by SMJ289** [rubyforgood/casa#1391]
Pairs well with #1255 

**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
Add tests to cover creating and editing *Contact Types*
Note: there is no delete functionality to maintain data integrity with existing records.

**Screenshots of current behavior, if any**
![Screen Shot 2020-11-24 at 4 27 09 PM](https://user-images.githubusercontent.com/57697706/100158734-42fda280-2e72-11eb-9841-0991462a0835.png)

**Comment by SMJ289** [comment]
I'll probably just tackle adding these tests while addressing issue #1255.

**Comment by compwron** [comment]
@SMJ289 are you still working on this? :)

**Comment by SMJ289** [comment]
@compwron hey, sorry I started an internship and have been preoccupied with that! Wow, it's been a while since I assigned myself this. I would be happy to pass it along. I figured out the other sorting ticket #1255 and could quickly commit and push that change but these tests will take a lot more time to implement.

**Comment by compwron** [comment]
@SMJ289 No worries! Congrats on the internship :) :)

**Comment by cjilbert504** [comment]
@compwron I'd like to give this a go if that's cool!

**Comment by compwron** [comment]
All yours, go for it :)

**Comment by efgalvao** [comment]
So, need to add some tests creating and editing contact types logged in as an admin  ?
Can i try this one ?

**Comment by compwron** [comment]
@efgalvao Yep exactly! All yours :)
