### ISSUE TITLE
Block Duplicate Contact Type Entries

### ISSUE THREAD

**Issue by SMJ289** [rubyforgood/casa#1392]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
Add a check to block duplicate *Contact Types* being created per `casa_org` by organization admins.
Edit Organization page  (i.e. `/casa_orgs/1/edit`)

**Screenshots of current behavior, if any**
What we don't want to happen:
![Screen Shot 2020-11-24 at 4 46 58 PM](https://user-images.githubusercontent.com/57697706/100160172-ac7eb080-2e74-11eb-966a-8227bb719e05.png)

**Comment by hiendinhngoc** [comment]
I am working on this issue
