### ISSUE TITLE
Clicking near Parent checks the Youth box when the screen is a certain size - see screenshot

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1395]
**What is the problem, and what should happen instead?**
Clicking near Parent checks the Youth box when the screen is a certain size - see screenshot

**Screenshots of current behavior, if any**
![Screen Shot 2020-11-25 at 6 31 13 PM](https://user-images.githubusercontent.com/578159/100301168-757bce00-2f4c-11eb-81b5-4ebd3513178b.png)

**Comment by Zrrrpy** [comment]
@compwron I think once #1274 is done this _should_ be resolved as long as it's only happening on mobile. Thoughts on closing this and reopening if it's still happening once #1274 is done?
