### ISSUE TITLE
Add clarifying UI about what case contacts will be in the court report

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1396]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer

**Description**
Court reports are every 6 months

Court date for this user is not set https://casa-qa.herokuapp.com/casa_cases/1072

What case contacts should show on the court report? Everything since the last court date. If there is not last court date, everything. 

Do not add a date range choice for now- it's easier to delete extra stuff. 

This issue is probably in file `app/models/case_court_report.rb`

**Screenshots of current behavior, if any**
![Screen Shot 2020-11-25 at 6 34 56 PM](https://user-images.githubusercontent.com/578159/100301473-0d79b780-2f4d-11eb-81ba-28c8f0c060d4.png)
![Screen Shot 2020-11-25 at 6 36 15 PM](https://user-images.githubusercontent.com/578159/100301563-3c902900-2f4d-11eb-9a7a-9b29ca9f1236.png)
![Screen Shot 2020-11-25 at 6 37 05 PM](https://user-images.githubusercontent.com/578159/100301572-3e59ec80-2f4d-11eb-8ed2-21861e375d6a.png)

**Comment by compwron** [comment]
This could use some clarification

**Comment by erik-trantt** [comment]
@compwron I can see that those contacts without any contact types are not showing up in the court report. Is this the issue you mentioned?

**Comment by compwron** [comment]
@erik-trantt aha yes that makes sense that the contacts without contact types would not show up. All contacts should have at least 1 contact type. I suspect that we have weird data in prod that is the cause of that bug- I'll make sure that we take care of that.

**Comment by erik-trantt** [comment]
@compwron Cool 👍 . Then I think we should add validation on that in the CaseContact model. It currently has the association `has_many` but no validation. What do you think?

**Comment by compwron** [comment]
@erik-trantt sounds good but make sure the validation is on save and doesn't prevent showing existing data, or include a `after_party` to set to "unknown" or similar

**Comment by erik-trantt** [comment]
I'm running into these findings:
  - It currently has a validation in JavaScript `app/javascript/src/case_contact.js`. My gut tells me that the weird data you mentioned might have been there before the JavaScript validation.
  - After add that validation to CaseContact model, existing case contacts are still showing and editable, including those without any contact types
  - but, 4 tests fail for not passing the new validation:
      ```bash
      Failed examples:
      
      rspec ./spec/seeds/seeds_spec.rb:29 # Seeds test development DB successfully populates all necessary tables
      rspec ./spec/system/case_contacts/edit_spec.rb:32 # case_contacts/edit when volunteer is successful
      rspec ./spec/system/case_contacts/edit_spec.rb:9 # case_contacts/edit when admin admin successfully edits case contact
      rspec ./spec/requests/case_contacts_spec.rb:31 # /case_contacts POST /create with valid parameters does create two new CaseContacts
      ```

I can update those tests, but do you think it worths a shot?

---

Validate using JavaScript:
![image](https://user-images.githubusercontent.com/44339322/102364742-e45bbc80-400a-11eb-8d27-9d3873605318.png)

Validate on save:
![image](https://user-images.githubusercontent.com/44339322/102364963-297fee80-400b-11eb-9692-07bab2e336d7.png)

**Comment by compwron** [comment]
Closing as done+stale
