### ISSUE TITLE
supervisor/admin can download already-generated court reports

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1398]
As a **supervisor or admin**,
I want the ability to download the most recently generated court report associated with a court date,
so that I can easily access these records when necessary for administrative purposes.

### How it works now
After a volunteer generates a court report, no user has the ability to re-download that report which has already been generated. 

### How it should work instead
Supervisors and admins should have the ability to access the most recently generated court report associated with a court date.

### Acceptance criteria
Part 1
- [x] IF `court_report_status` is `submitted` AND volunteer has generated a court report ever, THEN the hyperlinked text "Click to download" appears next to `court_report_status` on CASA Case Details page.
- [x] Clicking the hyperlinked text "click to download" triggers a download of the most recently generated court report associated with that `casa_case`

Part 2
- [ ] The dates are hyperlinked and clickable under "Past Court Dates" (this currently lives on the Edit CASA Case page)
- [ ] Clicking on a past court date triggers a download of the most recently generated court report associated with that court date. 
- [ ] "most recently generated court report associated with that court date" means... 
- court report was generated on or before the court date 
- but _after_ the court date that came before it. (An exception to this rule should be made for the first ever court date.)

**Comment by khiga8** [comment]
Hey! Just wanted to clarify: 

> I want the ability to download the most recently generated court report associated with a court date
- This generated report refers to the prefilled report volunteer may auto-generate from the `/case_court_reports` page.

> Supervisors and admins should have the ability to access the most recently generated court report associated with a court date.
- This refers to the auto-generated report from above.

I might be mistaken but looking at `app/controllers/case_court_reports_controller.rb`, it doesn't look like we actually save those generated court reports anywhere in our database so I'm unsure how we would get the `already-generated` report. `CasaCaseReport` is not an active record model. Am I missing something? Thanks a bunch!

**Comment by compwron** [comment]
i agree that CasaCaseReport isn't a model right now... but it will need to be in the future! I think you're going to get to make a db migration :)

**Comment by compwron** [comment]
Sorry, I moved this by accident but then I put it back :)

**Comment by khiga8** [comment]
https://github.com/rubyforgood/casa/pull/1650#issuecomment-770536668

Not doing part 2 for now! I'm gonna unassign myself... or maybe I should close this issue?

**Comment by Zrrrpy** [comment]
We can keep it open for now. Thank you for checking though, @khiga8!

**Comment by rpolley** [comment]
Going to take a stab at part 2 here.

**Comment by Zrrrpy** [comment]
Thank you, @rpolley!

**Comment by rpolley** [comment]
I'm not terribly familiar with this whole workflow so I having a bit of trouble replicating it in order to figure out how I'd add this. How does this functionality currently work? How does a volunteer generate and then submit a report in the first place?

**Comment by Zrrrpy** [comment]
Hey @rpolley, thank you again for dedicating time to this!

Currently, [only volunteers can generate court reports](https://www.youtube.com/watch?v=rKMu_ZVnzAc&list=PL8QvMNw9IqiFZRL6CbBhn2y5QKwdkd35p&index=5) – and they can only generate them for their active case assignments.

Volunteers submit court reports _off platform_, and once a supervisor receives it, they change the court report status _on platform_ (on the case details page) to "submitted".

Please let me know if you have any more questions about this flow!

**Comment by khiga8** [comment]
Hey @Zrrrpy @rpolley! I added a [comment](https://github.com/rubyforgood/casa/pull/1650#issuecomment-770536668) about why I wasn't sure whether to pursue Part 2 of this. 
Currently we're only saving one report ever so we weren't sure whether it made sense to add a hyperlink to court report dates given there's only ever one. Given this, maybe the requirements should change a bit or there needs to be some more prework?

**Comment by Zrrrpy** [comment]
Thank you @khiga8! For context on why we haven't moved forward on part two, we haven't yet determined whether or not storage is going to be an issue when court reports start accumulating. (We are currently relying on free Azure credits for this, and I'm not certain of how far they will stretch now that our second tenant is on the platform with more to come.) 

This is still open because it is something we'd like to implement, we just need to determine whether or not we should at this point in time given our storage situation.

I will follow up with @pollygee and @compwron to get their opinions so we can move forward one way or another.

**Comment by compwron** [comment]
It is sounding like we are ok on storage! Let's do it!

**Comment by Zrrrpy** [comment]
@rpolley you've got the go ahead to move forward with this! 

See the details in the ticket above under "Part 2" and let me know if you still have questions about the flow. 😃

**Comment by rpolley** [comment]
for whatever reason whenever I generate a report the downloaded "docx" file is just a plaintext file containing something like `#<File:0x00007f1cba003ee8>` any idea what's going on here?

**Comment by compwron** [comment]
@rpolley that is a recent bug that has been fixed in main. Rebasing your branch on main will fix it. Sorry about that.

**Comment by compwron** [comment]
Here is the fix https://github.com/rubyforgood/casa/blob/4495a1feb15d6a1effd38f5207f8166cf606e8c4/app/controllers/case_court_reports_controller.rb#L25
