### ISSUE TITLE
Add a row to the Admin dashboard summary of supervisors for volunteers not assigned to supervisors

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1400]
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**

Add a row to the Admin dashboard summary of supervisors for volunteers not assigned to supervisors

Do not show the row if there are no volunteers not assigned to supervisors

Make sure to only count *active* volunteers and *active assignments*

Note: CASA normal operation there should not be any volunteers not assigned to supervisors... but this code is for seeing when something funny is happening :)

**Screenshots of current behavior, if any**
https://casa-qa.herokuapp.com/supervisors
![Screen Shot 2020-11-25 at 7 35 35 PM](https://user-images.githubusercontent.com/578159/100305201-6a796b80-2f55-11eb-9483-a6603509ff44.png)

**Comment by notapatch** [comment]
re "add a row": I'm confused, do you mean "add a column"?

**Comment by rpolley** [comment]
So from the sound of it this would be a "row" for a supervisor that doesn't exist that volunteers with no supervisor would be assigned to? I feel like if this is something that doesn't occur under normal circumstances then mixing it with the normal data would just confuse people when it happened, and that it should be some sort of warning message that appears outside of the table.

**Comment by compwron** [comment]
@rpolley @notapatch correct, a row for volunteers not assigned to a supervisor. This should not usually happen but if it does, it will certainly be data that the users will want to know about. It does not currently need an included warning message.

**Comment by rpolley** [comment]
@compwron I feel like it should at least be made to stand out from the other rows somehow.

**Comment by rpolley** [comment]
@compwron maybe something like using the `table-warning` [contextual class](https://getbootstrap.com/docs/4.0/content/tables/#contextual-classes) to make the row stand out better?

**Comment by compwron** [comment]
@ErinClaudio `app/views/supervisors/index.html.erb`

**Comment by ErinClaudio** [comment]
@compwron, I am stumped with this issue. 

- I am receiving `undefined method` errors and have tried what I could find on StackOverflow to resolve this with no luck

I am too unfamiliar with the SupervisorVolunteer model and controller. I would love to chat about this Wednesday or whenever you have a moment.

**Comment by compwron** [comment]
Cool cool :) lmk

**Comment by librod89** [comment]
@compwron, is there anything left to do for this ticket? This is the current state of the Supervisors page

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/4965672/118664781-5e10f580-b7b7-11eb-92b6-8bbeb99c6bdd.png">
