### ISSUE TITLE
Your account has lost access to your connected GitHub account

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1401]
https://dashboard.heroku.com/pipelines/ab5437b7-b7da-4204-bcfc-33bac4466347

I see a message in heroku
> Your account has lost access to your connected GitHub account
> Apps and pipelines connected to your GitHub account will not work until you reconnect

But the PR I merged an hour ago did successfully deploy to QA. So... maybe we don't care?
![Screen Shot 2020-11-25 at 7 50 09 PM](https://user-images.githubusercontent.com/578159/100306134-80882b80-2f57-11eb-8e5f-824cf3b50e75.png)

**Comment by littleforest** [comment]
This seems to have fixed itself, and maybe was an issue on Github's end? The apps are connected to their repositories.

<img width="1655" alt="Screen Shot 2020-11-27 at 8 22 15 AM" src="https://user-images.githubusercontent.com/1938665/100468653-b3324100-3089-11eb-841a-727af67429d8.png">
