### ISSUE TITLE
Move all date formats to il8n

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1408]
Do this https://github.com/rubyforgood/casa/pull/1402#discussion_r531743219

Syntax we want to use: `format: :day_and_date`

**Why?**
- You can name the keys whatever you like using i18n
- One of the benefits of using i18n is that if you internationalize the application, then it's easy to have dates display in formats used by other countries/languages <- even if CASA doesn't need this, it's good for CASA contributors to get used to good ways of doing things. :)

**Comment by bjthompson805** [comment]
@compwron I'm going to give this a shot.

**Comment by littleforest** [comment]
Great!

**Comment by bjthompson805** [comment]
For this are you looking to move all of the formats in date_format.rb into en.yml, or do you want to use the existing day_and_date for everything?

**Comment by littleforest** [comment]
Please move all of the formats in the `date_format.rb` ento `en.yml`. You can also rename `day_and_date` to something else if you need to.
