### ISSUE TITLE
Automate github issue weekly "is this still in progress?" checkins 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1409]
Automate github issue weekly "is this still in progress?" checkins on "in progress" github issues without recent comments / commits. After two weeks (14 days) of checking-in and no comments or PRs, unassign the assignee and move the issue back to "to do" (automate as many parts of this as possible! Anything is better than nothing :) )

This is (hopefully) possible with github actions

**Comment by bjthompson805** [comment]
@compwron I'm gonna give this a go.

**Comment by bjthompson805** [comment]
Are you thinking to create a new custom github action for this, or is there one out there? I don't see any on the marketplace but I did find this which would work, just need to fork it and modify it:

https://github.com/JasonEtco/slash-assign-action

**Comment by compwron** [comment]
I'm *hoping* that we don't need to fork anything to do simple "Hello are you working on this" on ALL open PRs (irregardless of recently-updated state) - just setup a cron "scheduled action" 

To detect recent activity might take a script with some github API usage in addition (or a forked action)

To auto-unassign we will need github API usage (or a forked action)

I would be very happy with the Simplest Possible Thing as a starting point

In general, everything we fork, we have to maintain for our own use... (or accept that it might stop working eventually and either we delete it or fix it) and I would like to keep our surface area small where possible
But if forking would make it work, do itttt :)

**Comment by bjthompson805** [comment]
Wouldn't we want to comment on open ISSUES instead of PRs because the issue may not have a PR but may need to be unassigned?

**Comment by compwron** [comment]
@bjthompson805 good point, it should be issues.
