### ISSUE TITLE
Auto-run new migrations in heroku on deploy

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#142]
Right now, if any PR including a migration is merged, heroku autodeploy does not run the migration. Then staging probably stops working because there is code that depends on a missing column, and @compwron is currently the only person with heroku permissions on staging to run 
```
heroku login
heroku run rake db:migrate
```
This is not ideal. Automate this. 

Notes:
tundal45
it looks like they support a feature called releases that gives us this ability once we add a Procfile to the repo

**Comment by compwron** [comment]
this still needs doing

**Comment by tundal45** [comment]
Yes, it's on my list to do this weekend but if other folks are interested in taking this on before that, feel free!
