### ISSUE TITLE
[bug] supervisor unable to re-assign case to volunteer

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1432]
**What is the problem, and what should happen instead?**
on QA, supervisor1 is unable to assign case CINA-00-1015 to volunteer72 https://casa-qa.herokuapp.com/volunteers/1213/edit but should be able to, because the case is active https://casa-qa.herokuapp.com/casa_cases/1190
Could this be because the case *used* to be assigned to that volunteer, and has been unassigned from the volunteer? 

**Screenshots of current behavior, if any**
![Screen Shot 2020-12-09 at 6 54 58 PM](https://user-images.githubusercontent.com/578159/101715424-47b87e00-3a50-11eb-95a0-e0c65bdf560a.png)

**Comment by edwja** [comment]
It turns out that @compwron was correct.  The Volunteer edit side does not include previously assigned, inactive cases when looking for unassigned cases to present is the list of assignable cases.

**Comment by Zrrrpy** [comment]
Thank you for investigating and confirming, @edwja! 🕵️‍♂️  We definitely want volunteers to be able to get reassigned to cases that may have previously been assigned to them, as long as they're active. Are you up to take this on?

**Comment by edwja** [comment]
Yes!
