### ISSUE TITLE
Do not show inactive assignment or inactive case to volunteers. Do not include in supervisor weekly digest. 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1438]
**What is the problem, and what should happen instead?**
function `case_assignments_with_cases`
contains `case_assignments.includes(:casa_case)`

called by `views/volunteers/edit.html.erb` on line 80
and `views/supervisor_mailer/weekly_digest.html.erb `on line 15

**Acceptance criteria:**

- [ ] Volunteer Edit should NOT include casa cases from which the volunteer has been unassigned (inactive assignment)
- [ ] Write a test

- [ ] Volunteer Edit should NOT include **inactive** casa cases (inactive case)
- [ ] Write a test

- [ ] Supervisor email should NOT include cases which are inactive at the time that the mailer is generated (inactive case)
- [ ] Write a test

- [ ] Supervisor email should NOT include cases which have been unassigned from volunteers (inactive assignment)
- [ ] Write a test

- [ ] If a volunteer performs actions 
- - and is unassigned from a supervisor in the same week 
- - and **not** assigned to another supervisor
then the supervisor should see the activity in the email
and the email should indicate that the volunteer is unassigned

- [ ] If a volunteer performs actions 
- - and is unassigned from a supervisor in the same week 
- - and **is** assigned to another supervisor, then the volunteer's old supervisor should not see the volunteer's activity in the email 
- - and the volunteer's new supervisor should see the volunteer's activity in their email

Thanks @FireLemons for finding this! https://rubyforgood.slack.com/archives/CVB0QJGVD/p1607574310223400

**Comment by FireLemons** [comment]
The volunteer edit is actually fine because it already takes into account inactive and unassigned cases. 

What happens if a volunteer performs actions and is unassigned in the same week. Does the supervisor still want to see the activity in the email?

**Comment by compwron** [comment]
That's an interesting question... @Zrrrpy what do you think?

**Comment by compwron** [comment]
@FireLemons 
If a volunteer performs actions 
- and is unassigned from a supervisor in the same week 
- and **not** assigned to another supervisor
then the supervisor should see the activity in the email
and the email should indicate that the volunteer is unassigned

If a volunteer performs actions 
- and is unassigned from a supervisor in the same week 
- and **is** assigned to another supervisor, then the volunteer's old supervisor should not see the volunteer's activity in the email 
- and the volunteer's new supervisor should see the volunteer's activity in their email

**Comment by FireLemons** [comment]
I'm gonna try to do the first part of this  

    SupervisorMailer.weekly_digest(User.third).deliver_now
