### ISSUE TITLE
Calculation of volunteers serving transition aged youth should exclude inactive cases and unassigned cases

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1442]
**What is the problem, and what should happen instead?**
function `volunteers_serving_transition_aged_youth`
contains `volunteers.includes(:casa_cases).where(casa_cases: {transition_aged_youth: true}).size`
called by `views/supervisors/index.html.erb `on line 31

**Acceptance criteria:**
- [ ] Write a test!
- [ ] Exclude inactive cases and unassigned cases

Thanks @FireLemons for finding this! https://rubyforgood.slack.com/archives/CVB0QJGVD/p1607574310223400

**Comment by FireLemons** [comment]
note to self: in `user.rb`
