### ISSUE TITLE
Speed up test suite

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1449]
Our rspecs (and capybaras) are weirdly slow for how small our codebase is. Try to fix that!

Maybe it's factorybot creating too many objects? 

Or bullet, somehow?

Feel free to tune the CI scripts (CI uses Github Actions) if that will help. (but it's slow locally also, so maybe not)
https://github.com/rubyforgood/casa/actions?query=workflow%3Arspec

Or all of the above, or something else! 😅 
plz send halp

**Comment by compwron** [comment]
@scottolsen fyi here's a github issue for the slow spec :)

**Comment by scottolsen** [comment]
After a quick look around, I suspect this is mainly `FactoryBot` creating unneeded associations and Capybara in the system tests. 19 of the 20 slowest tests are system tests and they all take over 1.5 seconds. 

Also, one of the slower [user model specs](https://github.com/rubyforgood/casa/blob/75021c75b01caa2a0f3ddd610d5412a705c96340/spec/models/user_spec.rb#L35) I checked, creates around 50 database records.
```ruby
:casa_org=>{:create=>12, FactoryBot::Strategy::Create=>5}
:hearing_type=>{FactoryBot::Strategy::Create=>5}
:judge=>{FactoryBot::Strategy::Create=>5}
:casa_case=>{:create=>4, FactoryBot::Strategy::Create=>1} 
:case_assignment=>{:create=>5}
:volunteer=>{:create=>2}
:contact_type_group=>{FactoryBot::Strategy::Create=>4}
:contact_type=>{:create=>4}
:case_contact=>{:create=>4}
:user=>{FactoryBot::Strategy::Create=>1}
```

Hoping to dig in a little deeper this weekend.

**Comment by littleforest** [comment]
@scottolsen what did you run to get this fancy report?

**Comment by scottolsen** [comment]
@littleforest Pulled it from [factory_bot](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#activesupport-instrumentation). I need to tweak it so it only runs when a spec is tagged appropriately.

```ruby
  factory_bot_results = {}
  config.before(:suite) do
    ActiveSupport::Notifications.subscribe("factory_bot.run_factory") do |name, start, finish, id, payload|
      execution_time_in_seconds = finish - start

      if execution_time_in_seconds >= 0.5
        $stderr.puts "Slow factory: #{payload[:name]} using strategy #{payload[:strategy]}"
      end
    end

    ActiveSupport::Notifications.subscribe("factory_bot.run_factory") do |name, start, finish, id, payload|
      #one line for each create
      # $stderr.puts "FactoryBot: #{payload[:strategy]}(:#{payload[:name]})"
      factory_name = payload[:name]
      strategy_name = payload[:strategy]
      factory_bot_results[factory_name] ||= {}
      factory_bot_results[factory_name][strategy_name] ||= 0
      factory_bot_results[factory_name][strategy_name] += 1
    end
  end

  config.after(:suite) do
    p factory_bot_results
  end
```

**Comment by scottolsen** [comment]
This is the entire test suite. Orgs really jump out at me as being way higher than it should be. 

```ruby
"casa_org: {:total=>2601, :create=>2085, FactoryBot::Strategy::Build=>45, FactoryBot::Strategy::Create=>463, :build=>1, :build_stubbed=>7}"
"volunteer: {:total=>410, :build_stubbed=>8, :create=>398, :build=>4}"
"casa_admin: {:total=>298, :build_stubbed=>12, :create=>286}"
"user: {:total=>131, FactoryBot::Strategy::Build=>20, FactoryBot::Strategy::Create=>107, :build=>1, :create=>2, :build_stubbed=>1}"
"hearing_type: {:total=>618, FactoryBot::Strategy::Build=>39, FactoryBot::Strategy::Create=>552, :create=>21, :build_stubbed=>6}"
"judge: {:total=>622, FactoryBot::Strategy::Build=>39, FactoryBot::Strategy::Create=>551, :create=>25, :build=>1, :build_stubbed=>6}"
"casa_case: {:total=>597, FactoryBot::Strategy::Build=>20, FactoryBot::Strategy::Create=>136, :create=>416, :build=>19, :build_stubbed=>6}"
"contact_type_group: {:total=>370, FactoryBot::Strategy::Create=>254, FactoryBot::Strategy::Build=>5, :create=>111}"
"contact_type: {:total=>457, :create=>452, :build=>5}"
"case_contact: {:total=>264, :build=>21, :create=>241, :attributes_for=>2}"
"supervisor: {:total=>207, :create=>201, :build_stubbed=>6}"
"supervisor_volunteer: {:total=>67, :create=>67}"
"all_casa_admin: {:total=>31, :create=>31}"
"case_assignment: {:total=>206, :create=>203, :build=>3}"
"emancipation_category: {:total=>34, :create=>25, :build=>9}"
"emancipation_option: {:total=>38, :create=>37, :build=>1}"
"casa_org_logo: {:total=>2, :build=>1, :create=>1}"
"casa_cases_emancipation_option: {:total=>3, :build=>1, :create=>2}"
```

**Comment by littleforest** [comment]
Since most of these tests are meant to run within the same organization anyway, maybe in the factory we can use the first created `casa_org` unless one is explicitly passed.

**Comment by scottolsen** [comment]
@littleforest great minds think alike! I'm going through all the Factories now and adding a check to use the first org if there is one, otherwise create one. 

```ruby
casa_org { CasaOrg.first || create(:casa_org) }
```

**Comment by scottolsen** [comment]
I'm also unsure what the `@overrides` does. I don't see it used anywhere except in factory definitions.

```ruby
casa_org do
  @overrides[:casa_org] || @overrides[:supervisor].try(:casa_org) || create(:casa_org)
end
```

**Comment by littleforest** [comment]
@scottolsen I think it's okay to remove that.

**Comment by pollygee** [comment]
I'm taking a look at this to see if I can help here. 🤞

**Comment by pollygee** [comment]
I made some progress, then I had environment issues and things got busy again.  I'm going to remove myself in case someone else has time to look at this.  I plan to come back and if nobody has been working on it I'll give it another go.

**Comment by compwron** [comment]
You rock! :)

**Comment by compwron** [comment]
Closing this because we will always need to do more- let's open smaller issues for small improvements :)
