### ISSUE TITLE
Add railroady and rails-erd gems for generating block diagrams

### ISSUE THREAD

**Issue by jhsu802701** [rubyforgood/casa#1460]
I'd like to add the railroady and rails-erd gems for making it possible to AUTOMATICALLY generate block diagrams.  Unfortunately, adding them to the Gemfile and running "bundle install" in the Docker environment leads to the error message:
```bash
Could not find gem 'rails-erd' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

```

**Comment by compwron** [comment]
At one point we had ...some... gem that auto-generated diagrams but I removed it because it required installing imagemagick locally and that was hard for new contributors who didn't have docker. So I am a little wary of this. But as long as it doesn't complicate the repo setup process, I'm game :)

**Comment by littleforest** [comment]
@jhsu802701 to add new gems with Docker, you need to have a container running already. So:

1. Stash your changes to the Gemfile
2. Start a web container
3. Unstash Gemfile changes
4. Run: `docker-compose exec web bundle`
