### ISSUE TITLE
Documentation Observations

### ISSUE THREAD

**Issue by eclectic-coding** [rubyforgood/casa#147]
As a new contributor, I went through the project documentation for the first time and have a few small observations from a pair fresh eyes. 

In the README - [Setup to Develop](https://github.com/rubyforgood/casa#setup-to-develop) section: 
- I believe steps 9 & 10 are reversed. When I set up this project on my system, I could not run `webpacker:compile` until the package.json dependencies had been installed with `yarn`
- Step 11: `bundle exec rails db:setup` creates the database so step 13 (`rails db:create`) is not needed. This was my experience and when I did run `db:create` the CLI reminded me the database was already created. 

In the CONTRIBUTING (Step 3), it appears there was an intention to link to the setup guidelines, but the link is incomplete. This reference is probably to the [Setup to Develop](https://github.com/rubyforgood/casa#setup-to-develop) in the README noted above. 

Thank you for the opportunity to assist and I will be glad to make these changes if you are in agreement. 

Chuck

**Comment by compwron** [comment]
Sounds great, please do :)
