### ISSUE TITLE
Remove filler text

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1487]
https://github.com/rubyforgood/casa/pull/1484/files

And/or replace it with something our users will recognize, like "coming soon" - they are not savvy and this kind of thing confuses them

**Comment by cam-benfield** [comment]
@compwron , just took a look and this must've been resolved with an earlier commit and never tagged, as the directory this was in doesn't exist anymore. Searched in project and no "lorem ipsum" exists outside of a spec, which is acceptable.

**Comment by cam-benfield** [comment]
@compwron , this can be closed.

**Comment by compwron** [comment]
thanks for the help! :)
