### ISSUE TITLE
seed case_contacts should contain contact_types

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1505]
As a **contributor**,
I want `case_contacts` in QA to contain `contact_types`,
so that data in QA more closely resembles data in prod.

### How it works now
Nearly all of the seed data currently in QA for `case_contacts` is missing `contact_types`.
![without](https://user-images.githubusercontent.com/62810851/102549524-1acc2280-4071-11eb-8b08-1d2e93530eae.png)

### How it should work instead
Seed data for `case_contacts` should _all_ have `contact_types` and `groups` (because it is impossible to log a `case_contact` without selecting at least one `contact_type`).
![with](https://user-images.githubusercontent.com/62810851/102549541-215a9a00-4071-11eb-9212-0c72d38c205a.png)

### Acceptance Criteria
All seeded `case_contacts` in QA should have at least one `contact_type` selected.

**Comment by bjthompson805** [comment]
I'll take this.
