### ISSUE TITLE
open followups can be resolved by any user

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1506]
Part of epic #1495 | dependent on #1496

As **any user**, 
I want the ability to resolve an open follow up on a `case_contact`,
so that other users viewing the `case_contact` see that action has been taken.

### How it works now
It doesn't! This is a brand new feature.

### Acceptance Criteria
- [x] Any user can resolve any open follow up (even if they didn't create the follow up)
- [x] Clicking the "resolve" button on a `case_contact` clears the follow up icon from it (see #1496 for additional details)
- [x] After the "resolve" button has been clicked and the follow up has cleared, the text on the "resolve" button changes back to "follow up"

**Comment by scottolsen** [comment]
Should get this done tomorrow.
