### ISSUE TITLE
Automate moving bot-unassigned issues back to To-Do in Projects

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#1541]
When the bot unassigns issues that are in the "In Progress" column for the CASA Volunteer Portal project, then they should be moved back to the "To Do" column.

**Comment by littleforest** [comment]
@bjthompson805 is this possible?

**Comment by bjthompson805** [comment]
Yes it is. What about if they're in the Merged to QA or Done column?

**Comment by bjthompson805** [comment]
I'll do this in the existing github action, please assign to me.

**Comment by compwron** [comment]
> What about if they're in the Merged to QA or Done column?
I don't think that we need/want anything in particular to happen to cards in Merged to QA or Done columns
