### ISSUE TITLE
Admin default view of all supervisors - sort

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1573]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
Sort supervisors by name. Make all columns sortable. Do not add filters (we dont expect to have very many supervisors per org so there's no point)

**Screenshots of current behavior, if any**
![Screen Shot 2021-01-09 at 4 26 15 PM](https://user-images.githubusercontent.com/578159/104111508-6ac88e80-5297-11eb-89ba-0740d1112152.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by rpolley** [comment]
Going to take a look at this.

**Comment by ATMartin** [comment]
Bug discovered during QA: https://github.com/rubyforgood/casa/issues/1573

_That said_, the sorting functionality is working otherwise. Proposing this as "working-in-qa".
