### ISSUE TITLE
replace all emoji with SVG 🐛🦋❌

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1585]
Replace all emoji with SVG 🐛🦋❌

Because emoji don't look good/consistent everywhere (firefox/IE/edge) and we want to look good everywhere!

**Comment by compwron** [comment]
chill bot :)

**Comment by efgalvao** [comment]
Hello, do you have the .SVG files of the images ?

**Comment by compwron** [comment]
the SVG are on an old github issue somewhere, I will see if I can find it...

**Comment by compwron** [comment]
This is either done or not what we want right now.
