### ISSUE TITLE
Add sad path test coverage for emancipation

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1590]
How to view test coverage: run `bundle exec rspec` and then `open coverage/index.html`
![coverage](https://user-images.githubusercontent.com/578159/105279786-28d3fe00-5b5d-11eb-9bb2-93919d4694d1.png)

![Screen Shot 2021-01-13 at 7 58 43 PM](https://user-images.githubusercontent.com/578159/104543185-d719f980-55d9-11eb-896d-8fe082f6e283.png)

**Comment by ErinClaudio** [comment]
I ran the above commands `bundle exec rspec ` and then  `open coverage/index.html`.
currently here and reading articles on Unhappy testing.  
![Screen Shot 2021-01-22 at 10 11 47 AM](https://user-images.githubusercontent.com/20326770/105509520-9423ea00-5c9b-11eb-97ca-67b28a6650d9.png)

**Comment by compwron** [comment]
sounds good!

**Comment by compwron** [comment]
@ErinClaudio I assigned this to you since you have an open PR for it :)

**Comment by ErinClaudio** [comment]
I added three new tests, they all fail. 
Two because of 'No route matches' errors and one because of the expected error message response and the received message do not match. My attempts at fixing the message response failed.

**Comment by compwron** [comment]
Hmm, inactivebot doesn't seem to respect recent PR mentions

**Comment by fraserjohnstone** [comment]
Hi, I don't currently have access to this repo but I would like to pick this issue up today! @compwron would you please be able to assign this to me?

**Comment by compwron** [comment]
This is merged so I am closing it :)
