### ISSUE TITLE
Remove sort by Actions for viewing all supervisors page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1599]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor and admin

**Description**
![casa-sort](https://user-images.githubusercontent.com/578159/104823323-31939f80-57fe-11eb-94cf-2c44585a03a7.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by efgalvao** [comment]
@compwron I think I have misunderstood, you want only the option to sort to be removed and let the field to edit stay, is it ?

**Comment by efgalvao** [comment]
I think this Issue should be closed, If you look in the same place as the image in the description shows, you will see that there is no sort by in Actions field anymore.
* The supervisors page:
![Screenshot from 2021-06-23 14-19-21](https://user-images.githubusercontent.com/61836657/123141104-67345880-d42e-11eb-869b-937b111a8f42.png)

**Comment by compwron** [comment]
Thanks!
