### ISSUE TITLE
Fix 3 CodeQL security Code Scanning issues

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1602]
https://github.com/rubyforgood/casa/security/code-scanning
<img width="1184" alt="Screen Shot 2021-01-16 at 2 33 13 PM" src="https://user-images.githubusercontent.com/578159/104824581-d36bba00-5807-11eb-9ee9-81235eda66be.png">

**Comment by chinmayjoshi** [comment]
Hi , @Zrrrpy @compwron I would like to work on this one

**Comment by compwron** [comment]
Very cool! All yours :)
