### ISSUE TITLE
Show case number on emancipation checklist

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1610]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**

emancipation checklist should reference case - make it easier for volunteers w multiple youth, and for supervisors and admins

**Screenshots of current behavior, if any**
![show-case](https://user-images.githubusercontent.com/578159/105569022-ee9c6500-5cf2-11eb-80e9-f11a9ebc21a8.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by bmanek** [comment]
Hey, I'd like to work on this one. Thanks!

**Comment by compwron** [comment]
Hmm, I'm going to lengthen the time wait on the github-actions bot to 10->15 days, because 5-> 7  only spans one weekend and that feels too short to me. :)

**Comment by bmanek** [comment]
I appreciate that. I know it's a small feature, but I'm still trying to
wrap my head around some things.

**Comment by compwron** [comment]
back to you! :)
