### ISSUE TITLE
Supervisor dashboard sorts numbers as strings.

### ISSUE THREAD

**Issue by ATMartin** [rubyforgood/casa#1623]
### Impacted User Types
Admins (possibly others?)

### Environment
Staging environment, MacOS Desktop, Chrome browser

### Current Behavior
When sorting numeric columns on the Supervisors dashboard, values are sorted incorrectly (1, 10, 11, 2, 3...)
![image](https://user-images.githubusercontent.com/4934682/106088089-4839d080-60f3-11eb-9eb7-6cdf909c87ef.png)

### Expected Behavior
Numeric values should be sorted correctly (1, 2, 3...9, 10, 11, 12...)

### How to Replicate
1. - Log into staging as an admin.
2. - Sort the default Supervisors dashboard by "Volunteer Assignments" (or any other "numbers-only" column)

**Comment by ATMartin** [comment]
Discovered during QA of https://github.com/rubyforgood/casa/issues/1573

**Comment by ATMartin** [comment]
I'll take this fix on! ✋

**Comment by Zrrrpy** [comment]
@ATMartin all yours, thank you! 🙏🏼

**Comment by compwron** [comment]
Sorry, I moved this by accident but then I put it back :)
