### ISSUE TITLE
No-volunteers message in weekly supervisor status email

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1628]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor

**Description**
When a supervisor has no volunteers with assigned cases, instead of showing no contents, show "You have no volunteers with assigned cases - when you do, you will see their status here" or similar 

**Screenshots of current behavior, if any**
![email](https://user-images.githubusercontent.com/578159/106345158-10519b00-6263-11eb-876a-2fa89736f038.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by arku** [comment]
@compwron Just curious, why should the email be sent to supervisors with no volunteers?

**Comment by Zrrrpy** [comment]
@arku Great question! In this case, the email serves as a reminder that volunteers who _are_ assigned to this supervisor need case assignments OR if the supervisor has _no_ volunteers assigned to them, then it serves as a reminder that they need to assign volunteers to themselves. 

Context: CASA chapters typically don't have more than a dozen supervisors on staff (even a dozen would be for a larger sized CASA org, many have under ten) and they typically _always_ have volunteer assignments. If a supervisor does not have any volunteers assigned to them, it is usually for a very short period of time as they are being onboarded to the platform, or if they are returning from an extended leave where their volunteers were assigned to another supervisor. 

Hope this answers your question! Let me know if it doesn't and I'm happy to provide more details. :)

**Comment by arku** [comment]
@Zrrrpy Interesting. Thanks for the explanation!
