### ISSUE TITLE
When on Volunteer page and unassigning volunteer from supervisor, render back to Volunteer page, NOT current behavior

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1644]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor/admin

**Description**
When on Volunteer page and unassigning volunteer from supervisor, render back to Volunteer page, NOT current behavior

**Screenshots of current behavior, if any**
https://casa-qa.herokuapp.com/volunteers/1576/edit
![volunteer-page-unassign-from-supervisor](https://user-images.githubusercontent.com/578159/106346074-472aaf80-6269-11eb-9d67-54581bf58f20.gif)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by ChaelCodes** [comment]
Currently, unassigning a supervisor appears to direct the super to the editing volunteer page where they can assign a new super.
<img width="1391" alt="Screenshot 2021-04-27 at 11 14 23" src="https://user-images.githubusercontent.com/8124558/116266724-bf5e1f80-a749-11eb-98c9-55739f86c61a.png">
I think this one is already resolved.

**Comment by compwron** [comment]
Thanks! :)
