### ISSUE TITLE
Improve automated seed data

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#167]
Part of epic #59 

**What type of user is this for? [volunteer/supervisor/admin/all]**
none! for testing by contributors

**Where does/should this occur?**
database in staging to fill the front end with usable data for testing

**Description**
The goal here is to get realistic-looking staging data so we can understand how the UI will work when there are 100+ volunteers! Have fun with names, just don't use any real names. All emails should be at `@example.com` so we don't accidentally email any real people when we turn on email :)

1. Make more volunteers (100 ish- use a for loop for this!), set names on volunteers (including exciting characters- anything you can find!)

**2.** Make more supervisors (5) and assign all but 1 volunteer to a supervisor

**3.** Make 3 casa admin accounts

**4.** Generate **random** case contacts for volunteers with a wide timespan of contact dates

**5** Make sure there is one volunteer with no recent case contacts

**Comment by lisavogtsf** [comment]
Scoping out the amount of work on this for today

**Comment by lisavogtsf** [comment]
Will pull the latest and set up my environment first. Probably make 10 volunteers and maybe a few types of people manually before doing research into a handy automated generator.

**Comment by eclectic-coding** [comment]
I am working on PR to remove other from case_contact. I am on my phone, so if memory services me, issue 89. 

We should remember this when planning seed data.

**Comment by lisavogtsf** [comment]
Discovered you can only login as volunter or casa_admin, not supervisor (shouldn't error) or inactive (shouldn't login but shouldn't error) users. Added bugs #176  #179  for future reference.

**Comment by lisavogtsf** [comment]
@eclectic-coding Cool--I will take a note not to include a case_contact in seeds with contact_type "Other"

**Comment by lisavogtsf** [comment]
Picking this up again

**Comment by lisavogtsf** [comment]
PR to generate substantial amount of seed data using Faker gem, various assumptions outlined in PR.

Handles most of items 1-3 on this issue--probably forgot to leave a volunteer unassigned.

**Comment by keithrbennett** [comment]
This has been marked as done. Should this issue be closed?

**Comment by compwron** [comment]
> This has been marked as done. Should this issue be closed?

Good point, I agree!
Note: https://github.com/rubyforgood/casa/issues/601 is related
