### ISSUE TITLE
Tests failing on clean docker build

### ISSUE THREAD

**Issue by rpolley** [rubyforgood/casa#1675]
### Impacted User Types
developers

### Environment
development/docker

### Current Behavior
Some of the tests fail for me every time I use the `docker/build` and `docker/test` against code on the main branch/any other branch I've tried
![Capture1](https://user-images.githubusercontent.com/23124989/106840685-42e60400-6666-11eb-8c10-d4f2c97e28e0.PNG)
![Capture2](https://user-images.githubusercontent.com/23124989/106840689-45485e00-6666-11eb-917a-3999962606db.PNG)
![Capture3](https://user-images.githubusercontent.com/23124989/106840691-47122180-6666-11eb-8895-ab05bdc436a6.PNG)
![Capture4](https://user-images.githubusercontent.com/23124989/106840694-48dbe500-6666-11eb-8abb-f316940ba6a8.PNG)
It looks like they're all network timeout-related so maybe this has something to do with capybara/the database/rails all being on separate containers in the docker setup, although it's weird that it happens so consistently then.

### Expected Behavior
All tests should come back clean after creating a new docker image off of `main` using `docker/build`

### How to Replicate
1. clone the casa repository
1. create a new container and run tests in it using `docker/build` using Docker for Windows with the WSL2 backend while in the casa repository directory.

**Comment by cam-benfield** [comment]
I noticed in my own testing that I had to edit the webpacker manifest to add /src/ to remove some of those. It's a lot of different issues.
