### ISSUE TITLE
supervisor summary no contact column numbers are too low

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1680]
![supe-summay-bug](https://user-images.githubusercontent.com/578159/107107143-2079f500-67e4-11eb-81c3-4aeca1c6573f.png)

**Comment by efgalvao** [comment]
Just to confirm, the column "no contact" should show how many volunteers(assigned to that supervisor) have made no contacts in the last 14 days, right ?

**Comment by efgalvao** [comment]
The column "No contact" is showing the number of volunteers who have a case assigned AND has not registered a contact to an active case in the period of 14 days.
The volunteer assignments stills counts if the volunteer is deactivated and not unassigned from supervisor. Maybe this is causing the big difference ?
I'm not seeing what is wrong here.
Sorry.

**Comment by compwron** [comment]
Ah yes I think that is the problem
> The volunteer assignments stills counts if the volunteer is deactivated and not unassigned from supervisor.
Please change it to not include deactivated volunteers :)

**Comment by efgalvao** [comment]
I have changed the way the "Volunteer Assignments" counts as you suggested. 
I would like to ask about one situation.
If a volunteer makes a contact for a case and he is not assigned on this case anymore, still counts, so he is not included in the count of "no contacts" even if the case has been deactivated it will continues to count. This is the way it should work, right ?

**Comment by compwron** [comment]
Correct
thanks!
