### ISSUE TITLE
any supervisor can assign any volunteer to any case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#17]
Part of epic: #105 

**What type of user is this for? [admin/volunteer/supervisor/all]**
Supervisor

**Where does/should this occur**
On the "edit volunteer" page of Supervisor dashboard (future work not in this issue). (It should be the Supervisor equivalent [of this page](https://casa-r4g-staging.herokuapp.com/volunteers/88/edit).)

**Description**
Supervisors should be able to assign any volunteer to any `casa_case`, just like admins can.

**Screenshots**
[This is what it should look like](https://casa-r4g-staging.herokuapp.com/volunteers/88/edit). 
<img width="1369" alt="assign any volunteer to any case" src="https://user-images.githubusercontent.com/62810851/81511664-c2a99280-92cf-11ea-9d21-0333ebe03c92.png">

**Relates to issues**
#20, #30

**Comment by alindeman** [comment]
@colinsoleim @compwron Is it possible that https://github.com/rubyforgood/casa/pull/263 already took care of this one? As far as I can tell, supervisors can already assign volunteers to cases.

**Comment by compwron** [comment]
@alindeman Hmm I think you're right. I will close this. Thanks!
