### ISSUE TITLE
Add to all-casa-admin casas summary report

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1702]
**What type of user is this for? volunteer/supervisor/admin/all**
ALL CASA admin (not casa admin)

**Description**
Add 
1. case contacts count
(For ALL cases including inactive)
2. Supe-to-vol assignments (active)
3. Case assignments (active)

**Screenshots of current behavior, if any**
![all-casa-admin-summary-additions](https://user-images.githubusercontent.com/578159/107599167-84c9f980-6bd4-11eb-9849-c5252b7ef407.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by ErinClaudio** [comment]
@compwron Can I give this try!

**Comment by compwron** [comment]
Chill out bot :)

**Comment by ErinClaudio** [comment]
That bot is giving me anxiety.

**Comment by compwron** [comment]
Lol sorry
the bot is a replacement for the emotional labor where zoe & I had to keep an eye on issues and warn people and unassign if they didn't reply... from my perspective it's doing its job but I do really want to make the text more self-explanatory

**Comment by compwron** [comment]
This PR is open because I haven't merged it yet but I hope to do it during office hours tonight!
