### ISSUE TITLE
hide judge name and hearing type when they aren't selected

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1705]
AS a **volunteer/supervisor/admin**,
I DON'T WANT to see `judge_name` or `hearing_type` under CASA Case Details,
WHEN no `judge_name` or `hearing_type` has been selected under Edit Case Details,
SO THAT it is clear those items are not applicable to the case I'm viewing at this time. 

### Environment
QA, Staging, and Production

### How it works now
`judge_name` and `hearing_type` show up under CASA Case Details even if blank.
![Screen Shot 2021-02-11 at 3 00 35 PM (2)](https://user-images.githubusercontent.com/62810851/107711699-e80f6680-6c7c-11eb-8a58-191117043414.png)
![Screen Shot 2021-02-11 at 3 00 46 PM (2)](https://user-images.githubusercontent.com/62810851/107711704-ea71c080-6c7c-11eb-9fa9-de663d48331a.png)

### How it should work instead
`judge_name` and `hearing_type` should only show up under CASA Case Details if they are selected under Edit CASA Case.

**Comment by cam-benfield** [comment]
Working on this :)

**Comment by Zrrrpy** [comment]
all yours, @cam-benfield! Thank you 🙏🏼
