### ISSUE TITLE
add subheader: Court Details on Edit CASA Case page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1706]
AS a **supervisor/admin**,
I WANT a subheader reading "Court Details" to display above `hearing_type`,
SO THAT it's clear all the information beneath that pertains to court appearances. 

### Environment
QA, Staging, Production

### How it works now
Court details are not distinguished from other details on this page, they sort of all meld together in a long list.

### How it should work instead
Since we will be adding additional details to this page soon, a subheader for the (increasingly long) court details section can help provide clarity to the UI.
There should be a subheader here that reads: Court Details.
This should _only_ display for supervisors and admins, not volunteers (since volunteer see far less information on this page, it would be odd for the few details they do see to be separated by a subheader). 
![Screen Shot 2021-02-11 at 3 36 02 PM (2)](https://user-images.githubusercontent.com/62810851/107713012-3d4c7780-6c7f-11eb-8056-c8f6540bb19e.png)

**Comment by compwron** [comment]
good small bite :)
