### ISSUE TITLE
move "youth's birth month & year" up on the page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1707]
AS an admin,
I WANT "Youth's Birth Month & Year" to appear underneath "Case Number" on the Edit CASA Case page,
SO THAT it is easier for me to find.

### Environment
QA, Staging, Production

### How it works now
"Youth's Birth Month & Year" is hidden between court details, and isn't easy to find. 
![Screen Shot 2021-02-11 at 3 51 55 PM (2)](https://user-images.githubusercontent.com/62810851/107714028-57875500-6c81-11eb-96b4-cd7a09bbf967.png)

### How it should work instead
"Youth's Birth Month & Year" should be right underneath "Case Number" since this is also PII pertaining to the case. This will make it easier to find so it's not mixed among court details.

**Comment by compwron** [comment]
good small bite :)

**Comment by 96RadhikaJadhav** [comment]
@Zrrrpy If I'm not wrong, we have to make changes in app\views\casa_cases\_form.html.erb file here..right?

**Comment by compwron** [comment]
@96RadhikaJadhav correct, this is at https://github.com/rubyforgood/casa/blob/bf69053f406610607f75b4fef632d53fb964bfce/app/views/casa_cases/_form.html.erb#L87
