### ISSUE TITLE
all followup notifications should be clickable

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1709]
### Impacted users
volunteers

### Environments
QA, Staging, Prod

### Current behavior
If a volunteer has outstanding notifications regarding `case_contact` followups made by previous supervisor assignments, they will not be able to click on them and therefore the notification badge that appears over "inbox" will never go away. 
![Screen Shot 2021-02-11 at 5 01 35 PM (2)](https://user-images.githubusercontent.com/62810851/107719841-fade6700-6c8d-11eb-94f0-ec7f02482832.png)

### Expected behavior:
All notifications under "inbox" should be clickable, regardless of whether or not they regard followups made by current or previous supervisor assignments. 

### How to replicate
1. - Log into QA or Staging as supervisor1@example.com. 
2. - Identify a volunteer currently assigned to you, make note of their email, and log out.
3. - Log back in as that volunteer.
4. - Create a `case_contact`, and set the `occurred_at` date as today.
5. - Log out.
6. - Log back in as supervisor1@example.com. 
7. - Locate the `case_contact` you just created as a volunteer.
8. - Add a followup to it. 
9. - Unassign that volunteer from yourself. 
10. - Log out. 
11. - Log back in as that same volunteer.
12. - Click on your inbox (there should be a badge there denoting a new notification). 
13. - Click on the most recent notification. This should trigger a message that says "Sorry, you are not authorized to perform this action." If you navigate back to "My Cases," you'll notice the new notification badge is still next to your inbox.

**Comment by scottolsen** [comment]
@Zrrrpy Currently the only people who can edit a `case_contact` are admin, the creator and the creator's supervisor. If this logic needs to stay then we have a couple of options to make this work.

1. We add a check in the policy to look for a notification for the user/case_contact, if one exists we allow them to edit.
2. Delete, don't show or make the notification not clickable, if the volunteer is unassigned from the supervisor.
3. Allow all supervisors to edit any `case_contact`

Let me know your thoughts or if you were thinking something else :)

**Comment by Zrrrpy** [comment]
Thank you for taking this on, @scottolsen! Let's go with option 3 – we're finding increasingly that supervisors require more flexibility in their permissions anyway, so this works well.
