### ISSUE TITLE
deactivated volunteers show up in weekly digest email

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1728]
### Impacted user types
supervisors

### Environment
Prod

### How it works now
Deactivated volunteers show in the weekly digest email supervisors receive summarizing volunteer in/activity from the past week.

### How it should work instead
Deactivated volunteers should not show in the weekly digest email.

### How to replicate
Sendinblue only sends emails in prod, but the same logic that triggers this automated email should also be in QA and Staging. May be possible to manually trigger a local send to test this. 🤷🏼‍♀️

**Comment by hairedfox** [comment]
I'd love to solve this issue :bow: @Zrrrpy
