### ISSUE TITLE
reassigned volunteers should only show in their new supervisor's digest email

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1729]
### Impacted user types
supervisors

### Environment
Prod

### How it works now
After a volunteer has been reassigned to a new supervisor, they show up in _both_ supervisors' weekly digest email (the previous supervisor + the newly assigned supervisor). 

### How it should work instead
Volunteer should only show up in the weekly digest email belonging to their _newly assigned_ supervisor (i.e. their active supervisor assignment). They should not also be showing up in the weekly digest email belonging to any previous supervisor assignments.

### How to replicate
Sendinblue only sends emails in prod, but the same logic that triggers this automated email should also be in QA and Staging. May be possible to manually trigger a local send to test this. 🤷🏼‍♀️

**Comment by BrianBorge** [comment]
I can take this one.
