### ISSUE TITLE
[BUG] Exception if visiting case contact "0"

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#173]
**What's the bug?**
This should be a 404, not an exception (exceptions are things that need fixing & mean that the system is broken, 404s are not)

**How to make it happen**
1. Log in as volunteer1
1. Go to URL https://casa-r4g-staging.herokuapp.com/case_contacts/0 
1. See exception in #casa-bots https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1587845812056100

**Comment by colinsoleim** [comment]
After some research, It looks like Rails is giving a 404 error after the ActiveRecord::RecordNotFound exception is raised, and it's rendering the 404 page like it should. The linked PR above fixes the Slack notifications by adding these errors to the list of ignored errors in bugsnag.
