### ISSUE TITLE
add court mandates to Edit CASA Case page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1731]
Part of epic #1730

AS a supervisor,
I WANT to add court mandates to a case,
SO THAT they show up in volunteer generated court reports,
AND for historical context. 

### How it works now
It doesn't! This is a brand new feature.
![Screen Shot 2021-02-16 at 2 49 17 PM (2)](https://user-images.githubusercontent.com/62810851/108135429-eecb1e80-706c-11eb-8c83-1bbd2c2fa88d.png)

### How it should work instead
Supervisors should be able to add court mandates to a case (in the "Court Details" section). 

### Acceptance Criteria
- [ ] Only supervisors have the ability to add/edit/remove court mandates.
- [ ] This lives at the bottom of the "Court Details" section on the Edit CASA Case page. 
- [ ] There should be a subheader within this section with the text: Court Mandates
_If you have a different design vision for what follows, go for it! We are not married to what's described below._
- [ ] Underneath "Court Mandates", should be the text "Add a court mandate."
- [ ] There should be a clickable `+` symbol next to this text which creates a text field when clicked. 
- [ ] The user's cursor should automatically be in the new text field once it is created. 
- [ ] A "submit" button should appear alongside the new text field. 
- [ ] Clicking "submit" saves the court mandate as typed in the text field. 
- [ ] There is no limit on how many court mandates can be added. 
- [ ] Clicking "Update CASA Case" (already exists on the page) saves changes.

**Comment by rhian-cs** [comment]
Hello, I am working on this issue.

**Comment by compwron** [comment]
very cool! :) :)
