### ISSUE TITLE
court mandates can be edited/removed

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1733]
Part of epic #1730, dependent on #1731

AS a **supervisor**,
I WANT to be able to edit and/or remove court mandates,
SO THAT court mandates remain relevant, up-to-date, and can be removed if I make a mistake. 

### How it works now
After #1731 is complete, supervisors will have the ability to _add_ court mandates, but not _edit_ or _remove_ them.

### How it should work instead
Supervisors should be able to easily edit or remove court mandates from CASA Case Details. 

### Acceptance Criteria
- [ ] A blue "Edit" button appears to the right of each court mandate.
- [ ] Clicking the blue edit button drops the user's cursor into the corresponding text field. 
- [ ] A "Submit" button appears when the text field is being edited, just like when a court mandate is initially added. 
- [ ] Clicking the "submit" button saves changes. 
- [ ] A red "Remove" button appears to the right of the blue "Edit" button.
- [ ] Clicking "Remove" triggers a dialogue box with the text: _Are you sure you want to remove this court mandate? Doing so will delete all records of it unless it was included in a previous court report._ with two buttons underneath it: "Return" or "Remove". 
   - [ ] Clicking "Return" closes the dialogue box and does nothing.
   - [ ] Clicking "Remove" closes the dialogue box and deletes the court mandate. This should trigger a banner style notification reading, "Court mandate has been removed."

**Comment by rhian-cs** [comment]
Hello there, I am working on this issue.
I already did the edit part when implementing #1795, but I will finish the job by adding the delete option too.

**Comment by compwron** [comment]
very cool! :)
