### ISSUE TITLE
add court mandate implementation status to Edit CASA Case page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1734]
Part of epic #1730, dependent on #1731

AS a **supervisor**, 
I WANT to track the implementation status of court mandates,
SO THAT I can ensure a case's volunteer is assisting in implementation and accurately reporting progress to the court at hearings.

### How it works now
After #1731 is complete, supervisors will be able to add court mandates to cases, but no additional details about them, such as implementation status.

### How it should work
Supervisors should be able to select the implementation status that reflects the progress of each court mandate. 

### Acceptance Criteria
- [ ] Only supervisors can edit implementation status.
- [ ] Implementation status should display as a dropdown menu, with the following items in it:
   - [ ] not implemented
   - [ ] partially implemented
   - [ ] implemented
- [ ] When nothing is selected in the dropdown menu, the default (first item) should be: set implementation status
- [ ] On desktop web, implementation status should appear to the right of each court mandate.
- [ ] On mobile web, implementation status should appear underneath each court mandate.

**Comment by rhian-cs** [comment]
Hello, I am working on this issue.

I have one question though, are the supervisors allowed to set a blank value for the Implementation Status? In this case, leave the dropdown menu as "Set implementation status".

**Comment by compwron** [comment]
@rhian-cs yes, let's allow Supervisors to set blank value and show it in the dropdown as "Set implementation status" like you said :)
