### ISSUE TITLE
if case has court mandates, add to court report

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1736]
Part of epic #1730, dependent on #1731 and #1734

AS a **volunteer**,
I WANT court mandates and their implementation status to appear in court reports I generate and download,
SO THAT I do not need to fill these in manually.

### How it works now
Once #1733 is complete, court mandates and their implementation status will only appear in two places: the Case Details page, and when editing Case Details. If a volunteer wanted to add these details to a court report, they'd have to do so manually.

### How it should work
If a `case` has court mandates, they should appear in generated court reports in a new section (see attachment). 
_Please note: the information in the following example is all fake data developed for training purposes. Ignore what's on the first page. See the second page for what the new section should look like._
[Training Court Report _Good Copy.pdf](https://github.com/rubyforgood/casa/files/5992686/Training.Court.Report._Good.Copy.pdf)

### Acceptance Criteria
- [ ] If a `case` has court mandates, they should appear in generated court reports along with their implementation status. 
- [ ] If a `case` does _not_ have court mandates, the table and text described below should _not_ be included in its corresponding court report.
- [ ] Court mandates and implementation status should populate in a new table containing two columns: one with the header, "Ordered" and the second with the header "Status". 
  - [ ] Court mandates should appear in rows (one court mandate per row) in the column titled "Ordered". 
  - [ ] Implementation status should appear in rows (corresponding with court mandates) in the column titled "Status". 
- [ ] The table should appear underneath `case_contacts`
- [ ] The following text should appear above the court mandates table: `Orders from [last court_date] hearing` 
   - [ ] `last court_date` should display as: Month, numerical date, full year. Ex: November 1, 2008

**Comment by compwron** [comment]
Done!
