### ISSUE TITLE
Supvervisor Weekly Email: Show if a case has gone inactive during the week

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1737]
In the supervisor weekly email(`app/views/supervisor_mailer/weekly_digest.html.erb`), mention if a casa case was deactivated during the week.

Write a test(`spec/mailers/supervisor_mailer_spec.rb `)

**Comment by cam-benfield** [comment]
I'd like this one!

**Comment by Zrrrpy** [comment]
all yours, @cam-benfield! Thank you for your continued work on this project 😄

**Comment by FireLemons** [comment]
Hi @cam-benfield, I just wanted to warn you that `app/views/supervisor_mailer/weekly_digest.html.erb` hasn't been merged into the repo yet

You can take a look at the tests to be merged here https://github.com/rubyforgood/casa/pull/1732/files#diff-ba49c16cf0c0acb6ff1fdc7ad934bc32a01cf202f2e1b3ab78fc755d2fa87a34

**Comment by cam-benfield** [comment]
@FireLemons I think I've figured this one out, but I'm fairly new at this. I'll be able to merge my changes this afternoon (real-life job has needs today.)

**Comment by FireLemons** [comment]
Ok it's been merged. I said  `app/views/supervisor_mailer/weekly_digest.html.erb` but I meant `spec/mailers/supervisor_mailer_spec.rb `. Meaning there was no file to put the tests in when it was unmerged. My bad. @cam-benfield
