### ISSUE TITLE
Supervisor Weekly Email: Hide inactive cases past the week they were deactivated

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1738]
If a casa case has been deactivated in a previous week, do not display it in the supervisor weekly email(`app/views/supervisor_mailer/weekly_digest.html.erb`)  
  
Previous weeks as opposed to the current week so the supervisor see case activity for the last week the case was active.

Write a test(`spec/mailers/supervisor_mailer_spec.rb `)

**Comment by cam-benfield** [comment]
I'd like this one!

**Comment by compwron** [comment]
go for it! :)

**Comment by compwron** [comment]
@cam-benfield how's it going? :)

**Comment by cam-benfield** [comment]
Was finally able to get back into working on this and I'm running into some minor issues, but still working on it. :)

**Comment by compwron** [comment]
Very cool :) lmk if I can help :)

**Comment by cam-benfield** [comment]
So I've run into a bit of confusion, as the current behavior is that the mailer has this issue already sorted, and was likely resolved in a PR that resolved an issue I was unassigned from. (Lots of life issues lately.) [Here's the PR](https://github.com/rubyforgood/casa/pull/1820) for reference.

**Comment by compwron** [comment]
@cam-benfield oh no I"m sorry! 
You are great, I hope you forgive us and stick around.
If you have time & want another issue, maybe one of these?

1. https://github.com/rubyforgood/casa/issues/1902
1. https://github.com/rubyforgood/casa/issues/1866
1. https://github.com/rubyforgood/casa/issues/1890

**Comment by FireLemons** [comment]
I guess this is invalid now
