### ISSUE TITLE
Past court dates reveal past court details

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1739]
Part of epic #1730, dependent on #1731, #1734, and #1736

AS a **supervisor/admin**,
I WANT to see details associated with "Past Court Dates",
SO THAT I can easily reference them for historical context and compare them to current court details.

_Future work not in this issue_: also make this accessible to volunteers

### How it works now
Currently, no past court details are viewable other than date. 
![Screen Shot 2021-02-16 at 6 07 35 PM (2)](https://user-images.githubusercontent.com/62810851/108146785-acacd780-7082-11eb-8f7a-ebff93968b83.png)

### How it should work
When a past court date is clicked on under "Edit CASA Case", supervisors/admins are taken to a page containing court details associated with that date. 

### Acceptance Criteria
- [ ] Dates are clickable underneath "Past Court Dates" on the Edit CASA Case page.
- [ ] Clicking on a date takes you to a page where you can see details associated with that past court date, including:
  - [ ] Hearing type
  - [ ] Judge
  - [ ] Court mandates and implementation status

**Comment by librod89** [comment]
@Zrrrpy, currently hearing type, judge, court mandates, etc are not saved in the past court date db table. So for this feature, should those fields be blank for past court dates created before this feature? And we'll just start saving those fields in the db moving forward?

Or alternatively, we can make the date clickable _only_ if we have these extra fields for it?

**Comment by rhian-cs** [comment]
@librod89 are you working on this issue? I was thinking of giving this one a go

**Comment by librod89** [comment]
Feel free to take it @rhian-cs. I did not start on it.

**Comment by rhian-cs** [comment]
Right, I started working on this issue. One question though:

I see that the past court dates are created automatically based on the case's due date, and when that happens, some case data such as Court Date, Court Report Due Date and Court Report Status is reset.

When a past court date is created, should the data about the Court Mandates be reset as well?

**Comment by compwron** [comment]
That's a good question! I don't know. I will add it to things to discuss next Weds in our weekly stakeholder meeting

**Comment by compwron** [comment]
For now, let's not clear the old court mandates when a past court date is created.
