### ISSUE TITLE
Supervisor Weekly Email: Add a message saying if a case was assigned to a volunteer. 

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1744]
If a casa case has been assigned/reassigned to a supervisor's volunteer during the week, mention it in the supervisor weekly email(`app/views/supervisor_mailer/weekly_digest.html.erb`)  
 
Write a test(`spec/mailers/supervisor_mailer_spec.rb `)

**Comment by rpolley** [comment]
can take a look at this one

**Comment by compwron** [comment]
go for it! :)
