### ISSUE TITLE
Supervisor Weekly Email: Add a message saying if a volunteer was unassigned from the supervisor

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1745]
If a volunteer was unassigned from a supervisor during the week, display it in the supervisor weekly email(`app/views/supervisor_mailer/weekly_digest.html.erb`)  
Also display if the volunteer has not yet been assigned to a new supervisor.  

Write a test(`spec/mailers/supervisor_mailer_spec.rb `)

**Comment by adamnengland** [comment]
I'd like to take this one.

**Comment by FireLemons** [comment]
Hi @adamnengland, I just wanted to warn you that `app/views/supervisor_mailer/weekly_digest.html.erb` hasn't been merged into the repo yet

You can take a look at the tests to be merged here https://github.com/rubyforgood/casa/pull/1732/files#diff-ba49c16cf0c0acb6ff1fdc7ad934bc32a01cf202f2e1b3ab78fc755d2fa87a34

**Comment by FireLemons** [comment]
Ok it's been merged. I said  `app/views/supervisor_mailer/weekly_digest.html.erb` but I meant `spec/mailers/supervisor_mailer_spec.rb `. Meaning there was no file to put the tests in when it was unmerged. My bad. @adamnengland

**Comment by BrianBorge** [comment]
I can take this one.

**Comment by librod89** [comment]
@FireLemons Is there any more to be done on this ticket? It looks like the code is already displaying volunteers who were unassigned during the week.

**Comment by BrianBorge** [comment]
Oh good question -- I was looking at `weekly_digest.html.erb_spec.rb` and not `supervisor_mailer_spec.rb ` 🤦

**Comment by FireLemons** [comment]
> @FireLemons Is there any more to be done on this ticket? It looks like the code is already displaying volunteers who were unassigned during the week.

Before this pr there was code displaying if a volunteer was unassigned from a casa case. I don't think there was any code to show if a volunteer was unassigned from the supervisor.
