### ISSUE TITLE
remove transition_aged_youth column from case import .csv

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1759]
As an **admin**,
I WANT the `transition_aged_youth` column to be removed from the sample case import .csv,
SO THAT I don't accidentally do extra work that is now automated.

### Environments
QA, staging, prod

### How it works now
When an admin downloads a sample case .csv for imports, there is a column for `transiton_aged_youth`. This prompts admins to go through the whole spread sheet and mark `true` or `false` per case depending on their age. 
[Case sample import - Sheet1.pdf](https://github.com/rubyforgood/casa/files/6004863/Case.sample.import.-.Sheet1.pdf)

### How it should work instead
The `transition_aged_youth` column in this .csv should be removed since it is no longer needed. The platform now automatically calculates whether or not a youth is transition aged based off their birth month and year.

**Comment by rhian-cs** [comment]
Hello, may I work on this issue?
