### ISSUE TITLE
[BUG] Cannot login as supervisor user

### ISSUE THREAD

**Issue by lisavogtsf** [rubyforgood/casa#176]
**What's the bug?**
Attempting to login as the seeded "supervisor user," email: supervisor1@example.com, gets an "unrecognized role" error.  

Need to set up proper scope for a supervisor user in devise policies/scope--what permissions apply to this user?
**Supervisors can only access data associated with the following**
- volunteers assigned to them, regardless of case assignment status (view and edit)
- `case_contacts` associated with a supervisor's volunteer assignments (view and edit)
- `casa_cases` associated with a supervisor's volunteer assignments (view and edit)
- volunteer and case assignments (view and edit)
- generate reports (need more details)

Need to add a test to ensure this doesn't happen in the future.

**How to make it happen**
1. As a logged out user
2. Go to the home page/login page
3. Enter valid email and password from db seed.rb file
4. See runtime error: unrecognized role (screenshot below)

**Screenshots**
![Screen Shot 2020-04-25 at 1 34 55 PM](https://user-images.githubusercontent.com/7121497/80290490-1d50c500-86fa-11ea-82b3-0746c4fd55bd.png)

**Extra info:**
Error cites user_policy.rb line 25, that file only recognizes 'casa_admin' and 'volunteer' as valid roles

**relates to issues**
#30

**Comment by Zrrrpy** [comment]
@compwron has this fix pushed to staging? I'm still getting an error when I try to log in as a supervisor using supervisor1@example.com
