### ISSUE TITLE
migrate column case_assignment.is_active to case_assignment.active to match other columns

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1776]
migrate column case_assignment.is_active to case_assignment.active to match other columns

this is too annoying, kill it. 
and remember to do a SAFE column rename! :) 

we have a workaround in case-assignment scope, 
and in case assignment factory

**Comment by efgalvao** [comment]
To clarify, needs to create a migration to rename column safely and change in the code where it makes references, from .is_active to .active ?

**Comment by compwron** [comment]
Correct.

**Comment by efgalvao** [comment]
I would like to help with this issue.

**Comment by compwron** [comment]
Very cool! All yours :) Thank you!
