### ISSUE TITLE
create RFG Twilio account(s)

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1780]
Part of epic #1017 

AS a CASA maintainer and approved Twilio account user,
I WANT access to an unique or shared RFG Twilio account,
SO THAT we can begin work on SMS notifications.

### How it works now
It doesn't! We don't have a Twilio account yet.

### How it should work
Ruby For Good will either have one shared organization account that all projects can use _or_ each project will have their own Twilio account _or_ each platform tenant per project will have their own Twilio account. (This will depend on the scope of the partnership between RFG and Twlio.)

**Comment by talya19** [comment]
@seanmarcia @pollygee @compwron any update here? Was the Twilio account created ?

**Comment by talya19** [comment]
Actually not much I believe 
@polly any news? 

Talya Grausz

**Comment by seanmarcia** [comment]
We have the twilio account and some credits in it -- I thought the idea was to proceed with this and use the RfG good twilio account for testing but have each of the CASA's register for their own accounts.

**Comment by talya19** [comment]
Hi sean! That could be a good way to go.
We can probably mention that to the stakeholders today.

**Comment by compwron** [comment]
Each developer makes their own twilio account for testing to text themself
