### ISSUE TITLE
URLs in SMS notifications are shortened

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1782]
Part of epic #1017, dependent on #1781

AS a **volunteer/supervisor/admin**, 
I WANT to receive SMS notifications containing shortened links only,
SO THAT they are delivered to me in one message (not broken up due to length or blocked by my mobile carrier due to URL content).

### How it works now
Twilio is not set up yet, but once #1781 is complete, we will need to pick a link shortening service to integrate with Twilio. (Twilio used to offer their own link shortening, but that went away after Verizon blacklisted Twilio links in SMS.)

We don't have to use short.io, but they have <a href="https://blog.short.io/short-links-sms-marketing/">a blog post</a> with some good context on this.

### How it should work
Most mobile carriers block non branded shortened urls (i.e., bit.ly, rebrand.ly, etc), so we'll have to shop for a link shortening service that offers affordable branded options (there will likely be a cost associated with this). 

### Acceptance Criteria
- [x] create account with chosen link shortening service
- [x] integrate link shortening service with Twilio
- [x] enable branded links

**Comment by xihai01** [comment]
80% done
