### ISSUE TITLE
all users receive account activation sms notification

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1784]
Part of epic #1017, dependent on #1780, #1781, and #1782

AS a **volunteer/supervisor/admin**, 
I WANT to receive an SMS notification when my account is first created,
SO THAT I find out about my account expeditiously AND so that I immediately have the opportunity to opt out of SMS notifications.

### How it works now
It doesn't! Currently, the platform only supports email notifications.

### How it should work
Volunteers, supervisors, and admins should all be notified via SMS when a new account is created for them. That notification should read something like this, depending on character restrictions:
_A CASA [volunteer/supervisor/admin] account was created for you. Visit [link] to change your text message settings._

**Comment by xihai01** [comment]
@compwron Should we also send this SMS to users who re-activate their accounts again?

**Comment by compwron** [comment]
> [xihai01](/xihai01)

yes that sounds correct

**Comment by xihai01** [comment]
Edited issue description so now the sent SMS doesn't contain the _set your password_ link. Rest assured this link will be sent in #3616

**Comment by xihai01** [comment]
@compwron because SMS opt-in notifications are by default set to **false** when a new user is created, I feel a portion of the SMS message should be changed to something like this, 
_A CASA [volunteer/supervisor/admin] account was created for you.
Txt YES to opt in to future text notifications_

What do you think?

**Comment by xihai01** [comment]
@compwron @7riumph @harsohailB  because SMS opt-in notifications are by default set to false and there is an ongoing list of different events, I feel it would make more sense to direct the user to their respective edit pages to manage their SMS notification settings (instead of asking them to reply STOP). So something like this:


 _A CASA [volunteer/supervisor/admin] account was created for you.
Please visit [link] to change your text message settings._


What do you think?

**Comment by 7riumph** [comment]
> @compwron @7riumph @harsohailB because SMS opt-in notifications are by default set to false and there is an ongoing list of different events, I feel it would make more sense to direct the user to their respective edit pages to manage their SMS notification settings (instead of asking them to reply STOP). So something like this:
> 
> _A CASA [volunteer/supervisor/admin] account was created for you. Please visit [link] to change your text message settings._
> 
> What do you think?

I omitted the "STOP" reply section in the `terms of service` with similar thinking in mind so I agree. Just have to do it in a way where the profile link is sent after users set up their new account/can access their account. SMS replying would be good in the future though.

**Comment by xihai01** [comment]
> > @compwron @7riumph @harsohailB because SMS opt-in notifications are by default set to false and there is an ongoing list of different events, I feel it would make more sense to direct the user to their respective edit pages to manage their SMS notification settings (instead of asking them to reply STOP). So something like this:
> > _A CASA [volunteer/supervisor/admin] account was created for you. Please visit [link] to change your text message settings._
> > What do you think?
> 
> I omitted the "STOP" reply section in the `terms of service` with similar thinking in mind so I agree. Just have to do it in a way where the profile link is sent after users set up their new account/can access their account. SMS replying would be good in the future though.

currently, if a user tries to visit their profiles before they set up their account (i,e set their password), they will be redirected to the login page with a flash notice saying something like "please first accept invitation link". So maybe the SMS can be worded as such,

_A CASA ... account was created for you. First, set your password here [link]. Then visit [link] to change your text message settings._
