### ISSUE TITLE
user should remain on Edit Volunteer page after editing a volunteer

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1806]
AS a **supervisor** or **admin**,
WHEN I click "submit" after assigning a volunteer to a supervisor FROM the edit volunteer page,
I WANT to be remain on the same edit volunteer page,
SO THAT I can proceed with the changes I was making to that volunteer profile.

### How it works now
After a volunteer is assigned to a supervisor from the edit volunteer page, the user who made that change is directed to the Edit Supervisor page corresponding to the just-made supervisor_volunteer assignment. 

### How it should work instead
After clicking the submit button following the assignment of a volunteer to a supervisor from the edit volunteer page, the user submitting that change should see a success message "Volunteer successfully assigned to a supervisor." and _remain on the same page._

after assigning a volunteer to supervisor from volunteer page and submitting, next page user sees is the supervisor that volunteer has been assigned to.

**Comment by efgalvao** [comment]
Hello, can I try to fix this one ?

**Comment by efgalvao** [comment]
Do you want to stay in the edit volunteer page when you unassign from a supervisor too ?

**Comment by compwron** [comment]
Great! I will assign it to you. :) 

Yes please :)
> Do you want to stay in the edit volunteer page when you unassign from a supervisor too ?
