### ISSUE TITLE
Show volunteer's invitation accepted at and reset pass at on their edit page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1824]
**What type of user is this for? volunteer/supervisor/admin/all**
For supervisor/admin to view on volunteer's page
`user.invitation_accepted_at`
`user.reset_password_sent_at`

**Description**
![vol-info](https://user-images.githubusercontent.com/578159/110726387-22154f00-81ce-11eb-8531-afb957f83c2c.png)

**Screenshots of current behavior, if any**

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by compwron** [comment]
bot chill out :)

**Comment by ChaelCodes** [comment]
Looks like this has already been handled! Logged in as a supervisor.

![image](https://user-images.githubusercontent.com/8124558/116821464-f4061880-ab47-11eb-8127-50a9b6ece1ba.png)

**Comment by compwron** [comment]
@ChaelCodes Yes, this issue is in the Done column. Thanks for checking! :)

**Comment by ChaelCodes** [comment]
I only mentioned because it's an open issue.

**Comment by compwron** [comment]
Oh interesting, maybe not all our Done issues are Closed. We can add another bot for that... https://github.com/rubyforgood/casa/issues/2003
