### ISSUE TITLE
Give Montgomery their own logo and format for court report

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1826]
**What type of user is this for? volunteer/supervisor/admin/all**
All

**Description**
Custom court report doc per casa_org
letterhead is different and Montgomery wants a little chart at the top of theirs
User doesn't have to upload it, we can check it into git. Someday we will probably want the user to upload it tho- that can be a different github issue.

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by compwron** [comment]
TODO: get the Montgomery template before starting this work...

**Comment by talya19** [comment]
After reviewing the right copy, I am updating the requirements for the new Montgomery County custom Court report.
**What type of user is this for? volunteer/supervisor/admin/all**
Volunteer

**Description**
Stakeholders from Montgomery county are asking for improvements in the Court report generated by the App.
A few improvements are to be done on the report (from top to bottom):
- Header: Add logo and contact info of Montgomery County CASA Program.
- Replace 'Respondent' with 'Minor'
- Add a table title Orders from <Date> Hearing with 2 columns: Ordered and Status (Implemented, partially implemented or not implemented). @compwron is there a way to fill up this table when generating the report from the app?
- Remove italics in titles for each written section 
-Footer: Add "date" before "Appointed" and remove CASA in front of Case supervisor.

**Screenshots of current behavior, if any**

<img width="445" alt="Screenshot 2021-03-24 at 14 22 45" src="https://user-images.githubusercontent.com/54947327/112317493-6879ac00-8cac-11eb-9333-8fd331c69e18.png">

**Screenshots of the new behaviour**
<img width="444" alt="Screenshot 2021-03-24 at 14 24 29" src="https://user-images.githubusercontent.com/54947327/112317745-a676d000-8cac-11eb-9674-09fc68ad753b.png">

**- Attached is the good copy of the report, image of the logo and contact info
[Training Court Report _Good Copy.pdf](https://github.com/rubyforgood/casa/files/6197590/Training.Court.Report._Good.Copy.pdf)

<img width="104" alt="image" src="https://user-images.githubusercontent.com/54947327/112318835-c3f86980-8cad-11eb-94df-ec5af6dd499e.png">

Voices for Children MontgomeryCourt Appointed Special Advocate Program1010 Grandin Avenue · Room B-3 · Rockville, Maryland 20851Phone: (301) 340-7458 · Fax: (240) 319-7210www.casamontgomery.org · email:mail@casamontgomery.org
--


**

**Comment by FireLemons** [comment]
So there's a transition template and a non transition template (see https://github.com/rubyforgood/casa/tree/main/app/documents/templates). Are the changes applied to both templates for montgomery making a total of 4 templates?

**Comment by compwron** [comment]
@FireLemons Yes! Total of 4

**Comment by compwron** [comment]
It would be very nice to get this done soon- hopefully we can look at it tonight during office hours

**Comment by compwron** [comment]
We discussed in office hours

add new column on casa_org kinda like logo

@FireLemons 

auto-generate transition and non-transition versions?

**Comment by compwron** [comment]
original issues for this stuff
https://github.com/rubyforgood/casa/issues/922
https://github.com/rubyforgood/casa/issues/1064

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/113231499-faf7ed80-9260-11eb-99d1-1798ef2d220b.png)

**Comment by compwron** [comment]
https://github.com/senny/sablon#images-beta

**Comment by compwron** [comment]
Here's another version of the Montgomery demo court report

[Training Court Report _Good Copy.docx](https://github.com/rubyforgood/casa/files/6240438/Training.Court.Report._Good.Copy.docx)

attempting to share as a google doc https://drive.google.com/file/d/1luyjVuNM8ZYBrbkeExafMDDadghhFiAH/view?usp=sharing

**Comment by compwron** [comment]
another potential docx - to - PDF
https://www.adobe.com/acrobat/online/word-to-pdf.html

**Comment by compwron** [comment]
https://edgeguides.rubyonrails.org/active_storage_overview.html#discarding-files-stored-during-system-tests
