### ISSUE TITLE
Reduce Papertrail logging

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1834]
Log less so that we don't run out of free logging

<img width="1323" alt="Screen Shot 2021-03-12 at 6 56 35 PM" src="https://user-images.githubusercontent.com/578159/111016807-bdd8c380-8364-11eb-9926-9f9775224037.png">

> Hello,
> 
> Your Papertrail service for "casa-production" has reached 51% of its included log data transfer of 10 MB for today.
> 
> This is an informational notice. No action is needed.
> 
> Based on recent volume, your projected total daily log data transfer is 6.2 MB.
> 
> How's this work?
> 
> At capacity, new logs are dropped. Existing logs aren't affected. Processing automatically resumes the following day.
> 
> Not sure what's best for this app, or have a question or request? Just reply.
> 
> If you find Papertrail valuable, a paid service may be a good fit (and if it hasn't met your needs, tell us why!). $8 buys 500% more volume, a week of realtime search, and ∞ more innovation: See Plans
> 
> 10 minutes of tuning goes a long way
> 
> We're all about effective logs. If this is unexpected, an app may be generating more log data than is useful or intended. This email isn't to nag you to upgrade; we've invested a lot of effort to provide easy, free ways to manage log volume (and as users ourselves, we'd never want log processing to unexpectedly stop). Here's some options:
> 
> Have Papertrail filter noise free, such as requests for static assets.
> Denser logging. Many web frameworks (including Rails) are very verbose. We have tips to create denser, more informative logs (here's a few for Rails). Just reply and tell us which frameworks or daemons you use.
> Punt and tune later. Papertrail plans average 15,000 messages per $0.01 (that's 1/15,000th of a cent per message).
> Ask us. Just reply.
> We're out to provide awesome troubleshooting knowledge and a great value. We don't care whether that's $0 or $300 as long as it's solving your problem well.
> 
> Happy logging,
> 
> the Papertrail team

![Screen Shot 2021-03-12 at 6 58 42 PM](https://user-images.githubusercontent.com/578159/111016854-00020500-8365-11eb-87ea-0c56941bfb4c.png)

**Comment by cam-benfield** [comment]
@compwron , is this one done? Based on status updates, it states it's done, but I want to verify it's available. I'd like it if it's still open.

**Comment by cam-benfield** [comment]
Alright, I'll take this one then. Might take a bit, but I can do it.

**Comment by compwron** [comment]
@r-sierra I see that you moved this into In Progress so I assigned it to you. :)
