### ISSUE TITLE
One case contact for two separate youth

### ISSUE THREAD

**Issue by kacrank** [rubyforgood/casa#1849]
**What type of user is this for? volunteer/supervisor/admin/all**
Volunteer

**Description**
Sometimes a volunteer has two youth who might be siblings, may be with them at the same time, visit them at the same location and want to only use one location/entry for two separate youth. Mentioned/requested by stakeholder Francha on 3/16/21.

**Screenshots of current behavior, if any**
https://casa-qa.herokuapp.com/case_contacts/new?case_contact%5Bcasa_case_id%5D=1438
![Screen Shot 2021-03-17 at 9 41 45 PM](https://user-images.githubusercontent.com/80864804/111560838-c452ab00-8769-11eb-850b-3e69dab499c8.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by compwron** [comment]
This is done for now
