### ISSUE TITLE
Use correct logo on weekly supervisor email

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1855]
### Impacted User Types
supervisors

### Environment
PROD

### Current Behavior
![wrong-weekly-logo](https://user-images.githubusercontent.com/578159/112085841-731b3080-8b48-11eb-9e90-c57b19bd3fe1.png)

**Comment by compwron** [comment]
This is done! :)

**Comment by talya19** [comment]
Done and deployed in prod.
