### ISSUE TITLE
Admin can soft-delete and un-delete case contacts

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1862]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin, for now... maybe supervisor later

**Description**
Montgomery admin wants to be able to delete case contacts that volunteers put in by accident when they were exploring the system. the ONLY known use case for this is cleaning up after volunteer mistakes. 

A deleted case contact should:
1. not appear in any case contact exports (by volunteer, supervisor, or admin)
1. not appear in any **court reports**
1. not appear on the volunteer UI
1. not appear on the supervisor UI
1. not affect "last contact made" column value on volunteers index https://casa-qa.herokuapp.com/volunteers page
1. not affect "no contact (14 days)" on supervisors index https://casa-qa.herokuapp.com/supervisors
1. **appear** on the admin ui for a case with a "[deleted]" in the row

On a technical level, this should probably be a default scope built with a gem like:
1. https://github.com/paper-trail-gem/paper_trail (we already have this- so this is preferred) 
1. https://github.com/rubysherpas/paranoia most popular purpose-specific gem - second runner up
1. https://github.com/jhawthorn/discard also acceptable but not preferred
1. something else??? talk the maintainers into it

**Screenshots of current behavior, if any**
![delete-case-contact](https://user-images.githubusercontent.com/578159/112412622-0fc20780-8cdc-11eb-825a-8572f8c18664.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by hairedfox** [comment]
@compwron I'd love to take this ticket :bow: Because I just work on this in my free time. So if it needs to be done faster, just remind me :D Thank you.

**Comment by compwron** [comment]
Yes! :)
