### ISSUE TITLE
Supervisor or Admin can add a comment/note on a case comment

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1863]
**What type of user is this for? volunteer/supervisor/admin/all**
Supervisor or admin

**Description**
This is discussed in slack on 24 March 2021 https://rubyforgood.slack.com/archives/CVB0QJGVD/p1616616509018700?thread_ts=1616615406.015800&cid=CVB0QJGVD

Supervisor or Admin can add a comment / note on a case comment - **as well as** being able to click the "follow up" button

**The overall desires here:**
1. engage supervisors more closely with volunteer case contacts (feedback from existing CASA supervisors: "I don't need to DO anything on [this website] just look at case contacts?"
1. reinforce to volunteers that their case contact recording is valuable by showing that supervisors pay attention and value the work. "volunteers want affirmation when they put things in"
1. other ??

**Alternate proposals:**
1. from Sarah (PG CASA) - Instead of"Follow up" button on case contacts, a "verify" button for the supervisor to approve the case contact (imo this would feel weird for the volunteer tho... I don't know)
1. from Sarah (PG CASA) - add buttons in the supervisor's weekly email to add a gold star to a case contact (lol I love it but not sure it's what everyone wants)

**Screenshots of current behavior, if any**
![supervisor-feedback](https://user-images.githubusercontent.com/578159/112414343-1ef68480-8cdf-11eb-8045-49b03a27d3da.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by librod89** [comment]
@compwron Can I work on this? There seems to be a lot of unknowns in this ticket. 

My first instinct is to just create new db tables `comments` and `casa_cases_comments` and a new button on this page "New Comment" or something that opens a popup that lets a supervisor/admin add a comment to the case. Maybe there can be another ticket for volunteers to see those comments somewhere? Let me know if I'm missing the mark on this feature entirely. Thanks!

**Comment by mussajoop** [comment]
Hi there 👋🏾,
I'd like to work on that issue

**Comment by mussajoop** [comment]
Hi there 👋🏾,
I'd like to work on that one

**Comment by Thrillberg** [comment]
@compwron @FireLemons and I brainstormed on this ticket today.

Some ideas for how to implement. We currently have Reminders which have functionality that is _close_ to what we want but with a few exceptions. The follow is our idea of what might be a nice way to resolve this ticket.
1. This ticket wants to support multiple comments at once
2. This ticket wants to make rewarding/supportive comments that can send notifications to volunteers (but don't need to--can be toggled with a checkbox). If checked, it indicates that more work is needed and the volunteer will keep receiving notifications until the comment is resolved (maybe not?). If unchecked, no more work needed; it's purely a supportive comment! ❤️ 
3. This ticket to display comments on the case contact view (probably at the bottom?)
<img width="1544" alt="Screen Shot 2022-10-13 at 2 20 48 PM" src="https://user-images.githubusercontent.com/10481391/195675729-adf6f07d-3c8b-4a33-9072-375213a2c917.png">

**Comment by compwron** [comment]
Stakeholder JH says this is still wanted! We should dig in more

**Comment by compwron** [comment]
We still want this but we need to write down more details and split out chunks of the ticket!

**Comment by compwron** [comment]
Closing as very old- see new fresh ticket
