### ISSUE TITLE
Add Last Logged In At to all users and visible to all users

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1864]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer/supervisor/admin

**Description**
Add Last Logged In At date (**not time** even though we could make it time- that's a little too detailed it feels like) to all users and visible to all users
1. A volunteer can see **their own** "last logged in at" but because they can't view a View Supervisor page, they can't see any other volunteer or supervisor or admin's Last Logged In At
1. a supervisor can see any volunteer or supervisor's Last Logged In At but not admin because they can't visit an Edit Admin page
1. an admin can see any volunteer, supervisor, or admin Last Logged In At

On the technical side, we should use Devise `:trackable` for this (we already use devise) https://github.com/heartcombo/devise <- search "trackable" in the readme

Remember to write tests!! 💖💪✨

**Screenshots of current behavior, if any**

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by efgalvao** [comment]
Hello, I can help with this issue.

**Comment by compwron** [comment]
Very cool, thanks! :)
