### ISSUE TITLE
Copy Court Orders from One Case into Another

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1865]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer, supervisor, admin

**Description**

Currently we have no way to copy court orders that have been entered once to sibling cases that they also apply to. We would like to add a way to do that to the Edit Case Details page. We want this feature to add court orders from a selected case to another existing case's court orders, not overwrite court orders from one case with court orders from another. Under the current "Court Orders - Please check that you didn't enter any youth names" text we would like to add text that says "Copy all orders from case:" and then a dropdown with all the cases the current user has access to. (For a volunteer this would be their own cases, for a supervisor or admin this would be all cases within a given CASA. As noted on the image below this new section of the page should only be visible to volunteers with more than one case, supervisors, and admins.) Next to this dropdown we would like to add a submit button that only impacts this new section of the form. This submit button would add all the court orders from the case selected in the dropdown to the case being edited (leaving any existing court orders on the case being edited as they were). 

**Screenshots of current behavior, if any**
<img width="1592" alt="copy-court-orders" src="https://user-images.githubusercontent.com/578159/163077624-0e066556-d26b-419d-9c25-7036cae5be75.png">

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by compwron** [comment]
@CovenantHuman let's work on this one sometime, I think it's still valuable

**Comment by mussajoop** [comment]
hello, I'd like to work on that issue

**Comment by mussajoop** [comment]
is this still open @compwron ?

**Comment by compwron** [comment]
@mussajoop go for it!
