### ISSUE TITLE
Fix bullet n+1 issues in tests: 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1869]
**Description**
in file `/Users/compiledwrong/repositories/casa/config/environments/test.rb` set `raise = true` and run the tests locally. Fix failures. 
More info: https://github.com/flyerhzm/bullet

**Comment by dmarcoux** [comment]
This issue seems to be a duplicate of #1405.

**Comment by compwron** [comment]
@dmarcoux agreed this is a duplicate. #1870 is having some troubles with cypress and I'm not sure why. Any ideas?
