### ISSUE TITLE
Add Contributors section to repo

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#188]
Do something nice to showcase our volunteers :) 

https://api.github.com/repos/rubyforgood/casa/contributors

**Comment by wlcreate** [comment]
Hi! I would love to do this if it's available :) 
Just wondering: 
1. Where would you like the Contributors section to be in (i.e. the READme)?
2. What information about the contributors would you like to be displayed (i.e. GitHub username, profile picture, & link to their profile)?

**Comment by jmkoni** [comment]
@wlcreate just GitHub username and make that a link to the profile

**Comment by jmkoni** [comment]
@compwron  do we even want this anymore? Now that there is a contributors section in GitHub, this just seems like something else to maintain that isn’t really needed.

**Comment by jmkoni** [comment]
@wlcreate in the meantime, I would try to find something with the Hacktoberfest label.

**Comment by wlcreate** [comment]
@jmkoni Thank you for letting me know! Happy Hacktoberfest :)

**Comment by cam-benfield** [comment]
Is this still open or should it be closed?

**Comment by cam-benfield** [comment]
@compwron , this should probably be removed from the To Dos since it's now automated by GitHub.

**Comment by compwron** [comment]
good point, will do :)
