### ISSUE TITLE
Give user ability to enable/disable SMS notifications

### ISSUE THREAD

**Issue by talya19** [rubyforgood/casa#1884]
**What type of user is this for? volunteer/supervisor/admin/all**
Volunteer and supervisor

**Description**
We can't send SMS notifications yet but at this time we'd like to store the user preference in the database
- [x] User can enable SMS notifications
- [x] User can disable SMS notifications if email notifications are enabled.
- [x] If volunteer has deactivated email notifications, they cannot deactivate SMS notifications (to be validated with Francha from Montgomery).

**Screenshots of current behavior, if any**
Currently, user receives notifications via email only.

User Acceptance criteria:

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 12345678

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by FireLemons** [comment]
I'm copying the text from this into a card

**Comment by FireLemons** [comment]
Sorry nevermind I marked it as  not ready to build
