### ISSUE TITLE
Give user the ability to customise which SMS notifications they want to receive

### ISSUE THREAD

**Issue by talya19** [rubyforgood/casa#1885]
**What type of user is this for? **
Volunteer and supervisor

**Description**
User can control the notifications that they want to receive via SMS from the app.

User Acceptance criteria:

- [x] User sees events for which they can receive SMS notifications
- [x] User selects the events for which they receive SMS notifications
- [x] User can disable all SMS notifications only if email notifications are enabled

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by harsohailB** [comment]
@compwron Can we re-open this issue? Seems like it has a card in the projects view. Not sure why it was closed.

**Comment by harsohailB** [comment]
@compwron What exactly are the "events" that this issue talks about?

**Comment by compwron** [comment]
"events" like "volunteer made case contact" or "casa case youth has birthday" :)
