### ISSUE TITLE
Volunteer receives SMS notification when their account is reactivated by admin

### ISSUE THREAD

**Issue by talya19** [rubyforgood/casa#1887]
Part of epic #1017

AS a volunteer,
I WANT to receive an SMS notification when an admin reactivates my account
SO THAT I am aware of my status at CASA

### How it works now

Currently, volunteer receives a notification via email at the time when an admin has reactivated their account or a little later (admin decides when to send notification).

### How it should work

Volunteer should additionally (they choose in preferences #1016 ) or instead of the email (#1884), receive an SMS notification every time an admin reactivates their account (admin decides when to send notification).

### Acceptance criteria

- [x] When an admin reactivates a volunteer and at the time the admin decides to send notification, that volunteer receives an SMS notification.
- [x] That notification appears in the user's SMS notifications.
- [x] The reactivation notification should be text that reads like this example:

"Hello [volunteer display name],

Your CASA/Prince George’s County volunteer console account has been reactivated. You can login using the credentials you were already using.

If you have any questions, please contact your most recent Case Supervisor for assistance.

CASA/Prince George’s County"

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 12345678
Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by FireLemons** [comment]
I don't think we want to send a message on deactivation anymore

**Comment by compwron** [comment]
agreed

**Comment by FireLemons** [comment]
wait don't we still want to send a text when an account is reactivated

**Comment by compwron** [comment]
oops yes

**Comment by 7riumph** [comment]
> I don't think we want to send a message on deactivation anymore since we're not sending emails for it either

@compwron just confirming that this is still true so I can edit out the volunteer deactivation portion of this issue.

**Comment by compwron** [comment]
@[7riumph](https://github.com/7riumph) correct
