### ISSUE TITLE
add Reset Password to Edit Profile

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#189]
part of epics #3, #105, #4

**What type of user is this for? [volunteer/supervisor/admin/all]**
all (but most pressingly, volunteers)

**Where does/should this occur?**
On the <a href="https://casa-r4g-staging.herokuapp.com/users/edit">edit profile</a> page for all users.

**Description**
Add "Reset password" field to Edit Profile page.

**Related issues**
#125

**Comment by alindeman** [comment]
Is the idea here that the user is logged in, but has forgotten their password (so would not be able to login again)? Or that they know their current password but want to change it? Or maybe something else?

**Comment by compwron** [comment]
I think this should be available 
1. when the user is not logged in- it sends a "reset my password" link to the user's email
I think it's fine if this behavior is also present when the user is logged in but I would expect it to be less used

**Comment by seanmarcia** [comment]
Working on this.
