### ISSUE TITLE
Do not raise error when clicking Created By on case contact created by supervisor

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1902]
### Impacted User Types
admins and supervisors

### Environment
staging (all)

### Current Behavior
ex: When I click "generate report," no report is generated.
![bug](https://user-images.githubusercontent.com/578159/113464873-cad95780-93e4-11eb-8b5b-42929d72a34e.png)

### Expected Behavior
go to edit supervisor page 

### How to Replicate
1. login as admin or supervisor
1. create case contact
1. go to case page
1. click Created By on case contact (lower right)
1. see error :(

QA Login Details:
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.

volunteer1@example.com
supervisor1@example.com
casa_admin1@example.com

**Comment by hairedfox** [comment]
@compwron Could you provide me the screenshot or any log of this error? :D

**Comment by kacrank** [comment]
@hairedfox looks like the error may be related to a missing assigned volunteer name.

![new case contact error](https://user-images.githubusercontent.com/80864804/113803342-5414c500-972a-11eb-90f1-65d8ff9be217.png)

when I create a new contact, the volunteer name also differs from the name used in previous contacts for the same case.
![new case contact error 2](https://user-images.githubusercontent.com/80864804/113803383-6bec4900-972a-11eb-9dbf-0417291190b6.png)

**Comment by compwron** [comment]
@kacrank what user are you logged in as? Different users can create case contacts- past volunteers, current volunteers, any supervisor, any admin

**Comment by kacrank** [comment]
@compwron in this case was logged in as supervisor...

**Comment by cam-benfield** [comment]
@compwron , are you still able to get this error? I just attempted with admin1 and no error on case CINA-05-1003.

**Comment by compwron** [comment]
this was an admin clicking on Created By on a case contact created by a supervisor. So in that case let's assume that it is fixed. :)

**Comment by cam-benfield** [comment]
Sounds good! This can safely be closed then.

**Comment by CovenantHuman** [comment]
Cannot reproduce
