### ISSUE TITLE
make supervisors deactivate-able

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1906]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
Admins should be able to de-activate supervisors (in the same way that supervisors can de-activate volunteers).

**Screenshots of current behavior, if any**
currently no option to de-activate, only to edit (logged in as admin in screenshot below):
![Screen Shot 2021-04-07 at 2 44 11 PM](https://user-images.githubusercontent.com/80864804/113917875-c4195e80-97af-11eb-9669-d4912d5ffb9a.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by compwron** [comment]
@talya19 @kacrank @priyankaerao when you have time please do the PM magic to make this issue useful xD

**Comment by efgalvao** [comment]
Just make the supervisor deactivable/activable like volunteers ?
What type of user will have he "power" to deactivate a supervisor ?
I can try to do this one.

**Comment by compwron** [comment]
> Just make the supervisor deactivable/activable like volunteers ?
Correct

An admin will be able to do this. A supervisor will not.

**Comment by efgalvao** [comment]
Ok. I will try to help with this one, ok ?

**Comment by efgalvao** [comment]
Just to be sure, when a supervisor is deactivated, should I unassign all volunteers from him ?

**Comment by compwron** [comment]
> Just to be sure, when a supervisor is deactivated, should I unassign all volunteers
@efgalvao that's a good question! Let's say yes for now

PMs please keep this in mind as something to worry about @kacrank @priyankaerao @talya19

**Comment by talya19** [comment]
Ok will take a look at this issue!

**Comment by compwron** [comment]
@talya19 what's up here? ^

**Comment by talya19** [comment]
Hello! Sorry didn’t have time yet...

**Comment by kacrank** [comment]
@compwron added a few notes to the initial issue, lmk if anything's missing!
