### ISSUE TITLE
Show error on failed case court report generation

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1917]
**What type of user is this for?**
volunteer

**Description**
The generate report button just hangs if the operation fails. It would be nice to show an error on failure instead
**Current behavior**
![image](https://user-images.githubusercontent.com/8918762/113661162-33396a80-966b-11eb-9c87-d358dc10729e.png)
![image](https://user-images.githubusercontent.com/8918762/113661184-3e8c9600-966b-11eb-9145-1145f184d9b9.png)

**Comment by hairedfox** [comment]
@compwron I'll take this task 👍

**Comment by compwron** [comment]
Great! :)
