### ISSUE TITLE
Appointed date does not appear on generated court reports

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1931]
### Impacted User Types
volunteers

### Current Behavior
generating a court report does not display the date the volunteer was assigned to the case
no date after "Appointed:"
![image](https://user-images.githubusercontent.com/8918762/113954674-eb881f80-97df-11eb-9e25-cdfb09ca4bca.png) 
Attempting to manually generate the date throws an error
![image](https://user-images.githubusercontent.com/8918762/113954912-618c8680-97e0-11eb-9c3f-1fdecfb4d102.png)

### How to Replicate
ex: 
 - Log as a volunteer.
 - Click on "Generate Reports" in the left sidebar menu.
 - Generate a report

**Comment by hairedfox** [comment]
@compwron Let me take a look at this

**Comment by compwron** [comment]
:)
