### ISSUE TITLE
Supervisor weekly email is broken!!

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1932]
Event in production from casa in send_supervisor_digest (details)
Unhandled error
ActionView::Template::Error: undefined method `path_for' for #<ActiveStorage::Service::AzureStorageService:0x0000563f608cd8b8>
Location
app/models/casa_org.rb:36 - org_logo

https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1617620513150000

**Comment by dmarcoux** [comment]
This is the same error as #1883
