### ISSUE TITLE
Created date is not showing up in court reports

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1947]
### Impacted User Types
volunteers

Date written should not be blank
![image](https://user-images.githubusercontent.com/8918762/114658468-74f39200-9cb7-11eb-817d-363d89932481.png)

You may notice other fields are blank after generating the report. That's not because they're also broken. It's because the test data seeder leaves some fields blank. 
![image](https://user-images.githubusercontent.com/8918762/114658795-0e22a880-9cb8-11eb-9499-295657bf9a8b.png)

### How to Replicate
1. - log in to [QA](https://casa-qa.herokuapp.com/) or locally with `volunteer1@example.com`, `123456`
2. - Click on "Generate Reports" in the left sidebar menu.
3. - Generate a report

**Comment by efgalvao** [comment]
Hello, can I work on this one ?
