### ISSUE TITLE
let supervisors and admins generate court reports for a case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1969]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer, supervisor, admin

**Description**
https://casa-qa.herokuapp.com/case_court_reports
Let supervisors and admins generate court reports for a case
Add generate court report button to a case as well as having it in a sidebar item

**Screenshots of current behavior, if any**
![Screen Shot 2021-04-21 at 6 35 06 PM](https://user-images.githubusercontent.com/578159/115642754-6406da00-a2d0-11eb-90c6-08ff13ed3b61.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by hairedfox** [comment]
@compwron let me take this issue :D Thank you

**Comment by librod89** [comment]
I'll take this issue.
