### ISSUE TITLE
Refactor spec/system/supervisors/index_spec.rb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1990]
Refactor spec/system/supervisors/index_spec.rb

as a follow-on to 
https://github.com/rubyforgood/casa/pull/1929/files

**Comment by rhian-cs** [comment]
May I work on this issue? Not sure if @ErinClaudio is doing this one

**Comment by compwron** [comment]
Go for it! I think Erin is busy with something else :)
