### ISSUE TITLE
Add button for supervisor to remind volunteer to input case contacts

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2009]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor/admin

**Description**
Add button for supervisor to send volunteer a reminder email (someday we may also support SMS but not yet) to input case contacts
The button should be on the volunteer page *and* on the case page
There should be a tooltip with text explaining that an email will be sent to the volunteer
The supervisor should be CC'd on the email

<img width="1016" alt="case-reminder-button" src="https://user-images.githubusercontent.com/578159/118861764-b9afb180-b891-11eb-92cc-3586d38c82ca.png">
<img width="1080" alt="Cursor_and_CASA_Volunteer_Tracking" src="https://user-images.githubusercontent.com/578159/118861766-ba484800-b891-11eb-84b3-4ad52905371b.png">

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by efgalvao** [comment]
The button will send a notification ? An e-mail ?
Where exactly the button should be on the volunteer page and on the case page ?

**Comment by compwron** [comment]
@efgalvao thanks for the great questions! I added more details to the description and also some screenshots

> Add button for supervisor to send volunteer a reminder email (someday we may also support SMS but not yet) to input case contacts
> The button should be on the volunteer page *and* on the case page
> There should be a tooltip with text explaining that an email will be sent to the volunteer
> The supervisor should be CC'd on the email

 I don't have a precise idea of what the text of the email should be. For now just make up something that sounds good, and we will try to get more details from our stakeholders.

**Comment by efgalvao** [comment]
Ok. I would like to try this one, can you assign to me ?

**Comment by compwron** [comment]
Very cool, thanks! :)
