### ISSUE TITLE
Add to supervisor weekly email - re-invite your volunteer with this button

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2010]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor/admin

**Description**
Add to supervisor weekly email - re-invite your volunteer with this button

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by efgalvao** [comment]
Just to confirm, you want a button to re-invite volunteers, who has not accepted yet, by the supervisor who is the recipient of that mail ?

**Comment by efgalvao** [comment]
@compwron What you think of this 2 approaches ?
1 - The supervisor click in the link/button in the email, he is redirected to the site asking to login if not logged in, then the e-mail is sent automatically
2 - Supervisor click in the link, he is redirected to some page with no user authentication, checks a token and if ok then send the email.
