### ISSUE TITLE
Show casa admin a list of all emails we send

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2011]
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**
Show casa admin a list of all emails we send 
On the casa org page
If it's easier, show types of emails rather than exact individual emails and recipients

**Screenshots of current behavior, if any**
https://casa-qa.herokuapp.com/casa_orgs/28/edit
![CASA_Volunteer_Tracking](https://user-images.githubusercontent.com/578159/118064548-11a95e00-b350-11eb-8da2-177b6a4a8ad3.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- casa_admin1@example.com

**Comment by compwron** [comment]
@aedwardg this one is for you

**Comment by aedwardg** [comment]
@compwron, 

Is the backend keeping track of the sent emails anywhere, or will that need to be implemented? 
I took a look through the db schema and the various models but nothing I came across seems to be doing this.

**Comment by compwron** [comment]
> Is the backend keeping track of the sent emails anywhere
Not explicitly. Rails may be doing it somewhere but I don't think so.

**Comment by aedwardg** [comment]
I have a couple more questions:

1. Do we care about having a many to many relationship between these sent emails and the recipients (users)?
2. When we're displaying the recently sent Supervisor weekly digest, do we want to show one entry for each recipient (supervisor) or just one entry that says the weekly digest was sent out?
   - I don't think it would matter much if there are only a couple of supervisors, but if there are more than 10 and we are showing one entry per recipient, then the entire preview would consist of 10 random recipients of the same email. That doesn't seem like it would be particularly useful to me.

**Comment by compwron** [comment]
> I have a couple more questions:
> 
> 1. Do we care about having a many to many relationship between these sent emails and the recipients (users)?
> 2. When we're displaying the recently sent Supervisor weekly digest, do we want to show one entry for each recipient (supervisor) or just one entry that says the weekly digest was sent out?
>    
>    * I don't think it would matter much if there are only a couple of supervisors, but if there are more than 10 and we are showing one entry per recipient, then the entire preview would consist of 10 random recipients of the same email. That doesn't seem like it would be particularly useful to me.

1. it would be nice to have `volunteer.emails`, `supervisor.emails` etc. It would also be nice to have `email.sent_to`. (we could divine it from email, unless email has changed... people are allowed to change their emails) 
2. I have no preference right now, use your judgement. :)

**Comment by aedwardg** [comment]
I'm still working on this. Don't unassign me, silly bot! 😄
