### ISSUE TITLE
For Volunteer with only one case, open directly to Create Contact page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2012]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer

**Description**
For Volunteer with only one case, open directly to Create Contact page

**Screenshots of current behavior, if any**

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by ChaelCodes** [comment]
What page are they starting on or attempting to go to when we want to open the Create Contact page?

**Comment by compwron** [comment]
@ChaelCodes I have a start on a PR for this but I won't have time for it for a while (if you want to take it over, please do!), 
https://github.com/rubyforgood/casa/pull/2059
Basically I want to reduce the number of clicks for a volunteer to get to their core task of entering a case contact

**Comment by ChaelCodes** [comment]
@compwron Thanks! @muydanny and I will pick this up if we stream today, otherwise, we'll pick it up next week.

**Comment by ChaelCodes** [comment]
This issue is ready to be closed by #2061 !

**Comment by compwron** [comment]
cool, will do :)
