### ISSUE TITLE
Make ios app for CASA

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2013]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
We want an IOS app in the app store so that low-tech users can install it easily. 

Our top priority is to have minimal additional maintenance costs for this, so let's use as much webview as possible, as long as the user experience is even moderately acceptable. 

Note for team leads(NOT RELEVANT TO ISSUE)
When the app is published to the app store, make sure it is not published as an individual person but instead from a ruby for good account. Also, make sure that it is super clear that it is R4G not CASA itself publishing the app- their national marketing would NOT like that.

**Comment by compwron** [comment]
We still want this. It will be more complicated than the Android app maybe.

**Comment by aedwardg** [comment]
Posting this link here so we have it on hand -- minimum functionality guidelines for app to be accepted in the Apple App Store:
https://developer.apple.com/app-store/review/guidelines/#minimum-functionality
