### ISSUE TITLE
Invalid Email or password message should flash in red.

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#202]
Part of epic #38

**What type of user is this for? [volunteer/supervisor/admin/all]**
all

**Where does/should this occur?**
<a href="https://casa-r4g-staging.herokuapp.com/users/sign_in">Login screen</a>

**Description**
After an unsuccessful login attempted due to invalid email or password, the corresponding error message should flash in red. (Currently, the text has no highlight color and is not very noticeable.)

**Screenshots of current behavior**
<img width="1376" alt="invalid email pw" src="https://user-images.githubusercontent.com/62810851/80315035-05387e80-87aa-11ea-9837-d66d6bb07195.png">

**relates to issues**
#166

**Comment by colinsoleim** [comment]
Fixed by https://github.com/rubyforgood/casa/pull/211
