### ISSUE TITLE
New unhandled error in qa from casa in GET /supervisors/edit 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2029]
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1620757097410400
BugsnagAPP  11:18 AM
New unhandled error in qa from casa in GET /supervisors/edit (details)

Unhandled error
AbstractController::ActionNotFound: The action 'show' could not be found for SupervisorsController
Did you mean?  new
              current_organization
              require_organization!
              current_role
Location
vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/abstract_controller/base.rb:160 - process

**Comment by FireLemons** [comment]
triggered by attempting to access urls in the form https://casa-qa.herokuapp.com/supervisors/**<supervisor_id>**/

for example:
https://casa-qa.herokuapp.com/supervisors/1820/

could there be a bad redirect somewhere?

**Comment by CovenantHuman** [comment]
closing as outdated
