### ISSUE TITLE
When generating court report fails for any reason, show an error

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2038]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer

**Description**
Currently, it only shows an error for errors of type `Zip::Error`
Please throw the error again so our error monitoring service bugsnag can give us a stack trace. 

see `app/controllers/case_court_reports_controller.rb`

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by hiendinhngoc** [comment]
I am working on this issue
