### ISSUE TITLE
Hide Download All button when there are no case contacts

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2040]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
Hide Download All button when there are no case contacts

**Screenshots of current behavior, if any**
![Screen Shot 2021-05-12 at 8 00 16 PM](https://user-images.githubusercontent.com/578159/118071501-c0ec3200-b35c-11eb-96f6-118b8d4aa17d.png)

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- volunteer1@example.com
- supervisor1@example.com
- casa_admin1@example.com

**Comment by hiendinhngoc** [comment]
I am working on this issue
