### ISSUE TITLE
Add trait :with_case_contacts for casa case factory

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2044]
add a `:with_case_contacts` trait to the casa case factory
when creating the contacts, associate the contacts with a volunteer assigned to the case if the volunteer exists

basically this trait allows for a creation of a test casa case with case contacts already associated with it

see `spec/factories/casa_case.rb `

**Comment by efgalvao** [comment]
So you want a trait to automatically create a volunteer and some case contacts when you need to create a casa case?

**Comment by compwron** [comment]
Yep!

**Comment by FireLemons** [comment]
@efgalvao Actually just ignore the part about the volunteer. Just the case contacts would be fine. Otherwise it would duplicate the function of ` trait :with_cases_and_contacts` in `casa/spec/factories/volunteer.rb `

**Comment by efgalvao** [comment]
Can I try to do this one ?
How many contacts you think is good ? 
Can I write all required fields to be randomly generated/chosen ?

**Comment by FireLemons** [comment]
@efgalvao 

> How many contacts you think is good ?  

it looks like the most a test will use is 3 contacts. 

> Can I write all required fields to be randomly generated/chosen ?  

case contacts has a factory that does that
