### ISSUE TITLE
UI button overlap bug for case contacts

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2049]
### Environment
staging
qa
prod

### Current Behavior
button overlap on firefox
![image](https://user-images.githubusercontent.com/8918762/118410994-f8f2be00-b657-11eb-8f7f-d988b882e00d.png)

### How to Replicate
1. - Open casa in firefox
2. - Log into staging as an anyone.
3. - Click a casa case with case contacts.

**Comment by cam-benfield** [comment]
I'd like this :)

**Comment by cam-benfield** [comment]
@FireLemons , I'm able to reproduce this on staging in Firefox. Can you send over a URL pattern for where this should be? I'm Cam Benfield in Slack or you can add it to the bug specs. I'll let you know if I'm able to replicate here.

**Comment by cam-benfield** [comment]
Figured it out! Need to enter into a case with a recent contact, then click **Follow Up** on that recent contact.  👍

**Comment by cam-benfield** [comment]
Just updated this to better resolve it with bootstrap rather than CSS.
