### ISSUE TITLE
Don't run github actions for direct commits on the repo changing only readme files and documentation

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2060]
see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
see `.github/workflows/`

**Comment by FireLemons** [comment]
sometimes I like to edit the readmes on github but it triggers our test suite.
A huge thank you if you get this before me.

**Comment by r-sierra** [comment]
This has been addressed in PR #1313, so it should be closed.

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/123864772-c099fd00-d8f0-11eb-9eea-4ddc608bddf1.png) :thinking:

**Comment by r-sierra** [comment]
Oh, that README is in `bin/git_hooks/`. Seems that the `paths-ignore` filter is not set correctly.

**Comment by r-sierra** [comment]
@FireLemons should we skip CodeQL as well?
What about files under `/doc`, should we skip all of them too? Currently the workflows only skips files under `/docs/`

**Comment by FireLemons** [comment]
yeah doc should be skipped @r-sierra

**Comment by FireLemons** [comment]
@r-sierra why is it wrong? shouldn't it qualify under `*.md` and `bin/*`
![image](https://user-images.githubusercontent.com/8918762/123891934-4634a180-d91f-11eb-8f52-647fc8a9aa1d.png)

**Comment by FireLemons** [comment]
oh ok I see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

**Comment by r-sierra** [comment]
> yeah doc should be skipped @r-sierra

I'll take this as ok for skipping in CodeQL as well
