### ISSUE TITLE
Make Importing supervisors idempotent

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2068]
https://github.com/rubyforgood/casa/issues/2070 possibly dependent on this issue not being fixed

### Impacted User Types
admins

### Current Behavior
importing a supervisor data csv sucessfully will print an error on the second import attempt because the volunteers have already been added to the supervisor

### Expected Behavior
having volunteers already added to a supervisor should not result in an error

### How to Replicate
ex:
1. - Log into staging as an admin (username: casa_admin1@example.com, pass: 123456)
2. - Click on "System Imports" in the left sidebar menu.
3. Upload a csv like the ones found in `spec/fixtures`
4. Try importing again with the same CSV

**Comment by r-sierra** [comment]
I am working on it

**Comment by r-sierra** [comment]
Im not able to reproduce this issue. After reviewing the code i found that a fix was made in commit 8d6fbffdd3db6b0c00773b18e24668ff847868a9 that solves this issue.
@FireLemons, should i add tests to check for regressions ?

**Comment by FireLemons** [comment]
@r-sierra I guess the problem was only #2070. I didn't check QA again after 2070 was fixed.
