### ISSUE TITLE
Unhandled error when importing supervisor data

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2069]
### Impacted User Types
admins 

### Environment
ex: staging, local, qa

### Current Behavior
uploading `spec/fixtures/supervisor_volunteer.csv` to the supervisor importer causes an unhandled error

### Expected Behavior
gracefully handle the error

### How to Replicate
ex: 
1. - Log into staging as an admin. username: casa_admin1@example.com, pass: 123456
2. - Click on "System Imports" in the left sidebar menu.
3. Click the supervisor imports tab, attempt to upload [supervisor_volunteers.csv](https://github.com/rubyforgood/casa/files/6525566/supervisor_volunteers.csv)

**Comment by josearmandojacq** [comment]
@FireLemons after following the steps to replicate it, i see this:
<img width="1106" alt="Screenshot 2021-08-09 at 19 23 27" src="https://user-images.githubusercontent.com/24357305/128747627-54254f69-aba0-4db7-89bf-8921b7a86404.png">

What you mean with “gracefully handle the error” 😄

**Comment by FireLemons** [comment]
this may have gotten fixed with some previous prs. What does the failed rows file contain?

**Comment by josearmandojacq** [comment]
“Row contains unimported volunteers”

**Comment by FireLemons** [comment]
this seems fine
