### ISSUE TITLE
Android App web wrapper

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2071]
Create an android app where [our casa website](https://casa-production.herokuapp.com/) is simply linked in a [Trusted Web Activity](https://developer.chrome.com/docs/android/trusted-web-activity/overview/) in fullscreen mode.

**Comment by FireLemons** [comment]
https://developer.chrome.com/docs/android/trusted-web-activity/integration-guide/

**Comment by FireLemons** [comment]
newest com.google.androidbrowserhelper:androidbrowserhelper 
https://github.com/GoogleChrome/android-browser-helper/releases

**Comment by compwron** [comment]
https://github.com/compwron/ruby-for-good-CASA-android-app

**Comment by FireLemons** [comment]
https://stackoverflow.com/questions/27081347/how-can-deploy-signed-apk-when-click-run-in-android-studio

**Comment by FireLemons** [comment]
dev and prod keys?
