### ISSUE TITLE
Style Set password screen

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2083]
**What type(s) of user does this feature affect?**
volunteers, supervisors, admins

**Description**
Center the body on the set/reset password page. It shows up after accepting an invitation after an account is created.

**Screenshots of current behavior**  
![image](https://user-images.githubusercontent.com/8918762/119753008-a9846d00-be63-11eb-8b50-e6ab1c971ac2.png)

**Desired look**
Something closer to this(mostly positioning)
![image](https://mk0techtrackdat3j03u.kinstacdn.com/wp-content/uploads/2020/06/Password-Reset-Page-v2.0-1024x740.png)

**Comment by efgalvao** [comment]
Can I try to do this one ?

**Comment by efgalvao** [comment]
@compwron , I should leave as show in this picture and you decide later or you want me to set one ?
![Screenshot from 2021-06-04 12-11-28](https://user-images.githubusercontent.com/61836657/120823849-3c8d6900-c52e-11eb-99b3-8cccf0f77d7e.png)

**Comment by compwron** [comment]
The color is fine as it, it's good that it matches the rest of the site, it is the CASA brand color :)
