### ISSUE TITLE
Generate Report button UI changes and don't disappear

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2084]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
green Generate Report button should not disappear

**Screenshots of current behavior**  
![generate2](https://user-images.githubusercontent.com/578159/119756223-172a9c00-be58-11eb-97d1-53544224ff17.png)
![button1](https://user-images.githubusercontent.com/578159/119756226-17c33280-be58-11eb-8d05-cb6ea343b80c.png)
see `app/views/casa_cases/show.html.erb`

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by librod89** [comment]
This is the same functionality that happens on the `/case_court_reports` page when you generate a report. Do you want to stop the button from disappearing there too?

**Comment by compwron** [comment]
> This is the same functionality that happens on the `/case_court_reports` page when you generate a report. Do you want to stop the button from disappearing there too?

Yes please! :)

**Comment by compwron** [comment]
We want to do this on this page 
![image (4)](https://user-images.githubusercontent.com/578159/121760468-cfef0d00-cadf-11eb-90ff-632b3fe92149.png)

**Comment by librod89** [comment]
@compwron I just tested this on main, and the button is showing on that page. Are you using a supervisor or admin account? This button is only shown if the current user is supervisor or admin. Should I change this to always show this button?

**Comment by FireLemons** [comment]
Oh we thought based on the screenshot that the pr was done on the wrong element. So it's the same component on 2 pages
