### ISSUE TITLE
Remove e-mail header image

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2089]
This issue effect supervisors in the weekly supervisor e-mail. 

Code to change:
see `app/layouts/mailer.html.erb`
see `./devise/mailer/reset_password_instructions.html.erb`

![Logo Missing](https://user-images.githubusercontent.com/7007647/128798554-471df204-1134-4495-abe4-9e547d6e8def.PNG)

### Impacted User Types
Supervisors

### Environment
Prod
**!!! Important Prod Links to images via rails ActiveStorage which is connected to azure cloud storage.** This may be related to the issue. In a local environment, ActiveStorage just uses the local file system. 

### Current Behavior
sometimes images fail to load on emails

### Expected Behavior
When emails are received there should be no header image.

### How to Replicate
see https://github.com/rubyforgood/casa/wiki/Helpful-Commands for help generating local emails
letter opener displays sent emails in a new tab when sending emails from your test environment

**Comment by compwron** [comment]
![Screen Shot 2021-06-02 at 1 18 48 PM](https://user-images.githubusercontent.com/578159/120546733-17212380-c3a5-11eb-957a-4e0f3a81b8ef.png)
![Screen Shot 2021-06-02 at 1 18 38 PM](https://user-images.githubusercontent.com/578159/120546735-17b9ba00-c3a5-11eb-83c8-5ac290f3c3e0.png)

**Comment by rhian-cs** [comment]
@compwron what is the `src` value in the mails'  `img` tag?

**Comment by compwron** [comment]
You can see the src value in the file `reset_password_instructions`

**Comment by compwron** [comment]
the problem might be that the heroku link to the hosted image expires... maybe we need to host the image differently.
