### ISSUE TITLE
Convert inline css to .scss file

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2100]
Put new css code in the `.scss` files in `casa/app/javascript/src/stylesheets`

Search for `style=` in each `.erb` file and make (or preferrably reuse) a class in a `.scss` file

One `.erb` file per PR where possible, to keep PRs small

How this list was found: `grep -rin "style=" app` -> regex remove the non-filename -> `cat file | uniq`

1. app/views/case_contacts/_case_contact.html.erb
1. app/views/imports/_csv_error_modal.html.erb
 - the inline styling might be valid here for a js reason
1. app/views/emancipations/show.html.erb
 - Valid-ish for js in a jQuery kind of way. Might refactor `display` into a class later

**Comment by FireLemons** [comment]
see `https://github.com/rails/webpacker#paths` for email pack setup
