### ISSUE TITLE
split form into multiple saves for edit case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2118]
**What type(s) of user does this feature affect?**
all

**Description**
![editing](https://user-images.githubusercontent.com/578159/120879037-65851c80-c575-11eb-86ce-c15601661f3c.png)
![editing2](https://user-images.githubusercontent.com/578159/120879039-661db300-c575-11eb-9203-37f3c4f6aa8a.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/120879270-d46b7100-c587-11eb-8e30-f839a07f6e27.png)
copy this here on the edit casa case 
![image](https://user-images.githubusercontent.com/8918762/120879277-e0efc980-c587-11eb-9015-01939e1792f4.png)

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/120879299-fc5ad480-c587-11eb-9aae-3099e0f4c7dc.png)
edit casa case mandates delete button is strange

**Comment by talya19** [comment]
Hey @compwron and @FireLemons I want to add information here but I am not sure if the comments are additional developments to be done or explain the title...
Does the title mean: for each editable element when a user edits a case, they can save each edit with additional save buttons?

**Comment by FireLemons** [comment]
@talya19 this is a collection of ideas that will probably become several issues with some organization and more planning. In general the "Update casa case" button updates the whole form which can be split into several smaller pieces. So for example the "Court Details" section could have it's own save button and look visually separate from the rest of the form.

**Comment by talya19** [comment]
Ok I understand now thanks! 
Is that a request from stakeholders? or else?

**Comment by FireLemons** [comment]
@talya19 Not a request. Just me and compwron trying to make the form clearer

**Comment by FireLemons** [comment]
lets just wait for steph to get to this
