### ISSUE TITLE
Allow Supervisor or Volunteer or Admin to add a note to a Follow Up

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2119]
**What type(s) of user does this feature affect?**
- volunteers
 - supervisors
 - admins

**Description**
What **should** happen:
1.  A Supervisor or Volunteer or Admin selects a case contact and clicks on Follow up
1. The user sees a box appear with grey text "Optional: add a note about what followup is needed" and a Submit button
1. The user clicks the submit button
1. A volunteer assigned to a supervisor can see the note of the supervisor in the follow-up notification and supervisor can the note of the volunteer in the follow-up notifications in the inbox section
1. A volunteer can see their own note in the follow-up notifications in the inbox section
1. An admin can see the notes of supervisors and volunteers in the follow-up notifications in the inbox section

**Screenshots of current behavior, if any**  
![notification](https://user-images.githubusercontent.com/578159/120877562-1ab2d700-c56c-11eb-85d9-36b79f0c044e.png)
![followup-button](https://user-images.githubusercontent.com/578159/120877563-1b4b6d80-c56c-11eb-9fd2-23cba7f32090.png)
![more-note](https://user-images.githubusercontent.com/578159/123192032-fbb2b100-d456-11eb-8270-238876a1a00c.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by rhian-cs** [comment]
May I work on this issue?
