### ISSUE TITLE
Reset password email has Prince George logo

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2121]
### Impacted User Types
all

### Environment
prod, all

### Current Behavior
![reset-password-supervisor](https://user-images.githubusercontent.com/578159/120877863-a842f680-c56d-11eb-8b17-6ffd52b13c1c.png)

### Expected Behavior
correct logo OR generic logo without casa name

I think we want this but with a blue background(the same blue as the rest of the site)
![image](https://user-images.githubusercontent.com/8918762/120879374-7c813a00-c588-11eb-92d7-efa6fdfdfbf0.png)

### How to generate
reset email

**Comment by rhian-cs** [comment]
Hello, I am working on this issue.
