### ISSUE TITLE
Make it possible to unset hearing type for a case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2142]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Always have "-Select Hearing Type-" as an option and selecting it unsets the hearing type
Do not have "-Select Hearing Type-" selected by default when the hearing type has been set

**Screenshots of current behavior, if any**  
Before a hearing type is selected
![image](https://user-images.githubusercontent.com/8918762/121764256-41db4c80-cb08-11eb-883c-4a15284baff4.png)
And after
![image](https://user-images.githubusercontent.com/8918762/121764276-5ddeee00-cb08-11eb-9681-8460e7053740.png)
They don't look exactly like that but I can't get a screenshot of the select dropdown

see `app/views/casa_cases/_form.html.erb`

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by r-sierra** [comment]
I started to work on it
