### ISSUE TITLE
Serve email previews in nonprod environments

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2144]
The goal here is to be able to preview emails in QA and staging when logged in as any user, similar to how -- works locally (http://localhost:3000/rails/mailers/)

```
# config/initializers/action_mailer_previews.rb
return unless Rails.application.config.action_mailer.show_previews

Rails.application.reloader.to_prepare do
  # Ensure previews are sorted alphabetically
  Dir["#{Rails.application.config.action_mailer.preview_path}/**/*_preview.rb"].sort.each { |f| require f }

  Rails::MailersController.prepend_before_action do
    authenticate_user!
    head :forbidden unless current_user.super_admin?
  end
end
```

```
# config/application.rb
    config.action_mailer.default_url_options = { host: Rails.application.secrets.self_url, protocol: "https" }
    config.action_mailer.preview_path = "#{Rails.root}/app/mailer_previews"
```

Move preview files from `spec/mailers/previews` to `app/mailer_previews/`

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/126516196-8cbd2a42-2617-4d3d-8d23-9d2c9aa1275b.png)

**Comment by FireLemons** [comment]
nope

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/126660617-eaf01dc0-d0a2-4d4a-8932-b7a6265625eb.png)
what the heck why is it called production.rb

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/126678735-8922fe07-6660-484e-a38a-d0f9737307d2.png)
