### ISSUE TITLE
refactor: remove transition_aged_youth and only use casa_case.birth_month_year_youth 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2145]
refactor: remove all usages of `casa_case.transition_aged_youth` and only use `casa_case.birth_month_year_youth` and also make a migration to remove `casa_case.transition_aged_youth`. Make sure to use "Rails Ignored Columns".

We want to do this because having two different flags for this is having extra state which is unnecessary. 

Also remove this rake task
and the heroku job that runs it in qa, staging, and prod. 
```
desc "Transition youth who are now 14, run by heroku scheduler"
task transition_youth: :environment do
  puts "Updating casa cases..."
  CasaCase.should_transition.update_all(transition_aged_youth: true)
  puts "done."
end
```

**Comment by hiendinhngoc** [comment]
Hi, I am going to work on this issue.

**Comment by compwron** [comment]
https://www.cloudbees.com/blog/rails-migrations-zero-downtime is important reading for zero downtime migrations

**Comment by compwron** [comment]
@hiendinhngoc How's it going? :)

**Comment by hiendinhngoc** [comment]
hi @compwron, sorry for getting back to this issue so late. I tried to fix the failed test but did not succeed plus I am currently so busy and cannot spend much time with it. Could you assign it to someone who can spend more time on it?

**Comment by compwron** [comment]
@hiendinhngoc I will do that. Thanks! Good luck with your stuff. Come hang out with us any time :)

**Comment by dvsconcept1986** [comment]
I would like to take on this issue. Thanks

**Comment by compwron** [comment]
this is done! :)
