### ISSUE TITLE
Disable Court Report Case Search For Volunteers

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2150]
**What type of user does this feature affect?**
 - volunteers

**Description**
A volunteer will never have enough cases to warrant searching.
 - On the Generate Court Reports page, disable the search UI for casa cases if the user is a volunteer.
 - Write a test

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/121791393-08115100-cbaf-11eb-820b-64de5f1bb8f6.png)
remove the search bar. just make it a dropdown
see `app/views/case_court_reports/index.html.erb`

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
password: 123456

**Comment by rhian-cs** [comment]
Hello, may I work on this issue?
