### ISSUE TITLE
Email footer contains links without urls

### ISSUE THREAD

**Issue by librod89** [rubyforgood/casa#2157]
### Impacted User Types
All

### Environment
All

### Current Behavior
All of the mailers have a footer with two links "About CASA" and "Update Profile". These links are not hooked up to anything though. They just look like confusing text.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/4965672/121932677-c3023180-cd0a-11eb-8ddd-b416351227be.png">

### Expected Behavior
The links in a mailer should all go to the correct location within the app.

### How to Replicate
ex: 
1. -  Go to `localhost:3000/rails/mailers/supervisor_mailer/weekly_digest`
2. - Look at the bottom of the email
3. - Try to click "About CASA" or "Update Profile"
4. - Nothing happens

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/121994519-11dfb380-cd6b-11eb-82ea-20eb04bc0bf7.png)

We could add URLs to each anchor, but I don't see a reason for any user to click those links from their email so I think they should just be removed. 

see `app/views/layouts/mailer.html.erb`

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/121995051-f2955600-cd6b-11eb-94b9-c5de7a9c8cfa.png)
That strange id is hard coded into the view. I think someone copied and pasted HTML here

**Comment by compwron** [comment]
yep that id can go

in general I agree that the less in the email the better but maybe we do want Update Profile link... but also the less in the email, the better- less to maintain, and fewer decisions for the reader

**Comment by librod89** [comment]
There are a lot of very strange looking ids in this file that I encountered during #2148. I think we should leave the ids right now because they are still tied to styles. Unless we can import bootstrap here and use bootstrap classes instead.
