### ISSUE TITLE
Add a 404 page 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2164]
**What type(s) of user does this feature affect?**
all

**Description**
Add a 404 page 
We don't want to show our rails error page, it's unprofessional and looks bad
We have `config.public_file_server.enabled = ENV["RAILS_SERVE_STATIC_FILES"].present?` in `production.rb` but setting `RAILS_SERVE_STATIC_FILES` = true in prod did not change this behavior.
`casa/public/404.html` already exists but should look more CASA ish. Keep it simple- no images if possible, just our signature colors
We are deployed on heroku, we don't have apache or nginx that we know of. 

**Screenshots of current behavior, if any**  
![Screen Shot 2021-06-16 at 8 11 12 PM](https://user-images.githubusercontent.com/578159/122325243-1200c000-cedf-11eb-8a40-13a8ced5e903.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by efgalvao** [comment]
Can I get this one ?

**Comment by efgalvao** [comment]
What do you think about this ?

![Screenshot from 2021-06-18 08-36-16](https://user-images.githubusercontent.com/61836657/122555242-6a83aa80-d010-11eb-8f4a-fcbf1235290b.png)

Can I create a separate file for the css stylesheet ?
