### ISSUE TITLE
Update cypress test for generating court report

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2188]
### Current Behavior
2 selects are rendered for admins and supervisors
![image](https://user-images.githubusercontent.com/8918762/123193721-e778af00-d46a-11eb-8217-6ed6df606b82.png)
![image](https://user-images.githubusercontent.com/8918762/123193783-fe1f0600-d46a-11eb-9945-cde0c1f0b6dd.png)

The test selects an option from the old `<select>` which is now inaccessible on the page

### Expected Behavior
the select that is a `<ul>` should be used instead  
see `cypress/integration/volunteer/generate_court_report.spec.js`

### How to Replicate
ex: 
1. - Log into staging as an admin or supervisor.
2. - Click on "Generate Reports" in the left sidebar menu.
3. - open the element inspector to see both selects (`#case-selection` is the unused select)

see https://github.com/rubyforgood/casa/wiki/Helpful-Commands for help running cypress tests

**Comment by librod89** [comment]
The second select is generated programmatically by [select2](https://select2.org/getting-started/basic-usage) because of the search box in the dropdown list. I think this is required.

**Comment by FireLemons** [comment]
@librod89 thanks, I see now that it's required. I'm limiting the issue to just updating the cypress test now.
