### ISSUE TITLE
Update text for deactivated volunteer email

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#22]
Part of epic #3 

**What type of user is it for? [volunteer/supervisor/admin/all**
volunteers

**New email text**
https://github.com/rubyforgood/casa/blob/master/app/views/volunteer_mailer/deactivation.html.erb

Subject: Your account has been deactivated

Hello [volunteer display name],

Your CASA/Prince George’s County volunteer console account has been deactivated. Should you resume service as a CASA volunteer in the future, your account will be reactivated. Thank you for your service to CASA!

If you have any questions, please contact your most recent Case Supervisor for assistance.

– CASA/Prince George’s County

**Related issues**
#125, #23

**Comment by compwron** [comment]
Let's not dig into this for a while; we can get by without sending email for a while past MVP

**Comment by Zrrrpy** [comment]
copy updated with revisions from PG CASA

**Comment by compwron** [comment]
this is done- see https://github.com/rubyforgood/casa/blob/master/app/views/volunteer_mailer/deactivation.html.erb

**Comment by compwron** [comment]
@alindeman Hey just checking in, this is marked as "in progress" how is it going? If you want to pair program we're on zoom today 1-230pm pacific time, and I'm happy to hang out other times too. You can join us in ruby4good slack at #casa https://rubyforgood.herokuapp.com/

**Comment by alindeman** [comment]
Sorry about this. I will have limited access to a computer for the next
week or so. If it's needed sooner, feel free to unassign me. Otherwise I
think I can pick it up when I get back :)

**Comment by compwron** [comment]
@alindeman No worries! I will leave it assigned to you and check in next Sunday. 💖
