### ISSUE TITLE
Refactor css out of style tag into inline styles for app/views/layouts/mailer.html.erb

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2223]
**Description**
`app/views/layouts/mailer.html.erb` is included in most email views so the css in `style` may affect elements in other mail views
see https://github.com/rubyforgood/casa/commit/923796a9c4695a443ff208efd44664856816b207 (the commit where the style tag was added)
Move the css out of the `<style>` tag and into email friendly inline css

**Comment by efgalvao** [comment]
Media queries need to be included within a style block so, just part of the style tag can be moved to the inline.
