### ISSUE TITLE
Supervisor cannot download report for case without assigned volunteer 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2226]
### Impacted User Types
admins and supervisors

### Environment
staging

### Current Behavior
<img width="900" alt="Screen Shot 2021-07-02 at 6 09 35 PM" src="https://user-images.githubusercontent.com/578159/124339135-11179180-db61-11eb-8773-11e189b4be82.png">

**Comment by josearmandojacq** [comment]
I'm working on it 🙏🏽
