### ISSUE TITLE
Ability to exclude columns from data exporter

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2227]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Allow users to exclude columns when exporting data

see `app/models/case_contact_report.rb`

**Screenshots of current behavior**  
![image](https://user-images.githubusercontent.com/8918762/124343798-09bdab80-db94-11eb-8a9b-0b757c2ac4e9.png)

_QA Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
Click "Export Data" in the sidebar

Login Emails: 
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by tomoharutsutsumi** [comment]
@FireLemons 
Hi, my name is Tomoharu Tsutsumi. I have a question on this issue. You want columns to be left out of only the output, or left out of the output and the input? For example, if I want to exclude "Assigned to", I can uncheck "Assigned to" and the selection field will disappear Report Categories view? or the selection field won't disappear?

**Comment by FireLemons** [comment]
just the output @tomoharutsutsumi

**Comment by compwron** [comment]
@tomoharutsutsumi do you still want to work on this? You can assign yourself to it if you want :)

**Comment by tomoharutsutsumi** [comment]
Hi @compwron 
Anyway, I will though I have no idea how long it takes to finish up this task.

**Comment by librod89** [comment]
@tomoharutsutsumi are you still working on this?
