### ISSUE TITLE
Change export data page title

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2228]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Change the title from "Report Categories" to "Export Data"

see `config/locales/en.yml`
see `app/views/reports/index.html.erb`

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/124343866-6de06f80-db94-11eb-9e50-335e0eba38b4.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
Click "Export Data" in the sidebar

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this issue,
thanks
