### ISSUE TITLE
Add docker/build to github actions CI so we don't break it

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2236]

**Comment by librod89** [comment]
@compwron I didn't notice that you had already started a [PR](https://github.com/rubyforgood/casa/pull/2239) for this ticket. I created a GitHub action that ran successfully but it didn't run `docker/test`. Do you want it to build docker and then run tests?

https://github.com/rubyforgood/casa/pull/2320

**Comment by compwron** [comment]
All yours!

**Comment by compwron** [comment]
Yes please run the tests also
