### ISSUE TITLE
Fix past court dates view test not accounting for HTML escaped characters

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2244]
### Current Behavior

    expected "...
      <h6>
        <strong>Judge:</strong>
        Horacio O&#39;Kon MD
      </h6>
      ... " to include "Horacio O'Kon MD"

Full Stack:

    1) past_court_dates/show with court details when accessed by a casa admin behaves like a past court date with all court details displays all court details
       Failure/Error: expect(rendered).to include(past_court_date.judge.name)
  
         expected "<a href=\"/casa_cases/335/edit\">Back</a>\n\n<h1>Past Court Date</h1>\n<h2>July 7, 2021</h2>\n\n<div..." href=\"/casa_cases/335/past_court_dates/32.docx\">Download Report (.docx)</a>\n  </div>\n</div>\n" to include "Horacio O'Kon MD"
         Diff:
         @@ -1,47 +1,93 @@
         -Horacio O'Kon MD
         +<a href="/casa_cases/335/edit">Back</a>
         +
         +<h1>Past Court Date</h1>
         +<h2>July 7, 2021</h2>
         +
         +<div class="card card-container">
         +  <div class="card-body">
         +    <p>
         +      <h6><strong>Case Number:</strong> CINA-346</h6>
         +    </p>
         +    <p>
         +      <h6>
         +        <strong>Judge:</strong>
         +        Horacio O&#39;Kon MD
         +      </h6>
         +    </p>
         +    <p>
         +      <h6>
         +        <strong>Hearing Type:</strong>
         +        Emergency Hearing 367
         +      </h6>
         +    </p>
         +
         +      <p>
         +        <h6>
         +          <strong>Court Mandates:</strong>
         +        </h6>
         +      </p>
         +
         +      <div class="table-responsive">
         +        <table class="table table-hover">
         +          <thead>
         +            <th>Court Mandate Text</th>
         +            <th class="text-center">Implementation Status</th>
         +          </thead>
         +          <tbody>
         +              <tr>
         +                <td>Ut bos agnosco. Asperiores ara ascit. Est via amplitudo. Accendo desino volaticus. Audeo adeo crastinus. Toties valetudo vox. Aeneus quibusdam velit. Sol coaegresco adaugeo. Cultellus combibo triduana. Thalassinus cicuta eos. Coerceo quam viriliter. Et desolo sortitus. Succedo aut canto. Demonstro comes thema. Cetera debeo aperio. Concedo aut atrox. Tui tamisium victoria. Tergum nostrum beatae. Conqueror bellicus tamquam. Suasoria celebrer suspendo. Carbo thymum trans. Causa sol velum.</td>
         +                <td class="text-center">Partially implemented</td>
         +              </tr>
         +          </tbody>
         +        </table>
         +      </div>
         +
         +    <a class="btn btn-primary" href="/casa_cases/335/past_court_dates/32.docx">Download Report (.docx)</a>
         +  </div>
         +</div>
       Shared Example Group: "a past court date with all court details" called from ./spec/views/past_court_dates/show.html.erb_spec.rb:55
       # ./spec/views/past_court_dates/show.html.erb_spec.rb:11:in `block (3 levels) in <top (required)>'
  
    Finished in 4 minutes 40.6 seconds (files took 6.28 seconds to load)
    1265 examples, 1 failure, 2 pending
  
    Failed examples:
  
    rspec './spec/views/past_court_dates/show.html.erb_spec.rb[1:1:1:1:1]' # past_court_dates/show with court details when accessed by a casa admin behaves like a past court date with all court details displays all court details
  
    Randomized with seed 65320

### Expected Behavior
The Judge name should be HTML escaped before comparing against the view

see `./spec/views/past_court_dates/show.html.erb_spec.rb`

**Comment by jemcodes** [comment]
I ran into this bug tonight, as well, so I'll take it 👋
