### ISSUE TITLE
Use new Montgomery court report templates instead of old one

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2265]
Use new Montgomery court report templates instead of old one

The current Montgomery court report template is: https://github.com/rubyforgood/casa/blob/main/app/documents/templates/montgomery_report_template.docx

New court report templates are at: 
1. over 14 (transition aged youth) https://drive.google.com/file/d/1B89zt95qAP5pg-qHQTi05Ec_1sPjYG66/view?usp=sharing
2. under 14 (non transition aged youth) https://drive.google.com/file/d/1dJVlQ4wIoRO79sE1fwsDFYtCa-Zoy2oP/view?usp=sharing

Please merge these into the same template

Steps:
1. Edit the new files to have the correct `«=casa_case.court_date»` variables (it might be easier to start with the old file and copy over the new info into the file) Remember to show different info for transition aged youth vs not- you can use case statements or move some of the text into the codebase if that helps- keep in mind that we want to avoid writing custom code for each CASA as much as possible because it's not scalable)
1. On your local, generate a court report of each type and check that all the variables are set correctly so the dates and names display etc
1. Write even MORE tests in addition to the existing tests, since you're in here anyway. Test for edge cases like missing data and extra-long variable values. 
1. Ask in slack when you have questions! https://rubyforgood.slack.com/ `#casa` channel
1. Update https://github.com/rubyforgood/casa/wiki/Making-a-new-Court-Report-Format with your learnings on how to do this :)

see https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates

**Comment by compwron** [comment]
ping @FireLemons you know a lot about this, got any advice to share? :)

**Comment by FireLemons** [comment]
- [ ] Merge Transitioning and Non Transitioning Templates  
- [ ] Use New Template
- [ ] Auto Fill in Fields
- [ ] Autofill Tables
- [ ] Afterparty Task

**Comment by FireLemons** [comment]
In the past, if there were no mandates or contacts we would not show the section. maybe we should put something else if the volunteer had unentered mandates/contacts

**Comment by compwron** [comment]
Let's keep it simple for now and make additional tickets for additional work. I think that all cases have mandates in the real world, but sometimes they don't make it into our system- so having a place to enter them could still be useful

**Comment by FireLemons** [comment]
note to self contact.name shouldn't be part of the context because we don't have that

**Comment by FireLemons** [comment]
@compwron If I write tests for this new template, they'll only be for the Montgomery template. Should we test each template?

**Comment by FireLemons** [comment]
- [ ] Afterparty Task
- [ ] Test latest court date in court report context

**Comment by FireLemons** [comment]
Certain kinds of tests will be unmaintainable because the output of the xml is unpredictable
![image](https://user-images.githubusercontent.com/8918762/128445776-d1edcf03-53cf-47d5-ba94-b61b2f096601.png)
![image](https://user-images.githubusercontent.com/8918762/128445752-19ea6064-42ca-4c9a-bbc6-eaa6911abb80.png)
