### ISSUE TITLE
Set Email Invitation Expiration Time To Two Weeks for Supervisors and Admins

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2278]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
A pull request for each of these steps would be great

 - [x] Set the expiration date of the invite token to 2 weeks 
 - Write a test checking that the token expires
 - [x] In the account setup email, warn that the link only works for two weeks
 - Write or modify a test checking that the warning displays the correct date

see https://github.com/scambra/devise_invitable#model-configuration-
> `invite_for`: The period the generated invitation token is valid. After this period, the invited resource won't be able to accept the invitation. When `invite_for` is `0` (the default), the invitation won't expire.

see `app/views/casa_admin_mailer/account_setup.html.erb`
see `app/views/supervisor_mailer/account_setup.html.erb `

**Comment by librod89** [comment]
@FireLemons there is no invitation link in the account setup email. Did you mean the invitation instructions email?

**Comment by FireLemons** [comment]
@librod89 yes, the one with the invite link
