### ISSUE TITLE
Set Email Invitation Expiration Time To A Week for All Casa Admins

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2279]
**What type(s) of user does this feature affect?**
 - all casa admins

**Description**
A pull request for each of these steps would be great

 - [x] Set the expiration date of the invite token to a week 
 - Write a test checking that the token expires
 - [x] In the account setup email, warn that the link only works for a week
 - Write or modify a test checking that the warning displays the correct date

see https://github.com/scambra/devise_invitable#model-configuration-
> `invite_for`: The period the generated invitation token is valid. After this period, the invited resource won't be able to accept the invitation. When `invite_for` is `0` (the default), the invitation won't expire.

**Comment by efgalvao** [comment]
Later I will do the other task, in another pr.
