### ISSUE TITLE
Make archived case contacts more obvious.

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2286]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Screenshot of current behavior:**  
![image](https://user-images.githubusercontent.com/8918762/126021299-788018b9-9b5d-41fb-94c6-b8fb25cbf75c.png)

**Description**
![image](https://user-images.githubusercontent.com/8918762/126021609-a8981a9d-0f58-460a-9d9f-f70d6411fd90.png)
If a case contact has been archived,
 - Make the title gray
 - append "(Archived)" to the title
 - move the tooltip icon to the end of the title
 - Change the tooltip text to "Archived contacts can't be edited. Case contacts are archived after the end of each quarter."

see `app/views/case_contacts/_case_contact.html.erb`

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by rhian-cs** [comment]
Hello, may I work on this issue?

**Comment by compwron** [comment]
Yep, go for it! :)
