### ISSUE TITLE
Email String Validation

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2287]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins
 - all casa admins

**Description**

for forms requiring email,
 - validate that the string input is an email address
 -  show an error if the email is invalid
 - write a test for each form
see `URI::MailTo::EMAIL_REGEXP`

**Comment by rhian-cs** [comment]
@FireLemons may I give this one a try?

By the way, what if we use the [email_address](https://github.com/afair/email_address) gem? It also validates the hostname, but that is optional.

**Comment by compwron** [comment]
@rhian-cs @FireLemons let's not bring in more gems if we don't need to, that one looks ok in general but not hugely used, and most importantly, every gem is a maintenance burden on us as maintainers. Rails has an email validator. 
`email =~ Devise.email_regexp`
https://stackoverflow.com/questions/38611405/email-validation-in-ruby-on-rails

**Comment by compwron** [comment]
+1 to URI::MailTo::EMAIL_REGEXP

**Comment by rhian-cs** [comment]
@FireLemons I've taken a look at the present validations, they seem to be working fine (in some of them adding the regexp may be redundant).

I've tested in:
- the rails console
- when logging in
- when adding a new supervisor

Is there a specific page where you see this validation missing?

**Comment by FireLemons** [comment]
@rhian-cs I looked into this more and I think I made an invalid issue by mistake. We had a support ticket where an email was erroneously entered and ending in a period and I assumed that was an invalid format.
