### ISSUE TITLE
Make case assignment inactive when volunteer becomes inactive

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#230]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer/admin

**Description**
After an admin marks a volunteer as inactive, the case assigned to the volunteer should now show as not assigned to any volunteer (keep the case_assignment record but mark it inactive)

**Relates to issues**
#228, #237, #22

**Comment by compwron** [comment]
note: We discussed adding a separate "Mark inactive" button and that sounds great

**Comment by maebeale** [comment]
prob a separate ticket, but:
from `casa_cases` `edit`, do we def want to `destroy` the case_assignment ?
(wouldn't we want to retain record of a prior assignment? like, maybe there are two buttons there -- `unassign` and `delete`?)

**Comment by compwron** [comment]
We never want to destroy the case_assignment, that is a bug.

**Comment by maebeale** [comment]
do `supervisor` and `casa_admin` ever function as volunteers?

**Comment by maebeale** [comment]
are volunteers ever reinstated?

**Comment by compwron** [comment]
supervisor and casa_admin never function as volunteers for our purposes.
we are not currently planning for volunteers to be reinstated.
