### ISSUE TITLE
Limit volunteer mailer previews to only volunteers

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2311]
**Description**
Volunteer email previews can be passed an `id` get parameter with a user id.
Currently volunteer email previews shows the preview even if the user id passed doesn't refer to a volunteer.
Limit them to only work for volunteers.  
Write a test

see `lib/mailers/previews/volunteer_mailer_preview.rb`

_QA Details:_  
[Link to QA volunteer email previews](https://casa-qa.herokuapp.com/rails/mailers/volunteer_mailer)

**Comment by compwron** [comment]
Does this mean that only users logged in as volunteers can see the email previews (seems strange to me) or that the email previews only show user data of volunteers (also kinda weird but less so)

**Comment by FireLemons** [comment]
These 4 work for every type of user
![image](https://user-images.githubusercontent.com/8918762/127797433-832f867a-6901-4090-9dfc-5ebc10c577b8.png)

**Comment by FireLemons** [comment]
I think they should only show a preview if the user is actually a volunteer
