### ISSUE TITLE
Parameters for Devise Invitation Instructions Email Preview

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2315]
**Description**
 - refactor `invitation_instructions_as_all_casa_admin`, `invitation_instructions_as_casa_admin`, `invitation_instructions_as_supervisor`, and `invitation_instructions_as_volunteer` into a single `invitation_preview` method
 - add the ability to select which user's email to preview via user id

see `lib/mailers/previews/devise_mailer_preview.rb`

**Comment by compwron** [comment]
this is not doable by people other than you, what does this mean :)

**Comment by compwron** [comment]
This does not seem to add value, closing for now
