### ISSUE TITLE
Show thank you message to volunteer after case contact is saved

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2326]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors (if they write a case contact)
 - admins (if they write a case contact)

**Description**
Show thank you message to volunteer after case contact is saved
Because they will like it a lot
And the supervisors will also like it a lot

Text of thank you message should vary between these messages (randomly is fine)
1. ✨ 💖  Thank you for your work! CASA and the youth appreciate you :)
2. ✨ 💖  Thanks for all you do! 
3. ✨ 💖  Thank you for your time and patience
4. ✨ 💖  We couldn't do it without you! Thank you for doing this :)
5. ✨ 💖  Thank you for enabling judges to make the most well-informed decision for each child. 
Note: the above texts are provisional- email sent to stakeholders for feedback on 28 July 2021

SB
> Maybe we could do a short “Thank you!” with a rotation of meaningful volunteer quotes underneath. That way the volunteers who enter a lot of data wouldn’t start tuning it out because they’d be curious to read what the new pop up quote is.
> “One of the greatest gifts you can give is your time”
> “Those who can do, do. Those who can do more, volunteer”
> “Volunteers do not necessarily have the time, they just have the heart”
> Etc. etc. etc.

FD

> We love it, too!  I think maybe short ones, with an occasional quote underneath.  Some people might find it annoying to have a long pop-up every time.  Here are a few from my peeps :)
> Thanks for all you do!
> Thank you for your hard work!
> Thank you for a job well done!
> Thank you for volunteering!
> Thanks for being a great volunteer!

**Screenshots of current behavior, if any**  
![thanks](https://user-images.githubusercontent.com/578159/127417195-f737078f-49ca-41e0-8222-e39b682dd5ae.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by jpletner** [comment]
Hi Everyone, I want to start contributing to Casa and I'd like to start with this issue if that is ok.

**Comment by compwron** [comment]
@jpletner Welcome!! We are very happy to have you. Go for it! :)

**Comment by jpletner** [comment]
Good Evening, 

I'd like to ensure that I implement the desired requirements. Should I be following the suggestion from the latest stakeholder feedback (see below)? Currently, I have the thank you messages suggested in the below comment implemented without an `occasional quote underneath`. 

`We love it, too! I think maybe short ones, with an occasional quote underneath. Some people might find it annoying to have a long pop-up every time. Here are a few from my peeps :)

- Thanks for all you do!
- Thank you for your hard work!
- Thank you for a job well done!
- Thank you for volunteering!
- Thanks for being a great volunteer!
`

**Comment by compwron** [comment]
Let's start with this list and we can add more when we think of them. :) 

One of the greatest gifts you can give is your time
Those who can do, do. Those who can do more, volunteer
Volunteers do not necessarily have the time, they just have the heart
Thanks for all you do!
Thank you for your hard work!
Thank you for a job well done!
Thank you for volunteering!
Thanks for being a great volunteer!

**Comment by compwron** [comment]
@jpletner How is it going? :)

**Comment by compwron** [comment]
I see the branch, very cool :) https://github.com/rubyforgood/casa/compare/main...jpletner:thank-you-message-2326
PR soon? :)
