### ISSUE TITLE
Change court report select text transitioning to be calculated from birthdate

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2343]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
all

### Current Behavior
Casa cases where the birthdate occurred more than 14 years ago may not be marked as transitioning
As an admin, https://casa-qa.herokuapp.com/case_court_reports will take you to the relevant page.
![Transition Aged Incorrectly Labelled](https://user-images.githubusercontent.com/7007647/137834039-a2d074fa-35d9-4727-96aa-7785e676fc69.png)

### Expected Behavior
Casa cases where the birthdate occurred more than 14 years ago should be marked as transitioning

see `app/decorators/casa_case_decorator.rb`

**Comment by stufro** [comment]
Can I pick this one up?

**Comment by codewithjulie** [comment]
@stufro yes!

**Comment by compwron** [comment]
the stakeholders (Andrea from PG) asked about this again today

**Comment by carolyn-manning** [comment]
I have this updated for the text shown in the screenshot in the ticket. I'll submit a PR shortly. Still working on cleaning up the rest of the codebase so only the birthday will be used.
