### ISSUE TITLE
Look into weird montgomery -1 accepted

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2345]
Look into weird montrgomery -1 accepted

<img width="579" alt="Screen Shot 2021-08-01 at 3 41 52 PM" src="https://user-images.githubusercontent.com/578159/127787439-a361500b-de31-4296-9194-dbfeedb67604.png">

**Comment by FireLemons** [comment]
related?
![image](https://user-images.githubusercontent.com/8918762/127931632-3646c4ac-fbd2-49ec-bdec-5b5c1916cda2.png)

**Comment by FireLemons** [comment]
I hope no one was deleted
![image](https://user-images.githubusercontent.com/8918762/127932756-37fdf1d9-5579-49fe-8730-5ecee8e899f5.png)
