### ISSUE TITLE
Duplicate case numbers in Assign a New Case dropdown

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2346]
### Impacted User Types
 - supervisors
 - admins

### Environment
QA
https://casa-qa.herokuapp.com/volunteers/1898/edit
<img width="1289" alt="dupes" src="https://user-images.githubusercontent.com/578159/127788478-42c2aa25-af87-4802-ad64-573418b6b271.png">

### Current Behavior
Duplicate case numbers in Assign a New Case dropdown
and search for them is not working
write tests!!!!!!

**Comment by Beigelman** [comment]
Starting to work on this issue. @compwron could you assign it to me?

**Comment by compwron** [comment]
Closing - can't replicate
