### ISSUE TITLE
Admin cannot change password

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2352]
### Impacted User Types
 - admins

### Environment
Production 

### Current Behavior
When attempting to change a password, the password change fails and an error screen is shown.
![Updating password](https://user-images.githubusercontent.com/7007647/127947250-04eebf67-67e0-4c60-98a8-2eb62ddda3de.png)

### Expected Behavior
When I attempt to change my password it should change my password.

### How to Replicate

1. - Log in as an admin.
2. - Click on "Edit Profile" in the left sidebar menu.
3. - Click the "Change Password" button at the bottom of the page.
4. - Enter the existing password and new password into the appropriate textboxes.
5. - Click the "Update Password" button at the bottom of the page.
![Screen Shot 2021-08-02 at 7 43 39 PM](https://user-images.githubusercontent.com/578159/127949344-342c233a-7e73-445f-9ea8-8387a3f28997.png)

```
Aug 02 19:13:08 casa-production app/web.1 I, [2021-08-03T02:13:08.758412 #4]  INFO -- [Bugsnag]: [43526069-b404-4790-8f84-3281cc057d7a] Notifying https://notify.bugsnag.com of NoMethodError
Aug 02 19:13:08 casa-production app/web.1 F, [2021-08-03T02:13:08.762047 #4] FATAL -- : [43526069-b404-4790-8f84-3281cc057d7a]   
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] ActionView::Template::Error (undefined method `length' for nil:NilClass):
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     27:         </button>
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     28: 
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     29:         <% if policy(CasaAdmin).see_deactivate_option? %>
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     30:           <% if @active_casa_admins.length > 1 %>
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     31:             <%= link_to "Deactivate",
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     32:                         deactivate_casa_admin_path(current_user),
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     33:                         method: :patch,
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]   
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] app/views/users/edit.html.erb:30
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] app/views/users/edit.html.erb:5
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] app/controllers/users_controller.rb:32:in `update_password'
```

**Comment by efgalvao** [comment]
The password change function is working, but I think we should change the labels from "Password" and "Password confirmation" to "New Password" and "New Password Confirmation".
That error is because the new password does not match, I have fixed that and now shows a flash notice saying "Password not updated".
@compwron  What you think about updating the labels ?
