### ISSUE TITLE
Unexpected Gap in Pick Displayed Columns Pop Up

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2354]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
There is a gap in between Supervisor and Status in the Pick Displayed Columns pop up. Also, it would be nice to alphabetize the options on the Pick Displayed Columns pop up. 

**Screenshots of current behavior, if any**  
![Unexpected Gap](https://user-images.githubusercontent.com/7007647/127951203-0a00f5ce-7542-433f-b44f-162d6904daa6.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/127952124-e44bf653-0bf6-44e3-83c7-0835888c2431.png)

**Comment by karansapolia** [comment]
I'd like to work on this.

**Comment by sstacey** [comment]
Can you assign this to me?  Thanks!
