### ISSUE TITLE
Download Case Contacts As An Excel File Rather Than A CSV

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2356]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when downloading case contacts, they download as a CSV which when opened in excel does not automatically size columns correctly for human readability. If it downloaded as an Excel File it could be made to size columns correctly for human readability. 

**Screenshots of current behavior, if any**  
Current Downloads look like this:
![Excel results](https://user-images.githubusercontent.com/7007647/127952244-aef6df87-0a78-46a9-a70b-1432e64512cc.png)
The place where the download is pulled from is here:
![Excel Download Point](https://user-images.githubusercontent.com/7007647/127952299-1d47fbe0-34a7-4118-9728-d68d36de346e.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by RomanTurner** [comment]
Found a resource on how to implement that download as an excel file. 
Would adding the gem and formatting the download be the way to go?

Blog- https://medium.com/@JasonCodes/ruby-on-rails-exporting-data-to-excel-b3b204281085
Docs on the gem- https://github.com/caxlsx/caxlsx_rails

**Comment by sstacey** [comment]
Please assign this to me.  I'll attempt it.  :)

**Comment by sstacey** [comment]
Should I remove the old CSV way, or leave it?

**Comment by compwron** [comment]
All yours! Leave it for now :)
