### ISSUE TITLE
Write tests to verify that html tags are closed in all email templates

### ISSUE THREAD

**Issue by aedwardg** [rubyforgood/casa#2373]
HTML in emails is much more sensitive in emails than on a normal page, as we discovered with the unclosed `<style>` tags recently (see #2273)

My proposal for how to test this was discussed last Wednesday at office hours, just writing this issue up so I don't forget to do it.  Should reduce repeated code in these tests by using rspec `shared_example` magic 🧙

**Comment by FireLemons** [comment]
maybe you can configure erblint to check for this

**Comment by aedwardg** [comment]
Good idea, I'll look into that as well.  That would definitely be the better option if it's possible.

**Comment by aedwardg** [comment]
Hello bot, please don't unassign me. Just having a busy week 😄

**Comment by compwron** [comment]
https://github.com/Shopify/erb-lint

**Comment by FireLemons** [comment]
https://github.com/rubyforgood/casa/pull/2593/checks?check_run_id=3616679056

**Comment by aedwardg** [comment]
@FireLemons what's that?

**Comment by FireLemons** [comment]
erb lint is a collection of linters maybe one of them checks for closed tags

**Comment by FireLemons** [comment]
oh that's the wrong link

**Comment by FireLemons** [comment]
maybe the one called `ClosingErbTagIndent` will get it

**Comment by aedwardg** [comment]
Hey @FireLemons,
I looked into `ClosingErbTagIndent` and the other erblint options, but it looks like none of them will check for this.  Looking at the source code, it appears the only look for the erb tags (e.g., `<%%>`) but not regular html tags.  I think I'll stick with the regex + `shared_example` solution I discussed with Linda last month, but I probably won't get around to it this week.
