### ISSUE TITLE
rbenv Does Not Like Formatting of .ruby-version

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2379]
**Description**
Currently the formatting of .ruby-version is `ruby-3.0.1` and rbenv expects `3.0.1` 

Note: Before merging check against both rbenv and rvm to make sure they both interpret the value correctly.

**Existing gem(s), file(s) needing updating, changing or deleting**
.ruby-version needs updating

**Comment by FireLemons** [comment]
I think this is fine
![image](https://user-images.githubusercontent.com/8918762/133491932-c599f654-294b-46a5-a0ed-688687f17901.png)
