### ISSUE TITLE
Change Mileage Report Filenames to have Human Readable Datestamps

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2380]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Mileage reports currently generate with the unix time the report was generated in the filename (for example: `mileage-report-1628475178.csv`), we want to change this to a human readable datetime stamp (i.e.  `mileage-report-2021-07-23`). This date should be based on the timezone of the browser (not UTC).  `Time.zone.local`

**Screenshots of current behavior, if any**  
<img width="261" alt="Screen Shot 2021-08-06 at 5 24 35 PM" src="https://user-images.githubusercontent.com/7007647/128656228-94c2edb7-117b-40f6-bd72-8cae9413e673.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by josearmandojacq** [comment]
In a previous PR, I used `Time.now.strftime("%Y-%m-%d")` to get the date. Is OK to use it here again?

**Comment by m-pereira** [comment]
> @CovenantHuman In a previous PR, I used `Time.now.strftime("%Y-%m-%d")` to get the date. Is OK to use it here again?

I think `Time.current` is better, the `current` method, tries to get the zone first. 

https://apidock.com/rails/v5.2.3/Time/current/class

**Comment by AravindSelvamani** [comment]
I would like to work on this issue. Kindly assign the issue and provide me write access @m-pereira @CovenantHuman
