### ISSUE TITLE
Make Download All Case Contacts CSV Filename Prettier

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2382]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently the download all case contacts csv's have filenames that are less useful for the people working with them (i.e. `volunteer-1953-case-contacts-1628558253.csv`). We would like the filenames to instead have the format case number - case - contacts - human readable date (i.e. `CINA-07-1152-case-contacts-2021-07-23.csv`)

**Screenshots of current behavior, if any**  
![Volunteer case contacts filename](https://user-images.githubusercontent.com/7007647/128794291-4386b7d1-88d6-4aa3-aa39-2419e2f51e17.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by josearmandojacq** [comment]
Im gonna work on it 😄

**Comment by josearmandojacq** [comment]
Hey @compwron is this .csv the one created when exporting data?

**Comment by compwron** [comment]
@josearmandojacq no this is the one from the Download All button from the case page
