### ISSUE TITLE
Add Explanatory Text When There is No Data for Sections of Supervisor E-mail

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2387]
**What type(s) of user does this feature affect?**
 - supervisors
 
**Description**
Currently, when the supervisor receives their weekly e-mail it contains sections for Additional Notes and Pending Volunteers which can be empty. We would like for these sections to, if they do not contain other data, display the messages "There are no additional notes." and "There are no pending volunteers." respectively. 

**Screenshots of current behavior, if any**  
![Supervisor Email](https://user-images.githubusercontent.com/7007647/128799804-37f51883-43e4-4a9e-8708-d0beb5f7e334.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by colefortner** [comment]
I would like to work on this one -Cole

**Comment by FireLemons** [comment]
@colefortner are you familiar with database diagrams?

**Comment by FireLemons** [comment]
@colefortner we have this [database diagram](https://github.com/rubyforgood/casa/wiki/Database-diagram)

**Comment by colefortner** [comment]
Awesome, thank you!
