### ISSUE TITLE
Admin Active Status Text Not Displaying Properly

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2411]
### Impacted User Types
 - admins

### Environment
Production 

### Current Behavior
When an admin is active, the words "Active Text" appear next to the admins active state:
<img src="https://user-images.githubusercontent.com/7007647/129629600-c6f8ec83-3388-44af-a486-352baab39a5d.PNG" width="400" alt="Active Text Screenshot">

When an admin is deactivated the words "Deactive Text" appear next to the date that the admin was deactivated:
<img width="407" alt="Screen Shot 2021-08-13 at 6 56 18 PM" src="https://user-images.githubusercontent.com/7007647/129629622-b0acfaeb-1d23-4e50-9ebd-4e4f95ade541.png">

### Expected Behavior
Instead of "Active Text: the words "Admin is" should appear. Instead of "Deactive Text" the words "Admin was deactivated on" should appear

### How to Replicate
ex: 
1. - Log into qa as an admin.
2. - Click on "Admins" in the left sidebar menu.
3. - Select "Edit" next to one of the Admins.
4. - The "Active Text" will appear at the bottom of the page above the submit button.

**Comment by josearmandojacq** [comment]
I'm going to work on it
