### ISSUE TITLE
Clarify Password Change Failure Message 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2412]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a user's password change fails due to the new password not complying with the minimum length requirement a message is shown that states "1 error prohibited this (Volunteer/Casa admin/Supervisor) from being saved: " and then the reason listed below in a bullet point. 

Regardless of who is trying to change their password, if the password change fails the text should read "1 (or whatever the appropriate number of errors is) error(s) prohibited this password change from being saved: " and then the reason or reasons listed below in a bulleted list. 

**Screenshots of current behavior, if any**  
![Error message unclear](https://user-images.githubusercontent.com/7007647/129632050-967a341d-c4cc-4bd4-8ccb-569c719c65e1.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by AravindSelvamani** [comment]
I would like to work on this issue. Kindly assign the issue and provide me write access @FireLemons @CovenantHuman
