### ISSUE TITLE
Add Colored Bars to Supervisor's Screen 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2415]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
We would like to add colored bars to the chart that tells supervisors about their volunteers. These bars would be black rectangles filled with green to the appropriate percentage to represent how many of each supervisor's volunteers had made contact in the last fourteen days and red in the appropriate percent to represent the volunteers that haven't made case contacts in the last fourteen days. The number of transition aged youth would appear at the end of the bar in parenthesis. Above the top of the list of supervisor's there should be an explanatory version of the bar that's fifty-fifty and has "Have made contact in the last 14 days" in the green section, and "Have not made contact in the last fourteen days" in the red section. Beside this example bar should be "(Transition aged youth)" in black to match the styling of the bars for individual supervisors. 

**Screenshots of current behavior, if any**  
![Supervisor Visual Tracking Bar](https://user-images.githubusercontent.com/7007647/129654616-66d48ad6-1191-45ae-a60b-edb1d634cdcd.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by jesselasalle** [comment]
I'm down to tackle this, but have a few questions when anyone has some time. I'm in the slack, so feel free to ping me there, or drop a mention for me here :)

**Comment by compwron** [comment]
I pinged you in slack :)
We also have team office hours every Wednesday 6-8pm pacific time - the link posts in zoom. :)
