### ISSUE TITLE
Put Case Number and CASA Org in Case URLs

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2416]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
We would like to make it so that links to cases have the case number in the url. In addition, because multiple casa might have the same case number, we would like to add a short identifier based on the name of the casa to the url as well. An example of what a new url using this system would look like is `https://localhost:3000/casa_org/prince-george/casa_cases/CINA-10-1234`
The casa org saved identifier should not change even if the name of the casa org changes. 

Consider using the [FriendlyId gem](https://github.com/norman/friendly_id).

**Screenshots of current behavior, if any**  
![Casa case URL](https://user-images.githubusercontent.com/7007647/129655117-b4a8fef9-af25-48f5-b85d-605f7e5873e5.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by compwron** [comment]
This issue is available for work!
