### ISSUE TITLE
Preserve Case Contact Notes Even if Webform Times Out

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2417]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
We would like to make it so that even if the webform times out all notes on a case contact in progress are saved. 

 - When a user fills out text inputs auto save the fields to localstorage
 - Fill in the fields with saved data after page load
 - clear the saved data after a submit button has been pressed (could be redesigned around whether the submit was successful)

**Screenshots of current behavior, if any**  
![Notes Field](https://user-images.githubusercontent.com/7007647/129655998-3a350c0d-8309-47e9-8121-6523874d3d2c.PNG)
 
Technical Note: Maybe use local storage? 

We want this because it is currently causing users distress. 

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by FireLemons** [comment]
@littleforest @amygurski It will help to put all your logic in a module so later it can be imported in a jest test. 
See https://github.com/rubyforgood/casa/blob/main/app/javascript/src/async_notifier.js (example module)
See https://github.com/rubyforgood/casa/blob/main/app/javascript/__tests__/notifier.test.js (example tests)
