### ISSUE TITLE
Make Case Number A Clickable Link on Past Court Dates

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2418]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
We would like it if when a past court date is created the case number is a clickable link to the case. So in the case of the screenshot below "CINA-01-1110" would be a clickable link back to that case. 

**Screenshots of current behavior, if any**  
![Past Court Date Clickable Case Number](https://user-images.githubusercontent.com/7007647/129656623-84e117b7-a5bf-4bad-9c66-c39ee27433d6.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by josearmandojacq** [comment]
I'm going to work on this
