### ISSUE TITLE
Supervisor can log out

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#242]
Part of epic #105

**What type of user is this for? [volunteers/admin/supervisor]**
Supervisor

**Where does/should this occur?**
In the upper right hand corner of the static header which displays on every page in the Supervisor dashboard (which doesn't exist yet, but is ready to!).

**Description**
Supervisor should be able to log out by pressing a button in the location described above. Logged out screen should look the same for supervisors as it does for other user roles.

**Screenshots**
Should look like this.
<img width="1373" alt="log out" src="https://user-images.githubusercontent.com/62810851/81514466-1d4ce980-92e4-11ea-8938-76a0ca81e681.png">

**Relates to issues**
#30

**Comment by armahillo** [comment]
This feature appears to be implemented already
