### ISSUE TITLE
Supervisor can view all case contacts

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#243]
Part of epic #105

**What type of user is this for? [volunteer/supervisor/admin]**
Supervisor

**Where does/should this occur?**
<a href="https://casa-r4g-staging.herokuapp.com/casa_cases/68">In CASA Case Details</a>

**Description**
Supervisors should be able to view all `case_contacts` associated with a `casa_case` _including_ `case_contacts` from previous volunteer assignments. `case_contacts` should display in order of date in which they occurred.

**Screenshots**
<img width="1372" alt="CASA case_contacts" src="https://user-images.githubusercontent.com/62810851/81514658-2c806700-92e5-11ea-915b-5b5485e514a2.png">

**Relates to issues**
#30, #239

**Comment by armahillo** [comment]
Hi! I'm grabbing this. :) 

Can you either add me to the repo and assign it to me (I'm in RfG already, diaper project) or mark it as claimed? Thank you!

**Comment by armahillo** [comment]
A couple questions I'm trying to sort out: 

> Supervisors should be able to view all case_contacts associated with a casa_case 

 1. How does this differ from normal? I see in the `casa_cases#show` view that it's already iterating through `case_contacts` and displaying them. 

> including case_contacts from previous volunteer assignments. 

 2. Is this currently constrained? As far as I can tell, `case_assignment` and `case_contact` are independent of one another, though they both associate with `casa_case`.

Could you specify what the work difference is, here? I'm not completely clear what I'm adding beyond what already exists.

**Comment by colinsoleim** [comment]
For 1, you're correct. It looks like the supervisor role already works fine for this particular view/pundit policy. 

For 2, I think there's a plan to make changes with case assignments with this issue https://github.com/rubyforgood/casa/issues/230, but at the moment there is nothing that needs to be done. 

I'm not sure if this issue can be closed or not, I'll check with the admins. In the meantime, these two issues (https://github.com/rubyforgood/casa/issues/241, https://github.com/rubyforgood/casa/issues/240) relate to the supervisor role have clear behavior that needs to be changed. Thanks for your help, excited to have you on the project :)

**Comment by colinsoleim** [comment]
It looks like we're going to keep the current data relationship where `casa_case.case_contacts` returns both active and inactive case_contacts. I'm going to close this issue because as @armahillo pointed out everything with this issue is currently working.
