### ISSUE TITLE
Make Miles Driven Field Empty When Clicked On

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2433]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently the Miles Driven field in a new Case Contact is set to zero by default. This is good. However, when someone clicks into the Miles Driven field the zero does not currently disappear to make way for the new data, so the data ends up looking like the second screenshot below. We would like the zero to disappear when the Miles Driven field is clicked into so that the field is empty for the new data.

**Screenshots of current behavior, if any**  
![Miles Driven](https://user-images.githubusercontent.com/7007647/130002797-860abfeb-bd8d-41bf-b191-faf39d19b5e2.PNG)
![Miles Driven With Data](https://user-images.githubusercontent.com/7007647/130003088-149d752a-51a4-434e-b4a2-0c9aa41959a2.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by AravindSelvamani** [comment]
I would like to work on this issue. Kindly assign the issue and provide me write access @CovenantHuman @FireLemons @compwron

**Comment by FireLemons** [comment]
That field doesn't need a default value of 0. The placeholder is enough

**Comment by trevor-jameson** [comment]
Hey @FireLemons , I'm up to take this one if you haven't started already.
