### ISSUE TITLE
Create A Timeout Warning Before Users Are Automatically Logged Off

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2437]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a user leaves a window open without activity for an extended period of time there is no indication telling the user that they have been logged off behind the scenes until they refresh the page. This leads to users losing data when they try to save data on a page that they're actually logged out of. We would like a pop up that warns users when they are about to be automatically logged out two minutes before it happens. Ideally this pop-up would say something like "Warning: You are going to be logged out due to inactivity in two minutes. Please save or make a copy of your work now, to avoid loss.".

Check out https://medium.com/codex/user-session-inactivity-timeout-with-rails-and-devise-7269ac3a8213 for a head start

**Screenshots of current behavior, if any**  
Before a Refresh:
![Before Refresh](https://user-images.githubusercontent.com/7007647/130142140-bc06f9a1-c817-4c36-9afb-baebd3a8bc3b.PNG)

After A Refresh: 
![After Refresh](https://user-images.githubusercontent.com/7007647/130142158-59053fca-3d82-4e2b-8f2f-1c303b81bf76.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by tanja-dev** [comment]
No problem! 🙂

**Comment by compwron** [comment]
@tanja-dev are you working on this? :)

**Comment by tanja-dev** [comment]
No, I am sorry, I am not.

**Comment by compwron** [comment]
No worries :)

**Comment by JelenaD1** [comment]
Hello, I am going to take over and work on this issue.

**Comment by ThomasNathan** [comment]
@dpaola2 Can I claim this one?

**Comment by ThomasNathan** [comment]
Waiting for a PR review
