### ISSUE TITLE
Move Unassigned Volunteers to the Top of the Assign A New Volunteer Dropdown

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2438]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently when editing a case to add a volunteer, all the volunteers in the system show up in alphabetical order in the Assign A New Volunteer dropdown under Manage Volunteers. We would like currently unassigned volunteers to appear at the top of the list in alphabetical order under the label Not Assigned, with volunteers who are already assigned to at least one case appearing in alphabetical order below under the label Assigned. The drop down should remain searchable on volunteer name. 

**Screenshots of current behavior, if any**  
![Volunteers Not Sorted](https://user-images.githubusercontent.com/7007647/130143594-31fc27dc-18b7-43f7-902c-23427e1ee9c0.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by jpletner** [comment]
I'll take this one
