### ISSUE TITLE
Remove disable_bullet as many places as possible

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2441]
**Description**
 Remove as many as possible `disable_bullet`s. 

You don't need to remove them all, just remove some and tell us how many so we can celebrate with you!

Example:
`RSpec.describe "/all_casa_admins", :disable_bullet, type: :request do`

**Existing gem(s), file(s) needing updating, changing or deleting**
Many
**New file(s) needing creating**
None

**Comment by malini2** [comment]
@CovenantHuman Attempted to help on this issue. Please review!

**Comment by littleforest** [comment]
Not seeing any more bullet issues.
