### ISSUE TITLE
Add New Metric to Metrics Summary

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2462]
**Description**
We would like to add this metric https://data.heroku.com/dataclips/kltzsxjtbjggdjqjcliqgrvbkped to this https://firelemons.github.io/casaMetricsComparison/

**Existing gem(s), file(s) needing updating, changing or deleting**
https://firelemons.github.io/casaMetricsComparison/ is from https://github.com/rubyforgood/casa-metrics-comparison

**Comment by compwron** [comment]
closing for now as not developable
