### ISSUE TITLE
Add Generate Report Button to Volunteer Case Details Page

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2464]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Currently, supervisors have a pretty generate report button on their case details page, but the volunteers do not. We would like to add this same button to the case details page that volunteers see. 

**Screenshots of current behavior, if any**  
Currently Supervisors See:
![Supervisor with Button](https://user-images.githubusercontent.com/7007647/130542382-ae3a9095-44b6-4786-8f4c-8c3ceb1d81f7.png)

Currently Volunteers See:
![Volunteer without Button](https://user-images.githubusercontent.com/7007647/130542399-a153163b-464b-4edf-a489-06e388cb76d5.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by RomanTurner** [comment]
On it 🤠
