### ISSUE TITLE
Make Seed Data Generate Court Dates

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2469]
**Description**
Currently, seed data doesn't generate court dates. We would like the seed data to generate a future court date for the Next Court Date, a date approximately a month before the future court date for the Court Report Due Date, a Court Report Status (Not submitted, Submitted, In review, or Completed), and where appropriate a Court Report Submitted Date not too far before the due date. Approximately half of cases should also have at least one Past Court Date. 

**Existing gem(s), file(s) needing updating, changing or deleting**
seeds.rb
**New file(s) needing creating**

**Comment by lsparlin** [comment]
I can create some seed data

**Comment by compwron** [comment]
@lsparlin look at our existing `seed.rb` and how it generates data- we want court dates to be generated in the seed data in addition to existing data. You can run seed data locally by `rake db:seed`
