### ISSUE TITLE
Add Emancipation Checklist Summary to Emancipation Button

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2470]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently there is a plain button to link to the appropriate emancipation checklist from a case details page. We would like this button to have a fraction on it representing how complete the emancipation checklist is i.e. 0/18 (where 0 is the number of top level emancipation items they've entered results for out of 18 total).

**Screenshots of current behavior, if any**  
![Emancipation button](https://user-images.githubusercontent.com/7007647/130548038-fe02c73e-cd40-49ce-a909-b6437bbe95d3.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by r-sierra** [comment]
Working on it
