### ISSUE TITLE
Make Names Reflect Current Name in Past Notifications

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2471]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when someone updates their name, their name does not update in past notifications. We would like to change this so that the names appearing in notifications always reflect the current name of the person being referenced. 

**Screenshots of current behavior, if any**  
Here we see Whitney Block who used to be named Volunteer 1 still has a bunch of notifications referencing their old name:
![Names Should Update When Changed](https://user-images.githubusercontent.com/7007647/130549016-58255226-df9a-4078-aabd-b3b3ca8604fb.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by r-sierra** [comment]
Working on it
