### ISSUE TITLE
Change Court Mandates to Court Orders

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2474]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, we have a section of the case details page labelled Court Mandates. We would like to change all references to this to instead refer to Court Orders. 

**Screenshots of current behavior, if any**  
![Mandates to Orders](https://user-images.githubusercontent.com/7007647/130862366-77c48e0c-50a1-4092-8a60-1ccd0f37295e.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by FireLemons** [comment]
All good

**Comment by jpletner** [comment]
I'll work on this one.
