### ISSUE TITLE
Show Emancipations Checklist Link if Case is in transition age

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2488]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Current Behavior
![image](https://user-images.githubusercontent.com/8918762/131237446-bcd74405-802d-4a15-a6b6-179614befbf9.png)
The emancipation checklist link doesn't show if the case is of transitioning age

### Expected Behavior
When a case is at least 14 years old, show the emanipation button

**Comment by MohamedAsan** [comment]
@FireLemons This must be due to the non-functioning of the [rake task](https://github.com/rubyforgood/casa/blob/f5c6fd2915af50c6d8319a138ca306b9a741dafc/lib/tasks/scheduler.rake#L2) - `transition_youth`

Is there a way to check this in Heroku?

**Comment by FireLemons** [comment]
@MohamedAsan Could you please take only one issue at a time?

**Comment by MohamedAsan** [comment]
@FireLemons Sorry, I was just curious 😅

**Comment by samruddhi-m-suryaji** [comment]
Hi just curious, Is this still an open issue? I am able to see the Emancipation link on all transitioned cases.
![image](https://user-images.githubusercontent.com/6020999/148313897-d256c309-1d81-44ae-9a80-124838a3aaa1.png)

**Comment by FireLemons** [comment]
yes because that doesn't show up based on the age of the youth

**Comment by shkm** [comment]
I can do this one.
