### ISSUE TITLE
Align Generate Report Button with Other Buttons on the Case Details Page

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2495]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, on the CASA Case Details screen when the screen is sized so that all the buttons are in a line the New Case Contact, Edit Case Details, and Emancipation buttons are all aligned, but the Generate Report button is shifted four pixels up compared to these other buttons. We would like the Generate Report button to align with the other three buttons. 

**Screenshots of current behavior, if any**  
![image (1)](https://user-images.githubusercontent.com/7007647/131417333-3b25a0d5-0f2f-4a7a-814c-caf39211e962.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by jpletner** [comment]
I'll take this one.
