### ISSUE TITLE
Newly created CASA should have starter kit of contact types and hearing types

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2501]
**What type(s) of user does this feature affect?**
N/A / all

**Description**
Currently when a new CASA is added by an All Casa Admin by clicking the `Create CASA Organization` button https://github.com/rubyforgood/casa/blob/354cc0b239ed80519cf9909f90426b0edfff4ed4/app/views/all_casa_admins/casa_orgs/new.html.erb#L24 it doesn't have any hearing types, contact type groups, or contact types. 

Edit the controller https://github.com/rubyforgood/casa/blob/354cc0b239ed80519cf9909f90426b0edfff4ed4/app/controllers/all_casa_admins/casa_orgs_controller.rb#L11 to automatically create contact groups, contact types, and hearing types for newly created CASA Organizations. 

**Screenshots of current behavior, if any**  
![Unpopulated new CASA](https://user-images.githubusercontent.com/7007647/131571872-1a496a4c-de4b-44bd-8a48-d0f5e6b80fb0.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by librod89** [comment]
@FireLemons @compwron how are new casa_orgs created currently? The only way I can see to create on is through the rails console using `FactoryBot.create(:casa_org)`

**Comment by FireLemons** [comment]
as an all casa admin
![image](https://user-images.githubusercontent.com/8918762/135701828-3822a146-e613-4080-aa44-cd15c121207c.png)

**Comment by compwron** [comment]
We still need this- I just did it by hand in prod for Union casa

**Comment by compwron** [comment]
```
BASIC_CONTACT_TYPES = {
    CASA: ["Youth", "Supervisor"],
    Family: ["Parent", "Other Family", "Sibling", "Grandparent", "Aunt Uncle or Cousin", "Fictive Kin"],
    Placement: ["Foster Parent", "Caregiver Family", "Therapeutic Agency Worker"],
    "Social Services": ["Social Worker"],
    Legal: ["Court", "Attorney"],
    Health: ["Medical Professional", "Mental Health Therapist", "Other Therapist", "Psychiatric Practitioner"],
    Education: ["School", "Guidance Counselor", "Teacher", "IEP Team"]
}.freeze

casa_org = CasaOrg.last
casa_org.name # "CASA of Union County"
BASIC_CONTACT_TYPES.each do |contact_group_name, contact_type_names|
  group = ContactTypeGroup.find_or_create_by!(casa_org: casa_org, name: contact_group_name)
  contact_type_names.each do |type_name|
    ContactType.find_or_create_by!(contact_type_group: group, name: type_name)
  end
end

active_hearing_type_names = [
    "emergency hearing",
    "trial on the merits",
    "scheduling conference",
    "uncontested hearing",
    "pendente lite hearing",
    "pretrial conference"
]
active_hearing_type_names.each do |hearing_type_name|
  HearingType.find_or_create_by!(
      casa_org_id: casa_org.id,
      name: hearing_type_name,
      active: true
  )
end
```

**Comment by compwron** [comment]
This would be very nice to have right now, I am running it by hand for n mississippi
