### ISSUE TITLE
Fix Malfunctioning Rake Task clear_passed_dates

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2502]
**Description**
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1630018874022900

Make this rake task not cause the above error. It's creating an invalid something and it should not be. 

```
BugsnagAPP  4:01 PM
Event in production from casa in clear_passed_dates (details)

Unhandled error
ActiveRecord::RecordInvalid: Validation failed: Date must be in the past
Location
lib/tasks/scheduler.rake:13 - block (2 levels) in <main>
```

**Existing gem(s), file(s) needing updating, changing or deleting**
lib/tasks/scheduler.rake 

**New file(s) needing creating**
None

**Comment by compwron** [comment]
this is no longer happening. closing.
