### ISSUE TITLE
Add Text to Supervisor and Admin Reactivation Messages

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2503]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Currently when a Supervisor or Admin is reactivated a banner appears which says "(Supervisor/Admin) was activated." as shown in the screenshot below. We would like to add to this banner the text "They have been sent an email."

**Screenshots of current behavior, if any** 
![Activated Supervisor](https://user-images.githubusercontent.com/7007647/131573212-8f788ffd-9a05-4d5e-8ff0-60740ee2213a.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by AravindSelvamani** [comment]
I would like to work on this issue. Kindly assign the issue and provide me write access @CovenantHuman @FireLemons
