### ISSUE TITLE
Remove Return to Dashboard Button on New CASA Creation Page

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2504]
**What type(s) of user does this feature affect?**
 - all casa admins

**Description**
Currently on the Create a new CASA Organization page there is a Return to Dashboard button. We would like this button removed. 

**Screenshots of current behavior, if any**  
![New CASA Generation Screen](https://user-images.githubusercontent.com/7007647/131573791-048e7bda-da50-42f8-bc09-02cd15b669fb.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by MohamedAsan** [comment]
Why do we have to remove this button? It's an easier way to go back to the list page if the admin wants to cancel the operation. I would suggest renaming it to "Cancel" rather than removing it completely
