### ISSUE TITLE
Make Contact Types All Checked By Default on Edit Case Details Page

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2507]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, on the Edit Case Details page, all the boxes under contact types are unchecked by default. We would like all of these boxes to be checked by default instead. Also we would like to add two buttons, one which checks all the boxes, and one which unchecks all of the boxes. Finally, we would like all the boxes being unchecked to prevent the page from being saved, with a message pop up that says, "At least one contact type must be selected.".

There is another ticket relating to the layout of this page, which may be relevant: https://github.com/rubyforgood/casa/issues/2505

**Screenshots of current behavior, if any**  
![Contact Types in Edit Case Details](https://user-images.githubusercontent.com/7007647/131576230-f4479365-f02b-45e4-a9af-0e1d438491b0.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by nehaabraham** [comment]
To clarify, do you want all the contact types to be checked only if there are none already selected?

**Comment by compwron** [comment]
i am going to adopt this PR

**Comment by iloeza** [comment]
I can take this if it's still available

**Comment by compwron** [comment]
This issue is available for new developement. @iloeza Do you still want it? :)

**Comment by mussajoop** [comment]
I can work on this. 🙌

**Comment by mussajoop** [comment]
Hi there, what about if a Case has some contact types checked and saved (for example during a previous edit), do we follow the default behavior (all contact types are checked by default), or do we select only the contact types of that Case?? 🤔 
I mean if a Case has no contact types, we follow the default behavior (all contact types are checked) else, we select only the contact types of that Case.

**Comment by mussajoop** [comment]
Great! I'm just finishing some tests. I'll open a PR tonight then. Thanks
