### ISSUE TITLE
Make Status Filter for Supervisors

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2509]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, there is no way to filter supervisors on the Supervisors page. We would like to add a filter that allows for supervisors to be filtered by status (whether they are active or inactive), as can already be done with volunteers. The filter should match the filters already present on the Volunteers page. 

**Screenshots of current behavior, if any**  
The Supervisors page as it is now:
![Supervisors without Filters](https://user-images.githubusercontent.com/7007647/131739839-dcf902ad-6398-48b7-9eee-fe69b0dc8610.PNG)

The Volunteers page with filters:
![Volunteers with Filters](https://user-images.githubusercontent.com/7007647/131739892-ad43cc35-d347-47ae-8f26-b35933ac1720.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by m-pereira** [comment]
@CovenantHuman I would like to work on this, please give me more information about it, witch columns do we need to apply the filter? For example `volunteer assignments`, if user select this one, all the supervisors will be filtered by `volunteer assignments` `:desc`? Or it isn't the idea?

**Comment by CovenantHuman** [comment]
The column we want to sort by does not currently exist. We want to add a filter like the filters on the volunteer page (see attached image), that allows users to select whether to show only active people, only inactive people, or both. 

![Volunteers with Filters](https://user-images.githubusercontent.com/7007647/132270694-c082a217-46c2-4e86-a6dc-229aada8e238.PNG)

**Comment by m-pereira** [comment]
I'm learning how it was implemented in volunteers index page, mainly the javascript part
