### ISSUE TITLE
Add Column to Manage Volunteers Chart on Edit Supervisor Page Reflecting Current Supervisor for Unassigned Volunteers

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2524]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently the edit supervisor page has a section at the bottom that shows all their assigned volunteers. If Include Unassigned is selected, it also shows all volunteers previously assigned to this supervisor who no longer are. We would like to add a column to this chart which displays the current supervisor of volunteers previously assigned to this supervisor. If a volunteer that was formerly assigned to this supervisor is not currently assigned to a supervisor this column should read No one. 

**Screenshots of current behavior, if any**  
A screenshot of the current chart with the desired changes drawn in:
![supe-current](https://user-images.githubusercontent.com/7007647/132063636-0208b2b7-4375-430d-956e-afd6837d8647.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by AravindSelvamani** [comment]
I would like to work on this issue. Kindly assign the issue and provide me write access @FireLemons @CovenantHuman

**Comment by FireLemons** [comment]
@AravindSelvamani Could you take only 1 issue at a time so you don't discourage others from taking issues?
