### ISSUE TITLE
Reset Date to Current Date When Set to Future Date on Case Contact

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2533]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, if you try to set the Occurred at date on a Case Contact to a date in the future, a warning flashes on the screen, but the date does not change to a different date. We would like it if when this warning flashes the date would be set back to the current date. 

**Screenshots of current behavior, if any**  
![Case Contacts Shouldn't Occur in the Future](https://user-images.githubusercontent.com/7007647/132272425-dcdc3e81-cce3-4671-8b7f-36553daaebd1.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by arthur1041** [comment]
I can work on a fix for this issue.

**Comment by compwron** [comment]
@[arthur1041](https://github.com/arthur1041) yay! :)
