### ISSUE TITLE
Allow Volunteers to Edit/Modify Court Order Status 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2535]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Allow Volunteers to Edit/Modify Court Order Status as well as the court orders themselves. 

For allowing volunteers to Edit/Modify Court Orders themselves see ticket: https://github.com/rubyforgood/casa/issues/2494

**Screenshots of current behavior, if any**  
![Court Mandate Status](https://user-images.githubusercontent.com/7007647/132273131-166414fb-25a0-4d25-8f87-f168d7f70df9.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by josearmandojacq** [comment]
@CovenantHuman can you please close this one too? I worked on this in my PR too
