### ISSUE TITLE
Make Court Mandates Easier to Navigate Visually

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2537]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a user is looking at the CASA Case Details page for a case the Court Mandates are just a large amount of text with some useful line breaks. We would like to make this portion of the site easier to navigate visually. In order to do this, we would like to number the court mandates. We would also like to move the status from the end of each individual mandate to the beginning. We would like to have each status appear paired with an emoji, where Implementation Status Not Set and Not Implemented both appear with a red x (❌), Partially Implemented appears with a clock (🕗), and Implemented appears with a green checkmark (✔️).

Note: Make sure that the emoji will not show up in the Court Report. Make sure that the Court Report is unchanged by any of these changes.

**Screenshots of current behavior, if any**  
![Court Mandates Formatting](https://user-images.githubusercontent.com/7007647/132274447-e66a6edb-bdd8-46ce-a51d-f9c7c756c586.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by MohamedAsan** [comment]
I would like to work on this issue. Kindly assign it to me
