### ISSUE TITLE
Court Report Not Generating Properly

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2539]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
When I click Generate Court Report for this specific case, the court report is not generated and an error appears 
![Humanize](https://user-images.githubusercontent.com/7007647/132275637-677a04e9-9dae-4d74-af6b-60295696d0e7.png)

I believe this is being caused by the case having a court mandate set to Set Implementation Status rather than an implementation status. 

### Expected Behavior
When I click Generate Court Report a Court Report should be generated. 

### How to Replicate
ex: 
1. - Log into staging as an admin or supervisor.
2. - Click on "Generate Reports" in the left sidebar menu.
3. - Select Case Number 01-1004
4. - Click "Generate report" at the bottom of the page.

see https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates

**Comment by MohamedAsan** [comment]
@CovenantHuman This happens when the implementation status is not set.

How should it appear in the report? Should it be left blank, or should it be "Not implemented"?

Also, we can show "Not Implemented" as the default choice instead of "Set Implementation Status". Would like to hear your thoughts on this

**Comment by FireLemons** [comment]
It should be "Unspecified" in red text in the report

**Comment by MohamedAsan** [comment]
Hi @FireLemons,

I have raised a PR. I was not able to format the template docx file to show "Unspecified" in red text. Can you help me with that?

**Comment by FireLemons** [comment]
Try just making the text red and wrapping it in an if
![image](https://user-images.githubusercontent.com/8918762/135528093-2f595a3d-d2ee-4490-9ede-781e0dd7f93d.png)

**Comment by FireLemons** [comment]
It's kind of like php

**Comment by MohamedAsan** [comment]
@FireLemons Is there any recommended tool to edit the docx template file? I have a MacBook which does not have any applications to edit the file

**Comment by FireLemons** [comment]
You have to find a way to run ms word. Do you have a friend with a windows machine?

**Comment by MohamedAsan** [comment]
@FireLemons I tried this but still the value is empty. Kindly help

<img width="821" alt="Screenshot 2021-10-01 at 11 32 29 AM" src="https://user-images.githubusercontent.com/29650842/135573107-bc6639eb-ca60-4054-93ed-5de5884816a4.png">
[default_report_template_updated.docx](https://github.com/rubyforgood/casa/files/7264559/default_report_template_updated.docx)

**Comment by MohamedAsan** [comment]
Figured it out by following [these steps](https://github.com/senny/sablon/blob/master/misc/TEMPLATE.md#macos) 😄
