### ISSUE TITLE
de-flake Cypress tests

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2550]
Fairly often, cypress fails when nothing is wrong. Make it not do that. 

Examples:
https://github.com/rubyforgood/casa/pull/2595/checks?check_run_id=3616639951

How it runs in CI: https://github.com/rubyforgood/casa/blob/main/.github/workflows/cypress.yml

How to run it locally:
in 1 window, run `RAILS_ENV=test bundle exec rails server -b 0.0.0.0 -p 4040 -d`
in another window, run `npm run test:cypress`

**Comment by compwron** [comment]
On my local I am having login troubles but those are not the same as on CI as far as I can tell...

**Comment by FireLemons** [comment]
I think we removed cypress
