### ISSUE TITLE
Last Logged In Does Not Reflect Current User Session 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2551]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
The date displayed as last login does not reflect the current date when a user is currently logged in. Note that in this screenshot the user is logged in on September 8, but their last login is reported as August 24.
![Current Login Not Reflected in Last Login](https://user-images.githubusercontent.com/7007647/132583355-94a2d182-610f-42d8-8380-bb507b1ad36b.png)

### Expected Behavior
The date displayed as last login should reflect the date that the user was last logged in, therefore it should show the current date if the user is currently logged in. 

### How to Replicate
1. - Log into qa or staging as a user that has not logged in so far today.
2. - Go to Edit Profile and note the date displayed as last login.

**Comment by r-sierra** [comment]
Working on it!

**Comment by r-sierra** [comment]
According to [Devise docs](https://www.rubydoc.info/github/heartcombo/devise/master/Devise/Models/Trackable) the field `last_sign_in_at` holds the timestamp of the previous sign in and `current_sign_in_at` the timestamp when the user signs in.
