### ISSUE TITLE
Mac Install Instructions

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2557]
**Description**
add setup instructions to `doc/MAC_SETUP.md` for installing the project from scratch on mac os

**Comment by christinaheadley** [comment]
working on it

**Comment by FireLemons** [comment]
@christinaheadley heads up someone added to the mad install readme

**Comment by kaysiz** [comment]
@FireLemons @littleforest can this be closed since a PR was merged with the Mac installation instructions

**Comment by littleforest** [comment]
@ErinClaudio you are working on updating the instructions, right? Should this ticket be assigned to you?

**Comment by FireLemons** [comment]
yeah lets close. Erin has a different issue for his work
