### ISSUE TITLE
Remove All Return to Dashboard Buttons 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2577]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently there are at least three pages (New Case Contact, Create New Supervisor, New Volunteer) where we have Return to Dashboard buttons. We would like to remove these buttons everywhere they appear. 
Some relevant code: 
```./app/helpers/ui_helper.rb:3:    link_to "Return to Dashboard", root_path, {class: "btn btn-info pull-right"}
./config/locales/views.en.yml:348:        return_to_dashboard: Return To Dashboard
./spec/views/case_contacts/new.html.erb_spec.rb:24:    it { is_expected.to have_selector("a", text: "Return to Dashboard") }
./spec/views/supervisors/new.html.erb_spec.rb:15:    it { is_expected.to have_selector("a", text: "Return to Dashboard") }
./spec/views/volunteers/new.html.erb_spec.rb:15:    it { is_expected.to have_selector("a", text: "Return to Dashboard") }
```

Potentially Related Issue: https://github.com/rubyforgood/casa/issues/2504

**Screenshots of current behavior, if any**  
New Case Contact:
![New Case Contact Return to Dashboard](https://user-images.githubusercontent.com/7007647/133186423-57c53ed2-03e8-4775-9d9d-112785f55d26.PNG)

Supervisor:
![New Supervisor Return to Dashboard](https://user-images.githubusercontent.com/7007647/133186438-2bac37d2-24ba-47cb-acda-d4edf7633103.PNG)

Volunteer:
![New Volunteer Return to Dashboard](https://user-images.githubusercontent.com/7007647/133186453-6440403b-00a4-427a-902c-8a9d8fc32c19.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by AravindSelvamani** [comment]
I would like to work on this issue. Kindly assign the issue and provide me write access

**Comment by AravindSelvamani** [comment]
@CovenantHuman @FireLemons Can you please give me write access. I'm not able to publish the branch

**Comment by compwron** [comment]
@AravindSelvamani I sent you write permissions, you should have an invite email
