### ISSUE TITLE
Support multiple future court dates

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2582]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
 - [x] Rename past court date to court date in models, database tables, controllers, any other references
 - [x] Allow court dates to be from the future
 - [x] Write a migration that will change any casa case's court date column to a court date row and association (really prove that this works)
 - [x] Refactor code relying on a casa case's court date to use the next future court date instead
 - [x] Remove add court date section on edit casa case page
    ![image](https://user-images.githubusercontent.com/8918762/133290659-cdde60cd-7d8b-4854-a5d0-54f5dc67ef17.png)
 - [x] Change past court dates to just court dates on casa case page
 - [x] Write/update test for code

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by stephenandersondev** [comment]
I took care of the last 2 items on this one, I just need permission to create a branch on the repo.

**Comment by stephenandersondev** [comment]
> Things left to do for this ticket:
> 
> * [ ]  Remove `court_date` column from casa_cases table (maybe wait a couple weeks for this to make sure the data is no longer needed)
> * [ ]  Update header on `default_past_court_date_template.docx` from "Past Court Date Report" to "Court Date Report" (I can't do this myself because I can't open docx files without messing up the formatting)

The removal of `court_date` from `casa_cases` will be handled in https://github.com/rubyforgood/casa/pull/4464, and the updating of the header in `default_past_court_date_template.docx` will be handled in #4466
