### ISSUE TITLE
Rename all court mandates to court orders in the code

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2599]
Court Mandates have been named court orders on the frontend. Update all remaining code to refer to court mandates as court orders.

 - Create a migration to rename the table
 - Rename the model (`app/models/case_court_mandate.rb`)
 - rename the controller (`app/controllers/case_court_mandates_controller.rb`)
 - rename the policy (`app/policies/case_court_mandate_policy.rb`)
 - update any tests
see https://stackoverflow.com/questions/11924124/how-to-rename-rails-controller-and-model-in-a-project

**Comment by efgalvao** [comment]
Should I rename "mandate_text" to "order_text" too ?

**Comment by FireLemons** [comment]
should probably replace all "mandates" with "court_order". Yes, there should be no mention of court mandates in any backend code. Leave the views and javascript alone.

**Comment by efgalvao** [comment]
Should I rename the field 'mandate_text' to 'court_order_text' and all his references too ?

**Comment by FireLemons** [comment]
Where is that variable

**Comment by efgalvao** [comment]
It is a field in the "case_court_order"(the old case_court_mandate table)
```t.string "mandate_text"```
So it is referenced in all the backend, I only changed the table and his references in the code.

**Comment by FireLemons** [comment]
yeah change that

**Comment by compwron** [comment]
Yes please follow the article :)
