### ISSUE TITLE
Use Calendar Based Date Picker for Court Report Due Dates

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2600]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently we are using day, month, and year dropdowns to set dates for Court Report Due Dates on the Edit Case Details Page. (Example: Login to QA as volunteer1 and go to this link: https://casa-qa.herokuapp.com/casa_cases/2305/edit) We would like to replace this with a calendar based date picker like the one that is being used to set Occurred at on the New Case Contact Page.

Related to: https://github.com/rubyforgood/casa/issues/2932

**Screenshots of current behavior, if any**  
The Current Date Picker:
![New Past Court Date](https://user-images.githubusercontent.com/7007647/133694161-ca91b9f8-11cc-4d32-86b0-ec835eadd1bb.PNG)

The Desired Date Picker Style: 
![Nice Date Picker](https://user-images.githubusercontent.com/7007647/133694207-d3b5c6bd-fceb-4b9f-a91e-6c7f30327df6.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by c-duo** [comment]
I'll work on this issue 🤚
