### ISSUE TITLE
Emancipation Checklist api set status code to 500 for errors

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2610]
**Description**
When an error occurs for emancipation ajax requests, send the correct HTML Status codes 400s (client errors) 500s (server errors)
The emancipation javascript expects to receive errors as 200s range status codes (success)
update how errors are handled in `app/javascript/src/case_emancipation.js`
update tests

More about HTML status codes here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by compwron** [comment]
@FireLemons can you add more details to what change we want to make here?

**Comment by dpaola2** [comment]
@GALTdea @ThomasNathan
