### ISSUE TITLE
Send case contacts reminder email to volunteer without supervisor

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2611]
### Impacted User Types
 - volunteers

### Environment
all

### Current Behavior
When a volunteer without a supervisor is sent a case contacts reminder email, it fails because a supervisor is required in the cc

### Expected Behavior
Sen the email without the cc

see `app/mailers/volunteer_mailer.rb`

**Comment by compwron** [comment]
Closing, this is a duplicate of https://github.com/rubyforgood/casa/issues/2590
