### ISSUE TITLE
Make Blank Court Order on New Court Date Not Block Saving

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2616]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, if one adds a court order to a New Past Court Date (being renamed New Court Date. See issues: #2582 and #2589) and leaves it blank or types in it and then deletes all that text, the court date will not save because there can't be a blank court order (See screenshot below). We would like it if a blank court order would be not saved, but also not block the saving of the court date. We would like it if a blank court order was simply not saved as happens on the Edit Case Details Page. 

**Screenshots of current behavior, if any**  
![Blank Court Order](https://user-images.githubusercontent.com/7007647/134083676-9ae4452d-bf87-461e-89ac-f5f5e945be2a.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by compwron** [comment]
We still want to fix this
