### ISSUE TITLE
Fix CASA Case Prefix Filter

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2618]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
When a prefix is selected from the CASA Case Prefix Filter on the Cases page, cases do not filter.
![Screen Shot 2021-09-17 at 5 03 48 PM](https://user-images.githubusercontent.com/7007647/134087445-9cf1cb04-b637-4ef5-9099-a4d215240d27.png)

### Expected Behavior
When a prefix is selected from the CASA Case Prefix Filter only cases with that prefix should be shown. 

### How to Replicate
1. - Log into qa or staging as an admin or supervisor.
2. - Click on "Cases" in the left sidebar menu.
3. - Attempt to Use the CASA Case Prefix Filter on the top right.

**Comment by Beigelman** [comment]
hey @CovenantHuman can you assign this issue to me?
