### ISSUE TITLE
Make Table Labelling Consistent on Mobile

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2624]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently when screen size is sufficiently small, the tables for volunteers and cases are hard to read because they have no labels. The supervisors table however has labels and is easy to interact with at any size. We would like to make the volunteers and cases tables look like the supervisors table with appropriate labels.

**Screenshots of current behavior, if any**  
We want the table on the right to look more like the table on the left:
![More Readable Collapsed Tables](https://user-images.githubusercontent.com/7007647/134100552-8ab9f037-43cd-4770-9525-d6d8f8053ba7.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by acrosman** [comment]
I'll be happy to take a pass at this one.
