### ISSUE TITLE
Decouple Selection and Expansion on Emancipation Checklist

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2627]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when you expand a section of the emancipation checklist it automatically selects itself, and when you contract a section of the emancipation checklist it automatically deselects itself. We would like to make it so that sections can be expanded or contracted without changing their selection status (i.e. we would like to make it possible to select contracted sections, or deselect expanded sections without changing whether they are expanded or contracted and expand or contract sections without changing whether they are selected.) 

**Screenshots of current behavior, if any**  
![Expand without Checking](https://user-images.githubusercontent.com/7007647/134104023-01f6b124-1759-4b75-88b6-75feb357a45d.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by compwron** [comment]
We still want this

**Comment by vasconsaurus** [comment]
@compwron going to try this one 🙂

**Comment by vasconsaurus** [comment]
Please give me more time 🙃 it's slow, but moving forward

**Comment by vasconsaurus** [comment]
working on it! 🙂
