### ISSUE TITLE
localstorage autosaver for text fields

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2641]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
 - When a user fills out text inputs auto save the fields to localstorage
 - Fill in the fields with saved data after page load
 - clear the saved data after a submit button has been pressed (could be redesigned around whether the submit was successful)

**Comment by compwron** [comment]
related to https://github.com/rubyforgood/casa/issues/2417

**Comment by littleforest** [comment]
closing in favor of #2417
