### ISSUE TITLE
API

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2647]
**Description**
We'd like to accomplish many things with mobile development like offline service workers and creating an iOS app but to do so we need our routes to work like an api.

 - For every controller action that changes the database, make sure it supports a json format.
 - Error check/sanitize parameters
 - return a status of 500 if an error was encountered
 - Write tests
 - Document the api please edit the api readme in `doc/`

Action list:
Work In Progress List
 - All Casa Admin
   - [x] create
   - [x] update
   - [x] update_password
 - Casa Admin
   - [x] create
   - [x] update
   - [x] deactivate
   - [x] activate
 - Casa Case   
   - [x] create
   - [x] update
   - [x] deactivate
   - [x] reactivate
 - Casa Org (`app/controllers/all_casa_admins/casa_orgs_controller.rb`)
   - [x] create
 - Casa Org (`app/controllers/casa_orgs_controller.rb`)
   - [x] update
 - Case Assignments
   - [ ] create
   - [ ] unassign

Please do not do this all in a single pull request

**Comment by m-pereira** [comment]
I'm not sure about this idea, but I'd like to propose some solution. I'll start by `POST /casa_cases` route

**Comment by m-pereira** [comment]
I'd like to know, why it is necessary, for example, can we use the `respond_to with format` helper, in those controllers?

**Comment by FireLemons** [comment]
> can we use the `respond_to with format` helper  
  
That's originally what I had planned. I was just trying to get a list of all the routes that made changes to the database. Maybe I should look at each controller for a list.

**Comment by m-pereira** [comment]
> > can we use the `respond_to with format` helper
> 
> That's originally what I had planned. I was just trying to get a list of all the routes that made changes to the database. Maybe I should look at each controller for a list.

Nice, then we do not need that implementation and go on with `respond_to` helper. I'll adjust the [pr](https://github.com/rubyforgood/casa/pull/2686)

**Comment by FireLemons** [comment]
thanks I'll clean up the issue description too when I have a chance

**Comment by m-pereira** [comment]
Hey guys, I'm working on Casa Cases endpoints 😃

**Comment by efgalvao** [comment]
Hi, can I work on Casa Orgs endpoints ?

**Comment by mdchaney** [comment]
I actually created an issue regarding this, but the /casa_orgs endpoint should be a singular resource.  It might make sense to fix that while working on it.  That's #2919

**Comment by efgalvao** [comment]
Ok, first I will work on that one.

**Comment by m-pereira** [comment]
Hey guys, I'm working with `casa_admin` endpoints :D

**Comment by m-pereira** [comment]
Hey guys, I'm working on the remaining `CasaOrg` controller, and @thiantonello is working on the last one.

Let's finish this epic 🚀

**Comment by FireLemons** [comment]
That's not the complete list

**Comment by stephenandersondev** [comment]
I took care of the case assignments endpoints, I just need permission to create a branch on the repo.
