### ISSUE TITLE
Add date of last case contact to volunteer view for admins & supervisors

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#265]
Part of epic #4 & #105

**What type of user is this for? [admin/supervisor/volunteer]**
admin & supervisor

**Where does/should this occur?**
In supervisor and admin <a href="https://casa-r4g-staging.herokuapp.com/">dashboard</a> under all volunteer view.

**Description**
Add column to all volunteer view table for "Last Case contact". This column should display the date of the last `case_contact` logged by volunteer. 
Clicking on `case_contact` from the table should take user to  the corresponding <a href="https://casa-r4g-staging.herokuapp.com/casa_cases/329?>CASA case page</a> related to the last logged `case_contact`.

**Screenshots**
It should go here
![volunteer view](https://user-images.githubusercontent.com/62810851/82129227-0d1a8b80-9776-11ea-8395-545cf7084a3c.png)

**Comment by cliftonmcintosh** [comment]
I believe this column already exists. There is a column labeled "Last Contact Made". It is available in the "Pick displayed columns" selector. Once it is selected, a volunteer with a case in which contact has been made shows data. Is this the data you are thinking of?

See here in the view:
https://github.com/rubyforgood/casa/blob/master/app/views/dashboard/_volunteers_table.html.erb#L25
https://github.com/rubyforgood/casa/blob/master/app/views/dashboard/_volunteers_table.html.erb#L10

Here are some screenshots.
Pickable column
![pick-displayed-columns](https://user-images.githubusercontent.com/3824492/82829672-75a1f080-9e79-11ea-845d-40c151251cee.png)

Visible to a supervisor
![last-contact-made-supervisor-view](https://user-images.githubusercontent.com/3824492/82829673-763a8700-9e79-11ea-8ee0-eb70841e9dce.png)

Visible to an admin
![last-contact-made-admin-view](https://user-images.githubusercontent.com/3824492/82829675-76d31d80-9e79-11ea-900a-7ba4b25afea7.png)

**Comment by cliftonmcintosh** [comment]
I've opened #299 to add the link.
