### ISSUE TITLE
Preserve Case Contact notes when editing form

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#2656]
**What type(s) of user does this feature affect?**
 - volunteers?

**Description**
In #2417 , case notes are saved to local storage when the volunteer fills out a new case contact. If the volunteer is auto-logged out, then the case notes are re-populated from local storage into the form. However, this functionality is only working for creating a new case contact, and not for editing a case contact.

[This code](https://github.com/rubyforgood/casa/blob/main/app/javascript/src/case_contact_autosave.js#L3) needs to be modified to look for the form id, or some other element that is present on both the new case contact and edit case contact pages.

Also related to #2655 

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by AlysonBasilio** [comment]
Hey @littleforest, could you assign this issue to me? I would like to work on it.
