### ISSUE TITLE
Prevent webpacker from compiling when only tests have been updated

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2660]
**Description**
Webpacker recompiles when tests have been changed. Prevent webpacker from recompiling when there are changes to files in `https://github.com/rubyforgood/casa/tree/main/app/javascript/__tests__`

**Comment by peaonunes** [comment]
Hey @FireLemons I'm happy to help here on this one, but I could not reproduce the issue. I ran the dev server with `bin/webpack-dev-server` and it watches over `src` files but not recompiles on changes to files in `__tests__`. Could you add some steps to produce this issue?

**Comment by FireLemons** [comment]
try making a new file in `__tests__` that might trigger it. It's happening on my machine on ubuntu

**Comment by FireLemons** [comment]
will be moot soon
