### ISSUE TITLE
write a test asserting that all email previews render valid views

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2676]
**Description**
Write a test making sure all email previews don't render error pages

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/135696439-d0c7aa66-5351-4c1f-9381-e5f5a69be015.png)
![image](https://user-images.githubusercontent.com/8918762/135696452-55190e44-9aa3-4679-ba4e-156ddbd0c8cf.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by gabrielbaldao** [comment]
Could you tell me more about this case?
