### ISSUE TITLE
Do not allow a volunteer without an assigned case to submit a case contact

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#268]
**What type of user is this for? volunteer/supervisor/admin/all**
unknown

**Description**
When logged in as a user with no assigned case, it is possible to visit the `/case_contacts/new` page and submit an empty form, which results in an error because casa_case_id is nil. 

We *do* want to allow a volunteer without a case to view this page, so that they can see what they will do when they have a case but we don't want the form to be submittable without a case_id specified, so that they don't feel that the system is broken or unreliable. 

**Desired fix:** 
If there is no case associated with the user who is visiting the `/case_contacts/new` page, show a red error saying "no case available"

Since in this case this page was reached by changing the url directly, fixing this bug does not include hiding any "Create case contact" buttons/links on the UI.

**Screenshots of current behavior, if any**
![Screen Shot 2020-06-14 at 1 52 27 PM](https://user-images.githubusercontent.com/578159/84603817-537f0b00-ae46-11ea-86f3-ff8efa77bed8.png)
![Screen Shot 2020-06-14 at 1 52 22 PM](https://user-images.githubusercontent.com/578159/84603818-5548ce80-ae46-11ea-9128-83dfa0af4955.png)
![Screen Shot 2020-06-14 at 1 52 11 PM](https://user-images.githubusercontent.com/578159/84603820-5679fb80-ae46-11ea-91c2-e89cd6143a09.png)

**Comment by alindeman** [comment]
I think I'll probably end up solving this alongside (or closely after) #393. Assigning it to myself.
