### ISSUE TITLE
Add order by quantity, functionality in Supervisor index page

### ISSUE THREAD

**Issue by mauricio-prl** [rubyforgood/casa#2683]
**Description**
We are adding the SupervisorDatatable service, in this [PR](https://github.com/rubyforgood/casa/pull/2652), then we need to provide the functionality of order by:

* Volunteer Assignments
* Serving Transition Aged Youth
* No Attempt (14 days)

**Existing file(s) needing changing**

When the PR is merged, they should be: 
`app/datatables/supervisor_datatable.rb`, `spec/datatables/supervisor_datatable_spec.rb`, `spec/system/supervisors/index_spec.rb`

**Comment by m-pereira** [comment]
I think you can start if you copy some files, then after my pr is merged, you can adjust your branch. Thanks for helping! :D

**Comment by matisnape** [comment]
Hmm, I'm looking at how it works now and it seems that the sorting works already. What exactly is needed here? Is it about the query here? https://github.com/rubyforgood/casa/pull/2652/files#diff-22e57f3f06a75406351fecad9f5a40b186664a378509b34f4c59aed4d8946ff3R45 
Not sure what happens here, though...

**Comment by FireLemons** [comment]
Not needed. Our largest casa org only has 7 supervisors so there's no need for sorting

**Comment by crespire** [comment]
I will update #4664 to remove the tests added for this functionality.
