### ISSUE TITLE
Refactor and add some tests for dashboard.js

### ISSUE THREAD

**Issue by m-pereira** [rubyforgood/casa#2684]
**Description**

We need to refactor `app/javascript/src/dashboard.js` file, to avoid codeclimate warnings like [this](https://codeclimate.com/github/rubyforgood/casa/pull/2652). And then write some tests :)

**Existing gem(s), file(s) needing updating, changing or deleting**

app/javascript/src/dashboard.js

**Comment by compwron** [comment]
Closing as old
