### ISSUE TITLE
Combine Volunteers Tab into Cases Tab

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2694]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently on the left side of the screen for supervisors and admins there are two separate tabs, one for cases and one for volunteers. 

We would like to combine these into one tab called Volunteers, which has the following columns from left to right: 
Case Number, 
Case Status (labelled as Status),  
Transition Aged Youth, 
Assigned To, 
Supervisor (this column should default to not displaying, but should be available to be selected), 
and Last Attempted Contact. 

These tabs should be taken directly from the two currently existing pages. 

Also, in keeping with the currently existing pages, which columns to display should remain selectable with the Pick Displayed Columns button, and the filters for Case Status (labelled as Status), Assigned  to Volunteer, Assigned to More than 1 Volunteer, Assigned to Transition Aged Youth, Casa Case Prefix, and Supervisor should still be present and usable. 

Further, in keeping with the current pages the tables should be fully searchable. Finally, we would also like new case and new volunteer buttons at the top of this new page the same way they are currently at the top of their respective pages. 

Follow mock-up in link below:
- https://www.figma.com/proto/HBcfH4G9W2pD8psX67orhg/CASA-Redesigns?page-id=14%3A10&node-id=21%3A85&viewport=345%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=21%3A85&show-proto-sidebar=1

**Screenshots of current behavior, if any**  
The Current Case Page with Desired Columns Displayed (note: edit is not desired, but is currently not deselectable): 
![Desired Cases Columns](https://user-images.githubusercontent.com/7007647/135948184-f9a737a7-bc4d-485d-8926-1294e28a1178.PNG)

The Current Volunteer Page with Desired Columns Displayed: 
![Desired Volunteer Columns](https://user-images.githubusercontent.com/7007647/135948195-1a2d7b1f-9314-444b-a1b5-3554fd23c8b8.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by ludamillion** [comment]
I am working on this. I’m still familiarizing my self with the models and associations as well as the DataTables functionality. Also family and day job and all that. 

If anyone with more knowledge or time wants to work on this feel free. Otherwise I’ll keep chipping away at it.

**Comment by CovenantHuman** [comment]
@ludamillion Sounds great! We appreciate your help, and we look forward to seeing what you come up with. We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Craggar** [comment]
Hoping not to tred on anyone's toes, but I'm looking at this one

**Comment by ludamillion** [comment]
No worries at all. I thought I’d have time for it but a whole lot of stuff hit the fan right after I picked it up. Looking forward to seeing what you come up with.

**Comment by FireLemons** [comment]
I think we've already done this

**Comment by aedwardg** [comment]
@FireLemons from reading the issue description, it sounds like the goals of this issue were
1. Combine the Cases and Volunteers tabs; and
2. Combine the Cases and Volunteers table into a single table.

Neither of these seems to be done yet based on a fresh pull of `main`. 
Is there no longer a desire to combine these two pages?
