### ISSUE TITLE
Default Sort by Last Attempted Contact

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2695]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, we default sort volunteers alphabetically by name and cases by case number. We would like to change things so that we default sort volunteers by last attempted contact, and when these two pages are combined into one (see: https://github.com/rubyforgood/casa/issues/2694) we would like to sort that combined page by last attempted contact, as well.

**Screenshots of current behavior, if any**  
Here is a shot of the Volunteers table sorted alphabetically:
![Sorted Alphabetically](https://user-images.githubusercontent.com/7007647/135949057-2b80c1f0-d28f-4361-996e-4097bf592ff8.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by gabrielbaldao** [comment]
I am not sure if this was what did you ask, can you look please @CovenantHuman  and tell me if it is wrong
