### ISSUE TITLE
Add a Pop-up Summary of Volunteer Activity on Supervisor Log-in

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2696]
**What type(s) of user does this feature affect?**
 - supervisors

**Description**
Currently, when a Supervisor logs in the first thing they see is the Volunteers page. We would like to make it so that when a supervisor first logs in they are shown a pop-up summarizing the actions of their volunteers since their last log-in over this page. Essentially, we would like to base this pop-up on the supervisor's weekly emails which report case contacts made or not made over the course of the past week. In this case, it would be a summary of all the cases that the supervisor is responsible for sorted by volunteer with an update on any case contacts made or the fact that no case contacts have been made since the supervisor's last log-in. 

**Screenshots of current behavior, if any**  
The first thing a supervisor currently sees when they log-in:
![Volunteers Page](https://user-images.githubusercontent.com/7007647/135950255-e331e328-42c5-4856-840c-898efd4db758.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by littleforest** [comment]
closing as not as priority
