### ISSUE TITLE
Add Column to Allow Reminding Directly From Table

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2697]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
When the Volunteers and Cases Tabs are combined (see: https://github.com/rubyforgood/casa/issues/2694), we would like to add a column to this page that allows supervisors and admins to send a reminder to their volunteer directly from the table, preferably with a CC supervisor/admin and supervisor checkbox also inline. 

**Screenshots of current behavior, if any**  
No applicable current behavior to screenshot

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

**Comment by obaidashfaq20** [comment]
working on that

**Comment by obaidashfaq20** [comment]
working on that, require some more time

**Comment by patelkrunal31** [comment]
Is this still assigned to [obaidashfaq20](https://github.com/obaidashfaq20)? if not I am interested in picking up this issue.

**Comment by obaidashfaq20** [comment]
@patelkrunal31 you can contribute to this!

**Comment by littleforest** [comment]
@patelkrunal31 it would be great if you could pick this up! Let us know if you need any help.

**Comment by patelkrunal31** [comment]
Please assign this to me.

**Comment by patelkrunal31** [comment]
> This issue has been inactive for 260 hours (10.83 days) and will be unassigned after 100 more hours (4.17 days). If you have questions, please
> 
> If you are still working on this, comment here to tell the bot to give you more time

I am still working on this as a backend engineer, it's a little bit complex to contribute to the front-end piece.

**Comment by littleforest** [comment]
> It's a little bit complex to contribute to the front-end piece.

Let us know if you need help, or we can help find a front-end person to pair with you.

**Comment by compwron** [comment]
spam engine? mehhh
