### ISSUE TITLE
Allow Users to Save Column Display Preferences

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2698]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
On the combined cases and volunteers page (see: https://github.com/rubyforgood/casa/issues/2694) we would like to make it possible for users to save their preferences regarding which columns to show and which to hide in the table. 

**Screenshots of current behavior, if any**  
The Current Select Displayed Columns Pop-up:
![Select Columns Popup](https://user-images.githubusercontent.com/7007647/135951317-a004c994-4208-4f16-ad45-e637d6870f5a.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by compwron** [comment]
> When we say allow users to save preferences do we mean to the database? 
Yes

> If so is there currently a pattern for this in the application or would that be entirely new behavior?
New

**Comment by ludamillion** [comment]
Cool, I can take a swing at implementing this.

**Comment by JuanVqz** [comment]
I can work on this if still free to pick

**Comment by GALTdea** [comment]
@dpaola2 Is this a good issues to work on? @compwron can i work on this issue?

**Comment by GALTdea** [comment]
Thanks @JuanVqz! I'll definitely hit you up if I run into something!

**Comment by dpaola2** [comment]
@GALTdea has been working hard on this, trying to figure out how to put it into In-Progress

**Comment by GALTdea** [comment]
Still working on it!

**Comment by GALTdea** [comment]
Need more time

**Comment by GALTdea** [comment]
Need more time

**Comment by littleforest** [comment]
Completed in:

1. PR1: https://github.com/rubyforgood/casa/pull/4769
2. PR2: https://github.com/rubyforgood/casa/pull/4833
3. PR3: https://github.com/rubyforgood/casa/pull/4840 

!
