### ISSUE TITLE
Write a test checking that court mandates/orders appear in the generated past court date .docx file

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2717]
**Description**
To generate a past court date report, first edit a casa case, then add a past court date with mandates, then at the bottom of the past court date page, click on download report
![image](https://user-images.githubusercontent.com/8918762/136676732-733df993-75c0-4433-ae74-b2046e6e9b26.png)

Also write a test checking that the court mandates section does not appear if there are no mandates

See `spec/models/past_court_date_spec.rb`
See `spec/requests/case_court_reports_spec.rb` for an example

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by armahillo** [comment]
I don't want to steal all the fun so I'll leave this for someone else but if you're considering this check out these PRs -- it shouldn't be too complicated to do this: #2724  #2726  #2727
