### ISSUE TITLE
Add optional Additional Expense to case contact form

### ISSUE THREAD

**Issue by DirkCionci** [rubyforgood/casa#2760]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
As a Volunteer, I would like the New Case Contact form to be organized in a way that is easier for me to understand so that I can input the data that is needed for each case.

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

**How Should it Work**
- Create New Contact form should look like [mock-up] in link below
  - https://www.figma.com/proto/HBcfH4G9W2pD8psX67orhg/CASA-Redesigns?page-id=0%3A1&node-id=5%3A10&viewport=345%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=5%3A10&show-proto-sidebar=1
  - Other expenses should be associated with feature toggle in System Settings

**Acceptance Criteria**
- Create New Contact form looks like mockup
- Other expenses is displayed when feature toggle is enabled and NOT displayed when it is disbaled

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by DrewAPeterson7671** [comment]
I am working on it

**Comment by DrewAPeterson7671** [comment]
Question on this expense amount.  I need to make a column for it.  I'm thinking to use :decimal for the column type with :precision => 4 and :unit =>2.  But it occurred to me.  The end customer will likely have a maximum amount.  For validation, do we know or can we ask what the maximum expense is?  Would a single line item expense of $1,000 pop eyes out of sockets?  I should think I need to set a validation for a max amount of a line item.

**Comment by compwron** [comment]
Leave out validations for now, the human judgement component will cover it 
We can ask about validations in stakeholder sync next Weds or over email before then, but not urgent.
