### ISSUE TITLE
Add test to check that case contact notes autosaver clears notes correctly

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2766]
**Description**
The notes section of the new case contact form saves automatically to localstorage and is cleared after submitting a case contact successfully. Write a test checking that the notes section is not repopulated with the autosaved notes.

see `spec/system/case_contacts/new_spec.rb`

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.
