### ISSUE TITLE
Add Filters to Reimbursement Queue View

### ISSUE THREAD

**Issue by DirkCionci** [rubyforgood/casa#2771]
**What type(s) of user does this feature affect?**
 - admins

**Description**
As an Admin, I would like to be able to filter paid and unpaid  reimbursements by volunteer, expense type, and date added so that I can see reimbursements by each filter category.

**How should it work**
- Filters should be displayed as outlined in mock-up
   - https://www.figma.com/proto/HBcfH4G9W2pD8psX67orhg/CASA-Redesigns?page-id=30%3A267&node-id=32%3A2&viewport=345%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=67%3A202&show-proto-sidebar=1

**Acceptance Criteria**
- Results on page should display selected filter options
- Total at bottom of page updates to the correct amount of all amounts added from selected filter options
- Filters don't break other functionality of page

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by lukenofurther** [comment]
@compwron looks like 2762 is complete, so is this ready to work on? I'd like to take it on

**Comment by compwron** [comment]
@lukenofurther go for it! :)

**Comment by lukenofurther** [comment]
Awesome, thanks! :)

**Comment by FireLemons** [comment]
had to revert feature because something was broken

**Comment by lukenofurther** [comment]
Hi @compwron, thanks for merging my PR in back in March and sorry for the radio silence on my end. I see there was a problem and there was a partial revert. I'm not surprised - the reimbursements view was in quite a WIP state on the PR, with both the new datatable view and the original table visible. Were there other problems with the page? I have some time to work on it again.

cc @FireLemons

**Comment by compwron** [comment]
@lukenofurther the filters had some problems so we took them out in the meantime- if you have time, we'd love to try again! :)

**Comment by lukenofurther** [comment]
Hi @compwron yeah I saw that. I'll take a volunteer day from work next week or the week after - at the very least that should allow me to break the back of the work

**Comment by FireLemons** [comment]
I think if you comment the bot bothers you less
