### ISSUE TITLE
Add Reimbursement Complete Column to Mileage Report Export

### ISSUE THREAD

**Issue by DirkCionci** [rubyforgood/casa#2772]
**What type(s) of user does this feature affect?**
 - all casa admins

**Description**
As an Admin, I would like the ability to export all reimbursement requests so that all of the data is on one spreadsheet for end of year audits.

Add a column for reimbursement complete to the report 
https://casa-qa.herokuapp.com/reports

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by marmitoTH** [comment]
Hello! 

There are no "expense type" anywhere in the code, in fact, its column in the "Reimbursement Queue" is hardcoded to be always empty, same for the "description" column. The "amount" column from the reimbursement uses the same value from "miles driven". So, the only new column here would be "Reimbursement Complete". Is this correct or am I missing something?

cc @FireLemons @compwron

**Comment by compwron** [comment]
Alternately, just leave out the requests that have been fulfilled!! 
<img width="331" alt="Screen Shot 2022-09-09 at 11 15 42 AM" src="https://user-images.githubusercontent.com/578159/189417397-287970eb-1140-4f3a-9381-d8470cb138fa.png">
