### ISSUE TITLE
Use Calendar Integration and Similar to Allow Users to Set Custom Reminders

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2780]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
We would like to set up a customizable reminder system that allows users to put events on their calendar or request email reminders (we would likely enable this by making our own calendar and storing the events to send reminder emails on it for example calendar events would say to remind volunteer x every y that z). This would be used by volunteers who want to remember to contact x person every y amount of time or similar. We do not want to make our own reminder system we want to use existing tools such as https://www.addevent.com/. 

**Screenshots of current behavior, if any**  
No relevant images

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by littleforest** [comment]
Closing as not a priority
