### ISSUE TITLE
Improve Appearance of 404 Page and Stop Throwing an Exception on Use of Invalid URL

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2784]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a user tries to navigate to a page that doesn't exist by editing a URL, they get shown an error page, and an exception is thrown. We would like this situation to not throw an exception. We would also like the portion of the error page that contains the relevant information to be moved up and centered in the page instead of being nearly hidden by the footer. 
(See also: https://app.slack.com/client/T04PM108C/C010Z8RK8E6)

**Screenshots of current behavior, if any**  
![Current 404 Page](https://user-images.githubusercontent.com/7007647/137402467-bea5f765-a20f-4920-8a07-325bf7375829.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by JelenaD1** [comment]
I ma trying to replicate the issue. Can you provide more information?

**Comment by malsmr** [comment]
Is this still available to be worked on? I found this in ToDo

**Comment by Mar1g0m3z** [comment]
Certainly! Crafting a message to request involvement and inquire about the status of enhancing the user experience for navigating to non-existent pages requires clarity, conciseness, and a constructive tone. Here's a sample message you might consider sending through Slack or a similar communication platform:

Subject: Assistance and Status Inquiry for Error Page UX Improvement

Hi Team,

I hope this message finds you well. I recently noticed our current handling of situations where users navigate to non-existent pages by editing URLs directly. In these instances, they are met with an error page, and an exception is thrown in the system. This process not only impacts user experience negatively but also adds unnecessary exceptions to our logs, which can obscure genuine issues.

I understand there's an ongoing discussion or perhaps a planned enhancement to address this by preventing exceptions from being thrown in such scenarios and improving the error page layout. Specifically, the goal is to make the error message more prominent and user-friendly by centering the relevant information on the page, thus avoiding it being overshadowed by the footer.

Could you please update me on the current status of this initiative? I'm keen to offer my assistance in any capacity needed, whether it be in the planning, design, or development phases. I believe that with a few adjustments, we can significantly improve our users' experience during these navigation errors, making the site more intuitive and less frustrating to use.

Looking forward to your feedback and hoping to contribute to this effort.

Warm Regards,
Seli
