### ISSUE TITLE
new_case_contact form

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#28]
Related to #27 and #3 

Source: `new_case_contact` button

Fields to display on form:
- type (radio button, populated by hard coded options)
- hours (drop down menu that accepts only numbers but allows 15 minute increments. Ex: .15, 1.15, etc)
  - date - (pre-filled with html placeholder: mm/dd/yyyy and default to today's date) (post MVP: include a calendar popup, likely want to refer to a library for this)
 - ^^^ will be related to new post MVP issue: research libraries for calendar pop up options.
- submit button [related to new issue to come re: submit button backend stuff]
   - submit redirects to dashboard view

**Comment by duaimei** [comment]
I talked with Zoe yesterday, and the contact_type should be in a drop down and not as radio buttons.

The case contact id should be displayed when the volunteer has more than one case contact, but just be set when there is only one case contact.

When the "other" contact type is selected, there should be a text box for the user to fill out.
