### ISSUE TITLE
Make case number required when creating new casa cases

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2800]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Make the case number field required

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/137662643-12e30fb8-5a68-49e6-92b8-237c28f12242.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
it looks from the error screenshot like the case number is already required. What is left to do?
