### ISSUE TITLE
Show error if user is of wrong type or nonexistant in email preview

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2809]
**Description**
Some email previews can take a get parameter `id` to specify which user to show the email preview for. 
If the user is the wrong type of user for the preview or nonexistant, show an error instead of redirecting to a valid user.

**Screenshots of current behavior, if any**  
User with id=2265 is a volunteer  
![image](https://user-images.githubusercontent.com/8918762/137924943-e16b6bc1-8e11-4e3e-8a7d-288cfd54fbd7.png)
If I try to pass this id to the account setup supervisor email preview, it shows the first supervisor   
![image](https://user-images.githubusercontent.com/8918762/137925965-efb32eb0-292b-4447-8ffc-184a4c6ad6b5.png)
Also if the email preview is passed a nonexistant user id the first supervisor is shown
![image](https://user-images.githubusercontent.com/8918762/137926991-ad09abf8-388a-411e-aa0d-51a32cbdc15c.png)
Supervisor email preview working normally  
user with id=2185 is supervisor3@example.com
![image](https://user-images.githubusercontent.com/8918762/137926656-3141a393-8bed-4895-ab75-9dd754d5a3fb.png)

_QA Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[QA Mailer previews](https://casa-qa.herokuapp.com/rails/mailers/)

casa_admin1@example.com view other users on the site as an admin
password: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by geeksilva97** [comment]
I've made a Pull Request.
