### ISSUE TITLE
Add a screenshot test

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#282]
What is screenshot testing? https://medium.com/definitylabs/what-is-screenshot-testing-43981023cdff

Use capybara or selenium, since we already have them. The exact approach is up to you!
Capybara `page.save_screenshot('screenshot.png')` `Capybara.save_path` (since we already use capybara)
`Selenium::RSpec::SeleniumTestReportFormatter.capture_system_state(selenium_driver, self)`
https://github.com/mattheworiordan/capybara-screenshot (unmaintained) 😓
1. take a *full-page* screenshot (the pages we care the most about are "new case contact", "admin dashboard", and "login page" - do "new case contact" first because it's most important and easiest to break.
2. save screenshot in `spec/fixtures/`
3. write a test that takes a screenshot and compares it to the previous screenshot and fails if there's too much difference
4. easily overwrite the fixtures screenshot (for when we *want* to make changes)

We don't want to have very many of these, because they will be fragile and slow. BUT it's important to make sure we don't break visuals with yarn/gem updates etc. 

#### Notes on full page screenshots, and screenshots in general, and diffing images in ruby:
https://stackoverflow.com/questions/16695075/is-it-possible-to-take-a-screenshot-of-the-whole-page-with-selenium-capybara
https://stackoverflow.com/questions/50865148/how-to-take-a-screenshot-of-a-full-browser-page-and-its-elements-using-selenium
https://stackoverflow.com/questions/1821167/selenium-screenshots-using-rspec
https://jeffkreeftmeijer.com/ruby-compare-images/ https://gist.github.com/jeffkreeftmeijer/923894 - best approach imo
https://rosettacode.org/wiki/Percentage_difference_between_images#Ruby - alternate approach
https://github.com/teachbase/imatcher
https://github.com/libvips/ruby-vips overkill- probably avoid
https://github.com/samg/diffy unmaintained- probably avoid

https://gist.github.com/sb8244/55246c51e469524f2abd0c17dd3c574e

**Comment by Zrrrpy** [comment]
Hey @strangrjrjr, you still working on this? (No worries if not, we've got a bunch of new contributors working on the project this week!) Let me know either way. :)

**Comment by compwron** [comment]
I talked to Roger and let's put this back in the "to do" list for now :)
