### ISSUE TITLE
Add Court Orders to the Default Court Report Template

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2843]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Currently the default template for Court Reports does not include Court Orders. We would like to add Court Orders to the default template. Note that Court Orders should include implementation status information, and should NOT include emoji. 

see https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates

## Screenshots of current behavior, if any
![Court Report Template](https://user-images.githubusercontent.com/7007647/138800579-4777688f-6f38-4eae-ba59-6d7ec18cb411.PNG)

## QA site access
_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by vasconsaurus** [comment]
@CovenantHuman I will give this one a try 🙂

**Comment by vasconsaurus** [comment]
@CovenantHuman, I took a look at the file `default_report_template.docx`, but the court orders seem to be there.
Has this been done, or am I looking at the wrong thing?

![Screen Shot 2022-10-07 at 14 03 13](https://user-images.githubusercontent.com/87862340/194611734-18ab9125-d36d-40bd-b3b3-1edda9cac64c.png)

**Comment by FeminismIsAwesome** [comment]
@vasconsaurus agree that it appears solved, closing.
