### ISSUE TITLE
Only admins from the CASA which created a reimbursement request should be able to see it

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2880]
This is a follow on to https://github.com/rubyforgood/casa/issues/2762 FYI @matisnape 
Only admins from the CASA which created a reimbursement request should be able to see it

**Comment by m-pereira** [comment]
Hello guys! Can I try this one? 

Can it be solved by adding a `ReimbursementPolicy::Scope`?

**Comment by compwron** [comment]
That sounds like a great solution :)

**Comment by m-pereira** [comment]
Hello, @compwron I need some help here, I didn't understand how `casa_admins` are related directly to `reimbursements`. First of all, in `reimbursementes_controller`, it's been used `policy_scope(CaseContact)`. What is the relation that we need to filter? And now I'm not so sure about my first idea (`ReimbursementPolicy::Scope`). Does it still fit, since we are using `CaseContact` scope instead?

**Comment by m-pereira** [comment]
As far I understand admins can see all `casa_cases`, and then all their `case_contacts`, from the `casa_org`. Which `case_contacts` should we filter?

**Comment by compwron** [comment]
@m-pereira reimbursements are for one casa_org and admins are also for one casa_org. Only admins for the correct casa_org should be able to see reimbursements for that casa_org :)
I like the idea of `ReimbursementPolicy::Scope` more than `CaseContact` scope so that it is more clear. The CaseContact scope currently works because each reimbursement is for one case_contact but someday we want reimbursements that are not for any case_contact, so `ReimbursementPolicy::Scope` is better :)

**Comment by m-pereira** [comment]
> @m-pereira reimbursements are for one casa_org and admins are also for one casa_org. Only admins for the correct casa_org should be able to see reimbursements for that casa_org :) I like the idea of `ReimbursementPolicy::Scope` more than `CaseContact` scope so that it is more clear. The CaseContact scope currently works because each reimbursement is for one case_contact but someday we want reimbursements that are not for any case_contact, so `ReimbursementPolicy::Scope` is better :)

Nice! Thanks for the answer, I'll work on it soon.
