### ISSUE TITLE
Add a 'Change to Admin' button to Editing Supervisor Page When Viewed by Admin

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2882]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently because all users must have a unique email address admins cannot become supervisors and vice versa because they would be in the system twice. We would like to add a button visible only to admins to the Editing Supervisor Page that says 'Change to Admin'. This button would change the supervisors role in the database to admin.

Related to ticket: https://github.com/rubyforgood/casa/issues/2883

**Screenshots of current behavior, if any**  
![Editting Supervisor Page](https://user-images.githubusercontent.com/7007647/139775535-09a8b968-5ae9-4b9b-ac01-4582c404809c.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by scantisani** [comment]
I'm working on this!
