### ISSUE TITLE
Add a 'Change to Supervisor' button to Edit CASA Admin Page When Viewed by Admin

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2883]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently because all users must have a unique email address admins cannot become supervisors and vice versa because they would be in the system twice. We would like to add a button visible only to admins to the Edit CASA Admin Page that says 'Change to Supervisor'. This button would change the admins role in the database to supervisor.

Related to ticket: https://github.com/rubyforgood/casa/issues/2882

**Screenshots of current behavior, if any**  
![Edit CASA Admin Page](https://user-images.githubusercontent.com/7007647/139776101-6885eb80-c255-4c96-a7fe-0a2444fbf75d.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by scantisani** [comment]
I'm working on this!
