### ISSUE TITLE
When Driving Reimbursement is Requested Require an Address

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2884]
**What type(s) of user does this feature affect?**
 - volunteers
 - admins

**Description**
Currently we don't have any way of tracking volunteer addresses for mileage reimbursement. We would like to make it so that for CASAs with mileage reimbursement turned on, when Want Driving Reimbursement is set to yes in a Case Contact, an additional field will become visible and required that requests the volunteers address. Once this address has been set once it should auto-populate in the future, but continue to be editable. 

Related ticket: https://github.com/rubyforgood/casa/issues/2885

**Screenshots of current behavior, if any**  
![Want Driving Reimbursement](https://user-images.githubusercontent.com/7007647/139776854-01cf6d5f-a16e-4e33-a689-7950b911ac88.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by DrewAPeterson7671** [comment]
So this looks like what needs to be on this issue:

**Comment by DrewAPeterson7671** [comment]
So I think this would be my first thoughts on this issue:
Add mileage_address column to case_contacts table (as one long string?  Or array for street number, street, city, state, zip?)
Add to case contact form under mileage reimbursement address field(s).
Add mileage_address (as string or array) to case_contact_params
create js/scss to facilitate hide/show if reimbursement set to "Yes"
verify/create tests

**Comment by compwron** [comment]
address should be its own table

address can be linked to user via address.user_id because for now we expect each user to only have one address

**Comment by mussajoop** [comment]
I'd like to work on that one

**Comment by compwron** [comment]
go for it!!

**Comment by mussajoop** [comment]
what if a case has been assigned to more than one volunteer, 2 for example?

**Comment by compwron** [comment]
Yep that sounds correct :)
If the case has been assigned to more than one volunteer, then only update the address for the volunteer who is doing the editing.

**Comment by mussajoop** [comment]
Great! What about if the one editing the case contact is a `Supervisor` 🤔

**Comment by mussajoop** [comment]
Sounds clear!
