### ISSUE TITLE
Volunteer must be active before getting assigned to new case

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#289]
Part of epics: #4 and #105

**What type of user is this for? [admin/volunteer/supervisor]**
admins and supervisors

**Where does/should this occur?**
On the <a href="https://casa-r4g-staging.herokuapp.com/volunteers/662/edit">Edit Volunteer page</a> accessible by supervisors and admins.

**Description**
When a supervisor or admin try to assign a new case to an *inactive* volunteer, they should get a *red error message* that reads: _Volunteer must be active to assign a new case._
Assigning a new case _should not work_ if volunteer status is `inactive`.

**Comment by armahillo** [comment]
I *think* this might already be solved? 

I signed in as a supervisor, and also as an admin, and set a volunteer to be inactive (in the console). I looked at the edit page to see if I could assign the inactive user to anything, and I was unable to, in the UI. 

It *might* be possible to do this through some other means, but the main UI on the edit page does not appear to make that possible. Let me know if I'm overlooking something! TY!

**Comment by compwron** [comment]
I think you're right! Sorry for the confusion. :)
