### ISSUE TITLE
Automate Moving Tickets from QA to Merged

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2890]
**Description**
Make a bot automate moving tickets from the QA to merged column.
The bot should move the tickets after each deploy. The time of the latest deploy can be found at https://casavolunteertracking.org/health
It only needs to check once a day

**Existing gem(s), file(s) needing updating, changing or deleting**

**New file(s) needing creating**

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
done
