### ISSUE TITLE
Investigate Potential TOTP field

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2892]
**Description**
Investigate if/why LastPass thinks there is a TOTP field beside the Save Mileage Rate button on the New Mileage Rate Page.

**Existing gem(s), file(s) needing updating, changing or deleting**

**New file(s) needing creating**

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by CovenantHuman** [comment]
@FireLemons You mentioned this problem on slack.

**Comment by FireLemons** [comment]
Looking at the keepasxc browser extension repo page, this seems more like a problem with the keepassxc extension than with our codebase
