### ISSUE TITLE
re-enable pundit safety checks, fix tests

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2897]
```
  # after_action :verify_authorized, except: :index # TODO add this back and fix all tests
  # after_action :verify_policy_scoped, only: :index
```

**Comment by LawrenceWhalen** [comment]
@compwron I can take this on. Just to be sure, you want both lines re-added?

**Comment by compwron** [comment]
@LawrenceWhalen yes :)

**Comment by compwron** [comment]
We still want this

**Comment by littleforest** [comment]
@compwron @FireLemons what are your thoughts about removing Pundit requirements for `all_casa_admins` controllers? An `all_casa_admin` user should have access to any action in those controllers (currently). I'm leaning towards just removing Pundit requirements for those controllers since everything would default to true anyway. What are your thoughts?

**Comment by littleforest** [comment]
@compwron should any supervisor be able to edit or delete any note, even if it is not for their volunteer?

**Comment by compwron** [comment]
@littleforest that seems reasonable to remove for all-casa admins

re supervisors and notes... probably yes, but if it's not that way it's not a huge deal as long as admins can do it and the notes aren't volunteer-visible

**Comment by littleforest** [comment]
@compwron can volunteers do any actions with notes?

**Comment by littleforest** [comment]
still working on this

**Comment by littleforest** [comment]
@compwron I think the last controller that needs to be fixed is the `other_duties` controller. I'm a little confused about that feature though. I see a link to the `other_duties#index` page on both Supervisor and Admins, but no link to the `new` page (although it exists and I can manually visit the new page). Do you know what the permissions should be like? Is someone creating a duty for themselves? From the controller index method, it looks like a duty is getting created for a volunteer, but there is no volunteer on the form field. Anyway, wondering if this feature is somewhat unfinished, but I'm not seeing any open tickets around it.

**Comment by littleforest** [comment]
@compwron never mind! I found details in #3556

**Comment by compwron** [comment]
cool cool

**Comment by littleforest** [comment]
The only thing left with this is the OtherDuties controller. Even though this feature might be going away? (#4242) I'll try to get this piece finished soon.
