### ISSUE TITLE
Set case due date automatically to 3 weeks before hearing date when new future court date is added

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2905]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when we add a Next Court Date is set the Court Report Due Date has to be set separately. We would like to make it so that setting the Next Court Date automatically sets the Court Report Due Date to the date three weeks before the Next Court Date. We would like the Court Report Due Date to remain able to be changed manually later. We would just like it to set automatically at the time of adding a Next Court Date. 

**Screenshots of current behavior, if any**  
![Next Court Date with No Court Report Due Date](https://user-images.githubusercontent.com/7007647/140263181-2002cb84-dad9-40e8-ac96-e1b3309a9ce7.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
I ran this in prod
```CasaCase.active.where(court_report_due_date: nil).select { |cc| cc.next_court_date }.map { |cc| cc.update!(court_report_due_date: cc.next_court_date.date - 3.weeks) }```

**Comment by geeksilva97** [comment]
I would like to work on it. Can you assign me?

**Comment by compwron** [comment]
@geeksilva97 This issue needs to be worked on, it is not done. The issue is to start setting court report due dates automatically in prod when a new court date is added. :)

**Comment by geeksilva97** [comment]
@compwron the idea is to set it when the register is being saved?

**Comment by compwron** [comment]
Yes correct :)

**Comment by geeksilva97** [comment]
> Yes correct :)

Perfect!

**Comment by geeksilva97** [comment]
I'll send the Pull Request this week.

**Comment by compwron** [comment]
@geeksilva97 how's it going? Can I help with anything?

**Comment by geeksilva97** [comment]
Hi, @compwron. I've been sick and because of this, I couldn't finish yet. I'm almost finished, I only need some help to test.

I've tried to find the page you sent on the screenshot, but I couldn't. Could you give me a guide on how to find this page so I can test it?

**Comment by geeksilva97** [comment]
Oh my God, you did almost everything haha. Thank you!
