### ISSUE TITLE
Remove old unused field casa_case.court_date now that we use table court_dates instead

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2907]
Remove old unused field casa_case.court_date now that we use table court_dates instead

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kazuhirodk** [comment]
Hi! Can you assign me to work on this issue?

**Comment by stephenandersondev** [comment]
I can take this one. I already finished it, I just need permission to create a branch on the repo. @compwron is that something you can help me out with?
