### ISSUE TITLE
Remove starting default value for Contact Made for new case contact

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#291]
Part of epics #3 & #38 

**What type of user is this for? [volunteer/admin/supervisor/all]**
volunteer

**Where does/should this occur?**
On the <a href="https://casa-r4g-staging.herokuapp.com/case_contacts/new">New Case Contact page</a>.

**Description**
Instead of a dropdown menu under "contact made", there should be a single select radio button or toggle (the choice is yours!) with the same options: yes or no.

**Screenshots**
<img width="1418" alt="contact_made" src="https://user-images.githubusercontent.com/62810851/82740883-a52ded00-9d01-11ea-9ac5-d4dc56f660ee.png">

**Comment by Zrrrpy** [comment]
![Sarah's mockup](https://user-images.githubusercontent.com/62810851/83340481-9ad59b00-a28d-11ea-8f78-3eae1ec4f883.jpg)
 ^^This is a rough mockup showing how Sarah from PG CASA envisions a volunteer marking "contact made"

**Comment by cjilbert504** [comment]
I would like to try to work on this one!
