### ISSUE TITLE
try using https://github.com/tilfin/ougai

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2913]
https://github.com/tilfin/ougai

lets do better logging!

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ludamillion** [comment]
Is the intention for this to simply replace the built in Rails logger for starters?

**Comment by compwron** [comment]
We reverted this for breaking the deploy (see linked PRs), let's try it again :)

**Comment by littleforest** [comment]
Going to close this as unneeded for now.
