### ISSUE TITLE
Volunteers can only be assigned to one supervisor at a time

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#292]
Part of epics #105 and #4

**What type of user is this for? [admin/supervisor/volunteer/all]**
supervisors and admins

**Where does/should this occur?**
On the frontend: In the "edit supervisor" page (future work not in this issue)
On the backend: In the `supervisor_volunteers` table

**Description**
When a volunteer is assigned to a new supervisor, any previous supervisor assignments should end. 

**Relates to issues**
#288

**Comment by colinsoleim** [comment]
I think this behavior already exists because we use the `has_one` association between volunteers and supervisors. Here's the relevant code: 

https://github.com/rubyforgood/casa/blob/master/app/models/user.rb#L11

Was there a specific bug you saw related to this? @Zrrrpy

**Comment by compwron** [comment]
I agree- I checked on the UI and this is done! :) 

<img width="798" alt="Screen Shot 2020-07-22 at 8 31 07 AM" src="https://user-images.githubusercontent.com/578159/88196180-c160e400-cbf5-11ea-9bd7-6cc712ba4814.png">
<img width="763" alt="Screen Shot 2020-07-22 at 8 30 22 AM" src="https://user-images.githubusercontent.com/578159/88196194-c4f46b00-cbf5-11ea-8851-e51aac31e90b.png">
