### ISSUE TITLE
Switch to use date picker on New Court Date page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2932]
What type(s) of user does this feature affect?

- volunteers
- supervisors
- admins

Description
Currently we are using day, month, and year dropdowns to set dates for the New Court Date Page (example: Log into QA as volunteer1 and go to this link: https://casa-qa.herokuapp.com/casa_cases/2305/court_dates/new). We would like to replace this with a calendar based date picker like the one that is being used to set Occurred at on the New Case Contact Page.

Related to: https://github.com/rubyforgood/casa/issues/2600

Screenshots of current behavior, if any
The Current Date Picker:
<img width="711" alt="Screen Shot 2021-11-10 at 6 42 36 PM" src="https://user-images.githubusercontent.com/578159/141227898-374bc4f5-42ea-4b63-930b-e31b0383c3c7.png">

The Desired Date Picker Style:
![Nice Date Picker](https://user-images.githubusercontent.com/7007647/141883243-2c762518-df89-42de-b7bf-05ce3cdcde1e.PNG)

QA Login Details:
Link to QA site

Login Emails:

volunteer1@example.com view site as a volunteer
supervisor1@example.com view site as a supervisor
casa_admin1@example.com view site as an admin
password for all users: 123456

**Comment by RoelofWobben** [comment]
I think I can try this as a new person which is trying to learn rails and ruby

**Comment by RoelofWobben** [comment]
first question. 

on which layout can I found the calender layout that you wanted ?

**Comment by compwron** [comment]
I believe this is in `app/views/court_dates/_form.html.erb`

**Comment by RoelofWobben** [comment]
Thanks, 

This looks not good after a clone and all the steps described in the readme

```
Finished in 4 minutes 10.8 seconds (files took 4.02 seconds to load)
1561 examples, 231 failures, 10 pending
```

**Comment by compwron** [comment]
@RoelofWobben oh no! Can you post one of the failures?

**Comment by compwron** [comment]
My first guess would be that yarn install did not actually work and/or webpacker is sad, try rerunning those?

**Comment by RoelofWobben** [comment]
one of the last errors I see 

```

  195) MileageReport#to_csv includes case contacts from current org
       Failure/Error: expect(parsed_csv.length).to eq(2)
       
         expected: 2
              got: 1
       
         (compared using ==)
       # ./spec/models/mileage_report_spec.rb:58:in `block (3 levels) in <main>'
        `` `

**Comment by compwron** [comment]
Hmm that is... not a test that I would expect to fail for the above reasons. Got any others?

**Comment by RoelofWobben** [comment]
found the culprit. Had not installed chrome.
Got now some pending tests like this : 

 ```
 7) supervisors/index supervisor table filters status when only active checked filters the supervisors correctly
     # Temporarily skipped with xit
     # ./spec/system/supervisors/index_spec.rb:193

  8) supervisors/index supervisor table filters status when both checked filters the supervisors correctly
     # Temporarily skipped with xit
     # ./spec/system/supervisors/index_spec.rb:225

  9) supervisors/index supervisor table when sorting supervisors by supervisor name
     # Temporarily skipped with xit
     # ./spec/system/supervisors/index_spec.rb:103

  10) Health add some examples to (or delete) /home/roelof/casa/spec/models/health_spec.rb
     # Not yet implemented
     # ./spec/models/health_spec.rb
     ```

**Comment by RoelofWobben** [comment]
are the password changed.
I try the one mentioned on the readme and suddenly they do not work anymore

**Comment by RoelofWobben** [comment]
maybe im a too beginner but I do not get something 
I changed in the views/court-dates/_form the code to this : 

 ```
 <div class="field form-group">
        <%= form.label :date, "Add Court Date" %>
        <h2><%= form.label :occurred_at %></h2>
        <% occurred_at = @case_contact.occurred_at || Time.zone.now %>
        <%= form.text_field :occurred_at,
                        value: occurred_at.to_date,
                        data: {provide: "datepicker", date_format: "yyyy/mm/dd"},
                        class: "form-control" %>
      </div>
       ````

but when I refresh the screen , I still see the old screen.
IM sure I saved the form.

What is happening here ?

**Comment by compwron** [comment]
The variable @case_contact is not defined in this new block of code
`<% occurred_at = @case_contact.occurred_at || Time.zone.now %>`
