### ISSUE TITLE
Add hearing type and court report due date to next Court Date line

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2933]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
<img width="1409" alt="plan" src="https://user-images.githubusercontent.com/578159/141228133-c5347f6b-0eb8-45ec-8ef4-ed7d92156977.png">

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by vasconsaurus** [comment]
Hi @compwron! Isn't this done? 

<img width="977" alt="Screen Shot 2022-10-07 at 11 35 08" src="https://user-images.githubusercontent.com/87862340/194579038-87d6ec63-1ed2-4a7c-a611-f882be8ef76d.png">

**Comment by littleforest** [comment]
This looks completed.
