### ISSUE TITLE
Make the volunteer thank you message a modal

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2935]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
After making a case contact, the volunteer thank you message should be a bigger pop up modal on the page

<img width="1084" alt="Screen Shot 2021-11-10 at 1 27 13 PM" src="https://user-images.githubusercontent.com/578159/141228601-cd4a3de2-e193-4c2a-9862-e7764d135992.png">

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by thiantonello** [comment]
May I work on this one?

**Comment by compwron** [comment]
Go for it! :)
