### ISSUE TITLE
Add stock photo to login

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#294]
Part of epic #38

**What type of user is this for? [admin/supervisor/volunteer/all]**
all

**Where does/should this occur** 
on the <a href="https://casa-r4g-staging.herokuapp.com/users/sign_in">logged out view</a> for all users

**Description**
Replace the beautiful 700 x 700 box currently on the logged out view with <a href="https://casa-r4g-staging.herokuapp.com/users/sign_in">this image.</a>

**Screenshots**
<img width="1420" alt="logged out view" src="https://user-images.githubusercontent.com/62810851/82741243-fbe8f600-9d04-11ea-97e0-44a3fe7d80ed.png">

**Comment by colinsoleim** [comment]
![AM14480-1-800x533](https://user-images.githubusercontent.com/1221519/82742652-d244c480-9d2e-11ea-8451-f5528ccf3fd4.jpg)

Here's the image we discussed adding in this spot. Now that I'm looking at it, this image is only 800x533 for pixels, so the page layout might need to be changed a bit.
