### ISSUE TITLE
fix ignored spec supervisors/index_spec

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2940]
### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by aedwardg** [comment]
Looking into it, it appears that 3 of the ignored tests in this file are were failing because the status filter on the Supervisors page no longer works.  This has been documented in #3053
