### ISSUE TITLE
fix ignored spec reimbursements_controller_spec.rb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2941]
### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Oli0li** [comment]
Hello! May I work on this please? If so, could I please get authorisation to open a branch on this repo?

**Comment by FireLemons** [comment]
Move them over to `spec/requests` too
