### ISSUE TITLE
fix ignored spec "can see Add to Calendar buttons" - this depends on https://github.com/rubyforgood/casa/issues/2889

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2942]
fix ignored spec "can see Add to Calendar buttons" - this depends on https://github.com/rubyforgood/casa/issues/2889

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by littleforest** [comment]
Fixed in #4025
