### ISSUE TITLE
Add columns User Count and Case Contact Count to ALL Casa Admin dashboard

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2947]
**What type(s) of user does this feature affect?**
 - **all** casa admins

**Description**
Add columns User Count and Case Contact Count to ALL Casa Admin dashboard

**Screenshots of current behavior, if any**  
![Screen Shot 2021-11-14 at 7 43 59 PM](https://user-images.githubusercontent.com/578159/141719078-0ac4cadb-0ddf-4b9e-b0f2-be87fce8bf56.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by lukenofurther** [comment]
Note that the password to login with the seed accounts is `12345678`

**Comment by compwron** [comment]
> Also, I couldn't login as an all casa admin on the regular login page, I used this page instead:
> http://localhost:3000/all_casa_admins/sign_in

This is correct. Could you add it to the readme? Thanks :)
