### ISSUE TITLE
Wrong Number of Minimum Character Listed in Password Change Flow

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2950]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
The change your password flow states that the minimum number of characters for a password is 6. It's actually 8. 
![Screen Shot 2021-11-05 at 6 20 29 PM](https://user-images.githubusercontent.com/7007647/141884637-cddd8419-73e9-4324-b0d0-86411a16e9f0.png)

Related to: https://github.com/rubyforgood/casa/issues/2951

### Expected Behavior
The password changing flow should list the minimum number of characters as 8, and this number should not be hardcoded. 

### How to Replicate
1. Go to this link: https://casa-qa.herokuapp.com/users/password/edit?reset_password_token=faketoken

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by marmitoTH** [comment]
@CovenantHuman The minimum length is actually 6. You can see this configuration in here:
https://github.com/rubyforgood/casa/blob/main/config/initializers/devise.rb#L218

**Comment by compwron** [comment]
@marmitoTH @CovenantHuman I see it. I guess I was wrong, oops. The devise docs are mismatched to actual default. https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/test/rails_app/config/initializers/devise.rb#L99

I want to change it up it to 8, as long as we check into what the behavior will be for existing users. We may need to change our default seed QA password from 123456 to something longer! maybe 12345678 lol
Also we should stop hardcoding that number in the UI anyway if possible...

**Comment by marmitoTH** [comment]
@compwron It looks like someone has manually set it to 6. Anyway, changing it shouldn't be a problem for existing accounts since their hashes were already created. I'll take a look tomorrow.
