### ISSUE TITLE
Make Court Report Due Date an Optional Field on all Court Dates 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2952]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, we only have a Court Report Due Date for the next upcoming Court Date. 

1. We would like to add an optional field called "Court Report Due Date" to all court dates.
2. We would like to migrate currently set Court Report Due Dates so that they are attached to the next upcoming Court Date.
3.  We would like to remove the prompt to set a Court Report Due Date on the edit case details page. (See screenshot 1)
4. We want the Court Report Due Date to be settable when adding a Court Date. (See screenshot 2)
5. We want the Court Report Due Date to be settable when editing a Court Date. (See screenshot 3)
6. We want Court Report Due Date to be visible when viewing a Court Date. (See screenshot 4)

**Screenshots of current behavior, if any**  
Current location to set Court Report Due Date:
![Court Report Due Date Current Location](https://user-images.githubusercontent.com/7007647/141887194-7549d104-dd0a-45f5-ae2c-4df7afcc4839.PNG)

Desired location to set Court Report Due Date:
![Court Report Due Date Desired Location](https://user-images.githubusercontent.com/7007647/141887223-2c4ea500-9413-4f9a-9f3a-b649f464cbee.PNG)
and
![Edit Court Date Page](https://user-images.githubusercontent.com/7007647/141887912-9e4397a2-f771-431b-9cd7-10b4f0af27a2.PNG)

Court Report Due Date Should Be Visible:
![View Court Date](https://user-images.githubusercontent.com/7007647/141888112-ec56e0e6-171c-4281-ad60-c992a6e4899b.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by vasconsaurus** [comment]
I'm still working on it 🙂
