### ISSUE TITLE
Make Thank You Message Pop Up After Case Contact is Submitted 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2955]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a user enters a case contact, we display a banner stating that the contact was made successfully and a thank you message. We would like to leave the contact made successfully banner, but we would like to make a pop up for the thank you message similar to the one for notes when creating a case contact. 

**Screenshots of current behavior, if any**  
Current Form of the Thank You Message:
![Thank you message in current form](https://user-images.githubusercontent.com/7007647/141889520-70f35a08-08e0-4ae4-9e62-6a8c6bdf1709.PNG)

Desired Form:
![Notes Pop Up](https://user-images.githubusercontent.com/7007647/141889779-8f1cff45-7fec-4156-8d8f-e22980b37d37.PNG)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
This is done
