### ISSUE TITLE
Add .webp to Acceptable Logo File Types

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2957]
**What type(s) of user does this feature affect?**
 - admins

**Description**
We are limiting the kinds of files that can be uploaded as a CASAs logo image. We would like to add .webp to the list of allowable file types. 

Related to: https://github.com/rubyforgood/casa/pull/2910

**Screenshots of current behavior, if any**  
Log in as casa_admin1 and go to this link to see the field that's being limited: https://casa-qa.herokuapp.com/casa_orgs/69/edit

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by CovenantHuman** [comment]
@FireLemons How does this look?

**Comment by FireLemons** [comment]
lets just limit it to webp for now. I think allowing svg uploads might open the site up to some kind of vulnerability

**Comment by rhian-cs** [comment]
Hello, may I give this issue a try?
