### ISSUE TITLE
UI tuning for Supervisor Summary

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2958]
Current state:
![image](https://user-images.githubusercontent.com/8918762/142215083-86cdf24d-ccf1-40c8-80b1-33b4a770ef36.png)

 - Change the red and green to a red and green that contrasts with black text from https://materializecss.com/color.html
 - No borders for the bars including the title.
 - Use flexbox and `flex-grow` to set the bar width to stop calculating the width on the backend.
 - Larger font sizes for the titles.
 - A clearer way to label transitioning case count.

To see the page, log into https://casa-qa.herokuapp.com/ as casa_admin1@example.com password 12345678

**Comment by compwron** [comment]
@FireLemons how does this look?

**Comment by ludamillion** [comment]
![Screen Shot 2021-12-15 at 11 18 14 PM](https://user-images.githubusercontent.com/1638226/146307310-c7ab5fe1-f14a-4ca1-991b-91f8da1249ff.png)

What I've got so far.
