### ISSUE TITLE
Permissions for supervisors - post MVP

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#30]
This issue affects: *supervisors*

**Supervisors should be able to:**
1. View ALL volunteers, not just "their" volunteers (because they may need to help out other supervisors) But their default view should be only **their** volunteers, who they need to supervise)
2. Assign ANY volunteer to ANY case (not just "their" volunteers and cases)
3. Edit a case's "transition aged youth" flag
4. Edit their own name

**Supervisors should NOT be able to:**
1. edit the names of anyone other than themselves
2. create new volunteers
3. create new casa case

**Comment by compwron** [comment]
Closing this because all of the pieces of it are in other issues
