### ISSUE TITLE
Column support for unassign issues bot

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3017]
**Description**
add column name support to  
https://github.com/rubyforgood/unassign-issues
add a tag to each repo for the new release

edit 
`.github/workflows/issue-auto-unassign.yml`

to use column name instead of column id
https://docs.github.com/en/rest/reference/projects#list-project-columns

**Comment by FireLemons** [comment]
xyz

**Comment by FireLemons** [comment]
sadsad

**Comment by FireLemons** [comment]
no

**Comment by FireLemons** [comment]
no

**Comment by compwron** [comment]
bye
