### ISSUE TITLE
Status filter no longer works on Supervisors page

### ISSUE THREAD

**Issue by aedwardg** [rubyforgood/casa#3053]
### Impacted User Types
 - volunteers? ❌ 
 - supervisors? ✔️ 
 - admins? ✔️ 
 - all casa admins? ❌ 

### Environment
All environments, I believe (tested on local and QA with Firefox and Chrome) 

### Current Behavior
When I try to filter Supervisors by activity status nothing changes.  For example, selecting only "Inactive" supervisors does not remove the active supervisors from the list.

![image](https://user-images.githubusercontent.com/44326005/147447923-0451e051-edbe-4a54-ad34-d6cd63bd59a3.png)

### Expected Behavior
Status filter should work as it does on the Volunteers page

### How to Replicate
1. - Log into staging as an admin or supervisor.
2. - Click on "Status" at the top of the page to filter by activity status.
3. - Watch as nothing happens.

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by leevic31** [comment]
I can work on this

**Comment by matisnape** [comment]
May I call dibs on this one?

**Comment by aedwardg** [comment]
@matisnape sure!

**Comment by FranConcaro** [comment]
May I call for this one?

**Comment by aedwardg** [comment]
@FranConcaro Sure, I'll assign this one to you. For now let's keep both the filters and the "show (de)activated" button. We may decide to remove one or the other in the future, but that decision will probably require more discussion with the project leads.

**Comment by FranConcaro** [comment]
I need more time

**Comment by MiguelArgentina** [comment]
Hello @aedwardg , does this issue still needs to be fixed? If so, I could work on it. Please let me know!

**Comment by aedwardg** [comment]
@MiguelArgentina yes, this is still needed, but I'm not sure if @FranConcaro is still working on it.

@FranConcaro is this something you would like to continue, or should I pass it on to Miguel?

**Comment by FranConcaro** [comment]
Hi! I'm sorry, the past weeks had been hard.. i rather pass it, since I don't know if I'm going to be able to finish it

**Comment by aedwardg** [comment]
No worries!
@MiguelArgentina feel free to pick this up. I'll go ahead change the assignee to you.

**Comment by MiguelArgentina** [comment]
Thanks! @FranConcaro, do you have a PR you were working on or shall I start from scratch?

**Comment by FranConcaro** [comment]
No, what I can tell you is that the idea is to handle that rails table as an ajax datatable instead, but keeping the stlye. And once the filters work, remove the show activated/deactivated button

**Comment by ThomasNathan** [comment]
@aedwardg can I claim this?

**Comment by aedwardg** [comment]
@ThomasNathan sure, but it might be worth checking with @FireLemons to see if this is still needed. I haven't looked into it since the new UI changes began.

**Comment by FireLemons** [comment]
still broken

**Comment by ThomasNathan** [comment]
@dpaola2 Please reassign. Thanks

**Comment by dpaola2** [comment]
I believe @crespire is working on this with @ThomasNathan

**Comment by crespire** [comment]
Yep, @ThomasNathan is still leading this issue! We're close!

**Comment by crespire** [comment]
Just awaiting approval on the PR!

**Comment by crespire** [comment]
I'm still working on this!

**Comment by crespire** [comment]
I'm going to try to get this done later today.

**Comment by FireLemons** [comment]
I really wish it would double the amount of time it gave you every time you commented

**Comment by crespire** [comment]
Still working on this!

**Comment by crespire** [comment]
> This issue has been inactive for 444 hours (18.50 days) and is past the limit of 360 hours (15.00 days) so is being unassigned.You’ve just been unassigned from this ticket due to inactivity – but feel free to pick it back up (or a new one!) in the future! Thank you again for your contribution to this project.

This is finished and awaiting code review #4664
