### ISSUE TITLE
prod bugsnag No space left on device ???

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3056]
BugsnagAPP  4:35 PM
New unhandled error in production from casa in GET /casa_cases/214 (details)

Unhandled error
Errno::ENOSPC: No space left on device @ dir_s_mkdir - /app/tmp/cache/E0D
Location
vendor/ruby-3.0.2/lib/ruby/3.0.0/fileutils.rb:253 - mkdir
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1639960539020000

**Comment by FireLemons** [comment]
Maybe it's logging

**Comment by compwron** [comment]
Closing because it stopped.
