### ISSUE TITLE
fix downloading reports

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#306]
Part of epic #4

**What type of user is this for? [admin/supervisor/volunteer/all]**
admin

**Where does/should this occur?**
On the <a href="https://casa-r4g-staging.herokuapp.com/reports">Generate Report page</a> accessible from the admin dashboard

**Description**
Admins should be able to download reports. Right now, they time out when you try to download and land on an application error message. Investigate and fix, please!

**Screenshots**
![report error message](https://user-images.githubusercontent.com/62810851/83340293-30236000-a28b-11ea-9f36-6d5e99371696.png)

**Comment by colinsoleim** [comment]
We should probably make this a background job, do we have a preference on a gem for that? I typically use Sidekiq or DelayedJob, any preference from other contributors?

**Comment by compwron** [comment]
@colinsoleim No specific preference, just the simplest thing that works. Honestly I am a little reluctant to add this because I want to keep our architecture maximally simple, but I don't see a way around it in the long term and it should be relatively painless.
