### ISSUE TITLE
Data for "Last Contact Made" not displaying on admin or supervisor dash

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#307]
Part of epics #4 and #105

**What type of user is this for? [admin/supervisor/volunteer/all]**
admin and supervisor

**Where does/should this occur?**
On both admin and supervisor dashboards in the <a href="https://casa-r4g-staging.herokuapp.com/">Volunteer View.</a>

**Description**
When an admin or supervisor selects "Last Contact Made" in "Pick Displayed Columns" in the volunteer view section of their dashboard, the volunteer view should display by Last Contact Made. But no data is displaying in this column.

**Screenshots**
![volunteer view](https://user-images.githubusercontent.com/62810851/83340404-41b93780-a28c-11ea-8472-3435c05085e8.png)

**Comment by colinsoleim** [comment]
Looks like this column was nil because all the case_contacts in the staging DB had `contact_made` set to `false`. I just updated for testing purpose, should we have a specific string display if there has been no contact?

**Comment by compwron** [comment]
@colinsoleim thanks that's great! We should update seed.rb and I'd like to display "None" in the UI, or maybe ❌ or something
