### ISSUE TITLE
Email supervisor once per volunteer after 14 days of no case contacts being created

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#308]
Part of epic #105

**What type of user is this for? [admin/volunteer/supervisor/all]**
supervisor

**Where does/should this occur?**
This should be an automated email sent to a supervisor via system email.

**Description**
After 14 days with no `case_contact` added to active case assignments, supervisor assigned to volunteer responsible for that case should be notified by email. Text for email below:

Subject line: [Volunteer Name] hasn't made contact with their case in 14 days

Hi [Supervisor Name],

It has been 14 days since [Volunteer name] has logged a case contact. Please check in to troubleshoot any issues [Volunteer name] may be having. If [Volunteer name] _is_ making contact with their youth, please ensure they update their volunteer portal to reflect time spent with their youth.

– [`casa_org` `display_name`]

**Comment by TecnoSigma** [comment]
Hi,

I'm solving this problem.

Can you assign issue to me?

Tks!

**Comment by jmkoni** [comment]
@TecnoSigma did you finish #952? we'd generally prefer not to assign a single person multiple issues at a time.

**Comment by TecnoSigma** [comment]
No problems.

Tks!

**Comment by compwron** [comment]
#952 is merged
All yours @TecnoSigma :)

**Comment by compwron** [comment]
@TecnoSigma How is it going? :)

**Comment by TecnoSigma** [comment]
Hi.

Sorry,

I working in other project.

tks! :slightly_smiling_face:

**Comment by Zrrrpy** [comment]
putting this on hold now that this same information is covered by the supervisors weekly digest email.

This may be built out later if we want to increase email volume to supervisors OR as an SMS notification down the line.

**Comment by compwron** [comment]
closing for now because we don't feel the need for it
