### ISSUE TITLE
Add to Calendar Button Attempting to Add Event on Wrong Date

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3093]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
When I click the Add to Calendar button and attempt to add a court date to my calendar it tries to set the date to the day prior to the court date spanning to the day two days prior to the court date. (Note: It is 8:57pm Pacific Time on my computer)
![Funky Calendar Date](https://user-images.githubusercontent.com/7007647/148883989-4640c90a-4794-4296-861d-33c9e7f9b21a.PNG)

### Expected Behavior
When I click the Add to Calendar button, the calendar entry should be for the date of the Court Date in question, and not attempting to span backwards through time. 

### How to Replicate
ex: 
1. - Log into qa as a volunteer.
2. - Click on "My Cases" in the left sidebar menu.
3. - Select a case by clicking on the case number
4. - Click "Add to Calendar" button next to Next Court Date.

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by CovenantHuman** [comment]
@aedwardg I remember you were working on this. Do you have context to look into this issue?

**Comment by aedwardg** [comment]
Sure, I'll take a look and see whats going wrong here 🙂
