### ISSUE TITLE
Disable interactive form elements when there are no eligible volunteers for assignment

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3111]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Disable the dropdown and the assign volunteer button

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/149629678-9631cc71-0933-4066-bf02-7688d2bf2198.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
It's not a good pattern for easily confused users to hide components, it leads to "where did it go?" type questions.

**Comment by soc-man** [comment]
hello, i'd like to work on this
