### ISSUE TITLE
Create partial for Manage Volunteers section 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3112]
Create partial for Manage Volunteers section 
So we can get re-use and DRY code
![image (2)](https://user-images.githubusercontent.com/578159/149632389-6fd061e0-35fc-4b9a-bff9-7c1b6b5b74af.png)
![image (1)](https://user-images.githubusercontent.com/578159/149632391-d035b3ff-4234-4f3d-8497-c9a04e6c99ed.png)

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mattwd7** [comment]
I'll grab this 👍
