### ISSUE TITLE
Remove checkbox for no longer used field TAY on Case Edit

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3117]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Remove checkbox for no longer used field TAY on Case Edit

**Screenshots of current behavior, if any**  
![image (3)](https://user-images.githubusercontent.com/578159/149818205-8e77817e-e12f-45c5-9e25-9d0b7f46ce75.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by efgalvao** [comment]
@compwron , I think this Issue is completed.

**Comment by CovenantHuman** [comment]
This has been done.
