### ISSUE TITLE
Change Reimbursement Queue Date Added Column to Date Attempted

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3124]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Currently in the reimbursement queue there is a column for Date Added, which tells the admin the date that the case contact was added to the system. We would like to change this column to Date Attempted letting the admin know the date that the contact in question was attempted. 

**Screenshots of current behavior, if any**  
![Reimbursement Queue](https://user-images.githubusercontent.com/7007647/149840926-6b96623f-6f04-47f9-ae60-5da794eb48ac.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
FD asked again today

**Comment by spotswoodb** [comment]
Asking to claim this issue
