### ISSUE TITLE
Auto Update Docker Build

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3144]
**Description**
Create a github action to keep the docker image up to date when the code changes

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by HeitorMC** [comment]
Hello There :wave:
I would like to be assign for this issue

**Comment by FireLemons** [comment]
@HeitorMC sorry this issue is moot since we've added testing on the docker image to CI
