### ISSUE TITLE
Change format of court report to include medium_type 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3148]
(requested by Jocie from Howard on 21 Jan 2022)

**What we want and why:**
Howard County CASA wants to change their court report format to include the medium type of each contact (see attached doc to see what this looks like in practice). Don't worry about changing fonts or spacing to exactly match the mockup- the mock-up is just that, so there's no need to change fonts or anything like that to bring things into parity with the mock-up, just add the necessary code to sort the contact dates by medium type and label the medium types.

Microsoft Word might be a necessity to work on this issue- you just need LibreOffice or OpenOffice or Google Docs and "download as docx" - you will need ms word to insert mailmerge fields https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates

**Acceptance criteria:**
1. Create Court Report template that can be uploaded (or run locally) to fill in the new template with case contact data
2. Write a data backfill like: find Howard, add docx (from checked in file)

Howard wants a Court Report Format that produces something that looks approximately like this: 
[Report to the Court.docx](https://github.com/rubyforgood/casa/files/8422640/Report.to.the.Court.docx)
Or in screenshot form this:
![Court Report Mock-Up](https://user-images.githubusercontent.com/7007647/161873384-8f97a93a-2639-4b71-943e-ceaa4febe713.png)

**Comment by compwron** [comment]
See existing documents checked into the repo for the format you need to add the `<<` sections - maybe edit the existing document instead of making a new one from scratch / from the attached demo

**Comment by FireLemons** [comment]
Those `<<` sections are mail merge fields and you might need ms word to add those  
https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates
