### ISSUE TITLE
Add tests for controllers

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3161]
Add tests for controller files- see https://github.com/rubyforgood/casa/blob/main/spec/controllers/dashboard_controller_spec.rb as an example

See the file `.allow_skipping_tests` as a list of untested files (including controllers)

**Comment by m-pereira** [comment]
Hello @compwron, I wonder why do we need to test the controllers once we have `request` tests? I didn't find the `.allow_skipping_tests` file 😢

**Comment by compwron** [comment]
Closing in favor of smaller issues
