### ISSUE TITLE
Indicate Last Time Contact Was Made For Each Contact Type

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3171]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when looking at the case contact form, users get no feedback about the last time contacts of each type were made. We would like to change that. 

Specifically, we would like to indicate when the last contact of each specific type was made for each particular case. It is important that this is tied to the case rather than the volunteer as multiple volunteers can work on the same case, and in those cases we want the last contact made by anyone on the case to show not just by the person currently looking at the case contact form.

It should be visually noticeable, but not confusing to the volunteers. 

We would like it the amount of time elapsed since the last contact to be indicated as a number of days no matter how high the number of days is, and if the last contact  of a type was made never it should simply say 'Never'. 

Contacts that have been attempted within the last 14 days should have the number of days since last contact displayed in green, whereas contacts that haven't happened in more than 14 days should be some different, readable color that is not green. 

A link to a new case contact form in QA is here: https://casa-qa.herokuapp.com/case_contacts/new?case_contact%5Bcasa_case_id%5D=2468 To log in use the email `volunteer1@example.com` and the password 12345678.

**Screenshots of current behavior, if any**  
<img width="1615" alt="casa-vol" src="https://user-images.githubusercontent.com/7007647/151913004-24f49116-319b-4adf-a7e6-227eabf8ef40.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by m-pereira** [comment]
I would like to try this one

**Comment by m-pereira** [comment]
Hi @CovenantHuman, I have a question: If I am right, the `case_contact` form can be used to create contacts for more than one `casa_case` at once, right? Which one should be used to build the feedback about the last time contacts?

I think we will pollute the screen showing the `last time contact` for each `casa_case` in each `case_contact type`

![image](https://user-images.githubusercontent.com/47258878/152023573-081ea5e1-7447-469a-bb03-fed69ff0f394.png)

**Comment by compwron** [comment]
>  the case_contact form can be used to create contacts for more than one casa_case at once, right? 
Right

> Which one should be used to build the feedback about the last time contacts?
*Usually* it won't matter because if a volunteer has two cases, those cases are almost always siblings. Please pick the most recent for *either* of the volunteer's cases (show only one result)

**Comment by compwron** [comment]
By the way @m-pereira I don't know if you're in the slack already but if you want to be just put your email here https://rubyforgood.herokuapp.com/ and we will approve you. Slack is useful for getting question responses faster but you don't need it if you don't want it :) 
If you *are* for slack, I'm sorry that I couldn't find you! Post in #casa to say hi? :)

**Comment by m-pereira** [comment]
> By the way @m-pereira I don't know if you're in the slack already but if you want to be just put your email here https://rubyforgood.herokuapp.com/ and we will approve you. Slack is useful for getting question responses faster but you don't need it if you don't want it :) If you _are_ in slack already, I'm sorry that I couldn't find you! Post in #casa to say hi? :)

not yet, just sent my email to be invited :D

**Comment by FireLemons** [comment]
Maybe orange

See https://materializecss.com/color.html for colors that contrast with black and white

**Comment by compwron** [comment]
Some code thoughts
```
cc = CasaCase.last
contact_type = ContactType.last
cc.case_contacts.where(contact_made: true).order(:created_at).last.created_at
# contact_type: contact_type,
CaseContactContactType.includes(:case_contact, :contact_type).where("case_contacts.casa_case_id": cc.id, contact_type_id: contact_type.id)
contact_type = CaseContactContactType.last.contact_type
CaseContactContactType.includes(:case_contact, :contact_type).where("case_contacts.casa_case_id": cc.id)
CaseContactContactType.includes(:case_contact, :contact_type).where(contact_type_id: contact_type.id)
CaseContactContactType.where("case_contacts.casa_case_id": cc.id,

CaseContactContactType.includes(:case_contact, :contact_type).where("case_contacts.casa_case_id": cc.id, contact_type_id: contact_type.id)
CaseContactContactType.includes(:case_contact, :contact_type).where("case_contacts.casa_case_id": cc.id).map(&:contact_type), contact_type_id: contact_type.id)


CaseContactContactType.includes(:case_contact, :contact_type).where("case_contacts.casa_case_id": cc.id, "contact_type.id": contact_type.id)

```
