### ISSUE TITLE
Font Size Changes Depending On Whether Login Email Is Being Typed Or Selected

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3173]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
When I type in my Email the font is large, but if I select my email from the provided list of suggested logins then the font is small. 
This has been observed on Chrome on Mac and Chrome on Windows. 
![Font Size Large](https://user-images.githubusercontent.com/7007647/151914032-fe16b167-ee93-43e8-ac9d-242950cf4666.png)
![Font Size Small](https://user-images.githubusercontent.com/7007647/151914041-dd7b42e5-848f-4a19-8e6c-35ed5f24fe6f.png)

### Expected Behavior
We want the font to stay the same regardless of whether the input is being typed or selected. 

### How to Replicate

1. - Log into qa as a volunteer.
2. Log out.
3. Attempt to login again, but this time select the suggested email from the list that pops up when you begin typing in your browser. 

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by aedwardg** [comment]
From what I can tell, there is currently no fix for this issue.
See the comments on this SO thread for details:
https://stackoverflow.com/questions/56026043/how-to-prevent-chrome-from-changing-font-when-autofilling-username-password

**Comment by littleforest** [comment]
Closing as not a priority
