### ISSUE TITLE
Case Contacts Suggest Tomorrow as Date of Contact After Midnight GMT

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3174]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production, staging, QA, probably local? unconfirmed on local yet

### Current Behavior
When I try to make a case contact for the current day after 5pm Pacific Time, the default date offered is for the next day and I can save the case contact as having occurred the next day. See the difference between my system date and time and the date of the most recently saved case contact in the provided screenshot below.
![Datetime Error on Case Contact Creation](https://user-images.githubusercontent.com/7007647/151915179-3f990c31-9244-440e-bc84-832cb23be286.png)

### Expected Behavior
It should not be possible to make a case contact for a date in the future, nor should the suggested date on the case contact form be in the future. 

### How to Replicate
1. - Log into qa as a volunteer after midnight GMT.
2. - Select a Case by clicking on its Case Number.
3. - Press the New Case Contact Button at the top of the page.
4. - Check the date that the Case Contact Form is suggesting.

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by arthur1041** [comment]
I can work on a solution for this issue.

**Comment by compwron** [comment]
@arthur1041 thanks! :)
