### ISSUE TITLE
part 2? Update court_report_due_date when a new court_date is added

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3184]
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1644162749155199?thread_ts=1644024624.258029&cid=CVB0QJGVD
[Shen Yang](https://app.slack.com/team/U01CSSSCFD2)  [15 hours ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1644162723952119?thread_ts=1644024624.258029&cid=CVB0QJGVD)
Checked [Update court_report_due_date when a new court_date is added](https://github.com/rubyforgood/casa/pull/3142)

[Shen Yang](https://app.slack.com/team/U01CSSSCFD2)  [15 hours ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1644162749155199?thread_ts=1644024624.258029&cid=CVB0QJGVD)[](https://files.slack.com/files-pri/T04PM108C-F031ED219EK/image.png)[](https://files.slack.com/files-pri/T04PM108C-F031ED219EK/download/image.png)
It always overrides this value
image.png 
image.png

[Shen Yang](https://app.slack.com/team/U01CSSSCFD2)  [15 hours ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1644162766921329?thread_ts=1644024624.258029&cid=CVB0QJGVD)
maybe we should remove the field

[Shen Yang](https://app.slack.com/team/U01CSSSCFD2)  [15 hours ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1644162808039909?thread_ts=1644024624.258029&cid=CVB0QJGVD)
Sometimes it's autmatically set in the past if the court date is in the near future

**Comment by compwron** [comment]
TODO @compwron figure out if this is still valid?

**Comment by littleforest** [comment]
Closing. Can recreate new ticket with better description if needed in the future.
