### ISSUE TITLE
Add a Court Date to New CASA Cases on Creation

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3188]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Currently when creating a new CASA Case there is no way to add a court date. We would like to change this. We would like to add a date-picker for a Court Date below the dropdown for selecting a Judge and above the Court Report Due Date. 

**Screenshots of current behavior, if any**  
![New CASA Case ](https://user-images.githubusercontent.com/7007647/152918351-28eb9ed1-9127-4c1f-a3c3-cd195f3595ed.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by NickSchimek** [comment]
I can tackle this.

**Comment by NickSchimek** [comment]
It looks like there are two places for the concept of a `court_date` to be persisted to the database.

The `court_date` field on the `casa_cases` table, and the `court_dates` table.


Where should this `court_date` be persisted? Should a new `court_dates` record be created, or should the casa_cases `court_date` field be populated?

**Comment by compwron** [comment]
@NickSchimek a new court_dates record should be created. We are working to deprecate the casa_cases court_date field. 😅
