### ISSUE TITLE
Use Date Picker To Set Court Report Due Date on New CASA Case Page

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3189]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Currently when creating a new CASA Case we are setting the Court Report Due Date using three drop downs (Day, Month, Year). We would like to change this to a calendar based date picker like that used for setting the Court Date on the New Court Date Page. 
Like what was done here: https://github.com/rubyforgood/casa/issues/2932 , but for Court Report Due Date on the new CASA Case page. 

**Screenshots of current behavior, if any**  
Current New CASA Case page: 
![New CASA Case ](https://user-images.githubusercontent.com/7007647/152919354-47d91956-440f-42e6-b48f-df7569bed8ba.png)

Desired Date Picker Format: 
![New Court Date DatePicker](https://user-images.githubusercontent.com/7007647/152919409-0e2abd32-d4ba-4e0c-a0de-f30d6679e8b4.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
Resolved by https://github.com/rubyforgood/casa/pull/3210
