### ISSUE TITLE
Use Date Picker To Set Court Report Due Date on Edit Case Details

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3190]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when creating a Edit Case Details page we are setting the Court Report Due Date using three drop downs (Day, Month, Year). We would like to change this to a calendar based date picker like that used for setting the Court Date on the New Court Date Page. 
Like what was done here: https://github.com/rubyforgood/casa/issues/2932 , but for Court Report Due Date on the Edit Case Details page. 

**Screenshots of current behavior, if any**  
Current Edit Case Details Page: 
![Edit Case Details Page](https://user-images.githubusercontent.com/7007647/152919810-27ab5aa4-d55a-410f-81e3-40ee421e93c5.png)

Desired Date Picker Format: 
![New Court Date DatePicker](https://user-images.githubusercontent.com/7007647/152919409-0e2abd32-d4ba-4e0c-a0de-f30d6679e8b4.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
![Screen Shot 2022-03-08 at 6 30 35 PM](https://user-images.githubusercontent.com/578159/157361030-ab0b15b5-5a7c-423b-a47c-b5d880f8a9fd.png)
This looks done
