### ISSUE TITLE
Admin view - volunteers

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#32]
Relates to #4 
Volunteer -
  Index view of volunteer names and case number (like: `Donald Duck - 12345`), in order of newest volunteer on top. Should link to a [volunteer edit view/popup-type box](https://github.com/rubyforgood/casa/issues/5).
  New Volunteer button on top.

**Comment by leesharma** [comment]
In the case of one volunteer having multiple cases, do you want one row per case (with duplicate volunteer entries) or one row per volunteer (with multiple cases per row)?
