### ISSUE TITLE
Delete Saved Case Contact Notes at Time of Successful Submission

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3206]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently we are keeping note text in Case Contacts past the successful entry of that Case Contact into our system. We would like to change this so that the note text is only saved until such a time as we are showing the user the pop-up that thanks them for their service, and indicates a successful submission of a Case Contact. To be specific, when we show that pop-up we want to delete the saved note text at the same time. 

**Screenshots of current behavior, if any**  
Here is a previously made Case Contact:
![Note on Past Case Contact](https://user-images.githubusercontent.com/7007647/153658690-31aeea93-116b-4256-bc5e-4a95ae2766b9.png)

Here are its notes appearing on a new Case Contact:
![Persisting Past Save](https://user-images.githubusercontent.com/7007647/153658745-1d49bf23-2932-4ed8-9d11-4b7f069b68c5.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by librod89** [comment]
I can not reproduce this. Can anyone else try?

**Comment by dvsconcept1986** [comment]
I would like to work on this.

**Comment by dpaola2** [comment]
I think this has been fixed, there is a linked merged PR. Closing unless @compwron or @CovenantHuman can reproduce
