### ISSUE TITLE
Improve Speed of CasaCasesController#show

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3214]
**Description**
Improve speed of CasaCasesController#show 
<img width="1666" alt="Screen Shot 2022-02-04 at 11 36 37 AM" src="https://user-images.githubusercontent.com/7007647/153992827-6032bacc-e3d1-4c9a-9330-0171d20644f4.png">
![Screen Shot 2022-02-14 at 8 30 35 PM](https://user-images.githubusercontent.com/7007647/153993054-bd2e82f7-8632-4ff1-a890-e2e3db8d6a7a.png)

**Existing gem(s), file(s) needing updating, changing or deleting**
CasaCasesController
**New file(s) needing creating**
None
### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by r-sierra** [comment]
I´ll work on this.
