### ISSUE TITLE
Let Supervisors and Admins Delete Future Court Dates

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3215]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently there is no way for anyone to delete a court date. We would like to make it so that Supervisors and Admins can delete future court dates. We would like to make it so that on the screen that appears when one selects a Court Date from the Edit Case Details Screen (see screenshot below), there is a big red button under the currently existing box of information that says "Delete Future Court Date". 

**Screenshots of current behavior, if any**  
![Future Court Date Without Delete Option](https://user-images.githubusercontent.com/7007647/153993953-b6c93ea6-3a1f-441f-8023-f7a0288c6bd7.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by NickSchimek** [comment]
I'd like to tackle this this weekend.
