### ISSUE TITLE
Make Past Court Reports Like Present Court Reports

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3216]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 
## Description
Currently when downloading a court report there are actually two very different documents that might be generated. We only want to keep one of these document formats. Everywhere that there is currently a report being generated with the template: ```default_past_court_date_template.docx``` we want to replace with a court report based on the appropriate default report template (i.e. default in cases that aren't specified and CASA specific templates where which CASA is specified and a specific template exists). 
We want these reports to populate with the appropriate case contacts for the period in question. Essentially, we want court reports that look like someone downloaded a court report the day before the court report due date for any given past court date.  

 court report templates are set at the casa org level

## Screenshots of current behavior, if any
The document template we are trying to eliminate: 
![Past Court Date Default Template](https://user-images.githubusercontent.com/7007647/153995494-585036ad-471f-4d37-980e-8e044dc2d9eb.png)

## QA Login Details
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by elhalvers** [comment]
I would like to work on this! : )

**Comment by elhalvers** [comment]
I have 'assign myself' privileges but not sure if that is a preferred protocol : )

**Comment by dpaola2** [comment]
Steps to reproduce:

1. Log in as volunteer1@example.com
2. Click on "My cases"
3. click on CINA-03-1004
4. Click on "February 17, 2023" under "Court Dates" to download broken report
5. click on "Generate report" button or "Attached report" next to the court date to generate & download correct report


The link that generates the broken report (that we want replaced with the other one):

![Screenshot 2023-04-19 at 4 35 19 PM](https://user-images.githubusercontent.com/150509/233194223-86966c69-e350-4139-8d31-b97b19665bcf.png)

These buttons generate the correct report:

![Screenshot 2023-04-19 at 4 31 05 PM](https://user-images.githubusercontent.com/150509/233194214-c225e278-825b-4a0d-b9be-08a5c506e569.png)

**Comment by elhalvers** [comment]
I have started working on this issue but have been delayed on another issue. I should be finishing that one soon and then will resume this one.

**Comment by danaguilar** [comment]
I'll start working on this

**Comment by danaguilar** [comment]
Sorry, couldn't work on this last week. I'm about done though

**Comment by danaguilar** [comment]
I had some confusion about what this issue was asking for. I assumed the default court report was the report we wanted to use for everyone. In actuality court report templates are set at the casa org level. I have two questions now

1) Can I assume that these custom court report templates are using data the same way the current (old) court date report is? ie, If I passed these custom reports a param that included `court_date`, would they show the court date correctly?

2) Should the default court report be updated to make use of data found in court date? Currently if I were to pass `court_date` to the default report, that date would not show up on the report? Should this be updated or should we assume that no one should be using the default template in the first place?

**Comment by compwron** [comment]
1. yes
2. in general, the default template is more of a fallback
