### ISSUE TITLE
deprecate casa_case.court_date and wholly use court_dates table instead

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3226]
It looks like there are two places for the concept of a court_date to be persisted to the database.

The court_date field on the casa_cases table, and the court_dates table.

Where should this court_date be persisted? Should a new court_dates record be created, or should the casa_cases court_date field be populated?

**Comment by mattwd7** [comment]
I'll move on this

**Comment by compwron** [comment]
Great! :)
