### ISSUE TITLE
erb spec translation check

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3230]
add this to every erb spec
`expect(rendered).not_to have_css("span.translation_missing")`

**Comment by amygurski** [comment]
👋 Would you consider turning on the config in `test.rb` to fail tests on missing translations instead? https://github.com/rubyforgood/casa/blob/main/config/environments/test.rb#L53-L54 
If this sounds like an option, feel free to assign this to me and I'll look into it.

**Comment by compwron** [comment]
Yes, that would be cool! Will do
