### ISSUE TITLE
Prince George's Fund Application Form

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3235]
**What type(s) of user does this feature affect?**
non logged in users and stakeholder AM

**Description**
SB: targeted PG opportnities fund
gnerate applications for fund, email to add marie
a fillable form, send the form, “a hell of the time for the form to work for everyone” same doc, can’t fill it.
adobe document, reader.
new form that looks the same, questions,
pay-ee, other resuorces, rewuested…
SB; needs anme of kid and we dont do that… case cina number onlu
or vol name and AM can figure out kid
form goes to other parites also
volunteers in activity tracker could go there and submit it
lawyers submit the form too, dont have access to…
anyone can request funds… anyone in foster care not just casa youth
AM: no face to allowing lawyers in if they’re limited to that part of the sytem, a link send to them, here’s how to fill out the form…
if coming from outside casa, do ned the name because AM cant figure out, dont have access to all cina numbers
AM doesnt have access to cina if were not the case, no centralized case to look up cina numbers that thye ahave access to
“there will be someday” a place cina numbers lookup
cant get into “effec yet”
SB: 400 ish kids in care, PG handles 180 of them, dunno anything about them
and they send the forms to AM even if the kids arent in foster youth
donor wanted fund to live somewhere so its with casa “do it quickly wo beuaracracy, aoperatined by dept of social services, takesn months…”
AM can turn it around in an adg=ernnt
fund paid for braces, summer camp, …
some kid studio time for music
AM: reunification plane ticket

**Comment by compwron** [comment]
working on v2 in my brain

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/pull/3237

**Comment by compwron** [comment]
working on itttt

**Comment by littleforest** [comment]
@compwron I am closing this since looks like there is a merged PR in #3355
