### ISSUE TITLE
Create and Edit Pages for the Other Duties Table and Buttons Linking to Those Pages

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3256]
Contingent on https://github.com/rubyforgood/casa/issues/3255 being finished. 

**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Currently we have no way for volunteers to add new data to the "other_duties" table. We would like to create a "Record New Duty" page and accompanying "Edit Duty" page. These pages should have:
- a field labelled "Occurred at" which uses an interactive calendar drop down to allow a date to be set (like the one used in the new case contact page)
- a pair of sliders labelled "Duration" (extract and reuse a partial from the case contacts page) 
- a field labelled "Notes" (again this should be the same as the notes field on the case contact form).

The Edit Page should prepopulate with all the data already in the database for the appropriate Duty. 

Also there should be a button next to the title of Other Duties which is labelled "Create New Duty", which takes users to the Create New Duty page, and a column in the Other Duties table with a link labelled "Edit" which takes uses to the Edit Page for the appropriate Duty. 

**Screenshots of current behavior, if any**  
![Other Duties Area ](https://user-images.githubusercontent.com/7007647/157355586-d08df3a7-14c5-415b-b667-c280c13e5acd.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mattwd7** [comment]
I'll take this!

**Comment by mattwd7** [comment]
> a pair of sliders labelled "Duration" (extract and reuse a partial from the case contacts page)

I'm not seeing any duration sliders on the case contacts page. Instead, I see 2 numeric inputs (see screenshot below). What is ultimately expected here?

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2025059/158506282-f0709bf2-9f67-4368-88fd-7ff94a25d874.png">

**Comment by compwron** [comment]
@mattwd7 they used to be sliders! Just reuse the Duration of Meeting code as it is now :)

**Comment by iraline** [comment]
I can work on it. =)
