### ISSUE TITLE
Add Lines Separating Volunteers in Supervisor's Weekly Digest & Add Fake Data to Sample Email for Better Testing 

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3269]
**What type(s) of user does this feature affect?**
 - supervisors
 
**Description**
Currently the supervisor weekly digest email contains a lot of information with very little structure. We would like to add a line between each volunteer's information in the supervisor weekly digest email. Also we currently don't have a good way to look at what these emails look like outside of production. So we would like to add a bunch of fake data to the sample email at: https://casa-qa.herokuapp.com/rails/mailers/supervisor_mailer/weekly_digest to make testing changes to the weekly email layout more reasonable. 

**Screenshots of current behavior, if any**  
Fill in information to the sample to see what the email looks like when populated: https://casa-qa.herokuapp.com/rails/mailers/supervisor_mailer/weekly_digest

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by efgalvao** [comment]
@CovenantHuman and @compwron . I have a question, in the mail "view", there are some queries which choose content based on the date. I am creating a special supervisor to the mailer preview with the expected content, but after a week the weekly digest will have no content for this supervisor again.
How do you suggest to me approach the issue to accomplish the task?

**Comment by compwron** [comment]
> I have a question, in the mail "view", there are some queries which choose content based on the date. I am creating a special supervisor to the mailer preview with the expected content, but after a week the weekly digest will have no content for this supervisor again.

Don't create it in the database, just use `.build` in the mailer preview and then the data will always be fresh :)

**Comment by compwron** [comment]
```
# Preview all emails at http://localhost:3000/rails/mailers/supervisor_mailer
# :nocov:
class SupervisorMailerPreview < ActionMailer::Preview
  def account_setup
    supervisor = params.has_key?(:id) ? Supervisor.find_by(id: params[:id]) : Supervisor.last
    SupervisorMailer.account_setup(supervisor)
  end

  def weekly_digest
    supervisor = params.has_key?(:id) ? Supervisor.find_by(id: params[:id]) : Supervisor.last
    SupervisorMailer.weekly_digest(supervisor)
  end
end
# :nocov:

```

**Comment by codewithjulie** [comment]
Still working on it!

**Comment by codewithjulie** [comment]
Thanks team - we got the lines figured out! What do you think of this? 

(I also moved the name out so it's above and only once..thoughts?)

![Screen Shot 2022-09-13 at 8 39 53 PM](https://user-images.githubusercontent.com/70556962/190054262-d0267af6-25fa-4d17-a768-3f4e28959e65.png)

@compwron @FireLemons @cjilbert504

**Comment by FireLemons** [comment]
Could you make the "Summary for X" a bigger font size?

**Comment by codewithjulie** [comment]
@FireLemons 
<img width="524" alt="Screen Shot 2022-09-14 at 9 14 33 PM" src="https://user-images.githubusercontent.com/70556962/190312729-5d79dece-2f73-42fe-8ef4-dbb82a067edc.png">

**Comment by FireLemons** [comment]
I don't think we need to add sample data
