### ISSUE TITLE
Make Prince George's PDF filler login usable + fill info

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3275]
-PDF link button, Remove Youth Name, For in system link: make it possible to attach other information, for logged-in users Fostering Opportunities Fund Application on left nav bar by Emancipation Checklist, choose a case and default to neither

**Comment by littleforest** [comment]
@compwron do we still need this?

**Comment by compwron** [comment]
![Image](https://github.com/rubyforgood/casa/assets/578159/4b1b2fca-929b-4147-82d5-5df2dd871ed1)

not coherent enough to do
