### ISSUE TITLE
Make court date field required when creating a new casa case

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3277]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
The "Next Court Date" field can be left blank before submitting the form. Add the required attribute to the field so that it must be filled out before submitting the form. 

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/157374231-bde0b667-0cf1-4747-ad22-136fdcb2b1d2.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by joaoguiIherme** [comment]
Hi, i would like to claim this issue.
