### ISSUE TITLE
Upgrade to rails 7

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3283]
**Description**
Upgrade the rails version of casa from 6.1.4.6 to at least rails 7  
Ensure all tests pass and the website works locally

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jhund** [comment]
I just released Filterrific 5.2.3 with support for Rails 7
