### ISSUE TITLE
[bug] supervisor can see wrong case?

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3286]
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1647101732510999?thread_ts=1647048624.092779&cid=CVB0QJGVD
> A supervisor can see cases from a different org

**Comment by FireLemons** [comment]
Is it limited to supervisors?

**Comment by FireLemons** [comment]
![image](https://user-images.githubusercontent.com/8918762/158042856-ec682d19-9d3a-4143-b3dd-c3e9a729050e.png)
Admins can also do it

**Comment by compwron** [comment]
Yep apparently also. :/ We will fix that at the same time...
