### ISSUE TITLE
Add Date in Care to Case Details

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3294]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently we have no way for users to track a youth's date in care (i.e. when a youth entered the foster care system). We would like to add Date in Care as a piece of information tracked on the Case Details page. This information should be displayed below "Transition Aged Youth", and should display a date in care, followed by duration in care in parentheses. Duration in care should be measured in months, with one decimal digit (i.e. 1.5 months or 0.2 months etc.) up to twelve months at which point duration should be listed as years and months (i.e. 1 year and 2.7 months or 17 years and 1 month etc.) It should be visible to Volunteers, Supervisors and Admins, but only editable by Supervisors and Admins. 

**Screenshots of current behavior, if any**  
Current Case Details Page: 
![Current Case Details Page](https://user-images.githubusercontent.com/7007647/158495835-95c93f92-7eb9-478b-ba54-660409252130.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by metamoni** [comment]
@CovenantHuman where do I find the youth's date in care? Is it the same as the CASA case's creation date?

**Comment by CovenantHuman** [comment]
We don't currently have any date in care information. This will be adding a way for users to give us that information to the site.

**Comment by Craggar** [comment]
I'll take a look at this one @metamoni
