### ISSUE TITLE
Fix Permissions Issues

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3315]
**Description**

Users should not be able to edit outside of their own org. 

Related to:
https://github.com/rubyforgood/casa/pull/3300
https://github.com/rubyforgood/casa/pull/3298
![Supervisor Seeing Supervisor from Another Org](https://user-images.githubusercontent.com/7007647/159599697-42549473-9d63-41f0-bce7-6f2baed6a7ea.png)
![Admin Seeing Admin from Another Org](https://user-images.githubusercontent.com/7007647/159599711-f9ceec17-d2b5-467b-be1b-8956ea7eea9d.png)

**Existing gem(s), file(s) needing updating, changing or deleting**

**New file(s) needing creating**

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by MrJackStone** [comment]
Hey! Me and my team would like to work on this one!

**Comment by compwron** [comment]
Go for it :)
