### ISSUE TITLE
Make Notes on Volunteers Editable

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3316]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, Supervisors and Admins can make notes on Volunteers, but those notes cannot be edited. We would like to add an edit button and the ability to edit Notes. Notes on Volunteers can be found on the Editing Volunteer page when logged in as a Supervisor or Admin. 

**Screenshots of current behavior, if any**  
![Current State of Notes on Volunteer](https://user-images.githubusercontent.com/7007647/159600495-a186a9ba-378a-4879-8d62-202b668a0752.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by rhian-cs** [comment]
Hello, I will be working on this issue.
