### ISSUE TITLE
Table overflow styling fix

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3323]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
desktop browser

### Current Behavior
when the window is not wide enough, some tables overflow past their parent div
tables include the casa case table and the volunteers table
![image](https://user-images.githubusercontent.com/8918762/160319084-8e55109d-b3f0-4ec9-82c2-1a691de0c60d.png)
![image](https://user-images.githubusercontent.com/8918762/160319123-806893cf-eeed-4e9c-b1b5-6938d4c33eb6.png)

### Expected Behavior
the white background should always be behind the table. It's ok for the table to scroll if it's too wide

### How to Replicate
ex: 
1. - Log into QA as an admin
2. - Click the casa cases tab or the volunteers tab in the sidebar
3. - Shrink the width of the widow if the bug is not already visible

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by amygurski** [comment]
I can work on this one.
