### ISSUE TITLE
Add Case Number to Filename When Downloading Emancipation Checklist

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3332]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when downloading the Emancipation Checklist for a case, the filename does not include any information about which case the checklist is associated with. We would like the case number to be included in the filename in the format "CaseNumber Emancipation Checklist" (i.e. CINA-13-1002 Emancipation Checklist). 

**Screenshots of current behavior, if any**  
Current Filename for a Downloaded Emancipation Checklist visible here: 
![Emancipation Checklist Download](https://user-images.githubusercontent.com/7007647/161335418-8277974a-0b6c-4ac9-aabc-a62db5889129.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
<img width="1642" alt="Screen Shot 2022-05-03 at 6 35 03 PM" src="https://user-images.githubusercontent.com/578159/166612348-67a6b3b6-4124-4566-b550-1fe113847fcc.png">

**Comment by compwron** [comment]
```
        <%= link_to "Download Checklist", casa_case_emancipation_path(@current_case, format: :docx),
class: "btn btn-primary" %>
```

**Comment by compwron** [comment]
@marie-blue :)

**Comment by compwron** [comment]
https://stackoverflow.com/questions/617055/setting-the-filename-for-a-downloaded-file-in-a-rails-application
