### ISSUE TITLE
Multi-case volunteer New Case Contact default should be both cases

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3334]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
I have two cases in the same family and often the case contacts need to have both case numbers tagged. After I have put in a contact and it takes me back to the list of all case contacts, if I select New Case Contact there, I am only given a form with one of the two case numbers whether or not the contact I just entered included both case numbers. If I select "Case Contacts" on the side bar, then THAT new case contact button gives me both. It's frustrating when I am entering several contacts in a row, as is often the case.

**Screenshots of current behavior, if any**  
https://casa-qa.herokuapp.com/case_contacts/new logged in as volunteer2
<img width="1037" alt="Screen Shot 2022-04-01 at 11 11 23 PM" src="https://user-images.githubusercontent.com/578159/161369431-cb3fc94a-f906-49e3-90b8-652742f10135.png">
<img width="1656" alt="Screen Shot 2022-04-01 at 11 11 15 PM" src="https://user-images.githubusercontent.com/578159/161369432-c3c80fb7-3974-42cd-9de1-211386a4cece.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ErinClaudio** [comment]
@compwron 
Hello, a couple of questions.
_if I select New Case Contact there, I am only given a form with one of the two case numbers whether or not the contact I just entered included both case numbers._ 

1.  Am I on the correct track?

- When I click `New Case Contact` after creating a New Case Contact, I should see both case numbers listed. 

- Versus having to click on `Case Contacts` and then click  the case itself 

<img width="1072" alt="Screen Shot 2022-05-12 at 4 16 56 PM" src="https://user-images.githubusercontent.com/20326770/168160741-4ebf50b1-b86a-41a5-b23e-61fc28d7f8b4.png">

**Comment by compwron** [comment]
@ErinClaudio yep! :)

**Comment by ErinClaudio** [comment]
Thank you!

**Comment by ErinClaudio** [comment]
Can I have this issue back, or should I switch to something else @compwron / @FireLemons ? Sorry for the delay

**Comment by ChaelCodes** [comment]
Hey! I'd like to work on this one.

**Comment by ChaelCodes** [comment]
How do I create two cases in the same family?

**Comment by FireLemons** [comment]
> How do I create two cases in the same family?

We don't keep track of families. This would just be 2 cases

**Comment by ChaelCodes** [comment]
Hey, you requested that we default to selecting all, but this will be really painful for volunteers with multiple cases, because they have to unselect a bunch. I think the user is upset that they're redirected to the case page, because from there you can't select multiple cases, just the one from the case page.

I offered up two other PRs that I think will fix the issue in a nicer way.
1. Redirect to case contacts if there's more than one instead of a case page. This circumvents the limits on the new form.
2. Change the limit on cases from the case page to default to the case selected instead of removing the other options.

I built 3, so you can close the ones you don't want and merge the ones you do.
