### ISSUE TITLE
Let Supervisors and Admins Hide Case Contacts Made by Previous Volunteers on a Case

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3338]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a case is unassigned from one volunteer and assigned to a new volunteer, the new volunteer can see case contacts made by the old volunteer. We would like supervisors and admins to be able to choose whether new volunteers see old volunteers case contacts. Specifically, we would like to add a action to the Manage Volunteers Table for= volunteers with the status 'Unassigned' or 'Deactivated Volunteer', which is labeled "Hide Case Contacts" and will hide case contacts made by that volunteer from other volunteers assigned to the case. 

**Screenshots of current behavior, if any**  
New Volunteer seeing Old Case Contacts: 
![New Volunteer Sees Old Volunteers Case Contacts](https://user-images.githubusercontent.com/7007647/161664674-d4edd618-4732-415d-9516-9dd82b03284c.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by arthur1041** [comment]
I can work on this issue.
