### ISSUE TITLE
Remove duplicate tests in views

### ISSUE THREAD

**Issue by xihai01** [rubyforgood/casa#3344]
**Description**
_spec -> views -> volunteers -> edit.html.erb_spec.rb_ contains two identical tests with contradicting labels. See below screenshot. I think maybe one of them should be removed?
![Screenshot from 2022-04-05 21-55-39](https://user-images.githubusercontent.com/86758440/161989553-ba56582d-a47a-455c-9b6c-b56fcad3f64b.png)

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by HeitorMC** [comment]
Hello there! :tada:  I would like to be assign for this issue :smile:

**Comment by xihai01** [comment]
I've assigned you this issue @HeitorMC

**Comment by HeitorMC** [comment]
Hey @xihai01! Just finished this PR! Could you take a look at it?

Thank you in advance :smile:
