### ISSUE TITLE
Show contact type names in casa case change text

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3368]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Show contact type names instead of ids on casa case changes summary text after editing a casa case 

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/163088405-96f917d5-b539-4ab4-8ff1-c6e1e2c70081.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by gasperno** [comment]
Hey,

I would like to work on this @FireLemons.
