### ISSUE TITLE
Fix delete button wrapping on some case contacts on a casa case page

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3369]
### Impacted User Types
 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

### Current Behavior
![image](https://user-images.githubusercontent.com/8918762/163089211-e7c11bfa-939c-4365-ac1d-779859b1f20c.png)

### Expected Behavior
The delete button should be on the same line as the other buttons
![image](https://user-images.githubusercontent.com/8918762/163089296-32540b08-7ebc-4fb2-a023-cee4bdec2271.png)

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by apolimax** [comment]
Hey, can I try this one?

**Comment by xihai01** [comment]
> Hello there, can I try this one?

yes, have fun!
