### ISSUE TITLE
Speed up Reimbursement Queue Load Time

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3377]
**Description**
Currently the Reimbursement Queue takes a long time to load. Speeding it up would really improve the experience of using that feature. 
**Existing gem(s), file(s) needing updating, changing or deleting**

**New file(s) needing creating**

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by r-sierra** [comment]
Hi there! I would like to work on this.

**Comment by compwron** [comment]
@r-sierra go for it! :)
