### ISSUE TITLE
Bug with importing bootstrap

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/casa#339]
**What is the problem, and what should happen instead?**

Locally, my browser (Firefox) gives me this error in the console (`Cannot find module 'bootstrap'`). Tables are not paginating.

**Screenshots of current behavior, if any**
<img width="394" alt="Screenshot_6_14_20__1_32_PM" src="https://user-images.githubusercontent.com/10481391/84599911-88d62980-ae43-11ea-8b4e-debf1ac18713.png">

**Comment by compwron** [comment]
Not able to replicate

**Comment by compwron** [comment]
![Screen Shot 2020-06-21 at 1 45 56 PM](https://user-images.githubusercontent.com/578159/85234881-97818b00-b3c5-11ea-89f6-028b2106b941.png)
