### ISSUE TITLE
Code to Help Interpolate Word Docs

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3395]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Write this where you interpolate word docs so that we can maybe use it someday.

```persons_interviewed = [pi1, pi2]
persons_interviewed.iterate(pi)
pi.relationships # object to iterate over
relationship = pi1.each(relationship)
relationship.contact_type # "Phone" (bols in merge)
relationship.dates # string "11/11*, 12/7"
```

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by littleforest** [comment]
closing as not a priority
