### ISSUE TITLE
Format volunteer import data

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#34]
Revise .csv formatting to ensure it's compatible with how data should display on the backend post import. 

Will do once this is ready to release to CASA.

Related to epic #59

**Comment by Zrrrpy** [comment]
@Thrillberg or @compwron any idea where sample data lives currently so I can link here? (and if it lives nowhere yet, can you edit description/title above to "create" sample data?

**Comment by Thrillberg** [comment]
Yep! Seed data can be found in the project here: `db/seeds.rb`

Two commands are useful for running them:
- `rails db:seed` - runs the file, adding the data to your local database
- `rails db:seed:replant` - resets your database with the seed data

A note on completing this issue:
There is some subjectivity on what would be "complete" for this issue but probably having more examples of each data type, with different attributes would be a great start!

**Comment by compwron** [comment]
Because this is not currently being worked on, I want to move it out of the "in progress" column. I will leave it assigned to @Zrrrpy for now :)

**Comment by compwron** [comment]
This is done
