### ISSUE TITLE
Make Notes on Volunteers Delete-able

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3405]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, Supervisors and Admins can make and edit notes on Volunteers, but those notes cannot be deleted. We would like to add a delete button and the ability to delete Notes. Notes on Volunteers can be found on the Editing Volunteer page when logged in as a Supervisor or Admin.

**Screenshots of current behavior, if any**  
![Current Volunteer Note State](https://user-images.githubusercontent.com/7007647/166408120-ce5672aa-2f6f-4c8e-bd31-16f3b23f527d.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by iraline** [comment]
I can work on this fix. =)

**Comment by compwron** [comment]
@iraline go for it!
