### ISSUE TITLE
Make Contact Medium UI identical in different views

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#341]
**What is the problem, and what should happen instead?**
On the left in the screenshot "Voice Only" and on the right is "📞 voice-only" and we want them both to be "📞 Voice Only" and ideally use the same decorator method to do it. 

**Screenshots of current behavior, if any**
![Screen Shot 2020-06-14 at 11 20 55 AM](https://user-images.githubusercontent.com/578159/84600875-60ddca80-ae31-11ea-9f8c-139e54e74e5c.png)

**Comment by eclectic-coding** [comment]
I briefly looked to this PR. It looks like the the case detail for volunteer 1 is displaying `voice-only`, not as the above screenshot indicates. Has this already been fixed? 
Also, there is no current seed data for an admin to verify right side of screenshot above. Please advise. 

![Screenshot from 2020-07-19 19-34-17](https://user-images.githubusercontent.com/13651291/87887894-0bc84200-c9f7-11ea-9cc3-01e4695ddc1a.png)

**Comment by Zrrrpy** [comment]
@eclectic-coding looks like this has indeed been fixed already unless there are instances where it's still occurring that I'm not aware of. @compwron do you know of any or are we good to close out?

**Comment by compwron** [comment]
I think we're done then! :)
