### ISSUE TITLE
Let the Export Data page filter by case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3419]
**What type(s) of user does this feature affect?**

 - supervisors
 - admins

**Description**
Reported by Montgomery volunteer

> When I click Export Data, and fill in the information (4/1/22-5/5/22, for volunteer [volunteer name]- no other specifics ore restrictions in the other boxes) and ask for the report, it only gives me two entries from 5/5/22 entered by the volunteer.  I entered several contacts myself for the case for that timeframe, but the entries I inputted (for the given date parameters) are not showing up.  How do I get my entries for the case to show up on the report too?

**Screenshots of current behavior, if any**  
<img width="620" alt="Screen Shot 2022-05-10 at 5 29 53 PM" src="https://user-images.githubusercontent.com/578159/167745626-af44f08a-928d-4c7e-ae72-55b590d9836b.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by marmitoTH** [comment]
I'm working on it! 👍
