### ISSUE TITLE
Fix judges not seeding locally

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3423]
**Description**
Add test judges to be crated on seeing

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by creaturenex** [comment]
hello

**Comment by FireLemons** [comment]
@creaturenex update someone tried this earlier and it looks like the feature is not working https://github.com/rubyforgood/casa/commit/d124de1f5f2f798e72933b571dcdfd8949c0b057

**Comment by FireLemons** [comment]
not working for local only

**Comment by isaacm** [comment]
I've added a pull request to resolve the issue.

**Comment by creaturenex** [comment]
Hey Issac, next time do you mind just message the person who issue is assigned to if they are working on it? I didn't get a chance to work on this before you submitted the pull request.
