### ISSUE TITLE
Railsconf 7: update t() in app/views/casa_cases/_court_dates.html.erb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3445]
Thank you for coming to our workshop!

To complete this issue:
1. open `app/views/casa_cases/_court_dates.html.erb`
1. find each call of `t(STRING)`
1. look up `STRING` in `config/locales/views.en.yml`
    1. the YAML file is nested, first with the language (always `en` here), then the view name, then the action name
    1. so for your `STRING`, look under `en:` then `_court_dates.html.erb:` then `:` and then `STRING:`
    1. if you need any help figuring the view or action name to look up the translation with, please ask a workshop helper
1. replace the usage of `t(` with the translation you found in `config/locales/views.en.yml`

This will simplify our templates and make it easier to maintain the code going forward.

Example:

```
Before:
<span><%= t(".title") %></span>

In config/locales/views.en.yml:
en:
  _court_dates.html.erb:
    :
      title: Hello world

After:
<span>Hello world</span>
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by hogrammer** [comment]
Grabbing this one!
