### ISSUE TITLE
[BUG] If a volunteer has no name, you can't get to their profile

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#349]
**What is the problem, and what should happen instead?**
If a volunteer has no name, you can't get to their profile
If a volunteer has no name, show 'No Name' instead and make that a link to the volunteer edit page

**Screenshots of current behavior, if any**
![Screen Shot 2020-06-14 at 1 48 55 PM](https://user-images.githubusercontent.com/578159/84603784-f6835500-ae45-11ea-9604-c5ac2cb55de3.png)

**Comment by littleforest** [comment]
Already fixed:

```
<%= link_to(volunteer.decorate.name, edit_volunteer_path(volunteer)) %>
```

```
  def name
    return object.email if object.display_name.blank?

    object.display_name
  end
```
