### ISSUE TITLE
Validate no miles driven recorded for non-driving case contact types

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#355]
If a volunteer tries to save a case contact with miles_driven more than 0 for any contact type other than in_person, show a little pop-up asking if they're sure (but let them do it- don't disallow the save if they click that they're sure)

<img width="506" alt="Screen Shot 2020-06-14 at 4 19 49 PM" src="https://user-images.githubusercontent.com/578159/84606420-e45fe180-ae5a-11ea-9149-c99ee725d1a1.png">

**Comment by renatamarques97** [comment]
@compwron could you tell me which file this form is located? because I couldn't find it.

**Comment by compwron** [comment]
@renatamarques97 This is in `casa/app/views/case_contacts/_form.html.erb`
Thanks for taking a look! We are very happy to have you looking at CASA :) ✨
