### ISSUE TITLE
Make other duties' notes field required

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3558]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
On the cases page, as a volunteer
![image](https://user-images.githubusercontent.com/8918762/170159695-b0125f5c-cbfa-4438-a7b7-a46ab64e37e2.png)  
  
make the notes field of other duties form [required](https://www.w3schools.com/tags/att_input_required.asp)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mussajoop** [comment]
Hi there 👋🏾, I'd like to work on that issue
