### ISSUE TITLE
Truncate or make more human readable date string identifying which case contact was edited

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3559]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
After a case contact is edited on a casa case page, text identifying which one is displayed.  
Make the text more human readable.  

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/170166151-842e7d7f-4a29-4fe7-aa85-9857694f49a7.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Krikcet** [comment]
I'd like to give this a shot. Should be able to complete it within the next few days.
