### ISSUE TITLE
Highlight Button Opens Checklist Modal 

### ISSUE THREAD

**Issue by sasatterlee** [rubyforgood/casa#3567]
## What type(s) of user does this feature affect?
 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

## Description
This depends on - https://github.com/rubyforgood/casa/issues/3566
When the 'Highlight' button is selected checklist pops up with the different highlight options.   The user makes a selection and saves to close the modal. If the case contact is not saved the highlight is erased as well. If the case contact is saved then the use has the ability to click the highlight and view the modal again. 

Checklist Content:
<For volunteers - Objective Information>

Where is the child placed?
How is the child adjusting to the placement?
Are there any issues or concerns at this point in time at the placement?
If so, what are they and who is doing what to address those issues or concerns?

**ADD ALL CONTENT**

## Screenshots of current behavior, if any
You can paste images on the clipboard here

<img width="813" alt="Screen Shot 2022-05-26 at 7 33 02 PM" src="https://user-images.githubusercontent.com/82993198/170596530-80384f56-0671-42a5-978e-bcbe56017177.png">

## QA Login Details
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by GALTdea** [comment]
I'd like to give it a try!

 just a couple clarifying questions? 
1. WIll the checklist items be added as new fields in the case_contacts table?
or a new Highlight object that belonging to CaseContac? 

Thank you!

**Comment by littleforest** [comment]
@bcastillo32 @compwron I think this was the ticket that JH wanted at our last stakeholder's meeting. Maybe we can resurrect and figure out more details soon?

**Comment by bcastillo32** [comment]
> @bcastillo32 @compwron I think this was the ticket that JH wanted at our last stakeholder's meeting. Maybe we can resurrect and figure out more details soon?

Yeah, it would be good to learn more about this ask. we can find some time to chat about it for sure

**Comment by MalloryPriceDesign** [comment]
I've been designing a new feature within the New Case Contact page that captures this data. I'll be sharing with the team shortly, but just wanted to make sure no redundant work was done on this in the meantime.

**Comment by compwron** [comment]
related to court report topics

![Image](https://github.com/rubyforgood/casa/assets/578159/d20b8bd5-020a-4002-8936-e7df8042664c)

**Comment by elasticspoon** [comment]
https://github.com/rubyforgood/casa/pull/5517
