### ISSUE TITLE
Admin Edits the Default Court Report Checklist 

### ISSUE THREAD

**Issue by sasatterlee** [rubyforgood/casa#3568]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Add a column to hearing types under edit organization that is called 'Report Checklist'. When edit is pressed users have ability to make changes to the default checklist. There are three criteria per checklist item - description, category and whether it's mandatory. 

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
<img width="820" alt="Screen Shot 2022-05-26 at 7 43 26 PM" src="https://user-images.githubusercontent.com/82993198/170600722-f1416a7b-ff35-4751-a356-5336a31832c1.png">
 
<img width="839" alt="Screen Shot 2022-05-26 at 7 43 33 PM" src="https://user-images.githubusercontent.com/82993198/170600680-25411610-f541-4417-972d-4e8ea8628f25.png">

[Link to QA site](https://casa-qa.herokuapp.com/) 
Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues. Make it work like a standard rails edit page even if it differs from mockup.

**Comment by Learningstuff98** [comment]
@compwron Can I work on this?

**Comment by compwron** [comment]
@Learningstuff98 go for it!

**Comment by Learningstuff98** [comment]
@compwron Do you guys want edit and delete functionality for these checklist items? Here's are some screenshots of what I have so far:

![Screenshot (510)](https://user-images.githubusercontent.com/42154066/173473136-4208de46-db94-4929-ad00-be148940e36a.png)

![Screenshot (511)](https://user-images.githubusercontent.com/42154066/173473469-a039f777-1773-49a4-9092-8f8855f183a8.png)

![Screenshot (512)](https://user-images.githubusercontent.com/42154066/173473845-f4fd4033-35a3-4024-b227-129fd8033ef7.png)

**Comment by compwron** [comment]
@[Learningstuff98](https://github.com/Learningstuff98) yes edit and delete would be great, in a later PR is ok tho!

**Comment by Learningstuff98** [comment]
@compwron Ok, I just implemented edit functionality so I'll add delete functionality next.

**Comment by Learningstuff98** [comment]
@compwron I have some questions. The mockup shows the checklist items being paginated, but I couldn't find any gems in the gemfile for pagination. Would it be ok if I use the [kaminari gem](https://github.com/kaminari/kaminari)? Also where are the checklist items going to be visible for non admin users? Once I know then I can update the views accordingly.

**Comment by compwron** [comment]
@[Learningstuff98](https://github.com/Learningstuff98) it's ok to leave out pagination for now
kaminari is good but let's not do it yet. 
The checklist items will eventually be visible on a new section of the create case contact page but don't do that work in this PR- PRs should be fairly small.
