### ISSUE TITLE
Flaky local tests

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3584]
> Hi, I finally got my local environment setup for running and developing casa.  I was able to build the application and run it without too much trouble.  However, I am having a strange issue with the tests.  I am getting inconsistent results, even when using the same random seed.  For example, when using "bin/rspec spec --seed 33262" I have gotten three different results, 0 failures, 3 failures, and 2 failures respectively.  Has anyone else experienced something similar?
> Here is a pastebin showing the results of several tests - 3 with the same seed and a couple more with different seeds: https://pastebin.com/APjtgLys.  Which tests fail depends on the seed somewhat. More extensive testing would need to be done to better understand it.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Luke-kb** [comment]
Can this issue be closed?
