### ISSUE TITLE
Alphabetize CINA numbers in "assign volunteer to case" for easier assignment

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#359]
Double check the admin *and* supervisor views have this
![Screen Shot 2020-06-15 at 6 22 33 PM](https://user-images.githubusercontent.com/578159/84721316-41c86100-af35-11ea-8173-89f7c3965b62.png)

**Comment by renatamarques97** [comment]
could you explain better?

**Comment by compwron** [comment]
@renatamarques97 Hi! Sorry about the confusion, this issue was super unclear! In addition, it was fixed already and this issue wasn't closed. Sorry about that 😓

This issue was on the edit volunteer page, like https://casa-r4g-staging.herokuapp.com/volunteers/702/edit
