### ISSUE TITLE
Add phone number field to create supervisor and volunteer page

### ISSUE THREAD

**Issue by xihai01** [rubyforgood/casa#3609]
**What type(s) of user does this feature affect?**
 - volunteer registration
 - supervisor registration

**Description**
Currently, when an admin creates a volunteer or supervisor account, only the display name and email is required to be filled. However, we should also add another field for phone numbers (optional field). This is because SMS notifications are being rolled out and we want to send an SMS to the new user telling them about their new account (see #1784 )

**Screenshots of current behavior, if any**  
![phone](https://user-images.githubusercontent.com/86758440/171771446-41eb30a7-1085-4f7f-b5b1-09c4b8188eb3.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Thekote** [comment]
Hey @HeitorMC and @xihai01 I can try this one!

**Comment by xihai01** [comment]
No problem. Have fun!

**Comment by Thekote** [comment]
hey @xihai01 i've added the new field locally, but i'm not sure how should the phone number be stored and formatted, can you shed me some light?

**Comment by xihai01** [comment]
@Thekote No need to worry about adding the phone number field to the db. This and the validations for the phone number field has already been done in an earlier issue/pr: #3375 

The phone number format is "+(area code)" + "10 digits"
Ex. +13217897098
So in this example, +1 is the area code for the US and the rest are the actual digits of the phone number.
Area code is needed because our SMS provider (Twilio) needs it

**Comment by Thekote** [comment]
Hey @xihai01 I've just opened a PR for this issue (#3625) but there are some CI/CD tests failing... Could you take a look please?

**Comment by compwron** [comment]
@Thekote Please fix the failing tests :)
