### ISSUE TITLE
Volunteer can be unassigned from Supervisor by any supervisor or admin

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#362]
Add an "unassign" button

![Screen Shot 2020-06-16 at 10 36 15 PM](https://user-images.githubusercontent.com/578159/84859349-d1e3d480-b021-11ea-8511-6290e9f31960.png)

**Comment by cliftonmcintosh** [comment]
> Add an "unassign" button

in each volunteer's row in the "Assigned Volunteers" list?

**Comment by compwron** [comment]
@cliftonmcintosh Yes that is perfect :)

**Comment by cliftonmcintosh** [comment]
I'm having trouble finding the view where someone can edit a supervisor! When I'm logged in as "casa_admin1@example.com", the dashboard shows "Volunteers" and "Cases". What am I missing?

![admin-dashboard](https://user-images.githubusercontent.com/3824492/86542656-34234d00-bedd-11ea-8e5f-2144f40d89c6.png)

**Comment by Zrrrpy** [comment]
Go ahead and click on any of the supervisors listed in that first volunteer table under the column, "Supervisor." That will take you to the edit supervisor page for that particular supervisor.

**Comment by cliftonmcintosh** [comment]
My fork was out of date.

**Comment by Zrrrpy** [comment]
And [there is an issue open for creating a supervisor view on the admin dashboard](https://github.com/rubyforgood/casa/issues/360) (just like there is for volunteers and cases). It's in progress but hasn't been touched in a bit, open if you'd like to take a look!

**Comment by Zrrrpy** [comment]
PS @cliftonmcintosh just gave you write access.

**Comment by cliftonmcintosh** [comment]
Thanks. I am working on this.
