### ISSUE TITLE
datepicker CSS load is broken

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#363]
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1592275905314900

datepicker seems broken, probably something in webpacker/yarn(?) GET https://casa-r4g-staging.herokuapp.com/assets/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css net::ERR_ABORTED 404 (Not Found)

<img width="346" alt="Screen Shot 2020-06-15 at 7 51 32 PM (1)" src="https://user-images.githubusercontent.com/578159/84865497-29d40880-b02d-11ea-97ac-7d688a122d12.png">

**Comment by renatamarques97** [comment]
I don't see any problem with datepicker locally
![Screen Shot 2020-06-20 at 19 51 20](https://user-images.githubusercontent.com/25162312/85213043-956ced00-b32f-11ea-9de3-4576b10780b9.png)

Can you tell me the environment of this bug? (local, staging or production)

Also, there is no error in:
https://casa-r4g-staging.herokuapp.com/assets/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css 

![Screen Shot 2020-06-20 at 19 52 37](https://user-images.githubusercontent.com/25162312/85213069-dcf37900-b32f-11ea-9ede-58327a4ef55a.png)

**Comment by compwron** [comment]
Hi! You have correctly replicated the bug locally and in production. The datepicker is missing itits css, and the css is showing an error (like in your screenshot above) instead of existing. https://casa-r4g-staging.herokuapp.com/  https://bootstrap-datepicker.readthedocs.io/

![Screen Shot 2020-06-20 at 10 01 58 PM](https://user-images.githubusercontent.com/578159/85217156-91969600-b342-11ea-9bd0-e0af8ef610ad.png)

![Screen Shot 2020-06-20 at 10 04 01 PM](https://user-images.githubusercontent.com/578159/85217112-087f5f00-b342-11ea-961c-bc1a98bf0b51.png)
