### ISSUE TITLE
SMS Notification event selection not disabled when notifications are turned off

### ISSUE THREAD

**Issue by harsohailB** [rubyforgood/casa#3661]
### Impacted User Types
 - volunteers
 - supervisors
 - admins
 - all casa admins

### Environment

* All

### Current Behavior

* On the edit profile page, the text notification events are not disabled if "Text me" is not pressed

<img width="710" alt="Screen Shot 2022-06-20 at 6 08 28 PM" src="https://user-images.githubusercontent.com/47438886/174695607-3225edcf-673c-4522-8ea4-9454f2a91751.png">

### Expected Behavior

* If "text me" is not checked, the notification event selection boxes should be disabled

### How to Replicate
ex: 
1. - Log in with any user
2. - Click on "Edit profile"
3. - Uncheck "Text me"

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by xihai01** [comment]
"ex: When I click "generate report", a downloadable report should be generated."

Is this related to the issue?

**Comment by compwron** [comment]
@xihai01 no, it just looks like someone didn't clean up the github issue template for this issue.

**Comment by harsohailB** [comment]
@xihai01 Accidentally left that in. Added the correct sentence now.
