### ISSUE TITLE
Fix and Test Assignment Status on the Edit Volunteer Page

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3665]
### Impacted User Types
 - supervisors
 - admins

### Environment
Production

### Current Behavior
When I unassign a volunteer from their only current case, their case history disappears (see screenshots)
Before Unassigning the Case:
![Manage Cases Before](https://user-images.githubusercontent.com/7007647/174919225-a4ca3cc0-ab69-424e-93ca-b730d7ae8698.png)

After Unassigning the Case:
![Manage Cases After](https://user-images.githubusercontent.com/7007647/174919284-f12c358b-1872-40b3-a2af-1a26b6aa534f.png)

Also, there have been cases when a case is listed as both active and unassigned at the same time (see screenshot). This should not be possible.
![image (6)](https://user-images.githubusercontent.com/7007647/174919998-ed93f56c-6907-49e5-a3b2-0534b9cbf05d.png)

### Expected Behavior
Even when unassigned from all cases, a volunteer's case history should still show in the manage cases section of the volunteer edit page.

### How to Replicate
ex: 
1. - Log into qa as an admin or supervisor.
2. - Pick a volunteer from the Volunteers tab and go to their edit volunteer page.
3. - Unassign the volunteer from all cases.
4. - Go back to that volunteer's edit volunteer page. 

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by thejwuscript** [comment]
Hi, I'd like to work on this issue.

**Comment by CovenantHuman** [comment]
Yes, unassigned cases should appear in the Manage Cases section.
