### ISSUE TITLE
Fix problem where running migrations changes db ids from integer to bigint and back

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3668]
Fix problem where running migrations changes db ids from integer to bigint and back

They should be bigint

The problem seems to be the difference between `rake db:drop db:create db:migrate` and `rake db:setup`

**Comment by andreLumor** [comment]
Hi! Is this still happening? I couldn't reproduce the error.

**Comment by mussajoop** [comment]
Hi, yes it's still happening. For me, for example, when I run `rake db:migrate` some ids change from bigint to integer

**Comment by compwron** [comment]
The problem seems to be the difference between rake db:drop db:create db:migrate and rake db:setup :/

**Comment by johncarlocerna** [comment]
This is a known bug that has been addressed in Rails: https://github.com/rails/rails/issues/45093
If you're having this issue locally, you have to drop your database locally and recreate it.
