### ISSUE TITLE
Add test for channels/application_cable/connection.rb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3671]
Thank you for working on CASA!

To complete this issue:
1. open `channels/application_cable/connection.rb`
1. make a new test file: `spec/channels/speclication_cable/connection_spec.rb`
1. add at least one test for the functionality in channels/application_cable/connection.rb!
1. remove the line channels/application_cable/connection.rb from `.allow_skipping_tests`

This will improve our test coverage and make our code safer to modify and easier to understand.

Example:

```
Before:
require "rails_helper"

RSpec.describe Connection do
  it "adds the numbers" do
    expect(described_class.new(1, 1)).to eq(2)
  end
end
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by rinonb** [comment]
Anybody working on this? If not, happy to take this!

**Comment by compwron** [comment]
@rinonb  Go for it! :)

**Comment by ycorredius** [comment]
@rinonb Are you still working on this issue? If not, I would love to look into it

**Comment by compwron** [comment]
@Luke-kb go for it! :)

**Comment by FireLemons** [comment]
Action cable is not being used so it does not require testing
