### ISSUE TITLE
Add test for controllers/all_casa_admins/sessions_controller.rb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3675]
Thank you for working on CASA!

To complete this issue:
1. open `controllers/all_casa_admins/sessions_controller.rb`
1. make a new test file: `spec/controllers/all_casa_admins/sessions_controller_spec.rb`
1. add at least one test for the functionality in controllers/all_casa_admins/sessions_controller.rb!
1. remove the line controllers/all_casa_admins/sessions_controller.rb from `.allow_skipping_tests`

This will improve our test coverage and make our code safer to modify and easier to understand.

Example:

```
Before:
require "rails_helper"

RSpec.describe SessionsController do
  it "adds the numbers" do
    expect(described_class.new(1, 1)).to eq(2)
  end
end
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hello there, can I try to solve this?

**Comment by compwron** [comment]
@tonyaraujop go for it! :)

**Comment by tonyaraujop** [comment]
@compwron I was looking the `sessions_controller` and it appears that there no action at all...is that right?

```rb
# frozen_string_literal: true

class AllCasaAdmins::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
end
```

I found the routes, but it seems that it only implements Devise actions...

**Comment by compwron** [comment]
Yes that seems accurate. 
You can write just a small test that the devise action/s are present, we don't need to test the whole of devise, they have their own tests :) 
Basically the test should fail if you take out the `< Devise::SessionsController` or the `include Accessible` or the `skip_before_action :check_user, only: :destroy` lines :)

**Comment by compwron** [comment]
You can also pick a different ticket if you prefer :)
