### ISSUE TITLE
Add test for controllers/application_controller.rb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3678]
Thank you for working on CASA!

To complete this issue:
1. open `controllers/application_controller.rb`
1. make a new test file: `spec/controllers/spec/application_controller_spec`
1. add at least one test for the functionality in controllers/application_controller.rb!
1. remove the line controllers/application_controller.rb from `.allow_skipping_tests`

This will improve our test coverage and make our code safer to modify and easier to understand.

Example:

```
Before:
require "rails_helper"

RSpec.describe ApplicationController do
  it "adds the numbers" do
    expect(described_class.new(1, 1)).to eq(2)
  end
end
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mussajoop** [comment]
I'd like to work on that issue :)

**Comment by mussajoop** [comment]
Hi,
when you wrote: "2. make a new test file: `spec/controllers/speclication_controller_spec.rb`", 
`speclication_controller_spec` is a misspelling right? don't you mean `application_controller_spec.rb`??

**Comment by compwron** [comment]
Correct, that is a misspelling. Sorry about that

**Comment by mussajoop** [comment]
> Correct, that is a misspelling. Sorry about that

no problem :)
