### ISSUE TITLE
Add test for controllers/concerns/organizational.rb

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3688]
Thank you for working on CASA!

To complete this issue:
1. open `controllers/concerns/organizational.rb`
1. make a new test file: `spec/controllers/concerns/organizational_spec.rb`
1. add at least one test for the functionality in controllers/concerns/organizational.rb!
1. remove the line controllers/concerns/organizational.rb from `.allow_skipping_tests`

This will improve our test coverage and make our code safer to modify and easier to understand.

Example:

```
Before:
require "rails_helper"

RSpec.describe Organizational do
  it "adds the numbers" do
    expect(described_class.new(1, 1)).to eq(2)
  end
end
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by arthur1041** [comment]
I can work on this issue.

**Comment by arthur1041** [comment]
@compwron  should I create the test file inside `controllers/concerns/` or `spec/controllers/concerns/` ?
