### ISSUE TITLE
Fix Montgomery court report letterhead to include their logo

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3698]
[Letterhead Template II.docx](https://github.com/rubyforgood/casa/files/8979226/Letterhead.Template.II.docx)
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Write an after_party data modification task to replace the court report template for montgomery to be the same as currently but with this attached letterhead. 

This will require using microsoft office probably

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
@CovenantHuman we may need your Word magic for this 😓

**Comment by CovenantHuman** [comment]
Sure thing! Do we want the letterhead on every page or just the first page?

**Comment by CovenantHuman** [comment]
Here is the version with letterhead just on the first page. :)
[Montgomery_Report_Template_with_Letterhead.docx](https://github.com/rubyforgood/casa/files/8981650/Montgomery_Report_Template_with_Letterhead.docx)

**Comment by compwron** [comment]
this will run using `bundle exec rake after_party:run` command to generate a new rake task: https://github.com/theSteveMitchell/after_party
