### ISSUE TITLE
Make required field required for Create New CASA Org - Name

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3716]
**What type(s) of user does this feature affect?**
admins

**Description**
Create New CASA Org: Name
This code will be similar to https://github.com/rubyforgood/casa/pull/3713

Url:  https://casa-qa.herokuapp.com/all_casa_admins/casa_orgs

docs:  [required](https://www.w3schools.com/tags/att_input_required.asp)

login from here: https://casa-qa.herokuapp.com/all_casa_admins/sign_in

**Screenshots of current behavior, if any**  

<img width="1081" alt="Screen Shot 2022-06-28 at 7 11 11 PM" src="https://user-images.githubusercontent.com/578159/176336062-ed4218fb-dce3-46e0-9a70-c6261e196816.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by chetan104522** [comment]
This is done or not ?
