### ISSUE TITLE
[BUG] Volunteer assigned to supervisor does not appear in dashboard volunteers list

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#374]
**What is the problem, and what should happen instead?**
Admin user change the name of active volunteer `volunteer1@example.com` from nothing (empty) to `Kay Ulstrēd` and their name shows up attached to a case but does NOT show up in the list of volunteers (and it should) 

**Screenshots of current behavior, if any**
<img width="1440" alt="Screen Shot 2020-06-21 at 2 05 50 PM" src="https://user-images.githubusercontent.com/578159/85235312-d9f89700-b3c8-11ea-90d5-53b08a6d2439.png">

<img width="1440" alt="Screen Shot 2020-06-21 at 2 05 50 PM" src="https://user-images.githubusercontent.com/578159/85235428-96525d00-b3c9-11ea-9d1f-896d1a2b8479.png">

**Comment by compwron** [comment]
Something weird is happening here- I'm not sure that the bug is exactly as described. I am taking my name off of this for now because I am not currently looking at it, but I think we should look into this more before launch.

**Comment by alindeman** [comment]
I'll try to reproduce this and see what I come up with.
