### ISSUE TITLE
Remove Submit button on Supervisor Edit Supervisor page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#377]
**What type of user is this for? volunteer/supervisor/admin/all**
Supervisor

**Description**
Log in as a supervisor and go to the "edit" page of another supervisor. Because there are no editable fields controlled by the Submit button, the button should be removed. 

**Screenshots of current behavior, if any**
<img width="1284" alt="Screen Shot 2020-06-21 at 2 58 14 PM" src="https://user-images.githubusercontent.com/578159/85236108-aff6a300-b3cf-11ea-9653-04ad67f54aee.png">

**Comment by cjilbert504** [comment]
Does this submit button need to completely just be removed or should it just not be visible to users who do not have permissions to edit supervisor info?

**Comment by compwron** [comment]
Just not visible is fine

**Comment by cjilbert504** [comment]
I just looked at issue #378 which I think answered my question, but to confirm it seems as the desired behavior is for the button to only be visible to authorized users, no?

**Comment by cjilbert504** [comment]
Copy that, thanks!

**Comment by compwron** [comment]
@cjilbert504 are you looking at this one?

**Comment by cjilbert504** [comment]
@compwron I don't think I'm going to have the time at the moment. I have a lot going on with school at the moment that I need to get together first. I'm sorry, I should have more time soon though.

**Comment by compwron** [comment]
@cjilbert504 No worries! You rock. :) Come back anytime ✨💖  You're going to rock school 💪🚀

**Comment by cjilbert504** [comment]
Thanks! I only have two months left but as soon as it's over I plan to come back and contribute full force.
