### ISSUE TITLE
Change default value of No Supervisor filter on Volunteers page to True to prevent confusion after import

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3779]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
a bug/weird for us to file and fix
 When they were not matched to a supervisor, I could not sear for them by name.
The default filter was non-obvious and then the import failed instead of attaching the volunteer to the supervisor (might be a data error? look into it)

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here
![Screen Shot 2022-07-26 at 6 37 19 PM](https://user-images.githubusercontent.com/578159/181141584-42aab509-25fe-4d03-aec4-3ccc81011b30.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ChaelCodes** [comment]
The PR associated with this was closed as completed. Should this issue be closed too?
