### ISSUE TITLE
Supervisor should be able to edit their own email&name from the edit supervisor page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#378]
**What type of user is this for? volunteer/supervisor/admin/all**
supervisor

**Description**
Supervisor should be able to edit their **own** email&name from the edit supervisor page

**Screenshots of current behavior, if any**
<img width="1276" alt="Screen Shot 2020-06-21 at 2 58 24 PM" src="https://user-images.githubusercontent.com/578159/85236134-e6ccb900-b3cf-11ea-8593-0691598e2e9a.png">

**Comment by cliftonmcintosh** [comment]
@compwron This is addressed in #416. I saw this while addressing #377 and thought it made sense to make the update for both together.

**Comment by cliftonmcintosh** [comment]
I will assign this to myself and move it into In Progress.
