### ISSUE TITLE
Show a message on the other duties page if there are no duties to display.

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3785]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
When there are no "other duties" to display on the other duties page, display a message informing the user that there are no duties to display.

Write a test

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/181147658-115921fe-d599-47e5-9fe5-29327d3f86b3.png)
![image](https://user-images.githubusercontent.com/8918762/181147718-2d74abd5-49c6-4c61-943a-cf497b826b27.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by JeffMorhous** [comment]
I can work on this! (I think this is how we claim issues?)

**Comment by rinonb** [comment]
Looks like this is still open for grabs? Looking for something to contribute to!

**Comment by compwron** [comment]
@rinonb go for it! :)

**Comment by compwron** [comment]
@rinonb this one is assigned to @JeffMorhous try picking another :)

**Comment by compwron** [comment]
I am wrong, this ticket is not done yet and not assigned. @rinonb it's all yours if you want it :)

**Comment by JeffMorhous** [comment]
Sorry for the late response, this was completed in #3800 - it was requested that we write a test for a follow-up which we're working on.

Is it my responsibility to close the issue?

**Comment by FireLemons** [comment]
Actually it doesn't seem to be working

**Comment by JeffMorhous** [comment]
@FireLemons , good catch! We've dug in and found the source of the bug. We are actively working on a fix and will create a PR that also has tests. Thanks, and sorry about that!

CC: @ericlombardo
