### ISSUE TITLE
Add test for "inbox_label" function of app/helpers/sidebar_helper.rb

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3786]
**Description**
Add a test in `spec/helpers/sidebar_helper_spec.rb` for the function `inbox_label` found in `app/helpers/sidebar_helper.rb`

See: https://github.com/rubyforgood/casa/blob/main/app/helpers/sidebar_helper.rb
See: https://github.com/rubyforgood/casa/blob/main/spec/helpers/sidebar_helper_spec.rb

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by leevic31** [comment]
I can work on this
