### ISSUE TITLE
Front end design

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#38]
All work pertaining to how stuff looks on the front end! Will touch work on epics #3 & #4 

<u>Priorities</u>
- make things look nicer (without complicating functionality)
- ensure CASA brand & style are applied to all front end elements
- modular css style guide that can be applied across site. [Example of some modular css for Ruby can be found here.](https://blog.engineyard.com/front-end-maintainability-with-sass-and-style-guides)

<u>Not priority, but would be nice if you wanna make it happen!</u>
- light graphic design as needed that makes navigation easy and intuitive and on brand.

Open issues related to this epic: #8 #46

**Comment by Zrrrpy** [comment]
[color&font.pdf](https://github.com/rubyforgood/casa/files/4430593/color.font.pdf)
^^ html color codes and font families here

**Comment by compwron** [comment]
Keep in mind that this is intended to be a multi-tenant system and the different tenants will have different color schemes and logo images. So it would be nice to support that :)

**Comment by Zrrrpy** [comment]
All CASAs have the same color scheme thankfully! and the logo (child holding heart with no text) is also the same
