### ISSUE TITLE
Creating a footer

### ISSUE THREAD

**Issue by charuta-kulkarni** [rubyforgood/casa#3804]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins
 - all casa admins (Unknown)

**Description**
To add a footer to include links to 'report a site issue', 'terms and conditions, 'Ruby for Good', and 'c CASA/Volunteer Tracking'. The intent is to simplify the existing left navigation bar. 

Font Spec:
font-family: 'Montserrat';
font-style: normal;
font-weight: 400;
font-size: 14px;
line-height: 140%;
/* identical to box height, or 20px */
color: #2E2E2E;

Base rectangle Spec:
position: absolute;
width: 1032px;
height: 40px;
left: 0px;
top: 0px;
background: #F8F8F8;
box-shadow: 0px -2px 12px rgba(0, 0, 0, 0.25);

**Screenshots of current behavior, if any**  
<img width="963" alt="image" src="https://user-images.githubusercontent.com/103174148/184289222-4a1d37ac-5592-4292-b848-8c43416168c4.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view the site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by grazirs** [comment]
Hi @compwron! Can I get this issue?
