### ISSUE TITLE
Allow supervisors to "delete" notes like admins currently can

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3835]
**What type(s) of user does this feature affect?**
 - supervisors

**Description**
Allow supervisors to "delete" notes like admins currently can

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here
![Screen Shot 2022-08-12 at 11 23 18 AM](https://user-images.githubusercontent.com/578159/184420599-38f15b4e-30dd-468d-9e63-79f4cb974a29.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
Not working in staging
![image](https://user-images.githubusercontent.com/8918762/185773945-cf563885-1578-4774-8629-5ed71091e5aa.png)

**Comment by jacobherrington** [comment]
@FireLemons I just took a peak at this feature in the staging environment using the `supervisor1@...` account and it seems to be working for me.

**Comment by FireLemons** [comment]
How did you test this? @jacobherrington

**Comment by andreLumor** [comment]
Hi! How is the status of this issue? I can take a look at it.

**Comment by compwron** [comment]
@andreLumor go for it! :)

**Comment by andreLumor** [comment]
Hi, the changes made earlier were related to deleting case contact, not notes (as described in the issue). So I fixed permissions of #3841 in my PR.
 
 Are these changes to notes needed too?

**Comment by FireLemons** [comment]
No, supervisors can delete notes fine at least in QA

**Comment by FireLemons** [comment]
That picture in the issue is of case contacts but the title says notes. :thinking:
