### ISSUE TITLE
Prevent Admins from seeing other duties across orgs

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3845]
### Impacted User Types
 - admins

### Environment
all

### Current Behavior
Admins see all "Other Duties" even from other casa orgs
![image](https://user-images.githubusercontent.com/8918762/185017202-c470cda0-f27c-47f8-b937-ee81e3f38e76.png)

### Expected Behavior
Admins see only other duties from their own org

### How to Replicate
ex: 
1. - Log in as a volunteer
2. - Create a new duty
3. - Log in as a volunteer from a different org
4. - Create a new duty
5. - Log in as any admin
6. - Go to the other duties page via the left nav bar
7. - See both duties and volunteers listed

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- casa_admin2-1@example.com view the site as an admin from a different org

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hello @FireLemons can I try to solve this one?
