### ISSUE TITLE
Fix Learning hour flaking test

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3877]
### Current Behavior
In `spec/services/learning_hours_export_csv_service_spec.rb`
when the name of the learning hour is set to `Such, Such Were the Joys` the test will fail because it's not expecting quotes. Most likely due to the comma.  
  
Also please fix "learning" misspelled as "larning"  

### How to Replicate
in your local casa, run `bundle exec rspec spec/services/learning_hours_export_csv_service_spec.rb` from the repo root

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by amygurski** [comment]
Cool, that makes sense, thanks. for the 2nd question?

> Do we want the test to handle cases where there's a comma in the name, or can we just ensure the random names generated for the test don't have a comma?

**Comment by FireLemons** [comment]
We want the test to handle cases with commas

**Comment by amygurski** [comment]
Thanks, I'll see what I can do!
