### ISSUE TITLE
Bug: wrong TAY (transition aged youth) on the Volunteers List vs on the Casa Case page

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3904]
### Impacted User Types
 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

### Environment
prod

### Current Behavior
Here is the clear mismatch (the view case page is correct) 

<img width="501" alt="Screen Shot 2022-09-11 at 2 49 12 PM" src="https://user-images.githubusercontent.com/578159/189550286-7151a44d-c607-44a2-b492-33562ea9f44d.png">

### Expected Behavior
ex: When I click "generate report", a downloadable report should be generated.

### How to Replicate
ex: 
1. - Log into staging as an admin or supervisor.
2. - Click on "Generate Reports" in the left sidebar menu.
3. - Filter by a volunteer who has logged at least one case contact.
4. - Click "Generate report" at the bottom of the page.

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by librod89** [comment]
I just noticed that this ticket isn't in a project, but you linked to it from slack. Is this okay to work on?

**Comment by compwron** [comment]
Yep this is fine :)
