### ISSUE TITLE
Add link to issues in contributing guide

### ISSUE THREAD

**Issue by lalarustamli** [rubyforgood/casa#3905]
**Description**
[Contributing guide](https://github.com/rubyforgood/casa/blob/main/doc/CONTRIBUTING.md) has a [paragraph](https://github.com/rubyforgood/casa/blob/main/doc/CONTRIBUTING.md) for issues where the link is missing
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/23105462/189476026-c71733bf-552a-4528-bc44-765774b26866.png">

**Existing file(s) needing changing**
[Contributing guide](https://github.com/rubyforgood/casa/blob/main/doc/CONTRIBUTING.md)

**Comment by lalarustamli** [comment]
I don't have access rights for getting assigned or creating a branch

**Comment by tacoda** [comment]
To make the change, fork the repository to create a branch.
