### ISSUE TITLE
Make the logo link to the website root page.

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3945]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins
 - all casa admins

**Description**
Make the image in the top right of the website point to the root page of the website.
The website root page is the website url without the path. For example in `https://example.com/a/b/c/`, `a/b/c/` is the path so the link back to the root page would be `https://example.com/` or maybe just `/`.
![image](https://user-images.githubusercontent.com/8918762/190873510-31143ef2-54eb-4d50-b393-7f651c05f9e4.png)

Be sure to check that it works for all casa admins as well

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by xcelr8** [comment]
I would like to work on this issue.
