### ISSUE TITLE
Make Organization Name Required

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3973]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Make the name field on the organization edit page [required](https://www.w3schools.com/tags/att_input_required.asp)

To see the page, log in as an admin and click on edit organization on the bottom left
![image](https://user-images.githubusercontent.com/8918762/191890486-27bad360-4aae-4e7f-b2cd-5d418ac99c0e.png)

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/191890343-d1dac442-b9e7-43fc-8c26-6c39935d529c.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by italomatos** [comment]
@FireLemons I think that there is no exist this bug, I tested in my enviroment, and everything is ok. Show message and CasaOrg model has validates presence of in this field.

**Comment by FireLemons** [comment]
put a [required](https://www.w3schools.com/tags/att_input_required.asp) attribute on the input so the user doesn't have to send a request if it's blank
