### ISSUE TITLE
Add foreign key on the other duties table's creator_id referencing the id of the user table

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3976]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
In a migration, 
add a foreign key on the other_duties table's creator_id referencing the id of the user table
make sure the migration supports `db:rollback`

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by thejwuscript** [comment]
I would like to work on this issue.

**Comment by italomatos** [comment]
Hi @FireLemons , is this task make sense? I ask you this, because I see the code, and Note model is a polymorphic, and the idea is save other model references ( no only user reference ), using notable_type and notable_id.

Thanks

**Comment by FireLemons** [comment]
oh yeah I guess it doesn't make sense

**Comment by FireLemons** [comment]
@thejwuscript I'm going to change this issue to a very similar issue
