### ISSUE TITLE
Update Howard Country Court Report Template

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3984]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Part 1 https://github.com/rubyforgood/casa/issues/4154  

Requires Microsoft Word  
Most contributors here don't have MS word and this issue is very important to Howard County. If this issue interests you, could you consider going to your local library and using the computer there for a few hours?

Template: https://drive.proton.me/urls/NYBGB4MNPM#QrMlCMWqhqP1

Using information from the database, autofill in the template:
 - judge name(magistrate name)
 - hearing date
 - birth year and month(make it obvious day isn't there)
 - volunteer name
 - supervisor name
 - the current date
 - case contacts(in the table, leave person blank)

If any of these are null, let the user know what they still have to fill out by displaying what is supposed to be filled out in angle brackets \<X goes here\>

See https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates---word-document-court-report
See [`app/documents/templates/`](https://github.com/rubyforgood/casa/tree/main/app/documents/templates) for examples. This is also where you put the new document.

#### Part 2
Can be a different pull request

Create an [afterparty](https://github.com/theSteveMitchell/after_party) task to set the default court report template for howard as the new one.  
  
In prod, howard county's org has name: "Howard" and id: 4  

_Login Details:_

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
The stakeholders requested this again today... let's work on making this more understandable and doable for volunteers

**Comment by aedwardg** [comment]
Hm...didn't see this before I did #4036. Is that PR still something that is wanted?

**Comment by FireLemons** [comment]
You need something that can run ms word

**Comment by ErinClaudio** [comment]
I have TextEdit, which allows me to see the file.
<img width="1088" alt="Screen Shot 2022-10-21 at 4 50 54 PM" src="https://user-images.githubusercontent.com/20326770/197286484-42280624-8fc0-4fb3-8d9d-2af5971f6d5d.png">

Can I use this, or do I specifically need Word?

**Comment by FireLemons** [comment]
@ErinClaudio you gotta be able to put mailmerge fields into the document to add sablon instructions. Like this https://github.com/rubyforgood/casa/wiki/How-to-edit-docx-templates---word-document-court-report

**Comment by ErinClaudio** [comment]
Thank you, @FireLemons I will have to pass on this ticket. As I do not have MS word
