### ISSUE TITLE
remove unused css case-list from codebase

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4006]
**Description**
remove unused css case-list from codebase
it doesn't seem to do anything. 
https://github.com/rubyforgood/casa/pull/4005#discussion_r985355819

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by spencerldixon** [comment]
Hey @compwron, I'd like to work on this for hacktoberfest, would you mind assigning it to me?
