### ISSUE TITLE
new report (not ready to build)

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4019]
FD: avg number pf contacts per person would be a useful metrics view
report/ metric of number per volunteer (edited) 

Linda (she/her) - CASA and Flaredown
  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1664562329673119?thread_ts=1664560223.947239&cid=CVB0QJGVD)
FD: maybe see number of contacts instead of hours on the volunteer chart page
and number of types of contacts

**Comment by compwron** [comment]
close and make a new draft for making 

![Image](https://github.com/rubyforgood/casa/assets/578159/e337c083-06ca-4e1d-9472-a824aa2f7985)

this page more actionable

**Comment by elasticspoon** [comment]
closing in favor of #5774
