### ISSUE TITLE
Remove court_report_due_date from casa_cases table

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#4023]
**Description**

In #2952 the `court_report_due_date` data was moved from the `casa_cases` table to the `court_dates` table. This field is no longer needed on the `casa_cases` table.

**Existing gem(s), file(s) needing updating, changing or deleting**

Remove the `court_report_due_date` field from the `casa_cases` table

Blocked until after the next deploy + 1 week to make sure we do not have any data migration issues.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by vasconsaurus** [comment]
@littleforest I'll keep an eye for this one 🙂

**Comment by tonyaraujop** [comment]
Hello there, can I work on this?

**Comment by littleforest** [comment]
@tonyaraujop we are actually not ready to build this one yet, but it will be available in a couple of weeks.

**Comment by littleforest** [comment]
This ticket is ready to be worked on.

**Comment by vasconsaurus** [comment]
@littleforest I'm on it 😄
