### ISSUE TITLE
Bug: Docker/build creates a server without application.js

### ISSUE THREAD

**Issue by ChaelCodes** [rubyforgood/casa#4050]
### Impacted User Types
 - app contributors using docker

### Environment
development docker setup

### Current Behavior
When I run `docker/build` in GitHub codespaces, or an Ubuntu 18.0.1 WSL environment, the script runs successfully, but navigating to the server at localhost:3000 renders a `The asset "application.js" is not present in the asset pipeline.` error.
![error](https://user-images.githubusercontent.com/8124558/194925578-c0f59c00-0900-4c1c-a025-ba91ce980146.png)

The containers all report successful completion, and are running.
![docker ps log - 3 containers running](https://user-images.githubusercontent.com/8124558/194925165-7f7f86e2-5958-41f3-b520-06fa3b726701.png)

I'm on a recent commit to main.
![git log showing commit from 10/9](https://user-images.githubusercontent.com/8124558/194925369-9c947953-2a27-4fc0-8f79-f664f8b8642d.png)

The logs report that application.js was succefully built.
https://gist.github.com/ChaelCodes/47e434ad0534fcedb04a4adb8f8bf9b8#file-build-log-L763
The tests show it missing though.

### Expected Behavior
The application is running and accessible at localhost:3000.

### How to Replicate
1. - clone the repo
1. - Run `docker/build`
1. - Naviagte to localhost:3000

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
Hmmm that's not great. @FireLemons maybe we can look at this during office hours
How are the specs passing in this case?

**Comment by ChaelCodes** [comment]
> Hmmm that's not great. @FireLemons maybe we can look at this during office hours How are the specs passing in this case?

All the system specs have the same issue.
https://gist.github.com/ChaelCodes/47e434ad0534fcedb04a4adb8f8bf9b8#file-test-log-L1346-L1350

**Comment by AlysonBasilio** [comment]
Hey, @ChaelCodes @compwron how are you? I was setting up my local environment with docker and crossed this issue. I resolved this by running `docker-compose run --rm web yarn build` and `docker-compose run --rm web yarn build:css` before running `docker-compose up -d`.

I would be glad to work on this issue, but I'm not sure if we have to update the docs or if we have to improve docker execution to include asset building in the dev environment. What do you think?
