### ISSUE TITLE
Bug: missing button for adding court dates to cases without court dates

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4051]
### Impacted User Types
all

### Environment
all

### Issue
we seem to have lost the ability to add court dates to cases without court dates - this is a bug and we should fix it. 
https://casa-qa.herokuapp.com/casa_cases/2989
<img width="275" alt="Screen Shot 2022-10-10 at 1 01 05 PM" src="https://user-images.githubusercontent.com/578159/194943841-5b83497c-e0d3-48dc-8655-ec977a12b422.png">
<img width="348" alt="Screen Shot 2022-10-10 at 1 02 02 PM" src="https://user-images.githubusercontent.com/578159/194943844-d30825e1-80cc-4a90-a811-6741b253d4a6.png">

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hello there, can I work on this?

**Comment by compwron** [comment]
go for it!
