### ISSUE TITLE
Fill out app/policies/casa_org_policy.rb

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4061]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Fill out app/policies/casa_org_policy.rb such that admins can only edit and update the org they belong to
Fix / Update tests if needed

See https://github.com/varvet/pundit
See The other files in [`app/policies`](https://github.com/rubyforgood/casa/tree/main/app/policies) for examples

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hello there, can I work on this?

**Comment by compwron** [comment]
go for it! :)
