### ISSUE TITLE
Restrict supervisor controller method permissions to supervisor's organization

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4062]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Make sure all the methods in [`app/policies/supervisor_policy.rb`](https://github.com/rubyforgood/casa/blob/main/app/policies/supervisor_policy.rb) contain some logic to prevent access from users belonging to a different organization. 

Fix / Update tests if needed

See [`app/policies/application_policy.rb`](https://github.com/rubyforgood/casa/blob/main/app/policies/application_policy.rb) for helper methods
See https://github.com/varvet/pundit

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hello there, can I work on this?

**Comment by FireLemons** [comment]
@tonyaraujop One pull request per method in the policy file please
