### ISSUE TITLE
Limit casa case controller method permissions to the case's organization

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4063]
**What type(s) of user does this feature affect?**
- volunteers
 - supervisors
 - admins

**Description**
Make sure all the methods in [`app/policies/casa_case_policy.rb `](https://github.com/rubyforgood/casa/blob/main/app/policies/casa_case_policy.rb ) contain some logic to prevent casa case access from users belonging to a different organization. 

Fix / Update tests if needed

See [`app/policies/application_policy.rb`](https://github.com/rubyforgood/casa/blob/main/app/policies/application_policy.rb) for helper methods
See https://github.com/varvet/pundit

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
I can see at least the `activate` and `deactivate` casa case controller methods don't respect org boundaries. There might be more

**Comment by crespire** [comment]
Thanks! I'll poke around and try to attend office hours as well just to say hi! :)

**Comment by crespire** [comment]
:wave: I'm working through this slowly!

**Comment by crespire** [comment]
👋 still working on this!

**Comment by crespire** [comment]
@FireLemons 

:wave: I'm actually still working on this, along with @GALTdea so we will hopefully have something on this in the next little bit.

**Comment by crespire** [comment]
@FireLemons 

Hi Shen!

I hope you're having a great day. I wanted to touch base about this issue as we're working on it.

Currently, our strategy is to update all of the `CasaCasePolicies` and accompanying specs to ensure that the policies are scoped by organization. That is to say, we are working to make sure the policies and their tests reflect the accurate behaviour first, before moving on to correcting behaviour in the application at large that might break as a result of changes made to the policies.

So, with that in mind, we were wondering:
1) Are there any particular policies that *should not* be scoped by organization?
2) Once we make changes to these policies to be scoped by organization, I expect that there might be some errors in the rest of the app as a result of these policy changes. Should that work then be a separate issue and PR?

For example, the `CasaCasePolicy` `update_contact_types?` currently only uses `is_supervisor? || is_admin?` and we want to make sure the policy updates to use `is_supervisor_same_org? || is_admin_same_org?`

If these changes pass in isolation on the policy and test side, then we would work to make sure that these changes also then pass tests within the app itself.

Happy also to chat at office hours if it might be easier to discuss in real time.

**Comment by crespire** [comment]
@FireLemons 

Hi Shen,

Thanks for chatting with me at office hours. I appreciate your time! Just to recap my takeaways from our discussion:
* All the policies in `CasaCasePolicy` should be scoped by organization, as the `admin` in this case is an organization admin.
* We'll continue to work on the policies and policy spec in isolation before moving on to errors that this might generate in the application.
