### ISSUE TITLE
Limit case_assignment controller method permissions to the case assignment's organization

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4065]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
A case assignment links a casa case to a volunteer user

Make sure all the methods in [`app/policies/case_assignment_policy.rb `](https://github.com/rubyforgood/casa/blob/main/app/policies/case_assignment_policy.rb ) contain some logic to prevent casa case assignment access from users belonging to a different organization. 

Fix / Update tests if needed

See [`app/policies/application_policy.rb`](https://github.com/rubyforgood/casa/blob/main/app/policies/application_policy.rb) for helper methods
See https://github.com/varvet/pundit

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mateusdeap** [comment]
I can work on this!

**Comment by FireLemons** [comment]
@mateusdeap One pull request per method in the file please

**Comment by mateusdeap** [comment]
Just to be clear, should this affect create and destroy, or just the other methods?

The thing that's confusing me is that you already seem to be verifying wether the CaseAssignment and the user are in the same org for creation and destroy.

Also, because for create we still have no case assignment, there's no record to check for the org.

It can be done, but it seems we would have to pass the casa_case and not the CaseAssignment to the policy, which would be kind of weird...

**Comment by FireLemons** [comment]
> Just to be clear, should this affect create and destroy, or just the other methods?
All the methods because it looks like they all check simply if the user is an admin or a supervisor.

**Comment by FireLemons** [comment]
> The thing that's confusing me is that you already seem to be verifying wether the CaseAssignment and the user are in the same org for creation and destroy.  
  
If we're doing that somewhere else, it's in the wrong place. I think we check for cross org case access which may prevent cross org case assignment access.

**Comment by FireLemons** [comment]
> Also, because for create we still have no case assignment, there's no record to check for the org.  
  
Maybe you can't do it for create. In that case just do it for the methods that make sense.
