### ISSUE TITLE
Move the Remove Language method from the Language Controller to the Users Controller to match Add Language

### ISSUE THREAD

**Issue by elhalvers** [rubyforgood/casa#4079]
**Description**This is a continuation of https://github.com/rubyforgood/casa/pull/4056.

Move the Remove Language method from the Languages Controller to the User's Controller

Update the tests

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kaysiz** [comment]
@elhalvers @ludamillion  I can take a shot at this one. I see the add language method has already been moved, I can move the remove language method.

**Comment by elhalvers** [comment]
Hi @kaysiz If it is ok with you, I would like to continue to work on this one. I just created a PR to add the last of the tests for the add language method. I wanted to completely finish that one before working on this one. I would like to see if I can use my PR as a guide to do everything for the remove language method that was done for the add language method including all of the testing. If I run into challenges, maybe we can pair on it! What do you think? : )

**Comment by elhalvers** [comment]
Hey @kaysiz I got a good start on this today with 15 commits and a draft PR started. The behavior is not correct yet and I may need some help with debugging and testing if you are interested.

Thanks!

: )

**Comment by aboongm** [comment]
I want to work on this.
