### ISSUE TITLE
[bug] Editing a case contact should not by default change the row display date of case contact

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#408]
As a volunteer, if I change a case contact, the date of the case contact **should** be changeable but should **not** change by default/accident - see screenshot of pre-existing case contact, and the date field that auto-populates in the edit case contact view. 

![Screen Shot 2020-07-19 at 11 56 07 AM](https://user-images.githubusercontent.com/578159/87882710-e1ef2b00-c9b6-11ea-9e18-7568ec2fe095.png)
![Screen Shot 2020-07-19 at 11 55 29 AM](https://user-images.githubusercontent.com/578159/87882868-0d264a00-c9b8-11ea-8c08-1050fdecc720.png)

**Comment by GuillermoCoding** [comment]
Hello, I was wondering if I could pick up this issue ?

**Comment by compwron** [comment]
Go for it!
