### ISSUE TITLE
Bug: Casa Contact Types are shown as required on UI, but we can still submit the case with all uncheck

### ISSUE THREAD

**Issue by ashwinisukale** [rubyforgood/casa#4084]
### Impacted User Types
 - admins
 - all casa admins

### Environment
All Environment

### Current Behavior
We can create the case without the contact type selection, even on the UI it marked as required by showing the `*` symbol after the label.

### Expected Behavior
- We should make the casa contact type as required on the UI and backend

### How to Replicate

1. - Log into staging as an admin
2. - Click on "Cases" in the left sidebar menu.
3. - Create a "New Case"
4. - Fill all the details and Uncheck All contact types, then submit the form
5. - It will create the new case
6. - Now edit the same case, you will see all the contact types are checked, but we submitted as unchecked

### Screenshot
<img width="1768" alt="Screenshot 2022-10-19 at 3 25 14 PM" src="https://user-images.githubusercontent.com/1137325/196662944-42142426-8eb6-4f08-9bb7-25863928da05.png">

**Comment by rishijain** [comment]
Thanks for confirming the bug @Thrillberg and @ashwinisukale . I will be happy to take this up and fix it. :)
