### ISSUE TITLE
Add `bin/setup` script

### ISSUE THREAD

**Issue by mateusdeap** [rubyforgood/casa#4088]
**What type(s) of user does this feature affect?**
Developers, since this a more a DX kind of thing.

**Description**
I noticed that the setup section has quite a few instructions, so the idea would be simply to create a setup script that runs all of them in just one command, as is usually considered good practice.

No QA required in the site.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by zvwm** [comment]
It looks like there is an existing `bin/setup` script for this project although it's not referenced in the readme and might need some updates before it will configure everything.
