### ISSUE TITLE
Disable entering duplicate language options for casa orgs

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4096]
### Impacted User Types
 - admins

### Environment
all

### Current Behavior
Multiple of the same language can be entered as language options for casa orgs
![image](https://user-images.githubusercontent.com/8918762/197273958-2df6cec2-ddeb-4844-91a2-e0829081898b.png)

### Expected Behavior
A validation error is shown when duplicate languages are entered

### How to Replicate
ex: 
1. - Log as an admin.
2. - Click on "Edit Organization" in the left sidebar menu.
3. - Scroll to the languages section
4. - Copy a language from the list
5. - Click new language
6. - Paste the copied language into the box and submit

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kazuhirodk** [comment]
Can you assign me to work on this issue?

**Comment by kazuhirodk** [comment]
Thanks! I'm working on it

**Comment by kazuhirodk** [comment]
> This issue has been inactive for 250 hours (10.42 days) and will be unassigned after 110 more hours (4.58 days). If you have questions, please visit the #casa channel in slack during Tuesdays 6-8 PM PST. Link: https://rubyforgood.herokuapp.com/
> 
> If you are still working on this, comment here to tell the bot to give you more time

Sorry, I had some problems in the last few weeks, but I'll work on this task this week.

**Comment by anshu1992** [comment]
Hey @FireLemons, can I take this issue if it is not resolved?

**Comment by anshu1992** [comment]
I need more time to fix the tests.

**Comment by anshu1992** [comment]
I need more time to fix the tests.

**Comment by FireLemons** [comment]
@anshu1992 Can you mark your pull request as draft then?

**Comment by anshu1992** [comment]
@FireLemons done!

**Comment by anshu1992** [comment]
@FireLemons I fixed the specs, and they pass on my local but not on GitHub. System tests fail are failing, and I didn't make any changes there. I need help with this and have posted about the same in the casa channel on slack.

**Comment by anshu1992** [comment]
The [PR](https://github.com/rubyforgood/casa/pull/4461) for this is ready to be merged.
