### ISSUE TITLE
Remove horizontal scroll bar from volunteer search field

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4098]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Restyle the volunteer search text box on the reimbursements page so that it doesn't have a horizontal scroll bar.  
To see the reimbursements page, login as an admin and click on Reimbursement Queue in the left sidebar.  

See https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

**Screenshots of current behavior**  
![image](https://user-images.githubusercontent.com/8918762/197277384-f605f9bf-e904-49e8-a4b6-e778691e43d4.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kazuhirodk** [comment]
Hi! Can you assign me to work on this issue?
