### ISSUE TITLE
Add a button to add a Standard Court Order to a Casa Case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4123]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**

- [ ] On the Edit Casa Case page  like https://casa-qa.herokuapp.com/casa_cases/CINA-14-1002/edit add a second button like the "Add a court order" button which says "Add a standard court order" 
- [ ] When the + button with the "Add a standard court order"  text is clicked, show a modal or dropdown (try em and see what feels better) of options. For now make the list hardcoded in the code- see list below
- [ ] When a standard court order is clicked, add a court order with that text and stay on the edit casa case page. 
- [ ] (Optional) make that section look a bit nicer: make court orders a proper title, make the buttons more even, anything else that might bother you

Ex:

![image](https://github.com/rubyforgood/casa/assets/14540596/e72271cc-ddc7-40ea-ab7e-aea5b298b8a0)

(In a later ticket we will add a db table for customization and the db seed to auto setup standard court orders)

Standard court orders:

- Individual therapy for the Respondent;
- Family therapy;
- Birth certificate for the Respondent’s;
- Educational or Vocational referrals;
- Independent living skills classes or workshops;
- Learners’ permit for the Respondent, drivers’ education and driving hours when needed;
- Educational monitoring for the Respondent,
- Tutor for the Respondent;
- Individual therapy for the [parent];
- Substance abuse assessment for the [parent];
- Housing support for the [parent];
- Visitation assistance for the Respondent to see [family];
- No contact with (mother, father, other guardian)
- Supervised visits
- Supervised visits at DSS
- Virtual Visits
- Therapy (child, mother, father, other guardian)
- Psychiatric Evaluation and follow all recommendations  (child, mother, father, other guardian)
- Substance Abuse Evaluation and follow all recommendations (child, mother, father, other guardian)
- Substance Abuse Treatment (child, mother, father, other guardian)
- Urinalysis (child, mother, father, other guardian)
- Parenting Classes (mother, father, other guardian)
- Domestic Violence Education/Group

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by dvsconcept1986** [comment]
I would like to take this issue.

**Comment by malsmr** [comment]
Is this still available to be worked on? I found this in ToDo

**Comment by FionaDL** [comment]
Just checking in, I am going to start work on this issue, is that ok?
