### ISSUE TITLE
Move controller specs to request specs

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4129]
Move controller specs to request specs - see https://github.com/rubyforgood/casa/blob/main/doc/architecture-decisions/0008-controller-specs.txt for why and how

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by farrelld09** [comment]
Claim

**Comment by sandfortw** [comment]
@compwron I am confused about something.

The controller spec file was deleted in this PR:

https://github.com/rubyforgood/casa/pull/3432/

But then reintroduced here:

https://github.com/rubyforgood/casa/pull/3817

Was this an error? Can I safely delete it? Are we keeping some controller tests for some reason?

**Comment by sandfortw** [comment]
Only application_controller_spec, static_controller_spec, and sessions_controller_spec do not already have corresponding request spec files. Is there anything left to do for this issue except remove the redundant controller specs? 

Is the task that's left to make sure everything that is being tested in the current controller tests is also in the request tests, or are all of the existing controller tests supposed to remain, in which case this issue should be closed?

If I am fundamentally missing something, I may need to have this explained in office hours, or by someone who is willing to chat with me tomorrow or Friday.
