### ISSUE TITLE
Add judge to court report context

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4154]
**Description**
Add the name of the judge of the next court date to the case details section of the court report context
Write a test

See [`app/models/case_court_report.rb`](https://github.com/rubyforgood/casa/blob/main/app/models/case_court_report.rb)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hi, I'm hunting for my first open source contribution. Can I be assigned this issue if it still needs help?

**Comment by FireLemons** [comment]
@ShamiTomita I'm not sure what the status of this issue is. I think someone may be working on it.

**Comment by ShamiTomita** [comment]
I see, I’ll look elsewhere in the issues section then 😊
