### ISSUE TITLE
add test for CaseCourtReportContext in the case that all fields are populated

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4157]
**Description**
add tests for CaseCourtReportContext in the case that all fields are populated

Add test/s to fill in test data for these fields and test them in file `spec/models/case_court_report_context_spec.rb`

```
        expect(context[:case_contacts]).to eq([]) # TODO test this
        expect(context[:case_court_orders].length).to eq(4) # TODO test this better
        expect(context[:case_mandates].length).to eq(4) # TODO test this better
        expect(context[:latest_hearing_date]).to eq("___<LATEST HEARING DATE>____")
        expect(context[:org_address]).to eq(nil) # TODO test this better
        expect(context[:volunteer]).to eq(nil) # TODO test this better
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
I think we want to break this down into multiple tests
