### ISSUE TITLE
Admin report should contain supervisor of volunteer data

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#418]
![Screen Shot 2020-07-31 at 4 41 51 PM](https://user-images.githubusercontent.com/578159/89088373-c38d1600-d34c-11ea-9a52-6922886b6a6e.png)
![Screen Shot 2020-07-31 at 4 41 38 PM](https://user-images.githubusercontent.com/578159/89088374-c4be4300-d34c-11ea-8e37-00f4d700d17a.png)

**Comment by bobbyvidal** [comment]
I think someone may have already added this to the report. Is there anything else regarding the report that should be added or changed?

**Comment by compwron** [comment]
@bobbyvidal You're right! We seem to have a related problem though- the Supervisor name doesn't seem to be coming through- the column is empty on staging and it should not be.

**Comment by Garbar** [comment]
At the moment, the names are displayed correctly.
But except when the contact was made by a supervisor or admin. Then the field is empty.
On the stage now, almost all contacts were made by them.
<img width="736" alt="case-contacts-report-1597241782 2020-08-12 17-20-19" src="https://user-images.githubusercontent.com/1007159/90026723-5bc9ba00-dcc0-11ea-80ec-be017291bbe8.png">

**Comment by compwron** [comment]
That makes sense! Let's update the report so the column "Volunteer name" says "Creator name" and make sure that supervisor/admin names show up :)
