### ISSUE TITLE
Add Space Between Sections on Volunteer Homepage

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#4200]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Add more space between My Cases and Other Duties sections of the Volunteer Homepage. (https://casa-qa.herokuapp.com/casa_cases)

**Screenshots of current behavior, if any**  

<img width="1114" alt="Needs More Space " src="https://user-images.githubusercontent.com/7007647/201413546-bf720137-5103-4d67-a3a5-0d4e453d8e60.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by lautarol** [comment]
I can work on this

**Comment by compwron** [comment]
Hmm I merged this PR but it was intended to be a reserved ticket, whoops :/
