### ISSUE TITLE
Bug: phone number should not be required to reset password

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4205]
### Impacted User Types
all

### Environment
PROD, staging, qa, local

### Current Behavior

1. go to https://casa-qa.herokuapp.com/users/password/new and enter a real user account like volunteer1@example.com
2. expect to see something like "password reset email has been sent" but instead [BUG] see "1 error prohibited this Volunteer from being saved:
User does not exist." (but the user definitely does exist)
Also the user's saved phone number should not then appear on the reset password form!!!

Add a new test on spec/system/devise/passwords/new_spec.rb

<img width="658" alt="Screen Shot 2022-11-14 at 11 51 53 PM" src="https://user-images.githubusercontent.com/578159/201849313-53e67e10-d002-47cd-850f-627c70732b51.png">

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FranConcaro** [comment]
@compwron you might want to close this issue.
