### ISSUE TITLE
Bug: User creation should NOT give errors even if SMS is not setup for casa org and new volunteer has phone number

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4221]
### Impacted User Types
 - supervisors creating volunteers or supervisors
 - admins creating volunteers, supervisors, or admins

### Environment
all

### Current Behavior
Bug: User creation should NOT give errors even if SMS is not setup for casa org and new volunteer has phone number

### Expected Behavior
Creating a user should work without error 

### How to Replicate
ex: 
1. as a supervisor click the New Volunteer button on https://casa-qa.herokuapp.com/volunteers/new or anywhere else
2. enter valid info including phone number
3. click save, see the bad errror

<img width="880" alt="Screen Shot 2022-11-18 at 11 30 14 AM" src="https://user-images.githubusercontent.com/578159/202787046-1667271d-e4e9-498f-8da2-b7130b43641a.png">

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by CovenantHuman** [comment]
This appears to be resolved? 
<img width="1027" alt="Screenshot 2022-12-16 at 8 40 02 PM" src="https://user-images.githubusercontent.com/7007647/208225429-81e80349-ee16-449d-b5fc-a1c448cd96a1.png">

**Comment by schoork** [comment]
We currently don't have accounts using SMS.

**Comment by elasticspoon** [comment]
Cannot reproduce.
