### ISSUE TITLE
Allow case creation without next court report date BUT only with clicking confirm button 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4222]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
In the event that the court date for a new case being created is not known, currently we block creation of the case. We don't want to do that. So we want to add a button that says "I don't have it at the moment" to the court date part of the new case creation workflow. This button should allow the case to be created without a court date. 

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by andreLumor** [comment]
Hi! I'll work on it.
