### ISSUE TITLE
Add a Section to the Admin Cases Page for Cases Without Court Dates

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#4224]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Add a section to the admin homepage that displays cases that don't have any court dates listed.

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by aisayo** [comment]
Hi I would like to work on this

**Comment by anshu1992** [comment]
Hi @CovenantHuman, I would like to take this one if it still needs to be completed.

**Comment by tonyaraujop** [comment]
Hey @compwron  you know if is there any work for this issue? I would like to work on it.
