### ISSUE TITLE
Bug: When adding a New Case Contact to a Case it doesn't always add to the selected Case

### ISSUE THREAD

**Issue by vasconsaurus** [rubyforgood/casa#4236]
### Impacted User Types
 - casa admins?

### Environment
development, I also tested in the qa site

### Current Behavior
When I add a New Case Contact to a Case, if I added a New Contact Case on a different Case before, it will select the former Case and not the current one I'm working with. E.g.: the Case I wanted to add a new contact to was _03-1034_, and the case pre-selected was _manu-test_.

![Screenshot 2022-11-30 at 12 02 45](https://user-images.githubusercontent.com/87862340/204834123-079f3175-6fb1-4b41-a8ac-51f8bd2b0140.png)

![Screenshot 2022-11-30 at 12 02 57](https://user-images.githubusercontent.com/87862340/204834190-2a97f92f-7886-4fe3-89f6-ae6930cdd2d1.png)

![Screenshot 2022-11-30 at 12 03 00](https://user-images.githubusercontent.com/87862340/204834229-98de00dd-4a3b-4f4d-89ab-0ac70dfb5814.png)

### Expected Behavior
ex: When I try to add a new Case Contact the current Case I'm working on should be selected

### How to Replicate
ex: 
1. - Log in as an admin or supervisor
2. - Click on a Case, or create a new one
3. - Add a new Case Contact
4. - Go to a different Case
5. - Add a new Case Contact

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
That's not good! @CovenantHuman @FireLemons @littleforest do you have thoughts on this?
