### ISSUE TITLE
Make supervisor name a link to supervisor in Supervisors section of admin ashboard

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#424]
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**
Make supervisor name a link to supervisor in Supervisors section of admin dashboard

**Screenshots of current behavior, if any**
![Screen Shot 2020-07-19 at 11 38 29 AM](https://user-images.githubusercontent.com/578159/87882492-15c95100-c9b5-11ea-8b8c-f1965b0b43d6.png)

**Comment by GuillermoCoding** [comment]
Hello, can I pick this up?

**Comment by compwron** [comment]
@GuillermoCoding yes!
