### ISSUE TITLE
add the names of volunteers who haven't logged in, in 30 days, to the monday supervisor email

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4244]
**What type(s) of user does this feature affect?**
 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

**Description**

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by MiguelArgentina** [comment]
Hey there, can I work on this one?

**Comment by zorab47** [comment]
@ShamiTomita and I plan on taking this on in the next week. What would actions might supervisors take on volunteers who haven't logged in recently? That will help inform what information to show in the email.
