### ISSUE TITLE
Create a trait for a "FollowupNotification" in the notification factory

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4258]
Add a factorybot trait to `spec/factories/notifications.rb` to our notifications factory that makes the notification into a `FollowupNotification`  
see: [main/spec/factories/notifications.rb](https://github.com/rubyforgood/casa/blob/main/spec/factories/notifications.rb)
see: https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hi, can I work on this?
