### ISSUE TITLE
Rename New Case Contact to New Case Contact Type

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4278]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Admins editing their organization can modify their list of case contact types.
 - Change the title of the page from "New Case Contact" to "New Case Contact Type"
 - Add this description to the page: "Case contact types are the types of people that can be contacted for a case contact. Some examples are parents, teachers, and social workers."

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/206827960-92115f34-fea4-498a-a828-faca6ac9c6d1.png)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hi, can I work on this?
