### ISSUE TITLE
Bug: show both prompts for court dates when a case has no court dates

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4280]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Current Behavior
when a case has no court dates, no prompts asking for future and past court dates are shown

### Expected Behavior
when a case has no court dates, prompts asking for future and past court dates are shown
update the tests

### How to Replicate
ex: 
1. - Log in as any user
2. - navigate to a casa case's page
3. - if there are court dates, delete them via the rails console. Something like `CasaCase.find(CASE_ID).court_dates.destroy_all`
4. - create a case contact
5. - You should be redirected and a modal where the prompts appear should be visible

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by CovenantHuman** [comment]
I'd like to work on this. :)
