### ISSUE TITLE
Describe Contact Type Groups

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4281]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Add this description to the new case contact group page: 
"Case contact groups are used to group case contact types. For example a Family group could contain the case contact types: parent, grandpa, aunt."

This page is reachable when logged in as an admin. Visit the edit organization page in the **sidebar**

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/206828539-99fca729-0556-4a5a-89ae-f504bc2f915e.png)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kaysiz** [comment]
@FireLemons I can take this one

**Comment by anshu1992** [comment]
Hey @FireLemons, I can take this one.

**Comment by divyanshu0312** [comment]
Hi @FireLemons, you might want to close this issue.
