### ISSUE TITLE
Organize spec/models/case_court_report_context_spec.rb

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4284]
**Description**
A court report context is like a big json object containing all the data to be passed into a casa case court report.  
Organize the tests by  
 - ~~putting expects in the right test~~
 - ~~breaking up big tests with lots of expects into smaller tests with fewer expects~~
 - writing new tests for parts of the context not tested if needed
 - deleting unnecessary tests if needed
 - organizing sections of the context under describe blocks

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jamgar** [comment]
I can work on this

**Comment by napster235** [comment]
Hey @FireLemons. I opened a PR for this issue since no one was working on it.

**Comment by FireLemons** [comment]
describe context sections still need to be organized to match the context sections

**Comment by napster235** [comment]
@FireLemons Created this PR (https://github.com/rubyforgood/casa/pull/4492) that I think solves what you suggested

**Comment by FireLemons** [comment]
The tests still need to be organized under describe blocks grouping context sections. Some tests are missing like the check for supervisor name
