### ISSUE TITLE
New Theme (Epic)

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4304]
### Summary

Great news! We're excited to share that we're updating the look and feel of the CASA Volunteer tracker. We're upgrading it to the latest version of bootstrap and implementing a new theme called  [plainadmin](https://github.com/PlainAdmin/plain-free-bootstrap-admin-template) to add consistency and make future work easier. We've chosen  [plainadmin](https://github.com/PlainAdmin/plain-free-bootstrap-admin-template) because it's a bare bones template that we can easily customize as needed, but it's still robust enough to support the application's functionality.

To make it easier to break down the theming process into smaller tasks, we've converted the supervisors' index page to serve as a template for other pages and have already converted the application and sidebar layout files.

### Things to Consider

The CSS and assets are currently in the /public directly and will need to be moved at the end.

While we work on converting to the new theme pull requests will be made against the `new_theme` branch until it is finished. 

### Plan

* Convert all pages to the new theme
* Update informational text, and testimonials,  on the new landing page
* Update all helper methods `body_class`, `menu_item`, `og_tag`, and so on
* Consolidate and move css into /assets
* Ensure all tests are passing
* Lots of manual QA
* RELEASE!

**Comment by msespos** [comment]
<img width="716" alt="Screen Shot 2023-01-12 at 1 40 49 PM" src="https://user-images.githubusercontent.com/62808851/212190677-0210946e-0374-475a-992c-47abaa97bd46.png">

casa_cases/cina-07-1003/court_dates/new

I believe this is inconsistent with other "Add" buttons. I think the + sign should be in a button with the text "Add a court order", not outside the text in its own button with the text not in a button.

**Comment by msespos** [comment]
<img width="987" alt="Screen Shot 2023-01-12 at 2 09 15 PM" src="https://user-images.githubusercontent.com/62808851/212191802-8f8c1a9b-48e5-4c6f-b584-cbbb4f847114.png">

/casa_cases/cina-22-1002

I believe that the "New Case Contact" button should have a + icon to the left of the text.

**Comment by msespos** [comment]
<img width="1511" alt="Screen Shot 2023-01-12 at 2 14 52 PM" src="https://user-images.githubusercontent.com/62808851/212192605-53f269cb-7dd7-4f7b-b3ff-ce362099e2f2.png">
<img width="1494" alt="Screen Shot 2023-01-12 at 2 18 41 PM" src="https://user-images.githubusercontent.com/62808851/212193177-23b8e4ae-43ab-4b3d-b399-692bbe68eb32.png">

casa_cases/cina-22-1002/emancipation

+/- buttons on right do not appear to work as expected. After initially loading the page, clicking on any + button expands all of the fields, not just the one indicated by that + button. Clicking on any + or - button after that leads to more unexpected behavior. I think the desired behavior is that just one field expands or contracts at a time, using the + or - buttons respectively, though I'm not 100% sure.

**Comment by msespos** [comment]
<img width="693" alt="Screen Shot 2023-01-12 at 2 20 55 PM" src="https://user-images.githubusercontent.com/62808851/212193558-f0831b9f-6780-41b3-8392-b30692662550.png">

casa_cases/cina-22-1002/edit

"+" Add a court order should look like the "+ Add a court date button" button, with the text in the button not outside it.

**Comment by msespos** [comment]
<img width="858" alt="Screen Shot 2023-01-12 at 2 33 57 PM" src="https://user-images.githubusercontent.com/62808851/212195734-440e6b44-2cad-49bf-967c-f1a71a4d7867.png">

case_contacts

I believe this button should be the darker blue not this light blue.

**Comment by msespos** [comment]
<img width="1511" alt="Screen Shot 2023-01-12 at 2 39 35 PM" src="https://user-images.githubusercontent.com/62808851/212196533-2c4831ff-7383-4442-ae35-4a2db98dd255.png">
<img width="245" alt="Screen Shot 2023-01-12 at 2 42 30 PM" src="https://user-images.githubusercontent.com/62808851/212197014-54fc8c3a-5472-4f90-ba5f-1bbb6e0b5ff7.png">

casa_cases/cina-21-1004

Should the green Generate Report button have the download icon? I've seen it on at least one other Generate Report button. Also, should it be green?

**Comment by msespos** [comment]
<img width="1515" alt="Screen Shot 2023-01-12 at 2 52 34 PM" src="https://user-images.githubusercontent.com/62808851/212198288-88365b03-a224-4693-8315-baae85f8e212.png">

casa_cases/cina-07-1003/emancipation

Should the Download Checklist button have the download icon (see previous comment for example)?

**Comment by msespos** [comment]
<img width="1528" alt="Screen Shot 2023-01-12 at 2 54 58 PM" src="https://user-images.githubusercontent.com/62808851/212198676-bda00dac-203d-4609-8680-7c8c61a56e4b.png">

casa_cases/cina-21-1004/edit

Should the Update CASA case button be on the page twice?

**Comment by msespos** [comment]
<img width="754" alt="Screen Shot 2023-01-12 at 3 39 45 PM" src="https://user-images.githubusercontent.com/62808851/212204145-2189b5d0-8532-4aef-a0b1-dd488199aab1.png">

supervisors/5/edit

Should this button be the darker blue color?

**Comment by msespos** [comment]
<img width="1522" alt="Screen Shot 2023-01-12 at 3 43 49 PM" src="https://user-images.githubusercontent.com/62808851/212204614-9f0b1d4a-5bc0-4b03-b977-a3d7e0b30499.png">

casa_cases/97

I believe the two green buttons, Generate Report and Download All, should have the download icon.

**Comment by msespos** [comment]
<img width="1433" alt="Screen Shot 2023-01-12 at 3 45 52 PM" src="https://user-images.githubusercontent.com/62808851/212204813-4c5b0a32-8ffe-49ae-b848-dd78e41e9a0e.png">

casa_cases/97

Broken images (I believe) above CASA, Family and Family, CASA.

**Comment by msespos** [comment]
<img width="864" alt="Screen Shot 2023-01-12 at 3 48 37 PM" src="https://user-images.githubusercontent.com/62808851/212205078-c9830c38-83e8-4ada-a3a0-31cbf1535fe0.png">

casa_cases/cina-20-1097/edit

I believe this button should be the darker blue.

**Comment by msespos** [comment]
<img width="1521" alt="Screen Shot 2023-01-12 at 3 50 14 PM" src="https://user-images.githubusercontent.com/62808851/212205254-1e77a1de-ad84-4dd8-8130-be34b1f19289.png">

casa_cases/cina-20-1097/court_dates/new

"Add a court order" should be in the button with the + icon - icon and text in one button instead of as shown.

**Comment by msespos** [comment]
<img width="1506" alt="Screen Shot 2023-01-12 at 3 52 12 PM" src="https://user-images.githubusercontent.com/62808851/212205456-ed63fdef-086d-42b0-9e49-d8d790a5c4d5.png">

casa_cases/97

Send reminder button appears to be broken on Heroku.

**Comment by msespos** [comment]
<img width="688" alt="Screen Shot 2023-01-12 at 4 03 09 PM" src="https://user-images.githubusercontent.com/62808851/212206672-aecbaeb9-c1f5-408e-9100-a2846b399c13.png">

case_contacts/437/edit

I believe this button should be solid, dark blue.

**Comment by msespos** [comment]
<img width="416" alt="Screen Shot 2023-01-12 at 4 08 44 PM" src="https://user-images.githubusercontent.com/62808851/212207218-f0834f1c-19dc-4b82-8c1a-efdad1dcf1f4.png">

casa_cases/cina-15-1155/edit

"+ Add a court order" should look like "+ Add a court date" here.

**Comment by msespos** [comment]
<img width="1516" alt="Screen Shot 2023-01-12 at 4 11 56 PM" src="https://user-images.githubusercontent.com/62808851/212207561-f75e6932-ac27-4457-ad7a-954eab5e7697.png">
casa_cases/cina-03-1014

New Case Contact and Generate Report need icons (a + for the former and a download icon for the latter).

**Comment by msespos** [comment]
<img width="1237" alt="Screen Shot 2023-01-12 at 4 30 08 PM" src="https://user-images.githubusercontent.com/62808851/212209580-07f631a4-8c63-45c9-817f-b5f1d21b4ec8.png">

reports

Clicking on "Mileage Report" changes the text to "Downloading Mileage Report", but there is no similar text for clicking on any of the other buttons. I'm not sure if that is the intention or not.

**Comment by seanmarcia** [comment]
Hey @msespos I went through last night and fixed most of these. Some I didn't because I don't know the app well enough to know if they are doing things for a specific reason. I also wasn't sure if things are not working because it is in staging -- like the send reminders -- they might have that turned off so people are not getting spammed with emails from a demo account. I also left the one with the multiple update buttons on a single page as that might be intentional as that page has the potential to be very very long and it may have been requested.

Thanks so much for all this.

**Comment by msespos** [comment]
Glad I was able to help @seanmarcia ! Will be adding some more today, from the admin POV.

**Comment by msespos** [comment]
<img width="1522" alt="Screen Shot 2023-01-13 at 12 18 11 PM" src="https://user-images.githubusercontent.com/62808851/212411617-d68f93e0-16d5-476f-91b9-456bbc252261.png">

casa_admins

I believe this button should be the darker blue.

**Comment by msespos** [comment]
<img width="1451" alt="Screen Shot 2023-01-13 at 12 21 25 PM" src="https://user-images.githubusercontent.com/62808851/212412129-c690286c-a4bc-4f42-8d55-afebd761d751.png">

reimbursements

Occurred At column is showing a bug.

**Comment by msespos** [comment]
<img width="761" alt="Screen Shot 2023-01-13 at 12 23 15 PM" src="https://user-images.githubusercontent.com/62808851/212412405-5876b4cd-a6da-4656-8b39-c1fbbf273845.png">

reports

When clicking on Download Report, the button displays "False" while downloading, then goes back to displaying "Download Report".

**Comment by msespos** [comment]
<img width="1524" alt="Screen Shot 2023-01-13 at 12 25 31 PM" src="https://user-images.githubusercontent.com/62808851/212412724-204ea96c-e9bb-46b1-bc5a-ff8b5dcbbd87.png">

imports

Should this button be the darker blue or should it be green?

**Comment by msespos** [comment]
<img width="1526" alt="Screen Shot 2023-01-13 at 12 26 41 PM" src="https://user-images.githubusercontent.com/62808851/212412892-7cb2fd27-df73-4488-9c75-13047e128de0.png">

mileage_rates

I believe this button should be the darker blue.

**Comment by msespos** [comment]
<img width="1526" alt="Screen Shot 2023-01-13 at 12 26 41 PM" src="https://user-images.githubusercontent.com/62808851/212412892-7cb2fd27-df73-4488-9c75-13047e128de0.png">

mileage_rates

Clicking on edit shows an error on Heroku.

**Comment by msespos** [comment]
<img width="1492" alt="Screen Shot 2023-01-13 at 12 42 13 PM" src="https://user-images.githubusercontent.com/62808851/212415462-fd95b75b-8527-48e5-a544-3a4c6c0607ee.png">

casa_admins/114/edit

The Deactivate, Resend Invitation, and Change to Supervisor buttons are not in the usual style. For consistency I think they should be in the larger red outlined buttons that similar pages have.

**Comment by msespos** [comment]
<img width="1000" alt="Screen Shot 2023-01-13 at 12 52 17 PM" src="https://user-images.githubusercontent.com/62808851/212416947-59ff41b9-f26e-401a-9e11-90aa6ac5b206.png">

all_casa_admins/edit

Two things:

1) Should the Change Password button be yellow?

2) The Change Password button doesn't appear to do anything when clicked.

**Comment by FireLemons** [comment]
If there's desired work documented here, it should be made into smaller issues

**Comment by seanmarcia** [comment]
Deployed.
