### ISSUE TITLE
New Theme - casa_cases pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4306]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/casa_cases` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] _calendar_button.html.erb
- [ ] _court_dates.html.erb
- [ ] _filter.html.erb
- [ ] _form.html.erb
- [ ] _inactive_case.html.erb
- [ ] _other_duties.html.erb
- [ ] _thank_you_modal.html.erb
- [ ] _volunteer_assignment.html.erb
- [ ] edit.html.erb
- [ ] index.html.erb
- [ ] new.html.erb
- [ ] show.html.erb

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by Isaac-alencar** [comment]
Hi, @seanmarcia ! I can work on this issue, could you please assign to me?

**Comment by seanmarcia** [comment]
Hey @Isaac-alencar  do you have any updates on your progress? We are in a bit of a rush to get this out the door as the framework we are replacing, bootstrap 4, is now past its end of life and is no longer getting updates and security fixes as of January 1st. (https://endoflife.date/bootstrap)

Are you able to get this finished by Friday the 6th so we can review over the weekend and hopefully get this deployed quickly and avoid any security concerns with the application?

Sorry for the pressure, we absolutely want you to be successful and to meaningfully contribute but we need to ensure that the application remains secure given the extremely vulnerable population it supports.

**Comment by Isaac-alencar** [comment]
Hi @seanmarcia! I can deliver by Friday, for sure. Thanks to being patient
