### ISSUE TITLE
New Theme - case_assignment and case_court_reports pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4308]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the `/views/case_assignment` to use the new theme.
* Update all the views in the `/views/case_court_reports ` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] index.html.erb - case_assignment
- [x] index.html.erb - case_court_reports

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by italomatos** [comment]
Hi @seanmarcia ! How are you?
I didn't find any route that go case_assignments/index.html.erb 
Is it not better remove this file?

**Comment by seanmarcia** [comment]
Hey @italomatos looks like we may have merged you PR a little too quick!

I took a look and the immediate feedback:
Can you add the download icon to the generate report button as well as adding the `btn-sm` class to make it the same size as the other buttons that have been created elsewhere? You can see an example how this was done in the `reports/index.html` file.

It also looks like the select2 isn't behaving quite right -- it doesn't appear to be picking up bootstrap5 updates -- I don't know if we've had to convert anything other select2 selectors yet for the new bootstrap5 theme so I don't have a lot of advice yet. This may help: https://apalfrey.github.io/select2-bootstrap-5-theme/

**Comment by italomatos** [comment]
Hi @seanmarcia thank you for feedback. I fixed two items and open a new PR: https://github.com/rubyforgood/casa/pull/4368

And about case_assignments/index.html.erb, I cant see any route that go to this page. Can we remove this page?

**Comment by seanmarcia** [comment]
We should probably be able to remove the page but I'd like someone from the core team to weigh in first.
