### ISSUE TITLE
New Theme - emancipation_checklists, emancipations, and fund_requests pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4315]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/emancipation_checklists ` to use the new theme.
* Update all the views in the the `/views/emancipations ` to use the new theme.
* Update all the views in the the `/views/fund_requests ` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] index.html.erb - emancipation_checklists
- [ ] download.html.erb - emancipations
- [ ] show.html.erb - emancipations
- [ ] new.html.erb - fund_requests

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by Learningstuff98** [comment]
@compwron I can work on this

**Comment by seanmarcia** [comment]
Awesome, yours!
