### ISSUE TITLE
New Theme - learning_hours pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4320]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/learning_hours` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] _confirm_note.html.erb
- [ ] _form.html.erb
- [ ] _update_form.html.erb
- [ ] edit.html.erb
- [ ] index.html.erb
- [ ] new.html.erb
- [ ] show.html.erb

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by anshu1992** [comment]
Hello @seanmarcia, I would like to work on this one.

**Comment by seanmarcia** [comment]
Yours!
