### ISSUE TITLE
New Theme - notes and notifications pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4322]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/notes` to use the new theme.
* Update all the views in the the `/views/notifications` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [x] edit.html.erb - notes
- [x] _notification.html.erb - notifications
- [x] _patch_notes.html.erb - notifications
- [x] index.html.erb - notifications

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by tacoda** [comment]
👋  I'd like to work on this.

**Comment by seanmarcia** [comment]
Yours!

**Comment by tacoda** [comment]
Still working on this

**Comment by seanmarcia** [comment]
Hey @tacoda thanks for letting us know you are still working on it, do you have any updates on your progress? We are in a bit of a rush to get this out the door as the framework we are replacing, bootstrap 4, is now past its end of life and is no longer getting updates and security fixes as of January 1st. (https://endoflife.date/bootstrap)

Are you able to get this finished by Friday the 6th so we can review over the weekend and hopefully get this deployed quickly and avoid any security concerns with the application?

Sorry for the pressure, we absolutely want you to be successful and to meaningfully contribute but we need to ensure that the application remains secure given the extremely vulnerable population it supports.

**Comment by tacoda** [comment]
I'll spend some time working on this today. I think I can get this ready for review for the weekend. I'll post whatever I have to a PR by then so it's available.

**Comment by tacoda** [comment]
@seanmarcia I'm working on the notifications pages right now, but I'm not seeing anything that has to change (in terms of classes when referring to the Bootstrap 5 docs). Just wanted to verify this with you because the only other example of this use-case is in an open issue, so there's no code for me to investigate to find corollary classes. Does this UI look correct for `/notifications`?

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/39019266/211040295-c9478dcf-5caf-47e6-9cf9-8c1434268da9.png">

**Comment by tacoda** [comment]
Update: Since I cannot find a relevant code example and I cannot seem to find a changelog, I'm pressing on using this as a guide: https://getbootstrap.com/docs/5.0/migration/

**Comment by seanmarcia** [comment]
@tacoda Looking at the notifications page it looks different from other pages to me:

Supervisors:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/667909/211062056-9d8afa8d-b8ba-471a-80f9-447f6b7174e7.png">

Notifications:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/667909/211062152-48e4e0fd-1786-424d-a432-688107bdeac7.png">

We'd like it to be in line with the new theme of the app so the uses have a consistent experience.

**Comment by tacoda** [comment]
👍  Thanks for the use-case example!

**Comment by tacoda** [comment]
@seanmarcia  Quick update: I'm calling it a day. I pushed another change to my fork. Notifications page looks good, but I'm trying to add notifications to style them. I was able to create some notifications in the console, but I'm working through figuring out the type and params. I don't want to shave this yak forever, but there are no seeds for notifications. Open to suggestions.

**Comment by seanmarcia** [comment]
Are you able to submit a PR for the completed work?

I'll be honest, I don't quite know how notifications work. I'd probably check if there is a factorybot factory to create some.

**Comment by tacoda** [comment]
Sure, I was planning on wrapping up what I have in a PR tomorrow.
