### ISSUE TITLE
New Theme - supervisors pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4326]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/supervisors` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] _manage_active.html.erb
- [ ] edit.html.erb
- [ ] new.html.erb

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by Isaac-alencar** [comment]
Hi @seanmarcia, I can work on this issue!

**Comment by seanmarcia** [comment]
Awesome! It's yours :)

FYI - There may be a partial from the `/shared` directory that needs converting too.

**Comment by seanmarcia** [comment]
Hey @Isaac-alencar sorry we merged too quick!

Here is a PR that has the stylings for the list https://github.com/rubyforgood/casa/pull/4365 (I'd probably use the `ban` icon for the unassign though)

You can find lots of button styling examples elsewhere!

Please submit another PR with these additions!

**Comment by Isaac-alencar** [comment]
Okay! I apologize for the delay @seanmarcia , I'm planning to send the new PR tomorrow morning!

**Comment by Isaac-alencar** [comment]
@seanmarcia! Apologies for delaying this fix, but here's the new PR https://github.com/rubyforgood/casa/pull/4393
