### ISSUE TITLE
New Theme - users pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4327]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/users` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] _languages.html.erb
- [ ] edit.html.erb

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by raychiranjib1** [comment]
Please assign this ticket to me.

**Comment by seanmarcia** [comment]
Awesome! It's yours.

**Comment by seanmarcia** [comment]
Hey @raychiranjib1 looks like we merged your PR before you could make the changes that were requested. Can you submit another PR with the requested changes?

Here is an example PR that shows the formatting of the list https://github.com/rubyforgood/casa/pull/4365 

Thanks!
