### ISSUE TITLE
New Theme - all_casa_admins pages

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4329]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/all_casa_admins` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] _form.html.erb
- [ ] _manage_active.html.erb
- [ ] _manage_cases.html.erb
- [ ] _manage_supervisor.html.erb
- [ ] _notes.html.erb
- [ ] _send_reminder_button.html.erb
- [ ] _volunteer_reminder_form.html.erb
- [ ] edit.html.erb
- [ ] index.html.erb
- [ ] new.html.erb

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.
**Description**

**Comment by msespos** [comment]
Happy to take this on. It would be my first time contributing to rubyforgood and casa! Let me know if there is anything I should know beyond what's in the description and directions above.

**Comment by seanmarcia** [comment]
There are a good chunk of pages but it should be fairly straightforward. You can look at some of the other pages that folks have been converting if you are stuck.

Thank you so much for taking this on!!!

**Comment by msespos** [comment]
So I just forked and cloned the repo and I ran the tests using bundle exec rspec, and there are a lot of failing tests. I know I'm supposed to make sure all the tests are passing before I make my PR. Is there anything I should do about all of these failing tests, given that i haven't done any work yet? Or can I just make the changes and the PR with the failing tests as they are? Thanks very much!

**Comment by msespos** [comment]
Also maybe I am doing this incorrectly, but after forking and cloning I only have a main branch. How do I locate the `new_theme` branch? Sorry if these are obvious questions; I want to make sure I get my first PR correct!

**Comment by seanmarcia** [comment]
Hey @msespos is checking out the branch not working? `git checkout new_theme` 
You might have something in your gitconfig blocking it... I'm not sure. Does it give you an error message?

**Comment by msespos** [comment]
I get `error: pathspec 'new_theme' did not match any file(s) known to git`.

This is the content of my `.git/config` file:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:msespos/casa.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[alias]
  st = status
  add = add
  com = commit -m
  pus = push origin main
  hist = log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short
[remote "upstream"]
	url = https://github.com/rubyforgood/casa.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
```

**Comment by msespos** [comment]
Should I have forked and cloned the repo? Did I "lose" the branches by creating a local clone to work on? That's how I'm used to doing it for other projects, but maybe it's the wrong way to do it here.

Thanks @seanmarcia!

**Comment by seanmarcia** [comment]
Ah! I didn't realize you forked :) My bad.

If you just clone the repo without forking it you should have access to all the branches :)

**Comment by msespos** [comment]
Ahhh OK I didn't realize that I should have just cloned! I will do that. Thanks!

**Comment by seanmarcia** [comment]
Hey @msespos you should rebase from main -- there has been a bit of cleanup and continued work that is likely going to affect the `all_casa_admins` pages. :)

**Comment by msespos** [comment]
OK, thanks @seanmarcia - I actually just switched to a new machine and cloned a new repo to start working on, so I'm about to create a new branch anyway. Does that work? Thanks!

**Comment by seanmarcia** [comment]
Hey @msespos do you have any updates on your progress? We are in a bit of a rush to get this out the door as the framework we are replacing, bootstrap 4, is now past its end of life and is no longer getting updates and security fixes as of January 1st. (https://endoflife.date/bootstrap)

Are you able to get this finished by Friday the 6th so we can review over the weekend and hopefully get this deployed quickly and avoid any security concerns with the application?

Sorry for the pressure, we absolutely want you to be successful and to meaningfully contribute but we need to ensure that the application remains secure given the extremely vulnerable population it supports.

**Comment by msespos** [comment]
Hi @seanmarcia thanks for checking in. I am about 1/3 of the way through the style changes and am about 75% likely to finish them all by Friday. I have also been chasing down some intermittent but serious bugs from the new theme branch. E.g. the profile menu stops working. I’m not sure I can fix those bugs by Friday, but will try. I’ll update you on my progress tomorrow night.

**Comment by msespos** [comment]
Hi @seanmarcia here is my update as promised. I am about 95% done with editing the files. I plan to wrap it up and look it over tomorrow morning. I expect to make the PR by the end of the day tomorrow (Friday). Thanks for your patience.

**Comment by msespos** [comment]
Hi @seanmarcia so I'm done with my changes and ready to submit. However I'm receiving this message when I try to push:

ERROR: Permission to rubyforgood/casa.git denied to msespos.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I used 
[remote "origin"]
url = git@github.com:rubyforgood/casa.git

in my git/config.

Could you advise me of how to successfully push those changes?

Thanks!

**Comment by seanmarcia** [comment]
You should have a collaborator invitation to the repo. Also ensure that you are not pushing to main and instead pushing a branch up :)

**Comment by msespos** [comment]
I got the invitation and accepted, but it appears to only give me view access. Could you give me write access please? I will then push to update-theme-for-all-casa-admins-pages (my branch off of new_theme).

**Comment by seanmarcia** [comment]
I must have clicked the wrong button, please try again :)

**Comment by msespos** [comment]
Thanks @seanmarcia - the PR went through. I left the following comment there, but just in case, here it is again:

I found a number of bugs in the process of applying the new theme. Please let me know if I should submit a bug report and if so, where the best place is to do that. Thanks!

And thanks for the opportunity to contribute!

**Comment by seanmarcia** [comment]
Hey @msespos we'd love to hear about any bugs you found. Feel free to drop them in this issue or message me in the Ruby for Good slack.

It looks like you didn't branch off of the new theme and instead branched off of main which is trying to pull a lot of other items into your PR -- we're waiting til all the theme work is finished before merging in all the changes on main so we only have to do it once.

Can you remake your PR but this time branch off of the `new_theme` branch?

**Comment by msespos** [comment]
Hi @seanmarcia - I'll message you my bug report in the Ruby for Good slack. Thanks!

I believe I did branch off of the new theme, but i also did a rebase from main, which you asked me to do above. Could that be the source of the problem? If so, what is the fix? Will I have to make all of the changes again without rebasing from main?  Thanks again!

**Comment by seanmarcia** [comment]
Yeah, that was my typo. I meant the main working branch which is new_theme. This was to ensure that you didn't do work that someone else may have also been doing -- the all_casa_admin uses some of the partials in /views/shared that other views use so if someone else had modified them first and then you modified them it would cause a conflict.

**Comment by msespos** [comment]
OK, I see. That makes sense and thanks for clarifying. Given that I did branch off of new_theme, but then rebased from main rather than new_theme, what's my best move going forward?
