### ISSUE TITLE
New Theme -  Landing Page Text

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4330]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

When spiking out the new theme I put some filler text and capabilities for the site on the landing page but the core team should validate and clarify what is there. Illustrations used on the landing site are from [storyset](https://storyset.com/data) if more graphics are needed.

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the text, testimonials, and other information on the new landing page

- [ ] The landing page `/app/views/static/index.html.erb` has relevant text for the application.

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by littleforest** [comment]
Are testimonials something we are going to be getting?

**Comment by littleforest** [comment]
I started a branch `4330-new-theme-landing-page` with some tiny edits.

**Comment by seanmarcia** [comment]
If you want testimonials you can keep that section. The landing page is based on what I've seen on others -- if we don't want that section we can remove it. I thought if a random casa org found the site they might reach out to pgcasa -- or whoever gives a testimonial -- and ask if we are legit.

**Comment by littleforest** [comment]
It seems like we should be able to get some testimonials from Prince George's and Montgomery County at least.

**Comment by seanmarcia** [comment]
@littleforest want to put in a PR for the changes you've made? We can keep adding to it but this way others can build off of your work easier.
