### ISSUE TITLE
New Theme - Helper Methods

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4331]
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

The helper methods need to be updated for the new theme. Specifically, the ones that make the sidebar work like `active_class`, `menu_item`, and so on. The current sidebar is being expanded to demo how the active class works but it shouldn't start in the state it is in.

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update the helper methods so the sidebar accurately shows which page the user is on and expands/contracts the menu as expected.

- [ ] Sidebar works as expected
- [ ] Other helper items make things easier to use

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by anshu1992** [comment]
Hello, wanted to know if this issue is taken. If not I can pick it up.

**Comment by anshu1992** [comment]
Hey @seanmarcia, I would like to take it.

**Comment by jimnanney** [comment]
Go ahead @anshu1992, @seanmarcia had assigned it to me, but I was out of town until today. Sorry about the lack of response.
