### ISSUE TITLE
add real user Testimonials to site

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#4407]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

Part of #4304

We updated the landing page (`casavolunteertracking.org` / https://github.com/rubyforgood/casa/blob/main/app/views/static/index.html.erb) with a new theme but updating the testimonials got lost in the shuffle. Currently we have lorem ipsum instead. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/6b0f990c-8ab7-4bc7-afaa-005a3411f0cf)

Replace the images and test in the testimonials section with these images:

<img width="681" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/44e685d8-e10f-4059-8939-a09b06ad1640">
<img width="692" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/710303ca-69b9-4ef2-aac7-b6b56b793009">

Update the **testimonials** on the new landing page. We should probably be able to get some testimonials from Prince George's and Montgomery County at least.

Please be sure to use PNG files, not screenshots 👍🏼 and provide screenshots of your work. Ping @bcastillo32 or me if you can't grab the PNGs from this issue.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by littleforest** [comment]
still working

**Comment by littleforest** [comment]
still working

**Comment by littleforest** [comment]
still working

**Comment by littleforest** [comment]
@Nerajno we still need to get the testimonial copy from the stakeholders, so there's nothing to do for this one yet! But thank you for checking. I will move it out of To-Do.

**Comment by Nerajno** [comment]
We could just ask them but I will wait.

**Comment by compwron** [comment]
Did we do this? Did Brandon get them?

**Comment by compwron** [comment]
![Image](https://github.com/rubyforgood/casa/assets/578159/22474967-c1a5-472c-99ea-c69d9564c68e)

still needs doing - just put in the text that Brandon provides @bcastillo32

**Comment by compwron** [comment]
these might be in slack?

**Comment by josephmsmith** [comment]
Picking this up after chatting in office hours!

**Comment by jonathanmeneses** [comment]
To groom this issue out a bit more, would we want both the shared images in the testimonials section (stacked vertically)? 

Likewise, how should we reach out to stakeholders and ask for testimonials? Could we use our next bi-weekly meeting to ask for them?

**Comment by elasticspoon** [comment]
> To groom this issue out a bit more, would we want both the shared images in the testimonials section (stacked vertically)?
Yup. Just replace the existing sections with the images. 

> Likewise, how should we reach out to stakeholders and ask for testimonials? Could we use our next bi-weekly meeting to ask for them?

Could we? Yea. But it's pretty low priority to get additional testimonials when we already have two existing ones that just need to be inserted into that page.

**Comment by jonathanmeneses** [comment]
Went ahead and just took a stab at this instead of asking for permission since this has sat open long enough!

**Comment by compwron** [comment]
:)
