### ISSUE TITLE
New Theme - Change Heart in Footer

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#4413]
This is part of https://github.com/rubyforgood/casa/issues/4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme.

Directions
Checkout the new_theme branch and create a branch off of that branch for your work.
The footer currently has an animated emoji of a heart in it. We would like to change this to a static emoji of a heart for accessibility reasons. 

Things to consider:
It is difficult to keep the new_theme branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

**Comment by seanmarcia** [comment]
Fixed
