### ISSUE TITLE
Add Icon to Submit On Language Edit Page

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4435]
**Description**

The submit button on the language edit page is missing the same icon as the other submit icons. The button is also the wrong size, it should have the `btn-sm` class applied to it as well.

Fork from the `new_theme` branch, make your fixes, and submit a PR to the `new_theme` branch.

Part of #4304

**Comment by seanmarcia** [comment]
Looks like the new judge page needs the exact same thing if you wanted to fix two things :)

**Comment by rae-stanton** [comment]
@seanmarcia I submitted a PR for the resize, but I couldn't figure out what differences in styling for the buttons you were talking about.

**Comment by seanmarcia** [comment]
To add the same icon that other submit buttons have.
