### ISSUE TITLE
maintainer upgrade heroku stack

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4449]
This app is using the Heroku-20 stack, however a newer stack is available.
To upgrade to Heroku-22, see:
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by littleforest** [comment]
heroku-22 stack working fine on casa-qa. I set casa-production to change to heroku-22 stack after next deploy:

```
$ heroku stack:set heroku-22 -a casa-production
Setting stack to heroku-22... done
You will need to redeploy ⬢ casa-production for the change to take effect.
```

cc: @FireLemons
