### ISSUE TITLE
Bug: Clicking on New Case Contact with cached data can incorrectly populate case number selection. Looks like local storage is not clearing after successful submit.

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4451]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
all (found in prod)

### Current Behavior
Bug: Clicking on New Case Contact with cached data can incorrectly populate case number selection. Looks like local storage is not clearing after successful submit.

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Jaskaran2** [comment]
Hi @compwron is it ok if I may pick up this bug?
