### ISSUE TITLE
New Theme Fix Tests

### ISSUE THREAD

**Issue by seanmarcia** [rubyforgood/casa#4455]
Part of #4304 

We've completed the cosmetic fixes for the new theme and now we need to update the tests to reflect it the new look and feel. The current test suite uses the old theme and is using CSS classes that have changed as well as some differences on the pages.

Create a branch from the `new_theme` branch and submit your test fixes to it.

Take a look at the QA site - [casa-qa.herokuapp.com/](https://casa-qa.herokuapp.com/) to compare the old site to the new one when performing your updates.

We currently have about ~13 failing tests. It looks like they are almost entirely related to how things display now. For example, buttons now have icons in them so when the test looks to click the button `Add New Court Report` it can't find an exact match because it is now `+ Add New Court Report`. Or the error messages are different. And so on.

We'd sincerely appreciate pull requests addressing these broken tests! Since a lot of these tests will just require minor updates we request that each pull request fixes a minimum of 15 tests and we'll merge them as they come in!

Feel free to comment in this issue on the blocks of tests you are going to address so others also don't pick them up.

You can see the current failing tests [here](https://github.com/rubyforgood/casa/actions/runs/4153751533/jobs/7185573995).

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-1kfeimohe-KL~~~6Lkof7G94_7Ojd_Hw) #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hi @seanmarcia, can I do failures 4 - 23 to start?
./spec/system/deep_link/deep_link_spec.rb for failures 4-9
./spec/system/sessions/new_spec.rb for 10-23

**Comment by ShamiTomita** [comment]
My RSpec deduction skills aren't great (yet) but I've manually gone through the original failures to check which were still failing...but only up to 60 for right now: 

24 - ./spec/views/all_casa_admins/casa_orgs/new.html.erb_spec.rb
25 - 26 ./spec/system/all_casa_admins/sessions/new_spec.rb
27 -30 - ./spec/system/notifications/index_spec.rb
31 - good! 
32-36 ./spec/views/supervisors/index.html.erb_spec.rb
37 - good!

38 - 41 good! 
42 - good! 

43 - ./spec/views/checklist_items/edit.html.erb_spec.rb
44-45 -./spec/system/volunteers/new_spec.rb:34

46 - good! 

47 - ./spec/views/hearing_types/new.html.erb_spec.rb
48 -./spec/views/court_dates/edit.html.erb_spec.rb 

49 - 50 good! 

51 -./spec/system/court_dates/edit_spec.rb

53 - good! 
54 - good! 
57 - good! 

52 + 55-56 + 58 ./spec/system/casa_cases/edit_spec.rb
59 -60 ./spec/system/all_casa_admins/dashboard/show_spec.rb

I'm gonna tackle the next 15 failing tests so failures 24-45!

**Comment by seanmarcia** [comment]
@ShamiTomita I updated the link to the failing tests and you should be able to view the updated list by going to to [WIP PR](https://github.com/rubyforgood/casa/pull/4279) and looking at the actions.

**Comment by ShamiTomita** [comment]
@seanmarcia Ah gotcha, thank you!

**Comment by Learningstuff98** [comment]
@seanmarcia I can work on the following tests:

rspec ./spec/views/court_dates/new.html.erb_spec.rb:19 # court_dates/new is expected to have visible css ".btn-primary"

rspec ./spec/views/court_dates/new.html.erb_spec.rb:16 # court_dates/new is expected to have visible css "h1" with text "New Court Date"

rspec ./spec/views/case_court_reports/index.html.erb_spec.rb:18 # case_court_reports/index Volunteer views 'Generate Court Report' form has a Bootstrap card with card title 'Generate Court Report'

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:188 # layout/sidebar when logged in as a casa admin renders display name and email

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:163 # layout/sidebar when logged in as a casa admin renders the correct Role name on the sidebar

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:40 # layout/sidebar when logged in as a supervisor renders the correct Role name on the sidebar

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:63 # layout/sidebar when logged in as a supervisor renders display name and email

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:106 # layout/sidebar when logged in as a volunteer renders display name and email

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:84 # layout/sidebar when logged in as a volunteer renders the correct Role name on the sidebar

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:201 # layout/sidebar notifications displays badge when user has notifications

rspec ./spec/views/layouts/sidebar.html.erb_spec.rb:233 # layout/sidebar impersonation renders correct Role name when impersonating a volunteer

rspec ./spec/system/volunteers/index_spec.rb:225 # view all volunteers supervisor user can show/hide columns on volunteers table

rspec ./spec/system/volunteers/index_spec.rb:55 # view all volunteers admin user can show/hide columns on volunteers table

rspec ./spec/views/judges/new.html.erb_spec.rb:13 # judges/new shows new judge form

rspec ./spec/system/volunteers/edit_spec.rb:381 # volunteers/edit impersonate button when user is a supervisor impersonates the volunteer

**Comment by ShamiTomita** [comment]
I'm gonna start on the following spec files:

./spec/system/case_contacts/new_spec.rb (89, 255, 304, 347)
./spec/system/reports/export_data_spec.rb (6, 37)
./spec/views/checklist_items/new.html.erb_spec.rb (18)
./spec/requests/case_court_reports_spec.rb (75)
./spec/system/supervisors/edit_spec.rb (9)
./spec/system/all_casa_admins/casa_orgs/new_spec.rb (13, 46, 63)
./spec/views/hearing_types/edit.html.erb_spec.rb (13)
./spec/views/layouts/application.html.erb_spec.rb (9, 13, 14, 19)

**Comment by anshu1992** [comment]
This [PR](https://github.com/rubyforgood/casa/pull/4535) fixes the following 15 specs.

```
rspec ./spec/system/case_contacts/new_spec.rb:(347, 304, 255, 89)
rspec ./spec/system/case_court_reports/index_spec.rb:(120, 128, 183, 194, 166, 155, 99, 91, 220)
rspec ./spec/system/casa_cases/show_more_spec.rb:41
rspec ./spec/system/casa_cases/new_spec.rb:49
```

**Comment by anshu1992** [comment]
Working on next 15. Here are the ones I have picked to fix next.

```
rspec ./spec/system/casa_cases/new_spec.rb (81, 101, 120,69)
rspec ./spec/system/casa_cases/show_spec.rb (154, 146, 163, 100, 191)
rspec ./spec/requests/other_duties_spec.rb (237, 220)
rspec ./spec/requests/case_court_reports_spec.rb (75)
rspec ./spec/views/hearing_types/edit.html.erb_spec.rb (13)
rspec ./spec/system/supervisors/edit_spec.rb (74, 9)
```

**Comment by anshu1992** [comment]
Picked the following 18 specs to fix now:

```
rspec ./spec/system/case_contacts/additional_expenses_spec.rb (50, 124)
rspec ./spec/system/checklist_items/destroy_spec.rb (13)
rspec ./spec/system/reports/export_data_spec.rb (6, 37)
rspec ./spec/system/notifications/index_spec.rb (72, 93, 115, 40)
rspec ./spec/views/checklist_items/new.html.erb_spec.rb (18)
rspec ./spec/system/casa_cases/emancipation/show_spec.rb (25)
rspec ./spec/system/devise/passwords/new_spec.rb (28, 18, 9, 33)
rspec ./spec/system/all_casa_admins/casa_orgs/new_spec.rb (13, 46, 63)
```

After picking 15 there were only 3 more specs that remained so picked all of them. But if it is strictly not allowed then I will remove them, just let me know.

**Comment by seanmarcia** [comment]
Awesome! We're down to 49 failing tests :)

**Comment by seanmarcia** [comment]
Down to 13 failing tests:

rspec ./spec/system/volunteers/index_spec.rb:225 # view all volunteers supervisor user can show/hide columns on volunteers table
rspec ./spec/system/volunteers/index_spec.rb:55 # view all volunteers admin user can show/hide columns on volunteers table
rspec ./spec/system/casa_cases/emancipation/show_spec.rb:25 # casa_cases/show volunteer user opens through main input, selects an option, and unselects option through main input
rspec ./spec/views/court_dates/new.html.erb_spec.rb:19 # court_dates/new is expected to have visible css ".btn-primary"
rspec ./spec/models/learning_hours_report_spec.rb:20 # LearningHoursReport#to_csv when there are learning hours includes all learning hours
rspec ./spec/models/case_contact_spec.rb:422 # CaseContact#contact_groups_with_types returns the groups with their associated case types
rspec ./spec/system/case_contacts/additional_expenses_spec.rb:124 # addtional_expenses additional expenses for maximum entries
rspec ./spec/system/case_contacts/additional_expenses_spec.rb:50 # addtional_expenses additional expenses for multiple entries
rspec ./spec/system/checklist_items/destroy_spec.rb:13 # checklist_items/destroy deletes checklist items
rspec ./spec/system/all_casa_admins/edit_spec.rb:18 # all_casa_admin_edit_spec with valid parameters updates password
rspec ./spec/system/all_casa_admins/edit_spec.rb:12 # all_casa_admin_edit_spec with valid parameters updates email
rspec ./spec/system/case_contacts/edit_spec.rb:146 # case_contacts/edit volunteer user autosaves notes
rspec ./spec/system/case_contacts/index_spec.rb:40 # case_contacts/index with case contacts filtering case contacts by date of contact only shows the contacts with the correct date

**Comment by ShamiTomita** [comment]
I can tackle these 13 tests
