### ISSUE TITLE
Get readme test coverage badge working

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#446]
Test coverage is being calculated but the badge doesn't show https://codeclimate.com/github/rubyforgood/casa
<img width="1046" alt="Screen Shot 2020-07-26 at 10 03 45 AM" src="https://user-images.githubusercontent.com/578159/88484950-52ea9180-cf27-11ea-81c9-9906cd8a9eca.png">

**Comment by rafaeelaudibert** [comment]
The Test Coverage one is actually working, being displayed as <a href="https://codeclimate.com/github/rubyforgood/casa/test_coverage"><img src="https://api.codeclimate.com/v1/badges/24f3bb10db6afac417e2/test_coverage" /></a> like noted on https://codeclimate.com/github/rubyforgood/casa/badges#test-coverage-html.

Screenshot:
![image](https://user-images.githubusercontent.com/32079912/95162252-99583a00-077b-11eb-8d67-c2cf6c1322ea.png)

So, this issue can be closed
