### ISSUE TITLE
Reimbursement Request Email Recipients

### ISSUE THREAD

**Issue by volatile3** [rubyforgood/casa#4474]
Closely related to #4673 

**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Context**

- Supervisors get a weekly email. Reimbursement request should be in this weekly email, even if it's just a file attachment of the reimbursement requests.
- There's one person at every casa that does reimbursements and needs to know about all of them, regularly. So this should be a supervisor who needs to know all about all of them.
- It's ok if there's more than one per casa org.
- On the Supervisor's screen, you should be able to designate this user as someone who receives this regular reimbursement report.
- A volunteer cannot be a reimburser
- Will receive a wrap-up email with everybody's request (which doesn't exist yet)
- Timing: quarterly is minimum - more frequent would be better. Just email a copy of the CSV from the mileage queue. (Not yet finished / approved / fulfilled).

**Description**

1. Add checkbox on the `Supervisors#edit` screen (https://casa-qa.herokuapp.com/supervisors/5/edit)  with the text "Will receive reimbursement request emails".
2. When the checkbox is enabled, it will show a line of text under the password reset line, "Will receive reimbursement request emails" options are yes or no.
3. When we send weekly activity email reports to supervisors, include this report for the correct supervisors
4. Automated tests should be included

**Screenshots of current behavior** 
![Screenshot_20230124_092435](https://user-images.githubusercontent.com/123524778/214466721-529851ca-2f9e-4989-8bb8-722d0dca2259.png)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by anshu1992** [comment]
@volatile3 I can work on this.

**Comment by compwron** [comment]
:)

**Comment by dpaola2** [comment]
1. Supervisors get weekly email, this should be in the email
2. There's one person at ever casa that does reimbursements and needs to know about all of them - like a reimburser person, needs to know all about all of them. Everything is per casa org, never cross the streams. It's ok if there's more than one per casa org. It shouldn't be all volunteers or all admins. On the user screen, you should be able to designate this. a volunteer cannot be a reimburser. Will receive a wrap-up email with everybody's request (which doesn't exist yet). Quarterly is minimum - more frequent would be better. Just email a copy of the CSV from the mileage queue. (Not yet finished / approved / fulfilled).

**Comment by compwron** [comment]
The stakeholders asked today where we are at with this. They are excited for this functionality!

**Comment by jamgar** [comment]
I am with the Agency of Learning program, and going to attempt this if someone has not already done it.

**Comment by jamgar** [comment]
Please refer to https://github.com/rubyforgood/casa/issues/4476 as these two issues overlap. Per conversation on slack the issue will be covered with 4476.

**Comment by jamgar** [comment]
PR has been submitted
