### ISSUE TITLE
Add respective CASA logo to their landing pages

### ISSUE THREAD

**Issue by volatile3** [rubyforgood/casa#4475]
**What type(s) of user does this feature affect?**
 - non-logged in users  
 
**Description**
Add the logos of the specific CASAs we're serving to the landing page on the `new-theme` branch.  
 - Create a new section on the landing page titled
    "Casa Organizations Powered by Our App"
 - Make sure pictures of the logos are under this section
 - Every Casa has uploaded their own logos, use those.
 - Make sure it doesn't look weird on mobile views

**Screenshots of current behavior, if any**    
![Screenshot_20230124_094822](https://user-images.githubusercontent.com/123524778/214469490-faef1f00-3c4c-4444-8dee-5be25f332a95.png)  

https://casa-new-theme.herokuapp.com/

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by t-bello7** [comment]
I would like to work on this task
