### ISSUE TITLE
Let supervisors see mileage queue and learning hours

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4486]
**What type(s) of user does this feature affect?**
 - supervisors

**Description**
Let supervisors see mileage queue and learning hours
https://casa-qa.herokuapp.com/reimbursements
~https://casa-qa.herokuapp.com/reports Learning Hours Report button~

Stakeholder request - NK 27 jan 2023

<img width="734" alt="Screenshot 2023-01-27 at 11 06 14 AM" src="https://user-images.githubusercontent.com/578159/215173719-d1dc68a3-5eb5-4639-bd50-3c0f6a1f5a7f.png">

Update the tests

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by anshu1992** [comment]
I can work on this.

**Comment by dominiclizarraga** [comment]
Hi @FireLemons  please assign it to me.

**Comment by FireLemons** [comment]
Supervisors aren't allowed to look at the mileage queue

**Comment by FireLemons** [comment]
Supervisors still need to see the mileage queue which is also referred to as reimbursements

**Comment by dominiclizarraga** [comment]
Hi Shen, sure, Today I'll review this.
