### ISSUE TITLE
Limit reimbursement requests to particular cases

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4488]
**What type(s) of user does this feature affect?**
 - volunteers - change a permissions
 - supervisors - set a permission
 - admins - set a permission

**Description**
this is re-requested by stakeholder JH
Only allow specific volunteers to request reimbursement
OR do it by CASE? Can set it per case_assignment. Want to avoid ambiguity since there are some rare cases where a case has multiple volunteers.
How to do this on the UI? Some kind of mass management? 
Why? Not a lot of grants to reimburse for mileage

Supervisors should be able to allow or disallow someone to get a reimbursement.

Acceptance criteria
1. Make a new org-level setting, defaulting to SHOWING request for reimbursement (add to Org Settings page
2. when the setting is set to NOT allow reimbursement requests, hide the reimbursement request section on Create Case Contact

In a LATER issue:
2. For each CASE, add an override (only like 2 cases are eligible for stakeholder JH), "this case IS eligible for mileage reimbursement" setting on case

**Screenshots of current behavior, if any**  

remove the highlighted part but not the whole thing ,
<img width="638" alt="Screenshot 2023-01-27 at 11 20 44 AM" src="https://user-images.githubusercontent.com/578159/215178325-3ac5f8b9-83a9-42ab-8871-e84c6551e07d.png">

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by anshu1992** [comment]
I can work on this.

**Comment by jamgar** [comment]
I see this has been idle for some time. Will it be okay to grab this issue?

**Comment by jamgar** [comment]
For history posted this in Slack.
Working on https://github.com/rubyforgood/casa/issues/4488 and what I am understanding is that this feature will need to give Supervisors/Admins the ability to allow or disallow a volunteer to see the “Want Driving Reimbursement”, and that this setting will need to be toggled per case, per volunteer. I am thinking that this toggle can be set under the Manage Volunteers for the case. There is not much real estate so providing an image of what I think may be an option. What do you think?
![image](https://github.com/rubyforgood/casa/assets/14931684/55733708-0c06-4f10-b756-1c54e840a7f9)

Brandon (He/Him)
Hi James I think this is a good spot. Mallory any thoughts?

Mallory
James the location of the reimbursement button makes sense. However, I would suggest we add a new column to this table with a boolean field titled, "Enable Reimbursement" and render a toggle switch input in each row.

[Outcome]
![image](https://github.com/rubyforgood/casa/assets/14931684/8092fb6c-dc5d-4f32-ae43-a6ef1ba8aa75)

**Comment by jamgar** [comment]
Bot PR has been submitted 🤗

**Comment by compwron** [comment]
This is done in https://github.com/rubyforgood/casa/pull/4961
