### ISSUE TITLE
Bug: Reimbursement Datatable Sorted Order Flaky Test

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4495]
### Environment
GH Action

### Current Behavior
Sometimes the test at `spec/datatables/reimbursement_datatable_spec.rb:33` fails  
Example Output:
```
   1) ReimbursementDatatable multiple record handling order by miles driven behaves like a sorted results set explicit ascending order should order correctly
     Failure/Error: expect(first_result[:id]).to eq(sorted_case_contacts.first.id.to_s)

       expected: "80"
            got: "86"

       (compared using ==)
     Shared Example Group: "a sorted results set" called from ./spec/datatables/reimbursement_datatable_spec.rb:158
     # ./spec/datatables/reimbursement_datatable_spec.rb:33:in `block (4 levels) in <top (required)>'
```

### Expected Behavior
It should pass when the datatable is working

### How to Replicate
Run the test multiple times locally?

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by dominiclizarraga** [comment]
Hey Shen

**Comment by brodyf42** [comment]
I'll work on this one.
