### ISSUE TITLE
Bug: creating court orders from Court Date page does not error but does not save

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4533]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
prod, qa

### Current Behavior
adding a court order should persist on save
on a page like https://casa-qa.herokuapp.com/casa_cases/cina-11-1002/court_dates/733

<img width="1647" alt="Screenshot 2023-02-10 at 11 07 58 AM" src="https://user-images.githubusercontent.com/578159/218176898-3109a467-5ed9-4db3-97ec-174d36f5a43c.png">
<img width="1643" alt="Screenshot 2023-02-10 at 11 08 11 AM" src="https://user-images.githubusercontent.com/578159/218176942-692c41fa-9e52-4f41-900b-1d96c2780b00.png">

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by anshu1992** [comment]
I can work on this.

**Comment by cliiint** [comment]
Hey all I'll snag this one

**Comment by cliiint** [comment]
Ready for review
