### ISSUE TITLE
Email selected users an end of month email with attached Learning Hours report for their organization

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4534]
**What type(s) of user does this feature affect?**
selected users - probably admins of a particular casa org

**Description**
Similar to https://github.com/rubyforgood/casa/issues/4476 email some selected users (add a way to select which users) (never cross-CasaOrg)

Email selected users a end of month email with attached Learning Hours report for their organization

Email contents:
> Learning hours have been added this week for <your casa organization> see attached full report or export the full report at https://casa-qa.herokuapp.com/reports 

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by rae-stanton** [comment]
I'd like to grab this one, but just to clarify the needs here:
- We need to add a way to select users that are a part of a specific CASA organization. 
- The end of month email needs to have a learning hours report for that month with an attachment/link 
- Does the end of month email should go to admins only or anyone within the org?

**Comment by rae-stanton** [comment]
@compwron maybe you can answer these when you get a minute. 😊

**Comment by compwron** [comment]
Yes never get users for a different org

**Comment by compwron** [comment]
Email goes only to and of the one org that the email is for, never cross the orgs

**Comment by rae-stanton** [comment]
@compwron real quick, just in reference to #4474 - is this the same place we want to set the learning hours email recipients?

**Comment by compwron** [comment]
Yes, same place

**Comment by rae-stanton** [comment]
Still working on this!

**Comment by rae-stanton** [comment]
Hi! I'd still like to continue working on this - I apologize for the HUGE delay from my end.

**Comment by compwron** [comment]
@rae-stanton go for it!!

**Comment by rae-stanton** [comment]
Thank you!!! 😊

**Comment by rae-stanton** [comment]
Quick update: I've got the BG jobs & tests left to complete, but this is almost complete!

**Comment by compwron** [comment]
great!! :)

**Comment by compwron** [comment]
@rae-stanton is there a PR I should be looking at?

**Comment by rae-stanton** [comment]
There isn't a PR yet - I've been stuck on this for a bit now, sorry for the delays! I can't seem to figure out why the attachment is still giving me problems.

**Comment by rae-stanton** [comment]
Waiting on some clarification before I continue working on this.
