### ISSUE TITLE
Bug: Fix Edit Organization Link for Admins in new theme branch

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4549]
### Impacted User Types
 - admins

### Description
Fix the edit organization link in the user settings dropdown for admins. It currently just links to "#0"
![image](https://user-images.githubusercontent.com/8918762/218914803-b836383e-0f1d-4dca-a1db-09a5241a8aea.png)

Make a pull request on the new theme branch

### How to Replicate
ex: 
1. - Log into staging as an admin.
2. - Click on your profile picture.
3. - Click on Edit Organization in the dropdown
4. - The link doesn't go anywhere

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Email:
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
CC: @seanmarcia

**Comment by anshu1992** [comment]
@FireLemons @seanmarcia I can take it.
