### ISSUE TITLE
Bug: Edit and Delete buttons don't work on patch notes in new theme

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4562]
### Impacted User Types
 - all casa admins?

### Environment
New Theme

### Current Behavior
Clicking the edit and delete buttons does nothing
![image](https://user-images.githubusercontent.com/8918762/219474791-ae15b488-b425-4690-95e7-e6347e7e0c42.png)

### Expected Behavior
when edit is clicked, the patch note box
 - should be editable
 - should have a cancel button that exits out of edit mode
 - should have a save button that saves the patch note
![image](https://user-images.githubusercontent.com/8918762/219476279-bb9853b0-92e1-408c-86b8-dee7a7ea7307.png)

when delete is clicked,
 - it shows the number of times it needs to be clicked again to delete the patch note
 - it shows a message to click the button again to delete the patch note
![image](https://user-images.githubusercontent.com/8918762/219477527-ea2d7009-9ad9-46cb-94c8-116ebb966d6d.png)

### How to Replicate
ex: 
1. - Log in (go to `all_casa_admins/sign_in`) as an all casa admin
2. click on patch notes
3. make a patch note
4. patch note buttons don't work

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hey there, can I be assign for this one?

**Comment by FireLemons** [comment]
CC: @seanmarcia

**Comment by dominiclizarraga** [comment]
@FireLemons Shen, I'm addressing this issue in the next PR [4614](https://github.com/rubyforgood/casa/pull/4614)

Also if you have a chance to look at other PR I pushed [4591](https://github.com/rubyforgood/casa/pull/4591)
