### ISSUE TITLE
New Theme Landing Page Needs a javascript Required Warning

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4567]
**What type(s) of user does this feature affect?**
 - volunteers?
 - supervisors?
 - admins?

**Description**
Add a javascript required message to the login page on the new theme branch

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/219786157-ef0516c9-7d01-4e9c-81e1-e76eec506e4a.png)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/)

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
CC: @seanmarcia 
Not required for merge

**Comment by leslie-seeberger** [comment]
I'd like to take this one.

**Comment by elasticspoon** [comment]
Closed by https://github.com/rubyforgood/casa/pull/4604 but I have no clue what the status of the New Theme branch is.
