### ISSUE TITLE
Bug: Javascript warning for login pages not visible on new theme

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4568]
### Impacted User Types
 - volunteers
 - supervisors
 - admins
 - all casa admins

### Environment
New Theme Branch

### Current Behavior
![image](https://user-images.githubusercontent.com/8918762/219802378-8279e185-723b-4eea-800c-ef03e320dfb4.png)

### Expected Behavior
The javascript warning is visible

### How to Replicate
ex: 
1. - Log in
2. Disable javascript

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
CC: @seanmarcia Not required for merge

**Comment by Luke-kb** [comment]
This looks to be working as it should on my local
<img width="1512" alt="Screen Shot 2023-02-28 at 10 11 12 pm" src="https://user-images.githubusercontent.com/7802494/221837264-48133992-3a85-480d-82cb-c38398f46d14.png">

**Comment by FireLemons** [comment]
on the new theme branch

**Comment by Luke-kb** [comment]
Oops, wrong url. Thanks. Should it look like this?
<img width="1512" alt="Screen Shot 2023-03-01 at 8 50 58 am" src="https://user-images.githubusercontent.com/7802494/221989206-3ab225d2-1d5e-4ba8-bfa0-f09fd82d17af.png">

**Comment by FireLemons** [comment]
Yeah looks good. Just make sure it's visible. On mobile and chromium too

**Comment by zacgra** [comment]
Can I be assigned this issue?
