### ISSUE TITLE
Bug: Notifications button in top right doesn't work in new theme

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4569]
### Impacted User Types
 - volunteers?
 - supervisors?
 - admins

### Environment
New Theme branch

### Current Behavior
The button links to notifications but clicking the button does nothing
![image](https://user-images.githubusercontent.com/8918762/219803972-e54f61c2-f69a-4f88-97cb-559d63713a45.png)

### Expected Behavior
brings the user to their notifications page

### How to Replicate
ex: 
1. - Log in
2. Try to click the button in the top right

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
CC: @seanmarcia Not required for merge

**Comment by seanmarcia** [comment]
Just pushed a fix for this.
