### ISSUE TITLE
[bug] volunteer assign after unassign

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#457]
After a volunteer is unassigned from a case, that volunteer cannot be re-assigned to that case. When that is attempted, the error message "Unable to assign volunteer to case: Casa case has already been taken." In other words, once a volunteer has been unassigned from a particular case, that volunteer can't be re-assigned to it. https://github.com/rubyforgood/casa/pull/455#issuecomment-664087761

**Comment by GuillermoCoding** [comment]
Hello, going to pick this up (:

**Comment by Zrrrpy** [comment]
go for it @GuillermoCoding! Thank you!
