### ISSUE TITLE
Bug: occourred at field not visible in reimbursement table in firefox

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4570]
### Impacted User Types
 - admins

### Environment
firefox browser

### Current Behavior
All dates are "undefined 0NaN NaN"
![image](https://user-images.githubusercontent.com/8918762/219804677-a3d1ddbc-5e5e-4ff1-97c5-7d2635de86df.png)

### Expected Behavior
A date is displayed in each row

### How to Replicate
ex: 
1. - Log in as an admin.
2. - Click on Group Actions in the left sidebar
3. Click on Reimbursement Queue
4. Look at miles driven column

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
CC: @seanmarcia required for merge

**Comment by seanmarcia** [comment]
Hey @FireLemons is this still an issue? I just logged in to https://casa-new-theme.herokuapp.com/reimbursements and it looks like it has been fixed:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/667909/219930331-42e86afe-25d4-436a-9f66-b177cf90199e.png">

**Comment by FireLemons** [comment]
@seanmarcia I've logged in on 2 different computers in firefox and I see the NaN

**Comment by FireLemons** [comment]
Looks like firefox only

**Comment by seanmarcia** [comment]
Interesting find! This raises a question I should have asked sooner -- do you ensure compatibility across all browsers? I know the essentials project communicated early on that they were only going to ensure compatibility only with chrome. I think this was partly because no one on the team had a windows computer to test IE.

**Comment by FireLemons** [comment]
IE was deprecated. I think we ought to support firefox so if someone wants more privacy and control from the big tech companies they don't have to inferior products.

**Comment by seanmarcia** [comment]
I'm not sure I understand your comment. My question was me looking for information on what browsers you all have committed to the CASAs that you'll support so we can test the new theme accordingly. 
ie - Chrome/Safari/Firebox/Brave/Opera/Edge/Vivaldi/etc.

**Comment by FireLemons** [comment]
Well at least chromium based browsers and firefox. I use firefox and I need to be able to QA the site. I might just pick this one up tonight.

**Comment by FireLemons** [comment]
This bug is not limited to the new theme.
