### ISSUE TITLE
Wrong title for new theme login page

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4572]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins
 - all casa admins?

**Description**
change the title to "Casa Volunteer Tracking" on the login page for the new theme

**Screenshots of current behavior, if any**  
![image](https://user-images.githubusercontent.com/8918762/219972052-02fbc853-e1d5-4e8b-8d0d-17660514493f.png)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

CC: @seanmarcia not required for merge

**Comment by Ritikkhulbe** [comment]
hey @FireLemons , i would like to complete this task

**Comment by dvsconcept1986** [comment]
If this is still not resolved. I would like to tackle this issue.

**Comment by FireLemons** [comment]
It's still assigned. You can take it if the bot unassigns.
