### ISSUE TITLE
Disable entering duplicate language options for casa orgs when there is whitespace

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4585]
### Impacted User Types
 - admins

### Environment
all

### Current Behavior
Multiple of the same language can be entered as language options for casa orgs when the name is the same but the whitespace is different
![image](https://user-images.githubusercontent.com/8918762/197273958-2df6cec2-ddeb-4844-91a2-e0829081898b.png)

### Expected Behavior
A validation error is shown when duplicate languages are entered

### How to Replicate
ex: 
1. - Log as an admin.
2. - Click on "Edit Organization" in the left sidebar menu.
3. - Scroll to the languages section
4. - Copy a language from the list
5. - Click new language
6. - Paste the copied language into the box
7. Add a space at the end of the text
8. submit

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Learningstuff98** [comment]
@FireLemons I can work on this.
