### ISSUE TITLE
New export report for volunteer email changes

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4594]
**What type(s) of user does this feature affect?**

 - supervisors
 - admins

**Description**
This ticket depends on [TODO make ticket] which allows volunteers to change (and confirm!) their own emails. Export a report of volunteers who have changed their emails
As always, only export volunteers for the supervisor's current CASA
columns: `old email(s), new email`

**Screenshots of current behavior, if any**  
https://casa-qa.herokuapp.com/reports
<img width="1080" alt="Screenshot 2023-02-24 at 11 33 02 AM" src="https://user-images.githubusercontent.com/578159/221274151-075f0369-b32d-4ee5-9638-f686198dca39.png">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hi, can I work on this?

**Comment by ShamiTomita** [comment]
Also, is this ticket related to #4534 and #4476?

**Comment by ShamiTomita** [comment]
One more question, for the confirmation aspect of the email change, do y’all just need an additional “email confirmation” input in the form or do y’all need a confirmation email to be sent?

**Comment by dpaola2** [comment]
I would suggest that having a confirmation field is probably sufficient. @compwron can chime in if she disagrees, though. I think asking the user to enter the email twice will sufficiently prevent typos.

**Comment by ShamiTomita** [comment]
Awesome, followup question, would you want these email updates/confirmations extracted out of the user_params and made into their own functions in the user controller? Like how passwords are treated?

**Comment by ShamiTomita** [comment]
Perfect, thank you!

**Comment by ShamiTomita** [comment]
Hi still working on the related issue! I’ll try to get a working PR for that by early next week!

**Comment by ShamiTomita** [comment]
almost ready to start!

**Comment by ShamiTomita** [comment]
In Progress, Finished with Part 1  #4734 for users to change their own emails.

**Comment by ShamiTomita** [comment]
Part 2 Coming Up
