### ISSUE TITLE
User Role Permissions for Casa Cases New

### ISSUE THREAD

**Issue by crespire** [rubyforgood/casa#4610]
**Description**
Flagged in #4595, currently it is unclear what a supervisor's permissions are regarding creating new `CasaCases`. The `index` view for CasaCases does only shows the "New" button to `CasaAdmins`, but the policy seems to `allow_all` (which includes volunteers) while the policy spec only tests against admins and volunteers and omits testing for supervisors.

In the view layer, currently only admins are given the option to create cases in an organization. This is counter to what is in the controller/authorization layer, which seems to suggest that all users should be able to create cases.

Input on the intended permissions here would help to clarify what policies should be put in place, which can be used to update the behaviour of the view layer.

**Existing file(s) needing changing**
* `app/policies/dashboard_policy.rb`
* `spec/policies/dashboard_policy_spec.rb`
* `views/casa_cases/index.html.erb`

**New file(s) needing creating**
None as of right now.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by samho223** [comment]
Hi, can I work on this?

**Comment by crespire** [comment]
> Hi, can I work on this?

This issue requires some input from the maintainers. I was hoping to be assigned the work as it was related to an issue I've already worked on.

**Comment by dpaola2** [comment]
@crespire Can you pose specific questions about what you need to move forward with this?

**Comment by crespire** [comment]
> @crespire Can you pose specific questions about what you need to move forward with this?

Are supervisors supposed to be able to create new cases once they are logged in via the UI?
