### ISSUE TITLE
Add mileage rates to the seeder

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4628]
**Description**
Add mileage rates to the seeder
in `db/seeds/db_populator.rb`

after running `rails db:reset` your local server should have mileage rates

Mileage rates are visible at `/mileage_rates` after logging in as an admin

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by dominiclizarraga** [comment]
@FireLemons please assign me here.
