### ISSUE TITLE
Remove phone number requirement for all casa admin password reset

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4652]
**What type(s) of user does this feature affect?**
 - all casa admins?

**Description**
The all casa admin password reset now has a phone number field as a part of a fix for the password reset but all casa admins can't be texted.  
  
Allow add casa admins to reset their password and remove the phone number field.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
See https://github.com/rubyforgood/casa/pull/4581

**Comment by napster235** [comment]
I can work on this one since it's related to my fix from #4581.
