### ISSUE TITLE
Admins can create new supervisors

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#466]
part of epic #4

**What type of user is this for? [admin/volunteer/supervisor/all]**
admin

**Where does/should this occur?**
On the admin dashboard just above the supervisor view.

**Description**
Above the supervisor view on the admin dashboard, there should be a button reading "New Supervisor" that opens a Create Supervisor page.

That page should contain the following fields:
- Email (text field)
- Display name (text field)
- Assign a volunteer (dropdown menu displaying all active, unassigned volunteers in alphabetical order)

**Screenshots**
It should look like this, except instead of saying "Editing Supervisor" it should say "Create a New Supervisor":
![Screen Shot 2020-07-29 at 6 52 53 PM (2)](https://user-images.githubusercontent.com/62810851/88871507-ebee0680-d1cc-11ea-9918-49bcece2cf86.png)

**Comment by compwron** [comment]
This is done! :) 
<img width="874" alt="Screen Shot 2020-08-02 at 3 42 53 PM" src="https://user-images.githubusercontent.com/578159/89134074-dcc1ce00-d4d6-11ea-9fae-3f0fc4af1e38.png">
<img width="1267" alt="Screen Shot 2020-08-02 at 3 42 43 PM" src="https://user-images.githubusercontent.com/578159/89134075-de8b9180-d4d6-11ea-8b52-f7bcafe7a032.png">
