### ISSUE TITLE
Ability to lock cases for case contacts

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4666]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
 - Remove autosaving of checked cases from the case contact form autosaver
 - For each casa case listed at the top of the new case contact form, put a lock button on the right
 - The lock button will
    - have an unlocked icon by default
    - toggle between a locked and unlocked icon when clicked
    - disable the checkbox left of it when in locked mode
    - make the checkbox checked in locked mode
 - The locked state will not change until the user toggles the lock
 - Write System Tests

Kind of like this but make the buttons line up
![image](https://user-images.githubusercontent.com/8918762/225486968-395567bd-3bcc-4bf2-8e5d-7237fafb667e.png)

**Screenshots of current behavior**  
![image](https://user-images.githubusercontent.com/8918762/225481507-82f65632-fba0-43f1-9c43-a86f35b8aa52.png)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by dominiclizarraga** [comment]
@FireLemons please let me help you

**Comment by gaurijo** [comment]
Hi, I'd like to work on this issue if no one else is :)

**Comment by FireLemons** [comment]
It's assigned to dominic

**Comment by dominiclizarraga** [comment]
Yes, I'm still on it

**Comment by dominiclizarraga** [comment]
@FireLemons Shen, please any feedback you can provide [PR](https://github.com/rubyforgood/casa/pull/4754).

**Comment by littleforest** [comment]
Here is the CodeClimate error. If possible to fix, that would be great, otherwise we don't have to worry about it:

<img width="834" alt="Screen Shot 2023-05-13 at 10 48 57 AM" src="https://github.com/rubyforgood/casa/assets/1938665/c0c7f6cf-fd3f-402a-8514-d9a38bb7cb91">

**Comment by FireLemons** [comment]
When the case is locked, I can still toggle the checkbox. That shouldn't be possible.

**Comment by FireLemons** [comment]
Could you move the lock to the left of the checkbox? So all the all the locks line up horizontally.

**Comment by schoork** [comment]
Moved this to nah. With the new redesign, this is not autosaved in the same way.
