### ISSUE TITLE
Bug: Emancipation Reminders Show the Incorrect Time

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4679]
### Impacted User Types
 - volunteers

### Current Behavior
Making a new emancipation reminder seems to set the time of all previous emancipation reminders to the time of the newest one.
![image](https://user-images.githubusercontent.com/8918762/226390323-e90a5525-00af-4983-bc5a-69825e418597.png) 

### Expected Behavior
The time of previous emancipation reminders is unaffected by new emancipation reminders.

### How to Replicate
ex: 
1. Log in as an admin
2. go to cases
3. find a transitioning case
4. click send a reminder
5. you are redirected to the volunteer
6. impersonate the volunteer
7. check your inbox as the volunteer

You may need to create a few reminders and change the dates on some of them in the database to make them older.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ciaranc78** [comment]
@FireLemons when a volunteer navigates to their inbox, `mark_as_read!` is being called on all EmancipationChecklistReminderNotifications which in turn updates the `updated_at` column which is the attribute used in the view.

https://github.com/rubyforgood/casa/blob/0afa84c637ef548f781dc5f5de2c83cb8c2105d1/app/views/notifications/index.html.erb#L27-L31

This could be as simple as using the `created_at` value instead? but I'm unsure if there is any reason for using the `updated_at` attribute in the view which I'm not aware of.

**Comment by FireLemons** [comment]
It should just be created at
