### ISSUE TITLE
Fill out Notification Tests

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4681]
**Description**
For each kind of notification:
 - Make sure the notification [factory](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#inheritance) can create it
 - Make sure there is a test for the notification displaying correctly

Types of notifications can be found in `app/notifications`

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jenniferhalloran** [comment]
Hey - interested in fixing this issue!

**Comment by deannahburke** [comment]
Also interested in collaborating with Jenn on this issue!

**Comment by jenniferhalloran** [comment]
Still working on this! Just taking a bit since it is my first contribution. :)

**Comment by jenniferhalloran** [comment]
Had surgery on my hand - so a bit delayed but am working on this! :)

**Comment by bcastillo32** [comment]
@jenniferhalloran (I hope your hand is healing ok!) and/ or @deannahburke  Are you still working on this issue? If you are exp any blockers, plz message our team slack :)

**Comment by bcastillo32** [comment]
@FireLemons Can you please explain what this ticket is for please :) I am trying to go through and understand all the tickets. Thanks in advance

**Comment by sandfortw** [comment]
I am going to take the first half of this issue for now (just creating factories for notifications).

**Comment by sandfortw** [comment]
Still working on this, will update again when I've made a PR.

**Comment by FireLemons** [comment]
You can make a draft pr so we know not to merge it but it will run the checks(like the linters) so you can fix those ahead of time.

**Comment by sandfortw** [comment]
Just as a clarifying question, is creating the missing factories and creating corresponding component tests sufficient to close this issue, or do we also need more tests in spec/system/notifications/index_spec.rb to call this done?

**Comment by sandfortw** [comment]
I believe the above pull request should close this issue--let me know if I've missed anything or misunderstood the assignment.
