### ISSUE TITLE
Stakeholder Bug: previous saved data still present

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4698]
Volunteer reports:

1.  When I click on New Case Contact, the last entry comes up and I have to delete the previous entry to enter a new contact.

**Comment by elhalvers** [comment]
I was not able to duplicate the issue.

1. I logged in as voluteer1@example.com (Shirley Wehner Sr.).
2. I clicked on the 'Case Contacts' link in the left panel which opened the list of 'case/contacts'.

<img width="1031" alt="Screenshot 2023-04-07 at 9 34 26 AM" src="https://user-images.githubusercontent.com/74928397/230646512-dea38ad2-095f-47e0-aa85-f13fe62eab6f.png">

3. I clicked on the '+ New Case Contact' button which opened the 'case_contacts/new' form.

<img width="1106" alt="Screenshot 2023-04-07 at 9 34 43 AM" src="https://user-images.githubusercontent.com/74928397/230646554-a117d1c0-cb2e-4490-94d1-7e4b9db14ec5.png">

**Comment by jamgar** [comment]
Will take a look at this to see if I can repro. Is there any further details that can be given? For example does this happen every time they create a New Case Contact, or intermittent?

**Comment by compwron** [comment]
[casa](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1685981074475339)



Brandon (He/Him)
  [1 hour ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1685981074475339)
Hi 
[@Linda (she/her) - CASA and Flaredown](https://rubyforgood.slack.com/team/UTSG40QCW)
 were you able to reproduce this bug? perhaps get a recording?
https://github.com/rubyforgood/casa/issues/4698
3 replies


Linda (she/her) - CASA and Flaredown
  [1 minute ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1685984899322449?thread_ts=1685981074.475339&cid=CVB0QJGVD)
i am trying to reproduce it following the instructions in the issue now


Linda (she/her) - CASA and Flaredown
  [< 1 minute ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1685984973471899?thread_ts=1685981074.475339&cid=CVB0QJGVD)
I do not see this bug reproducing


Linda (she/her) - CASA and Flaredown
  [< 1 minute ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1685984983721659?thread_ts=1685981074.475339&cid=CVB0QJGVD)
although in trying, it looks like we lost some error handling for missing fields on create case contact
