### ISSUE TITLE
Placements create tables

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4701]
https://github.com/rubyforgood/casa/issues/4695
Add table placement_type: name, casa_org_id. Add table placement: placement_id, casa_case_id, started_at, created_by_id (links to user table)

**Comment by compwron** [comment]
@ciaranc78 sorry I missed your comment, I had an open PR. Do you want to work on the next section- create/update/delete for these new models?

**Comment by ciaranc78** [comment]
> @ciaranc78 sorry I missed your comment, I had an open PR. Do you want to work on the next section- create/update/delete for these new models?

@compwron Absolutely, thanks!
