### ISSUE TITLE
On casa case show page, show placements (below court orders)

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4717]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
On casa case show page, show placements (below court orders)
Do not add the Create or Update yet. 
Write tests

This is part of epic #4695

<img width="1662" alt="Screenshot 2023-03-29 at 8 16 24 PM" src="https://user-images.githubusercontent.com/578159/228719608-8b8bb5b4-d7da-445b-b488-06691c84dba7.png">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
@ciaranc78 do yu want to work on this one?

**Comment by ciaranc78** [comment]
@compwron Sure yeah!

**Comment by ciaranc78** [comment]
@compwron there is currently no casa_case_id on the placements table...I'll go ahead and add it as part of this PR?

**Comment by ciaranc78** [comment]
just getting back to this
