### ISSUE TITLE
Export Data report for Placements

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4718]
This is part of epic #4695 

**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
In the Export Data tab, https://casa-qa.herokuapp.com/reports add a button for Placements to export all placements for all casa cases **for that casa org**. Columns: casa_case.number, placement type, placement start, created_at, creator name

**Screenshots of current behavior, if any**  
<img width="1659" alt="Screenshot 2023-03-29 at 8 35 44 PM" src="https://user-images.githubusercontent.com/578159/228722128-ffef4d03-8dcb-498e-971a-e165e8694765.png">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by leevic31** [comment]
@compwron Hello! Can I work on this?

**Comment by rae-stanton** [comment]
I'll take this one on. 😊

**Comment by rae-stanton** [comment]
Just an update, I'm pausing my side of development here until PR #4752 has been completed and merged into main - it seems some of the work will be doubled up and some of the migrations will allow me to finish this ticket up properly. 😊
