### ISSUE TITLE
Change the password set/reset email to describe when the links expire.

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4726]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins
 - all casa admins

**Description**
Change the text of the password set/reset emails to describe when the links expire. I think they expire within a certain time and after a single click. The time may be different depending on the kind of user. For higher privileged accounts the expiration time might be shorter.

 - Find out what conditions cause the links to expire.
 - Edit the email texts found in `app/views/devise/mailer`

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
The app sends emails

**Comment by puneethkumarvh** [comment]
okay will check

**Comment by cliiint** [comment]
I'm grabbing this one!

**Comment by cliiint** [comment]
Ready for review!
