### ISSUE TITLE
Display App Metrics

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4753]
**What type(s) of user does this feature affect?**
Any Visitor

**Description**
Use [chart.js](https://www.chartjs.org/docs/latest/getting-started/installation.html) to create a [bubble chart](https://www.chartjs.org/docs/latest/charts/bubble.html) of when case case contacts  are created. 

Display the metrics at the `/health` page

1. Add chart.js to application.js
2. For the data points get a list of the `created_at` times for case contacts created in the last week. The data points are truncated by day for the y axis and truncated by hour for the x axis. If 2 data points overlap they are combined and the radius of the circle is increased. Time is fetched from the backend as unix time and converted to local time on the frontend. Do not make any other details of the case contacts accessible on the page.  
3. Create a chart like the one below. The y axis of the graph is the day of the week and the x axis is the hour of the day. 
![image](https://user-images.githubusercontent.com/8918762/231637142-5c3b5bae-b801-424d-84a9-2da3d248ee79.png)

See [this guide](https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets) for working with javascript in the CASA project.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by aboongm** [comment]
I want to work on this.

**Comment by FireLemons** [comment]
sorry my bad still gotta review the pr

**Comment by aboongm** [comment]
I m still working on this. Give me more time.
