### ISSUE TITLE
Allow turning off of reimbursement feature for an organization

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#4757]
**What type(s) of user does this feature affect?**
 - admins?

**Description**
We would overall like a complete opt-out ability at the organization level for the reimbursement function.

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by dpaola2** [comment]
While this does "work", the UI needs work on the New Case Contact screen.

**Comment by cliiint** [comment]
Heya, I'll grab this one
