### ISSUE TITLE
Modify visualization on view all supervisors page

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#4758]
**What type(s) of user does this feature affect?**
 - supervisors?
 - admins?

**Description**
On the `/supervisors` page the red + green + gray bubbles do  not add up to the total number of volunteers. While the legend at the top indicates that the red + green should add up to the total number of volunteers, and the gray bubble is just a count of transition-aged youth, this is still visually confusing for the stakeholders. Modify this in some way so that it doesn't seem like the bubbles should add up to the total number of volunteers

**Screenshots of current behavior, if any**  
<img width="1539" alt="Screen Shot 2023-04-14 at 11 29 35 AM" src="https://user-images.githubusercontent.com/1938665/232127530-64d02fde-f2bc-41f5-a29b-ddbe9887472b.png">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by rae-stanton** [comment]
@littleforest I'd like to work on this, but I'd like to quickly clarify what the need here is - are you saying that we need some kind of reference that says "total volunteer count"? IE where the "legend" is it says total volunteers are equivalent to the red and green indicators total or something like that. Thanks in advance. 😊

**Comment by JelenaSkracic** [comment]
@littleforest help me understand this better. 
Green and red should be showing the total number of volunteers,  while gray is a separate indicator for transition-aged youth? Is there any reason why are those even put together? 
Thanks :D

**Comment by littleforest** [comment]
@JelenaSkracic 

> Green and red should be showing the total number of volunteers, while gray is a separate indicator for transition-aged youth?

Yes

> Is there any reason why are those even put together?

No! I think we were just trying to convey some info at-a-glance re volunteers and youth, but it ended up being very confusing.

**Comment by littleforest** [comment]
@rae-stanton would you be able to implement new designs that @JelenaSkracic comes up with?

**Comment by rae-stanton** [comment]
@littleforest Sure thing! 

@JelenaSkracic just let me know what you come up with! Feel free to shoot me a message on Slack. My name is the same on there. 😊

**Comment by dpaola2** [comment]
Stack these two things:
- Have they done their job?
- % of transition aged youth
-

**Comment by JelenaSkracic** [comment]
@rae-stanton I thought of something like this 
![LegendForSupervisorList](https://user-images.githubusercontent.com/54455242/235258956-8d021c33-260c-4fbb-9f67-48fccac24e40.png)

**Comment by rae-stanton** [comment]
@JelenaSkracic I was thinking that too! I think that's the best option overall Thank you!
