### ISSUE TITLE
Allow supervisors to view reimbursements

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4759]
**What type(s) of user does this feature affect?**
 - supervisors

**Description**
Allow supervisors to only view the reimbursements page

The reimbursements page can be found by logging in as an admin and following the reimbursements link in the sidebar on the left.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by gaurijo** [comment]
@FireLemons I'd like to take on this issue

**Comment by gaurijo** [comment]
Still working on this but almost finished

**Comment by gaurijo** [comment]
Hi @FireLemons - could I have permission to create a new branch off this repo so I could send off a PR? Thank you

**Comment by gaurijo** [comment]
Just waiting for permission to create a new branch to send up a PR :)
