### ISSUE TITLE
List timestamps on user edit page

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#4771]
**What type(s) of user does this feature affect?**
 - volunteers?
 - supervisors?
 - admins?

**Description**
When editing a user, there is a list of dates for "Added to System", "Last logged in", etc. However these should be actual timestamps (with a timezone) rather than just a date.

This should be fixed for the `/volunteers/:id/edit`, `/supervisors/:id/edit`, and `casa_admins/:id/edit` pages.

**Screenshots of current behavior, if any**  
<img width="806" alt="Screen Shot 2023-04-21 at 11 10 51 AM" src="https://user-images.githubusercontent.com/1938665/233706366-46bd36bb-8c75-4b09-a147-b5b4781260cf.png">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by elhalvers** [comment]
I can jump on this one! : )

**Comment by elhalvers** [comment]
I made the following change in my dev environment for the 'Edit Profile' page and manually tested logged in as a Volunteer, Supervisor, and Casa Admin (Adding the time and time zone to the date/time stamp)

Does this meet requirements?

<img width="332" alt="Screenshot 2023-04-21 at 2 37 48 PM" src="https://user-images.githubusercontent.com/74928397/233738688-de4a1cd5-01e8-4f23-ad2a-d63a953ac1fd.png">



<img width="734" alt="Screenshot 2023-04-21 at 2 34 27 PM" src="https://user-images.githubusercontent.com/74928397/233738410-e8dfe8c7-3638-4950-83af-1110e04c9184.png">

Thanks! : )

**Comment by elhalvers** [comment]
I will review the automated tests to see if they exist for this section and modify as needed : )

**Comment by elhalvers** [comment]
I hard coded `config.time_zone = "Eastern Time (US & Canada)"` in the `config/application.rb` file. I do not know if we capture the 'current_user' time zone to make it dynamic. I can also leave off the time zone in the format string if preferred.

**Comment by elhalvers** [comment]
Also, so far, I have only modified the date formatting for editing a user profile. Should we leave it at that for now? or modify it everywhere there are dates, for example, casa contacts, court dates, etc...

: )

**Comment by littleforest** [comment]
> I hard coded config.time_zone = "Eastern Time (US & Canada)" in the config/application.rb file

That sounds good! Please always include a timezone when displaying a timestamp.

**Comment by littleforest** [comment]
> Should we leave it at that for now? or modify it everywhere there are dates, for example, casa contacts, court dates, etc...

I think just changing the users if fine for this PR.

**Comment by elhalvers** [comment]
Great! I have stubbed out the corresponding tests. I will finish those and then submit a PR.

Thank you @littleforest  😃

**Comment by elhalvers** [comment]
Still working on this. I finished successful tests for the changes I made that impact the 'User Profile' timestamps, however, the change has affected some other RSpec tests that are expecting a different date format. Cleaning up the other tests now. I pushed a new branch that I am working on for this issue. 😄

**Comment by littleforest** [comment]
> Hardcoding time zone in config/application.rb breaks other tests. Working on adding a solution to display local time zones based on browser.

If setting the timezone based on the browser ends up being tricky, I'm happy to pair and work on the tests for hardcoding the timezone. Down the line we can add a timezone field for a user or organization and can display the timezones in whatever timezone they set.

**Comment by elhalvers** [comment]
> > Hardcoding time zone in config/application.rb breaks other tests. Working on adding a solution to display local time zones based on browser.
> 
> If setting the timezone based on the browser ends up being tricky, I'm happy to pair and work on the tests for hardcoding the timezone. Down the line we can add a timezone field for a user or organization and can display the timezones in whatever timezone they set.

Hey @littleforest I am still exploring 'setting the timezone based on the browser' but I would be happy to pair to discuss the solution when you are available. Thanks! : )
