### ISSUE TITLE
Improve the validation of the phone number field

### ISSUE THREAD

**Issue by dpaola2** [rubyforgood/casa#4773]
**What type(s) of user does this feature affect?**

Everyone:

 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

**Description**

We should accept 222333444 instead of insisting on +1222333444.

**Screenshots of current behavior, if any**  

![image](https://user-images.githubusercontent.com/150509/233709512-01671228-54bf-47f3-91a1-661fd8b10de6.png)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by MarchandMD** [comment]
Hey! Happy to take on this one!

**Comment by dpaola2** [comment]
Go for it!

**Comment by MarchandMD** [comment]
bot, give us more time

thanks!

**Comment by littleforest** [comment]
At Stakeholder meeting we are talking about just having the input field be a string field, and the backend strips all non-number characters and adds "+1" if it is missing. The validations could be that it has to have 10 digits or it has 11 digits and begins with 1.

**Comment by littleforest** [comment]
I don't know if we actually want to edit the user input, or just check that we have the correct info so that we can strip out non-numbers as part of a method call and send an SMS down the line.

**Comment by Tscasady** [comment]
Sorry, I've been traveling, should have a PR up this afternoon. It sounds like our solution is what you are suggesting. We were thinking of leaving the current validation as is, but adding a condition for 10 digit numbers. A before_save callback would add the '+1' to numbers that pass the 10 digit validation. It is my understanding that SMS needs the country code?

**Comment by littleforest** [comment]
Yes, SMS needs the country code. The CASAs are only US-based, so we do not need to worry about other country codes.
