### ISSUE TITLE
show_casa_case view for Admins

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#48]
Admins should be able to click on a `casa_case` from anywhere on the platform and see a `show` view displaying the following `casa_case` details:

- casa_case's `case_number`
- Volunteer email/indentifying info via `case_assignment` (potentially a list)
  - whether or not this `case_assignment` `is_active`
   - `case_contacts` infinite view by volunteer with rows displaying:
      - `case_contact` type
      - `case_contact` duration

'teen program eligible' checkbox can remain

**Comment by lisale0** [comment]
show we include the attribute `teen eligible` on the show view?

**Comment by lisale0** [comment]
show all case assigned volunteers 

Case assignment - all data

Volunteer name/information/email
List active versus not active
List volunteer and then all their CaseContact

see/access volunteer information through CaseAssignment
