### ISSUE TITLE
Create Casa Org Features Section on Casa Org Edit Page

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4810]
**What type(s) of user does this feature affect?**
 - admins

**Description**
 - Add a header over the reimbursement enabling feature, reading "Organization Features"
 - Move the header and the checkbox down to just above the submit button
 - Put an `<hr>` over the header

Kind of like this
![image](https://github.com/rubyforgood/casa/assets/8918762/f94bf85c-ee99-4832-9602-6f400704a5f5)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kasugaijin** [comment]
i'll take this one!
