### ISSUE TITLE
Add SMS to Organization Features Section

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4815]
**What type(s) of user does this feature affect?**
 - admins

**Description**
On the edit casa org page,
 - Create a new checkbox for SMS under the organization features section
 - Move the twilio fields under the new checkbox.
 - Only show the twilio text fields if the SMS checkbox is checked
 - Is the SMS checkbox is unchecked, disable all SMS features
 - Preserve the twilio field values when the SMS checkbox is unchecked

**Screenshots of current behavior, if any**  
![image](https://github.com/rubyforgood/casa/assets/8918762/0aea4133-7477-4b69-8c41-47f534f68a39)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Can I work on this?

**Comment by ShamiTomita** [comment]
Still working! Almost there!

**Comment by compwron** [comment]
:)

**Comment by ShamiTomita** [comment]
Hi! Last Two PR's (#4885  & #4886 ) are ready for final review and pass all the checks!

**Comment by mattzollinhofer** [comment]
Just cruising around reading issues on the in progress column of the board and noticed this one seems like maybe it’s done? All the related MRs appear to merged or closed if I’m following the trail correctly. 

Should this be moved along?

**Comment by schoork** [comment]
No one is currently using SMS.

**Comment by elasticspoon** [comment]
Looks like this got done somewhere here: https://github.com/rubyforgood/casa/pull/4885, https://github.com/rubyforgood/casa/pull/4883, https://github.com/rubyforgood/casa/pull/4836
