### ISSUE TITLE
Add this yaml linter to the project workflows

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4817]
**Description**
add this linter to our github workflows https://github.com/marketplace/actions/yaml-lint
lint when commits are pushed to the main branch and for pull requests

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by EfeAgare** [comment]
confirm
