### ISSUE TITLE
Bug: Emancipation Checklist Option Expansion Expands/Collapses all the Options

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4831]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Current Behavior
In the emancipation checklist form, when any section is expanded, all the sections are expanded and vice versa for collapsing. 

### Expected Behavior
Only one emancipation option section should be expanded collapsed at a time.
An emancipation option section is expanded when
 - an unchecked category box above the checklist options section is checked
 - the "+" icon above the section is clicked

An emancipation option section is collapsed when
-  - the "-" icon above the section is clicked

### How to Replicate
ex: 
1. - Log in
2. - Navigate to a transitioning case. They are marked by the butterflies in the table.
3. - Click on "emancipation x/18" at the top
4. - Click around the form.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by danaguilar** [comment]
I would like to pick this issue if it's still available.
