### ISSUE TITLE
saving a case contact that doesn't meet minimum duration requirements should prompt dialogue box

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#485]
Part of epic #3

**What type of user is this for? [admin/supervisor/all]**
primarily volunteers, but also accessible by admins and supervisors

**Where does/should this occur?**
On the <a href="https://casa-r4g-staging.herokuapp.com/case_contacts/new">New Case Contact page</a>, accessible by all users.

**Description**
If any user tries to save a new case contact or update an existing and the `case_contact_duration` is less than the minimum of 15 minutes, this should prompt a dialogue box that says:

Please enter a minimum duration of 15 minutes (even if you spent less time than this). 

There should be **only one button** in the dialogue box that says "okay". After a user clicks the button, the dialogue box should disappear and the user should be brought back to the same page with no changes to values. 

**Relates to issue**
#484

**Comment by compwron** [comment]
<img width="976" alt="Screen Shot 2020-08-14 at 7 39 31 PM" src="https://user-images.githubusercontent.com/578159/90303798-fa435000-de65-11ea-8489-20b1ef7a0808.png">

**Comment by compwron** [comment]
@nickschimek is working on this
