### ISSUE TITLE
Bug: add to calendar button on casa cases looks bad

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4853]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Current Behavior
The text is going through the border
![image](https://github.com/rubyforgood/casa/assets/8918762/e9054a6a-06a4-4ed7-9e55-8b2125b9e2f6)

### Expected Behavior
Text stays inside the border.
Look matches the rest of the website. We use the [plainadmin theme](https://plainadmin.com/) which is built on top of bootstrap

### How to Replicate
ex: 
1. - Log in.
2. - Navigate to a casa case with a court date

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by bacchist** [comment]
I could not reproduce this using Chrome or Firefox. Checked both the live demo QA site and locally, and everything appears to be working as expected including drop down menu.

![Screenshot 2023-05-31 182648](https://github.com/rubyforgood/casa/assets/1015716/ee57fcee-a3e4-44cb-9edf-e0e2318fd412)
![Screenshot 2023-05-31 183139](https://github.com/rubyforgood/casa/assets/1015716/07ef5011-e5f4-4abf-9a82-f7183bf71de6)

**Comment by d-otis** [comment]
> I could not reproduce this using Chrome or Firefox. Checked both the live demo QA site and locally, and everything appears to be working as expected including drop down menu.
> 
> ![Screenshot 2023-05-31 182648](https://user-images.githubusercontent.com/1015716/242429043-ee57fcee-a3e4-44cb-9edf-e0e2318fd412.png) ![Screenshot 2023-05-31 183139](https://user-images.githubusercontent.com/1015716/242429479-07ef5011-e5f4-4abf-9a82-f7183bf71de6.png)

I also was unable to reproduce locally or on QA site. 
I tried resizing the browser smaller to see if I could trigger the text overflow, but no dice.

**Comment by fchatterji** [comment]
Hey, I managed to reproduce the issue, on firefox on ubuntu. Can i work on this issue?

**Comment by fchatterji** [comment]
Added a PR for this
