### ISSUE TITLE
Bug: creating new contact type does not show up in case contact types

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4856]
### Impacted User Types
all

### Environment
all

### Current Behavior
add contact type in https://casa-qa.herokuapp.com/casa_org/1/edit
should be viewable in: https://casa-qa.herokuapp.com/casa_cases/new and also in existing cases (if existing case doesn't have custom contact types already) 

<img width="1436" alt="Screenshot 2023-06-02 at 11 22 12 AM" src="https://github.com/rubyforgood/casa/assets/578159/e1483c6c-eaab-4c5e-aaa1-aa02c3abd51f">
<img width="1625" alt="Screenshot 2023-06-02 at 11 22 48 AM" src="https://github.com/rubyforgood/casa/assets/578159/9cfd0273-985d-4f3e-883d-f36ae872bdd8">

A PR was started on this in #4868, feel free to pick up from there or start fresh!

## QA Login Details
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by gaurijo** [comment]
Hi @compwron I'd like to take on this issue please :)

**Comment by compwron** [comment]
Go for it! :)

**Comment by gaurijo** [comment]
Still working on this - just need to write a test :)

**Comment by gaurijo** [comment]
Still working on this! Had some life obligations come up

**Comment by compwron** [comment]
This came up with stakeholders today, they are excited for it!

**Comment by gaurijo** [comment]
Awesome! Hoping to submit an updated PR that includes testing, either this weekend or early next week. Thanks for your patience :)

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/pull/4868

**Comment by compwron** [comment]
I hope we fixed this...

**Comment by elasticspoon** [comment]
I am pretty sure we have done this. I will close 🙏
