### ISSUE TITLE
[bug] in upload supervisors, throws exception when importing the example file

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#486]

**Comment by alindeman** [comment]
@compwron Is it possible that you had 'Import Volunteers' still selected when you attempted to import a supervisors file? That's the only way I could reproduce this.

If so, I still think this is probably worth fixing, as I don't think even invalid user input should cause the app to crash.

**Comment by compwron** [comment]
Hmm it's possible. Agreed, worth fixing!
