### ISSUE TITLE
Display Error Message When metrics chart fails to load

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4867]
**Description**
When the chart at `/health` fails to load. Show an error explaining why.
The chart at `/health` currently fails to load if viewed when not logged in and loads successfully when logged in.

See it in our QA environment: https://casa-qa.herokuapp.com/health
See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets
See: https://www.chartjs.org/

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Nwabor** [comment]
I can work on this

**Comment by Nwabor** [comment]
Please, give me more time I am still working on it
