### ISSUE TITLE
Scrollable section for "Select all relevant CASA cases" in New Case Contact page

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4869]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
When creating a new case contact, the first section "Select all relevant CASA cases" card can be very large when a supervisor or admin views it (when they are not impersonating a volunteer). To make for a smoother feeling workflow, we would like to house the selectable cases in a Scroll box (see pics below). How long the scroll box should be is undecided but please message @bcastillo32 and send pics of what you're thinking 😀. Maybe if there are more than X amount, make it scrollable because some volunteers only see a few at a time. 

### Where to navigate

1. Log in
2. Click on "cases" in the left navbar
3. Click on a case number
4. Click "+ New Case Contact" button at the top 
5. You will see section 1 titled "Select all relevant CASA cases" - this is the targeted section

**Screenshots of current behavior, if any**  
https://www.loom.com/share/6214c4a013c54832b79233d3559ee824
<img width="618" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/1c987844-5762-4ebb-8baf-166ada5770ec">

## Acceptance Criteria
- scroll box width is only slightly wider than the length of the case with the longest character count and does not take up the whole card
- if my mouse is not in the scroll box and I scroll, I scroll the entire window and not the scroll box
- selectable cases are housed in the scroll box
-  when my mouse is in scroll box, if I have scrolled to the top of the scroll box and continue to scroll my entire window scrolls up
- when my mouse is in scroll box and I am neither at the top or bottom of the scroll box, only the scroll box scrolls
- when my mouse is in scroll box, if I have scrolled to the bottom of the scroll box and continue to scroll my entire window scrolls down
- when I scroll a scroll bar appears that I am able to grab and scroll with
- when I don't scroll the scroll bar disappears 

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
Seems reasonable. Only supervisors and admins ever have many cases- in real life, volunteers usually have one, occasionally two.

**Comment by elhalvers** [comment]
I can do this! : )

**Comment by bcastillo32** [comment]
Thank you for picking this up @elhalvers
