### ISSUE TITLE
Add Supervisor to Reimbursements CSV download

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4870]
**What type(s) of user does this feature affect?**

 - supervisors
 - admins

**Description**
Add Supervisor to Reimbursements CSV download
From stakeholder SB on June 9, 2023
Because: When sending reimbursements, after the check is cut, the reimburser tells the supervisor to tell the volunteer that the check is in the mail (manual process) and the admin wants to be able to see the supervisor without having to look them up in a separate system. 
At url like https://casa-qa.herokuapp.com/reimbursements

**Screenshots of current behavior, if any**  

<img width="1420" alt="Screenshot 2023-06-09 at 11 07 20 AM" src="https://github.com/rubyforgood/casa/assets/578159/57c55bc1-3ae9-493a-abe9-b475da2e3ca8">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
<img width="210" alt="Screenshot 2023-06-09 at 11 09 14 AM" src="https://github.com/rubyforgood/casa/assets/578159/e3511a5e-997d-44a9-bd6d-b1b6dc0cad9b">

(later issue) AND on checking checkbox, send a notification to supe and to volunteer saying "Volunteer Linda's request for reimbursement fo 3mi for $12 on June 9, 2023 has been processed and is en route"

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/issues/4871

**Comment by compwron** [comment]
TOD split out the UI to another ticket - this one can just be the download

**Comment by danaguilar** [comment]
I can pick up this issue
