### ISSUE TITLE
Send in-app notification to volunteer and supervisor on Reimbursement Complete checkbox selection

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4871]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Sign in as a `casa_admin` role. Go to https://casa-qa.herokuapp.com/reimbursements.

On checking checkbox, send an in-app notification (see Notification model) to supervisor and to volunteer saying "Volunteer Linda's request for reimbursement for 3mi for $12 on June 9, 2023 has been processed and is en route"

<img width="210" alt="Screenshot 2023-06-09 at 11 09 14 AM" src="https://github.com/rubyforgood/casa/assets/578159/e3511a5e-997d-44a9-bd6d-b1b6dc0cad9b">

## QA Login Details
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by schoork** [comment]
@compwron Questions:
1. Curious about the logic to determine the rate of pay... I see mileage rates, is the rate paid based on the active mileage rate on date of travel or the date approved?
2. Should we display the mileage rate in the reimbursements table or on the page?
3. Is there value in just now showing the rate that will be paid (a mileage rate could be out of date, etc.)

**Comment by schoork** [comment]
I'll push the code without $$ and if it's still desired, would recommend a new ticket with some business logic to figure out the current rate of pay.
