### ISSUE TITLE
[EPIC] Volunteer propose adding and removing contact type from case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4872]
Proposed features

- If volunteer requests have not been handled for long enough, notify admin... 
- Add button per contact type group on https://casa-qa.herokuapp.com/case_contacts/new?case_contact%5Bcasa_case_id%5D=160
- - Volunteer choose from hidden contact types from list
- volunteer-clickable "hide" button for contact types - which hides (greys out?) contact type and notifies supervisor to approve the request, which then does the same thing as supervisor "edit case" hiding some options

<img width="200" alt="Screenshot 2023-06-09 at 11 16 57 AM" src="https://github.com/rubyforgood/casa/assets/578159/162ee60c-5e9b-4c59-a503-0582aefe264f">
- SB doesn't care about how many miles driven- want volunteers to be able to hide that. per volunteer persistent hiding travel details even though the org as a whole allows submitting for reinbmursement. *only* be able to minimize travel section. Maybe show on the User page their always-minimize-travel option selection also. (Track on user model)
<img width="541" alt="Screenshot 2023-06-09 at 11 20 01 AM" src="https://github.com/rubyforgood/casa/assets/578159/0fd125ee-36a0-44e9-9fc5-0aa8ef5cbb7d">

**What type(s) of user does this feature affect?**
 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

**Description**

Make it easier for a volunteer to add a contact tuype
This is several tickets!

<img width="1165" alt="Screenshot 2023-06-09 at 11 13 07 AM" src="https://github.com/rubyforgood/casa/assets/578159/b7f70c8a-c857-494a-98c4-c90c8d9e70eb">
on**

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by bcastillo32** [comment]
I will begin splitting this up sometime this evening.

**Comment by bcastillo32** [comment]
Hi @compwron thank you for the help!

 for "Add button per contact type group on https://casa-qa.herokuapp.com/case_contacts/new?case_contact%5Bcasa_case_id%5D=160
Volunteer choose from hidden contact types from list
volunteer-clickable "hide" button for contact types - which hides (greys out?) contact type and notifies supervisor to approve the request, which then does the same thing as supervisor "edit case" hiding some options"
 
 a couple questions:
should we say the supervisor needs to approve the contact being added? (ie: if in the Education type, I added "School Nurse") this would need to be approved by supervisor?
for "hiding" we are just greying out  - but will still be able to be selected if clicked on?

**Comment by compwron** [comment]
outdated...
