### ISSUE TITLE
Bulk Actions: assign and unassign volunteers to supervisor 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4873]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, there is no way to bulk assign volunteers to a supervisor. We would like to add this functionality to make it easier for adminsand/or supervisors to assign volunteers quickly. Please see the mocks and acceptance criteria below.

Please refer to the Figma file to see how the UI should look and how the UX should function. The below acceptance criteria represent this same behavior in checklist form.

Figma
[Figma link](https://www.figma.com/file/wRUtmMJCAFdfkUV5JWGu3V/R4G---CASA---Bulk-Actions?type=design&node-id=92%3A6669&mode=design&t=OkMwoBGKhmSdk6rA-1)
PS: Log into Figma to leave comments, and Mallory (our design lead) will respond to them!
 

**Acceptance Criteria**
Table overview

- Assume all table UI and dimensions remain the same unless otherwise noted
- [ ] Bottom border of each row spans the table
- [ ] Add checkboxes on the left of each row
- [ ] Change the “Extra Languages” header to “Additional Languages”
- [ ] Move pagination items to the bottom of the table and change all text to “Content 3” text style and update wrap of right pagination item
- [ ] Remove “Responsive Data Table” heading
- [ ] Change search bar font to “Content 1” text style
- [ ] When screen width is 1024px or below, remove the checkbox column and related functionality
 
Row checkbox functionality

- [ ] The default state is that the check box is unselected
- [ ] On row hover, shadow appears behind row (see https://demo.plainadmin.com/task for reference)
- [ ] On box click, highlight row with color and change checkbox to blue box with white checkmark
- [ ] When at least one but not all checkboxes have been clicked, change header checkbox to blue box with white line
- [ ] When at least one checkbox has been selected display “Manage Volunteer” button above table (update number and add or remove “s” after “Volunteer” to match number of selected boxes)
- [ ] When checkbox on header row is selected, check all checkboxes in the table
- [ ] When checkbox on header row is deselected, uncheck all checkboxes in the table
- [ ] When any checkboxes are unselected return row to default state
 
Manage Volunteers Button (On-click)

- [ ] When “Manage Volunteers” button is selected display a modal and page backdrop
- [ ] On hover of dropdown in modal, outline the dropdown box in colored border
- [ ] On click, display names of all supervisors and a “None” option
- [ ] On hover in the dropdown list, highlight hovered item in blue
- [ ] On click, display a checkmark on the left of selection, close dropdown, and display selection in place of “Choose a supervisor”
- [ ] When dropdown is open, after a selection is made, and without hover, selected item returns to original color and continues to display checkmark
- [ ] When "Cancel" or "X" is selected in modal, close modal and backdrop and return to original screen while maintaining row selections
- [ ] On click of “Confirmation,” close modal, reflect changes in Volunteers table:
If "None" is selected from dropdown and confirmed, update each selected Volunteer’s Supervisor to unassigned/empty
Otherwise, update Supervisor for each Volunteer to selected Supervisor

**References**:
Modal reference is “Modal 3” at following link: https://demo.plainadmin.com/modals.html
Dropdown reference is on “Selects” card at the following link: https://demo.plainadmin.com/form-elements.html

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by MalloryPriceDesign** [comment]
@bcastillo32 I have thrown together a rough Figma mock of what this flow could look like. This isn't pixel perfect but I wanted your feedback on if this achieves the desired user story. I left some comments on the file, which are only viewable if you're logged into Figma. 

https://www.figma.com/file/dS8qPLIVFwa3zNPsq7ukNp/Volunteers-table-view-with-multiselect?type=design&node-id=0%3A1&t=SKtYRMjnAoe3ZZgX-1

**Comment by bcastillo32** [comment]
> @bcastillo32 I have thrown together a rough Figma mock of what this flow could look like. This isn't pixel perfect but I wanted your feedback on if this achieves the desired user story. I left some comments on the file, which are only viewable if you're logged into Figma.
> 
> https://www.figma.com/file/dS8qPLIVFwa3zNPsq7ukNp/Volunteers-table-view-with-multiselect?type=design&node-id=0%3A1&t=SKtYRMjnAoe3ZZgX-1

these look great. I like the modal that you decided to use. Makes it very clear what the user is about to do.

**Comment by compwron** [comment]
Same as https://github.com/rubyforgood/casa/issues/2523 ?

**Comment by bcastillo32** [comment]
duplicate issue

**Comment by bcastillo32** [comment]
dupe ticket
