### ISSUE TITLE
Add Backend Check for Twilio Service

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4880]
part of #4815 

**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Implement a check for Twilio Service and disable SMS services when a casa org’s twilio feature is not enabled. 

Affected Areas:
-> controller updates 
-> models 
-> database 
-> RSpec Factory 
-> notifications/services 
-> lib/tasks 

Acceptance Criteria:
- If the feature is not enabled -> disable all SMS features

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hello!
