### ISSUE TITLE
Adding frontend update for Twilio UI 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4881]
Part of #4815 

**What type(s) of user does this feature affect?**
 - volunteers?
 - supervisors?
 - admins?

**Description**
Update Frontend with changes to views and new JS files -> Adding the accordion Twilio Feature for Edit CASA Org and other necessary frontend changes/safeguards 

- Log-in as as Admin 
- Navigate to "edit organization" (https://casa-qa.herokuapp.com/casa_org/1/edit)

Areas affected:
->Views (Casa Org, Users, Volunteers)
-> JS Files (Casa Org Accordion, SMS Reactivation)

Acceptance Criteria:
- Create a new checkbox for SMS under the organization features section
- Move the twilio fields under the new checkbox.
- Only show the twilio text fields if the SMS checkbox is checked
- Preserve the twilio field values when the SMS checkbox is unchecked

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hello Again!

**Comment by ShamiTomita** [comment]
PR Is Ready to merge! docker check failed bc of flaky test
