### ISSUE TITLE
Add Tests for an Orgs Disabled Twilio Feature

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4882]
Part of #4815 

**What type(s) of user does this feature affect?**
 - n/a

**Description**
RSpec Test Suite additions (testing for disabled Twilio), Tests all scenarios for when a casa org’s twilio functionality is disabled

Acceptance Criteria:
test for anytime Twilo SMS service is disabled

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Last One!
