### ISSUE TITLE
Bug: Additional Expenses Toggle Does Not Respect Organization Boundaries

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4890]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Current Behavior
Toggling additional expenses in the system settings toggles it for all organizations

### Expected Behavior
Toggling additional expenses in the system settings toggles it for only the organization of the logged in admin

### How to Replicate
1. - Log in as an admin.
2. - Expand "Group Actions" in the left sidebar menu.
2. - Click on "System Settings" in the left sidebar menu.
4. - Toggle the checkbox and submit
5. - Log in as a user from a different organization
6. Navigate to a case
7. Create a new case contact
8. The form does not show a section to enter additional expenses

See: https://rubyforgood.slack.com/archives/CVB0QJGVD/p1687212363179219?thread_ts=1687209198.690109&cid=CVB0QJGVD

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
@danaguilar all yours :)
