### ISSUE TITLE
Bug: Flaky Test for ./spec/system/court_dates/edit_spec.rb

### ISSUE THREAD

**Issue by ShamiTomita** [rubyforgood/casa#4893]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself.

./spec/system/court_dates/edit_spec.rb

### Environment
local and docker test kept failing without the inclusion of `sleep(1)`

### Current Behavior
without `sleep(1)`, the test does not sign out the admin and conflicts with `sign_in volunteer`

![Screenshot 2023-06-20 at 12 36 41 PM](https://github.com/rubyforgood/casa/assets/70528966/d43ef17a-3ec4-4378-bf59-d4611d0e2492)

Example Failure Output:
```
  1) court_dates/edit can't delete a future court date as volunteer
     Failure/Error: expect(page).not_to have_content "Delete Future Court Date"
       expected not to find text "Delete Future Court Date" in "Inbox\nSupervisors\nVolunteers\nOther Duties\nCases\nAdmins\nGroup Actions\nMenu\nUser 2806\nCourt Date\nJanuary 8, 2021\nEdit\nCase Number:\nCINA-2153\nCourt Report Due Date:\nNone\nJudge:\nRep. Lesley Will\nHearing Type:\nEmergency Hearing 74\nCourt Orders:\nCase Order Text Implementation Status\nSubiungo tristis nihil. Omnis verbera carus. Sit aut et. Accusamus soleo ut. Antea acceptus absconditus. Vinco quia stabilis. Allatus quasi aufero. Angelus turpis tabesco. Video administratio credo. Tabula asper thesis. Volaticus tricesimus vorago. Unimplemented\nDownload Report (.docx)\nDelete Future Court Date\n© CASA / Volunteer Tracking\nBuilt with by Ruby For Good\nReport a site issue\nSMS Terms & Conditions"

     [Screenshot Image]: /home/runner/work/casa/casa/tmp/capybara/failures_r_spec_example_groups_court_dates_edit_can_t_delete_a_future_court_date_as_volunteer_672.png


     # ./spec/system/court_dates/edit_spec.rb:98:in `block (2 levels) in <top (required)>'
```

### Expected Behavior
This test should pass without having to use `sleep(1)` which is inefficient/not best practice. 

### How to Replicate
ex: 
1. remove `sleep(1)` from the test's it block 
2. run test locally

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchatterji** [comment]
Hey, I'd like to work on that :)
