### ISSUE TITLE
Bug: Flaky test in spec/system/casa_cases/show_spec.rb

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4894]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself

### Environment
Docker

### Current Behavior
Example Failure
```
  1) casa_cases/show volunteer user when old case contacts are hidden should display only visible cases to volunteer
     Failure/Error: expect(page).to have_css("#case_contacts_list .card-content", count: 1)
       expected to find css "#case_contacts_list .card-content" 1 time but there were no matches

     [Screenshot Image]: /usr/src/app/tmp/capybara/failures_r_spec_example_groups_casa_cases_show_3_volunteer_user_when_old_case_contacts_are_hidden_should_display_only_visible_cases_to_volunteer_458.png


     # ./spec/system/casa_cases/show_spec.rb:205:in `block (4 levels) in <top (required)>'
```

### Expected Behavior
The test either passes every time or fails every time when the code is not modified.

### How to Replicate
This has been seen to fail in docker on github actions. It might be replicatable in a local docker setup.
from the project root:
`bundle exec rspec ./spec/system/casa_cases/show_spec.rb`

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchatterji** [comment]
i can work on that
