### ISSUE TITLE
Bug: Flaky Test in spec/services/volunteers_emails_export_csv_service_spec.rb

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4895]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself

### Current Behavior
Example Failure Output
```
1) VolunteersEmailsExportCsvService#call Exports correct data from volunteers
     Failure/Error: expect(results[1]).to eq("#{active_volunteer.email},No Old Emails,\"#{active_volunteer_cases.keys.join(", ")}\",#{active_volunteer.display_name},\"#{active_volunteer_cases.values.join(", ")}\"")

       expected: "email1927@example.com,No Old Emails,\"CINA-1187, CINA-1188\",User 1480,\"true, true\""
            got: "email1930@example.com,old_email@example.com,\"\",User 1483,\"\""

       (compared using ==)
     # ./spec/services/volunteers_emails_export_csv_service_spec.rb:20:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Expected Behavior
The test either passes every time or fails every time when the code is not modified.

### How to Replicate
Might not be replicatable locally
from the project root:
bundle exec rspec ./spec/system/casa_cases/show_spec.rb

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

### Questions?
Ask in a comment below

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ShamiTomita** [comment]
Hi @FireLemons, I have a fix for this test included in PR #4886 . I didn't create a separate issue/PR for it originally because I didn't know the protocol for flaky tests so I just tacked it on to that PR. I can make sure to make separate Bug Issues for flaky tests as soon as I come across them in the future.
