### ISSUE TITLE
Bug: Async Notifier Shows an Async Action in Progress on the Patch Notes Page Constantly

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4896]
### Impacted User Types
 - all casa admins

### Current Behavior
When I navigate to the patch notes page. The async notifier immediately shows a saving notification meaning an async action is in progress.

The notifier is seen here in the bottom right:
![image](https://github.com/rubyforgood/casa/assets/8918762/63aab5fe-e69b-453b-a947-2a6357fd2ea1)

### Expected Behavior
It does not show loading unless there is an async event in progress.

An example of an async event would be making a patch note and clicking on create. Create causes an [ajax](https://www.w3schools.com/xml/ajax_intro.asp) request to be sent to the server. The async even ends when the response comes back from the server usually in under a second.

### How to Replicate
ex: 
1. - Log in as an all casa admin.
2. - Click on "Patch Notes" in the left sidebar menu.

See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jamgar** [comment]
I can work on this.
