### ISSUE TITLE
Bug: Remove White Space Under Casa Case Checklist

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4900]
### Impacted User Types
 - volunteers

### Current Behavior
![image](https://github.com/rubyforgood/casa/assets/8918762/a48d6204-af6b-49f1-b5fd-ce5e3cd30bd1)

### Expected Behavior
The bottom of the white box should be near the last checklist item.

### How to Replicate
1. - Log in as a volunteer.
2. - Navigate to a casa case.
3. - Click "+ New case contact" near the top.

The pr that introduced the bug: https://github.com/rubyforgood/casa/pull/4879/files

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by zeeshan-haidar** [comment]
I can work on this

**Comment by bcastillo32** [comment]
@zeeshan-haidar assigning you. :)

**Comment by zeeshan-haidar** [comment]
Hi, I checked but this one is working fine for me, I tried on Chrome and Firefox 

![Screenshot from 2023-06-28 12-08-35](https://github.com/rubyforgood/casa/assets/82927963/a968c26c-0974-4903-acbb-6291c131aa8b)

**Comment by zeeshan-haidar** [comment]
> Hi @bcastillo32 , I tried to reproduce this bug but this one is working fine for me, I tried on both Chrome and Firefox
> 
> ![Screenshot from 2023-06-28 12-08-35](https://user-images.githubusercontent.com/82927963/249383778-a968c26c-0974-4903-acbb-6291c131aa8b.png)

my bad, the recompile assets was needed, now it's reproducing :)
