### ISSUE TITLE
Feature Flag Controls for All Casa Admin

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4914]
**What type(s) of user does this feature affect?**
 - all casa admins

**Description**
[Feature Flag Definition](https://www.productplan.com/glossary/feature-flag/)

We have a table of booleans called `feature_flags`
Add a page for all casa admins where feature flags can be toggled.
Write tests

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by strangeforloop** [comment]
I am taking this issue :)

**Comment by strangeforloop** [comment]
Still working on it

**Comment by strangeforloop** [comment]
working

**Comment by FionaDL** [comment]
Picking this up
