### ISSUE TITLE
Make Additional Expense Organization Toggle Visibility Linked to Additional Expense Feature Flag

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4915]
**What type(s) of user does this feature affect?**
 - admins

**Description**
Admins have access to an organization settings page. On that page there is a toggle for the additional expense feature for just their organization.

![additional expense organization toggle](https://github.com/rubyforgood/casa/assets/8918762/9b6f83b2-376b-40e4-8cce-fe6b54dc6305)

There is an additional expense feature flag which toggles additional expenses for all organizations. When the feature flag is turned off, do not render the additional expense checkbox on the organization settings page.

Like this:
![image](https://github.com/rubyforgood/casa/assets/8918762/14084a59-94d8-4106-92df-7713d1ba4c0f)

Write/update tests if needed

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchatterji** [comment]
I can work on this
