### ISSUE TITLE
Make test_checker.rake respect request tests for controllers

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4917]
Make https://github.com/rubyforgood/casa/blob/main/lib/tasks/test_checker.rake respect request tests for controllers
As in the test for https://github.com/rubyforgood/casa/blob/main/app/controllers/casa_org_controller.rb is https://github.com/rubyforgood/casa/blob/main/spec/requests/casa_org_spec.rb but https://github.com/rubyforgood/casa/blob/main/.allow_skipping_tests#L11 ignores the controller because it does not pick up the test.

**Comment by sandfortw** [comment]
I would be interested in taking this issue, is there a process for getting assigned? This would be my first issue with Ruby for Good.

**Comment by bcastillo32** [comment]
@sandfortw I can assign you :)
