### ISSUE TITLE
Bug: Flaky Test Sent Emails Table Not Found

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4922]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### Sample Error Output:
```
   1) casa_org/edit has sent emails table
     Failure/Error: scroll_to(page.find("table#sent-emails", visible: false))

     Capybara::ElementNotFound:
       Unable to find css "table#sent-emails"

     [Screenshot Image]: /home/runner/work/casa/casa/tmp/capybara/failures_r_spec_example_groups_casa_org_edit_has_sent_emails_table_100.png


     # ./spec/system/casa_org/edit_spec.rb:90:in `block (2 levels) in <top (required)>'
```

### How to Replicate
Try running the test lots of times locally
`bundle exec rspec spec/system/casa_org/edit_spec.rb`

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sandfortw** [comment]
I was curious about this and ran this ~200 times locally, and was not able to reproduce the test failure. Is there an easy way to run the test suite a certain number of times with github actions  to try to make it fail that way? I want to test if just adding a wait fixes it, or, if not, see if I can figure out what else could be happening.

**Comment by sandfortw** [comment]
Just an update, I've figured out a way to run the test many times in CI without running the whole suite. So far I have not been able to replicate the failure.

**Comment by sandfortw** [comment]
I am unable to reproduce this.
