### ISSUE TITLE
Bug: Fix CASA logo ratio 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4925]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
CASA web app

### Current Behavior
Logo is distorted

### Expected Behavior
logo is correct ratio

### How to Replicate
ex: 
1. Log in as a volunteer, admin or supervisor.
2. look at logo at top left on nav bar

Distorted logo

<img width="220" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/d68c7e84-f7d0-40c8-941d-439939145a34">

Correct logo ratio

<img width="289" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/9504bc40-9124-4a4f-8c56-ef1f34515d27">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by gabrielcnunez** [comment]
I would like to be assigned this issue, and it will be my first issue with Ruby for Good! 🎉

**Comment by bcastillo32** [comment]
@gabrielcnunez please let me know if you like to work on this before https://github.com/rubyforgood/casa/issues/4927 :)

**Comment by gabrielcnunez** [comment]
@bcastillo32 I have the fix for this issue ready to push up to my forked repo for a PR, so I'll take this one first. Thanks!

**Comment by bcastillo32** [comment]
@gabrielcnunez all set, thank you!

**Comment by FireLemons** [comment]
Last pr doesn't preserve image aspect ratio

**Comment by gabrielcnunez** [comment]
@FireLemons Another PR was made to correct this issue that preserves the aspect ratio of any logo that may be used in the future.
