### ISSUE TITLE
Bug: Left nav bar behavior 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4926]
### Impacted User Types
 - volunteers
 - supervisor
 - admins

### Environment
CASA web app

### Current Behavior
1. The "Group Action" menu item appears active when user is viewing other pages
2.  "Learning Hours" Menu item does not appear active when viewing that page

The indicator is the vertical  blue line that is at the left edge of each menu item

<img width="237" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/ada5384d-a7a4-4819-917c-2ed21ad99917">
<img width="838" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/c3f7d1c2-71c4-4ebb-abfb-93f4ed65eaed">

### Expected Behavior
whichever page you are viewing - only that item should be active

### How to Replicate
ex: 
1. Log in as a volunteer, admin or supervisor.
2. click on a menu item
4. click on "Learning Hours"

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchatterji** [comment]
I can work on this

**Comment by jamgar** [comment]
@bcastillo32 getting a little different behavior outlined below. Either way the goal for this issue is the same **whichever page you are viewing - only that item should be active** so will pick this up and focus on that.

1. Getting same for **The "Group Action" menu item appears active when user is viewing other pages**
2. For **Learning Hours" Menu**, "Group Action" is highlighted, but "Learning Hours" is not. (See example below)

![image](https://github.com/rubyforgood/casa/assets/14931684/79132127-5ecb-45cc-811f-4b59e8a5b523)

**Comment by bcastillo32** [comment]
@jamgar that is odd! but yes you are correct, the page you are on should be the one that is "active" with the icon

**Comment by jamgar** [comment]
@bcastillo32 I have been able to fix the of Group Actions to not appear active when on other pages. However, I have a question on how do we want to handle the behavior of the styling for the Group Actions menu. How this active state is handled for these menu items, formerly and currently, is by using a helper method in rails based on the URL. When you click on Group Actions it does not navigate to a URL so it never becomes active. The only time it shows the blue vertical bar is when in a user hovers over it. The submenu item that is clicked on does change to an active state when clicked on. See example below. So the question is does Group Actions need be shown active at any time? If so, I will need to change the approach from using the rails helper method to implementing this active menu behavior with Javascript.  

![image](https://github.com/rubyforgood/casa/assets/14931684/b25bd224-1a81-46bb-b929-ee7385ac4794)

**Comment by bcastillo32** [comment]
> @bcastillo32 I have been able to fix the of Group Actions to not appear active when on other pages. However, I have a question on how do we want to handle the behavior of the styling for the Group Actions menu. How this active state is handled for these menu items, formerly and currently, is by using a helper method in rails based on the URL. When you click on Group Actions it does not navigate to a URL so it never becomes active. The only time it shows the blue vertical bar is when in a user hovers over it. The submenu item that is clicked on does change to an active state when clicked on. See example below. So the question is does Group Actions need be shown active at any time? If so, I will need to change the approach from using the rails helper method to implementing this active menu behavior with Javascript.
> 
> ![image](https://user-images.githubusercontent.com/14931684/252521568-b25bd224-1a81-46bb-b929-ee7385ac4794.png)

Hi! I think I understand what you are saying. So instead of showing “Group Actions” as active it seems like it would make more sense to just highlight whatever page is active on the submenu. With that being said, I don’t see any reason why we would ever need to show “Group Actions” as active. Does this help?

**Comment by jamgar** [comment]
Yes that helps! Thank you 😄

**Comment by littleforest** [comment]
Fixed in https://github.com/rubyforgood/casa/pull/4982
