### ISSUE TITLE
Bug: Standardize Main Headers

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4927]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
CASA web app

Currently, the main headers are all different sizes

Please standardize the top header on all pages to be h1 (font-size: 32px and font-weight: 700)

### How to Replicate
ex: 
1. Log in as a volunteer, admin, or supervisor.
2. navigate to any page on the app and you'll notice the inconsistencies in the sizes of the top headers. 

here is an example in "My Cases" where the "My Cases" header is an h2
<img width="1918" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/0f52b6aa-8de2-4a69-b391-c2f8e0054bb7">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by gabrielcnunez** [comment]
I would like to take this issue.  After navigating through most of the views, it feels like the h1 headers (e.g. "Other Duties" in the screenshot above) are more out-of-place stylistically than the h2 headers.  I searched all files for both header tags, and there are over twice as many h2's (45) than h1's (22).  Would it make more sense to change the h1 tags instead?

**Comment by bcastillo32** [comment]
@gabrielcnunez thanks for grabbing this one! We took that into consideration and decided to go the route specified in the ticket. To our designer, it made more sense to standardize the top headers.

**Comment by bcastillo32** [comment]
HI @gabrielcnunez are you still working on this? :)

**Comment by gabrielcnunez** [comment]
Hi @bcastillo32!  I am still working on this, appreciate the reminder.
