### ISSUE TITLE
Allow supervisors to download reports of case contacts

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#493]
Part of epic #529 

**What type of user is this for? [supervisor/admin/volunteer/all or All CASA Admin]**
supervisor

**Where does/should this occur?**
Reports should be accessible on the frontend via dropdown menu accessible by clicking on the logged in user's email in the upper right hand corner of the screen, (See screenshots below for reference.) [which should lead to this page](https://casa-r4g-staging.herokuapp.com/reports).

**Description**
Allow Supervisors to download reports of all case contacts, just like Admins can. (No difference in what displays on the reports).

**Screenshots**
The path to accessing this page for Supervisors should look like this:
![generate reports](https://user-images.githubusercontent.com/62810851/92309774-3a758a00-ef5d-11ea-93a4-8d0b4502b527.png)

**Comment by Zrrrpy** [comment]
@compwron FYI I revised this to simplify and essentially just enable access to [reports page](https://casa-r4g-staging.herokuapp.com/reports) for supervisors. I'll file a separate issue about report filters for both Admins & Supervisors (no permission issues with supervisors seeing case contacts from volunteers not assigned to them).
