### ISSUE TITLE
Bug: Button color accessibility 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4936]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
web app

### Current Behavior
The are currently buttons using inaccessible background colors: yellow (#F7C800) and light blue (#00C1F8)
<img width="1511" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/82ac6080-11bd-43ee-b227-379b4d3f9175">

### Expected Behavior
please change background color of all yellow (#F7C800) and light blue (#00C1F8) buttons to the darker "primary" blue (#4A6CF7).

### How to Replicate
ex: 
1. Log in as an admin or supervisor.
2. there are examples of yellow and light blue buttons in Edit profile, and the menu button that is at the top left of the page

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highan ad slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kaysiz** [comment]
I can work on this

**Comment by Iverick** [comment]
I can work on this
