### ISSUE TITLE
Bug: "Edit" button Style 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4937]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
web app

Style the edit buttons in all tables to look like the edit button on the "My Cases" page (unbold). See screenshot.
<img width="132" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/3a765e42-ba10-4321-8a55-d4e5829ba8ff">

here is an example of a bold "Edit" button - we do not want them to be bold like the ones in the pic below
<img width="165" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/927412b9-a8bb-4956-ac76-3db3652a2420">

You can also find a bolded "Edit" button "Edit" button when logged in as a volunteer under "Cases Contacts"
![image](https://github.com/rubyforgood/casa/assets/77401173/24b38b9f-9b24-45ab-8161-d94b9ae54e80)

### How to Replicate
ex: 
1. Log in as an admin
2. example of bold "Edit" buttons are in "Admins" tab 
3. example of preferred unbold "Edit" button in "Cases" tab

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kaysiz** [comment]
I can work on this one

**Comment by gabrielcnunez** [comment]
I would like to work on this one.  A similar bolded "Edit" button appears when logged in as a volunteer under "Cases Contacts"

<img width="637" alt="Screenshot 2023-07-05 at 2 48 44 PM" src="https://github.com/rubyforgood/casa/assets/108249540/4a8c14d0-57ab-4730-87e1-19a711c4fe1d">

@bcastillo32 Can this button fix be included with this issue?
