### ISSUE TITLE
Bug: "Actions" in "My Cases" table

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4938]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
web app

Currently, there is a "Actions" column in the "My Cases" table - when clicked it takes you to the case details. We can already access case details by clicking on the actual case number link - so this is redundant - Please remove the "Actions" column from this table. 
<img width="1883" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/81ddfd6f-3c9c-4c20-af01-0306203e2d27">

### How to Replicate
ex: 
1. Log in as a volunteer or supervisor.
2. Click on Cases

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchatterji** [comment]
I can work on this
