### ISSUE TITLE
Bug: casa case url slug should update when case number is updated

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4939]
### Impacted User Types
all

### Environment
all

### Current Behavior
Bug: casa case url slug should update when case number is updated

See https://rubyforgood.slack.com/archives/CVB0QJGVD/p1688346454341029?thread_ts=1688346323.871039&cid=CVB0QJGVD

Steps to replicate:
1. make casa case with case number FOO
2. change casa case case number to FOO2
3. see url ("slug") not change
we use https://github.com/norman/friendly_id
make it update on field change

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchatterji** [comment]
I can work on this

**Comment by fchatterji** [comment]
Added a PR, note that I did not change the incorrect slugs of existing casa cases, as it was not mentionned in the issue. Maybe it could have been done in an afterparty?
