### ISSUE TITLE
Add white backgroundcard for "Communication Preferences" section

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4952]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
currently, the "Communication Preferences" section does not have a white background card like the other sections in "Edit Profile". Please add a white background card behind the "Communication Preferences" section

<img width="1912" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/eed9298c-a3f8-44e2-816d-c4ef8f8e9601">

Log-in as volunteer
click on drop-down on the top right next to the name of the user
click "Edit Profile"

**Acceptance Criteria**
- "Communication Preference" section has a white background card similar to the section above it.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
It seems to be somewhat related to https://github.com/rubyforgood/casa/issues/4936 so I can handle this as well

**Comment by bcastillo32** [comment]
thank you @Iverick !
