### ISSUE TITLE
Bug: "New Case Contact" button alignment

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4957]
### Impacted User Types
 - volunteers

### Environment
CASA webapp

### Current Behavior
currently, the "New Case Contact" button is not aligned with the header like on other pages
<img width="418" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/eb4de2a8-b65a-4a1c-bef5-e25789789767">

### Expected Behavior
the screenshot below is an example of how the "New Case Contact"  button should be aligned (to the right of the header text). 
<img width="509" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/2d9dbbc6-f2ba-4e77-b95d-d26f41183e64">

Please align the "New Case Contact" button with the “Case Contacts” header to match the style of other pages like the Learning Hours header

### How to Replicate
ex: 
1. - Log in as a volunteer
2. - Click on the "Case Contacts" tab on the left nav bar

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mgrigoriev8109** [comment]
Can I be assigned this issue?

**Comment by bcastillo32** [comment]
@mgrigoriev8109 yes! assigning now :)

**Comment by bcastillo32** [comment]
@mgrigoriev8109 still working on this? :)

**Comment by mgrigoriev8109** [comment]
@bcastillo32 will be getting started on this either this weekend or next week. Sorry for the delay, life got in the way and lost track.

**Comment by bcastillo32** [comment]
> @bcastillo32 will be getting started on this either this weekend or next week. Sorry for the delay, life got in the way and lost track.

thank you for the update. No worries.
