### ISSUE TITLE
Add foreign key contraint for creator_id in notes table

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4959]
**Description**
Create a foreign key constraint using a [migration](https://guides.rubyonrails.org/active_record_migrations.html) for the `creator_id` column on the notes table.

**Screenshots of current behavior, if any**  
![image](https://github.com/rubyforgood/casa/assets/8918762/de2038ec-2f61-4f7d-9e9f-9b2a7a956a4b)

Comparison to a table with the constraint:
![image](https://github.com/rubyforgood/casa/assets/8918762/96dff62f-23ef-49c6-ab7a-b8295473000d)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by zeeshan-haidar** [comment]
I can work on this

**Comment by zeeshan-haidar** [comment]
@FireLemons Hi, the PR for this issue has been merged but issue is still Open, because the Resolves# number was wrong on PR at the time of merge which I later updated with correct one, so you can close this issue, thanks

**Comment by littleforest** [comment]
Fixed in https://github.com/rubyforgood/casa/pull/4978
