### ISSUE TITLE
Bug: "Created by" label in Case Contact cards

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4962]
### Impacted User Types
 - volunteers
 - supervisors
 - admins
 

### Environment
CASA web app

### Current Behavior
currently, the "Created by" label for a contact is below the contact card
<img width="1115" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/400dcb11-2310-47d8-9fd3-4ce20bd1af3e">

### Expected Behavior
Please move the "created by" label to be within the card

### How to Replicate
ex: 
1. Log in as an admin or volunteer
2. click on the "Case Contacts" tab on the on the left nav bar

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by naomiyocum** [comment]
I can work on this!
