### ISSUE TITLE
Bug: Learning Hours table

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#4963]
### Impacted User Types
 - volunteers

### Environment
CASA web app

### Current Behavior
Currently, the Learning Hours table has a column titled "Actions>" where you can click "See More"
<img width="1191" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/c264903f-8d79-4c90-beee-fe4725f741fb">

### Expected Behavior
Make the "Title" clickable (adopt the behavior of the "Actions>" field) and remove the "Actions>" field in the table

### How to Replicate
ex: 
1. Log in as a volunteer.
2. click on the "Learning Hours" tab on the left nav bar.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
I can work on this
