### ISSUE TITLE
Add foreign key contraint for casa_case_id in placements table

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4977]
**Description**
Create a foreign key constraint using a [migration](https://guides.rubyonrails.org/active_record_migrations.html) for the `casa_case_id` column on the placements table.

**Screenshots of current behavior, if any**  
![image](https://github.com/rubyforgood/casa/assets/8918762/d3af7337-e4db-408f-9b04-38abe75f96ab)

Comparison to a table with the constraint:
![image](https://github.com/rubyforgood/casa/assets/8918762/79062bd3-235b-4a4a-b3f0-3b052fbf29a9)

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by oscarada87** [comment]
I can work on this

**Comment by kassandraleyba** [comment]
Hi! I can work on this @FireLemons

**Comment by kassandraleyba** [comment]
Thank you! @littleforest

**Comment by Br0k3nh4nd012** [comment]
@littleforest Can i work on this?

**Comment by kassandraleyba** [comment]
Hey, @Br0k3nh4nd012. I'm working on this! (:

**Comment by kassandraleyba** [comment]
Hi! I need more time, thanks!

**Comment by kassandraleyba** [comment]
Can I get permission to push my branch to the repo so I can create a PR?

**Comment by kassandraleyba** [comment]
Can I get permission to push my branch to the repo so I can create a PR? @littleforest @FireLemons

**Comment by littleforest** [comment]
@kassandraleyba I added you.

**Comment by kassandraleyba** [comment]
Can I get a review on this? Thanks :)
