### ISSUE TITLE
Error Reporting for Column Visibility Settings Saving

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4980]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
The settings for which columns are visible in the volunteers table are saved automatically via ajax.  

 - Display errors to the user when the request to save the settings responds with an error using the async notifier.  
 - Print the error in detail in the browser console.

Async Notifier (shows toasts in response to async events):
See: https://github.com/rubyforgood/casa/blob/main/app/javascript/src/async_notifier.js
See: https://github.com/rubyforgood/casa/blob/main/app/views/shared/_async_notifier.erb
Example Javascript Usage: https://github.com/rubyforgood/casa/blob/main/app/javascript/src/all_casa_admin/patch_notes.js

Pull Request Adding Column Saving:
See: https://github.com/rubyforgood/casa/pull/4840

See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by xeniabarreto** [comment]
I am working on it.

**Comment by xeniabarreto** [comment]
@FireLemons,

While simulating a scenario, I noticed that the error message during the preferences update is returning a status code 200. My question is: is this a standard handling, or should I modify it to use a more appropriate status code for errors?
