### ISSUE TITLE
Volunteers should be rerouted when trying to make a new casa case

### ISSUE THREAD

**Issue by cjilbert504** [rubyforgood/casa#499]
**What is the problem, and what should happen instead?**
Currently, if a volunteer navigates to https://casa-r4g-staging.herokuapp.com/casa_cases and clicks on the "New CASA Case" button they are shown an error screen. Instead the volunteer should be rerouted to a page of which they are authorized to be on and shown a friendly message expressing that they are not authorized to do the previously attempted action. 

**Screenshots of current behavior, if any**
![image](https://user-images.githubusercontent.com/54157657/89695063-56432d00-d8d8-11ea-8dc2-e90193f7f272.png)
![image](https://user-images.githubusercontent.com/54157657/89695082-60652b80-d8d8-11ea-9996-dab771e802c4.png)

**Comment by alindeman** [comment]
If we just hid the button from users who are not authorized to create new cases, would that sufficiently solve the issue as well?

**Comment by cjilbert504** [comment]
Per @compwron from a slack thread about this: 
"The volunteer should not be able to add a casa case. The volunteer should not be able to see the “add casa case” page, and also if the volunteer tried an action they are not allowed to do, they should see a nice error and be redirected, instead of the error page in the screenshot."
So I believe the volunteer should be redirected just from trying to access this page.
