### ISSUE TITLE
Fix Upload Template button on Admin UI

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4992]
see console for errors
https://casa-qa.herokuapp.com/casa_org/1/edit
<img width="433" alt="Screenshot 2023-07-19 at 6 38 28 PM" src="https://github.com/rubyforgood/casa/assets/578159/d517a385-8a6b-401d-8cbb-5dc40bf623a8">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
I have a fix for this issue

**Comment by Iverick** [comment]
I think the problem was with a broken Twilio toggle form rather than with the upload section. I got a fix for errors displayed in the console but I'm unsure if I have to make a PR here or create a separate issue.
