### ISSUE TITLE
Add Download Current Template button for Admin UI

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#4993]
<img width="428" alt="Screenshot 2023-07-19 at 6 42 42 PM" src="https://github.com/rubyforgood/casa/assets/578159/48dee7cb-cec6-4667-bf96-4eefffed3218">
https://casa-qa.herokuapp.com/casa_org/1/edit

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by xeniabarreto** [comment]
We need to insert a button to download the document, for example "CINA-11-1002..."
Please, could you give me more information?
