### ISSUE TITLE
Add a banner that can be customized to the top of the screen

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#4996]
**What type(s) of user does this feature affect?**
 - volunteers?
 - supervisors?
 - admins?

**Description**

One of the organizations would like to display a banner temporarily to the volunteers when they sign in that has a link to a survey they are trying to promote.

Requirements
1. The banner must be viewable at the organization level (Prince George's County can display a banner that is not viewable to Howard's county)
2. The banner must be able to be toggled on or off by an admin (maybe supervisor is okay too?)
3. The banner text should be editable by an admin or supervisor (using Action Text rich text editor ideally)

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by metamoni** [comment]
Happy to work on this. Do we have any mockups for what we want it to look like and where we want it to be?

**Comment by littleforest** [comment]
@metamoni are you going to be at the DC event? We were actually going to hold this ticket for this weekend.

**Comment by metamoni** [comment]
I won't be there. I've unassigned myself from it.
