### ISSUE TITLE
Admin view/edit individual volunteer

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/casa#5]
This is part of epic "Admin view" (#4 ). Relates to issue #91 (change volunteer assignment).

**What type of user is this for? [volunteer/admin/supervisor/all]**
admin

**Where does/should this occur?**
When an admin is on their dashboard and clicks the "edit" button on a volunteer and are taken to the <a href="https://casa-r4g-staging.herokuapp.com/volunteers/6/edit">edit volunteer page</a> 

**Description**
Here, admins should be able to:
- see and **edit** volunteer display name
- see and **edit** volunteer email address
- see volunteer start date (date formatted: dd/mm/yyyy)
- see and **edit** volunteer status to be active or inactive (maybe as a radio button, dropdown,  or toggle? Have fun!) - you will need to add this database column
- see a list of cases assigned to the volunteer, with an "edit" link for each which links to the edit case view, and an "unassign" link which unassigns the case from the volunteer
- assign volunteer to new case
- deactivate volunteer account (see issue #204)

Future work (NOT in this issue):
1. At the bottom should be a "View as the volunteer" button. (see #3 for full details on volunteer dash view)

**Relates to issues**
#21 #22 #204

**Comment by compwron** [comment]
Hey @jimnanney how is it going? Please reach out if you want any help. If you don't have time to work on this right now, that's totally ok, just let us know :)

**Comment by compwron** [comment]
Hey @jimnanney I hope stuff is good with you. I'd love for you to continue contributing to CASA- it doesn't have to be this task in particular or right now. If I don't hear from you in the next few days I'll unassign this ticket :)
