### ISSUE TITLE
Build draft support for the case contact form

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#5015]
**What type(s) of user does this feature affect?**
 - volunteers

**Description**

Build draft support for the case contact form. Sometimes volunteers take so long to fill it out the session times out on them and it would set us up for breaking the casa case form down into multiple screens.

**Screenshots of current behavior, if any**  
<img width="1102" alt="Screen Shot 2023-07-27 at 8 58 57 PM" src="https://github.com/rubyforgood/casa/assets/1938665/9d61624f-94a9-4e25-a5e4-e75ffc3ca7d0">
<img width="1224" alt="Screen Shot 2023-07-27 at 8 59 10 PM" src="https://github.com/rubyforgood/casa/assets/1938665/6641aac3-4733-4528-a9c7-e299353e076a">
<img width="938" alt="Screen Shot 2023-07-27 at 8 59 17 PM" src="https://github.com/rubyforgood/casa/assets/1938665/075812c1-bc37-4ec5-879e-6d589291f861">

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by meg-gutshall** [comment]
FYI: @carrollsa and I are working through this today

**Comment by meg-gutshall** [comment]
> This issue has been inactive for 247 hours (10.29 days) and will be unassigned after 113 more hours (4.71 days). If you have questions, please
> 
> If you are still working on this, comment here to tell the bot to give you more time

Slow your roll Git bot!

**Comment by schoork** [comment]
I'm gonna take this on.

**Comment by schoork** [comment]
Currently I anticipate 2 problems getting in the way.

**Problems:**
1. Autosave of the form completed by `case_contact_autosave.js`. 
2. Currently the form allows you to submit a case contact for multiple cases at once. When you submit the form, the controller copies the single case contact you submitted into one for each of the casa case ids you've checked. This pattern is problematic for the wicked gem (once the contact is stored in the database, it loses the ability to edit multiple at once).
![Case Contact DRAFT support](https://github.com/rubyforgood/casa/assets/50247514/68d3f51e-0011-4697-be6a-bb3efd1fe1b0)

**Proposed Solutions**
1. To deal with autosaving, I may just turn that off during development, and then see what should be added back at the end.
2. I think what makes sense is to have a column on the CaseContact table that stores all of the checked case contact ids. When the case contact is saved as a DRAFT, this column is filled and the case_contact_id is set to `nil`. When the draft is PUBLISHED, the new ids column is emptied and a case contact is made for each one with the appropriate `casa_case_id`.
![Case Contact DRAFT support - Proposed](https://github.com/rubyforgood/casa/assets/50247514/be27053b-11ac-4645-b49b-eabb1072a977)
