### ISSUE TITLE
Edit Organization: Manage Learning Hours

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5028]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
User Story: As an Admin of a CASA organization, on the "Edit Organization" page(QA: https://casa-qa.herokuapp.com/casa_org/4/edit), I would like to be able to manage the choices my volunteers are able to choose from the "Type of Learning" drop-down. 
<br />
![image](https://github.com/rubyforgood/casa/assets/77401173/2e78d31e-3201-4ab6-bf28-109a5bdcf4be)
![image](https://github.com/rubyforgood/casa/assets/77401173/f8ea186f-b750-4f23-9f34-747c240fce09)Volunteer view(QA): https://casa-qa.herokuapp.com/volunteers/139/learning_hours/new

Please make it look like the other "manage" sections in "Edit Organization"
<img width="1699" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/a56824fb-6ab6-4c6d-a4de-0bc1207addff">
<br />
Similar to this layout - "Manage Contact Types" -> "Manage Learning Hours" and the first card "Contact Type Groups" -> "Type of Learning"

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by schoork** [comment]
- will work like judge model (casa_org_id, active, name)
- afterparty task for converting enum to new _id column
- new issue for after prod deploy to remove enum column

**Comment by schoork** [comment]
Added issue #5039 for cleanup work after prod deployment.
