### ISSUE TITLE
Meta Issue: Test Suite Cleanup

### ISSUE THREAD

**Issue by meg-gutshall** [rubyforgood/casa#5037]
I ran the test suite on the entire codebase to see what warnings and deprecations would arise.

Also, specs tend to be forgotten once marked pending.

### Environment

The following screenshots are the result of running `bin/rails spec` locally on `main` after cloning down the app.

### Sample Error Output:

<img width="1662" alt="test-suite-warning-1" src="https://github.com/rubyforgood/casa/assets/37842352/9cb9ae0f-7167-425f-b84d-b1ec52b19253">
<img width="1662" alt="test-suite-warning-2" src="https://github.com/rubyforgood/casa/assets/37842352/e5c853ed-8719-42b1-9b8a-98a320915e3b">
<img width="1805" alt="test-suite-warning-3" src="https://github.com/rubyforgood/casa/assets/37842352/4ba2f1c6-45de-4321-9dc7-dcc1bcf01b07">
<img width="1805" alt="test-suite-warning-4" src="https://github.com/rubyforgood/casa/assets/37842352/3f6771e6-896a-4050-8ccf-560ac7a0fbfa">
<img width="1822" alt="test-suite-warning-5" src="https://github.com/rubyforgood/casa/assets/37842352/6b5641c4-3f0c-4678-b9d3-7e54a79ae15d">
<img width="1822" alt="test-suite-warning-6" src="https://github.com/rubyforgood/casa/assets/37842352/283fce0e-a769-48e5-83ca-cfe1b7c270c7">
<img width="1822" alt="test-suite-warning-7" src="https://github.com/rubyforgood/casa/assets/37842352/a9b5202b-9aad-4316-8a25-c8456602b2cc">

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by meg-gutshall** [comment]
@littleforest Do you want to groom this a little?

**Comment by bcastillo32** [comment]
linked PR merged https://github.com/rubyforgood/casa/pull/5053

**Comment by littleforest** [comment]
This actually has a lot of things to work on still. Haven't gotten to them all.

**Comment by sean-dickinson** [comment]
@littleforest I'd be happy to open a PR for some of the low hanging fruit if you like.

**Comment by littleforest** [comment]
@sean-dickinson that would be great, thanks!

**Comment by compwron** [comment]
This is super valid and we should do more with fixing testing. I am closing this as old. We may bring it back in a different form.
