### ISSUE TITLE
Remove deprecated hearing_type_id and judge_id from casa_cases table

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#5044]
## Description
The `hearing_type` and `judge` associations were moved from the CasaCase model to the CourtDate model in #3770. These fields are no longer needed on the CasaCase model.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
I can work on this
