### ISSUE TITLE
Bug: Flaky Test with spec/models/case_contact_spec.rb:453

### ISSUE THREAD

**Issue by schoork** [rubyforgood/casa#5050]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### Environment
docker

### Sample Error Output:
```
Failure/Error:
       expect(groups_with_types).to eql(
         {
           "Family" => ["Parent"],
           "Health" => ["Medical Professional", "Other Therapist"]
         }
       )

       expected: {"Family"=>["Parent"], "Health"=>["Medical Professional", "Other Therapist"]}
            got: {"Family"=>["Parent"], "Health"=>["Other Therapist", "Medical Professional"]}

       (compared using eql?)

       Diff:
       @@ -1,3 +1,3 @@
        "Family" => ["Parent"],
       -"Health" => ["Medical Professional", "Other Therapist"],
       +"Health" => ["Other Therapist", "Medical Professional"],
     # ./spec/models/case_contact_spec.rb:453:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### How to Replicate
Try running the test lots of times locally
`bundle exec rspec spec/models/case_contact_spec.rb:453`

Ran fine locally, failed in [CI](https://github.com/rubyforgood/casa/actions/runs/5705992317/job/15461231292?pr=5048).

Looks like the expected vs. got was just a different order in the array.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Gokul312-rently** [comment]
HI @schoork, I am new to open-source contribution. 
Can I work on this issue?

**Comment by schoork** [comment]
Absolutely! I will assign you to it.

**Comment by Br0k3nh4nd012** [comment]
Hey @schoork, sorry for the confusion. I have commented on different GitHub accounts previously.
Could you please assign it to this account?
Thanks.
