### ISSUE TITLE
Spell check codebase

### ISSUE THREAD

**Issue by meg-gutshall** [rubyforgood/casa#5056]
**Description**

There are misspellings scattered throughout the codebase which interfere with its functioning.

**Examples**

```diff
- request.referrer
+ request.referer

- recrusive: true
+ recursive: true
```

Fun fact: Yes, `referer` is technically spelled wrong above, but by the time it was realized, too many people were using it! Read the [HTTP referer etymology](https://en.wikipedia.org/wiki/HTTP_referer#Etymology) to learn more.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by xeniabarreto** [comment]
I am working
