### ISSUE TITLE
Replace Jest with Jasmine Javascript Testing Framework to the Project

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5085]
## Description
Jest cannot to my knowledge access any of the html generated by rails. Jasmine can wrap a rails page and run and display tests on it which allows selenium to read the output. It can also mock javascript time.  

- [ ] Install Jasmine
- [ ] Configure Jasmine to only turn on when running tests
- [ ] Replace the jest tests with jasmine tests
- [ ] Remove jest

## Screenshots of Jasmine
![image](https://github.com/rubyforgood/casa/assets/8918762/ba019780-523d-4bcb-a970-5077a7936244)
![image](https://github.com/rubyforgood/casa/assets/8918762/866ba23a-a7dd-4e91-834a-a5c5b58b140a)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Nwabor** [comment]
I can work on this..

**Comment by FireLemons** [comment]
Sorry someone else is already working on this.

**Comment by littleforest** [comment]
@FireLemons is there really a need for a separate JavaScript testing framework? Is there any reason why we can't just test JS behavior through the system specs?

**Comment by FireLemons** [comment]
There's no way to mock timeouts / intervals

**Comment by seanmarcia** [comment]
This *feels* like a bad idea. I'd really like to understand the problem this is solving before making major framework changes. This has the same feel to me as when Cypress was implemented and then we later needed to pull it out.

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.
