### ISSUE TITLE
Nav Bar Enhancement

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5086]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 

## Description
In an effort to improve the usability and overall feel of the app. We have made the decision to make a few changes to our navbar. Please refer to the [Figma file here](https://www.figma.com/file/iJ2vsIZHmNcAl5HPCfqvT4/Ruby-for-Good---CASA---Left-Navigation-Bar?type=design&node-id=0-1&mode=design&t=5LgOkxewS6NAW78f-0) and the acceptance criteria below - if you have any questions please ask @bcastillo32 (PM) and/or @MalloryPriceDesign (Design Lead). You can also message us on the casa slack channel. :) 

## Acceptance Criteria
**Hover Behavior and list item color**
Please reference [PlainAdmin's ](https://demo.plainadmin.com/icons) navbar - we want to use the same hover behavior and list item color as the PlainAdmin navbar

**Mobile (<770 px)**
**Closed State (default)**
1. The menu button is represented by a hamburger icon, with no text.
<br />

**Open State**
1. On click, the menu slides open from the left and a backdrop appears behind the menu.
2. At the top left of the menu is the hamburger button and on the top right is a horizontal logo.
- Logo updating behavior via the admin account should remain unchanged.
- The menu nav list items visual design and behavior is unchanged.
- Exiting the menu by clicking outside of the menu behavior should remain unchanged.
3. Clicking on the hamburger button in the open menu results in the menu sliding closed to the left.
<br />

**Desktop (>770 px)**
**Open State (default)**
1. The menu button is represented by a hamburger icon, with no text, and on the top right is a horizontal logo.
- Logo updating behavior via the admin account should remain unchanged.
- The menu nav list items visual design and behavior is unchanged.
2. Opening the nav bar displaces the site content to the right, this behavior is unchanged.
<br />

**Closed State**
1. Closing the nav bar results in a truncated nav bar, which includes the same hamburger button and the icons from the nav list.
2. Closing the nav bar expands the site content to the left, this behavior is unchanged.
<br />

**Hover State**
1. Hovering over the closed nav bar, starting at the list items and below, results in the nav bar expanding.
- This expansion does not displace site content.
2. Removing the mouse from hover, the nav bar returns to its closed state.
<br />

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by bcastillo32** [comment]
@MalloryPriceDesign

**Comment by MalloryPriceDesign** [comment]
Feel free to message me with any questions!

**Comment by malsmr** [comment]
is this ready to be worked on?

**Comment by bcastillo32** [comment]
> is this ready to be worked on?

yes it is. would you still like to work on this?

**Comment by jamgar** [comment]
If no one has started this I can work on this.

**Comment by bcastillo32** [comment]
@jamgar plz go ahead and grab it! I just assigned to you. Please reach out if you have any questions 😎

**Comment by jamgar** [comment]
@bcastillo32 or @MalloryPriceDesign do you have the updated horizontal logo?

**Comment by bcastillo32** [comment]
> @bcastillo32 or @MalloryPriceDesign do you have the updated horizontal logo?

Hi @jamgar  Happy to help. what logo are you referring to?

**Comment by jamgar** [comment]
> Hi @jamgar Happy to help. what logo are you referring to?

This one below. 
![image](https://github.com/rubyforgood/casa/assets/14931684/4b55bf46-5acc-4c16-add2-ba87a2191f75)

**Comment by MalloryPriceDesign** [comment]
@jamgar here's the horizontal logo. 
![CASA Horizontal Logo](https://github.com/rubyforgood/casa/assets/136859444/33fc19bf-ec9f-494d-8e7d-3b550aee0f96)

**Comment by bcastillo32** [comment]
@jamgar how are you doing? anything you need help with? :)

**Comment by jamgar** [comment]
I have removed myself from the assignment. If someone else has bandwidth to take this on please feel free to take. :)

**Comment by schoork** [comment]
I'll take a crack at it

**Comment by schoork** [comment]
@bcastillo32 @MalloryPriceDesign I have a [loom](https://www.loom.com/share/e3d3e34a8fbd44d9822f716a3c215f37?sid=d715fd89-b8f6-45aa-950a-71ef240da651) for you to check out where I am.

**Questions:**
1. Take a look at the loom starting around the 36th second. When a group is opened on desktop view and the user clicks the button to minimize the sidebar, what do you want to happen to the group? Should it be zipped up? Should it be left open?

**Notes:**

- These are the colors I could get from the Plain Admin sidebar:
  - Inactive: #9AA4CA
  - Hover: #365CF5
  - Looking back  I just realized text should be black/dark grey so I'll update that (will look like below)
- Appreciate any and all feedback!

![Screenshot 2023-10-06 at 4 37 06 PM](https://github.com/rubyforgood/casa/assets/50247514/a1766ca6-e9b6-4834-8b98-5b5892f2b8d5)

**Comment by MalloryPriceDesign** [comment]
> @bcastillo32 @MalloryPriceDesign I have a [loom](https://www.loom.com/share/e3d3e34a8fbd44d9822f716a3c215f37?sid=d715fd89-b8f6-45aa-950a-71ef240da651) for you to check out where I am.
> 
> **Questions:**
> 
> 1. Take a look at the loom starting around the 36th second. When a group is opened on desktop view and the user clicks the button to minimize the sidebar, what do you want to happen to the group? Should it be zipped up? Should it be left open?
> 
> **Notes:**
> 
> * These are the colors I could get from the Plain Admin sidebar:
>   
>   * Inactive: #9AA4CA
>   * Hover: #365CF5
>   * Looking back  I just realized text should be black/dark grey so I'll update that (will look like below)
> * Appreciate any and all feedback!
> 
> ![Screenshot 2023-10-06 at 4 37 06 PM](https://user-images.githubusercontent.com/50247514/273327023-a1766ca6-e9b6-4834-8b98-5b5892f2b8d5.png)

@schoork Thanks for your question! The dropdown should remain in the state that the user put it in. ie if they are in a page within the Group Actions, that menu should still be expanded in the nav bar.

What I saw in the Loom video looks great! Thanks for the hard work!

**Comment by bcastillo32** [comment]
@schoork The updated nav bar looks incredible! Thank you for getting this done and looking forward to working with you!
