### ISSUE TITLE
Make Case Group Names Unique Per Org

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5105]
## What type(s) of user does this feature affect?
 - supervisors
 - admins

## Description
Prevent duplicate case group names
Update the tests

## Screenshots of current behavior, if any
![image](https://github.com/rubyforgood/casa/assets/8918762/79182405-3921-4ce6-81df-0b0bb7100980)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sandfortw** [comment]
I have an open PR that should close this @FireLemons

**Comment by sandfortw** [comment]
Just got back from a trip. Should fix the last little issue here today.
