### ISSUE TITLE
Bug: Flaky Test Failed to Locate Element on New Case Contact Page

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5128]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
rspec

### Sample Error Output:
```
   1) case_contacts/new when admin with HTML in notes renders HTML correctly on the index page
     Failure/Error: expect(hello_line.first.include?(note_content)).to be true

     NoMethodError:
       undefined method `include?' for nil:NilClass

     # ./spec/system/case_contacts/new_spec.rb:197:in `block (4 levels) in <top (required)>'
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mattpettenato** [comment]
@FireLemons can I work on this?
