### ISSUE TITLE
Bug: Flaky Test Failed to click on new case button as admin

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5131]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
rspec in docker

### Sample Error Output:
```
  1) casa_cases/new when signed in as a Casa Org Admin when all fields are filled is successful
     Failure/Error: click_on "New Case"

     Capybara::ElementNotFound:
       Unable to find link or button "New Case"

     ...
     # ./spec/system/casa_cases/new_spec.rb:18:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jsobralgitpush** [comment]
Can i work on this one ?

**Comment by compwron** [comment]
peter is working on this https://rubyforgood.slack.com/archives/CVB0QJGVD/p1705550093325509

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.
