### ISSUE TITLE
Handle Exception Thrown when Attempting to Add the Same Language Twice as a User

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5132]
## What type(s) of user does this feature affect?
 - volunteers

## Description
Trying to add the same language twice results in an uncaught exception. Gracefully handle the error and show the user an error on the website instead.

To add a language twice, log in as a volunteer and go to edit profile in the top right.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @FireLemons Can you please assign me this issue?
