### ISSUE TITLE
Local Time Display Component

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5134]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 - all casa admins

## Description
Displayed time across the app has timezones determined by the server but the user may not have the same time zone as the server resulting in incorrect times. In some cases the time displayed is actually UTC time.

Create a [view component](https://viewcomponent.org/guide/getting-started.html) that renders the local time ~html with a unix timestamp and converts it to the local time on the client via javascript. Similar to [discord timestamps](https://www.pattlesstore.com/articles/how-to-use-timestamps-on-discord)~

The component should take as arguments
 - the time in unix timestamp format
 - the format

The [`title`](https://www.w3schools.com/TAGS/att_title.asp) of the component should show a more specific representation of the time.

~so on the page it will render something like <span><t: UNIX_TIME_VALUE, f: FORMAT ></span> and then javascript will convert the html into something human readable~ it's probably better to get the time zone from the cookies from the browser so no js required

Write Tests

See https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

## Screenshots of current behavior, if any
You can paste images on the clipboard here

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
Hi there, I want to take this issue! Can you assign it to me, please?

**Comment by SajjadAhmad14** [comment]
Hi @FireLemons 
I checked out the users/edit pages for all the mentioned users and it seems that time is correct. Can you produce a screenshot of the error [please?[](url)](url)
![time](https://github.com/rubyforgood/casa/assets/35504149/7c59030a-6149-4190-a956-e05cb562de90)

**Comment by SajjadAhmad14** [comment]
Give me more time
