### ISSUE TITLE
Bug: remove onHover clickable effect for "Role" and "email" on profile menu

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5137]
## Impacted User Types
 - volunteers
 - supervisors
 - admins
 

## Environment
desktop web

## Current Behavior
when I hover over the role or email, it highlights as if it those list items are clickable. The email and email are not supposed to be clicked on. 
<img width="369" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/07d0194f-cb71-46eb-b01e-43f5986e1c60">

## Expected Behavior
"role" and the email item in this dropdown should not highlight as clickable when hovered on.

## How to Replicate
ex: 
1. - Log in as a user
2. - Click on the profile menu at the top right of the screen

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
I can work on this
