### ISSUE TITLE
Remove "Inbox" tab from Left Navbar 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5152]
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Environment
web app

We currently have 3 spots in the app where we can access notifications. It is also named 3 different ways which is confusing. In an effort to improve usability of our app and clean up the UI - CASA folks are ok with removing "Inbox" tab from the navbar since it is accessible in 2 other spots. 
<img width="250" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/a069f777-4cd1-41de-8547-c357008e5176">

## How to Replicate
ex: 
1. - Log in as any role
2. - Locate "Inbox" on the left navbar

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by moizafzal936** [comment]
Hey @bcastillo32! I'm a software engineer experienced in Ruby on Rails, and I'd love to work on this issue. It seems like a great fit for my skill set. Could I be assigned to this? Looking forward to contributing!
