### ISSUE TITLE
Bug: Case Contact form "Go Back to Form" button doesn't work

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5153]
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Environment
web app

## Current Behavior
When you click the "Go Back to Form" button, it does nothing
<img width="1020" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/c71353b3-f5a4-4762-a5d9-6ee7ad1c64a4">

## Expected Behavior
When the "Go back to form" button is clicked - the modal should disappear and the user should go back to editing case contact form

## How to Replicate
ex: 
1. - Log in as a volunteer 
2. - Click on "Cases" in the left sidebar menu.
3. - Click on a case
4. - Click "+ New Case Contact" button
5. Fill out the case contact form and click "Submit" button
6. Fill out the notes section
7. try clicking "Go Back to Form" button (it won't work)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by chahmedejaz** [comment]
Hey @bcastillo32  I'd like to pick this issue. I'm spiking on the fix for this.

**Comment by chahmedejaz** [comment]
A thing to add in repro steps, it's reproduced only when you fill out the Notes for the case contact form:
![image](https://github.com/rubyforgood/casa/assets/59338032/b0bdef2f-9bca-4858-8bd0-36161a8ecf68)

**Comment by moizafzal936** [comment]
Hey @bcastillo32! I'm a software engineer experienced in Ruby on Rails, and I'd love to work on this issue. It seems like a great fit for my skill set. Could I be assigned to this? Looking forward to contributing!
