### ISSUE TITLE
Re-route user back to correct page after Submitting Case Contact form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5154]
## Impacted User Types
 - volunteer

## Environment
web app

## Current Behavior
After submitting a case contact - the volunteer user is routed to the CASA Case details page and not the page where they entered the "+ New Case Contact" form.
[Please see quick explanation video here](https://www.loom.com/share/7cd822cbbc784b93b9f3cdf9dc3233b7?sid=158fb3ec-466f-4292-82de-867643d278db)

## Expected Behavior
Whatever Case Contact page the user entered the "+ New Case Contact" from - the user should be routed back to that original entry point. 
<br />
Please reach out if you have any questions. 

## How to Replicate
ex: 
1. - Log in as a Volunteer
2. - click on "Case Contacts" on the left navbar
3. - Click on "All"
4. - Click "+ New Case Contact"
5. - Submit the case contact form

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by bcastillo32** [comment]
For some reason - I cannot replicate this again

**Comment by moizafzal936** [comment]
Hi @bcastillo32! I noticed no one worked on this issue so, I fixed it and opened a PR. Hope so, it will fix the problem.
thanks!

**Comment by bcastillo32** [comment]
> Hi @bcastillo32! I noticed no one worked on this issue so, I fixed it and opened a PR. Hope so, it will fix the problem. thanks!

Awesome. Thank you so much!

**Comment by moizafzal936** [comment]
[Pr](https://github.com/rubyforgood/casa/pull/5169) is opened and need to be reviewed.
Thanks!
