### ISSUE TITLE
Make Double Language Add Error Message Full Width of Parent

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5178]
## What type(s) of user does this feature affect?
 - volunteers

## Description
Go to page `/users/edit`. Input some invalid values for name or email (such a blank inputs) and press update. You get an error.

Make the error shown below the width of the parent container with some margin.

## Screenshots of current behavior
![image](https://github.com/rubyforgood/casa/assets/8918762/f4d66328-6ffd-46dd-933a-41ffa9a4cfe3)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
@FireLemons can you assign it to me, please?

**Comment by jp524** [comment]
I would like to help with this issue

**Comment by mattpettenato** [comment]
I would love to work on this if possible!

**Comment by mattpettenato** [comment]
![image](https://github.com/rubyforgood/casa/assets/66044946/409370a1-5c12-41fc-94dc-60a4f9c26823)

@FireLemons @schoork does this look correct? Is there anything I should change?

**Comment by mattpettenato** [comment]
waiting for response

**Comment by schoork** [comment]
@mattpettenato Honestly not sure. But that does look right. Did you check mobile views, too?

**Comment by mattzollinhofer** [comment]
@mattpettenato seems like it's pretty close if it's not already there. Do you have a PR to take a look at?

**Comment by atbalaji** [comment]
Hi, I would love to work on this. I have some doubts. Shall we discuss here or at the slack channel?

**Comment by atbalaji** [comment]
Commenting for follow up. Is this issue still available to work on? @mattzollinhofer

**Comment by jamesh38** [comment]
Noticing some quietness on this issue. I have fixed this locally and can create a PR if it is assigned to me.

<img width="1248" alt="Screenshot 2024-07-29 at 10 46 04 PM" src="https://github.com/user-attachments/assets/767dfe08-1f47-467c-9581-b16e574ba08e">
<img width="1010" alt="Screenshot 2024-07-29 at 10 45 50 PM" src="https://github.com/user-attachments/assets/76c12c42-1b20-4bca-835d-4a76ba278819">
<img width="973" alt="Screenshot 2024-07-29 at 10 46 30 PM" src="https://github.com/user-attachments/assets/80a85664-b5ed-40ce-89b6-9b23a6872d33">
<img width="538" alt="Screenshot 2024-07-29 at 10 46 46 PM" src="https://github.com/user-attachments/assets/ed093442-1ac4-4f33-8a23-d6ab387068fb">

**Comment by elasticspoon** [comment]
@jamesh38 send it!

**Comment by jamesh38** [comment]
Sure thing how's this looking https://github.com/rubyforgood/casa/pull/5956
