### ISSUE TITLE
Create a "My Cases" dropdown for volunteers

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5180]
## What type(s) of user does this feature affect?
 - volunteers

## Description
As a volunteer - I would like a "My Cases Dropdown" that allows me to navigate directly to a case from the navbar. To achieve this functionality, please mimic the behavior of the "Case Contacts" dropdown and apply it to "My Cases" navbar item. [Here is a quick video explanation. ](https://www.loom.com/share/b976c3afdef447069d7be8e418cdbdba)

<img width="1437" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/8304d91a-5615-4305-9313-8571e059e28c">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by chahmedejaz** [comment]
Hey @bcastillo32 - I'd like to work on this feature. Can you please assign it to me? Thanks :)

**Comment by mattpettenato** [comment]
I'd love to work on this if possible!

**Comment by bcastillo32** [comment]
@mattpettenato I will assign it to you. @chahmedejaz Just trying to spread work around as best I can :) hope you understand. I think you still have a ticket open, yes?

**Comment by chahmedejaz** [comment]
Hey @bcastillo32 - I understand no issue. :)
Yes, the ticket is still open however, the development work for the feature has been completed now and here's the [update](https://github.com/rubyforgood/casa/issues/5174#issuecomment-1706346413) on it.
I'm just waiting for code owners to review the PR :)

**Comment by bcastillo32** [comment]
> Hey @bcastillo32 - I understand no issue. :) Yes, the ticket is still open however, the development work for the issue has been completed and here's the [update](https://github.com/rubyforgood/casa/issues/5174#issuecomment-1706346413) on it. I'm just waiting for code owners to review the PR :)

great! Thank you so much for your contribution. Please do comment on another ticket you would like to work on :)

**Comment by mattpettenato** [comment]
I am still working on this.

**Comment by bcastillo32** [comment]
hi @mattpettenato are you experiencing any blockers on this ticket?

**Comment by bcastillo32** [comment]
@chahmedejaz would you still like to jump on this one?

**Comment by chahmedejaz** [comment]
> @chahmedejaz would you still like to jump on this one? 

@bcastillo32, Sure 👍🏻

**Comment by Rafael-Martins** [comment]
Oh, sorry @chahmedejaz I went forward and implemented it, I did not saw that you was willing to do it!

**Comment by chahmedejaz** [comment]
> Oh, sorry @chahmedejaz I went forward and implemented it, I did not saw that you was willing to do it!

No worries, you may take this forward 👍🏻
