### ISSUE TITLE
Fix bullet n+1 issues in tests

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#519]
In `test.rb` uncomment the line `Bullet.raise = true` and run the tests `rake rspec`
You will see failures. 
Fix the failures (one PR per test is fine&good). 
When there are no failures, leave the line `Bullet.raise = true` not commented and make a PR for that also

**Comment by Garbar** [comment]
Gem Bullet added 13 days ago in "Applies standardrb fixes" by Aaron Hill

**Comment by compwron** [comment]
@Garbar good point! I think we need to start fixing bullet errors :) To see tests fail on bullet, you can add `Bullet.raise = true` to test.rb next to `Bullet.rails_logger = true`

Some problems won't be caught by our unit tests, so whoever works on this issue should also run the server locally and watch the logs for bullet warnings, then fix those (and add tests that exercise the functionality0

**Comment by Garbar** [comment]
I'm not sure about Bullet.raise = true. Because now after this 259 examples, 7 failures.
Perhaps after someone fixes all the current errors or adds them to exceptions, only then enable this function for tests.
So far, I've added a Bullet for tests and added a separate bullet log, so that it would be easier to track errors.

**Comment by compwron** [comment]
Sounds good! I think the next step on this issue is to fix each test one by one, and when they're all done, push a commit with `Bullet.raise = true` :)

**Comment by armahillo** [comment]
I'll take a peek at this one!

**Comment by compwron** [comment]
I'm going to unassign this one because I don't think it's being worked on right now- feel free to pick it up!
