### ISSUE TITLE
testing: remove duplication of login/signin roles in testing

### ISSUE THREAD

**Issue by lisale0** [rubyforgood/casa#52]
remove duplication of login/signin roles in testing

See  example below:
https://github.com/rubyforgood/casa/blob/b6026a7688d00a1df399a378670f65eaa98bb1f5/spec/features/admin_adds_new_case_spec.rb#L7

**Comment by eclectic-coding** [comment]
Would you like me to pick this one up? 
I did a cursory search through the `spec` folder indicated the `/admin_adds_new_case_spec.rb` is the only occurrence. The `login_as admin` needs to be removed. If the reverse is done, the test fails.

**Comment by compwron** [comment]
That would be great, please do! :)
