### ISSUE TITLE
Run rspec --profile and fix things it shows

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#520]
**What type of user is this for? volunteer/supervisor/admin/all**

**Description**

**Screenshots of current behavior, if any**

**Comment by Garbar** [comment]
I runned rspec --profile. And there was only one error, but it happened 45 times
```
ArgumentError:
  Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
```

  The error disappeared if I remove the line
`  require "bundler/setup" # Set up gems listed in the Gemfile.`
  from  ./config/boot.rb
  I'm just not sure if this is the right decision.

**Comment by compwron** [comment]
Hmm, I'm not sure either. @armahillo what do you think? 
> I runned rspec --profile. And there was only one error, but it happened 45 times
> ArgumentError:
>  Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
> The error disappeared if I remove the line
> require "bundler/setup" # Set up gems listed in the Gemfile.
> from ./config/boot.rb
> I'm just not sure if this is the right decision.

**Comment by jmkoni** [comment]
We are putting up a PR to move what was a system test to a unit test (save 2 sec!) but all these slow specs are system tests, so there's not much we can do to speed them up 😢
