### ISSUE TITLE
System Test for Password Reset

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5217]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 - all casa admins(optional)

## Description
 - Create a system test for resetting a password
 - put it in `spec/system/devise/passwords/`

## Screenshots of current behavior, if any
You can paste images on the clipboard here

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jp524** [comment]
I'd like to help with this issue
