### ISSUE TITLE
Remove "Assigned To" column from My Cases table (Volunteers only)

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5218]
## What type(s) of user does this feature affect?
 - volunteers

## Description
FOR VOLUNTEERS ONLY - remove the "Assigned To" column from My Cases table since Volunteers only see cases they are assigned to.

<img width="1437" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/db2587bc-65e8-46da-a88c-962c07014eee">

## How to Replicate
ex: 
1. - Log in as a volunteer

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
Added PR to solve an issue
