### ISSUE TITLE
Create 3 gifs of navigating staging as volunteer, supervisor, admin, and add them to the README

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#522]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
Create 3 gifs of navigating staging as volunteer, supervisor, admin, and add them to the README

**Comment by Zrrrpy** [comment]
let's hold on this until the new UI is built out

**Comment by acrosman** [comment]
I can do this one.

**Comment by acrosman** [comment]
That said, are there specific things you want captured, or just the basic difference in interface between the user types?

**Comment by Zrrrpy** [comment]
moved back to "Not ready to build" until some of the big new features are done.
