### ISSUE TITLE
Adjust Seeded Mileage Rate Range

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5221]
## Description
Make mileage rates generated by the seeder for test data between 0 and a dollar.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Br0k3nh4nd012** [comment]
@FireLemons Can I work on this?
