### ISSUE TITLE
Sort Mileage Rates by Effective Date

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5227]
## What type(s) of user does this feature affect?
 - admins

## Description
 - Sort the milage rates table by date
 - Newest at top
 - Add a test

Only admins can see the table

## Screenshots of current behavior, if any
![image](https://github.com/rubyforgood/casa/assets/8918762/97171e82-b46e-4452-b834-955b1d84fa2f)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
@FireLemons Can you assign this issue to me please?
