### ISSUE TITLE
Create Past Mileage Rates for Test Data

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5244]
## Description
Get the seeder to create mileage rates with effective dates in the past.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kassandraleyba** [comment]
I can help with this

**Comment by meamalpb** [comment]
I'd like to help with this!
