### ISSUE TITLE
Add Topic Column to Learning Hour Table

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5245]
## What type(s) of user does this feature affect?
 - volunteers

## Description
 - Add a learning hour topic column to the learning hour table for volunteers.
 - The learning hour topic feature can be toggled per org. If the feature is turned off, do not show the column.
 - Write tests

## Screenshots of current behavior, if any
You can paste images on the clipboard here

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @FireLemons I would like to work on this issue... Can you please assign it to me?

**Comment by sarvaiyanidhi** [comment]
Hi @FireLemons As it was very small change so I went ahead and implemented changes. Have opened PR for the same. Let me know if you need any changes. Thanks
