### ISSUE TITLE
Allow Supervisors and Admins to See Learning Hours

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5246]
## What type(s) of user does this feature affect?
 - supervisors
 - admins

## Description
 - Allow supervisors and admins to see a table of volunteers' learning hours.
 You can repurpose this view for Supervisors and Admins
<img width="1906" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/30e991a1-1149-4f02-bb2a-d31317c46cea">
<br></br>
- Add the "Learning Hours" list item to left navbar for supervisors and admins 
<img width="145" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/7852bc60-3a7b-423c-93ca-78db4fc0eaa4">
<br></br>
 - The table should have columns: volunteer name with link to volunteer, Time Completed (this is sum of all "Time Spent" for a volunteer)
 - The table - use https://datatables.net/
 - Admins should be able to see all volunteers' learning hours on the table
 - Supervisors should be able to see only the learning hours of volunteers assigned to them
 - Write tests

See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
Can you please assign this issue to me, @FireLemons ?

**Comment by bcastillo32** [comment]
I need to reach out to CASA leadership to see what info would be most helpful to see on this table - we will also want to use the same type of table being used through out the app to keep design and feel of the app consistent

**Comment by bcastillo32** [comment]
> Can you please assign this issue to me, @FireLemons ?

Hi @SajjadAhmad14 Once I get some clarification from CASA leadership regarding what info would be most helpful on its view  I will assign this to you.

**Comment by SajjadAhmad14** [comment]
Thank you @bcastillo32

**Comment by sarvaiyanidhi** [comment]
Hi.. I would like to take up this issue if it is still open and @SajjadAhmad14 is not taking it up as he has commented earlier. Thanks

**Comment by bcastillo32** [comment]
> Hi.. I would like to take up this issue if it is still open and @SajjadAhmad14 is not taking it up as he has commented earlier. Thanks

Thank you for grabbing this! Please let us know if you have any questions or need further clarification :)
