### ISSUE TITLE
Relocate "Banners" tab on Navbar

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5249]
## Impacted User Types
 - supervisors
 - admins

## Environment
web app

## Current Behavior
Currently, the "Banners" tab is nested in the "Group Actions" navbar dropdown.
<img width="247" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/081f72c2-d45c-40b4-95c3-590f0e029b53">
<img width="250" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/0f1eb8f0-a5d3-4538-8dd8-ae31f445c597">

## Desired Behavior
In an effort to make the "Banners" tab easier to locate for Supervisors and Admins, please pull the "Banners" tab out of the "Group Actions" navbar dropdown and put it above "Group Actions". 

## How to Replicate
ex: 
1. - Log in as an admin or supervisor.
2. - Click on "Group Actions" in the left sidebar menu.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users except Admin: 12345678  
password for Admin: 123456789

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
Hi @bcastillo32, I can work on this one before issue #5246 is ready to build. Thanks!

**Comment by meamalpb** [comment]
Hi @bcastillo32 , I'd like to help with this issue if possible!
