### ISSUE TITLE
Update nodejs for the project to an LTS version 16 or higher

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5259]
**Description**
One of dependabot's pull requests cannot be merged because it relies on version 16 or higher

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by aakashdeepsil** [comment]
Hi
I want to take on this issue. 
Also, the above link isn't allowing me to join the Slack channel. Please provide a working link.

**Comment by FireLemons** [comment]
Not needed
