### ISSUE TITLE
Responsive Support For Volunteer and Casa Cases table

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5261]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Somewhere between desktop and mobile width(ipad size), the [datatables](https://datatables.net/)' pagination controls display vertically.
Make it so the controls display horizontally when the screen is this size.

## Screenshots of current behavior, if any
![image](https://github.com/rubyforgood/casa/assets/8918762/b7d765ab-90f0-4e71-8703-6e82686e5a60)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
Hi @FireLemons! Can you please assign this issue to me?

**Comment by SajjadAhmad14** [comment]
Hi @FireLemons! Can you please assign this issue to me?

**Comment by SajjadAhmad14** [comment]
Yes working on it yet.
