### ISSUE TITLE
Remove the “+ Highlight” button from the “Enter Notes” field

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5285]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 

## Description
On the "New Case Contact" form, please remove the "+ Highlight" button from the "Enter Notes" section.
<br></br>
- Log in as volunteer
- Click "Case Contacts" on the left navbar
- Cick "All"
- Click "+ New Case Contact"
- Scroll down to "Enter Notes" section

## Screenshots of current behavior, if any
<img width="1430" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/fcd4230e-7674-4bf0-ad37-0391a73208ab">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jp524** [comment]
I'd like to work on this if possible!
