### ISSUE TITLE
Bug: "Youth's Date in Care" being deleted when new case is created

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5291]
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Environment
desktop

## Current Behavior
When a new case is created, "Youth's Date in Care" entered is deleted.
<br></br>
Before Clicking "+Create CASA Case" (submitting form)
<img width="280" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/fa75a9db-fa99-4348-9cef-79a4806ee7c4">
<br></br>
After - "Edit Case Details"
<img width="709" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/1ef7297f-a490-4ba5-bf6e-c8c431624138">

## Expected Behavior
When a New CASA Case is created, all info submitted is saved
## How to Replicate
ex: 
1. Log in as an admin.
2. Click on "Cases" in the left sidebar menu.
3. Click "+New Case"
4. Fill out Form details including "Youth's Date in Care"
5. Submit form - click "+Create CASA Case"
6. Click "Edit Case Details" and notice "Youth's Date in Care" is missing

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mattzollinhofer** [comment]
I can take a look at this issue.

**Comment by mattzollinhofer** [comment]
After an initial look, it appears that `date_in_care` is [not part of permitted params](https://github.com/rubyforgood/casa/blob/main/app/controllers/casa_cases_controller.rb#L151) and so the date is not making its way into the `CasaCase` creation.

**Comment by schoork** [comment]
@mattzollinhofer Can you start with an initially failing test and then make the changes to fix it?

**Comment by mattzollinhofer** [comment]
> @mattzollinhofer Can you start with an initially failing test and then make the changes to fix it?

Ha, sorry -- I was just taking notes while I wasn't assigned to the issue. I'll certainly get specs around this and get an PR out.
