### ISSUE TITLE
Bug: "Assign New Volunteer" defaults to first name on picklist for new cases

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5292]
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Environment
dekstop

## Current Behavior
When editing a new case to "Assign a New Volunteer" for the first time, the drop-down is defaulted to the first name on the list. 
<img width="1170" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/bd2156f1-ac22-4999-951b-6a3be3d84282">

## Expected Behavior
For new cases that have never had a volunteer assigned, the drop-down should default to a "null" picklist item. It can be a blank a string but if you have a different suggestion, please let @bcastillo32 know. 

## How to Replicate
ex: 
1. Log in as an admin.
2. Click on "Cases" in the left sidebar menu.
3. Click "+New Case"
4. Fill out Form details
5. Submit form - click "+Create CASA Case"
6. Click "Edit Case Details" and notice "Assign New Volunteer" has defaulted to the first list item on the picklist

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @bcastillo32,

I was thinking instead of showing nil value, can we show text as "Please Select Volunteer" with value as nil so it prompts error if user don't select any volunteer as shown in below screenshot

![volunteer-select](https://github.com/rubyforgood/casa/assets/514363/05d6f56f-d30a-4aea-bcd1-1bfcd29956ef)

If it is good I can submit PR as it is very small fix.

Thanks

**Comment by bcastillo32** [comment]
> Hi @bcastillo32,
> 
> I was thinking instead of showing nil value, can we show text as "Please Select Volunteer" with value as nil so it prompts error if user don't select any volunteer as shown in below screenshot
> 
> ![volunteer-select](https://user-images.githubusercontent.com/514363/276992036-05d6f56f-d30a-4aea-bcd1-1bfcd29956ef.png)
> 
> If it is good I can submit PR as it is very small fix.
> 
> Thanks

Yes that works! Thank you!
