### ISSUE TITLE
update "2. Select All Contact Types" section on Case Contact Form with Dropdown menu and new styling/copy

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5309]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File/Prototype](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Steps to view a Figma prototype:**

1. Access the provided link in your web browser.
2. Press the play button located at the top right of the browser window.
3. (Optional) Create a free account and log in. This grants access to view comments left on the file.
4. (Optional) If the prototype extends beyond your screen width, click the "options" dropdown at the top right of the screen and select "fit width."
5. Explore the prototype by clicking different areas to discover interactive elements.

**Styling Chart**
<img width="638" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/93c599bd-513d-4d76-be66-53f418767827">

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

## Acceptance Criteria
1. "2. Select All Contact Types" section on Case Contact Form should be updated with proper styling and copy to match that of the Figma file referenced above. Please also use the styling chart
2. Dropdown menu should include all available contact types (ie, Attorney, Foster Parent, etc.)
3. Dropdown menu should be scrollable
4. One or many contact types should be able to be selected
5. A label/pill for each selected contact type should be displayed
6. Selected contacts should be removed from selected if users select the “X” in the pill or deselect the check mark in the dropdown
7. A user should be able to fuzzy search based on “Contact Type Groups” (see “Editing CASA Organization page in admin portal), ie searching “Family” would still display “Grandparent”

**Snippet from Figma file/Prototype**
https://www.loom.com/share/c48d5b321bcb42bba2f116afcb510c41?sid=d59c0bfb-8ff7-4f89-9e5c-58bb314a655f

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by SajjadAhmad14** [comment]
Hi @bcastillo32 I would like to work on this issue if you can please assign it to me! Thanks!

**Comment by bcastillo32** [comment]
Hi @SajjadAhmad14 thank you for your help here. Please reach out to myself or @mallorypricedesigns if you have any questions.

**Comment by bcastillo32** [comment]
Hi @SajjadAhmad14 are you still working on this? Please let us know when you can :)

**Comment by SajjadAhmad14** [comment]
Hi @bcastillo32. I could not be able to work on it. But I will do it submit a PR by next week! Thanks!

**Comment by SajjadAhmad14** [comment]
I need to know that should this drop down be implemented on new casa case conatct form? I am asking this because there is no information where should the drop down go. Thanks!

**Comment by bcastillo32** [comment]
> @bcastillo32 I need to know that should this drop down be implemented on new casa case conatct form? I am asking this because there is no information where should the drop down go. Thanks!

Hi @SajjadAhmad14 thank you for your help here. I have updated the ticket to help clarify the goal and acceptance criteria. Please let me know if you have any questions! :)

**Comment by bcastillo32** [comment]
also @SajjadAhmad14 I am waiting on a mock-up for how the pills should be displayed - this is related to #5 in the acceptance criteria

**Comment by bcastillo32** [comment]
@SajjadAhmad14 I have updated the ticket. Let me know if you have any questions :)

**Comment by bcastillo32** [comment]
Hi @SajjadAhmad14 are you still working on this? :)

**Comment by SajjadAhmad14** [comment]
Hi @bcastillo32 I am just left with search by contact type group functionlity.

**Comment by bcastillo32** [comment]
> Hi @bcastillo32 I am just left with search by contact type group functionlity.

Hi @SajjadAhmad14 - are you saying all that you have left if the search portion for the component?

**Comment by SajjadAhmad14** [comment]
Hi @bcastillo32 Can you please guide me for the UI of search functionality we want to implement which is specified in point 7 of acceptance criteria. A loom video of the example would be best.

7: A user should be able to fuzzy search based on “Contact Type Groups” (see “Editing CASA Organization page in admin portal), ie searching “Family” would still display “Grandparent”
Snippet from Figma file/Prototype

**Comment by bcastillo32** [comment]
> Hi @bcastillo32 Can you please guide me for the UI of search functionality we want to implement which is specified in point 7 of acceptance criteria. A loom video of the example would be best.
> 
> 7: A user should be able to fuzzy search based on “Contact Type Groups” (see “Editing CASA Organization page in admin portal), ie searching “Family” would still display “Grandparent” Snippet from Figma file/Prototype

Hi @SajjadAhmad14 Sure thing I will have some feedback for you shortly. I am just clarifying with some folks on my end before doing so.

**Comment by bcastillo32** [comment]
Hi @SajjadAhmad14 Here is a quick video explaining the fuzzy search requirement:
https://www.loom.com/share/8775a5f3f44b4a758e37d1f66821ec7b?sid=2c08ab61-3c9c-46ad-a89d-2d386cefa703

**Comment by bcastillo32** [comment]
> Hi @SajjadAhmad14 Here is a quick video explaining the fuzzy search requirement: https://www.loom.com/share/8775a5f3f44b4a758e37d1f66821ec7b?sid=2c08ab61-3c9c-46ad-a89d-2d386cefa703

Hi @SajjadAhmad14 was this helpful?

**Comment by SajjadAhmad14** [comment]
> > Hi @SajjadAhmad14 Here is a quick video explaining the fuzzy search requirement: https://www.loom.com/share/8775a5f3f44b4a758e37d1f66821ec7b?sid=2c08ab61-3c9c-46ad-a89d-2d386cefa703
> 
> Hi @SajjadAhmad14 was this helpful?

Yeah it did. Thanks!

**Comment by bcastillo32** [comment]
hi @SajjadAhmad14 how is it coming with this ticket? Are you still actively working on this?

**Comment by bcastillo32** [comment]
> hi @SajjadAhmad14 how is it coming with this ticket? Are you still actively working on this?

Hi @SajjadAhmad14 If you can let me know but the end of this week that would be great. If not we might have to re-assign as this is a high-priority item. Please let me know.
