### ISSUE TITLE
add mysql slow queries log config and have them post somewhere (bugsnag? slack? papertrail?)

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#531]

**Comment by compwron** [comment]
duplicate

**Comment by duaimei** [comment]
@leesharma  and I have looked into this issue and there are three options:
1) manual logging
It involves using ActiveSupport and a slack_notification gem
https://www.westagilelabs.com/blog/log-your-slow-queries-in-slack-using-rails/

2) bug snag
There's not a lot of documentation on how to achieve this, but we believe that it would be something like a custom breadcrumb/filter. 

3) NewRelic/Scout
It creates a new dependency in the application, but we get dashboards as well as slack integrations "for free" (no, to little customization). 

Scout only keeps the dashboard information for 24 hours.

https://newrelic.com/products/application-monitoring/features
https://scoutapm.com/ruby-monitoring
These are generally as easy as installing the gem, and configuring the API key.

**Comment by Zrrrpy** [comment]
reassigning to Linda because she has access to everything (including Skylight which we might use for this)
