### ISSUE TITLE
alerts supervisors to upcoming volunteer birthdays

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#5316]
Hey, We would LOVE to have a function that alerts supervisors to upcoming volunteer birthdays! We are currently using a calendar to track it but its sloppy with old volunteers vs making sure new volunteers are added.

Jocie

Jocelyn Hagan, LCSW-C (she/her)
Supervisor of Volunteers
Voices for Children, Inc.

## What type(s) of user does this feature affect?
 - volunteers?
 - supervisors?
 - admins?
 - all casa admins?

## Screenshots of current behavior, if any
You can paste images on the clipboard here

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by elasticspoon** [comment]
https://github.com/rubyforgood/casa/pull/5328
