### ISSUE TITLE
Volunteer dashboard redesign

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#532]
[_Please reference the mockup here when reviewing Improvements and additions to the UI below._](https://udw1g1.axshare.com/#id=8zvctq&p=volunteer_dashboard&c=1)

Filter issues by the labels "Design" and "Volunteer" to see all work relating to this epic.

**Context**
Now that the volunteer dashboard serves its core functionality in the MVP build, we are ready to move into phase two and improve design and user experience. 

**How to access**
<a href="https://casa-qa.herokuapp.com/">Log in to QA</a> as a volunteer using the following credentials:
Email: volunteer1@example.com
password: 123456

**Improvements and additions to the UI**

- [ ] #696 new table header with CINA details (Replaces Edit CASA Case page)
- [ ] #735 tabs separate case contacts for volunteers assigned to more than one case

_Court date_
- [ ] Add court date to banner (or somewhere better)
- [ ] add court report due date (20 business days before court date)
- [ ] visual indicator that shows court date is approaching (optional)
- [ ] visual indicator that court date has passed
- [ ] volunteer can download court report template
- [ ]  ^^ doing so triggers notification to supervisor 
- [ ] once volunteer has submitted court report to supervisor (off platform), supervisor manually adds completion badge to volunteer's court date
- [ ] ^^ this triggers completion badge on volunteer dashboard next to court date (or something better than that)

_Dashboard case contact view_
- [ ] display contact_type categories, with the ability for user to click and display each selected in that category.
- [ ] display case_contacts associated with different cases in individual tabs (see mock up below)
- [ ] by default, display the last 30 case_contacts when user signs in (can filter by date to show wider range of case_contacts)

<img width="1131" alt="Screen Shot 2020-09-06 at 4 23 42 PM" src="https://user-images.githubusercontent.com/62810851/92334908-0a0a1a80-f047-11ea-8523-4f692903b10c.png">

_Per Case Contact_
- [ ] max 4 lines of notes should display (less on mobile) - "Read more" to expand and show remaining lines.

_Follow Ups_
- [ ] Volunteer/Supervisor/Admin can flag a case contact for follow up
- [ ] After volunteer adds first followup to case contact, icon (or something better) changes to reflect that. 
- [ ] Follow up case contacts should relate to case contact where follow up originated.
- [ ] Supervisor should be able to mark a follow up as complete. Something should change visually when this happens. 
- [ ] Followup count in CINA banner should update to reflect incomplete followups (any stage other than complete)
- [ ] Follow up count should not display when 0
- [ ] Create `follow_up` table for all the stuff that will be associated with followups
- [ ] Followups can not be edited or deleted by volunteers.
- [ ] Followups can only be edited or deleted by supervisors and admins. 
- [ ] Add instructional text above open field reading: To honor confidentiality, remember to refer to individuals as roles instead of names.
- [ ] When do you need to do this by? with date field >>> This should inform notification hierarchy for supervisors

_Contact Types_
- [ ] Ann Marie will email complete list of contact types
- [ ] Add contact_type categories to db
- [ ] Add contact_type categories to reports
- [ ] Look into options for long list of contact_types on mobile

_Miles driven / reimbursements_
- [ ] add question: Did you drive? (Yes/No)
- [ ] Yes triggers next two questions to display: miles driven and reimbursements
- [ ] Update question to: How many miles did you drive?
- [ ] Do you need a reimbursement? Should default to "no"

_Contact Made_
- [ ] Change question to: Was contact made?
- [ ] Change "What happened?" to "Notes"

_Filter_
- [ ] Volunteers should be able to filter by: 
       - date ranges 
       - contact type
      - contact made (yes/no)
      - contact medium
      - open/pending/closed followup
      - driving yes/no 
      - reimbursement yes/no
- [ ] Volunteers can sort by ascending and descending dates ^^ + all those above.

**Comment by Zrrrpy** [comment]
We discussed:

- last case contact made
- case contacts made in the past 30 days
- member of CASA case's team who hasn't been contacted for longest duration of time

**Comment by Zrrrpy** [comment]
snapshot should only pull from `case_contacts` created by the volunteer (not the supervisor)

**Comment by Zrrrpy** [comment]
high character restriction (if any) on notes – maybe a "read more" option for longer notes displaying in the main dashboard.

**Comment by Zrrrpy** [comment]
Ann Marie would prefer for lists to be longer and more specific vs other. 

Placement: 
Foster Parent
Independent Living Placement
Relative Placement

**Comment by Zrrrpy** [comment]
Ensure entire text next to check box is clickable under _Who did you contact?_

**Comment by Zrrrpy** [comment]
add white div above CINA info banner

**Comment by Zrrrpy** [comment]
explore how to mark a CASA case as transition aged youth (maybe click the caterpillar and it turns into butterfly?)

Other notes from chat:
We could add “days/weeks/etc ago” to the date on case contacts if we want it 
From Linda to Everyone: (11:56 AM)

 If it fits … and also could make “duration” be one clock icon per hour spent if we want more visual representation but that might be too confusing Follow-ups seem cool :) 
From Polly (she/her) to Everyone: (11:57 AM)

 I think that’s a great idea, while you and zoe stepped out we talked about having a button that toggles the “before the last court report” contacts on and off and also filters so we could look for certain types of contacts when looking at history

**Comment by metamoni** [comment]
I'd like to work on this piece and I think it makes sense for one person to start by setting up the table, before we can break it down into smaller tasks. I grabbed issue number #696 for starters. @jmkoni, @compwron, @littleforest what do you think would be the best way to go around this? Do we use any libraries to add feature flags? Or should I work in a hidden "test" route and view, and then replace the old code once the table is finished?

**Comment by compwron** [comment]
We don't currently use feature flags. Either of those solutions are fine with me- test route vs adding feature flags.

**Comment by metamoni** [comment]
I've done some of the work for the header and table body on [this](https://github.com/rubyforgood/casa/tree/696-volunteer-table-header) branch, but I am unable to continue working on this at the moment. The table is set up on a test path, which you can get to by going to Case Contacts, selecting an entry to edit, and replacing `/edit` in the url with `/table`. For example `http://localhost:3000/case_contacts/785/table`.

What's left to do: add interactivity (update case contact details on page and in header when user selects another case) and mobile view.
