### ISSUE TITLE
Update case contact page header

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5324]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Styling Chart**
<img width="638" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/93c599bd-513d-4d76-be66-53f418767827">

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

## Acceptance Criteria
- Page header should read "Record new case contact"
- Styling should match that of the styling card referenced above

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jp524** [comment]
I would like to help with this issue!

**Comment by bcastillo32** [comment]
> I would like to help with this issue!

Thank you! Please reach out if you have any questions! :)

**Comment by schoork** [comment]
@jp524 View Components would be really helpful here. Could be used site-wide eventually.

**Comment by jp524** [comment]
> @jp524 View Components would be really helpful here. Could be used site-wide eventually.

I can definitely implement them! I'm planning to first implement the style/form updates, and making the switch to View Components later. Does that work for you?

**Comment by chahmedejaz** [comment]
Hey @bcastillo32 - I'd love to work on this, can you please assign it to me? Thanks. :)

**Comment by bcastillo32** [comment]
> Hey @bcastillo32 - I'd love to work on this, can you please assign it to me? Thanks. :)

Hi there - we are thinking about splitting this ticket up a bit since it is a bit of a “heavy” ticket unless you feel comfortable tackling it yourself. Please let me know what you think. :)

**Comment by chahmedejaz** [comment]
> > Hey @bcastillo32 - I'd love to work on this, can you please assign it to me? Thanks. :)
> 
> Hi there - we are thinking about splitting this ticket up a bit since it is a bit of a “heavy” ticket unless you feel comfortable tackling it yourself. Please let me know what you think. :)

It'll take time but I can take care of the whole ticket. If we are very short on time, then it would be great to break it down. :)

**Comment by bcastillo32** [comment]
> > > Hey @bcastillo32 - I'd love to work on this, can you please assign it to me? Thanks. :)
> > 
> > 
> > Hi there - we are thinking about splitting this ticket up a bit since it is a bit of a “heavy” ticket unless you feel comfortable tackling it yourself. Please let me know what you think. :)
> 
> It'll take time but I can take care of the whole ticket. If we are very short on time, then it would be great to break it down. :)

I think I will split it up and have you and @jp524 split the work if that sounds good? :) give me some time to split the ticket. I should have it done by tomorrow. I just have to finish up work for my day job first :)

**Comment by chahmedejaz** [comment]
Sounds good. Please let us know when the tickets are ready. Thanks :)

**Comment by bcastillo32** [comment]
> Sounds good. Please let us know when the tickets are ready. Thanks :)

I will have them ready today :)

**Comment by bcastillo32** [comment]
@jp524 or @chahmedejaz either of of you can grab this - I am working on releasing the other tickets. Now that I have taken a look and implemented some feedback from @jp524, there will be more bite-size tickets to come :)

**Comment by chahmedejaz** [comment]
@bcastillo32 - I'd like to work on this one. However, If @jp524 wants to work on this as well, then no worries, you may assign any of other tickets to me. Thanks :)

**Comment by jp524** [comment]
All yours @chahmedejaz
