### ISSUE TITLE
Connect Prod Bugsnag account to Slack

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#533]
**Description**
Bugsnag notifications from prod should post to the #casa-bots channel in Slack.

@compwron @seanmarcia @pollygee you are the humans who have access to this account – dibs for whoever gets to it first!

**Comment by seanmarcia** [comment]
This is done! If someone can force an error we should see it.

**Comment by compwron** [comment]
I forced a prod error just now (by assigning empty volunteer to a supervisor)
it worked! https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1599329470046100
I want to move it to #casa-prod channel eventually but it's not urgent
