### ISSUE TITLE
Upgrade datatables from 1.13.6 to 1.13.7

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5337]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Upgrade the datatables javascript dependency from 1.13.6 to 1.13.7. The upgrade is currently incompatible with the app.  
The system tests should be working unlike the checks in the dependabot pull request.

See: https://github.com/rubyforgood/casa/pull/5332

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by crespire** [comment]
Could this be an opportunity to maybe re-consider the datatables usage and swap it to something StimulusJS based? Or are we using jQuery elsewhere in the app that would make this switch not necessary?

**Comment by fchagasjr** [comment]
Can I be assigned to that?
