### ISSUE TITLE
Link the Help Site in app

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5339]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Please link the help site in the user dropdown in between "Messages" and "Sign Out". 
Link for help site: https://thunder-flower-8c2.notion.site/Casa-Volunteer-Tracking-App-HelpSite-3b95705e80c742ffa729ccce7beeabfa

<img width="255" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/201f6047-baa4-4e18-bd1b-245fda14a61a">

- Please use the "question-circle" icon [from Pain Admin.](https://demo.plainadmin.com/icons) 
- The List item should be titled "Help"

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @bcastillo32 Can you please assign this to me?
