### ISSUE TITLE
Add Previews for the Fund Request Mailer

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5344]
## Description
The [fund request mailer](https://github.com/rubyforgood/casa/blob/main/app/mailers/fund_request_mailer.rb) does not have a preview. 
Create a preview for the mailer.

## Screenshots of current behavior, if any
![image](https://github.com/rubyforgood/casa/assets/8918762/316dbff9-cf7f-4447-81d7-57ffc8564b41)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi.. I will take up this issue. Thanks
