### ISSUE TITLE
Update "3. Enter Contact Details" section on Case contact form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5348]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Styling Chart**
<img width="638" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/93c599bd-513d-4d76-be66-53f418767827">

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

## Acceptance Criteria
- card header should read "3. Record contact details" - see Figma file and styling chart referenced above
- An asterisk should be placed at the end of the text - see Figma file and styling chart referenced above
- each section of card should be updated to match Figma File - see Figma File and styling chart referenced above
- Card text should use correct styling - see Figma file and styling chart referenced above

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ahasunos** [comment]
Can I give a shot at this?

**Comment by ahasunos** [comment]
Can I give a shot at this? @bcastillo32

**Comment by ahasunos** [comment]
And if I understand the a/c correctly, it is to improve the below card:
<img width="1428" alt="image" src="https://github.com/rubyforgood/casa/assets/98935583/e0091210-c9f3-44b4-b273-10da7d667ee8">

to match the card as shown in the figma:
<img width="896" alt="image" src="https://github.com/rubyforgood/casa/assets/98935583/8e4048a4-5410-4575-8ae3-0e4487f2660f">

**Comment by chahmedejaz** [comment]
Hey @ahasunos - Just a heads up, if you are gonna work on this issue then please know that most of the form component style changes (`bold <> light labels` and `asterisk on next line <> same line`) will be done automatically when the following PR gets merged
https://github.com/rubyforgood/casa/pull/5366/files
You'd just need to take off the placeholders and other HTML tag-related changes for this issue. Thanks :)

**Comment by bcastillo32** [comment]
Hi @ahasunos yes that is correct. We want to update the card to match that of the Figma file. And thank you @chahmedejaz for the help!

**Comment by ahasunos** [comment]
Thanks @chahmedejaz and @bcastillo32 
Given the styling changes I would get from the PR 5366, I will go ahead and make the html related changes.

**Comment by ahasunos** [comment]
still working

**Comment by bcastillo32** [comment]
@chahmedejaz this was never completed - do you want to work on this?

**Comment by chahmedejaz** [comment]
> do you want to work on this?

Sure @bcastillo32, I'd love to work on it. You may assign it to me. Thanks.

**Comment by bcastillo32** [comment]
> > do you want to work on this?
> 
> Sure @bcastillo32, I'd love to work on it. You may assign it to me. Thanks.

Thanks a lot! Assigning you now :)

**Comment by JoshDevHub** [comment]
@bcastillo32 Hi, could I be assigned to work on this?

**Comment by bcastillo32** [comment]
> @bcastillo32 Hi, could I be assigned to work on this?

Hi @JoshDevHub yes! Assigning you now!

**Comment by JoshDevHub** [comment]
> This issue has been inactive for 246 hours (10.25 days) and will be unassigned after 114 more hours (4.75 days). If you have questions, please
> 
> If you are still working on this, comment here to tell the bot to give you more time

Still working on this!
