### ISSUE TITLE
Check date in volunteer birthday reminder task

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5350]
## What type(s) of user does this feature affect?
 - volunteers

## Description
[This rake task](https://github.com/rubyforgood/casa/blob/main/lib/tasks/volunteer_birthday_reminder.rake) was designed with the idea that it would be ran on the 15th of each month. However heroku's free job scheduler has a maximum interval of daily. We would like to run the task daily but only have it execute if the day of the month is 15.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi.. Please assign it me.. I will work on this issue. Thanks

**Comment by meamalpb** [comment]
I would like to work on this
