### ISSUE TITLE
Bug: Volunteer Address not showing for Supervisors and Admins

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5362]
## Impacted User Types
 - supervisors
 - admins

## Environment
staging and Prod

## Current Behavior
Volunteer Address not showing for Supervisors and Admins

## How to Replicate Bug
ex: 
1. Log in as an admin or supervisor 
2. Click on on a volunteers name
3. notice Address field is missing

<img width="998" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/330767d7-5f36-46ca-af14-cf6093771e80">

## Expected Behavior
Volunteer Address be visible for Supervisors and Admins when looking at Volunteer details

## How to Expected Behavior
ex: 
1. Log in as a volunteer
2. Click on Volunteer Name menu
<img width="258" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/61da4897-51fa-431e-bc04-5a9488d90dcc">

3. Click "Edit Profile"
4. Notice the Address field is showing - this should be visible for Supervisors and Admins.

<img width="678" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/8d6f2b8a-e1ba-4d00-8dd8-709fb78c7b77">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by chahmedejaz** [comment]
I'm looking into this, @bcastillo32

**Comment by chahmedejaz** [comment]
Hey @bcastillo32 -  I did a bit of spike on this and here are my findings:

- This is not a bug but a missing functionality.
- For Admins and Supervisors we only show the Mailing Address field and not the Address Field
- Please let me know how do we want to proceed.
- Should we move forward with this as a new feature as per the given Expected Behavior?

**Comment by schoork** [comment]
Maybe if mailing address is blank it should show the address?

**Comment by chahmedejaz** [comment]
> Maybe if mailing address is blank it should show the address?

- Hmm...Actually it's the edit page and I'm not sure if it'd make sense to show the address fields conditionally. 
- It would create some unexpected behaviors i.e. sometimes the address field is displayed and other times it's not
- I'm not sure it'd be a good UX.

- I believe we need to decide which volunteer address fields admin/supervisors should have access to update and then display those fields in the edit form as well.

Please let me know if you have any follow-ups. Thanks.

**Comment by schoork** [comment]
It sounds like they need a list of addresses to mail things to. How about a page to display these?

**Comment by chahmedejaz** [comment]
> It sounds like they need a list of addresses to mail things to. How about a page to display these?

We can display these on the Edit Volunteer Page as well. We just need to descide whether the admins/supervisors should be able to update the volunteer address? or they should only be able to edit the mailing address. 😅

**Comment by bcastillo32** [comment]
> > It sounds like they need a list of addresses to mail things to. How about a page to display these?
> 
> We can display all addresses on the Edit Volunteer Page as well. We just need to descide whether the admins/supervisors should be able to update the volunteer address? or they should only be able to edit the mailing address.

Hi there! Thank you for all your hard work and feedback. For now just please make sure the address field shows for supervisors and admins and is able to be edited in the volunteer details. We can scope out different views later which im happy to include you in.

**Comment by chahmedejaz** [comment]
> > > It sounds like they need a list of addresses to mail things to. How about a page to display these?
> > 
> > 
> > We can display all addresses on the Edit Volunteer Page as well. We just need to descide whether the admins/supervisors should be able to update the volunteer address? or they should only be able to edit the mailing address.
> 
> Hi there! Thank you for all your hard work and feedback. For now just please make sure the address field shows for supervisors and admins and is able to be edited in the volunteer details. We can scope out different views later which im happy to include you in.

- @bcastillo32 - Sorry for the misunderstanding on my part here.
- I just realized it's the discrepancy in the labeling of the fields. 
- For volunteer view of the Edit Page, we display the `Address` label for the volunteer address field
- For the admin/supervisor view of the Edit Page, we display the `Mailing Address` label for the same field
- It's the same field with different labels for different views.
- Should we change the admin/supervisor view's address field label to match that of the volunteer's view or do we just need to convey this knowledge to the stakeholders? Thanks.
- Again really sorry for the misunderstanding.

CC: @schoork

**Comment by bcastillo32** [comment]
> > > > It sounds like they need a list of addresses to mail things to. How about a page to display these?
> > > 
> > > 
> > > We can display all addresses on the Edit Volunteer Page as well. We just need to descide whether the admins/supervisors should be able to update the volunteer address? or they should only be able to edit the mailing address.
> > 
> > 
> > Hi there! Thank you for all your hard work and feedback. For now just please make sure the address field shows for supervisors and admins and is able to be edited in the volunteer details. We can scope out different views later which im happy to include you in.
> 
> * @bcastillo32 - Sorry for the misunderstanding on my part here.
> * I just realized it's the discrepancy in the labeling of the fields.
> * For volunteer view of the Edit Page, we display the `Address` label for the volunteer address field
> * For the admin/supervisor view of the Edit Page, we display the `Mailing Address` label for the same field
> * It's the same field with different labels for different views.
> * Should we change the admin/supervisor view's address field label to match that of the volunteer's view or do we just need to convey this knowledge to the stakeholders? Thanks.
> * Again really sorry for the misunderstanding.
> 
> CC: @schoork

Hi @chahmedejaz no need to apologize! This is part of development and we appreciate all your help and questions, truly! I think the best course of action would be to merely make the volunteer address info available to the supervisors/admins. They use that info to send out holiday cards and for quick reference. We can change labels later on a different ticket. Please let me know your thoughts! :)

**Comment by chahmedejaz** [comment]
> I think the best course of action would be to merely make the volunteer address info available to the supervisors/admins. They use that info to send out holiday cards and for quick reference. We can change labels later on a different ticket. Please let me know your thoughts! :)

Thanks @bcastillo32 :heart: 

I just submitted the PR to fix the discrepancy between the field names.

**Comment by chahmedejaz** [comment]
>  no need to apologize! This is part of development and we appreciate all your help and questions, truly! 

Thanks @bcastillo32 :heart: 

> I think the best course of action would be to merely make the volunteer address info available to the supervisors/admins. They use that info to send out holiday cards and for quick reference. We can change labels later on a different ticket. Please let me know your thoughts! :)

Sure, lets do that.
I just submitted the PR to fix the discrepancy between the field names.

**Comment by littleforest** [comment]
I think the issue is that the address only shows up if `current_organization.show_driving_reimbursement` is true, but the organizations that aren’t giving reimbursements still want the volunteer’s address for other reasons (like to mail holiday cards). So I think the fix is actually just to move the address field up to be underneath the Date of Birth field, and don’t wrap it in the `if current_organization.show_driving_reimbursement` conditional. I also think it’s better to just leave the label as “Mailing Address” than to change it to “Address” as it’s clear that it is the address to which they can receive mail.

**Comment by chahmedejaz** [comment]
> I think the issue is that the address only shows up if `current_organization.show_driving_reimbursement` is true, but the organizations that aren’t giving reimbursements still want the volunteer’s address for other reasons (like to mail holiday cards). So I think the fix is actually just to move the address field up to be underneath the Date of Birth field, and don’t wrap it in the `if current_organization.show_driving_reimbursement` conditional. I also think it’s better to just leave the label as “Mailing Address” than to change it to “Address” as it’s clear that it is the address to which they can receive mail.

sure, let me do that and submit the fix again. Thanks for the guide :star:
