### ISSUE TITLE
Learning Hours for the Seeder

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5370]
## Description
 - Add learning hours to the seeder
 - Make sure the seeder output shows how many learning hours have been created
 - Show proof your solution works
The seeder can be run with `rails db:reset`

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by cflannagan** [comment]
I'd like to tackle this

**Comment by cflannagan** [comment]
@FireLemons Do you have any particular wants/needs for the ticket? Ie: how many LearningHour records the new seeding logic will create, specific values, etc? Let me know and thanks!
