### ISSUE TITLE
DRY Learning Hours Form Partial

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5372]
## What type(s) of user does this feature affect?
 - volunteers?
 - admins?

## Description
In the learning hours views, the edit page references a partial "update_form" and the new page references a partial "form". For most other features the new and edit pages both reference the same partial called "form". "update_form" and "form" have very similar layouts. Combine the 2 forms back into a single form or explain why it can't / shouldn't be done.  
  
The learning hours view file structure compared to other features:
```
learning_hours
├──_confirm_note.html.erb
├── _form.html.erb
├── _update_form.html.erb
├── edit.html.erb
├── index.html.erb
├── new.html.erb
└── show.html.erb
```

```
judges
├── _form.html.erb
├── edit.html.erb
└── new.html.erb
```

```
other_duties
├── _form.html.erb
├── edit.html.erb
├── index.html.erb
└── new.html.erb
```

[About the DRY Principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
Added PR to address this issue
