### ISSUE TITLE
Bug: White text against white background

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5378]
When editing a volunteer / looking at the detailed volunteer page as an admin, if you scroll to the case assignment area, the active status indicators have white text. The background is also white making the text invisible.

 - Fix the color using classes from our css frameworks
 - Also fix the unassigned label
 - Prove your solution works

## Current Behavior
![image](https://github.com/rubyforgood/casa/assets/8918762/748d9741-b872-4c14-838a-f9257ecce1da)
![image](https://github.com/rubyforgood/casa/assets/8918762/24a5d96e-32eb-446c-b537-81c1d96ef843)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Daniel-Penaloza** [comment]
Hi please assign this to me :)
