### ISSUE TITLE
display start and end date of current & past volunteer assignments

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#538]
**Part of epics** #4 and #105 

**What type of user is this for? [admin/supervisor/volunteer/all]**
supervisors and admins

**Where does/should this occur?**
On Editing CASA Case pages where past volunteer assignments display, accessible by supervisors and admins.

**Description**
Two new columns should be added to the table that displays information about Assigned Volunteers on the Editing CASA Case page:
- Start Date
- End Date

The _Start Date_ column should display the creation date of this volunteer/case assignment, a.k.a. the date this volunteer was assigned to the case.

The _End Date_ column should display the termination date of this volunteer/case assignment, a.k.a. the date the volunteer was unassigned from the case.

**Comment by cliftonmcintosh** [comment]
I have a question about this requirement:

> The End Date column should display the termination date of this volunteer/case assignment, a.k.a. the date the volunteer was unassigned from the case

To the best of my knowledge, the date on which a volunteer was unassigned is not recorded. The closest approximation of that is the `case_assignments.updated_at` column, but that would only be true if the last update to a case assignment record happened to be to the `is_active` column. Practically, speaking, that's probably the only column that would ever change in a case assignment.

Is that what is wanted, to infer that the `updated_at` field on an inactive case assignment is the date on which the case was unassigned?

**Comment by cliftonmcintosh** [comment]
What is the expected format of the dates?

Where do the new columns go? Before the "actions" column? After the "actions" column? Somewhere else?

**Comment by cliftonmcintosh** [comment]
Here is a sample screenshot with the following characteristics:

The Start Date and End Date columns are place before the Actions column
The dates are formatted like "January 1, 2020"
The "updated at" column is presumed to be the date on which an assignment was deactivated when the "is_active" flag is false
When the assignment is active, the End Date column is empty

How does this compare to what is wanted?

![sample-start-end-dates](https://user-images.githubusercontent.com/3824492/90345692-7cf41880-dfe8-11ea-971e-0c57e1c065f3.png)

**Comment by compwron** [comment]
I like the screenshot! I'm happy to merge this change. Someday we will also want to add a `deactivated_at` column and/or use the existing `User.paper_trail` functionality to be more sure about this date logic.
