### ISSUE TITLE
Duration inputs on forms require the user to input both hours and minutes

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5383]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

### Problem
Duration sections like this:
![image](https://github.com/rubyforgood/casa/assets/8918762/d34c237c-3509-49cf-b220-c39de48d1489)

require the user to type a number for both hours and minutes. So if the activity lasts exactly an hour the user has to type a 0 for minutes to be able to submit the form.  

Removing the `required` HTML attribute reveals the controller requires the field also.
![image](https://github.com/rubyforgood/casa/assets/8918762/24a484ed-f07d-4868-9b08-c07f102f1a04)

### Solution
Remove the `required` attributes from the form.
If the input is blank, make the controller assume the value is 0.
Update / write a test

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by schoork** [comment]
Could also initially set the value as 0. I'd probably do this in the view. 

`value: form.object.new_record? ? 0 : VALUE`

**Comment by fchagasjr** [comment]
Can I be assigned to this?

**Comment by Br0k3nh4nd012** [comment]
@FireLemons Can I work on this?
