### ISSUE TITLE
Update "4. Enter Travel Details" section on Case Contact Form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5387]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File/Prototype](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Steps to view a Figma prototype:**
1. Access the provided link in your web browser.
2. Press the play button located at the top right of the browser window.
3. (Optional) Create a free account and log in. This grants access to view comments left on the file.
4. (Optional) If the prototype extends beyond your screen width, click the "options" dropdown at the top right of the screen and select "fit width."
5. Explore the prototype by clicking different areas to discover interactive elements.

**Styling Chart**

<img width="638" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/93c599bd-513d-4d76-be66-53f418767827">

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

**Current Version**
<img width="1212" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/12256324-1d7c-4273-9b53-0495067d9f94">

**Updated version (from Figma File)**
https://www.loom.com/share/9c28d091270649c484ccd49198f0477f

## Acceptance Criteria
- card header should read "1. Travel details (optional)" - see Figma file and styling chart referenced above
- each section of card should be updated to match Figma File - see Figma File and styling chart referenced above
- Card text should use correct styling - see Figma file and styling chart referenced above
- break up card into the 2 sections. 
- Second Section Header should read "2. Other expenses (optional)" and styling and text should match the Figma file/prototype and styling chart.

<img width="1150" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/54b42eba-f8eb-4924-bc55-7b0badcd741c">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by chahmedejaz** [comment]
Hey @bcastillo32 - I'd love to work on this. Can you please assign it to me?

**Comment by chahmedejaz** [comment]
Hey @bcastillo32 - I've a question here.
- Now for the address field, we have a states dropdown. Do we have to implement the same states as shown in the Figma?
- Because I believe states depend upon the entered country. 
- How do we want to handle this? Thanks.

**Comment by bcastillo32** [comment]
> I believe PlainAdmin uses the native browser dropdown styling. if that's correct, let's go with that. As far as country goes, I think our target users are located in the US. Is this correct @bcastillo32 ?

Yes! users are in the US. @chahmedejaz

**Comment by bcastillo32** [comment]
hi @chahmedejaz I just saw your comment and hope you are feeling better! Let us know if there is anything we can do to help or if you are experiencing any blockers. Feel better soon!  ❤️

**Comment by bcastillo32** [comment]
> I'm working on it however, I'm sick these days. Will continue the work soon. Thanks.

Hi @chahmedejaz how are you feeling? are you ok? Please let me know. I hope all is well.

**Comment by chahmedejaz** [comment]
> Hi @chahmedejaz how are you feeling? are you ok? Please let me know. I hope all is well.

I'm feeling much better now, thanks for asking :innocent: 
I've some concerns regarding regarding the new address field. let me do some spike and get back to you on this. Thanks.

**Comment by bcastillo32** [comment]
> > Hi @chahmedejaz how are you feeling? are you ok? Please let me know. I hope all is well.
> 
> I'm feeling much better now, thanks for asking 😇 I've some concerns regarding regarding the new address field. let me do some spike and get back to you on this. Thanks.

Great to hear you are feeling better. and ok sounds good. let us know how we can be of help. 👍🏼

**Comment by chahmedejaz** [comment]
Hey - I'm getting a little busier with my office these days. I might not be able to complete it soon. Sorry for holding this for a long time 😢 
Anyone can pick this up.

**Comment by bcastillo32** [comment]
> @bcastillo32 I'll take this.

Hi @ycorredius thank you! Assigning you now!

**Comment by JoshDevHub** [comment]
If this is open, I'd be glad to work on it @bcastillo32

**Comment by ycorredius** [comment]
@bcastillo32 You can assign it to @JoshDevHub. I didn't have time to complete this.

**Comment by bcastillo32** [comment]
hi @JoshDevHub how are you coming along? Are you experiencing any blockers? any questions? :)

**Comment by JoshDevHub** [comment]
hi @bcastillo32 

It's coming along. A rough todo list of remaining tasks:
- add dollar sign to the "expense amount" field
- split address field up into different sections for street, city, state, etc.
- little details with button styling

Most other changes have been made. The address thing may take me some time to work through because it'll surely involve some digging into how the form is consumed on the backend.

No blockers for now though. Will let you know if/when we run into one :thumbsup:

**Comment by bcastillo32** [comment]
> hi @bcastillo32
> 
> It's coming along. A rough todo list of remaining tasks:
> 
> * add dollar sign to the "expense amount" field
> * split address field up into different sections for street, city, state, etc.
> * little details with button styling
> 
> Most other changes have been made. The address thing may take me some time to work through because it'll surely involve some digging into how the form is consumed on the backend.
> 
> No blockers for now though. Will let you know if/when we run into one 👍

Thanks for the update @JoshDevHub - if you need help please let me know and feel free to reach out in our slack in our #proj-case-contact-refactor channel.

**Comment by JoshDevHub** [comment]
Hi @bcastillo32 

We're still working on this, and we had some questions about the new way the form is handling the address field.

Currently, the address is all one text string. This is the case for both the form and how the data is stored internally in the database:
![Selection_386](https://github.com/rubyforgood/casa/assets/88392688/9fcf75bd-7a2e-4794-a3c0-b77891ca90b9)

The updated design segments the address into different parts in the form like this:
![image](https://github.com/rubyforgood/casa/assets/88392688/7ed51cce-3eef-46ce-99c8-d178c79c1120)

But this creates a discrepancy between how the data is stored (all in one string), and how it is displayed in this form. This can be especially a problem for the existing data on the site, which may or may not neatly fit into the new way this is organized. It's difficult to guarantee the existing data will play nicely with this update.

I think to do this well, we'd have to add new fields to the `addresses` table. Currently it's like this:
```rb
  create_table "addresses", force: :cascade do |t|
    t.string "content" # string that holds full address
    t.bigint "user_id", null: false
  end
```
when it would map better to the new form as something like:
```rb
  create_table "addresses", force: :cascade do |t|
    t.string "street_address"
    t.string "city"
    t.string "state"
    t.string "zip_code"
    t.bigint "user_id", null: false
  end
```
But this would require a migration from the way the data is currently organized into a new way of doing it, which would definitely be out of scope for this ticket.

We could also try writing something that would separate the one string up into constituent pieces, but I'd estimate this would likely run into issues with the way people have formatted their addresses, used punctuation, etc. under the current system.

Do y'all have any thoughts for how to proceed with this?

**Comment by bcastillo32** [comment]
> Hi @bcastillo32
> 
> We're still working on this, and we had some questions about the new way the form is handling the address field.
> 
> Currently, the address is all one text string. This is the case for both the form and how the data is stored internally in the database: ![Selection_386](https://private-user-images.githubusercontent.com/88392688/312610472-9fcf75bd-7a2e-4794-a3c0-b77891ca90b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzQ3NjMsIm5iZiI6MTcxMDM3NDQ2MywicGF0aCI6Ii84ODM5MjY4OC8zMTI2MTA0NzItOWZjZjc1YmQtN2EyZS00Nzk0LWEzYzAtYjc3ODkxY2E5MGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwMDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMGEzZTA5ZGYzNmM5NmQzZTVhYTFlNTQxMjEzYzg3ZDM3ODg0Y2ExOGMyZjA0MGFjNTcyMTMyOGViZDNmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9IchPIfyx0sF6mN14YU9uHvmwEKi6eV_yOxz7Dy_SMI)
> 
> The updated design segments the address into different parts in the form like this: ![image](https://private-user-images.githubusercontent.com/88392688/312610852-7ed51cce-3eef-46ce-99c8-d178c79c1120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzQ3NjMsIm5iZiI6MTcxMDM3NDQ2MywicGF0aCI6Ii84ODM5MjY4OC8zMTI2MTA4NTItN2VkNTFjY2UtM2VlZi00NmNlLTk5YzgtZDE3OGM3OWMxMTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwMDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5M2JjNTk3YTY5MzZhZWVhODFlZGU1MjU5YWNmNWUyNjBlOWVhMzFkYTJiODhjOWZlNmE0YTMwZGFiNWY0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e-fdFXkB_Ztbi9RJLgcH9rIzaSD-JGPYB5LYV8rSW3I)
> 
> But this creates a discrepancy between how the data is stored (all in one string), and how it is displayed in this form. This can be especially a problem for the existing data on the site, which may or may not neatly fit into the new way this is organized. It's difficult to guarantee the existing data will play nicely with this update.
> 
> I think to do this well, we'd have to add new fields to the `addresses` table. Currently it's like this:
> 
> ```ruby
>   create_table "addresses", force: :cascade do |t|
>     t.string "content" # string that holds full address
>     t.bigint "user_id", null: false
>   end
> ```
> 
> when it would map better to the new form as something like:
> 
> ```ruby
>   create_table "addresses", force: :cascade do |t|
>     t.string "street_address"
>     t.string "city"
>     t.string "state"
>     t.string "zip_code"
>     t.bigint "user_id", null: false
>   end
> ```
> 
> But this would require a migration from the way the data is currently organized into a new way of doing it, which would definitely be out of scope for this ticket.
> 
> We could also try writing something that would separate the one string up into constituent pieces, but I'd estimate this would likely run into issues with the way people have formatted their addresses, used punctuation, etc. under the current system.
> 
> Do y'all have any thoughts for how to proceed with this?

Hi @JoshDevHub thank you bringing this to my attention and for detailed explanation. Before I make a final decision, I’m going to run this by design. Seeing that it would require a major change to how data is stored, I’m leaning toward sticking with one field but let me make sure with design first. I’ll be in touch!

**Comment by bcastillo32** [comment]
@JoshDevHub go ahead and leave the address as one field. Thanks for checking and for pointing this out. Let us know if you need anything else :)
