### ISSUE TITLE
Add "4. Court report topics (optional)" card/section to case contact form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5388]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File/Prototype](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Steps to view a Figma prototype:**

1. Access the provided link in your web browser.
2. Press the play button located at the top right of the browser window.
3. (Optional) Create a free account and log in. This grants access to view comments left on the file.
4. (Optional) If the prototype extends beyond your screen width, click the "options" dropdown at the top right of the screen and select "fit width."
5. Explore the prototype by clicking different areas to discover interactive elements.

**Styling Chart**

<img width="638" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/93c599bd-513d-4d76-be66-53f418767827">

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

## Acceptance Criteria

1. The card header should read "4. Court report topics (optional)" - see reference materials above
2. Card components should match that of the figma file and styling chart - see reference materials
3. Card text should match figma file and use correct styling - see reference materials above

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by JoshuaMaurer** [comment]
Hey Brandon! Is it ok if I pick this one up? Cheers!

**Comment by bcastillo32** [comment]
hi @JoshuaMaurer how are you coming along? Any blockers? :)

**Comment by elasticspoon** [comment]
Hey. I'm interested in taking this but I am new to this code base and I had some questions about this issue. 

1. Is PR meant to both create the HTML form and modify the controller?
2. The court report topics themselves, are they hard coded or are they stored on a model somewhere?
3. When you specify the style ex: Content 1, is that a CSS class somewhere that I can apply or does it have some other meaning?

Thanks

**Comment by bcastillo32** [comment]
> Hey. I'm interested in taking this but I am new to this code base and I had some questions about this issue. @bcastillo32
> 
> 1. Is PR meant to both create the HTML form and modify the controller?
> 2. The court report topics themselves, are they hard coded or are they stored on a model somewhere?
> 3. When you specify the style ex: Content 1, is that a CSS class somewhere that I can apply or does it have some other meaning?
> 
> Thanks

Hi @elasticspoon The card will need to be created. I'm not 100% clear on my understanding of controllers but perhaps I can provide a bit more context on what the end design will look like. For now the topics can be hardcoded but soon after this form revamp is done, we will want those topics to be customizable for admins. So one day an admin of an ord might decide to use different topics. Does this help answer your question?

As for the "Content 1" that is to be used for text in the card that say "optional" like the picture below
<img width="172" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/f7d13e26-ae72-4448-a709-ca2f9cefc4cd">

**Comment by elasticspoon** [comment]
Well, I've got the basic look of it sketched out
![image](https://github.com/rubyforgood/casa/assets/14540596/2fd9f4a2-a16f-4b01-b885-a5dae1c3f8cd)

However, I am not totally sure how best to hook this up, as in make this portion of the form actually do something. Like if admins of orgs might want to change this the information should probably live with the org rather than with the case contact. 

Who would be best to consult for something like that? As in who would know more about the back end?

**Comment by bcastillo32** [comment]
> Well, I've got the basic look of it sketched out ![image](https://private-user-images.githubusercontent.com/14540596/299828917-2fd9f4a2-a16f-4b01-b885-a5dae1c3f8cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMzIwMTAsIm5iZiI6MTcwNjIzMTcxMCwicGF0aCI6Ii8xNDU0MDU5Ni8yOTk4Mjg5MTctMmZkOWY0YTItYTE2Zi00YjAxLWI4ODUtYTVkYWUxYzNmOGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAxMTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ODBkZTdkNTZjN2U0OTcyYzRkZjc3MWIwNWRiYWYxMjQzYmYwZGEyMzcyMTFiMDI1MTcwMjI2YzdkZDVhMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXD0QtSYk-PDKoqd5S1PAmMY29uTamHpM29vp2Q5Wg8)
> 
> However, I am not totally sure how best to hook this up, as in make this portion of the form actually do something. Like if admins of orgs might want to change this the information should probably live with the org rather than with the case contact.
> 
> Who would be best to consult for something like that? As in who would know more about the back end?

Hi there. if you could please join our slack channel and message me (Brandon) in the #proj-case-contact-refactor channel we can help connect with a backend dev who is a maintainer.

**Comment by bcastillo32** [comment]
@elasticspoon and apologies - I could have been more clear but the topics will be set at the org level by admins and will be applied to every case contact. Let me know is this helps. Please do connect on slack as well :)

**Comment by elasticspoon** [comment]
still working

**Comment by elasticspoon** [comment]
@bcastillo32 Hey. So a couple of questions came up:

For clarity I will call this the questions page
![image](https://github.com/rubyforgood/casa/assets/14540596/f54b0174-5c15-43d3-b807-8447f901548b)
And this the answers page: 
![image](https://github.com/rubyforgood/casa/assets/14540596/c0bd1b07-6132-4ff4-b38c-ac5d341d8117)

1. On the questions page the user does not select anything, on the answers page the user expands every question. They go back to the questions page. Should the questions be selected now?

2. Who has permissions to add contact topics for an organization?

**Comment by bcastillo32** [comment]
> @bcastillo32 Hey. So a couple of questions came up:
> 
> For clarity I will call this the questions page ![image](https://private-user-images.githubusercontent.com/14540596/305752283-f54b0174-5c15-43d3-b807-8447f901548b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzI1MDksIm5iZiI6MTcwODM3MjIwOSwicGF0aCI6Ii8xNDU0MDU5Ni8zMDU3NTIyODMtZjU0YjAxNzQtNWMxNS00M2QzLWI4MDctODQ0N2Y5MDE1NDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE5NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4N2M4NGE2NmFjNzA2NTA2OWYwNGUwNDkzNmZhM2VmNmRmMWRiMzRiZmE4YjQ3NmNmMDM1MDNlZjAxZWY1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GVJ30hPkL-ndp5nolgBxDea7FSnq9q5ADWgNHMu6sYw) And this the answers page: ![image](https://private-user-images.githubusercontent.com/14540596/305752353-c0bd1b07-6132-4ff4-b38c-ac5d341d8117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzI1MDksIm5iZiI6MTcwODM3MjIwOSwicGF0aCI6Ii8xNDU0MDU5Ni8zMDU3NTIzNTMtYzBiZDFiMDctNjEzMi00ZmY0LWIzOGMtYWM1ZDM0MWQ4MTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE5NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OWI5ZGI3ZDU5NGU1YzdiOGZkZGIxNTM1YjM5MWEwZTk2NWE2MzUwNmMwMGVmNTA5MjBhYTMzYzI3MDhjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l6kiPYsPT6hUSu_rZmaANdisAiY0Afc1BAaUcKBipR0)
> 
> 1. On the questions page the user does not select anything, on the answers page the user expands every question. They go back to the questions page. Should the questions be selected now?
> 2. Who has permissions to add contact topics for an organization?

Hi @elasticspoon - I am going to answer these questions in our slack channel and will tag you. question one is more of a design choice and needs to be answered by Mallory. Thank you for calling this out. This is a great edge case we did not think about.

**Comment by MalloryPriceDesign** [comment]
> > @bcastillo32 Hey. So a couple of questions came up:
> > For clarity I will call this the questions page ![image](https://private-user-images.githubusercontent.com/14540596/305752283-f54b0174-5c15-43d3-b807-8447f901548b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzI1MDksIm5iZiI6MTcwODM3MjIwOSwicGF0aCI6Ii8xNDU0MDU5Ni8zMDU3NTIyODMtZjU0YjAxNzQtNWMxNS00M2QzLWI4MDctODQ0N2Y5MDE1NDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE5NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4N2M4NGE2NmFjNzA2NTA2OWYwNGUwNDkzNmZhM2VmNmRmMWRiMzRiZmE4YjQ3NmNmMDM1MDNlZjAxZWY1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GVJ30hPkL-ndp5nolgBxDea7FSnq9q5ADWgNHMu6sYw) And this the answers page: ![image](https://private-user-images.githubusercontent.com/14540596/305752353-c0bd1b07-6132-4ff4-b38c-ac5d341d8117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzI1MDksIm5iZiI6MTcwODM3MjIwOSwicGF0aCI6Ii8xNDU0MDU5Ni8zMDU3NTIzNTMtYzBiZDFiMDctNjEzMi00ZmY0LWIzOGMtYWM1ZDM0MWQ4MTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE5NTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OWI5ZGI3ZDU5NGU1YzdiOGZkZGIxNTM1YjM5MWEwZTk2NWE2MzUwNmMwMGVmNTA5MjBhYTMzYzI3MDhjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l6kiPYsPT6hUSu_rZmaANdisAiY0Afc1BAaUcKBipR0)
> > 
> > 1. On the questions page the user does not select anything, on the answers page the user expands every question. They go back to the questions page. Should the questions be selected now?
> > 2. Who has permissions to add contact topics for an organization?
> 
> Hi @elasticspoon - I am going to answer these questions in our slack channel and will tag you. question one is more of a design choice and needs to be answered by Mallory. Thank you for calling this out. This is a great edge case we did not think about.

Hi @elasticspoon! Great questions, here are some of my thoughts. Let me know if you have any other questions

1. I do not think we need to update the selections on the questions page if the user has expanded the topics on the answers page. Are you storing these selections in the backend? If we are, then we might want to update the selections, but I'm not sure we need to store this information at all, since we should store the users' text responses in the answers page.
2. Brandon is correct, only admins of that organization have permission to edit topics. Let me know if you have questions about the UX for that page. You can see the admin view in that same Figma file.
