### ISSUE TITLE
Make link previews look good

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#539]
**Description**
Add open graph tags for:
- site title
- site description
- site image

Example: 
![Screen Shot 2020-09-09 at 7 01 18 PM](https://user-images.githubusercontent.com/578159/92672995-e5c06f00-f2ce-11ea-82bd-4733ba792fc9.png)

**Content**
site title: CASA Volunteer Tracking
site description: Volunteer activity tracking for CASA volunteers, supervisors, and administrators. 
site image:
![AM14480-1-800x533](https://user-images.githubusercontent.com/62810851/90304444-cd466b80-de6c-11ea-8b77-0a5946d52dcb.jpg)

**Comment by joaovitoras** [comment]
@Zrrrpy can you assign this problem to me? I would love to work on it
