### ISSUE TITLE
Update "5. Enter Notes" section on case contact form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5391]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File/Prototype](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Steps to view a Figma prototype:**
1. Access the provided link in your web browser.
2. Press the play button located at the top right of the browser window.
3. (Optional) Create a free account and log in. This grants access to view comments left on the file.
4. (Optional) If the prototype extends beyond your screen width, click the "options" dropdown at the top right of the screen and select "fit width."
5. Explore the prototype by clicking different areas to discover interactive elements.

**Styling Chart**

<img width="638" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/93c599bd-513d-4d76-be66-53f418767827">

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

**Current Version**
<img width="1231" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/c4ad91f4-0233-4dcf-b41c-f16420738312">

**Updated version (from Figma File)**
<img width="1130" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/7ed73f5b-8d5d-41ce-9d1b-c3472f539673">

## Acceptance Criteria
- card header should read "7. Additional notes (optional)" - see Figma file and styling chart referenced above
- each section of card should be updated to match Figma File - see Figma File and styling chart referenced above
- Card text should use correct styling - see Figma file and styling chart referenced above
- please note - you do not need to create the accordion effect as seen in the Figma file/prototype. This will be done on a separate ticket. 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Iverick** [comment]
I can work on this

**Comment by bcastillo32** [comment]
Hi @Iverick ! How are you coming along? Are you experiencing any blockers?
