### ISSUE TITLE
Bug: Uncaught exception for email preview

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5396]
**Environment:** qa
**Message**: Could not find an executable ["pdftk"] on your path.
**Stack:**
  **File:** app/services/fdf_inputs_service.rb:20
```ruby
  def write_to_file(flatten: true)
    file ||= Tempfile.new(basename)
    with_fdf_tempfile do |fdf|
      pdftk = PdfForms.new
      pdftk.fill_form_with_fdf(pdf_template_path, file.path, fdf.path, flatten: flatten)
    end
    file
```
  **File:** app/services/fdf_inputs_service.rb:34
```ruby
    Tempfile.open(basename) do |fdf|
      fdf.puts ERB.new(fdf_template).result(binding)
      fdf.rewind
      yield(fdf)
    end
  end

```
  **File:** app/services/fdf_inputs_service.rb:31
```ruby
  attr_reader :inputs, :pdf_template_path, :basename

  def with_fdf_tempfile
    Tempfile.open(basename) do |fdf|
      fdf.puts ERB.new(fdf_template).result(binding)
      fdf.rewind
      yield(fdf)
```
  **File:** app/services/fdf_inputs_service.rb:19
```ruby

  def write_to_file(flatten: true)
    file ||= Tempfile.new(basename)
    with_fdf_tempfile do |fdf|
      pdftk = PdfForms.new
      pdftk.fill_form_with_fdf(pdf_template_path, file.path, fdf.path, flatten: flatten)
    end
```
  **File:** app/mailers/fund_request_mailer.rb:16
```ruby
        inputs: @inputs,
        pdf_template_path: File.join(["data", "fund_request.pdf"]),
        basename: ["fund_request", "pdf"]
      ).write_to_file.read
      attachments.inline["fund-request-#{Date.today}-#{submitter_name}.pdf"] = pdf_attachment
    rescue => e
      Bugsnag.notify(e)
```

**Controller:** rails/mailers#preview
**App URL:** https://casa-qa.herokuapp.com/rails/mailers/fund_request_mailer/send_request?part=text%2Fhtml

## How to Replicate
 - Visit /rails/mailers
 - Click on send_request
![image](https://github.com/rubyforgood/casa/assets/8918762/0b8034b2-054b-412c-9a76-5f7fa6267f7b)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](http://bit.ly/3Quxc1Q) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mgrigoriev8109** [comment]
@FireLemons I can work on this one.

**Comment by fchagasjr** [comment]
Can I be assigned to this?
