### ISSUE TITLE
New Line Chart Metric

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5407]
## Description
On the `/health` page, add a new line chart. The chart should contain 12 months of data including the current month. The chart should track the following stats:
 - count of how many case contacts were created during the month
 - count of how many case contacts created during the month had notes
 - count of users who created case contacts during the month

Create a json endpoint for the chart data. Make sure the json contains the minimum amount of data for the chart. Make sure the endpoint is accessible to users who are logged out.

If chart creation fails, display an error to the user explaining why. Print a detailed version of the error in the console.

No testing required but prove your solution works. 

See:
 - https://github.com/rubyforgood/casa/blob/main/app/controllers/health_controller.rb
 - https://github.com/rubyforgood/casa/blob/main/app/javascript/src/display_app_metric.js

We use [chart.js](https://www.chartjs.org/docs/latest/samples/line/line.html) for graphs
See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](http://bit.ly/3Quxc1Q) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @FireLemons Can you assign it to me.. I would like to implement this feature. Thanks

**Comment by bcastillo32** [comment]
looking forward to this! Thank you for creating the ticket @FireLemons and thank you for working on it @sarvaiyanidhi !

**Comment by sarvaiyanidhi** [comment]
PR is submitted for review #5425

**Comment by sarvaiyanidhi** [comment]
PR is submitted for review
