### ISSUE TITLE
Bug: Banner dismissed forever 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5428]
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Environment
QA and Prod

## Current Behavior
When a user dismisses an "active" banner in one session, the banner never shows up for them again - it is dismissed forever

https://www.loom.com/share/9d0312d7095b4419bf760bcd0de22d0f

## Expected Behavior
active banners should show up for every session for a user as long as the banner is "active"

## How to Replicate
ex: 
1. Log in as an admin or supervisor.
2. Click on "Banners"
3. Create a new banner and set it to "active"
4. Dismiss the banner for yourself
5. End your session by logging out and log back in
6. Notice the banner is not showing for you despite it still being active

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](http://bit.ly/3Quxc1Q) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by h-m-m** [comment]
I've got my dev env set up, so I'll look into this today and tomorrow
