### ISSUE TITLE
upgrade rails from 7.0.8 to 7.1.0

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5462]
## Description
A new version of rails is not compatible with our project. Fix the compatibility issues and upgrade the rails version. The target version is only to 7.1.0 because that version most likely contains the compatibility issues.

See: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1
See: https://github.com/rubyforgood/casa/pull/5434

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @FireLemons I can work on this upgrade.. Can you please assign it to me?

**Comment by sarvaiyanidhi** [comment]
Submitted PR and work in progress

**Comment by sarvaiyanidhi** [comment]
Submitted PR and waiting for feedback
