### ISSUE TITLE
Fix rswag deprecation warning

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5467]
## Description
Update the rswag initializer so that this warning goes away:

```
DEPRECATION WARNING: swagger_root= is deprecated and will be removed from rswag-api 3.0 (use openapi_root= instead) (called from block in <top (required)> at .../casa/config/initializers/rswag_api.rb:6)
```

This warning can be caused by resetting the database using `rails db:reset`

**Comment by fransan6** [comment]
Can I give this a go? I'm quite beginner though so if I can't do it within a day or two, then I'll say so someone else can do it

**Comment by compwron** [comment]
@fransan6 go for it! :)

**Comment by fransan6** [comment]
Submitted PR that was merged. Issue to be closed.
