### ISSUE TITLE
Remove Localization

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5470]
## What type(s) of user does this feature affect?
 - volunteers

## Description
Finally remove localization from the app.

 - remove the final `t(` calls from `/app/notifications/emancipation_checklist_reminder_notification.rb`
 - delete the directory `/config/locales`
 - determine if any gems should be removed and remove them

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by fchagasjr** [comment]
Please, can I be assigned to this?
