### ISSUE TITLE
Admins/Supervisors Learning Hours Tab - Clicking on Volunteer name should route to Volunteer's Learning Hours Page

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5474]
## Impacted User Types
 - supervisors
 - admins

## Current Behavior
When the Admin or Supervisor clicks on the volunteer's name in the "Learning Hours" page, they are routed to "Editing Volunteer"

<img width="1437" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/f428ac00-04f0-45c2-8542-243e33fcae1b">

<img width="1399" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/391a958c-e35f-44e3-ba48-56de4e88d73e">

## How to Replicate
ex: 
1. - Log in as a supervisor
2. - Click on "Learning Hours" in the left sidebar menu.
3. - Click on a volunteer name 

## Expected Behavior
When the Admin or Supervisor clicks on the volunteer's name in "Learning Hours", they should be routed to that Volunteer's Learning Hours page so they see what types of learnings the volunteer has done.

<img width="1429" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/a4103b72-4be8-4958-9db4-673e77f50d5d">

## Where to see the expected routing point
ex: 
1. - Log in as a volunteer
2. - Click on "Learning Hours" in the left sidebar menu. 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack! 

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Nwabor** [comment]
Hi @bcastillo32 can you please assign this to me?

**Comment by bcastillo32** [comment]
> Hi @bcastillo32 can you please assign this to me?

Yes! Thank you for picking this up and please reach out if you have any questions :)

**Comment by Nwabor** [comment]
Okay..Thanks

**Comment by sarvaiyanidhi** [comment]
Hi @bcastillo32 I can work on this if it is still available.. Thanks
