### ISSUE TITLE
Add "YTD" to "Time Completed" Learning Hours Table Column

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5486]
## What type(s) of user does this feature affect?
 - supervisors
 - admins

## Description
Supervisors and Admins "Learning Hours" table has column titled "Time Completed". Please make the column read "Time Completed YTD"

<img width="1440" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/2a55c54b-4828-4e32-ada7-6cc730986744">

## Navigating to the Supervisor/Admin "Learning Hours" table
- Log in as an Admin
- Click on "Learning Hours"

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by TheZero0-ctrl** [comment]
I will like to solve this issue

**Comment by compwron** [comment]
@TheZero0-ctrl go for it!
