### ISSUE TITLE
By default this was set to true but I have changed it to false as it was failing specs for verify_authorized action

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#5502]
By default this was set to true but I have changed it to false as it was failing specs for verify_authorized action

_Originally posted by @sarvaiyanidhi in https://github.com/rubyforgood/casa/pull/5478#discussion_r1447657413_

**Comment by JoshDevHub** [comment]
I'd be glad to look into this one.

**Comment by JoshDevHub** [comment]
Still workin on it :thumbsup:
