### ISSUE TITLE
Add Name of assigned volunteer next to docket number (for Supervisors/Admins only)

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5520]
## What type(s) of user does this feature affect?
 - supervisors
 - admins

## Description
For Supervisors and Admins roles - Please add the name of the assigned volunteer next to (the right) the case docket number as pictured below. Please use black text similar in size to the docket number with a light grey background. Everywhere a docket shows for the Supervisor and admin, the assigned volunteer's name should follow. If there is not a volunteer assigned, please use "Unassigned".

If you have any questions, comments or concerns, please reach out to me here or on slack :) 

## Screenshots
<img width="1142" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/ec90549e-42b2-487b-87b0-fb0cfedc87a3">
<img width="426" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/c34711c9-2501-4f53-8e51-99c331380ea1">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Hi @bcastillo32 ,

Was checking on above requirement and wanted to clarify before proceeding with implementation.

We are already showing Volunteer name in Assigned To field so showing again volunteer name next to docker won't it duplicate information in the screen.

Attaching the screenshot for reference

![CASA-Volunteer-Tracking](https://github.com/rubyforgood/casa/assets/514363/94a366b4-567a-4214-8b62-531c595b5a44)

Can you please clarify if I am missing something?

**Comment by bcastillo32** [comment]
> Hi @bcastillo32 ,
> 
> Was checking on above requirement and wanted to clarify before proceeding with implementation.
> 
> We are already showing Volunteer name in Assigned To field so showing again volunteer name next to docker won't it duplicate information in the screen.
> 
> Attaching the screenshot for reference
> 
> ![CASA-Volunteer-Tracking](https://private-user-images.githubusercontent.com/514363/304273596-94a366b4-567a-4214-8b62-531c595b5a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3OTg4MDEsIm5iZiI6MTcwNzc5ODUwMSwicGF0aCI6Ii81MTQzNjMvMzA0MjczNTk2LTk0YTM2NmI0LTU2N2EtNDIxNC04YjYyLTUzMWM1OTViNWE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwNDI4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2EwMjhlZTBiNTUzZTRiNWQxZDQ2YWE5MDMxZjY5MjFjYjQ5NzJjYzU4YTFiYmQ1ZjYwZDFlZTY0NTc2YTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0x9Ql9XTKBxo8NXf7RaBVXxD1E0PkT0FybyfCMxxuLg)
> 
> Can you please clarify if I am missing something?

Hi @sarvaiyanidhi it is ok to add the assigned name next to the docket number for supervisor/admins. This ticket is unrelated to the column you pointed out. Does this help clarify? CASA stakeholders let us know it would be most helpful to always have the names included with the docket as proped.

**Comment by bcastillo32** [comment]
@sarvaiyanidhi since you worked on the last chart, would you be interested in working on new one we need? Please see the [ticket here](https://github.com/rubyforgood/casa/issues/5530) and let me know :)

**Comment by sarvaiyanidhi** [comment]
> Hi @sarvaiyanidhi it is ok to add the assigned name next to the docket number for supervisor/admins. This ticket is unrelated to the column you pointed out. Does this help clarify? CASA stakeholders let us know it would be most helpful to always have the names included with the docket as proped.

Thank you for the clarification. Will go ahead and implement the solution as per requirement. Thanks

**Comment by sarvaiyanidhi** [comment]
Have already released PR for review #5534

**Comment by sarvaiyanidhi** [comment]
PR is submitted for review #5534

**Comment by sarvaiyanidhi** [comment]
PR is submitted for review https://github.com/rubyforgood/casa/pull/5534

**Comment by sarvaiyanidhi** [comment]
Working on PR feedback
