### ISSUE TITLE
Update Phone Number Input

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5573]
## Impacted User Types
 - supervisors
 - admins

## Current Behavior
When supervisors create a new volunteer profile, they must input the volunteer's phone number in a specific way. Update this input box to accept phone numbers in the following formats:

International: +1XXXXXXXXXX

Basic: XXXXXXXXXX, 1XXXXXXXXXX

Hyphenated: XXX-XXX-XXXX, 1-XXX-XXX-XXXX

Spaced: XXX XXX XXXX, 1 XXX XXX XXXX

Parentheses: (XXX)XXXXXXX, (XXX) XXX-XXXX, 1(XXX)XXX-XXXX

Dots: XXX.XXX.XXXX, 1.XXX.XXX.XXXX

Note: If entering all of these formats is not possible, include the necessary text to prompt the user to enter in the correct format (1 example is good) and please include placeholder text in the input box with the correct format. 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by zsalikmtc** [comment]
I would love to take a crack at this! Once approved, is it recommended to make a branch to work on the issue? Thank you!

**Comment by bcastillo32** [comment]
> I would love to take a crack at this! Once approved, is it recommended to make a branch to work on the issue? Thank you!

Hi @zsalikmtc apologies for the delayed response I was out and then had to catch up on some stuff for work. Plz do create a new branch and let me know if you run into any issues. Thank you for working on this - it was a big ask from our users :)

**Comment by zsalikmtc** [comment]
> > I would love to take a crack at this! Once approved, is it recommended to make a branch to work on the issue? Thank you!
> 
> Hi @zsalikmtc apologies for the delayed response I was out and then had to catch up on some stuff for work. Plz do create a new branch and let me know if you run into any issues. Thank you for working on this - it was a big ask from our users :)

Hi @bcastillo32 Thank you so much! I created a branch and have been hacking away at this, and should have some good results soon. 

Would you be able to give me access to push the branch to the repo? It gave me a permission denied, not sure if I just need to be granted access. Thanks so much!

**Comment by bcastillo32** [comment]
> > > I would love to take a crack at this! Once approved, is it recommended to make a branch to work on the issue? Thank you!
> > 
> > 
> > Hi @zsalikmtc apologies for the delayed response I was out and then had to catch up on some stuff for work. Plz do create a new branch and let me know if you run into any issues. Thank you for working on this - it was a big ask from our users :)
> 
> Hi @bcastillo32 Thank you so much! I created a branch and have been hacking away at this, and should have some good results soon.
> 
> Would you be able to give me access to push the branch to the repo? It gave me a permission denied, not sure if I just need to be granted access. Thanks so much!

Hi @zsalikmtc sounds great! I will find out about access to push to repo and get back to you asap.

**Comment by bcastillo32** [comment]
@zsalikmtc we also have [some info here](https://github.com/rubyforgood/casa/blob/main/doc/CONTRIBUTING.md) that might answer your question. Let me know if this helps.

**Comment by bcastillo32** [comment]
@zsalikmtc I confirmed the process is to fork the casa repository, work on that copy (since its your copy you can freely push changes) and when you want to you open a pull request to get your local changes into the main repository. Info can be found in the contributing guide I linked above.

**Comment by zsalikmtc** [comment]
Sounds good @bcastillo32! I will follow those steps. Take care!

**Comment by compwron** [comment]
> I am continuing to work on this, and will create a PR as soon as I am ready by mid-week.
> […](#)
> On Apr 21, 2024 at 20:15 -0400, github-actions[bot] ***@***.***>, wrote: This issue has been inactive for 248 hours (10.33 days) and will be unassigned after 112 more hours (4.67 days). If you have questions, please If you are still working on this, comment here to tell the bot to give you more time — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

very cool :)
