### ISSUE TITLE
Migrate Case Contact Notes to Corresponding Section When Generating Court Report

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5579]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
When a user generates a court report, they should be able to pick the date range for case contact notes to flow into their corresponding section of the court report doc. 

[Figma File](https://www.figma.com/file/OuJMUdTiBbyNhiiOtqVaBG/Generate-Report-Flow?type=design&node-id=0%3A1&mode=design&t=cGQDpVrDhC5EXrMv-1)
[Prototype](https://www.figma.com/proto/OuJMUdTiBbyNhiiOtqVaBG/Generate-Report-Flow?page-id=0%3A1&type=design&node-id=35-6399&viewport=287%2C1263%2C0.54&t=JDPdyDjDKpJkdcr5-1&scaling=min-zoom&starting-point-node-id=35%3A6399)

The prototype shows this page - Please implement here:
<img width="1912" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/f27cb389-5b04-434a-9ddf-9ce3a1a8453c">

Please also implement the modal behavior where users can generate a court report from "Case Details" using the "Generate Report" button on the top right of the screen. The case should default to whatever case they are in. 
<img width="1904" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/e2f6fc28-1f70-4e5f-a6e1-dd038f911815">
<img width="490" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/afbdddfe-9e90-4fa6-aa3a-4f5669b58cf9">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by elasticspoon** [comment]
I shall take
