### ISSUE TITLE
Group CASA cases in dropdown menu by not/assigned to volunteer

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#558]
Part of epics #4 and #105 

**What type of user is this for? [admin/supervisor/admin/all casa admin/all]**
supervisors and admins

**Where does/should this occur?**
On the Edit Volunteer page, in the drop down menu under "Assign a new case".

**Description**
On Edit Volunteer page, use "option groups" for CINA numbers in the dropdown menu
- 1 group for not assigned to any volunteer
- 1 group for assigned to at least 1 volunteer 

**Screenshots**
Example: http://localhost:3000/volunteers/672/edit
![Screen Shot 2020-08-17 at 5 34 47 PM](https://user-images.githubusercontent.com/578159/90457324-11757e00-e0b0-11ea-8de4-2f23156437a9.png)

This is related to: https://github.com/rubyforgood/casa/issues/558

**Comment by drborges** [comment]
I'll be working on this one.

**Comment by drborges** [comment]
Looks like there are higher priority stories that I can work on, so I'll move this back to `To do`.
