### ISSUE TITLE
Format date to US format MM/DD/YYYY

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5580]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 - all casa admins

## Description
Date is formatted in an odd format. See screenshot below from Case Creation as an Admin:
<img width="1908" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/1bc968e4-19e3-4909-aa14-5bc198e22235">

we would instead like all date picking and formatting to be in US format (MM/DD/YYYY). Users should also be able to type it in as long as it matches the format. If they type it incorrectly please return a message letting them know the correct format required. 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by daviluis321** [comment]
I would like to help with this issue :)

**Comment by bcastillo32** [comment]
> I would like to help with this issue :)

Assigned. Thank you for the help! :)

**Comment by RobBoothAppDev21** [comment]
Hi

By the way, ActiveRecord's default date format is yyyy/mm/dd. Dates passed along as mm/dd/yyyy are converted to "" resulting in court date objects being nil.

Removing bootstrap datepicker and data options and changing the input to a date_field will default to the browsers default picker and use the users locale format, mm/dd/yyyy for the US, but should submit in ActiveRecords preferred format of yyyy/mm/dd. The native picker has some slight styling difference and could require light js to open the calendar when the input field is selected. I included screenshots using the native picker in chrome.

app/views/casa_cases/_form.html.erb:67
current:
`<%= cdf.text_field :date,
                                 data: {provide: "datepicker", date_format: "yyyy/mm/dd"},
                                 class: "form-control" %>`

update:
`<%= cdf.date_field :date, class: "form-control" %>`

![Screenshot 2024-04-04 at 12 42 50 PM](https://github.com/rubyforgood/casa/assets/91844645/f808acb7-8c2a-4de3-9fd8-909fea5c2208)
![Screenshot 2024-04-04 at 12 43 35 PM](https://github.com/rubyforgood/casa/assets/91844645/27fedfd9-5989-47a0-9090-1137769b46da)

**Comment by bcastillo32** [comment]
> Hi
> 
> By the way, ActiveRecord's default date format is yyyy/mm/dd. Dates passed along as mm/dd/yyyy are converted to "" resulting in court date objects being nil.
> 
> Removing bootstrap datepicker and data options and changing the input to a date_field will default to the browsers default picker and use the users locale format, mm/dd/yyyy for the US, but should submit in ActiveRecords preferred format of yyyy/mm/dd. The native picker has some slight styling difference and could require light js to open the calendar when the input field is selected. I included screenshots using the native picker in chrome.
> 
> app/views/casa_cases/_form.html.erb:67 current: `<%= cdf.text_field :date, data: {provide: "datepicker", date_format: "yyyy/mm/dd"}, class: "form-control" %>`
> 
> update: `<%= cdf.date_field :date, class: "form-control" %>`
> 
> ![Screenshot 2024-04-04 at 12 42 50 PM](https://private-user-images.githubusercontent.com/91844645/320077824-f808acb7-8c2a-4de3-9fd8-909fea5c2208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTc1MzEsIm5iZiI6MTcxMjUxNzIzMSwicGF0aCI6Ii85MTg0NDY0NS8zMjAwNzc4MjQtZjgwOGFjYjctOGMyYS00ZGUzLTlmZDgtOTA5ZmVhNWMyMjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE5MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNTEwMjkzOWZlM2I3YjczZjVjYmY0YjZkYWUwODc3Y2Q5YTY0NzY5M2M3MzdjNGM1YWFkNTdiZDBmNDg4ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aBZLKnbmEF3t1ArglqQ6AQh7yZhYi3iAKi29pWq1zK8) ![Screenshot 2024-04-04 at 12 43 35 PM](https://private-user-images.githubusercontent.com/91844645/320077843-27fedfd9-5989-47a0-9090-1137769b46da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTc1MzEsIm5iZiI6MTcxMjUxNzIzMSwicGF0aCI6Ii85MTg0NDY0NS8zMjAwNzc4NDMtMjdmZWRmZDktNTk4OS00N2EwLTkwOTAtMTEzNzc2OWI0NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE5MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTFiYTI5NGQ3YmYzODdkYTg5M2ZmNDI0MGIxNWJmNDM4YzA5ODRlMzk3NDViYzJmZjQwZTg5ODdiYzIzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rvjWzS9sidJvS25zDlulJMoh1d_jtnhb5sUbO0rl1xY)

Hi @RobBoothAppDev21 apologies for my delayed response - I had just got back from traveling and was catching up on some stuff for work. Thank you for the detailed explanation. Can we go ahead and change all date pickers to the native one? From what I understand, this will fix the issue, correct?

**Comment by RobBoothAppDev21** [comment]
Yes, using the native browser should fix it. 

No problem I'll get started on it.

**Comment by bcastillo32** [comment]
> Yes, using the native browser should fix it.
> 
> No problem I'll get started on it.

Thanks so much! 🙏🏼

**Comment by bcastillo32** [comment]
> @bcastillo32 Almost finished with [updating](https://github.com/ryoung-sf/casa/commit/6006cfa90d24725d28c4aaafb909c8bb059c0792) the date picker to use mm/dd/yyyy format.
> 
> I added "onfocus: this.showPicker()" to the date fields to enable the date picker, calendar, to open when a user clicks on the field. The onfocus attribute in views/layouts/components/_ranged_date_picker.html.erb causes the tests on lines 42 and 189 to fail in the spec/systems/case_contacts/new_spec.rb to fail. The hours and minutes used to calculate the duration are being submitted as "0" in the test. I think the wizard and the onfocus attribute are conflicting but I can't determine where. However, this issue doesn't exist when running the app locally.

Hi @ryoung-sf thanks for the update! Are you on our slack by chance? You can post there for help with tests if you need it.
