### ISSUE TITLE
Bug: Health Page - contacts without notes calculated incorrectly

### ISSUE THREAD

**Issue by MalloryPriceDesign** [rubyforgood/casa#5591]
## Impacted User Types
Viewers of the [health page](https://casavolunteertracking.org/health), ie RFG members

## Current Behavior
The Case Contact Creation graph depicts **Total Case Contacts** and **Total Contacts with Notes**. Due to recent changes introduced by https://github.com/rubyforgood/casa/pull/5517, the calculation for **Contacts with Notes** needs to be updated.

If you see [here](https://github.com/rubyforgood/casa/blob/3302c45c24acb52e28b34085ee88e3f8ad00eef1/app/controllers/health_controller.rb#L27), we are only considering Case Contacts without an empty notes field as Contacts with Notes. This field still exists, however, users can now capture notes on specific topics by using the newly created `contact_topic_answers`. These new topic answers should be considered notes and be included in the calculation of Contacts with Notes.

## Expected Behavior
We need to update how we calculate Contacts with Notes. 

A Contact should be considered a Contact With Notes if **either** of the following is true:
- The contact's `notes` field is not empty
- Any of the contact's contact topic answers are not empty

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Have fixed issue and created PR #5592
