### ISSUE TITLE
Bug: Weekly supervisor email bottom section includes unknown names - probably volunteers from other orgs

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#5597]
## Impacted User Types

 - supervisors

## Environment
prod

## Current Behavior
Bug: Weekly supervisor email bottom section includes unknown names - probably volunteers from other orgs

## Expected Behavior
Show only the email-receiving-supervisor's volunteers who have not logged in

## How to Replicate
TODO

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by nepaakash** [comment]
Hello, if this task is ready to work on, I would like to work on it.

**Comment by bcastillo32** [comment]
> Hello, if this task is ready to work on, I would like to work on it.

thank you @nepaakash !

**Comment by nepaakash** [comment]
Hello @bcastillo32, Can I have furthermore details on this bug?

**Comment by bcastillo32** [comment]
hi @nepaakash apologies for the delay -  the email that is going out is listing volunteers who haven't logged on but for some reason, it lists 100 people, most not even in the org the email recipient is associated with. We think it it could be listing people who have been deleted as users from all orgs possibly. we arent 100% sure. it should only be listing active users that haven't logged in that are associated with the same org as the email recipient.
