### ISSUE TITLE
left navbar edit: un-nest "Generate Court Reports" for Volunteers

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5599]
## What type(s) of user does this feature affect?
 - volunteers

## Description
Please un-nest the "Generate Court Reports" list item from "Group Actions" on the leftnavbar and then get rid of "Group Actions"

<img width="208" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/8fe584f9-1d89-473f-bfc2-829967ba13f4">

Please also make sure the "Generate Court Reports" icon shows when the menu is minimized like the others after you have made your changes.

<img width="73" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/53ceac50-e469-49ad-aed2-6461024ca12d">

**Note**

This displays differently for Admins. It should only get un-nested for volunteers.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by amitduaaa** [comment]
Looks like a great first issue! I would like to take this up. Thanks.

**Comment by bcastillo32** [comment]
> Looks like a great first issue! I would like to take this up. Thanks.

thank you @amitduaaa !

**Comment by amitduaaa** [comment]
Can you please create a branch for me?

**Comment by bcastillo32** [comment]
> @bcastillo32 Can you please create a branch for me?

Hi @amitduaaa - Please refer to our [setup guide here ](https://github.com/rubyforgood/casa#installation)and let me know if you run into any issues.

**Comment by bcastillo32** [comment]
> > @bcastillo32 Can you please create a branch for me?
> 
> Hi @amitduaaa - Please refer to our [setup guide here ](https://github.com/rubyforgood/casa#installation)and let me know if you run into any issues.

hi @amitduaaa are you still working on this?

**Comment by iamronakgupta** [comment]
@bcastillo32 I would love to work on this issue.

**Comment by elasticspoon** [comment]
all you @iamronakgupta
