### ISSUE TITLE
Enable Admins to set an expiration time for banners

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#5604]
## What type(s) of user does this feature affect?
all

## Description
People who can make banners, should be able to add an optional banner expiration, after which the banner will stop showing. This is for banners advertising trainings or other seasonal/dated events. 

see previous work at https://github.com/rubyforgood/casa/issues/5428

## Screenshots of current behavior, if any
Existing banner: 
![Screenshot 2024-04-12 at 11 14 50 AM](https://github.com/rubyforgood/casa/assets/578159/eaced89d-7a92-4a49-9cac-5231b443ac51)
![Screenshot 2024-04-12 at 11 15 25 AM](https://github.com/rubyforgood/casa/assets/578159/9cfaaecc-5de7-4e88-9829-c2c184f20752)
![Screenshot 2024-04-12 at 11 15 19 AM](https://github.com/rubyforgood/casa/assets/578159/0b288210-1e7b-4aa4-9ebe-7434d04a14f1)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sandfortw** [comment]
I'll tackle this one.

**Comment by sandfortw** [comment]
Sorry, some things came up this week and I wasn't able to complete this.
