### ISSUE TITLE
add test for org scoping in supervisor weekly email

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#5640]
Test the code in this PR: https://github.com/rubyforgood/casa/pull/5632/files

_Originally posted by @compwron in https://github.com/rubyforgood/casa/issues/5632#issuecomment-2078327610_

**Comment by compwron** [comment]
@nepaakash do you have time to work on this?

**Comment by nepaakash** [comment]
Yes I will work on it @compwron

**Comment by elasticspoon** [comment]
@nepaakash you still want this or you busy with https://github.com/rubyforgood/casa/issues/5704?

**Comment by nepaakash** [comment]
@elasticspoon I am busy with #5704 right now but I can come back to it later if it is not the high-priority task.

**Comment by elasticspoon** [comment]
closing per discussion in this PR https://github.com/rubyforgood/casa/pull/6024
