### ISSUE TITLE
Add test for successfully submitting case contact for volunteer with only one case

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#5644]
This is a followup which should test the functionality in PRs:
1. https://github.com/rubyforgood/casa/pull/5643
2. https://github.com/rubyforgood/casa/pull/5642
3. https://github.com/rubyforgood/casa/pull/5641

Feel free to ping @schoork for more info

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by guswhitten** [comment]
@compwron can you assign this issue to me?
