### ISSUE TITLE
Implement User login tracking details

### ISSUE THREAD

**Issue by sarvaiyanidhi** [rubyforgood/casa#5652]
## What type(s) of user does this feature affect?
 All

## Description
To implement functionality of MAU (Monthly Active Users) and WAU (Weekly Active Users) by Role as mentioned in issue #5530 , we need to implement functionality to track login history of User.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by sarvaiyanidhi** [comment]
Planning to implement functionality with below steps

- New table login_activities
- Controller inherited from Devise::SessionsController which makes entry in login_activities after each login

**Comment by sarvaiyanidhi** [comment]
@bcastillo32 Can you please assign me this issue?

**Comment by bcastillo32** [comment]
Will do now!
