### ISSUE TITLE
Editing case contact errors should not wipe previous selections

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#570]
Part of epics #3 #105 #4

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
all

**Where does/should this occur?**
On the edit case contact page, accessible from all user dashboards with exception to All CASA Admin.

**Description**
When a user triggers an error message on the Edit Case Contact page, sometimes the user's previous selections get wiped (not all of them, but it's not consistent). Making any changes when editing a case contact (whether or not an error is triggered) should preserve user selections, not wipe them.

This bug is not consistently replicated.

The most common way to trigger an error and replicate: 
Change the duration to 0 hours and 0 minutes, and click submit.

This bug will probably require testing on the entire Edit Case Contact page to help replicate consistently and identify bug.

**Screenshots**
None yet, but if you are able to replicate, please take a screenshot and add here!

**Comment by alindeman** [comment]
I'm planning to work on this during Ruby for Good 2020.
