### ISSUE TITLE
User should remain on the same page after editing a CASA case

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#572]
Part of epics #4, #3, #105

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
all

**Where does/should this occur?**
On the Edit CASA Case page.

**Description**
_Current behavior_: After editing a CASA case, user is redirected back to home. 
_Desired behavior_: After editing a CASA case, user remains on the same page with the same success message they currently see when redirected back to home. 

**Screenshots**
This is what the success message looks like. It should remain the same but appear on the correct page after the CASA case is updated, not on home.
![Screen Shot 2020-08-19 at 7 49 11 PM (2)](https://user-images.githubusercontent.com/62810851/90711314-3fe08e00-e255-11ea-85bb-7e6e4d7066c2.png)

**Comment by GuillermoCoding** [comment]
Hello, going to pick this up!
