### ISSUE TITLE
Fix send_reminder_button

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5729]
The partial `volunteers/_send_reminder_button.html.erb` needs fixing. 

![image](https://github.com/rubyforgood/casa/assets/14540596/0547932a-d44a-46d8-9c41-29eaeebe099f)

It has a label(1) and a checkbox(2). They should not be separate. Consider turning the partial into a ViewComponent.

**Comment by JoshDevHub** [comment]
I'd like to work on this one :slightly_smiling_face:

**Comment by elasticspoon** [comment]
Go for it!

**Comment by JoshDevHub** [comment]
Still a WIP

**Comment by JoshDevHub** [comment]
Still working on this

**Comment by JoshDevHub** [comment]
Still a WIP

**Comment by Smullz622** [comment]
Is this available to work on?

**Comment by elasticspoon** [comment]
@Smullz622 go for it
