### ISSUE TITLE
Clicking on a CASA Case number anywhere on platform should bring you to the CASA Case details page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#575]
Part of epic #4, #3, #105

**What type of user is this for? [admin/supervisor/volunteer/all or All CASA Admin]**
all

**Where does/should this occur?**
Everywhere you can click on a CASA case number.

**Description**
_Current behavior:_ Clicking on a CASA case number pretty much everywhere takes you the Edit CASA Case page.
_Desired behavior:_ Clicking on a CASA case everywhere takes you to the view CASA Case Details page.

**Comment by GuillermoCoding** [comment]
Picking this up! 😃
