### ISSUE TITLE
Fix Contact Type Select Styles

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5759]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

In the contact type selection dropdown when something is being searched for the currently typed in letters get highlighted. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/2b2ec8a2-340d-46a5-a5f0-9c5cecfd3cc4)

As you can see the styling is off. Fix the css styling so this issue is no longer occurring.

- [ ] Fix on page `/case_contacts/:id/form/details` in form Select All Contact Types 
- [ ] Fix on page `/casa_cases/new` in form Contact Types

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by elasticspoon** [comment]
@logtay all you!

**Comment by logtay** [comment]
I submitted a PR (#5830) for this but can make changes
