### ISSUE TITLE
Fix "Manage Volunteers" Styling on `/volunteers` page

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5761]
## What type(s) of user does this feature affect?
 - admins
 - supervisors

## Description

On the `/volunteers` page when a volunteer is checked off a "Manage Volunteers" button suddenly pops up and shifts all the items on the page.

![Image](https://github.com/rubyforgood/casa/assets/14540596/ccfc9b7e-2594-4349-a284-44b79831d12b)

Make is so that this button appearing does not move all the items on the page. 

Additionally change the styling of the checkboxes on the page so the contrast is better when they are not selected.

![Image](https://github.com/rubyforgood/casa/assets/14540596/57fc7c6e-a3c5-4a1d-8a9b-4531d5d9723c)

Criteria for completion:

- [ ] Make is so that this button appearing does not move all the items on the page. 
- [ ] change the styling of the checkboxes on the page so the contrast is better when they are not selected (use #757575)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by IvarSmits** [comment]
Ill create a PR for this issue
