### ISSUE TITLE
Disable expenses page when orgs have no expenses

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5762]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

The final step of the case contact form is filling in driving expenses and additional reimbursements. An organization may choose to disable both those features on  `/casa_org/:id/edit`.

![Image](https://github.com/rubyforgood/casa/assets/14540596/4cbfcf21-b455-4c2f-8acc-b8a3b3bba5c0)

This results in a the final page of the case contact form (`/case_contacts/:id/form/expenses`) looking like this:

![Image](https://github.com/rubyforgood/casa/assets/14540596/fc4a396f-3a38-4bdb-8b4e-3306ef54c8ce)

Change the page so that it does not show for a user if both types of expenses are disabled.

**Note**

This might need some changes to a relatively complex wizard controller (`controllers/case_contacts/form_controller.rb`) 🧙‍♂ 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by iamronakgupta** [comment]
Can I take this up?

**Comment by compwron** [comment]
@iamronakgupta go for it! :)

**Comment by iamronakgupta** [comment]
This is how we wanted it to be? When both types of expenses are disabled.

![image](https://github.com/rubyforgood/casa/assets/75837235/ec5e4506-52f3-4965-8243-3eac19461929)
