### ISSUE TITLE
Add "Enable Other Duties" as Organization Feature flag to Edit Organization 

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5771]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins
 

## Description
Because not all orgs will use "Other Duties" we would like to add this as a Organization Feature. The default should be "On" (check marked). Can be titled "Enable Other Duties"

<img width="1814" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/ac906b49-dcae-4a55-9509-677e7be79fb2">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by iamronakgupta** [comment]
Can I take this?

My approach will incluce following steps:

1. Creating a migration for  casa_org table to add other_duties_enabled as new columns.
2. Change view of edit layout to add Enable Other Duties checkbox.
3. Add authorization in OtherDuty Policy to check for  other_duties_enabled field from casa_org.
4. Putting constraint for Other Duties in Sidebar.

**Comment by elasticspoon** [comment]
@iamronakgupta sounds like a reasonable approach. go for it
