### ISSUE TITLE
Uncap submissions for Additional Expenses and improve UX

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5773]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

If an org has enabled additional expenses the last step of the case contact form (`case_contacts/:id/form/expenses`) allows the volunteer to add additional expenses.

![Image](https://github.com/rubyforgood/casa/assets/14540596/cf911fd9-4080-4d0d-8b1d-ef5dc4cb66b2)

Currently there is a cap of 10 expenses. When you hit 10 the button remains but you cannot add any more.

![Image](https://github.com/rubyforgood/casa/assets/14540596/c363bcab-1d84-43a3-8f79-b853191465d2)

We have https://www.stimulus-components.com/docs/stimulus-rails-nested-form/ in the application. It could potentially be of use (unless needed I would suggest using the non-extended version of the stimulus controller). 

**Completion Criteria:**

- [ ] Use some javascript to uncap the amount of expenses 
- [ ] Add a way to remove expenses.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by shacon** [comment]
I would like to work on this!

**Comment by shacon** [comment]
> This issue has been inactive for 240 hours (10.00 days) and will be unassigned after 120 more hours (5.00 days). If you have questions, please
> 
> If you are still working on this, comment here to tell the bot to give you more time

Still working on this!

**Comment by shacon** [comment]
pr for this has updated changes: https://github.com/rubyforgood/casa/pull/5908/files
