### ISSUE TITLE
Improve discoverabilty for creating and editting Court Report Topics

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5775]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

When we implement the Court Report Topics feature several organizations did not realize that they needed to create the topics themselves in their organization settings. 

When no topics are set contact topic section does not appear in the new case form `/casa_cases/:id/new`.

![Image](https://github.com/rubyforgood/casa/assets/14540596/e7662808-8a9e-426f-956c-b13ed4aa624e)

We should make this feature a bit more discoverable. How to do this best can be up to you.

Some ideas:
- If an org has no contact topics set (Note: this is different from no topics active) maybe the contact topics section should have a link to where the could be set by an admin.
- Maybe when a volunteer is viewing it could say: "Your organization has not set any Court Report Topics yet."
- and an admin would see "Visit some_link to set Court Report Topics"

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by josephmsmith** [comment]
Picking this up!
