### ISSUE TITLE
Add Back and Forth Buttons to Case Contact Form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5777]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Please add simple back and forth buttons to the case contact form - can be simple buttons with "<" and ">" like seen on the carousels [here](https://demo.plainadmin.com/carousel).  Please place them to the left of "Step" on each page. If you move from page to page, any changes made should be saved. 

<img width="1690" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/53b9b5c6-6851-4875-8169-fd05455582d6">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-2k5ezv241-Ia2Iac3amxDS8CuhOr69ZA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by priyapower** [comment]
👋🏾 Happy to take this on

The slack link doesn't look like a live link anymore - but will also plan to attend office hours next Tuesday via discord

**Comment by elasticspoon** [comment]
This should be a working link https://join.slack.com/t/rubyforgood/shared_invite/zt-2k5ezv241-Ia2Iac3amxDS8CuhOr69ZA. 

Up to you in terms of what method you prefer. Fork vs get perms but in most open source projects you will be forking so I would suggest that. 

I would also suggest the local install instead of code spaces just cause those are capped at 60hours free a month.

**Comment by priyapower** [comment]
> This should be a working link https://join.slack.com/t/rubyforgood/shared_invite/zt-2k5ezv241-Ia2Iac3amxDS8CuhOr69ZA.
> 
> Up to you in terms of what method you prefer. Fork vs get perms but in most open source projects you will be forking so I would suggest that.
> 
> I would also suggest the local install instead of code spaces just cause those are capped at 60hours free a month.

@elasticspoon - thank you for the suggestions - I am happy to fork and I have done a local install and thank you for the updated slack link!

**Comment by priyapower** [comment]
Commenting for more time

**Comment by priyapower** [comment]
I was ghastly ill and bedridden for a couple weeks - I am official better now and can work on this; however, also happy to hand off

**Comment by priyapower** [comment]
PR is currently in draft. Things to finish/update after power outage is resolved (Chicago hit with major storm):
* 🐛 Back button validates but routes incorrectly after validation is successful
* 🧪 Spec updates (thought I see some potential failing specs on main - this could be a local development issue though, so will capture more details)

**Comment by priyapower** [comment]
@elasticspoon - I realize that my PR was only marked ready for review like 12ish hours ago so I hope I'm not coming off as pushy, more curious about how y'all work - besides the automatic reviewers based on code owners, is there anything else I need to do to get a review?

(I checked the contribution guide and setup readme and I don't see anything about this but I could be missing it)

**Comment by elasticspoon** [comment]
@priyapower Nope! You are good. It usually takes a bit for a review. If there is no movement for like a 5+ days feel free to ask for a review in the casa slack.  

We typically do reviews in batches 1-2 times a week. (I say we but everyone has their own patterns).

**Comment by thejonroberts** [comment]
Resolved in #6048 - single page form
