### ISSUE TITLE
add court report topic answers to case contact export

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5789]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

One of the biggest features that sets our application apart from the competitors is that we do not have any user lock in. We make all user data available for export if they so desire at `/reports`. 

We added the Court Topics feature not long ago but have not made them exportable yet. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/a89c9462-2337-4869-bfee-c5b308ebb986)

Add the court topics to the exports, each topic should be its own column but the filter should be all or nothing (all topics or none).

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by JacobUnleashed** [comment]
Hi, I would like to help with this.
