### ISSUE TITLE
export all data generates a file when the filter modal is close even if close with X rather than generate

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5795]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description
One of the biggest features that sets our application apart from the competitors is that we do not have any user lock in. We make all user data available for export if they so desire at `/reports`.

Here you can filter the columns to export.

![Image](https://github.com/rubyforgood/casa/assets/14540596/29300ce5-6fc4-4998-8a07-4e845d20fb1d)

However, if you exit out of the modal it still generates the report, even if you haven't clicked generate. We should fix this.

### Criteria for Completion

- [ ] Ensure that if a user open the report modal on `reports` and then exits it without intending to generate a report report does not get generate
- [ ] Unless it is not possible please change this modal to use the modal view component https://github.com/rubyforgood/casa/tree/main/app/components/modal

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Naraveni** [comment]
Can I work on this

**Comment by Naraveni** [comment]
Can I work on this please

**Comment by elasticspoon** [comment]
@Naraveni go for it

**Comment by Naraveni** [comment]
i working on it

**Comment by Naraveni** [comment]
I already raised the pr

**Comment by Naraveni** [comment]
https://github.com/rubyforgood/casa/pull/5866
