### ISSUE TITLE
Alert messages disappear quickly and cause distracting page content movement.

### ISSUE THREAD

**Issue by abachman** [rubyforgood/casa#580]
**What is the problem, and what should happen instead?**

Notification flash alert messages move all page content when they disappear making early clicks risky and they often disappear too quickly to read. 

Some design recommendations: 

- Alerts should float without disturbing or page layout content.
- Alerts should never cover important content.
- Alerts should always last long enough for people to read. 
- If multiple alerts appear on a page, the newest should be at the top.

**Screenshots of current behavior, if any**

Some examples: 

![image](https://user-images.githubusercontent.com/13002/90965768-1adc5d00-e499-11ea-8fb0-ad1a89aa619c.png)

![image](https://user-images.githubusercontent.com/13002/90965775-27f94c00-e499-11ea-96dd-11e3961886d2.png)

**Comment by compwron** [comment]
This is fixed
