### ISSUE TITLE
Logging out shows "You need to sign in before continuing." warning message at top of screen.

### ISSUE THREAD

**Issue by abachman** [rubyforgood/casa#581]
**What is the problem, and what should happen instead?**

Logging out shouldn't attempt to perform any actions that would cause a "you need to sign in" warning to appear.

Warnings when a user didn't do anything wrong are unnecessary negative feedback.

**Steps to reproduce:**

- sign in as a user
- use log out button to sign out
- observe warning message

**Comment by littleforest** [comment]
Also, when going to root path, get unnecessary "You need to sign in or sign up before continuing" message.

**Comment by littleforest** [comment]
Is the `all_casa_admins` model being used, or can I also delete the `devise_for :all_casa_admins` line in the route file? It looks like STI is being used instead for the different user roles?
