### ISSUE TITLE
refactor volunteer case contact form to use new submit button component

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5819]
## What type(s) of user does this feature affect?

![Steve Ballmer DEVELOPERS DEVELOPERS DEVELOPERS](https://i.makeagif.com/media/7-29-2015/OA5hkn.gif)

## Description

In this PR (https://github.com/rubyforgood/casa/pull/5793) we modified the case contact creation process (`/case_contacts/:id/form/details`) to not show the final expenses page if a user had no expenses to show. 

As part of that we introduced a Submit button component. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/b26ae3a1-d160-4be5-a5fa-4196527e678c)

### Criteria for Completion

- [ ] Refactor the rest of the form to use the same component.
- [ ] Refactor a minor stylistic nit https://github.com/rubyforgood/casa/pull/5793#discussion_r1630632974
- [ ] Anything else that you notice in that form that could use refactoring

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by iamronakgupta** [comment]
@elasticspoon can you please assign this to me?
