### ISSUE TITLE
Add Other Duties to the Seeder

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5844]
## Description
Make [our seeder](https://github.com/rubyforgood/casa/blob/main/db/seeds/db_populator.rb) create "other duties" records for test data.  

Only volunteers are allowed to create other duties so make sure no other kind of user has any.  

Make sure the seeder prints out how many other duties records were created.  

Show that your pr works. Just some screenshots or text will be fine. No need to write tests.  

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by gaurijo** [comment]
Hi! I'd like to take on this issue

**Comment by elasticspoon** [comment]
@gaurijo go for it!

**Comment by gaurijo** [comment]
Clarifying question - should the functionality be for volunteers for each casa org, or just generally for volunteers? Basically I'm wondering if I should be specifying `casa_org` as a param in this method.

`def create_other_duties(casa_org)` 

vs

`def create_other_duties`

**Comment by gaurijo** [comment]
I've got a PR ready for review [here ](https://github.com/rubyforgood/casa/pull/5903):)
