### ISSUE TITLE
Surface common available filters for case contacts

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5847]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

We recently added a feature for drafts of case contacts (`/case_contacts`). 

![Image](https://github.com/rubyforgood/casa/assets/14540596/2ca93a3d-2c20-4fe9-9bc8-98a4bd3b1e2e)

This was added to make sure that volunteers would not lose progress towards their completion of the form. However, volunteers are having issues with accidentally creating drafts and those polluting their case contact screen.

![Image](https://github.com/rubyforgood/casa/assets/14540596/c09a0c9a-2a3f-43f9-a650-9a87350f1c48)

However, we have filters that would allow users to hide those drafts.

![Image](https://github.com/rubyforgood/casa/assets/14540596/47390c15-48dd-41ea-b7f4-452c7d7e1e41)
![Image](https://github.com/rubyforgood/casa/assets/14540596/98e6cea2-f881-43c8-83db-f38062c7723d)

Volunteers were not aware that they could do that, thus, we should surface this functionality better. Lets show the most commonly used filters while the menu is still folded. Something like (THIS IS JUST AN EXAMPLE. ITS UGLY. PLEASE MAKE IT NICER :heart:):

![Image](https://github.com/rubyforgood/casa/assets/14540596/f8e2f599-a8a6-414e-9535-2e0375d8df41)

## Criteria for completion

- [ ] show hide drafts in folded state
- [ ] show sort order in folded state
- [ ] show clear and filter buttons in folded state
- [ ] write some system tests

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-2k5ezv241-Ia2Iac3amxDS8CuhOr69ZA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by mononoken** [comment]
Can I work on this one?

**Comment by elasticspoon** [comment]
@mononoken all you!

**Comment by mononoken** [comment]
Still working (─‿‿─)
