### ISSUE TITLE
Draft case contacts for the seeder

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5862]
## Description
Currently, all case contacts are marked as draft by [the seeder](https://github.com/rubyforgood/casa/blob/main/db/seeds/db_populator.rb). 
For each case make most of its case contacts completed and leave between 0 and 1 draft for each.

A recent bug caused the seeder to make case contacts that are not displayed. Make sure your branch includes [this pull request](https://github.com/rubyforgood/casa/pull/5861)

## Screenshots of current behavior, if any
![local site after reseeding](https://github.com/rubyforgood/casa/assets/8918762/40d7ef29-2f21-4acc-9b37-36b1552017b9)

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Kerman07** [comment]
I can work on this.

**Comment by elasticspoon** [comment]
@Kerman07 all you
