### ISSUE TITLE
Bug: 2 clicks required to close the case contact filters.

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5864]
## Impacted User Types
 - volunteers

## Current Behavior
After submitting the filters on the case contact page, 2 clicks are required to close the filters
![image](https://github.com/rubyforgood/casa/assets/8918762/f1da5c1f-8cea-4a18-b18b-73d2aa06d6be)

## Expected Behavior
Only one click closes the filters

## How to Replicate
ex: 
1. Log in as volunteer
2. Go to case contacts page
3. Click "show/hide" filters
4. Click the grey filter button at the bottom of the filters to submit the form
5. Click "show/hide" once

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Naraveni** [comment]
can I work on this

**Comment by elasticspoon** [comment]
@Naraveni all you
