### ISSUE TITLE
Add anchor links to Edit Org page for faster navigation and nest them in sidebar

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5887]
## What type(s) of user does this feature affect?
 - admins

## Description

If you look at the page to make changes to an organization (`/casa_org/:id/edit`) it is suuuuuper long. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/faf0801b-038f-4bfb-ac20-77b33d084a95)

If you want to make changes to something at the very end it is a lot of scrolling, even worse if you make a change then have to scroll all the way back down.

We had the idea of breaking the page up into smaller pages BUT after discussion we think that we can achieve a similar effect with much less work by simply making the headers of each section anchors.

#### For example: 

On the page https://github.com/rubyforgood/casa/wiki/Components

Form validation components can be linked to directly via https://github.com/rubyforgood/casa/wiki/Components#form-validation-components

### Criteria for Completion

Lets break this page up into reasonable sections and nest them in a menu. 

- Each section (`h2` heading) should have its own respective anchor and link to that anchor in the sidebar

![Image](https://github.com/rubyforgood/casa/assets/14540596/e4088d79-1381-4f6d-b69d-060456424979)

- [ ] Create anchor and sidebar link for Contact Types
- [ ] Create anchor and sidebar link  for Court Details 
- [ ] Create  anchor and sidebar link for Organization Details
- [ ] Create anchor and sidebar link for Learning Hours 
- [ ] Create  anchor and sidebar link for Case Contact Topics 

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by MclPio** [comment]
Hello, can I address this after some clarification in slack? I already sent my question.

**Comment by elasticspoon** [comment]
@MclPio to answer your questions

> Take out 'Edit Organization' from the collapsible 'Group Actions' and make it its own item in the sidebar that is now also collapsible with links to requested pages as per issue description.

Correct. Edit Organization could potentially be a link to the base page and then nest links to anchor tags (you should try both ways and see how the UX makes more sense) 

> Change most of the partials to actual pages in the app/views/casa_org folder.

No longer applies

> I will need to also edit the routes and make nested URLs for the edit pages; not sure how to approach this right now. What I am thinking is have each page with links like this: http://localhost:3000/casa_org/1/edit/contact_types

No longer applies. The links will be in the form `/casa_org/1/edit#contact_types`

> What about the link in the profile drop-down?

No longer applies (I think?) I would keep as is.

**Comment by MclPio** [comment]
will begin working on it tomorrow. Thanks for clarification!

**Comment by MclPio** [comment]
Work In Progress
