### ISSUE TITLE
fix VolunteersController#edit N+1 issues

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5894]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/5ebf4b86-2f24-46d1-94da-129efef60c43

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Naraveni** [comment]
hey, can I work on this

**Comment by elasticspoon** [comment]
Go for it

**Comment by ElisaRmz** [comment]
Hi! Could I work on this?
@elasticspoon

**Comment by elasticspoon** [comment]
@ElisaRmz absolutely. lemme know if you have any issue with the scout link

**Comment by ElisaRmz** [comment]
@elasticspoon, I can't access to the link of the Description: 
https://scoutapm.com/shares/5ebf4b86-2f24-46d1-94da-129efef60c43

**Comment by elasticspoon** [comment]
https://scoutapm.com/shares/7590bdb4-042d-438b-b330-bf20ea1874e1 try that

**Comment by ElisaRmz** [comment]
It works, thanks!

**Comment by ElisaRmz** [comment]
Working on it

**Comment by ElisaRmz** [comment]
@elasticspoon, I can't access this link https://scoutapm.com/shares/7590bdb4-042d-438b-b330-bf20ea1874e1,
Does it work only for some time?

**Comment by elasticspoon** [comment]
Interesting. We are on some free version of scout so its possible that it just expired. https://scoutapm.com/shares/cf2dc01b-92fb-42a9-86e5-d700318139a6

**Comment by ElisaRmz** [comment]
Working on it
