### ISSUE TITLE
Bug: Too many error messages for blank dates while creating a casa case

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5921]
## Impacted User Types
 - admins

## Current Behavior
This appears after trying to make a new casa case with a blank court date
![image](https://github.com/user-attachments/assets/fc12c097-36be-4a7c-a52b-c90e2ae78942)
This appears after trying to make a new casa case with a blank birth month and year
![image](https://github.com/user-attachments/assets/ecbcbe85-6458-4e36-b81d-3b5ae59cb7e9)

## Expected Behavior
Only the top error message is shown when the date is left blank for each type of date.

## How to Replicate
1. - Log in as an admin.
2. - Click "📁 cases" in the left sidebar menu.
3. - Click "+ New Case"
4. - Enter a case number
5. - Click "+ Create CASA Case"

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by ElisaRmz** [comment]
Hi! I want to fix this bug.

**Comment by elasticspoon** [comment]
@ElisaRmz all you!

**Comment by ElisaRmz** [comment]
Hi @elasticspoon, could you give me permission to create a branch? 🙏🏻

**Comment by elasticspoon** [comment]
@ElisaRmz you got it

**Comment by ElisaRmz** [comment]
@elasticspoon could you check again? I'm still getting the error

**Comment by elasticspoon** [comment]
> @elasticspoon could you check again? I'm still getting the error

Sorry I forgot to mention you have to accept the invite. did you get it? its gonna go to your email / maybe when you are on rubyforgood/casa github page

**Comment by ElisaRmz** [comment]
Thanks! I have received the invitation and it already works. 🙂
