### ISSUE TITLE
add button to "create another" case contact when submitting case contact

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5925]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

Often times our volunteers will create case contacts (`/case_contacts/:id:/form`) in bulk after the actual contact. We would like to improve the process of creating bulk contacts for them.

Currently, after a case contact is created the land back on the Case page and have to restart that process from scratch. Lets implement something like linear or jira when creating multiple issues.

![Image](https://github.com/user-attachments/assets/8882c97e-61be-416a-92f1-69a249b3292e)

When a user is on the final page submitting their case contact they should have the option to "Create Another". This will take them right back to the start of the form after creating the Case Contact so they can start directly on another contact.

This new case contact should retain some of the values of the case contact that gets created such as the case with which it is associated but everything else should get cleared out.

## Criteria for Completion

- [ ] Add a "Create Another" toggle or checkbox on the final page of the `/case_contacts/:id/form`
- [ ] Redirect the user back to the first page of the case contact form if it is submitted with  "Create Another" selected
- [ ] After redirection makes sure all the fields are cleared out except the case  
- [ ] Add some sort of a popup or descriptive tooltip so that users have a better idea of what the button does
- [ ] case contacts have a `jsonb` `metadata` field. when a new case contact is created store whether it was created via "Create Another" or not so that we have metrics

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by thejonroberts** [comment]
I am looking at this, have the first three criteria roughed out & working.
