### ISSUE TITLE
Bug: Broken calendar link in README

### ISSUE THREAD

**Issue by kyle-apex** [rubyforgood/casa#5962]
## Impacted User Types
 - developers

## Current Behavior
When I click the "our google calendar" link, it takes me to the incorrect relative url

## Expected Behavior
When I click the link, it takes me to the bit.ly url

## How to Replicate
Click the "our google calendar" link in README

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by Deepakchowdavarapu** [comment]
I would like to work on this issue.
