### ISSUE TITLE
Notes field for case_contacts

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#600]
Part of epics #3, #4, #105

**What type of user is this for? [admin/supervisor/volunteer/all or All CASA Admin]**
mostly volunteers, but also accessible by admins and supervisors

**Where does/should this occur?**
On the Create Case Contact page accessible by volunteers, admins, and supervisors. 

**Description**
On the Create Case Contact page, there should be an open text field labeled Notes. 

The field should be five lines high, and should contain preview text providing guidance to volunteers for what to put here. This is what it should say:

_Please refer to individuals by their roles instead of by their names. Ex: My supervisor joined me for a call with the social worker to discuss my youth._

This field should be all the way at the bottom of the page underneath **Want Driving reimbursement** and above the _submit_ button.

Relates to issue #604

**Comment by GuillermoCoding** [comment]
Hello, picking this up!
