### ISSUE TITLE
Make it possible to run seed with a lot less stuff

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#601]
Right now “rake db:seed” makes a lot of data. It would be nice to have a command rake:db:seed:little” (or similar, no preference) which makes less data, because we have volunteers who are currently inconvenienced by how much data there is locally - makes server operations slow 

note: `rake db:seed:replant` deletes all data and re-runs `seed.rb`

Could have it check Rails Env and do different data-volumes depending on which env you’re in?

**Comment by keithrbennett** [comment]
Currently the seeds.rb file contains:

```
# number of volunteer users and casa cases to generate
VOLUNTEER_USER_COUNT = 100
CASA_CASE_COUNT = 150
SUPERVISOR_COUNT = 5
```

These numbers are very small for a data base, and if the system is running slowly then I think we have a different problem. @Zrrrpy Could you say more about exactly what is slow? Maybe we need to look at those areas of the application to see why.

**Comment by compwron** [comment]
> Currently the seeds.rb file contains:
> 
> ```
> # number of volunteer users and casa cases to generate
> VOLUNTEER_USER_COUNT = 100
> CASA_CASE_COUNT = 150
> SUPERVISOR_COUNT = 5
> ```
> 
> These numbers are very small for a data base, and if the system is running slowly then I think we have a different problem. @Zrrrpy Could you say more about exactly what is slow? Maybe we need to look at those areas of the application to see why.

@keithrbennett We have a few n+1 queries (loading all cases, loading all volunteers, loading all case contacts) when a supervisor or admin loads their dashboard. I believe that these are the cause of the slowness. We have the `bullet` gem which will tell us about these, and we can also watch the output of `rails server` which shows the sql queries when running locally and watch for repetition. 

The majority of the rows in the database is in the `case_contacts` table- only ~10k rows or so I believe (there is some randomness in seed) but enough to gum up the works combined with one or more n+1 queries.

Separately, slowness has been reported in the tests in docker and in windows but not ion osx- I suspect our capybara driver but I have no particular evidence for that.
