### ISSUE TITLE
Make "a. Was contact made?" defaulted to "Yes" on Case Contact Form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#6016]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Please make "a. Was contact made?" defaulted to "Yes"

## Screenshots of current behavior, if any
<img width="586" alt="image" src="https://github.com/user-attachments/assets/fd888dc2-2d09-4119-8424-836ba9bb9d7c">

## How to access the Case Contact Form
- Go to "Case Contacts" on left nav bar
- Click "All"
- Click "+ New Case Contact" button

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by DariusPirvulescu** [comment]
Hello, I can take this issue if that's ok.

**Comment by bcastillo32** [comment]
> Hello, I can take this issue if that's ok.

Thank you! Just assigned it to you! 🙏🏼
