### ISSUE TITLE
Make linter enforce line length on ERB files

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#602]
Related to https://github.com/rubyforgood/casa/issues/489

`bundle exec erblint --lint-all --enable-all-linters --autocorrect` (see readme)
https://github.com/Shopify/erb-lint which uses https://github.com/Shopify/better-html

**Comment by compwron** [comment]
We added some linters but this wasn't one of them yet. This still needs doing. I'm going to unassign this because we're not actively working on it. Feel free to work on this! :)
