### ISSUE TITLE
active volunteers without supervisors is missing table styling

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#6025]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

On the page `/supervisors` the table that shows active volunteers without supervisors is missing the styling of other tables as well as a proper table name.

![Image](https://github.com/rubyforgood/casa/assets/14540596/bbbe3465-7707-4c32-a2fa-5afcf5e7ae11)

Make 1 more like 2.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by leevic31** [comment]
I would like to work on this one

**Comment by elasticspoon** [comment]
all you
