### ISSUE TITLE
Improve timezones on sent emails page on org settings as admin

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#6026]
## What type(s) of user does this feature affect?
 - admins

## Description

Under `/casa_org/:id/edit` we have a table that shows all sent emails. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/afc1658e-c4f6-4405-b9c0-1747a4f68624)

The times on this table are all in UTC. The Admins would love it if you could change it to use a more reasonable timezone. 

I believe there are a few helpers in the application that set the timezone and it should be getting set as a session token as well.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by DariusPirvulescu** [comment]
Hi, I can maybe look into it. 
But about "a more reasonable timezone", does that mean the user's local timezone?
For this, I found the [User::TimeZone](https://github.com/rubyforgood/casa/blob/main/app/controllers/concerns/users/time_zone.rb) concern, which reads the `:browser_time_zone` cookie. I think this might work.

**Comment by elasticspoon** [comment]
@DariusPirvulescu yea that exactly what we are going for. And if that can't be found EST is a reasonable fallback (most of our users in in the DC area)

**Comment by DariusPirvulescu** [comment]
Still working on it.

**Comment by DariusPirvulescu** [comment]
PR open and ready for review.
