### ISSUE TITLE
Refactor "Was contact made?" to checkbox on Case Contact Form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#6055]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Please change the current "Was contact made?" selection to a checkbox as shown in the[ figma file](https://www.figma.com/design/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?node-id=2201-3486&node-type=canvas&t=sshkxICZ2hwE6Eou-0).

## Screenshots

Current(old)
<img width="417" alt="image" src="https://github.com/user-attachments/assets/a46686e1-3b32-4965-8f43-7af6139b0fe5">

Desired(new from figma file)
<img width="254" alt="image" src="https://github.com/user-attachments/assets/14002f91-91ac-45a4-b325-799eef8b5b81">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

## How to access Case Contact form
- "Case Contacts" on left navbar
- Click "All"
- Click "+ New Case Contact" button

### Questions? Join Slack and message us in the proj-case-contact-refactor channel or message here! 

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by felicia22** [comment]
Hi, I would love to contribute to this issue as well for a class project. Could you please assign this issue to me as well as help point me in the right direction (as in any files to look at, etc)?

**Comment by elasticspoon** [comment]
Same deal on this issue as the previous one unfortunately :frowning:

**Comment by thejonroberts** [comment]
Resolved in #6048
