### ISSUE TITLE
Refactor "Select All Contact Types" to checkbox style on case contact form

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#6056]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
Please change the current Select All Contact Types dropdown on case contact form to checkbox style as seen in this [figma file](https://www.figma.com/design/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?node-id=2201-3486&node-type=canvas&t=sshkxICZ2hwE6Eou-0)

## Screenshots of current behavior, if any
Current(old)
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/d56d328d-f8e4-4acf-a053-a28579cac8b6">

Desired(new from figma file)
<img width="681" alt="image" src="https://github.com/user-attachments/assets/9d78aabf-62c0-43cc-be40-966aa58e7f62">

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

## How to access Case Contact form
- "Case Contacts" on left navbar
- Click "All"
- Click "+ New Case Contact" button

### Questions? Join Slack and message us in the proj-case-contact-refactor channel or message here! 

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by felicia22** [comment]
Hi, I would love to contribute to this issue for a class project. Could you please assign this issue to me as well as help point me in the right direction (as in any files to look at, etc)?

**Comment by elasticspoon** [comment]
Hey @felicia22! Thanks for the interest, this particular issue is actually probably going to be closed by an existing PR https://github.com/rubyforgood/casa/pull/6048 whenever we get that reviewed and merge so I would suggest you pick something else from the backlog. 

This list https://github.com/orgs/rubyforgood/projects/15/views/1 provides a pretty good idea of what needs to be done, etc.

**Comment by thejonroberts** [comment]
Resolved in #6048
