### ISSUE TITLE
notification when saving notes

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#618]
Part of epics #3, #4, #105

**What type of user is this for? [volunteer/admin/supervisor/all or All CASA Admin]**
all, but mostly volunteers

**Where does/should this occur?**
On the Edit Case Contact page AND on the Create New Case Contact page

**Description**
When a user tries to save a case contact containing text in the notes field, clicking the submit button at the bottom of the page should trigger a dialogue box reading,

"Please double check your notes to ensure they don't contain any identifying details about your youth or anyone else."

with a button that says "okay" and closes the dialogue box.

Dependent on issue #600

**Comment by haoxianZ** [comment]
Hello! I am new to this project and I would like to start contributing by working on this!

**Comment by compwron** [comment]
@haoxianZ Welcome! You can work on this :)
You can ask questions here or in the #casa channel on the ruby for good slack :) https://rubyforgood.herokuapp.com/

**Comment by compwron** [comment]
Hi @haoxianZ ! How are you doing with this issue? Are you still working on it? Please let me know :)

**Comment by haoxianZ** [comment]
Hi, Sorry, last week was quite busy, is it OK I get this done by end of next week? if this is an urgent issue, then please feel free to take over.

**Comment by compwron** [comment]
@haoxianZ That's good :)
