### ISSUE TITLE
automated email notification for volunteers reminding them that court report is due

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#620]
AS a **volunteer**,
I WANT to receive an email notification one week before my court report due date,
SO THAT I remember to submit my court report to my supervisor. 

**Volunteer receives email notification if all of the following conditions are met:**
- Volunteer is assigned to at least one `casa_case` with an upcoming court date _and_ a corresponding court report due date,
- It is seven calendar days before the court report due date,
- court report submitted = false

**Email Content**

- subject line: Your court report is due on: `court_report_due_date`

- body: 

`volunteer` `display_name`, 

This is a reminder that your next court report is due on `court_report_due_date`. Please submit your court report to your supervisor no later than this date. 

You can generate a court report by clicking on "Generate Court Reports" in your volunteer portal. Log in here to get started: https://www.casavolunteertracking.org

Please email your supervisor directly if you need further assistance.

**Comment by ChaelCodes** [comment]
I'm not claiming this issue, but I have some questions about the mailer:
1. How do you want to schedule this? Rake task, Redis/Sidekiq/DelayedJob, or ActiveJob?
2. Should the mailer link to the Generate Court Reports page?

**Comment by Zrrrpy** [comment]
1. @compwron, @littleforest or @jmkoni may have thoughts on this!
2. It would be great to include a link to the Generate Court Reports page, if possible! (It did not exist at the time this ticket was opened.) However, I'd consider this a "nice to have", so if it's a big lift it's okay to forgo. I'd like to hear @compwron's thoughts on this re: security and how we should handle directing the volunteer to that page (whether we log them in automatically upon clicking the link or if we require them to manually log in before viewing). 

Thank you for your interest and for asking great questions, @ChaelCodes! 😄

**Comment by jmkoni** [comment]
@ChaelCodes  we use heroku scheduler, so if you create a rake task, we can schedule it every day 🙂
