### ISSUE TITLE
All CASA Admin can log out

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#632]
Part of epic #527

**What type of user is this for? [supervisor/volunteer/admin/all or All CASA Admin]**
All CASA Admin

**Where does/should this occur?**
In the All CASA Admin dashboard (dependent on #628)

**Description**
All CASA Admin should be able to log out like any other user type. There should be a logout button in the upper right hand corner of the dashboard. Log in to another user account type to see how it looks. <a href="https://github.com/rubyforgood/casa/blob/master/db/seeds.rb">Instructions for logging in here.</a>

**Screenshots**
It should look like this:
![Screen Shot 2020-08-31 at 7 00 34 PM (2)](https://user-images.githubusercontent.com/62810851/91786406-67701880-ebbc-11ea-9823-6cc7e573a265.png)

Relates to issues: #628 #627

**Comment by abachman** [comment]
Good news! This one was closed by 75fb302ff45
