### ISSUE TITLE
handle error caused by incorrectly formatted import file

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#636]
Part of epic #528

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
admin

**Where does/should this occur?**
On the import page

**Description**
_Current behavior:_ user imports incorrectly formatted file, and get an unhandled error message (reference screenshot below)

_What should happen instead:_ User imports incorrectly formatted file, this prompts a dialogue box reading:

Looks like this .csv contains invalid formatting. Please download an example .csv for reference and try again.

With an "okay" button that closes the dialogue box and returns user to the import page.

_Invalid formatting = column headers do not match column headers in example .csv's <a href="https://casa-r4g-staging.herokuapp.com/imports">on this page</a>_

**Screenshots**
This is how it looks now:
![Screen Shot 2020-09-02 at 6 50 10 PM](https://user-images.githubusercontent.com/62810851/92067184-8c00f780-ed58-11ea-9820-7232a9f55062.png)

**Comment by Zrrrpy** [comment]
Note to self that the definition of _invalid formatting_ may include more than what's defined above.

**Comment by compwron** [comment]
Who is working on this?

**Comment by alindeman** [comment]
I'll take a look :+1:

**Comment by Zrrrpy** [comment]
@alindeman yes! If you [download a report](https://casa-r4g-staging.herokuapp.com/reports) as an Admin and then try to import it, that should trigger this error.

**Comment by alindeman** [comment]
@Zrrrpy I downloaded a report from the link for 2020-08-06 - 2020-09-06 and attempted to import it as a volunteer CSV, supervisor CSV and cases CSV. In each case, I received an error (as a flash message), but the app did not crash. Is it possible this one got resolved inadvertently, or am I still missing a step to reproduce it?

**Comment by compwron** [comment]
I double-checked and I agree that the exception isn't thrown in this case It must have been somehow fixed 😅

**Comment by compwron** [comment]
That error could be SO much prettier tho

**Comment by alindeman** [comment]
> That error could be SO much prettier tho

Good point. Do you have ideas on how it should look? As it stands today, it could also become quite large if there are a lot of invalid records.

**Comment by compwron** [comment]
![Screen Shot 2020-09-06 at 8 41 45 AM](https://user-images.githubusercontent.com/578159/92329533-d31f0f00-f01c-11ea-9b23-8338d61d5435.png)

**Comment by compwron** [comment]
Please hold off on this until https://github.com/rubyforgood/casa/pull/624 is merged

**Comment by keithrbennett** [comment]
#624 is now merged.
