### ISSUE TITLE
better tables on mobile

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#646]
Does anyone have ideas on how to make tables look good on mobile view? I want better mobile UI :) 

 Don’t use an actual table 
But use bootstrap with different column sizes based on size 

 No design system per se, just bootstrap, some datatables.js, emoji feels, and the dream Plz send halp 

there are some RWD techniques for displaying tables at different viewport sizes, so that the data can stay in tabular format

**Comment by armahillo** [comment]
I can work on this one later but if someone else is wanting to work on it go for it!
