### ISSUE TITLE
Pull header and footer organization details from CasaOrg when I am signed in

### ISSUE THREAD

**Issue by abachman** [rubyforgood/casa#647]
**Description**

Right now, header and footer are hardcoded with PG CASA's branding. 

We'll need to store and retrieve:

- a header logo
- header title (organization name?)
- footer copyright (maybe same as header title?)
- footer address (one liner)
- footer logo (maybe same as header logo?)
- links to organization's resources incl. link text + href

**User stories**

Putting on my product hat 🎩 . 

```gherkin
GIVEN I am a Volunteer for PG Casa
WHEN I visit my home page
THEN I should see "PG CASA" in the header
```

```gherkin
GIVEN I am a Volunteer for San Francisco CASA
WHEN I visit my home page
THEN I should see "San Francisco CASA" in the header
```

**Screenshots of current behavior, if any**

The parts circled in orange.

![Screen Shot 2020-09-04 at 8 46 47 PM](https://user-images.githubusercontent.com/13002/92293245-fc8e4c80-eeef-11ea-8e09-e3cbd10e10b8.png)

**Comment by keithrbennett** [comment]
One way to do this would be to have a `tenant.yml` file containing these data pieces. Perhaps a `CASA_TENANT_CONFIG` environment variable could override this filespec?

I could probably do this, but would need some help figuring out where in Rails some of this stuff goes (e.g. how would the config data be exposed/available to the application after loading).

**Comment by compwron** [comment]
@keithrbennett My two cents- I want to build towards tenant config changes not requiring a production deploy. Adding a new tenant should be done via the UI by an `AllCasaAdmin`. Intermediate steps might be needed though, because we haven't built that yet. 
@abachman is the official Multi Tenant Opinion Lead so I'll leave it to y'all to discuss. :)

**Comment by abachman** [comment]
We'll want to pull this from a database table, I think. The driving goal is that these details will be self-managed by the organizations.

The organization editing form can come later, but this issue should discover the DB model that will drive this behavior. Then the editing form will just be a basic CRUD wrapper on the data we already know we need to manage.
