### ISSUE TITLE
Admin can customize basic appearance of their org's instance

### ISSUE THREAD

**Issue by abachman** [rubyforgood/casa#648]
**What type of user is this for? volunteer/supervisor/admin/all**

Admin **ONLY**

**Where does/should this occur?**
In the Admin dashboard accessible by upper right hand drop down menu where Admins can currently access reports, system imports, etc. 
Corresponding text in the dropdown menu should read "Customize"

**Description**
Build a form for Admins to customize the appearance of their corresponding org's CASA instance: 

- Your CASA's logo (file upload for header and footer)
- Your CASA's name (text field with the preview text: _This should be the name of your CASA Org_) – this will populate in the header and footer
- Your CASA's address (for footer)

Relates to issue #647 (closed)

**Comment by Zrrrpy** [comment]
@abachman I revised this and consolidated quite a bit – I think we're going to remove the org resource links from the footer and replace them with two static links that don't need to be customized: one to Ruby for Good, one to a bug reporting form. I'll link to the related issue here once it's filed.
