### ISSUE TITLE
README Refactoring to Better Separate OS-specific from OS-agnostic information

### ISSUE THREAD

**Issue by keithrbennett** [rubyforgood/casa#649]
**Description**

I wrote up the LINUX_SETUP.md file but forgot to refer to it in README.md, so someone reading there for instructions for installing on a Linux host may never find out that there are more detailed instructions for them there. Since there is also a Docker instruction file, I suggest we remove the remaining Linux and Docker information from README.md, and move the Mac OS instructions to a new file (maybe MAC_OS.md), and refer and link to the three of them similarly in README.md.

**Existing file(s) needing changing**
README.md

**New file(s) needing creating**
MAC_OS.md

**Comment by compwron** [comment]
I agree that this sounds like a good idea :)

**Comment by talentedunicorn** [comment]
@keithrbennett can I have this one :)

**Comment by keithrbennett** [comment]
Sure, I've assigned it to you. Thank you!

**Comment by keithrbennett** [comment]
This issue is a lot more complex than it appears at first glance, and it requires a lot of detail orientation and patience (which is why I have not addressed the issue yet myself). The meat of this issue is studying the text, extracting, clarifying, and sometimes copying. It is not a simple cut and paste; there are some references to specific OS's, and some to multiple; OS-specific content needs to be extracted, but without resulting in omissions of important information for other OS's.

**Comment by compwron** [comment]
@jmkoni I notice that this issue is "in progress" on the board. Why did you unassign @talentedunicorn  ? It sounds like I missed a discussion somewhere? @keithrbennett it sounds like you have context on this. Is this intended to be "in progress" and if so, who is it assigned to? :)

**Comment by keithrbennett** [comment]
@compwron The context of this is the discussion on the PR at https://github.com/rubyforgood/casa/pull/921. It was not originally clear from the issue description that this was not a simple edit (I have added my comment above to clarify that). It's not really in progress anymore, though I hope to look at this some time in the not too distant future if no one beats me to it.

**Comment by compwron** [comment]
Is this done?

**Comment by keithrbennett** [comment]
Sorry, it is not in progress, I have not started it yet.

I'm not assigned to it yet, which is good, because that leaves it open for
someone else to do if they want.

**Comment by keithrbennett** [comment]
Sorry, I don't know when I'll be able to get to this. Feel free to close it.
