### ISSUE TITLE
Missing error explanation when editing date occurred to the future as an admin

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#654]
![Screen Shot 2020-09-05 at 8 29 04 AM](https://user-images.githubusercontent.com/578159/92308372-f335cc00-ef51-11ea-874b-31e1bae77498.png)

**Comment by Zrrrpy** [comment]
This is accompanied by a textual error message, but it only flashes briefly at the top of the page and then disappears. I think this is captured by #534 so going to close, feel free to re-open if you think necessary @compwron. ✅
