### ISSUE TITLE
[BUG] new case contact contact made defaults to false. It should not have a default

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#673]
[BUG] new case contact contact made defaults to false. It should not have a default
Please also write a test for this to make sure it doesn't break again (for all no-default fields)
This happened while logged into staging with volunteer2

![Screen Shot 2020-09-05 at 2 52 57 PM](https://user-images.githubusercontent.com/578159/92314068-b4226d80-ef87-11ea-957b-77af0f855cf8.png)

**Comment by jmkoni** [comment]
Ooh I think this might’ve been me and @mecastelom. One of us can fix it.
