### ISSUE TITLE
Do not show case as assignable to a volunteer already assigned to it

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#677]
Do not show case as assignable to a volunteer already assigned to it

![Screen Shot 2020-09-09 at 6 27 42 PM](https://user-images.githubusercontent.com/578159/92671053-2f5a8b00-f2ca-11ea-895a-cb1949b3fb30.png)

**Comment by ErinClaudio** [comment]
Attempted to solve the issue with no luck.

`.reject {|cc| cc.volunteers.include?(current_user) }`
Did not work
