### ISSUE TITLE
Admin can not import volunteers without display names

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#691]

**Comment by strangrjrjr** [comment]
I have a plan for resolving this issue via the `volunteers_controller`, but I need a little nudge to provide informative errors to the user. I've added validations to prevent creation of a volunteer record when the `email` or `display_name` are empty.

Where do the following errors come from?

![Screen Shot 2020-09-06 at 10 07 47 AM](https://user-images.githubusercontent.com/5456014/92331123-1e3f1f00-f029-11ea-8687-d131b552b704.png)

1. I'd like to use the mechanism of display to inform the user that both fields must have content.
2. Looks like there's some incorrect checking of fields currently, the page should only display errors for fields present within.

**Comment by compwron** [comment]
Please avoid working on import functionality until #624 is merged

**Comment by keithrbennett** [comment]
#624 is now merged.

**Comment by keithrbennett** [comment]
Interesting question about where is the validation specified, I would have expected it in the model but don't see it there. I noticed that null is set to false in the schema.rb file -- does that somehow result in the validation? For example:

```
    t.string "email", default: "", null: false
```

**Comment by abachman** [comment]
Yes, `null: false` at the DB level is the only way to _guarantee_ that a blank/null value will never be accepted. Rails validations can be bypassed fairly easily.

Rails validations, though, should also be used so that the DB restrictions are reinforced by the model and clear to everyone involved.

**Comment by strangrjrjr** [comment]
Would it make sense to put something like `validates :email, presence: true` in the `User` model or the `Volunteer` model? I was thinking `User`; wouldn't all types need an email and a display name?
