### ISSUE TITLE
new header for case contacts

### ISSUE THREAD

**Issue by maggie-larkin** [rubyforgood/casa#696]
Part of epic #532 (<a href="https://udw1g1.axshare.com/#id=v15n5y&p=volunteer_experience&g=1">see complete mockups here</a>)

### Context:
- @taysvea redesigned the volunteer portal! Yay having a designer 
- From her research, it seems very very rare to have two cases at a time
- She's made a whole comp but some of the things on this mock up are unverified yet
- This story just deals with the header area of the table

### Acceptance Criteria:

As a volunteer 
I want to navigate this system easily
So I can fill out my case contacts efficiently 

GIVEN I am logged in as a volunteer
WHEN I'm viewing Case Contacts 
THEN I see a table header row that displays: 
- [ ] whether the youth is transition aged or not:
caterpillar : non `transition_aged_youth` (under 14 years)
butterfly : `transition_aged youth` (over 14 years)
- [ ] case number
- [ ] next `court_date`
- [ ] `court_report_due_date`
- [ ] court report status (i.e. submitted, in review, complete - see #806)
- [ ] a dropdown menu to "Filter by" (currently displays in sidebar in mockup below, ignore this)
- [ ] a button to add a new `case_contact`

### Screenshots of new behavior
![Screen Shot 2020-10-13 at 4 07 09 PM (3)](https://user-images.githubusercontent.com/62810851/95926806-04080780-0d72-11eb-9b11-10655e81b51d.png)

**Comment by compwron** [comment]
@maggie-larkin  / anyone, what are next steps on this issue? :)

**Comment by maggie-larkin** [comment]
Sorry I hadn't finished writing it. It's ready to go now!

**Comment by metamoni** [comment]
@maggie-larkin @Zrrrpy does the caterpillar icon need to be clickable? According to issue #532 users can click it to change to transitioned youth, but we can just display either the caterpillar or the butterfly based on the case data. Should volunteers be able to update this (on the case and in the database)?

**Comment by metamoni** [comment]
I've done some of the work for the header and table body on [this](https://github.com/rubyforgood/casa/tree/696-volunteer-table-header) branch, but I am unable to continue working on this at the moment. The table is set up on a test path, which you can get to by going to Case Contacts, selecting an entry to edit, and replacing `/edit` in the url with `/table`. For example `http://localhost:3000/case_contacts/785/table`.

What's left to do: add interactivity (update case contact details on page and in header when user selects another case) and mobile view.

**Comment by compwron** [comment]
Closing as done / later
