### ISSUE TITLE
add paper_trail gem to User table to track roles field?

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#7]

**Comment by Thrillberg** [comment]
It seems like `paper_trail` could be very useful for tracking if a `case` gets re-assigned to a different `volunteer`. Ordinarily we would lose track of who their old `volunteer`was but with this we could easily have access to that history, correct?

Do we anticipate `User` roles changing a lot and if so, is there anything we'd do with the information about old roles a `User` may have had?

**Comment by Thrillberg** [comment]
I believe this is resolved by 3c10b651b56316d24780d04ab7c3d6dd858466d8. Feel free to reopen if not!
