### ISSUE TITLE
Show logged-in user's email address somewhere

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#70]

**Comment by lisale0** [comment]
Hey @Zrrrpy, we are seeing this view right now.  It contains the volunteer's email address.  Is there something else you want to see here?

![Screen Shot 2020-04-05 at 1 42 18 PM](https://user-images.githubusercontent.com/25441869/78509529-5de4a080-7743-11ea-9b09-945aa7985695.png)

**Comment by lisale0** [comment]
Disregard.  I was logged in as admin

**Comment by lisale0** [comment]
@Zrrrpy This is the login view for a volunteer, is this sufficient?

![Screen Shot 2020-04-05 at 1 49 35 PM](https://user-images.githubusercontent.com/25441869/78509644-5d98d500-7744-11ea-8240-6ce052e709b9.png)

**Comment by Zrrrpy** [comment]
this looks good! The volunteer email should also display anywhere else an admin is viewing volunteer details. (ex for this instance, when admin clicks on "edit" next to case and sees volunteer assigned to that case)
