### ISSUE TITLE
BUG - admin dashboard shows volunteer unassigned from supervisor as assigned

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#704]
logged in as admin, unassign volunteer from supervisor. Go to admin dashboard, the volunteer will still show as assigned to that supevisor. this is probably because the supervisor_volunteer record hasn't been deleted, just marked active-false. Fix this by making volunteer.supervisor only return active supervisor_volunteer record link
Make sure that this also works for supervisors
`casa/app/views/dashboard/_volunteers_table.html.erb`
```
      <td id="supervisor-column">
        <%- unless volunteer.supervisor.nil? %>
          <%= link_to(volunteer.supervisor.decorate.name, edit_supervisor_path(volunteer.supervisor)) %>
        <%- end %>
      </td>
```

**Comment by littleforest** [comment]
@compwron whoops I didn't read your comment closely enough. Is your preference that `volunteer.supervisor` returns nil if the `supervisor_volunteer` record is inactive? I can make that change instead.

**Comment by compwron** [comment]
Confirmed this works for supervisor and admin in staging :)
