### ISSUE TITLE
Add “pick displayed columns” for supervisor like admin has

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#706]
(and on the technical side, reduce the dashboard duplication that allowed this to happen)

![Screen Shot 2020-09-09 at 8 44 25 PM](https://user-images.githubusercontent.com/578159/92679440-49ea2f80-f2dd-11ea-9757-08cfb1d574ae.png)
![Screen Shot 2020-09-09 at 8 44 20 PM](https://user-images.githubusercontent.com/578159/92679443-4b1b5c80-f2dd-11ea-9659-fcef82f8508a.png)

**Comment by BrianBorge** [comment]
Can a supervisor create new volunteers?

**Comment by compwron** [comment]
@BrianBorge Correct, a supervisor cannot create new volunteers
