### ISSUE TITLE
Adjust rubocop settings

### ISSUE THREAD

**Issue by duaimei** [rubyforgood/casa#718]
**What type of user is this for? volunteer/supervisor/admin/all**
As a developer I want to be able to run rubocop -a and for it to only fix the files that I have made changes to.

**Description**
right now, if you run `bundle exec rubocop -a`, it changes all double quotes to single quotes. Which is not the Ruby way. Find the config file for rubocop, change that, and then see if there are any other rules that need to be disabled.

**Screenshots of current behavior, if any**

**Comment by jmkoni** [comment]
We use standard... not rubocop 😄 . If you want to fix the files, run `standardrb --fix`
