### ISSUE TITLE
 "other" casa contact type behavior

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#72]
relates to #28 

As a volunteer that is logging a new Case Contact event, I should not see the "other contact type" text box unless "other" is chosen as a Case Contact Type.

As a volunteer, I expect that if "other" is chosen, then the "other contact type" text field is required.

As a volunteer, I expect for the "other contact type" to no longer be visible if I choose "other" and then choose another option in the "case contact type" select.

**Comment by compwron** [comment]
we should put it back sometime tho?

**Comment by duaimei** [comment]
I am still working on this task.

**Comment by duaimei** [comment]
I have completed the majority of this task. I decided to just implement it so that the "other" text field  only shows up if "other" is chosen, and if it is chosen then the text box is required to be filled out.

I have opened up a PR, but I have not completed the tests for this yet.

**Comment by compwron** [comment]
You rock! :)
