### ISSUE TITLE
Style error message when updating volunteers

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#728]
**What type of user is this for? volunteer/supervisor/admin/all**
Admin

**Description**
When updating volunteer or supervisor email, if the email is a duplicate, then an error message is returned.  The error message needs to be prettified.

* Log in as casa_admin
  * Click a volunteer name to edit
  * Enter an email that belongs to another user
  * Click "Submit"

* Log in as casa_admin
  * Click a supervisor name to edit
  * Enter an email that belongs to another user
  * Click "Submit"

The `all_casa_admin` edit page already has styling for this error, so can copy from there.

**Screenshots of current behavior, if any**
<img width="705" alt="Screen Shot 2020-09-12 at 10 38 59 AM" src="https://user-images.githubusercontent.com/1938665/93001490-35c44f00-f4e4-11ea-8afb-6af6c1cc92fd.png">

**Comment by MohamedAsan** [comment]
I am willing to take this up. Can someone assign it to me?
