### ISSUE TITLE
Fix edit new case contact

### ISSUE THREAD

**Issue by johncarlocerna** [rubyforgood/casa#73]
As a volunteer, when I edit a case contact, I expect to see the same parameters as in the index entry that I clicked.

Currently, the edit parameters are the default ones.
http://localhost:3000/case_contacts

Make sure to create a feature spec for this!

**Comment by colinsoleim** [comment]
This was fixed in PR #138 and can be closed

https://github.com/rubyforgood/casa/pull/138/files#diff-a0b2b175072ab430b10f32d665c6e105
