### ISSUE TITLE
Tabs separate cases for volunteers

### ISSUE THREAD

**Issue by maggie-larkin** [rubyforgood/casa#735]
### Context

- Through user research, @taysvea has found that it's rare for a volunteer to have more than one case
- So we'll want to show only one case at a time

### How it works now
Volunteers assigned to multiple `casa_cases` see `case_contact` page cards stacked on top of each other.

### Screenshot of Current Behavior
<img width="1440" alt="Screen Shot 2020-10-13 at 4 07 09 PM" src="https://user-images.githubusercontent.com/62810851/95925254-2ef05c80-0d6e-11eb-9751-88d199354fb4.png">

### How it should work instead
Case Contact view per `casa_case` should be accessed by tabs.

### Screenshot of New Behavior
<img width="1131" alt="92334908-0a0a1a80-f047-11ea-8523-4f692903b10c" src="https://user-images.githubusercontent.com/62810851/95925590-0e74d200-0d6f-11eb-99fd-eb5dce8dbc6f.png">

### Acceptance Criteria

**As a** volunteer
**I want to** only see one case
**So that** I can focus on one youth at a time

GIVEN I am assigned more than one case
THEN I see one case (let's do the numerically lower) as the default tab under Case Contacts
AND I see the other case as an unselected tabbed option

**Comment by Zrrrpy** [comment]
deferred due to new redesign

**Comment by compwron** [comment]
@NickSchimek I'm unassigning this from you because I don't think it's actively being worked on. Feel free to pick it up if you have time to dig in!

**Comment by NickSchimek** [comment]
Ok thanks for letting me know. I will

**Comment by Zrrrpy** [comment]
I'm not sure why this issue was closed @scottolsen, reopening!

( @compwron lmk if this should remain closed )

**Comment by NickSchimek** [comment]
The PR mentioned that it was only partially completed, and that the second half would be finished if there was time. It seems like they didn't have time to finish. Perhaps @scottolsen needs to be removed as an assignee to allow someone to pick this up and finish the second half?
