### ISSUE TITLE
Admins can download reimbursement request summary

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/casa#736]
Part of epic #529 

**What type of user is this for? volunteer/supervisor/admin/all**
admin and supervisors

**Where does/should this occur?**
On the <a href="https://casa-qa.herokuapp.com/reports">Generate Reports page,</a> accessible via the admin dashboard.

[Log in to QA](https://casa-qa.herokuapp.com/) and use these credentials to access the admin dashboard:
username – casa_admin1@example.com
password – 123456

**Description**
Admins and supervisors should be able to download driving reimbursement request _summaries_ (i.e. totals) requested per volunteer over a period of time determined by user (same as the "Starting From" and "Ending At" for Case Contacts Report). 

**Context**
At the end of the month, one person at PG CASA needs to distribute checks for reimbursement for miles to volunteers who have requested it. They need a list for that month of who requested reimbursement and how many miles they requested it for.

**Comment by Zrrrpy** [comment]
Going to gather more information on this from stakeholders and then will update with more details.

**Comment by Zrrrpy** [comment]
emailed stakeholders about which users need this. Will update here once they get back.

**Comment by pollygee** [comment]
This is covered b #894
