### ISSUE TITLE
Complete per-CASA footer to include real info and not just the ruby for good logo

### ISSUE THREAD

**Issue by abachman** [rubyforgood/casa#744]
**What type of user is this for? volunteer/supervisor/admin/all**

All

**Description**

We have two controller helper methods doing the same work in slightly different ways, refactor all uses of `@casa_org` in views to be `current_organization`.

**Comment by Zrrrpy** [comment]
we'll need to seed QA with admins for our two other CASA orgs for this to be _fully_ tested on the frontend, but what I can test looks good.
