### ISSUE TITLE
New CASA Admins receive invite email

### ISSUE THREAD

**Issue by alindeman** [rubyforgood/casa#749]
**What type of user is this for? volunteer/supervisor/admin/all**
All CASA Admin, CASA Admin

**Description**
When a new CASA Admin is created, they should receive an email with details about how to login for the first time.

Relates to issue: #751

**Comment by stevelandwehr** [comment]
This issue can be closed because the work for this was done in https://github.com/rubyforgood/casa/issues/774 here: https://github.com/rubyforgood/casa/pull/821/files#diff-f1fbb36df68dc7ee2fa2412362ea8283R13

**Comment by alindeman** [comment]
> This issue can be closed because the work for this was done in #774 here: https://github.com/rubyforgood/casa/pull/821/files#diff-f1fbb36df68dc7ee2fa2412362ea8283R13

Sounds right to me :+1:
