### ISSUE TITLE
Import flash message should display nothing instead of [nil] for empty rows

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#750]
Part of epic #528 

**What type of user is this for? [admin/supervisor/volunteer/all or All CASA Admin]**
admins

**Where does/should this occur?**
On the <a href="https://casa-qa.herokuapp.com/imports">import page</a> accessible by admins.

**Description**
When an admin imports a .csv containing blank rows in a column containing a header, the system displays a flash message at the top of the screen listing all the rows that were blank in that header as "nil". 
Instead, when an admin imports a .csv containing blank rows in a column containing a header, the system should not display "nil" per empty row or anything in its place. In the example below, nothing would display after each "TRUE" and "FALSE". 

**Screenshots**
<img width="982" alt="93021846-2a8c2480-f5b3-11ea-9756-bd0e68aed23e" src="https://user-images.githubusercontent.com/62810851/93655055-18a4ea00-f9d6-11ea-9cd3-c56674b7ebed.png">

**Comment by armahillo** [comment]
1. Sign in as casa_admin1@example.com
 2. Click on account -> system imports
 3. Download example CSVs (import cases)
 4. Add rows with any numbers for the first column, TRUE or FALSE for second, and leave the third blank
 5. Import the document

Try different combinations of missing headers / missing data. 

Some data with quoted fields result in a 500. 

Original user case exported from Excel

**Comment by armahillo** [comment]
From Zoe: 
```csv
case_number,transition_aged_youth,case_assignment
CINA-01-4347,TRUE
CINA-01-4348,FALSE
```
"change the data in rows 2 and 3 before re-importing each time so we know the nil isn’t due to duplicate accounts"

**Comment by armahillo** [comment]
<img width="982" alt="Screen Shot 2020-09-13 at 11 20 07 AM" src="https://user-images.githubusercontent.com/502363/93021846-2a8c2480-f5b3-11ea-9756-bd0e68aed23e.png">

**Comment by ryanmrodriguez** [comment]
May be resolved by https://github.com/rubyforgood/casa/pull/854

**Comment by compwron** [comment]
I think we may have broken this again
