### ISSUE TITLE
Use devise_invitable for all invite emails

### ISSUE THREAD

**Issue by alindeman** [rubyforgood/casa#751]
**What is the problem, and what should happen instead?**
Right now we have two different mailers that have more or less the same content:
* `app/views/devise/mailer/invitation_instructions.{html,text}.erb`
* `app/views/volunteer_mailer/account_setup.html.erb`

The former is used by the [devise_invitable](https://github.com/scambra/devise_invitable) gem, which we use for inviting supervisors and user imports. The latter is our own mailer, used only by `VolunteerMailer` and `VolunteersController`.

It would be better to decide to use `devise_invitable` for all invite emails, or not at all. The current situation is a bit confusing and duplicative.

**Comment by compwron** [comment]
Hmm yeah that would be a good improvement :)

**Comment by Zrrrpy** [comment]
sounds like consensus then is that we will use `devise_invitable` for all invite emails and scrap the `app/views/volunteer_mailer/account_setup.html.erb` mailer? cc @compwron (If yes I'll update the ticket to reflect this)

**Comment by stevelandwehr** [comment]
In the [PR for this issue](https://github.com/rubyforgood/casa/pull/838), `app/views/volunteer_mailer/account_setup.html.erb` was not scrapped because when a volunteer is activated, the `VolunteerMailer` is being used to update the user's password token and not just sending an invitation email.
