### ISSUE TITLE
Mail was not delivered to Mailcatcher when using Docker

### ISSUE THREAD

**Issue by alindeman** [rubyforgood/casa#754]
**What is the problem, and what should happen instead?**
* Start up Docker using instructions in DOCKER.md
* Login as a CASA admin
* Create a new supervisor
* Expected: The supervisor invite email should be available at http://localhost:1080, but it is not

It looks like Mailcatcher is supposed to be hooked up correctly, including for Docker, but when pairing with @dominiquecuevas we did not see mail being delivered there.

**Comment by littleforest** [comment]
I can take a look!

**Comment by littleforest** [comment]
If you still have your Docker setup going, can you just try to hard-refresh the http://localhost:1080 page? I’ve had issues before where the mail is coming in, you just need to refresh.

**Comment by dominiquecuevas** [comment]
@littleforest A refresh of the page didn't work

**Comment by littleforest** [comment]
It looks like `letter_opener` is also installed. Does anyone know if there are conflicts to using both `letter_opener` and `mailcatcher`? I will also research.

**Comment by littleforest** [comment]
Oh, I see the problem -- the dev environment file is set up for both letter_opener and mailcatcher for the `smtp` method, and letter opener wins. Should I just remove the mailcatcher setup and we can go with letter opener?

**Comment by littleforest** [comment]
I'm just going to remove the mailcatcher setup and we will continue to use `letter_opener` which is what is actually configured. Please stop and remove the mailcatcher service so you don't end up with an orphan container after #767 is merged:

```
$ docker-compose stop mailcatcher
$ docker-compose rm -f mailcatcher
```

**Comment by dominiquecuevas** [comment]
Done! thanks, Jeanine!
