### ISSUE TITLE
[bug] Any supervisor should be able to view any supervisor page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#756]
[Bug]

_Current behavior:_ Supervisors get an unhandled error message when trying to access any view supervisor page (including their own).

_What should happen:_ Any supervisor should be able to view any supervisor page (including their own).

**How to reproduce**: 
1 - Log in as supervisor1@example.com
2 - PW: 123456
3 - Click on any supervisor name (including your own: it's Gloria).
4 - Reference the #casa-bots channel in Slack to watch the error message come through.

**Comment by Zrrrpy** [comment]
This appears to be fixed on the frontend in staging now – @armahillo // @jmkoni any outstanding work on the backend or can I close this?

**Comment by compwron** [comment]
I will close this because it appears to be done. :)
