### ISSUE TITLE
Admin can enter CASA Case's birth month and year

### ISSUE THREAD

**Issue by maggie-larkin** [rubyforgood/casa#760]
### Context
- Right now, the burden is on the users to update the case from "Youth Under 14" to "Transition Age"
- We want to make this automatic in the system 
- We also don't want to put too much PII in the system, so this will only use month and year to determine the youth's age
- Open to how this field (or fields) looks. I am picturing something like "Start Year Demonstration" example [here](https://kidsysco.github.io/jquery-ui-month-picker/) but am flexible to engineering constraints. As long as we can capture month and year (and preferably in numeric form), I'm happy!

### Acceptance Criteria
**As an** admin
**I want to** add a youth's birth month and year
**So that** users don't have to manually update ages

Scenario 1: See the field
GIVEN I am an admin 
WHEN the Edit Case Details page loads
THEN I see a date picker field that accepts month and year and is labeled "Youth's Birth Month & Year"

Scenario 2: Saving
WHEN I am on the Edit Case Details page
AND I have edited the Youth Birth Month and Year
WHEN I hit "submit"
THEN the "Youth's Birth Month & Year" saves to the database

**Comment by khiga8** [comment]
Hey @maggie-larkin, for this issue, since we're only using birth month and year to determine age, would we want to round up or down?

If the system only knows birth day and month, should a youth be marked as their new age as soon as it hits September, or wait until October?

**Comment by Zrrrpy** [comment]
Just checked with the stakeholders about this – the system would wait until October in this instance.
