### ISSUE TITLE
AllCasaAdmin casa_org overview

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#771]
Part of epics: #527 and #530 

**What type of user is this for? [volunteer/supervisor/admin/all or All CASA Admin]**
All CASA Admin

**Where does/should this occur?**
In the All CASA Admin dashboard, on a <a href="https://casa-qa.herokuapp.com/all_casa_admins/casa_orgs/2">casa_org page</a>.

_Accessible by logging into the <a href="https://casa-qa.herokuapp.com/all_casa_admins/sign_in">All CASA Admin QA environment</a> with the below credentials:_
- Email: allcasaadmin@example.com
- Password: 123456

**Description**
This page view should show administrators an overview of activity and user accounts per `casa_org`. The overview should include:
- total number of active volunteer users
- total number of inactive (deactivated) volunteer users
- total number of active supervisors
- total number of inactive (deactivated) supervisors
- total number active admin users
- total number of inactive (deactivated) admin users
- total number of CASA cases
- total number of active volunteer / CASA case assignments
- total number active volunteer / supervisor assignments
- total number of case contacts logged to date

**Comment by compwron** [comment]
@talentedunicorn how is it going? Are you still working on this? If you are working on this, please reply. Otherwise I will put this back in the TODO list :)

**Comment by talentedunicorn** [comment]
@compwron sorry lost track of this, you can put it back to TODO

**Comment by compwron** [comment]
I am closing this as a duplicate / merging with #1086
