### ISSUE TITLE
Admin can edit other admin accounts

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#780]
Part of epic #4

**What type of user is this for? [admin/volunteer/supervisor/all]**
admin

**Where does/should this occur?**
On the admin dashboard, at the bottom underneath subheader "Admins". 

<a href="https://casa-r4g-staging.herokuapp.com/">Log in to staging</a> and use these credentials to access the admin dashboard:
username – casa_admin1@example.com
password – 123456

**Description**
Underneath "Actions" in the Admins section of the Admin dashboard, there should be hyperlinked text per row "Edit" that leads to an Edit Admin user page. This page should look a lot like the <a href="https://casa-r4g-staging.herokuapp.com/users/edit">Edit Profile page for Admins</a>, minus the ability to change password.

Relates to issues: #774, #779

**Comment by drborges** [comment]
Closed by mistake.
