### ISSUE TITLE
Admin can deactivate their own account

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#781]
Part of epic #4

**What type of user is this for? [admin/supervisor/volunteer/all or All CASA Admin]**
admin

**Where does/should this occur?**
On the <"https://casa-r4g-staging.herokuapp.com/users/edit">edit profile page</a> for Admins.

<a href="https://casa-r4g-staging.herokuapp.com/">Log in to staging</a> and use these credentials to access the admin dashboard:
username – casa_admin1@example.com
password – 123456

**Description**
Admins should be able to deactivate their own accounts. There should be a distinguished button on an Admin's edit profile page that does this. 

_Note: If there is only one active admin account, the user should not be able to deactivate themself. When they try, they should see an error message that reads: Contact your administrator at Ruby For Good to deactivate this account._

**Comment by KatherineMuedas** [comment]
Hello @Zrrrpy , I've been looking at the User Model and we have an `active` boolean attribute. Can we use that `active` attribute to deactivate an account? If so, when deactivating the account the active would change from true to false.
