### ISSUE TITLE
Fix miles_driven nil to 0 value migration

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#789]
See slack thread https://rubyforgood.slack.com/archives/CVB0QJGVD/p1600305358004800

**Screenshots**
<img width="1614" alt="Screen Shot 2020-09-16 at 6 15 31 PM" src="https://user-images.githubusercontent.com/62810851/93723650-449aa980-fb55-11ea-9d1f-e498c3385e3e.png">

**Comment by Garbar** [comment]
It seems to me that these changes are already added in migrations by @jmkoni

**Comment by compwron** [comment]
@Garbar I think you're right! I will close this. Thanks for the catch :)

**Comment by compwron** [comment]
This doesn't seem to be working in QA (I created a case contact and removed the 0 in the field in the UI)
BugsnagAPP  3:10 PM
Event in qa from casa in case_contacts#create (details)
Unhandled error
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "miles_driven" violates not-null constraint
DETAIL:  Failing row contains (927, 209, 94, 600, 2020-10-04 00:00:00, 2020-10-04 22:10:11.456755, 2020-10-04 22:10:11.456755, t, text/email, null, null, f, ).
Location
app/controllers/case_contacts_controller.rb:51 - block in create

**Comment by compwron** [comment]
tracked in https://github.com/rubyforgood/casa/issues/956
