### ISSUE TITLE
Remove extra Login button and make Logout button match

### ISSUE THREAD

**Issue by datadaveshin** [rubyforgood/casa#79]
- [ ] There is an extra Login button at the bottom of the Login page, which isn't functional - I assume the functional one above came from Devise - which should be removed:
- [ ] The Logout button should be updated to match the Login button

Here are the Login buttons:
![Login Screen Shot 2020-04-06 at 7 14 08 PM](https://user-images.githubusercontent.com/14435667/78623286-27d71780-783c-11ea-8557-d7bb5e1d8f71.png)

------------------------------

Here is the Logout button
![Logout 2020-04-06 at 7 13 31 PM](https://user-images.githubusercontent.com/14435667/78623397-65d43b80-783c-11ea-87fe-13eacd8f6c56.png)

**Comment by compwron** [comment]
Thanks for this great issue! I agree we should do this :)

**Comment by datadaveshin** [comment]
I'll try to fix it by tomorrow morning

**Comment by datadaveshin** [comment]
My bad, I later realized the dark blue bars with "Login" and "Logout" at the bottom were meant to be in a footer originally so we could log in and out to get the app rolling.

Looks like the [mockup](https://github.com/rubyforgood/casa/wiki) has the "Login" and "Logout" buttons in the navbar, so move there?

Navbar from wiki:
![navbar Screen Shot 2020-04-07 at 7 14 35 AM](https://user-images.githubusercontent.com/14435667/78680087-e9734400-789f-11ea-9b3d-479f163fd1e4.png)
