### ISSUE TITLE
Supervisor dashboard redesign

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#801]
Filter issues by the labels "Supervisor" and "Design" to see all work related to this epic.

<a href="https://udw1g1.axshare.com/#id=e82lqg&p=supervisor_experience&g=1">Please reference the Supervisor Experience mockup to see what the new Supervisor dashboard should look like.</a>

**Context**
Supervisors have the second highest level of user access, and can see many of the same things as an admin, but the focus of their experience should be on the volunteers that are actively assigned to them. 

_Note:_ The mockup above is not reflective of all the functionalities the supervisor dashboard currently contains. Please reference the current supervisor dashboard (see below for how to access) for full functionality. 

**How to access the supervisor dashboard**
<a href="https://casa-qa.herokuapp.com/">Log in to QA</a> with the following credentials:
Email: supervisor1@example.com
Password: 123456

**Comment by compwron** [comment]
Closing for now, there is too much distance between here and there.
