### ISSUE TITLE
Admin dashboard redesign

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#802]
Filter issues by the labels "Admin" and "Design" to see all work related to this epic.

**Context** 
The Admin dashbboard contains the most information out of all user accounts; They can view, add, and edit information pertaining to all other account types. Now that the MVP Admin dashboard is functional and operational in production, we'd like to redesign it to present all of this information in a less overwhelming, more streamlined way.

Brand new mockups will be needed for this user dashboard. Please reference the <a href="https://udw1g1.axshare.com/#id=e82lqg&p=supervisor_experience&g=1">supervisor and volunteer mockups</a> as a starting point.

**How to access the admin dashboard**
<a href="https://casa-qa.herokuapp.com/">Log in to QA</a> with these credentials:
email: casa_admin1@example.com
password: 123456

**Comment by compwron** [comment]
Closing for now
