### ISSUE TITLE
supervisors/admins can edit court report submission status

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#806]
Part of epic #880 

**What type of user is this for? [volunteer/supervisor/admin/all or All CASA Admin]**
supervisors and admins

**Where does/should this occur?**
On the Edit CASA Case page (example: https://casa-qa.herokuapp.com/casa_cases/2/edit)
![Screen Shot 2020-09-26 at 4 30 47 PM (2)](https://user-images.githubusercontent.com/62810851/94352993-f9830980-0020-11eb-9f14-5fe279b25ea3.png)

**Description**
As a supervisor/admin, I should be able to add the following statuses to `court_report_submission`:
- Submitted
- In review
- Completed

**Frontend**
There should be a "Select Status" dropdown menu next to Court Report Submission (see issue #619) where admins and supervisors can select from one of the statuses listed above. The status should then display under CASA Case details next to the text Court Report Submission, which displays for all user types viewing a `casa_case`'s details.

**Comment by jtnegrotto** [comment]
Mind if I take this one?

**Comment by compwron** [comment]
@jtnegrotto as you can see you have been assigned to this issue. It is all yours. have fun! :)

**Comment by compwron** [comment]
@jtnegrotto How is it going? Are you still working on this? Do you need help?

**Comment by Zrrrpy** [comment]
Hey @jtnegrotto, I'm going to un-assign this for now so it can keep moving forward, but please feel free to reassign to yourself if you still have time and would like to pick it back up. 😃

**Comment by ChaelCodes** [comment]
I'd like to work on this issue!

**Comment by ChaelCodes** [comment]
Hey, the linked issue adds court report submission as a boolean named `court_report_submitted` instead of an enum that could support statuses. The field is available to volunteers, admins, and supervisors. I'm not sure if the intent of this issue is to restrict access, convert the field type, or something else?

![image](https://user-images.githubusercontent.com/8124558/97109100-b069b800-16a7-11eb-8afc-f8d5316496a0.png)

**Comment by littleforest** [comment]
@ChaelCodes thanks for picking this up! Can you please make the following changes:

To the `casa_cases` table:
- [ ] Add a datetime field called `court_report_submitted_at`.
- [ ] Add an integer field called `court_report_status` that will be an enum.
- [ ] Create an [After Party](https://github.com/theSteveMitchell/after_party) task that marks the `court_report_submitted_at` with the current time for any records that have `court_report_submitted`.

- [ ] On the Casa Cases edit page, remove the checkbox for "Court report submitted" and replace with "Court report status" that has selection of enum values, including blank.

- [ ] Mark the `court_report_submitted_at` timestamp the FIRST time a non-blank value is selected for Court report status. It should not be updated for further status changes (though I guess should be cleared if blank is selected - for the situation that someone entered incorrectly that a court report had been submitted).

- [ ] Modify `court_report_submitted` method to now be true if `court_report_submitted_at` has a value.

- [ ] Check for other instances of `court_report_submitted` that might need to be modified.

- [ ] Create follow-up task to remove boolean `court_report_submitted` field.

We can break this up into smaller tasks if that's easier! Ultimately we want to create a separate Court Reports table but it proved difficult to do during Hacktoberfest with many different contributors picking up separate pieces of this.

**Comment by compwron** [comment]
@ChaelCodes How is it going? Can we help? Also feel free to join us in slack for real-time (ish) discussion if you want https://rubyforgood.herokuapp.com/ #casa channel
Also we have a weekly zoom "office hours" (link in slack) if that is something you want to hang out in (currently Weds 6-8 Pacific)
