### ISSUE TITLE
supervisors and admins can add next court date per volunteer

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#807]
Part of epic #880 

**What type of user is this for? [volunteer/supervisor/admin/all or All CASA Admin]**
mostly supervisors, but also admins

**Where does/should this occur?**
On the Edit CASA Case page (example: https://casa-qa.herokuapp.com/casa_cases/2/edit)

**Description**
As a supervisor or admin, I should be able to add the next Court Date associated with a `casa_case`.

**Backend**
This is a _brand new_ feature, so an addition will need to be made to db for `court_date` which can be associated with a `casa_case`. (see details in epic #880)

**Frontend**
Next `court_date` should appear on the Edit CASA Case Page, in the same section as *Case number* and *Transition Aged Youth* (see screenshot below). The information entered here should appear for all users viewing a `casa_case`. 
![Screen Shot 2020-09-26 at 4 30 47 PM (2)](https://user-images.githubusercontent.com/62810851/94352156-63e27c80-0016-11eb-8cc2-8c556c0e883f.png)

**Comment by compwron** [comment]
Because this is mentioned in a PR, I am assigning it to the creator of that PR

**Comment by compwron** [comment]
Found bug https://github.com/rubyforgood/casa/issues/954 while testing this
