### ISSUE TITLE
supervisors and admins can add court report due date per casa_case

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#808]
Part of epic #880 

**What type of user is this for? [volunteers/supervisors/admins/all or All CASA Admin]**
mostly supervisors, but also admins

**Where does/should this occur?**
On the Edit CASA Case page (example: https://casa-qa.herokuapp.com/casa_cases/2/edit)

**Description**
As a `supervisor` or `admin`, I should be able to add the next Court Report Due Date associated with a `casa_case`.

**Backend**
This is a new feature, so an addition will need to be made to db (probably in the same table as `court_date` #807) for `court_report_due_date` which can be associated with a `casa_case`.

**Frontend**
Next `court_report_due_date` should appear on the Edit CASA Page, in the same section as *Case number* and *Transition Aged Youth* (see screenshot below), next to the Next Court Date (see #807).
![Screen Shot 2020-09-26 at 4 30 47 PM (2)](https://user-images.githubusercontent.com/62810851/94352302-eae42480-0017-11eb-88de-a2d4e25819e4.png)

**Comment by khiga8** [comment]
Hello! Can I take this issue?

**Comment by compwron** [comment]
@khiga8 as you can see, you have been assigned to this issue, so it is yours. Have fun! :)

**Comment by khiga8** [comment]
> @khiga8 as you can see, you have been assigned to this issue, so it is yours. Have fun! :)

Yes! Thank you!

**Comment by khiga8** [comment]
Hey @Zrrrpy!

Should the lower and upper bound date for this be the same as #807?

**Comment by compwron** [comment]
@khiga8 yes, yet's go with that for now :)
