### ISSUE TITLE
Admins can add contact_types and groups

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#813]
Part of epic #4 // relates to issues #815, #816 

**What type of user is this for? [admin/supervisor/volunteer/all or All CASA Admin]**
admin

**Context**
`contact_types` associated with `case_contacts` vary from CASA Org to CASA Org. Giving admins the ability to add `contact_types` associated with their unique Org instance will increase accuracy in reporting.
Grouping `contact_types` will help paint a higher level picture of which `contact_types` are being contacted most and least.

**How to access on the frontend in QA:**
<a href="https://casa-qa.herokuapp.com/">Log in to QA</a> and use these credentials to access the admin dashboard:
username – casa_admin1@example.com
password – 123456

**Where does/should this occur?**
On the <a href="https://casa-qa.herokuapp.com/casa_orgs/2/edit">Edit CASA Org page</a> in the admin dashboard.

**Frontend**
Admins should be able to add `contact_types` and `contact_groups` associated with `case_contacts` to be used in their organization's instance and display on create and edit case contact forms. 

**Backend**
_Current structure:_
`case_contact: … contact_types(arr(str))`
_Future structure should look something like this:_ 
`case_contact: …
contact_type: casa_org_id, name, group
join table (one(case_contact)-to-many(contact_type)): case_contact_contact_type: case_contact_id, contact_type_id uniq(case_contact_id, contact_type_id)`

**Comment by gmfvpereira** [comment]
@Zrrrpy do you know which groups we need to create for the existing contact types? 
```
attorney
bio_parent
court
dss_worker
foster_parent
medical_professional
other_family
other_support_worker
school
social_worker
supervisor
therapist
youth
```

If you don’t know the groups yet, I can simply add all of them into a single group and we change it later on.

**Comment by Zrrrpy** [comment]
Yes! Will send them here in a sec @gmfvpereira

**Comment by Zrrrpy** [comment]
**Group: CASA**
`youth
supervisor`

**Group: Biological family**
`bio_parent
other_family`

**Group: Placement**
`foster_parent`

**Group: Social Services**
`social_worker
dss_worker`

**Group: Legal**
`court
attorney`

**Category: Health**
`medical_professional
therapist`

**Category: Education**
`school`

**Category: Support Worker**
`other_support_worker`

**Comment by gmfvpereira** [comment]
> Future structure should look something like this:
case_contact: … contact_type: casa_org_id, name, group join table (one(case_contact)-to-many(contact_type)): case_contact_contact_type: case_contact_id, contact_type_id uniq(case_contact_id, contact_type_id)

I'm not sure I understood the proposed structure with that notation @Zrrrpy 

This is what I got, let me know if there's something wrong with it:
![casa_structure](https://user-images.githubusercontent.com/386460/93899697-f4455800-fcca-11ea-8947-7f1ecb553e7a.jpg)

**Comment by Zrrrpy** [comment]
This looks right to me! @compwron does this accurately reflect what we discussed yesterday?

**Comment by gmfvpereira** [comment]
The way I understood it makes it possible to share a `contact_type` with different organizations, but looking to https://github.com/rubyforgood/casa/issues/816 makes me think that we may not wanna share `contact_types` across organizations.

If we end up going with the idea of sharing `contact_types` across organizations we may need to change #816 to add/edit/update contact types in a page other than the edit page of a specific organization. Maybe adding an "Edit Contact Types" to the dropdown at the top navbar?

@compwron @Zrrrpy thoughts?

**Comment by Zrrrpy** [comment]
We don't want to share `contact_types` across different organizations, but rather to give each organization instance the ability to create and use their own unique `contact_types` (although there will likely be a few default `contact_types` each organization instance starts with that they can customize, but this is not ticketed out yet.)

**Comment by Zrrrpy** [comment]
^^ confirmed with @compwron that the visualization above is accurate.

**Comment by gmfvpereira** [comment]
Not the best UX, but good enough for a first pass.

<img width="1440" alt="Screen Shot 2020-09-24 at 1 14 12 PM" src="https://user-images.githubusercontent.com/386460/94172292-b54d0900-fe68-11ea-8441-d303ec516d87.png">
<img width="1440" alt="Screen Shot 2020-09-24 at 1 14 20 PM" src="https://user-images.githubusercontent.com/386460/94172302-b8e09000-fe68-11ea-8d12-9d137971d6fa.png">
<img width="1440" alt="Screen Shot 2020-09-24 at 1 14 26 PM" src="https://user-images.githubusercontent.com/386460/94172309-ba11bd00-fe68-11ea-8189-2bed6795e2ed.png">
<img width="1440" alt="Screen Shot 2020-09-24 at 1 14 32 PM" src="https://user-images.githubusercontent.com/386460/94172313-bb42ea00-fe68-11ea-81fc-ad0dbe72f77d.png">
