### ISSUE TITLE
Display contact_types in groups

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#815]
Part of epic #3 // dependent on #813 

**What type of user is this for? [admin/volunteer/supervisor/all]**
primarily volunteers, but also admins and supervisors

**Where does/should this occur?**
On the create/edit case contact forms accessible in all user dashboards.

**Description**
`Contact_types` should be nested under Groups on Create and Edit Case Contact forms.

**Comment by compwron** [comment]
@leilaweiss @roxannecojocariu How is this going? :)

**Comment by roxannecojocariu** [comment]
@compwron I believe this was completed in [this PR](https://github.com/rubyforgood/casa/pull/811).  We kind of kept getting more stories in this one little logo story.  Please let me know if there is something else that needs to be addressed, but I was under the impression this was closed.

**Comment by roxannecojocariu** [comment]
@compwron Also, in [my other PR](https://github.com/rubyforgood/casa/pull/985), the contact_types are appropriately nested under Group, so I believe this may be completed :)

**Comment by jmkoni** [comment]
@roxannecojocariu great! in the future, can you make sure to keep your PRs small and only related to one ticket? That was definitely huge scope creep since the contact types shouldn't have anything to do with the footer...

**Comment by compwron** [comment]
I am closing this because it is done as discussed above
