### ISSUE TITLE
Use ActiveRecord Store (or similar alternative) for system imports.

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#826]
**Context**
Currently, our system imports fail when a user attempts to import a file larger than 4kb (approximately 30 rows in a .csv).

**Resolution**
Refactor file uploads to use something like ActiveRecordStore to allow the file importer to handle larger files.

**Comment by stephenagreer** [comment]
@Zrrrpy This shouldn't be needed anymore. We've restructured the error messaging for imports and are no longer hitting the 4kb limit for cookies.
