### ISSUE TITLE
Add route to Edit Profile from sidebar menu

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#833]
Part of epic #822

As a volunteer/supervisor/admin, I want to click on "Edit Profile" in the blue left sidebar menu,
and then see the "Edit Profile form" on my home screen,
so that I can make updates to my profile without navigating to a different page.

**How does it work now?**
Users must select "Edit Profile" from a dropdown menu in the upper right hand corner of the screen in order to access the Edit Profile form. 

**How should it work?**
Users should be able to open the Edit Profile form by clicking "Edit Profile" in the left sidebar menu.

**Acceptance criteria**
"Edit Profile" displays in left sidebar menu.
"Edit Profile" is clickable.
"Edit Profile" opens the "Edit Profile" form in a wrapper on home. (see #832)

**Comment by Zrrrpy** [comment]
@jasperfurniss should I close this out? Sounds like it's already done due to the existing menu layout.

**Comment by casadei** [comment]
I believe this requirement was addressed by [this commit](https://github.com/rubyforgood/casa/commit/b153709a48b8234926579de35a9614050d35d67e). Dunno what is the best way to proceed with this task!
