### ISSUE TITLE
Frontend Testing

### ISSUE THREAD

**Issue by duaimei** [rubyforgood/casa#84]
As discussed in the CASA slack channel, I'm going to be implementing Cypress so that Javascript is testable.

As a part of this I would like to:

- programmatically sign in users
- create fixtures for test setup
- convert the current Capybara tests to Cypress tests
- cypress integrated into CI
- README instructions on how to run

**Comment by compwron** [comment]
Sounds great! Thank you so much for driving us in a good direction with this :)

**Comment by compwron** [comment]
Hey @duaimei I am still excited about this :) If you want to pair program we're on zoom today 1-230pm pacific time, and I'm happy to hang out other times too. Feel free to react out in the rubyforgood slack also :) 
If you don't have time for this right now, no worries :)

**Comment by Zrrrpy** [comment]
@duaimei Is this something you'd like to continue working on? (No worries if not!) Let me know either way as we have a bunch of new contributors this week and I'll put this back in to-do if it's good to be picked up by someone else.

**Comment by compwron** [comment]
I will mark this done because we merged the PR to add Cypress :)
