### ISSUE TITLE
Add route to supervisors from sidebar menu

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#840]
Part of epic #822

As an admin/supervisor,
I want to see the text "Supervisors" in sidebar menu,
so that I can click on it to see and take all actions associated with supervisors (in accordance with my user permissions). 

**How does it work now?**
_For admins:_ supervisors display toward the bottom of the home dashboard. Clicking on any individual supervisor directs user to a different page where they can take associated actions in accordance with their user permissions.

_For supervisors:_ Other supervisor accounts only display when user filters their volunteer view (on home dashboard) to include volunteers assigned to other supervisors. Supervisors can click on the name of another supervisor from the volunteer view to be directed to a different page where they can take associated actions in accordance with their user permissions.

**How should it work?**
Supervisors and admins should both be able to access supervisors and take associated actions from the left sidebar. 

**Acceptance criteria**
Text: "Supervisors" appears in left sidebar.
Text: "Supervisors" is clickable.
Clicking "Supervisors" opens the supervisor view in a contained wrapper on the same page.

**Comment by drborges** [comment]
@Zrrrpy should supervisors be able to **add** new supervisors? The reason I ask is that, although there does not seem to be an "Add New Supervisor" button anywhere for logged in supervisors, I'm still able to access the "New Supervisor" page via its URL: https://casa-qa.herokuapp.com/supervisors/new.

**Comment by Zrrrpy** [comment]
They should not be - only admins can add new supervisors.

**Comment by drborges** [comment]
@Zrrrpy just wanted to doublecheck with you, supervisors should now have access to the list of supervisors by clicking the `Supervisors` link on the sidebar as per the issue's description, eventhough they don't currently have access to that listing on their dashboard, did I get that right?

Also, I noticed that supervisors can currently edit other supervisors by clicking the supervisor's name on a volunteer, so I assume the `Edit` link on the supervisors list will be available for both supervisor and admin users, is that accurate?

**Comment by drborges** [comment]
Looks like I did not pay a lot of attention. So let me try that again:

It looks like a supervisor **cannot** edit other supervisors, so when logged in as a supervisor the `Supervisors` menu item should not be available.

**Comment by Zrrrpy** [comment]
Yes! Correct – Supervisors have the same edit permissions for other supervisors as admins. The only difference is they can't **create** a new supervisor. The current layout doesn't allow easy access to supervisors for other supervisors, but that is a design not a permissions flaw.

**Comment by drborges** [comment]
Ah! Ok,  thanks I started to get confused there for a moment 😆
