### ISSUE TITLE
Add route to Edit Organization from sidebar

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#845]
Part of epic #822

As an Admin,
I want to click on text, "Edit Organization" in sidebar,
so that I can view and edit my Organization details.

**How it works now**
Admins click on their email in the upper right hand side of the header and select "Edit Organization" from a drop down menu. "Edit Organization" directs to a different page, from where Admin can view and edit their CASA Organization details.

**How it should work**
Admins click on "Edit Organization" in left sidebar and are presented with their organization details contained within a wrapper on the same page. 

**Acceptance criteria**
Text "Edit Organization" displays in left sidebar.
"Edit Organization" is clickable. 
Clicking on "Edit Organization" opens CASA Organization details and displays them within a contained wrapper on the same page.

**Comment by casadei** [comment]
I was wrapping up my code and realized that this requirement was addressed in [this commit](https://github.com/rubyforgood/casa/commit/b153709a48b8234926579de35a9614050d35d67e). So, I believe there is nothing else to do in this task.
