### ISSUE TITLE
apply new wrapper to CASA Organization details

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#846]
Part of epic #822

As an Admin,
I want to click on text "Edit Organization" in left sidebar,
so that I see my organization details contained within a wrapper on the same page,
from where I can take all actions associated with my organization details. 

**How it works now**
Clicking on "Edit Organization" from the dropdown menu on the upper right hand side of the Admin dashboard directs to a different page. After an Admin saves their changes, they must navigate back to home. 

**How it should work**
Clicking on "Edit Organization" from the left sidebar should open Organization details in a contained wrapper as a page card. 

**Acceptance criteria**
Clicking on "Edit Organization" from left sidebar opens Organization Details,
which display in a contained wrapper.

**Comment by drborges** [comment]
@Zrrrpy for the user story in the description, wouldn't the following be what we want? I think it's not in our plans to avoid page refreshes, can you confirm @jasperfurniss?

```diff
As an Admin,
I want to click on text "Edit Organization" in left sidebar,
- so that I see my organization details contained within a wrapper on the same page,
+ And be redirected to the `Edit Organization` view page,
from where I can take all actions associated with my organization details.
```

**Comment by Zrrrpy** [comment]
I think you're right @drborges and that I've just been thinking about and imagining the transition from "click" to display view incorrectly – but I'll let let @jasperfurniss confirm as I'm not 100% sure of what he and @coleerikson were imagining for this.
