### ISSUE TITLE
Admins can reactivate other admin accounts

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#848]
As an admin,
I want to reactivate previously deactivated admin accounts,
so that an email is triggered re-inviting the previously deactivated admin to the platform.

**How it works now**
Admins do not have the ability to reactivate a deactivated admin account.

**How it should work**
Admins should see a button or clickable text reading "Activate Admin" that reactivates the account, and triggers an invite email to be resent to that admin, regranting them access to their account.

**Acceptance criteria**
Admin sees button or clickable text reading "Activate Admin" on a deactivated admin's profile.
Taking action "Activate Admin" triggers an email invite to the previously deactivated admin regranting them access to their account.

**Comment by compwron** [comment]
This was resolved by https://github.com/rubyforgood/casa/pull/851

**Comment by compwron** [comment]
Foung bug https://github.com/rubyforgood/casa/issues/952 while testing this.
