### ISSUE TITLE
Contact Types and Groups display per casa_case when creating/editing a case_contact

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#859]
Part of epic #856 // dependent on #858

As a volunteer/supervisor/admin, I want to see Contact Types and Groups relevant to the `casa_case` I am logging a `case_contact` for.

**How does it work now?**
All users see all Contact Types when logging a `case_contact` for any `casa_case`.

**How should it work?**
All users should **only** see Contact Types and Groups associated with the `casa_case` they are creating/editing a `case_contact` for – as determined by a Supervisor (see #858)

**Acceptance criteria**
When creating/editing a `case_contact` for a `casa_case`, only Contact Types and Groups selected by a supervisor for that `casa_case` should display.
For `casa_cases` that do not have customized Contact Types and Groups, all Contact Types and Groups available to the associated CASA Org instance (which have not been hidden by an Admin) should display when editing/creating a `case_contact` associated with that `casa_case`.  

So in this example, ONLY the two checked case_contact types should show up for the volunteer
![Screen Shot 2020-12-09 at 7 49 20 PM](https://user-images.githubusercontent.com/578159/101719196-b0efbf80-3a57-11eb-9aa9-ec2b324041c6.png)

**Comment by Zrrrpy** [comment]
covered by #815 - closing out

**Comment by myllenaalves** [comment]
Can I take this issue?

**Comment by Zrrrpy** [comment]
go for it @myllenaalves!

**Comment by Zrrrpy** [comment]
@myllenaalves are you still working on this? No worries if not, but let us know so we can open it back up, if so. :)

**Comment by myllenaalves** [comment]
I realized that maybe I won't be able to do it and I think it's better to pass it on to someone else, thank you!

**Comment by compwron** [comment]
@myllenaalves thanks for letting us know. Feel free to come back anytime and/or pick up a different issue if you want :)

**Comment by cliftonmcintosh** [comment]
What's the expected behavior of the case has not had contact types defined for it by a supervisor? Does that ever happen or is it never supposed to happen? If it does happen, what contact types should be shown? Show all contact types?
