### ISSUE TITLE
default Contact Types and Groups for all CASA Org instances

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#870]
Part of epic #530

As any user part of a CASA Org instance,
my instance should come pre-loaded with the below **default Contact Types and Groups**,
so that Admins can customize them for their instance, supervisors can associate them with cases, and volunteers can select from them when creating/editing a `case_contact`. (see #856)

Admins should be able edit, hide, and show default Contact Types and Groups – same permissions that apply to all other Contact Types and Groups.

Group: `CASA`
·      `youth`
·      `supervisor`

Group: `Family`
·      `parent`
·      `other_family`
·      `sibling`
·      `grandparent`
·      `aunt_uncle_cousin`
·      `fictive_kin`

Group: `Placement`
·      `foster_parent`
·      `caregiver_family`
·      `therapeutic_agency_worker`

Group: `Social_Services`
·      `social_worker`

Group: `Legal`
·      `court`
·      `attorney`

Group: `Health`
·     `medical_professional`
·     `mental_health_therapist`(should be changed from `therapist`)
·      `other_therapist` 
·      `psychiatric_practitioner`

Group: `Education`
·      `school`
·      `guidance_counselor`
·      `teacher`
·      `IEP_team`

**Comment by Zrrrpy** [comment]
@gmfvpereira FYI stakeholders finalized this list (after a couple days of back and forth 😅 ) no expectations for this to be done today, just flagging in case you think there might be time for it!

**Comment by Zrrrpy** [comment]
We'll need to seed QA with a new organization or two and some corresponding admin accounts for this to be tested.

**Comment by compwron** [comment]
I added 2 more orgs, San Jose CASA and SF CASA. 

New admin accounts:

SF `casa_admin_sf@example.com`
Ssan Jose `casa_admin_sj@example.com`

<img width="1629" alt="Screen Shot 2020-10-11 at 2 32 47 PM" src="https://user-images.githubusercontent.com/578159/95690743-a7b8b280-0bce-11eb-8423-3fef542511c8.png">
