### ISSUE TITLE
broken login screen layout on qa

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#878]
**Environment**
qa https://casa-qa.herokuapp.com/

**What's broken**
- image is cut off
- email and password text fields are too short
- page should not have so much blank space on the left
- sidebar should be on the left side (although I think it might be gone entirely in the new login screen mockup)

**Screenshots of current behavior**
<img width="1317" alt="Screen Shot 2020-09-25 at 4 02 56 PM" src="https://user-images.githubusercontent.com/62810851/94323080-4d222400-ff49-11ea-83ba-01bc881ca74f.png">

**Comment by drborges** [comment]
@Zrrrpy the PR above will fix that login page issue along with a few other UI issues that I encountered. I've added a few GIFs and screenshots on the PR showing the before/after states. Let me know if there's anything you'd like me to change.

**Comment by Zrrrpy** [comment]
@drborges login screen still looks funky at https://casa-qa.herokuapp.com/users/sign_in 
can you:
- [ ] eliminate the white space underneath the footer 
- [ ] add space between "Forgot your password?" and footer
- [ ] add image here
![Screen Shot 2020-10-11 at 12 03 50 PM (2)](https://user-images.githubusercontent.com/62810851/95687676-fad43a80-0bb9-11eb-90f4-349670b8a0ca.png)

**Comment by drborges** [comment]
@Zrrrpy I'll look into this later today 👍🏼
