### ISSUE TITLE
Court Date/Report info "clears" once date has passed

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#881]
Part of epic #880 // dependent on #808 & #805

**What type of user is this for? [ volunteer/supervisor/admin/all or All CASA Admin]**
all

**Where does/should this occur?**
On the Edit CASA Case page (example: https://casa-qa.herokuapp.com/casa_cases/2/edit)
![Screen Shot 2020-09-26 at 4 30 47 PM (2)](https://user-images.githubusercontent.com/62810851/94353260-eaea2180-0023-11eb-9f8e-38b1c403630c.png)

**Description**
After the Next Court Date has passed, that date should "clear" and display under "`past_court_dates` (see #805), and all other associated data should reset, including:
- `court_report_due_date`
- `court_report_submission` status

**Frontend**
After the Next Court date has passed, *no* date should appear next to text: Next Court Date on the `casa_case` details page, and all associated information above should also reset.

**Comment by tauhir** [comment]
I'd like to give this ago if this is available? @Zrrrpy

**Comment by Zrrrpy** [comment]
just assigned it to you @tauhir - all yours!

**Comment by Zrrrpy** [comment]
Hey @tauhir, you still interested in this? No worries if not, but I'll un-assign if that's the case so someone else can pick up. :)

**Comment by tauhir** [comment]
Hi @Zrrrpy, yes I am. Does #808 as well as #805 need to be assigned to me as well?

**Comment by littleforest** [comment]
@tauhir I made some notes on #880 re a table structure. I took #807, but feel free to unassign me if you want to grab the whole lot of related tasks.

**Comment by Zrrrpy** [comment]
yes, when you're ready to take it on go ahead and assign to yourself @tauhir! Generally if a ticket is unassigned it's up for grabs. :)

**Comment by keithrbennett** [comment]
This issue's title is "Court Date/Report info "clears" once date has passed". Should it be instead "Court Date/Report info *should clear*" once date has passed"?

**Comment by big-meel** [comment]
I would like to work on this

**Comment by big-meel** [comment]
Hey, Is here the best channel to ask questions or is the slack channel?

**Comment by compwron** [comment]
@big-meel yep, #casa channel is us :)

**Comment by big-meel** [comment]
Excellent, Thank you

**Comment by big-meel** [comment]
Hey i created the method for this, to "clear" the dates when they are passed so just a quick question

the bit about adding it to past_due_dates which i can see hasn't been implemented just yet, will that be an attribute that stores the dates or a model for itself as being discussed in #805 ?

**Comment by compwron** [comment]
@big-meel Yes, showing `past_due_dates` does require having the model `past_court_dates` (or similar name) which will be created by https://github.com/rubyforgood/casa/issues/805 but this issue doesn't need that model to exist

**Comment by big-meel** [comment]
@compwron Ok thanks. In that case then I will submit the PR soon.

**Comment by big-meel** [comment]
@compwron Added the PR. Let me know how it looks :)
