### ISSUE TITLE
court report submission status updates automatically

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#882]
Part of epic #880 // dependent on #619 

**What type of user is this for? [volunteer/supervisor/admin/all or All CASA Admin]**
all

**Where does/should this occur?**
On the CASA Case details page next to text "Court Report Submission".

**Description**
After checking the box next to "Court Report Submission" on the Edit CASA Case page, the status associated with the Court Report Submission should update to: `submitted`. 

**Acceptance criteria**
IF the checkbox next to `court_report_submission` is checked, THEN the status of `court_report_submission` is `submitted`.

**Comment by SMJ289** [comment]
I am working on adding this feature for Hacktoberfest!
