### ISSUE TITLE
Duplication of Contact Type Group

### ISSUE THREAD

**Issue by exgin** [rubyforgood/casa#883]
**What is the problem, and what should happen instead?**
When creating a new group on the Manage Contact Type Form.

Link to Form: 
https://casa-qa.herokuapp.com/casa_orgs/2/edit

We should only have one unique group. When there is a group & one is created with the same name, we should see an error or popup. 

**Screenshots of current behavior, if any**
![casa_bug2](https://user-images.githubusercontent.com/59214236/94382307-30811a00-010a-11eb-9a2a-5505c5181a29.JPG)

**Comment by compwron** [comment]
@exgin how is it going? You got this! :)

**Comment by exgin** [comment]
Hey! I'm still here working on the issue, it's been a slug getting famaliar with the code base. I have a side ruby on rails application I'm using alongside ruby for good's so I can better understand it!

**Comment by compwron** [comment]
Very cool :)
