### ISSUE TITLE
UI: font mismatch for dropdown vs sidebar in Firefox

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#886]
**What is the problem, and what should happen instead?**
UI: font mismatch for dropdown vs sidebar in Firefox
In QA on 27 Sept 2020

**Screenshots of current behavior, if any**
![issue](https://files.slack.com/files-pri/T04PM108C-F01BNT5BJF6/screen_shot_2020-09-27_at_5.16.34_pm.png)
<img width="376" alt="Screen Shot 2020-09-27 at 5 16 34 PM (1)" src="https://user-images.githubusercontent.com/578159/94490999-31628c00-019c-11eb-957d-0e41aa957ac9.png">

**Comment by drborges** [comment]
@compwron I can tackle this.
