### ISSUE TITLE
create qa env in webpacker.yml

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#889]
➜  casa git:(master) heroku run rails c --app casa-qa
Running rails c on ⬢ casa-qa... up, run.2537 (Hobby)
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

W, [2020-09-29T02:24:14.300927 #4]  WARN -- Skylight: [SKYLIGHT] [4.3.1] You are running in the qa environment but haven't added it to config.skylight.environments, so no data will be sent to Skylight servers.
RAILS_ENV=qa environment is not defined in config/webpacker.yml, falling back to production environment

**Comment by Garbar** [comment]
Is QA environment in settings like production?
Do we need to add config/environments/qa.rb, the block in config/webpacker.yml, and config/webpack/qa.js files?

**Comment by littleforest** [comment]
@Garbar i am going to work on unifying the environments in #895 (so staging, qa use “production” environment and we distinguish them with flags instead), so I don’t think we will need this ultimately.

**Comment by littleforest** [comment]
Closing this since will be unnecessary after #895 .
