### ISSUE TITLE
[BUG] saving case contact in QA

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#892]
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1601480577084100
BugsnagAPP  8:42 AM
New unhandled error in qa from casa in case_contacts#create (details)
Unhandled error
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "miles_driven" violates not-null constraint
DETAIL:  Failing row contains (925, 109, 101, 30, 2020-09-30 00:00:00, 2020-09-30 15:42:54.977362, 2020-09-30 15:42:54.977362, f, text/email, null, null, f, ).
Location
app/controllers/case_contacts_controller.rb:51 - block in create

**Comment by littleforest** [comment]
For some reason migration `20200917175655_add_default_value_to_case_contact_miles_driven.rb` had not run on QA. We ran the migration manually: `rake db:migrate:redo VERSION=20200917175655`.
