### ISSUE TITLE
Update readme with QA env info

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#893]

**Comment by talentedunicorn** [comment]
@Zrrrpy can I give this a shot?

**Comment by compwron** [comment]
I did this in https://github.com/rubyforgood/casa/pull/951

**Comment by compwron** [comment]
Whoops sorry I didn't intend to edit this. All yours!

**Comment by talentedunicorn** [comment]
@Zrrrpy what QA information should be added to README? My assumption is 

- Staging URLs
- login details

Does this cover the use case? Thanks

**Comment by compwron** [comment]
@talentedunicorn yep sounds good! :) You can use the "Staging" section as an example to follow :)
