### ISSUE TITLE
Add report filters to frontend

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#894]
Part of epic #529 // related to #662

**What type of user is this for?** [admin/volunteer/supervisor/all or All CASA Admin]
admins and supervisors

**Where does/should this occur?**
On the Generate Reports page.

**Screenshot**
<img width="1331" alt="Screen Shot 2020-09-30 at 6 57 19 PM" src="https://user-images.githubusercontent.com/62810851/94757371-eccb2200-034e-11eb-9390-3a4c43373df5.png">

**How to access**
<a href="https://casa-qa.herokuapp.com/reports">Log in to QA</a> as an admin or supervisor using the following credentials:
casa_admin1@example.com OR supervisor1@example.com
pw: 123456

**Description**
[NOTE: With exception to `contact_type_group`, this work is _complete_ on the backend. This now needs to be implemented on the **frontend**.] 
In addition to "starting from" and "end date" filters for reports, users should be able to filter by any combination of the following:
- [ ] Assigned to supervisors (choose from multi-select dropdown)
- [ ] Volunteers a.k.a created_by (choose from multi-select dropdown)
- [ ] Contact type (choose from multi-select dropdown)
- [ ] `contact_type_group` (choose from multi-select dropdown)
- [ ] Wants driving reimbursement (two checkboxes: yes / no)
- [ ] Contact made (two checkboxes: yes / no)
- [ ] Transition aged youth (two checkboxes: yes/no)

**Comment by matisnape** [comment]
Hi, does it involve JS or is it simply Rails views?

**Comment by jimnanney** [comment]
Simply rails views, not even using filterriffic.

**Comment by matisnape** [comment]
OK, I'll take this over :)

**Comment by compwron** [comment]
How is this going? :)

**Comment by matisnape** [comment]
@compwron Pardon me, but I don't see the backend code for those filters on master. I think it's here https://github.com/rubyforgood/casa/compare/add-report-filters-894 but there's also frontend done here, so I'm a little confused. Shall I work from this branch?

**Comment by jmkoni** [comment]
@jimnanney @pollygee  are y’all working on this? Or should we unassign?

**Comment by jimnanney** [comment]
@jmknoi Still working on it. Will get branch and PR pushed up today or tomorrow. Had previous branch that needed more tests.

But after discussion we are going to convert to use 3 radio buttons instead of 3 checkboxes, will have those up in next push.

**Comment by jimnanney** [comment]
@jmkoni I've pushed up the latest, but the linters and standardrb don't pass due to things on master. Should I add fixes for the linter issues on master in this branch or make a PR with it as is?

**Comment by jmkoni** [comment]
@jimnanney we don’t block based on linting, just test failures, so go for it!

**Comment by jimnanney** [comment]
After rebase, tests are failing, gotta track that down. sorry for delay getting this up.
