### ISSUE TITLE
unify envs

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#895]
**What type of user is this for? volunteer/supervisor/admin/all**
don't use non-production.rb files for diff envs, to avoid making duplicate changes and catching them. 

**Description**
Make sure no one can send mail from staging environment.

**Comment by littleforest** [comment]
@compwron you mentioned that emails should not go out on staging, but I'm not seeing anywhere in the [configuration file](https://github.com/rubyforgood/casa/blob/master/config/environments/staging.rb) nor in the code that prohibits that. Can you point me where that would be? Or were you saying that feature needs to be set up?

**Comment by compwron** [comment]
@littleforest yes, I meant "should" as in "the way I want it to be" not as in "the way I believe it currently is" sorry for the confusion.

**Comment by littleforest** [comment]
@compwron thanks! I'm not seeing any differences in configuration between staging and production currently -- would that be the only change? Also, I'm assuming QA should be able to send emails?

**Comment by compwron** [comment]
@littleforest agreed, staging and prod are intended to be the same right now. QA currently does not have API keys for sending emails set up in heroku (intentionally, to prevent spam risk) but it is ok to have the rails configurations assume that sending emails ok
