### ISSUE TITLE
remove ability to edit transition_aged_youth

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#896]
**Description**
Previously, it was up to users to mark a `casa_case` as `transition_aged_youth`. After #831 is done, this will be automated. So users no longer need the ability to edit this manually. This change should be made on the frontend _and_ the backend so that there is only one trigger that changes `transition_aged_youth` from `false` to `true`. 

**Where does/should this occur?**
On the Edit CASA Case page accessible by all users. (<a href="https://casa-qa.herokuapp.com/casa_cases/152/edit">Here is an example</a>. Login using: email - supervisor1@example.com // pw: 123456)

**How is it working now?**
All users can change `transition_aged_youth` from `false` to `true` and vice versa. 

**How should it work instead?**
No user should have the ability to adjust `transition_aged_youth` status for any `casa_case`.

**Comment by rafaeelaudibert** [comment]
Hello! Im taking a go on this! Awesome project btw
