### ISSUE TITLE
Integrate Cypress with Travis CI

### ISSUE THREAD

**Issue by duaimei** [rubyforgood/casa#898]
**What type of user is this for? volunteer/supervisor/admin/all**
developer

**Description**
Tests that aren't in CI don't exist. 

Documentation is here:
https://docs.cypress.io/guides/guides/continuous-integration.html#Examples

An example configuration file is:
https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml

This is sort of dependent of issue 82 being merged in, which is the basic implementation.

**Comment by compwron** [comment]
This is working! :)
