### ISSUE TITLE
change volunteer assignment

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#91]
part of epic #4 (Admin dashboard)

In "edit volunteer" view, admins should see: 

- a dropdown menu labeled "assign new case." 
- Dropdown menu displays all cases sorted by `case_number` 
- Unassigned cases display at the top and assigned cases at the bottom. 

- a button that says "assign"
- button triggers new `case_assignment`

<a href="https://casa-r4g-staging.herokuapp.com/volunteers/6/edit">This is the edit volunteer page on staging (it is currently empty).</a>

**Comment by compwron** [comment]
Closing because this is a duplicate of #92
