### ISSUE TITLE
Schedule job created in #831

### ISSUE THREAD

**Issue by jmkoni** [rubyforgood/casa#919]
After #831 is completed, need to actually add heroku scheduler to each environment and schedule the job (daily). No code change is needed for this, it's all in heroku.

Schedule on:
- [x] casa-qa
- [ ] casa-staging
- [ ] casa-production

**Comment by jmkoni** [comment]
Scheduled on casa-qa.

**Comment by compwron** [comment]
@jmkoni the code for this is in staging and prod now, I think you have permissions to finish it when you have time :)

**Comment by compwron** [comment]
@jmkoni does this still need work?

**Comment by compwron** [comment]
I am closing this because it is done
