### ISSUE TITLE
volunteers can generate court report for transition aged youth

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#922]
Part of epic #880 // relates to #923 

AS a **volunteer**,
I can generate a court report that auto-fills with select details,
SO that I can fill out remaining details after downloading and submit it to my supervisor.

**Court Report for transition aged youth should look like this**
[Example of a CASA Report.docx](https://github.com/rubyforgood/casa/files/5322243/Example.of.a.CASA.Report.docx)

**Court Report Fields for `Transition_Aged_Youth`** _as they should appear_ (Italicized text is helper text the volunteer will need to manually delete before submitting. All information that should be automatically filled when the report is generated appears in [brackets].)
- Date Written: [`date` the report is generated]
- Hearing Date: [`court_report_date`]
- Respondent: 
- Case #: [`casa_case`] 
- DOB: [`birth_month_year_youth`]
- Persons Interviewed Regarding the Situation:
- Name // Title/Relationship // Contact Dates (should display as headers in a single row – underneath each header, the below details related to all `case_contacts` that occurred since the previous `court_report_date` show)
[one `case_contact_contact_type` should display per row under "Title" column] 
[one `occurred_at` `date` should display per row under "Contact Dates" column]
- Situation: _Leave blank, your supervisor will fill this section out._
- Objective Information: _Summarize factual information gathered from your contacts. Just the Facts! Your fact-based opinions come later! Indicate sources and dates from school personnel, physicians, psychological reports, psychiatric repots, etc. (For example: This CASA spoke with Ms. Teacher on January 12, 2009. Ms. Teacher stated…)   After each sentence if someone asked “says who?” the answer should be “Jordy, Mom, DSS, school, foster parents, my eyes”.  The answer should not be “the CASA volunteer thinks so”._ 
- Placement: 
_Where is the child placed?_  
_How is the child adjusting to the placement?_  
_Are there any issues or concerns at this point in time at the placement?_  
_If so, what are they and who is doing what to address those issues or concerns?_
- Education/Vocation:
_Where is the child placed for education (public school, non-public school, GED, JobCorps, etc)?_  
_How is the child adjusting to the placement?_  
_Are there any concerns at this point in time?_  
_If so, what are they and who is doing what to address those concerns?_  
_Does this child have any IEP? if not, is there a need for one?_ 
_How are the child’s grades/behaviors? Any concerns or additional support needed (tutoring, etc)?_
_What are the child’s post-secondary plans/goals? Is there an interest in going to college or a vocational program?_
_Do they need to prepare to take the PSAT’s, SAT’s, or ACTs?_
_Do they need assistance with college applications, going on college/vocational program tours, or filing for financial aid?_
- Health/Mental Health:
_Is the child up to date with medical exams?_ 
_Are there any other medical concerns?_
_Is the child receiving therapy, medication monitoring, mentoring, other therapeutic services?_ 
_If so, with whom?_  
_What do the professionals (who are providing these services) say about the child's progress?_
- Family/Community Connections:
_Is this child seeing parents, siblings, other relatives?_  
_If so, who is the child visiting, and how often? Any concerns?_ 
_If there is no visitation, why is it not happening?_
- Post Emancipation Planning:
_Is the child employed? If so, where? If not, are they looking for a job?_
_Does the child have any vocational/life skills?_ 
_Are they attending life skill classes?_
_Do they have any other life skills needs? (transportation assistance, clothing voucher, etc.)_
_What sources of income does the youth currently have (allowance, job, SILA, etc.)?_
_Does the youth have a bank account in good standing?_
_Has the youth had their credit report checked?_ 
_Does the youth understand the basics of money-management?_
_Does the youth have permanent family and/or adult connections?_
_Who does the youth identify as the people with whom he/she could turn to in a crisis?_ 
_Is the youth connected to desired community activities?_
_Does the youth have all identifying documents, i.e., birth certificate, social security card, driver’s license or state ID?_
_Are there any outstanding criminal or delinquency cases for the youth?_
_Is the youth a U.S. citizen? If not, has AYUDA been contacted?_
_Has the youth identified their core values?_
_Where does the youth see themselves after emancipation?_
- Permanency Plan: 
_What is the child's permanency plan? Give a summary of the actions taken to achieve it._
- Assessment: 
_This section should provide information that leads to your recommendations, but be based on the objective information included in the section above._  
_Describe how the child is doing. Include a statement about the CASA’s role in the child’s life. Describe the relationship the CASA and the child currently have._
_What are the current concerns for the child? Is there a need that is not being met?_  
_You are presenting your opinion about the case (using factual information). For example: Family therapy is currently not in place. It is important that this service begins because…_
_One paragraph should be dedicated to each concern. 
What is your recommendation on a service or a plan to meet this need?_ 
_Restate the permanency plan. 
Is this the most appropriate plan at this time?  Describe why or why not._ 
_If there is another plan that may be better, offer a recommendation for that plan and describe why and how to achieve this plan._ 
- Recommendations:
_Therefore, CASA respectfully recommends:_ 
_1.  Ben Price remains in the care and custody of the Department of Social Services/his mother/etc;_ 
_2.  Something else;_
_3.  Something else; and_
_4. CASA is continued._ 
- (( space for signature ))
- [`volunteer_display_name`]
- Court Appointed Special Advocate
- Appointed: [`case_assignment` `created_at` date]
- (( space for signature ))
- [`supervisor_volunteer` `display_name`]
- CASA Case Supervisor

**Acceptance criteria:**
- [ ] Volunteer can select which `casa_case` they are generating a court report for. 
- [ ] Their selection determines which court report type is generated (if `transition_aged_youth` is `TRUE` then court report for transition aged youth is generated, if `transition_aged_youth` is `FALSE` then court report for non-transition aged youth is generated)
- [ ] Their selection also determines which `casa_case` the auto filled data should be associated with.
- [ ] When volunteer clicks button "Generate Report", a court report is generated based off of the above requirements, and text: _Court report generating. Do not refresh or leave this page_ appears.
- [ ] When court report finishes generating, a button to "Download Court Report" appears.
- [ ] Clicking the button downloads the court report as a .docx

**Comment by jmkoni** [comment]
@erik-trantt it seems I can’t assign you unless you comment in the issue

**Comment by jmkoni** [comment]
@erik-trantt it seems I can’t assign you unless you comment in the issue

**Comment by erik-trantt** [comment]
Hi @jmkoni, thank you. I didnt know that we need to comment first to get assign. I'll take this issue.

**Comment by jmkoni** [comment]
@erik-trantt it's just an oddity about Github 🤷‍♀️ I can assign it to you if you've commented *or* if you are part of the org. Either way... assigned!

**Comment by erik-trantt** [comment]
> * Name // Title/Relationship // Contact Dates (should display as headers in a single row – underneath each header, the below details related to all `case_contacts` that occurred since the previous `court_report_date` show)
>   [one `contact_type` should display per row under "Title" column]
>   [one `occurred_at` `date` should display per row under "Contact Dates" column]

---
### Contact tables
![image](https://user-images.githubusercontent.com/44339322/95756431-7dabe100-0cf1-11eb-8b3a-354eb2d9b92c.png)
---

@Zrrrpy I have some questions regarding the format of the template:
- For name of contacts, which field should I use?
- For `contact_type`, can there be 2 or more contacts for a type?
- For **Indicates attempted contacts**, which field represents this? 

Thanks!

**Comment by compwron** [comment]
@erik-trantt 
Hi! I'm not @Zrrrpy but I can give it a try 
1. name of contacts - this model is not in the db yet. I recommend adding a placeholder value 
1. `contact_type` assume there can be 2 or more contacts for a type (but contacts don't exist in the db yet- are you thinking of `case_contact`? There will be many `case_contacts` per case with the same type because, for example, the volunteer will talk to the youth many times. 
1. **Indicates attempted contacts** - this comes from a `case_contact` with column `contact_made` having value false

**Comment by erik-trantt** [comment]
Thanks @compwron. It's taking a while to dig into the models. I'm now more clear about 1 & 3.

2. For `contact_type`, your explanation totally makes sense to me. My understanding is, the table lists the persons relating to the case with their relationship to the youth and dates they are contacted.

For example, 2 volunteers work together with the youth, so in this reports, each of them will appear as seperate record. Would that be correct?

Also, when creating a `case_contact`, I notice that:
- `case_contact`.`contact_types` is nil, while 
- `case_contact`.`case_contact_contact_type` holds the selected `contact_type`s

I am confused as I assume those 2 fields are the same?

**Comment by Zrrrpy** [comment]
sorry to jump in late here, @erik-trantt! Thank you for picking up this big ticket. :) 

We will likely never be adding names corresponding with `case_contact_contact_type` to the platform, for privacy reasons. Even though names are included in the example court report, they will not be generated with names, but rather with `case_contact_contact_type`s, in place of names. 

For 2 re: `contact_type`: Yes. A volunteer can make multiple `case_contacts` associated with one `case_contact_contact_type`s on different dates. It would be preferable to dedicate one row to each `contact_type` and to list all the dates associated with those `case_contacts` in one single row on the report.

Let me know if you have any follow up questions about this!
