### ISSUE TITLE
Add route to "Generate Court Report" to sidebar

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#923]
Part of epic #880 // dependent on #922 

AS a volunteer, 
I want to click "Generate Court Report" in the left sidebar,
so that I can select the `casa_case` I am generating a court report for, and then generate and download said report.

**Acceptance Criteria**
- [ ] Text: "Generate Court Report" displays in left sidebar.
- [ ] "Generate Court Report" is clickable.
- [ ] When clicked, "Generate Court Report" form displays in container (the same way all other forms appear on platform).

**Comment by erik-trantt** [comment]
Hi @Zrrrpy, I've recently joined Hacktoberfest and I'd love to work on this one. Is it still available? If yes, is there anything to look out for? Thanks.

**Comment by Zrrrpy** [comment]
Hi @erik-trantt, it is! Please first familiarize yourself with the epic this is a part of, #880, and be sure to check on the status of #922.

**Comment by erik-trantt** [comment]
@Zrrrpy Thanks for the advice 😄. I got a general idea about epic #880 and what should be built for #922 & #923. I can't find a way to assign myself to the issues. Can you help me with that? Thanks.

**Comment by erik-trantt** [comment]
@Zrrrpy  Can Admins & Supervisors also see the "Generate Court Report" link? Or just the Volunteers?

**Comment by compwron** [comment]
@erik-trantt In general, anything that volunteers can see, supervisors and admins should also be able to see.
