### ISSUE TITLE
Database migration test

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#926]
This test/s should run *all* migrations against a newly created database schema, and should also test the code in *all* `after_party` tasks. The purpose of this is to protect against issues like the one explained below, where a migration including data changes stopped working because of new code changes and is therefore blocking prod deployment.
https://rubyforgood.slack.com/archives/CVB0QJGVD/p1601763571083900

There is no one right way to do this. Anything you make up that works, is good. 
1. runs relatively quickly (rough guide: less than 60 seconds maximum)
1. can run locally on osx or docker without breaking the developer's development database
1. runs and passes on travisCI
1. catches errors like below

> Hello, I'm running into such a weird issue; and I've been troubleshooting for quite a while so I'm probably calling it a night, but has anyone else run into issues with trying to run the migrations?  Specifically, we have a few files in `db/migrate` that populate tables with data.  The migrations run and create the schema, but (in the example I linked above) the ContactTypes are not being created.  I have searched high and low and am quite puzzled.  I need this specific info/data because I'll be adding new contact types to groups.

> I'm running the app in a docker container and have tried resetting the db, breaking down the entire container and starting from scratch, manually triggering the migration files individually, and looking into the annotate gem (though haven't fully ruled this being part of the problem).  Any help is greatly appreciated and apologies if I don't respond this evening!

> The solution to the above was that the meaning of `case_contact.contact_types` has changed over time from a column on `case_contact` to a relationship with table `contact_type` via join table `case_contact_contact_type` and the data backfill in the migration migration was correct when it was merged but no longer works because of these code changes. Roxanne will fix it as part of ongoing work. This is a blocker for deploying code currently in QA to prod. I have also made a new issue for adding a new kind of test for migrations to protect us from this type of issue in the future.

Resources/ideas:

https://medium.com/@xevix/activerecord-migration-testing-624aada9d276
https://github.com/xevix/activerecord_migration_testing_example
https://spin.atomicobject.com/2016/08/17/ruby-on-rails-data-migration/
https://blog.carbonfive.com/start-testing-your-migrations-right-now/
https://docs.gitlab.com/ee/development/testing_guide/testing_migrations_guide.html
https://gist.github.com/peter/700194
https://nebulab.it/blog/testing-ruby-on-rails-migrations/

**Comment by keithrbennett** [comment]
When you say "This test/s should run all migrations against a newly created database _schema_", do you mean to say a newly created database? The schema would not yet be know to the DB before the migrations, right?

**Comment by compwron** [comment]
@keithrbennett can you clarify the question? 
To restate, the new test should run all the migration against an empty schema (the schema exists has no tables) or any equivalent behavior which can provably catch errors where migrations no longer work.

**Comment by keithrbennett** [comment]
Ok, I think _empty_ schema clarifies it for me. So _empty_ schema means that the database has been created but neither schema.rb nor the migrations have been run yet, right?

**Comment by compwron** [comment]
@keithrbennett exactly. But again the point is to make sure that migrations which have been run in qa but not yet in prod keep working long enough to get to prod! And also to make sure that new developers are able to run migrations without having issues :)

**Comment by roxannecojocariu** [comment]
@compwron I'm wondering now if this is still necessary.  We've now added all migrations that populated data as after_party tasks which are run in CI.

**Comment by compwron** [comment]
I would still very much like this. There will always be new migrations.

**Comment by compwron** [comment]
Closing for now, we are using strong_migrations instead
