### ISSUE TITLE
supervisors and admins can associate judge_name and hearing_type with next court_date

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#927]
Part of epic #880 

AS a supervisor or admin, 
I want to be able to associate a `court_date` with a `judge_name` and `hearing_type`,
so that `judge_name` and `hearing_type` display along with a volunteer's next `court_date` associated with a `casa_case` they are assigned to.

**Acceptance criteria**
- [ ] Supervisors and admins can select a `hearing_type` to associate with a `court_date` from a dropdown menu (or similar alternative)
- [ ] Supervisors and admins can select a `judge_name` to associate with a `court_date` from a dropdown menu 
- [ ] `judge_name` and `hearing_type` display along with next `court_date` on its associated `casa_case` for all users.

**Comment by haydenrou** [comment]
I'd like to pick this up please, but I do not have permissions to assign it to myself.

**Comment by compwron** [comment]
@haydenrou All yours :)

**Comment by compwron** [comment]
Resolved by #1000

**Comment by Zrrrpy** [comment]
#1000 lays the foundation work for this issue (gives admins the ability to create and customize `hearing_types` for their organization), but does not complete it. See acceptance criteria above @haydenrou and @compwron.

**Comment by haydenrou** [comment]
As mentioned in #1000 , that was just to address #928 - I will do this in a separate PR.

**Comment by Zrrrpy** [comment]
Thanks @haydenrou! Moved this back to In Progress so that PR can be linked to this issue. :)

**Comment by haydenrou** [comment]
Waiting for #929 before submitting a PR for the second half of this.
