### ISSUE TITLE
admins can customize hearing_types per casa_org

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#928]
Part of epic #880

AS an **admin**, 
I want to add/edit/show/hide `hearing_types` specific to my `casa_org`, 
so that only relevant `hearing_types` display for users within my organization. 

**Where does/should this occur?**
Under "Edit Organization" 

**How to access in QA**
<a href="https://casa-qa.herokuapp.com/casa_orgs/2/edit">Log in to QA</a> with the following credentials:
email: casa_admin1@example.com
password: 123456

**Acceptance Criteria**
- [ ] On the Edit CASA Organization page, there is a section called "Manage Court Details" (check to make sure this has not already been handled by #929)
In this section, an admin can: 
- [ ] create new `hearing_types`
- [ ] edit existing `hearing_types`
- [ ] hide `hearing_types`
- [ ] view hidden `hearing_types`
- [ ] show hidden `hearing_types`
- [ ] changes admins make here are reflected in `hearing_types` available to `supervisors`

**Comment by haydenrou** [comment]
I'd like to pick this up please, but I do not have permissions to assign it to myself.

**Comment by compwron** [comment]
@haydenrou It's yours! :)

**Comment by acrosman** [comment]
From a quick look it might be helpful to seed the table with the Maryland types:

- emergency hearing 
- trial on the merits 
- scheduling conference
- uncontested hearing
- pendente lite hearing
- pretrial conference
- other:

Source: https://www.courts.state.md.us/sites/default/files/court-forms/family/forms/ccdr059.pdf/ccdr059.pdf

**Comment by compwron** [comment]
@acrosman Thanks for the great info! This seems reasonable. 
@haydenrou if you add those `hearing_type`s please put them in the seed files in `seeds/qa` etc 
If we want to also pre-populate these in prod, it should be added as an idempotent `after_party` https://github.com/theSteveMitchell/after_party task in addition to being in the seeds file (instead of a rake task or data update inside a db migration) :)

**Comment by compwron** [comment]
@acrosman If you haven't already joined us in slack at https://rubyforgood.herokuapp.com/ in the #casa channel, we'd love to hear more of your insights! We also have office hours Weds 6-8pm pacific time (Zoom link in slack or I can DM it to you somehow if you prefer)

**Comment by Zrrrpy** [comment]
PG CASA got back to me about this today; `hearing_types` are actually not applicable to them at all, as PG County does not distinguish between the two most common types of hearings in their state: Permanency Planning and Review Hearings.

That being said, I'd actually like the default hearing types to be as broadly applicable as possible. So instead of going by what's most common in Maryland, we should identify the most common hearing types that occur across the U.S. (@acrosman for reference, this is a multitenant application, PG CASA is just the first chapter on the platform.)

**Comment by acrosman** [comment]
I don't need to be right here, and certainly not trying to tell PG county their business, just trying to offer up what I know/can find and offer. When I go to court in SC we need to know the hearing type, if for no other reason it is a required line in the court report (and things like a TPR and Merits are handled very differently). As in Maryland my experience here is that PP and Judicial Review/Review Hearings are also by far the most common and they are more or less interchangeable for us. 

I understand that this is envisioned as multitenant with PG going first. As this project comes together I'd love to see it adopted here as we're in great need of better tools – but I have more or less zero influence on that front.

I'm in the slack channel (see the person who joined the casa channel Saturday). I will try to join office hours when I'm able to learn more than to share.

**Comment by haydenrou** [comment]
@Zrrrpy please could you elaborate on hiding hearing types? Is this a flag they can turn on and off? Should it be default scoped? 
What do you mean by showing/hiding them?

Also regarding the last point, do you want me to show the paper trail versions in a table on the hearing types edit page or did you have something else in mind?

**Comment by Zrrrpy** [comment]
@haydenrou we've got a good use case in QA for showing/hiding `contact_types` that you can reference for an example of how this should be handling. 

[Log in to QA](https://casa-qa.herokuapp.com/) here with the following credentials:
email: casa_admin1@example.com
password: 123456

[and then go to this page](https://casa-qa.herokuapp.com/contact_type_groups/1/edit)

You can also access by going to "Edit Organization" in the left side bar
and then editing any `contact_type` or `contact_type_group`

**Comment by Zrrrpy** [comment]
@acrosman it'd be great if you could join our open office hours tomorrow to discuss! details pinned in the #casa slack channel 😀

**Comment by haydenrou** [comment]
#1000 has done the A/C above for this issue, however the aforementioned seeding of hearing types need to be done in another PR. Up to you if you want to re-open this or open a new issue to address that @Zrrrpy

**Comment by Zrrrpy** [comment]
This one can stay closed @haydenrou - feel free to add a new issue to link the seeding PR to.
