### ISSUE TITLE
admins can customize judge_names per casa_org

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#929]
Part of epic #880

AS an **admin**, 
I want to add/edit/show/hide `judge_names` specific to my `casa_org`, 
so that only relevant `judge_names` display for users within my organization. 

**Where does/should this occur?**
Under "Edit Organization" 

**How to access in QA**
<a href="https://casa-qa.herokuapp.com/casa_orgs/2/edit">Log in to QA</a> with the following credentials:
email: casa_admin1@example.com
password: 123456

**Acceptance Criteria**
- [ ] On the Edit CASA Organization page, there is a section called "Manage Court Details" (check to make sure this was not already handled by #928)
In this section, an admin can: 
- [ ] create new `judge_names`
- [ ] edit existing `judge_names`
- [ ] hide `judge_names`
- [ ] view hidden `judge_names`
- [ ] show hidden `judge_names`

**Comment by matisnape** [comment]
@Zrrrpy 
1) How would you like the hiding work? Should it happen on edit judge or from the list of judges in the table (button in Actions column)?
2) How the judges are relevant to `hearing_types` and where can I find this view?

**Comment by jmkoni** [comment]
@matisnape hey, make sure to only claim one story at a time. you are currently assigned to one and sorta claiming two more.

**Comment by matisnape** [comment]
@jmkoni sure, I'm just collecting additional info :)

**Comment by khiga8** [comment]
Hi! Can I claim this issue? :-)

**Comment by khiga8** [comment]
Hey! I'm imagining this implementation will be very similar to Hearing types [here](https://github.com/rubyforgood/casa/pull/1000/files). 

I am thinking I'll need to introduce a `JudgeName` model that `belongs_to` `:casa_org` .
Besides a name column, do we need anything else?  

I'm a little confused about the last point: 
`changes admins make here are reflected in hearing_types available to supervisors`

**Comment by compwron** [comment]
@khiga8 that matches what I am thinking. I am also a little confused about `changes admins make here are reflected in hearing_types available to supervisors` 
@Zrrrpy can you elaborate? :)

**Comment by Zrrrpy** [comment]
just removed that line from the acceptance criteria. Apologies for the confusion!

**Comment by Zrrrpy** [comment]
@khiga8 active / inactive status would be great. This will allow admins to show/hide judges :)
