### ISSUE TITLE
populate_prince_george_casa_org_details.rake should work even if with no data in the db 

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#930]
Fix populate_prince_george_casa_org_details.rake to work even if there is no data in the db (create_or_update) AND make extra sure it won't mess up prod...

**Comment by Zrrrpy** [comment]
@compwron add more details if you have any!

**Comment by compwron** [comment]
because this is assigned, I will move it into "in progress" on the board.
