### ISSUE TITLE
search presets and results should clear after a page is loaded

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#932]
AS a **supervisor** or **admin**,
WHEN I search within Volunteers,
my search history should clear after I navigate away from that view,
SO that I don't get confused by limited results when I eventually return to the Volunteer view.

**Where does/should this occur**
In the <a href="https://casa-qa.herokuapp.com/volunteers">Volunteer view</a> accessible by admins and supervisors. 

**How to access QA**
<a href="https://casa-qa.herokuapp.com/volunteers">Log into QA</a> using the following credentials:
email: supervisor1@example.com OR casa_admin1@example.com
password: 123456

**How it works now**
Search presets and results in the Volunteer view _do not_ clear after a user navigates away from it.

**How it should work**
Search presets and results in the Volunteer view _should_ clear after a user navigates away from it.

**Comment by Mozart2234** [comment]
I'm working in this issue.

**Comment by compwron** [comment]
Found issue https://github.com/rubyforgood/casa/issues/953 while testing this.
