### ISSUE TITLE
only volunteers assigned to supervisor should display by default

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#933]
AS a **supervisor**,
I WANT to only see volunteers assigned to me by default when I log in,
SO that I can focus on my `supervisor_volunteer` assignments.

**Where does/should this occur?**
In the <a href="https://casa-qa.herokuapp.com/volunteers">Volunteer view.</a>

**How to access in QA**
<a href="https://casa-qa.herokuapp.com/">Log in to QA</a> using the following credentials:
email: supervisor1@example.com
password: 123456

**How does it work now?**
When I log in to QA as a supervisor, my default volunteer view contains volunteers assigned to all supervisors. 

**How should it work instead?**
When I log in to QA as a supervisor, I want my default volunteer view to contain only volunteers assigned to me. (I can always filter by volunteers assigned to other supervisors if I want to see them.)
_This works the way it's supposed to (for the most part) in staging already. I'm not sure what's causing it to misbehave in QA._

**Comment by cdncat** [comment]
can I try to help with this issue?

**Comment by metamoni** [comment]
@cdncat have you started working on this? I have a fix for it or I can help if you're stuck.

**Comment by Mozart2234** [comment]
:( Just now,  I'm passing the final tests.

**Comment by cdncat** [comment]
👋 
I'm actually pretty new to Ruby so not too sure if the PR https://github.com/rubyforgood/casa/pull/938 is sufficient
Feel free to close or modify the PR!

**Comment by Mozart2234** [comment]
Wow, I really didn't understand the issue.

**Comment by compwron** [comment]
@Mozart2234 @cdncat in the future when you are working on an issue, please make it clear you are working on the issue by leaving a comment like "I am working on this" so that other contributors don't see it as an available issue and work on it also :)

**Comment by cdncat** [comment]
I believe the code change in #938 is correct since I've verified via manual testing--but wasn't able to get the new ruby spec test up and running. I've closed the PR as I don't have much time upcoming to work on it--anyone is free to take this ticket!

**Comment by metamoni** [comment]
I'll take a look at this issue

**Comment by jmkoni** [comment]
@metamoni feel free to look at @cdncat's closed PR. I think they got close.

**Comment by maycowmeira** [comment]
@Zrrrpy I would like to create PR for this Issue, how can I do that?

**Comment by compwron** [comment]
@maycowmeira Please choose a different issue because this issue is assigned to @metamoni

**Comment by metamoni** [comment]
@maycowmeira if you already have a branch with a working fix I can hand it over to you. I haven't gotten too far with it yet.
