### ISSUE TITLE
create volunteer view filter for volunteers without a supervisor

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#934]
AS a **supervisor** or **admin**,
I WANT the ability to filter my volunteer view by volunteers not assigned to a supervisor,
SO I can see volunteers who need supervisor assignments.

**Where does/should this occur?**
In the <a href="https://casa-qa.herokuapp.com/volunteers">Volunteer view.</a>

**How to access in QA**
<a href="https://casa-qa.herokuapp.com/">Log in to QA</a> using the following credentials:
email: supervisor1@example.com 
password: 123456

**How does it work now?**
`active` `volunteers` without a `supervisor_volunteer` assignment display along with `volunteers` assigned to the logged in `supervisor`. 
You can also view them by deselecting all `supervisors` in the "Filter by: Supervisor" dropdown menu.

**How should it work instead?**
`active` `volunteers` without a `supervisor_volunteer` assignment should only display if user filters the volunteer view by "No supervisor assignment" under "Supervisor." 

**Acceptance Criteria**
- [ ] "No supervisor assignment" is an option in the "Filter by: Supervisor" dropdown menu.
- [ ] This option displays at the top of the dropdown menu.
- [ ] Selecting this option yields the same results as deselecting all supervisor names in the dropdown menu, i.e. shows all `active` `volunteers` lacking an _active_ `supervisor_volunteer` assignment.

**Comment by metamoni** [comment]
I'd like to help with this. I'll start working on it.
