### ISSUE TITLE
Move data seeding out of migrations

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#937]
**Description**
* Move data seeding out of migrations and into after party rake task
* Run after party tasks as part of the seeds files
* Cleanup any old after party tasks

**Comment by compwron** [comment]
@littleforest please coordinate with @roxannecojocariu who is fixing up the existing data population migrations (in-place I believe) as part of needing to get her current issue for contact_types done. I don't want you to conflict with each other and not know it :)

**Comment by littleforest** [comment]
Oh perfect thanks for letting me know! @roxannecojocariu I can wait until you're done before making any other changes.
