### ISSUE TITLE
[bug] casa admin de/activating casa admin succeeds but shows an exception when email creds are missing/invalid

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#952]
https://casa-qa.herokuapp.com/casa_admins/225/deactivate

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

BugsnagAPP  2:47 PM
New unhandled error in qa from casa in casa_admins#deactivate (details)
Unhandled error
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25
Location
app/controllers/casa_admins_controller.rb:48 - deactivate

https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1601848027166900

This is probably caused by the lack of email credentials in QA. We should handle failed email creds differently:
1. do not show exception on UI
1. log error to bugsnag
1. show "email not sent" error on UI

**Comment by TecnoSigma** [comment]
Hi,

I'm solving this problem.

Can you assign issue to me?

Tks!
