### ISSUE TITLE
[bug] Error handling when email creds are not correct - creating new casa admin in qa

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#955]
This is caused by incorrect email config in qa somehow. The user is still created but the email is not sent and the user sees a UI exception on the UI. Instead we should catch the exception and show a better error on the UI. 

BugsnagAPP  2:59 PM
New unhandled error in qa from casa in casa_admins#create (details)
Unhandled error
ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
Location
app/views/devise/mailer/invitation_instructions.html.erb:15 - _app_views_devise_mailer_invitation_instructions_html_erb___2990494963078439499_35580

**Comment by littleforest** [comment]
This should get resolved with changes being made in #895 .

**Comment by compwron** [comment]
:)

**Comment by Zrrrpy** [comment]
The UI error when trying to create/save a casa admin with invalid email is fixed, but flagging that #952 is still not working and may be related
