### ISSUE TITLE
Exception when setting case_contact.miles_driven to 0 in UI. miles_driven should not be allowed negative

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#956]
**What is the problem, and what should happen instead?**
This is really 2 bugs at once but it will be easier to fix them at the same time. 
Exception when setting case_contact.miles_driven to 0 in UI. miles_driven should not be allowed negative
https://casa-qa.herokuapp.com/casa_cases/94
`rails db:migrate:redo VERSION=20200917175655` worked but this problem persists

**Screenshots of current behavior, if any**

<img width="707" alt="Screen Shot 2020-10-04 at 3 17 38 PM" src="https://user-images.githubusercontent.com/578159/95028407-edb4ca00-0654-11eb-872f-d5525e702da2.png">
<img width="1053" alt="Screen Shot 2020-10-04 at 3 17 10 PM" src="https://user-images.githubusercontent.com/578159/95028421-fe654000-0654-11eb-87f2-4040d8730ad1.png">

**Comment by Mozart2234** [comment]
I'm working on this issue.
