### ISSUE TITLE
Fix test "/dashboard as an admin GET /show doesn't show other organizations' cases"

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#961]
The text is currently not running. Get a test for this functionality running.

this test is in `dashboard_spec.rb`

**Comment by maycowmeira** [comment]
@compwron There are two examples with this description, would it be the one at: `spec/system/admin_edits_a_case_spec.rb` or the one at `spec/system/volunteer_edits_case_spec.rb` ?

**Comment by maycowmeira** [comment]
@compwron I would like to make a Pull Request for this issue.

**Comment by compwron** [comment]
@maycowmeira ok this issue is yours :)
This test seems to have already been fixed so I will change this issue to be a new one.

**Comment by compwron** [comment]
@maycowmeira are you still working on this?

**Comment by maycowmeira** [comment]
> @maycowmeira are you still working on this?

Hi @compwron . I had busy week at my job and could not see it anymore. I am almost sure the other test was broken as well that day, but I check it later.
I probably will work on it this week if that is ok.

**Comment by compwron** [comment]
Sounds good :)

**Comment by Zrrrpy** [comment]
Hi @maycowmeira! How's it goin? Let us know if you're still working on this or would like it unassigned. All good either way 😄

**Comment by compwron** [comment]
I am going to unassign this due to activity for now. Feel free to pick it up again when you have time. :)

**Comment by compwron** [comment]
I am closing this because we just now reorganized the tests and I think the issue needs to be rewritten to take that into consideration.
