### ISSUE TITLE
Fix test /can_sign_in_as_all_casa_admin_spec.rb:15:    xit "allows sign out"

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#966]
The text is currently not running. Get a test for this functionality running.

**Comment by joaovitoras** [comment]
I'm solving this problem with this PR https://github.com/rubyforgood/casa/pull/979 of another problem
Can you assign issue to me?

**Comment by jmkoni** [comment]
@joaovitoras is the same change fixing all of these? otherwise, please open separate PRs.

**Comment by jmkoni** [comment]
I can assign these to you, but we would appreciate a PR per issue, unless one change fixes all.

**Comment by joaovitoras** [comment]
One change fixes all
This is a problem with capybara driver, fixing the driver i fixed all these related issues

**Comment by compwron** [comment]
very very very cool!
