### ISSUE TITLE
Fix test all_casa_admins_casa_orgs_spec.rb:93:    xit "redirects to root"

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#967]
The text is currently not running. Get a test for this functionality running.

**Comment by jmkoni** [comment]
@joaovitoras can you confirm that you are planning on fixing this issue? We generally want issues to be assigned before work is started.

**Comment by joaovitoras** [comment]
@jmkoni I opened a PR to see the behavior in the CI and understand what was actually happening
Anyway, could you assign this issue to me? I will work on it
