### ISSUE TITLE
[write test] admin or supervisor edits a case contact - fails across organizations

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#988]
The text is currently not running. Get a test for this functionality running.
` ./spec/system/admin_edits_a_case_contact_spec.rb:26`

**Comment by mateusfdl** [comment]
@compwron  I would like to make a PR for this issue.

**Comment by compwron** [comment]
@mateusfdl How is this going? Are you still working on it? Do you need help?

**Comment by compwron** [comment]
@mateusfdl because you haven't responded in a while, I am going to reassign this issue. Feel free to pick it up again if you have time!

**Comment by librod89** [comment]
I have a PR coming for this ticket shortly.
