### ISSUE TITLE
add supervisor as filter in "Volunteers view"

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#99]
part of epic #4 (admin dashboard), relates to #97, and #98 

<a href="https://casa-r4g-staging.herokuapp.com/">This issue refers to the "Volunteers" section in the admin dashboard here.</a>

In addition to filtering by _active_ and _inactive_, admins should also be able to filter volunteers by their assigned _supervisor_.

"Filter by supervisor" should open a drop down menu listing all supervisors. Admins should be able to select and filter by more than one supervisor.

**Comment by colinsoleim** [comment]
I'm currently working on this issue. I put in some work adding basic bootstrap styles and getting dropdowns set up for this issue (and #97 / #98). I just need to finish the javascript for the filter functionality. Current dashboard looks like this: 

<img width="1786" alt="Screen Shot 2020-04-17 at 9 37 22 PM" src="https://user-images.githubusercontent.com/1221519/79624985-ac0a8400-80f3-11ea-913c-38add4ccf871.png">
