### ISSUE TITLE
too big number in miles_driven on case_contact creates exception

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#990]
**What is the problem, and what should happen instead?**
too big number in miled_driven on case_contact creates exception
Instead we should have a nice js or rails (or both) validation
https://casa-qa.herokuapp.com/case_contacts/926/edit
https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1601951820231400

BugsnagAPP  7:37 PM
New unhandled error in qa from casa in case_contacts#update (details)
Unhandled error
ActiveModel::RangeError: 926413928346219834723698476348926421846312846 is out of range for ActiveModel::Type::Integer with limit 4 bytes
Location
app/models/case_contact.rb:61 - block in update_cleaning_contact_types

**Screenshots of current behavior, if any**

![Screen Shot 2020-10-05 at 7 40 23 PM](https://user-images.githubusercontent.com/578159/95152747-a278e500-0742-11eb-94d3-5ab3c2113515.png)

**Comment by NickSchimek** [comment]
So I'm having a hard time deciding on the validation message that should be displayed. It's a tie between these two:
> x miles driven? Really?!?
or
> Our technology wont allow you to drive that far. Where did you go? Mars?

**Comment by compwron** [comment]
@NickSchimek Both of those are funny and cute but I am worried that they might come off as too flippant or rude to volunteers? But maybe not? I have no idea. Anyway it's easy to change so go for it. I would choose "Our technology wont allow you to drive that far." :)

**Comment by NickSchimek** [comment]
Sorry, I can be sarcastic even when it is not appropriate. I was not planning on putting that in there.  Although `Our technology wont allow you to drive that far` seems appropriate and cute still. Sorry, I know it takes time to check these comments.

**Comment by littleforest** [comment]
Don't forget the apostrophe in "won't" 😬
