### ISSUE TITLE
db seed test

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#995]
Add a test like this

```
describe "database seeder" do
  it "runs successfully" do
    expect { ActiveRecord::Tasks::DatabaseTasks.load_seed }.not_to raise_error
  end
end
```

**Comment by kinduff** [comment]
@compwron happy to take this one

**Comment by compwron** [comment]
@kinduff Very cool! :)

**Comment by Garbar** [comment]
@compwron This's test wiil be failed with "<LoadError: cannot load such file -- .../db/seeds/test.rb" error.
We have tested development and staging seed files. Maybe we just need to add a test for QA?

**Comment by compwron** [comment]
@Garbar I think that @kinduff  is working on this
I don't want to add a test seeds file just for this test. I want the test to test all of our existing seeds files. So we should probably pass in a rails env to the test so it knows to run each seed file
