### ISSUE TITLE
Move user permission logic from erb into pundit policy files

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#996]
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
Move logic about whether a user is allowed to do something from .erb files into the appropriate pundit policy files
`<% if !current_user.supervisor?` 

Extra credit / stretch goal: write a test that fails when logic like `current_user.casa_admin?`  etc is added to an erb file (the hard part is avoiding false positives...)

**Comment by Mozart2234** [comment]
I work on this issue
